// Czech content pack. Mirrors packs/en.js key for key — see the header there.
export default {
  lang: 'cs',
  formats: {
    pdf: { about: 'PDF je formát s pevnou sazbou: ukládá přesnou polohu každého znaku, každé linky a každého obrázku, a proto vypadá stejně na jakékoli obrazovce i tiskárně, ale špatně se upravuje.', note: 'PDF zamyká stránkování, písma i sazbu, takže příjemce vidí přesně to, co jste odeslali.' },
    docx: { about: 'DOCX je moderní formát Microsoft Wordu, kde text žije v upravitelných odstavcích a stylech, místo aby byl přibitý k pevným souřadnicím na stránce.', note: 'DOCX vám vrátí skutečně upravitelné odstavce, sledování změn a komentáře ve Wordu, Dokumentech Google nebo LibreOffice.' },
    xlsx: { about: 'XLSX je tabulkový formát Excelu, kde každá hodnota sedí v adresovatelné buňce, kterou lze řadit, filtrovat a použít ve vzorci.', note: 'Jakmile jsou data v XLSX, můžete je sčítat, řadit, kontingenčně vyhodnocovat a vynášet do grafů, místo abyste je přepisovali.' },
    pptx: { about: 'PPTX ukládá prezentaci jako samostatné snímky s upravitelnými textovými poli, tvary, poznámkami řečníka a přechody.', note: 'PPTX vám vrátí snímky, které opravdu můžete znovu upravit, přeuspořádat a znovu prezentovat.' },
    txt: { about: 'Soubor TXT není nic než znaky — žádná písma, žádné obrázky, žádná struktura stránky — což ho činí drobným, čitelným všude a triviálně prohledatelným.', note: 'TXT odstraní všechno kromě slov, a přesně to chtějí skripty, vyhledávací indexy a textové editory.' },
    html: { about: 'HTML je značkovací jazyk webu: text zabalený do značek, ze kterých prohlížeč udělá nadpisy, odstavce, odkazy a obrázky.', note: 'HTML se otevře v jakémkoli prohlížeči a lze ho vložit rovnou na web nebo do redakčního systému.' },
    rtf: { about: 'RTF je otevřený dokumentový formát postavený na prostém textu, který si nese základní formátování — tučné písmo, kurzivu, písma, tabulky — aniž by vás zamkl do jediného textového editoru.', note: 'RTF se otevře ve Wordu, Pages, LibreOffice, WordPadu a téměř každém textovém editoru, který kdy vznikl.' },
    odt: { about: 'ODT je textový formát OpenDocument používaný LibreOffice a OpenOffice a je to norma ISO, nikoli formát jednoho výrobce.', note: 'ODT je nativní, plně upravitelný formát LibreOffice a OpenOffice.' },
    epub: { about: 'EPUB je formát elektronické knihy s plynulým textem: nemá pevnou velikost stránky, takže se text přesází podle obrazovky a velikosti písma, které čtenář používá.', note: 'EPUB dovolí čtenáři změnit velikost písma a nechat text přetéct, a právě to dělá dlouhé dokumenty pohodlnými na telefonu nebo čtečce.' },
    jpg: { about: 'JPG používá ztrátovou kompresi vyladěnou na fotografie: zahazuje detaily, kterých si oko všimne nejméně, což fotky zmenší, ale kolem ostrých hran a textu přidá měkké, kostkované artefakty.', note: 'JPG dává malé soubory, které se otevřou doslova všude, za cenu trvale zahozených detailů a chybějící průhlednosti.' },
    jfif: { about: 'JFIF je obrázek JPEG uložený s jinou příponou; pixely uvnitř jsou běžná data JPEG, ale Windows často odmítá soubor předat aplikaci, kterou chcete.', note: 'JFIF je ve skutečnosti jen JPEG pod jiným jménem.' },
    png: { about: 'PNG je bezeztrátový: ukládá každý pixel přesně, podporuje plný alfa kanál pro průhlednost a nikdy se nezhorší, když ho znovu uložíte, a proto je první volbou pro snímky obrazovky, loga a grafiku rozhraní.', note: 'PNG uchová každý pixel přesně tak, jak je, a podporuje skutečnou průhlednost, takže snese opakované úpravy bez zhoršení.' },
    webp: { about: 'WebP je moderní webový obrázkový formát od Googlu; komprimuje znatelně silněji než JPG či PNG při srovnatelné kvalitě a podporuje průhlednost i animaci, ale spousta desktopových a tiskových programů ho stále neumí otevřít.', note: 'WebP dává nejmenší soubory z běžných webových formátů a podporuje průhlednost.' },
    bmp: { about: 'BMP ukládá surová, prakticky nekomprimovaná pixelová data, což z něj činí dokonale věrný a nesmírně rozhazovačný formát — fotografie může snadno zabírat desetkrát více než tentýž obrázek v PNG.', note: 'BMP je surový a nekomprimovaný, a právě to starý windowsový software a některé skenery dodnes očekávají.' },
    tiff: { about: 'TIFF je archivní a předtiskový formát: bezeztrátový, s vysokou barevnou hloubkou, schopný pojmout více stran či vrstev — a odpovídajícím způsobem objemný.', note: 'TIFF je formát, o který si tiskárny a archivy říkají, protože se nic nezahazuje.' },
    gif: { about: 'GIF je omezen na paletu 256 barev na snímek, a proto v něm fotografie vypadají pruhovaně, ale animuje se a spouští se sám vloženě téměř všude na internetu.', note: 'GIF se animuje a spouští sám v chatovacích aplikacích, systémech tiketů a na fórech, ale je omezen na 256 barev na snímek.' },
    ico: { about: 'ICO je windowsový kontejner ikon, který obsahuje tutéž grafiku v několika velikostech naráz, aby si systém mohl vybrat 16×16 pro záložku a 256×256 pro zástupce na ploše.', note: 'ICO svazuje více rozlišení do jediného souboru, a přesně to favicony a ikony windowsových aplikací potřebují.' },
    heic: { about: 'HEIC je formát, do kterého iPhone ukládá fotky ve výchozím nastavení; nabízí zhruba stejnou kvalitu jako JPG přibližně na polovině místa, jenže Windows, mnoho webových formulářů a spousta staršího softwaru ho prostě odmítají otevřít.', note: 'HEIC je kompaktní, ale mimo zařízení Apple špatně podporovaný.' },
    svg: { about: 'SVG se vůbec neskládá z pixelů — je to XML popisující tvary, křivky a text, takže zůstává dokonale ostrý v jakékoli velikosti a lze ho upravovat či restylovat kódem.', note: 'SVG se zvětší do jakékoli velikosti, aniž by kdy zesvětlalo do rozmazanosti, protože ukládá tvary místo pixelů.' },
    mp4: { about: 'MP4 je kontejner — obvykle video H.264 se zvukem AAC — a je to jediný videoformát, na kterém se telefony, prohlížeče, televize, střihové programy i sociální platformy shodnou.', note: 'MP4 se přehraje prakticky v každém telefonu, prohlížeči, televizi i střihovém programu bez dalšího softwaru.' },
    avi: { about: 'AVI je kontejner od Microsoftu z devadesátých let; starší přehrávače a střihové sady ho stále čtou, ale nemá moderní funkce pro streamování a jeho soubory bývají výrazně větší než MP4.', note: 'AVI je to, co očekávají starší přehrávače, nástroje na tvorbu DVD a letitý střihový software.' },
    mov: { about: 'MOV je kontejner QuickTime od Applu, formát, do kterého natáčejí iPhone a Mac a se kterým si Final Cut Pro a iMovie poradí nejhladčeji.', note: 'MOV je kontejner, se kterým střihové nástroje Applu pracují nejhladčeji.' },
    mkv: { about: 'MKV (Matroska) je otevřený kontejner, který pojme libovolný počet obrazových, zvukových a titulkových stop v jednom souboru — skvělý na archivaci, ale většina telefonů, televizí a prohlížečů ho odmítá.', note: 'MKV umí nést více zvukových a titulkových stop v jediném souboru.' },
    webm: { about: 'WebM je kontejner bez licenčních poplatků postavený pro HTML5 video, obvykle s VP9 nebo AV1; prohlížeče ho milují, ale desktopové střihové programy a software Applu se ho často ani nedotknou.', note: 'WebM je malý a nativně se streamuje v prohlížečích.' },
    wmv: { about: 'WMV je videoformát Windows Media od Microsoftu, prakticky jen pro Windows a mimo staré firemní nahrávky a záznamy obrazovky do značné míry opuštěný.', note: 'WMV je formát Windows Media s velmi slabou podporou jinde.' },
    flv: { about: 'FLV byl kontejner za Flash videem, a od chvíle, kdy byl Flash odstraněn ze všech prohlížečů, je to fakticky nepřehratelný archivní formát.', note: 'FLV je mrtvý kontejner z éry Flashe.' },
    mp3: { about: 'MP3 je ztrátový: kodér natrvalo maže ty části signálu, o kterých předpokládá, že je neuslyšíte, což smrskne skladbu zhruba na desetinu a je důvodem, proč se přehraje úplně na všem.', note: 'MP3 je asi desetkrát menší než nekomprimovaný zvuk a přehraje se v každém telefonu, autorádiu i přehrávači posledních dvaceti let.' },
    wav: { about: 'WAV ukládá zvuk nekomprimovaně, vzorek po vzorku, přesně tak, jak byl nahrán — proto ho používají studia a proto minuta stereo záznamu v kvalitě CD zabere okolo 10 MB.', note: 'WAV je nekomprimovaný a bezeztrátový, takže střihové a masteringové programy ho mohou zpracovávat, aniž by cokoli nejprve dekódovaly.' },
    flac: { about: 'FLAC komprimuje zvuk bezeztrátově: zabírá zhruba polovinu toho co WAV a přesto se dekóduje zpět na bit po bitu shodnou kopii původní nahrávky.', note: 'FLAC je bit po bitu shodný, ale zabírá zhruba polovinu toho co WAV.' },
    aac: { about: 'AAC je ztrátový kodek, který stojí za Apple Music, YouTubem a většinou streamovacích služeb; při stejném datovém toku zní zpravidla lépe než MP3.', note: 'AAC zní při stejném datovém toku lépe než MP3 a je standardem ve světě Applu a streamování.' },
    ogg: { about: 'OGG Vorbis je patentově nezatížený ztrátový kodek, kterému dávají přednost hry, otevřený software a Wikipedie, kvalitou srovnatelný s MP3 při menší velikosti.', note: 'OGG je prostý patentových omezení, a proto ho herní enginy a projekty s otevřeným kódem upřednostňují.' },
    m4a: { about: 'M4A je kontejner MP4 obsahující pouze zvuk, obvykle AAC — formát, který vytvářejí iTunes, Apple Music a hlasové poznámky iPhonu.', note: 'M4A je standardní zvukový soubor ekosystému Apple.' },
    wma: { about: 'WMA je ztrátový zvukový kodek Microsoftu z éry Windows Media Playeru, mimo Windows podporovaný jen zřídka a fakticky ukončený.', note: 'WMA je zastaralý zvukový kodek žijící jen na Windows.' },
    zip: { about: 'ZIP je archivní formát zabudovaný do Windows, macOS i každého telefonu — stačí dvojkliknout, bez instalace čehokoli dalšího.', note: 'ZIP se otevře dvojklikem ve Windows, macOS, Linuxu, iOS i Androidu, aniž by se cokoli instalovalo.' },
    rar: { about: 'RAR je uzavřený archivní formát s dobrou kompresí a obnovovacími záznamy, ale k otevření potřebuje WinRAR nebo kompatibilní nástroj.', note: 'RAR vyžaduje k rozbalení software třetí strany.' },
    '7z': { about: '7Z používá kompresi LZMA, která pravidelně vytváří znatelně menší archivy než ZIP — za cenu toho, že k jejich otevření je potřeba 7-Zip nebo kompatibilní nástroj.', note: '7Z komprimuje výrazně těsněji než ZIP, což se počítá u velkých složek a placeného cloudového úložiště.' },
    tar: { about: 'Soubor TAR svazuje mnoho souborů do jednoho, aniž by je komprimoval; pochází z unixového světa a zachovává oprávnění i adresářovou strukturu.', note: 'TAR zachovává unixová oprávnění a adresářovou strukturu.' },
    gz: { about: 'GZ (gzip) komprimuje jediný datový proud a je to to, co vytvářejí linuxové servery a nástroje příkazové řádky; ve Windows se bez dalšího softwaru otevírá nepohodlně.', note: 'GZ je standardní kompresní formát na Linuxu a webových serverech.' },
    srt: { about: 'SRT je titulkový formát v prostém textu, kterému rozumí každý střihový program i každý přehrávač: číslované repliky, rozsah časového kódu a řádek dialogu.', note: 'SRT přijímají YouTube, Vimeo, Premiere, Final Cut i každý běžný přehrávač.' },
  },
  reasons: {
    'pdf-to-word': 'Obvyklým podnětem je změna, kterou v samotném PDF udělat nelze — smluvní ustanovení, odrážka v životopisu nebo odstavec zprávy, který se musí změnit, aniž by se celý dokument přepisoval.',
    'word-to-pdf': 'Word se převádí do PDF úplně na konci života dokumentu: když životopis, nabídka nebo podepsaný formulář míří k někomu, jehož písma, verzi Wordu a okraje neovlivníte.',
    'pdf-to-excel': 'Typickým případem je bankovní výpis, faktura nebo zpráva, která existuje jen jako PDF, ale jejíž čísla potřebujete sečíst, seřadit nebo vynést do grafu.',
    'excel-to-pdf': 'Tohle se dělá před odesláním rozpočtu nebo ceníku někomu, kdo je má číst, ale ne měnit, a před tiskem — PDF přibije zalomení stránek, které by Excel jinak na každém počítači přepočítal.',
    'pptx-to-pdf': 'Většina lidí převede prezentaci do PDF před odesláním nebo rozdáním, aby se snímky nerozhodily a aby k jejich otevření nikdo nepotřeboval nainstalovaný PowerPoint.',
    'pdf-to-pptx': 'Tohle potřebujete, když jediná dochovaná kopie prezentace je PDF, které kolovalo po schůzce, a snímky musíte aktualizovat nebo znovu použít.',
    'pdf-to-txt': 'Běžné důvody: nakrmit dokumentem skript, vyhledávací index nebo nástroj s umělou inteligencí, nebo zredukovat dlouhou zprávu na něco, co jde prohledat, porovnat a vložit kamkoli.',
    'pdf-to-html': 'Je to nejrychlejší způsob, jak publikovat existující zprávu, příručku nebo brožuru na webu, aniž byste stránku stavěli ručně znovu.',
    'html-to-pdf': 'Dělá se to kvůli archivaci webové stránky přesně tak, jak dnes vypadá, nebo kvůli převedení HTML šablony faktury či zprávy na něco tisknutelného a odesílatelného.',
    'rtf-to-pdf': 'RTF obvykle vypadává ze staršího softwaru nebo z právních šablon dokumentů; převod do PDF vám dá jediný soubor, který se všude otevře stejně a nedá se omylem změnit.',
    'pdf-to-rtf': 'Tohle je volba, když potřebujete upravitelnou kopii PDF, ale nemůžete předpokládat, že příjemce má Word — RTF otevře prakticky každý textový editor, který kdy vznikl.',
    'odt-to-pdf': 'Typický případ: dokument jste napsali v LibreOffice nebo OpenOffice a ten, kdo ho dostává, používá Microsoft Office — nebo vůbec nic.',
    'pdf-to-epub': 'Číst PDF na telefonu znamená neustálé přibližování a vodorovné posouvání; tenhle převod je hlavně o tom, aby byl dlouhý dokument opravdu čitelný na malé obrazovce nebo čtečce.',
    'epub-to-pdf': 'EPUB se převádí do PDF, když chcete knihu vytisknout, opatřit ji poznámkami k pevným číslům stránek nebo ji poslat někomu, kdo nemá nainstalovanou žádnou čtečkovou aplikaci.',
    'document-converter': 'Tohle je nástroj, který otevřete, když vám někdo předá dokument ve formátu, jaký zrovna měl, a vy ho potřebujete v tom, který váš vlastní software skutečně otevře.',
    'ebook-converter': 'Knihkupectví s e-knihami i čtečky každý upřednostňují svůj vlastní formát, takže tímhle přesunete knihu, kterou vlastníte, z jedné čtečky nebo aplikace do druhé.',
    'jpg-to-png': 'Obvyklým podnětem je úprava: potřebujete vyříznout pozadí, položit logo přes jiný obrázek nebo zabránit tomu, aby snímek obrazovky s každým dalším uložením rozmazával.',
    'png-to-jpg': 'Tohle je řešení pro snímek obrazovky nebo export, který je příliš velký na přílohu e-mailu nebo na to, aby prošel limitem velikosti v nahrávacím formuláři.',
    'webp-to-png': 'Obvykle to potřebujete poté, co jste si uložili obrázek z webu: WebP se stáhne bez problémů, ale starší grafické editory, kancelářský software a některé tiskové služby ho stále odmítají otevřít.',
    'webp-to-jpg': 'Většina lidí to dělá, aby dostala obrázek z webu do něčeho všeobecně přijímaného — do e-mailu, do staršího redakčního systému, do fotolabu nebo do prastarého programu kolegy.',
    'heic-to-jpg': 'Tohle je klasický problém iPhonu: fotky vypadají na telefonu dobře, ale na počítači s Windows nebo ve webovém formuláři přistanou jako neotevíratelné soubory .heic.',
    'heic-to-png': 'Použijte to, když se chystáte fotku upravovat, a nejen ji sdílet — PNG předá vašemu editoru bezeztrátové pixely místo čerstvě znovu zkomprimované kopie.',
    'svg-to-png': 'Obvyklým důvodem je nástroj, který odmítá vektory: prezentace, inzerát na tržišti, e-mailový podpis nebo výrobní řetězec ikon, který bere jen pixely.',
    'svg-to-jpg': 'Tohle je pro místa, která chtějí prostý soubor fotografického typu — dokument, příspěvek na sociální síti nebo nahrávací formulář, který odmítá jak značkování SVG, tak průhlednost.',
    'bmp-to-png': 'Soubory BMP vylézají ze starého windowsového softwaru a ze skenerů v absurdních velikostech; PNG uloží přesně tytéž pixely na zlomku místa.',
    'tiff-to-jpg': 'Skenery a profesionální fotoaparáty vytvářejí soubory TIFF, které jsou na e-mail příliš velké, takže JPG je to, co odešlete, jakmile je archivní kopie v bezpečí.',
    'gif-to-png': 'Tohle se dělá se statickým GIFem — logem, ikonou nebo vyexportovaným snímkem — který kvůli limitu 256 barev ukazuje barevné pruhy nebo roztřepený okraj.',
    'png-to-ico': 'Skoro každý, kdo převádí PNG do ICO, staví faviconu nebo ikonu windowsové aplikace, a obojí očekává kontejner ICO, nikoli prostý obrázkový soubor.',
    'jfif-to-png': 'Soubory JFIF se typicky objeví, když se fotka uloží z Outlooku nebo z prohlížeče a Windows ji pak odmítne předat aplikaci, kterou jste chtěli použít.',
    'heic-to-pdf': 'Užitečné, když iPhonem fotíte dokumenty, účtenky nebo tabuli a musíte je odevzdat jako jediný soubor místo složky obrázků.',
    'image-compressor': 'Obvyklým důvodem je někde nějaký tvrdý limit — nahrávací formulář, strop pro e-mailové přílohy nebo webová stránka, která se načítá příliš pomalu, protože její obrázky jsou mnohem větší, než je potřeba.',
    'jpeg-compressor': 'Fotografové a majitelé webů to používají, když soubory JPEG v plném rozlišení brzdí stránku nebo neprojdou limitem pro nahrávání.',
    'png-compressor': 'Snímky obrazovky a vyexportovaná grafika rozhraní často váží několik megabajtů bez dobrého důvodu; tohle je zmenší, než skončí v dokumentu, v tiketu nebo na webové stránce.',
    'mp4-to-avi': 'Důvodem je téměř vždy starší zařízení nebo konkrétní program — některé letité přehrávače, nástroje na tvorbu DVD a programy k fotoaparátům čtou AVI a nic jiného.',
    'mp4-to-mov': 'Tohle je obvykle první krok před střihem na Macu, protože Final Cut Pro a iMovie si se soubory QuickTime poradí nejhladčeji.',
    'mov-to-mp4': 'iPhone a Mac natáčejí do MOV; všechno ostatní očekává MP4, takže tenhle převod se spouští před nahráním, odesláním nebo zveřejněním klipu.',
    'mkv-to-mp4': 'MKV je skvělý na ukládání, ale telefony, televize, prohlížeče a většina střihových programů ho nepřehrají — převod do MP4 je to, co soubor teprve učiní opravdu použitelným.',
    'webm-to-mp4': 'Soubory WebM uložené z webu se často odmítají otevřít v QuickTime, na iOS nebo v Premiere; MP4 je formát, který přijmou všechny.',
    'avi-to-mp4': 'Tohle je standardní záchrana pro staré záběry z kamery a archivované klipy, které polykají gigabajty a nepřehrají se na žádném telefonu.',
    'flv-to-mp4': 'Flash zmizel ze všech prohlížečů, takže každý FLV, který ještě máte, je fakticky nepřehratelný — převod do MP4 udrží ten archivní materiál sledovatelný.',
    'wmv-to-mp4': 'WMV je pozůstatek žijící jen na Windows, takže tohle se dělá před odesláním staré nahrávky nebo záznamu obrazovky na Mac, iPhone nebo webovou platformu.',
    'mp4-to-mp3': 'Obvykle jde o zvuk, ne o obraz — o přednášku, rozhovor, podcast nebo videoklip, který chcete mít v telefonu, aniž byste s sebou vláčeli video.',
    'video-to-mp3': 'Sáhne se po tom, když je zvuk tou částí, kterou stojí za to si nechat: nahraná přednáška, rozhovor, zkouška nebo hudební doprovod.',
    'mp4-converter': 'Tohle je nástroj pro chvíli, kdy se klip nepřehraje nebo nejde nahrát, protože MP4 je jediný videoformát, který přijímají telefony, prohlížeče, televize i sociální platformy.',
    'video-converter': 'Použijte ho, když klip potřebuje změnit svět — dostat se ze střihového programu, do telefonu, do prohlížeče nebo na platformu, která bere jen jeden konkrétní kontejner.',
    'mp3-to-wav': 'Obvyklým důvodem je střih: zvukové stanice, masteringové řetězce a mnoho zvukových procesů pro vysílání či hry chtějí nekomprimovaný WAV, aby nemusely při každé jednotlivé operaci dekódovat komprimovaný soubor.',
    'wav-to-mp3': 'Nahrávky vylézají z terénního rekordéru nebo ze zvukové stanice jako obrovské soubory WAV; MP3 je udělá dost malé na to, aby se daly poslat, nahrát nebo vejít do telefonu.',
    'flac-to-mp3': 'Knihovna ve FLAC zní doma skvěle, jenže autorádia, starší telefony a levné přehrávače ji často odmítají — MP3 je kompatibilní kopie, kterou si berete s sebou.',
    'aac-to-mp3': 'Jde tu hlavně o kompatibilitu: AAC pochází z ekosystému Applu a streamování, zatímco starší přehrávače, autorádia a dýdžejský software očekávají MP3.',
    'ogg-to-mp3': 'OGG se objevuje ve hrách, na Wikipedii a v otevřeném softwaru a téměř žádný z běžných přehrávačů v telefonu nebo v autě ho neotevře.',
    'wma-to-mp3': 'WMA je relikt éry Windows Media Playeru, a takhle se zachraňuje stará vyripovaná hudební sbírka pro telefon nebo streamovací knihovnu.',
    'm4a-to-mp3': 'Tohle je obvyklý krok při přesunu hudby nebo hlasových poznámek z iPhonu ze zařízení Applu do programů, aut nebo přehrávačů, které rozumí jen MP3.',
    'mp3-to-aac': 'Některá zařízení a aplikace — zvláště v prostředí Applu a streamovacích platforem — dávají přednost AAC, takže tohle je kompatibilní převod, ne zlepšení kvality.',
    'mp3-to-ogg': 'Do OGG se převádí kvůli herním enginům, projektům s otevřeným kódem a platformám, kde je vyžadován patentově nezatížený kodek.',
    'audio-converter': 'Tohle je nástroj pro okamžik, kdy se soubor nepřehraje: jediné místo, kde zvuk převedete přesně do toho z běžných formátů, na kterém trvá vaše zařízení, váš editor nebo váš nahrávací formulář.',
    'rar-to-zip': 'RAR potřebuje k otevření další software, takže tohle se dělá před odesláním archivu někomu, kdo si WinRAR instalovat nebude.',
    '7z-to-zip': '7Z komprimuje lépe, ale vyžaduje nainstalovaný 7-Zip; v ZIPu může příjemce prostě na soubor dvojkliknout.',
    'tar-to-zip': 'TAR pochází z příkazové řádky Linuxu a macOS, kdežto ZIP je to, co kolega na Windows otevře bez instalace čehokoli.',
    'gz-to-zip': 'Soubory GZ obvykle přicházejí ze serveru nebo z linuxového nástroje a ve Windows jsou nepohodlné, kde se ZIP rozbalí dvojklikem.',
    'zip-to-7z': 'Tady jde o velikost: komprese 7Z je znatelně silnější, což se počítá, když archivujete velkou složku nebo platíte za cloudové úložiště po gigabajtech.',
    'video-to-gif': 'Typickým užitím je krátká smyčka do chatové zprávy, do souboru README, do hlášení chyby nebo do příspěvku — do míst, kde se GIF spustí sám vloženě, kdežto videosoubor ne.',
    'mp4-to-gif': 'Typickým užitím je krátká smyčka do chatu, do souboru README, do hlášení chyby nebo do příspěvku, kde se GIF spustí sám vloženě, kdežto video by tam jen leželo jako příloha.',
    'webm-to-gif': 'Klipy WebM uložené z webu se často nedají vložit tam, kam chcete, kdežto GIF se přehraje vloženě v chatovacích aplikacích, systémech tiketů a na fórech.',
    'mov-to-gif': 'Tohle se dělá se záznamem obrazovky z QuickTime, který se má objevit vloženě v pull requestu, v tiketu podpory nebo v příspěvku.',
    'avi-to-gif': 'Převést pár vteřin starého klipu AVI na GIF je nejjednodušší způsob, jak je dostat do dokumentu, do chatového vlákna nebo na webovou stránku.',
    'gif-to-mp4': 'Dlouhé GIFy jsou obrovské a přehrávají se trhaně; MP4 ukáže tutéž animaci na zlomku velikosti, a přesně proto je sociální platformy v zákulisí převádějí.',
    'image-to-gif': 'Užitečné, když platforma nebo starší systém výslovně očekává GIF, nebo když potřebujete statický snímek ve stejném formátu jako existující sadu animací.',
    'gif-compressor': 'Animované GIFy rychle nabobtnají a tohle je řešení, když je některý příliš těžký na e-mail, na limit nahrávání v chatu nebo na stránku, která se musí načíst rychle.',
    'merge-pdf': 'Klasickým případem je žádost nebo hlášení škody: formulář, sken a účtenka, které všechny musí dorazit jako jediný dokument.',
    'split-pdf': 'Obvykle potřebujete přesně jednu věc z mnohem delšího souboru — jednu kapitolu, jednu fakturu, jednu podepsanou stranu z padesátistránkového skenu.',
    'compress-pdf': 'Téměř vždy limit velikosti: strop pro e-mailové přílohy, úřední formulář nebo portál, který odmítá cokoli nad pár megabajtů.',
    'rotate-pdf': 'Tohle řeší všední problém se skenerem — stránky, které vylezly na bok nebo vzhůru nohama podle toho, jak byly listy podávány.',
    'protect-pdf': 'PDF se chrání heslem před odesláním výplatních pásek, smluv nebo lékařských zpráv, aby obsah nebyl čitelný pro toho, komu bude zpráva vzápětí přeposlána.',
    'unlock-pdf': 'Použijte to na dokumenty, které vlastníte, když heslo znáte, ale omezení překáží — třeba na bankovní výpis, který nejde vytisknout.',
    'view-metadata': 'Odpovídá na otázky, které vám soubor přímo neřekne: jaký fotoaparát tuhle fotku pořídil, jak dlouhá tahle nahrávka opravdu je, jaký kodek je uvnitř tohohle videa, kolik stran má tohle PDF.',
    'ocr': 'Situace je vždy stejná: máte dokument jako obrázek a potřebujete z něj slova — abyste v nich hledali, citovali je, upravovali nebo je pořádně archivovali.',
    'pdf-compress-ai': 'Sáhněte po tom, když jste běžnou kompresi už zkusili a soubor je pořád příliš velký na limit nahrávání, se kterým bojujete.',
    'text-to-speech': 'Používá se k tomu, aby si člověk něco poslechl místo čtení — článek cestou do práce, scénář přečtený nahlas kvůli odhalení kostrbatých formulací, nebo komentář k videu.',
    'speech-to-text': 'Obvyklým případem je nahrávka, kterou potřebujete písemně: schůzka, rozhovor, přednáška nebo hlasová poznámka, ze které se mají stát poznámky, zápis nebo citovatelný přepis.',
    'auto-subtitle': 'Titulky jsou to, co dělá video sledovatelným bez zvuku a dohledatelným pro vyhledávače, a psát je ručně zabere i u krátkého klipu mnohem víc času, než si lidé myslí.',
    'document-translation': 'Cílem je přečíst nebo odeslat dokument v jiném jazyce, aniž by se ztratila sazba, která ho dělá čitelným.',
  },
  t: {
    'list.and': 'a',
    'family.document': 'dokumentový',
    'family.image': 'obrázkový',
    'family.video': 'video',
    'family.audio': 'zvukový',
    'family.ebook': 'e-knižní',
    'family.archive': 'archivní',
    'family.subtitle': 'titulkový',
    'family.none': 'souborový',
    'unit.sample': 'každý vzorek',
    'unit.pixel': 'každý pixel',

    'intro.convert': '{{fromAbout}} {{toAbout}} {{reason}} {{toNote}}',
    'intro.convert.noSource': '{{fn}} je zdrojový formát tohoto převodu.',
    'intro.lead': '{{lead}} {{reason}}',
    'intro.hub': 'Tohle je univerzální {{category}} převodník: přijímá {{inputs}} a zapisuje {{outputs}}, takže nemusíte lovit ten jediný nástroj, který odpovídá právě vaší dvojici formátů. {{reason}} Vyberte výše cílový formát — převod probíhá na serveru, není co instalovat.',
    'intro.hubExtract': 'Tenhle nástroj vytáhne zvukovou stopu z videosouboru a uloží ji samostatně, takže se z videa stane obyčejný zvukový soubor, který se přehraje všude. Přijímá {{inputs}} a zapisuje {{outputs}}. Obrazová stopa se prostě zahodí, a proto je výsledek zlomkem původní velikosti. {{reason}}',
    'intro.hubGif': 'Tenhle nástroj mění soubory {{inputs}} na animované GIFy. {{gifAbout}} {{reason}}',
    'intro.hubGif.gifAbout': 'GIF je omezen na paletu 256 barev na snímek, a proto v něm fotografie vypadají pruhovaně, ale animuje se a spouští se sám vloženě téměř všude na internetu.',
    'intro.compress': '{{about}} Tenhle nástroj váš soubor {{fn}} znovu zakóduje do menší velikosti, aniž by změnil formát, takže to, co si stáhnete, je pořád obyčejný {{fn}}, který se otevře přesně tam, kde se otevíral originál. {{reason}}{{extra}}',
    'intro.compress.lossless': ' Protože {{fn}} je bezeztrátový, největší část úspory pochází z chytřejšího kódování a zúžené palety, nikoli ze zahazování detailů.',
    'intro.soon': '{{reason}} Tenhle nástroj ještě neběží — právě vzniká a objeví se tady, jakmile bude hotový.',
    'intro.lead.pdf-merge': 'Sloučení spojí několik PDF do jediného souboru v pořadí, které zvolíte, aniž by stránky znovu vykreslovalo — text zůstává označitelný a obrázky si drží původní kvalitu. PDF je formát s pevnou sazbou: ukládá přesnou polohu každého znaku, každé linky a každého obrázku, a proto vypadá všude stejně, ale špatně se upravuje.',
    'intro.lead.pdf-split': 'Rozdělení vytáhne z PDF stránky, které určíte, a uloží je jako nový dokument, přičemž originál zůstane nedotčený. PDF je formát s pevnou sazbou: ukládá přesnou polohu každého znaku, každé linky a každého obrázku, a proto vypadá všude stejně, ale špatně se upravuje.',
    'intro.lead.pdf-compress': 'Komprese PDF znovu zakóduje obrázky uvnitř a odstraní nadbytečná vložená data, a právě tam se u velkého PDF skrývá téměř celá velikost. Text a vektorová grafika zůstávají ostré.',
    'intro.lead.pdf-compress-ai': 'Tenhle nástroj před kompresí rozebere, co je uvnitř PDF, takže fotografické obrázky, plošná grafika a čistě textové strany se každé zpracují tak, jak se ušetří nejvíc místa bez viditelného zhoršení.',
    'intro.lead.pdf-rotate': 'Otočení změní příznak orientace a geometrii stránek v PDF, aby se stránky zobrazovaly a tiskly správnou stranou nahoru. Nic se znovu nevykresluje, takže se neztrácí žádná kvalita.',
    'intro.lead.pdf-protect': 'Ochrana PDF zašifruje jeho obsah, takže ho nelze otevřít bez hesla, které nastavíte. Šifrování se aplikuje na samotný soubor, ne na obal kolem něj.',
    'intro.lead.pdf-unlock': 'Odemknutí odstraní heslo a omezení použití z PDF, jehož heslo už máte, aby se dalo zase normálně otevírat, tisknout a kopírovat z něj.',
    'intro.lead.metadata': 'Každý soubor s sebou nese informace o sobě samém, které při otevření nevidíte: rozměry obrázku a nastavení fotoaparátu, délku a datový tok zvuku, kodek a snímkovou frekvenci videa, autora a počet stran dokumentu. Tenhle nástroj ta metadata přečte a ukáže vám je.',
    'intro.lead.ocr': 'Optické rozpoznávání znaků se podívá na obraz textu — sken, fotografii, stránku PDF bez textové vrstvy — a odvodí, o jaké znaky jde, čímž se z obrázku slov stanou slova, ve kterých počítač umí hledat, která umí kopírovat a upravovat.',
    'intro.lead.tts': 'Převod textu na řeč vytváří mluvený zvuk z napsaného textu pomocí neuronových hlasů, takže dostanete přirozeně znějící nahrávku místo plochého robotického výstupu starších systémů.',
    'intro.lead.stt': 'Převod řeči na text přepisuje mluvený zvuk do slov. Se spontánní řečí, přízvuky a hlukem v pozadí si poradí mnohem lépe než kdysi diktovací software a vrací přepis, který můžete upravovat.',
    'intro.lead.subtitle': 'Generátor titulků přepíše řeč z videa a vypíše ji s časovými kódy, čímž vznikne standardní titulkový soubor, nikoli pouhý přepis.',

    'steps.convert.1.batch': 'Přetáhněte svůj soubor {{fn}} do oblasti pro nahrávání v horní části této stránky, nebo na ni klikněte a soubor v zařízení vyhledejte. Můžete přidat několik souborů — nebo celou složku — a převést je všechny najednou.',
    'steps.convert.1.single': 'Přetáhněte svůj soubor {{fn}} do oblasti pro nahrávání v horní části této stránky, nebo na ni klikněte a soubor v zařízení vyhledejte.',
    'steps.convert.2.direct': 'Zvolte {{tn}} jako výstupní formát a klikněte na Převést.',
    'steps.convert.2.dropdown': 'Zvolte {{tn}} jako výstupní formát v rozbalovací nabídce a klikněte na Převést.',
    'steps.convert.2.directMedia': 'Zvolte {{tn}} jako výstupní formát, v případě potřeby upravte kvalitu nebo velikost v pokročilém nastavení a klikněte na Převést.',
    'steps.convert.2.dropdownMedia': 'Zvolte {{tn}} jako výstupní formát v rozbalovací nabídce, v případě potřeby upravte kvalitu nebo velikost v pokročilém nastavení a klikněte na Převést.',
    'steps.convert.3': 'Stáhněte si hotový soubor {{tn}}. Odkaz ke stažení zůstává aktivní 24 hodin, poté se oba soubory automaticky smažou.',
    'steps.hub.1.batch': 'Přetáhněte svůj {{category}} soubor ({{inputs}} jsou všechny přijímány) do oblasti pro nahrávání v horní části této stránky, nebo na ni klikněte a soubor v zařízení vyhledejte. Můžete přidat několik souborů — nebo celou složku — a převést je všechny najednou.',
    'steps.hub.1.single': 'Přetáhněte svůj {{category}} soubor ({{inputs}} jsou všechny přijímány) do oblasti pro nahrávání v horní části této stránky, nebo na ni klikněte a soubor v zařízení vyhledejte.',
    'steps.hub.2.direct': 'Vyberte výstupní formát, který potřebujete, a klikněte na Převést.',
    'steps.hub.2.dropdown': 'Vyberte v rozbalovací nabídce výstupní formát, který potřebujete, a klikněte na Převést.',
    'steps.hub.2.directMedia': 'Vyberte výstupní formát, který potřebujete, v případě potřeby upravte kvalitu nebo velikost v pokročilém nastavení a klikněte na Převést.',
    'steps.hub.2.dropdownMedia': 'Vyberte v rozbalovací nabídce výstupní formát, který potřebujete, v případě potřeby upravte kvalitu nebo velikost v pokročilém nastavení a klikněte na Převést.',
    'steps.hub.3': 'Stáhněte si hotový soubor. Odkaz ke stažení zůstává aktivní 24 hodin, poté se oba soubory automaticky smažou.',
    'steps.pdf-merge.1': 'Přidejte každé PDF, které chcete spojit — přetáhněte je do oblasti pro nahrávání společně, nebo klikněte a vybírejte je jedno po druhém.',
    'steps.pdf-merge.2': 'Přetáhněte soubory do pořadí, v jakém mají v hotovém dokumentu následovat.',
    'steps.pdf-merge.3': 'Klikněte na Sloučit a stáhněte si jediné spojené PDF.',
    'steps.pdf-split.1': 'Nahrajte PDF, ze kterého chcete vytáhnout stránky.',
    'steps.pdf-split.2': 'Napište potřebné stránky nebo rozsahy do pole pro rozsahy stránek — například 1-3, 5, 7-10.',
    'steps.pdf-split.3': 'Klikněte na Převést a stáhněte si vytažené stránky.',
    'steps.pdf-compress.1': 'Přetáhněte své PDF do oblasti pro nahrávání, nebo klikněte a vyhledejte ho.',
    'steps.pdf-compress.2': 'Klikněte na Převést — soubor se rozebere a jeho obrázky a vložená data se znovu zakódují do menší velikosti.',
    'steps.pdf-compress.3': 'Stáhněte si zkomprimované PDF a podívejte se na úsporu velikosti zobrazenou vedle.',
    'steps.pdf-rotate.1': 'Nahrajte PDF, jehož stránky jsou otočené špatně.',
    'steps.pdf-rotate.2': 'Zvolte, o kolik se mají otočit — o 90°, 180° nebo 270°.',
    'steps.pdf-rotate.3': 'Klikněte na Převést a stáhněte si opravené PDF.',
    'steps.pdf-protect.1': 'Nahrajte PDF, které chcete zabezpečit.',
    'steps.pdf-protect.2': 'Zadejte heslo, které bude potřeba k jeho otevření, a uschovejte si jeho kopii na bezpečném místě.',
    'steps.pdf-protect.3': 'Klikněte na Převést a stáhněte si zašifrované PDF.',
    'steps.pdf-unlock.1': 'Nahrajte PDF chráněné heslem.',
    'steps.pdf-unlock.2': 'Zadejte jeho současné heslo, aby bylo možné soubor dešifrovat.',
    'steps.pdf-unlock.3': 'Klikněte na Převést a stáhněte si odemčené PDF.',
    'steps.metadata.1': 'Přetáhněte jakýkoli soubor do oblasti pro nahrávání — obrázek, video, zvukový soubor nebo dokument.',
    'steps.metadata.2': 'Soubor se prozkoumá, nikoli převede, takže se na něm nic nemění.',
    'steps.metadata.3': 'Přečtěte si metadata přímo na stránce: rozměry, délku, kodek, údaje o fotoaparátu, počet stran a další.',
    'steps.ocr.1': 'Nahrajte naskenované PDF nebo fotografii textu.',
    'steps.ocr.2': 'Zvolte jazyk dokumentu a zda chcete prohledatelné PDF, nebo prostý text.',
    'steps.ocr.3': 'Klikněte na Převést a stáhněte si výsledek, v němž je rozpoznaný text nyní označitelný a prohledatelný.',
    'steps.tts.1': 'Napište nebo vložte svůj text do pole — až 4096 znaků na jeden převod.',
    'steps.tts.2': 'Zvolte hlas, rychlost řeči a výstupní formát.',
    'steps.tts.3': 'Klikněte na Převést a stáhněte si hotový zvukový soubor.',
    'steps.stt.1': 'Nahrajte svou nahrávku, nebo nahrávejte rovnou z mikrofonu tlačítkem na stránce.',
    'steps.stt.2': 'Volitelně nastavte mluvený jazyk pro vyšší přesnost a zvolte výstup TXT nebo DOCX.',
    'steps.stt.3': 'Klikněte na Převést, přečtěte si přepis na stránce a pak si ho stáhněte.',
    'steps.subtitle.1': 'Nahrajte video, ke kterému chcete titulky.',
    'steps.subtitle.2': 'Zvolte SRT nebo VTT a nastavte mluvený jazyk, pokud ho znáte.',
    'steps.subtitle.3': 'Klikněte na Převést a stáhněte si časovaný titulkový soubor, připravený vložit do přehrávače nebo střihového programu.',
    'steps.compress.1': 'Přetáhněte své obrázky {{fn}} do oblasti pro nahrávání, nebo klikněte a vyhledejte je. Můžete přidat celou složku najednou.',
    'steps.compress.1.gif': 'Přetáhněte svou animaci {{fn}} do oblasti pro nahrávání, nebo klikněte a vyhledejte ji. Můžete přidat celou složku najednou.',
    'steps.compress.2': 'Klikněte na Převést — soubor se znovu zakóduje do menší velikosti a zůstane přitom ve stejném formátu.',
    'steps.compress.3': 'Stáhněte si výsledek a porovnejte ho s původní velikostí zobrazenou na stránce.',
    'steps.soon.1': 'Vyberte si nástroj, který potřebujete, na stránce Nástroje — všechno kromě tohohle už dnes funguje.',
    'steps.soon.2': 'Nahrajte svůj soubor a zvolte výstupní formát.',
    'steps.soon.3': 'Stáhněte si výsledek, nebo se sem vraťte, až se překlad dokumentů spustí.',

    'faq.cost.q.pair': 'Je převod {{from}} na {{to}} zdarma?',
    'faq.cost.q.tool': 'Je {{label}} zdarma?',
    'faq.cost.a.pair': 'Nové účty dostávají jeden kredit na převod zdarma, takže váš první převod {{from}} na {{to}} nestojí nic. Poté každý převod spotřebuje jeden kredit z malého předplaceného balíčku — žádné předplatné, kredity nikdy nevyprší a za neúspěšný převod se neplatí.',
    'faq.cost.a.tool': 'Nové účty dostávají jeden kredit na převod zdarma, takže váš první soubor nestojí nic. Poté každý převod spotřebuje jeden kredit z malého předplaceného balíčku — žádné předplatné, kredity nikdy nevyprší a za neúspěšný převod se neplatí.',
    'faq.cost.a.smartTts': 'Nové účty dostávají jeden kredit na převod zdarma na vyzkoušení a chytré funkce se účtují podle využití, ne po souborech — 1 kredit za každých 1000 znaků textu, zaokrouhleno nahoru. Žádné předplatné: kredity se kupují v malých předplacených balíčcích, nikdy nevyprší a neúspěšný převod nikdy nic nestojí.',
    'faq.cost.a.smartAv': 'Nové účty dostávají jeden kredit na převod zdarma na vyzkoušení a chytré funkce se účtují podle využití, ne po souborech — 1 kredit za každých 5 minut zvuku či videa, zaokrouhleno nahoru. Žádné předplatné: kredity se kupují v malých předplacených balíčcích, nikdy nevyprší a neúspěšný převod nikdy nic nestojí.',
    'faq.cost.q.metadata': 'Je nástroj Informace o souboru zdarma?',
    'faq.cost.a.metadata': 'Ano. Čtení metadat souboru není převod, a tak nespotřebuje kredit — můžete prozkoumat kolik souborů chcete. Kredity se utrácejí jen tehdy, když pro vás nástroj skutečně vytvoří nový soubor.',
    'faq.cost.q.soon': 'Je už {{label}} k dispozici?',
    'faq.cost.a.soon': 'Zatím ne — tahle stránka je zástupné místo po dobu, kdy se nástroj staví, takže tu dnes není co nahrávat. Ceny budou následovat stejný model předplacených kreditů jako zbytek webu: žádné předplatné, kredity, které nikdy nevyprší, a žádný poplatek za neúspěšný převod.',

    'faq.time.q.pair': 'Jak dlouho trvá převod {{from}} na {{to}}?',
    'faq.time.q.tool': 'Jak dlouho trvá {{label}}?',
    'faq.time.a': '{{speed}} Omezujícím činitelem bývá rychlost nahrávání, takže velký soubor na pomalém připojení zabere víc času než samotný převod.{{suffix}}',
    'faq.time.speed.image': 'Obrázky jsou to nejrychlejší, co převádíme — jediná fotografie je obvykle hotová do pěti sekund a celá složka zabere zhruba tolik co samotné nahrávání.',
    'faq.time.speed.document': 'Většina dokumentů je hotová za pár sekund. Velmi dlouhé soubory — několik set stran nebo sken plný obrázků — mohou zabrat až minutu.',
    'faq.time.speed.audio': 'Běžná skladba se převede za pár sekund. Nahrávka v plné délce, třeba přednáška nebo díl podcastu, obvykle zabere výrazně méně než minutu a většinu z toho tvoří nahrávání.',
    'faq.time.speed.video': 'Video je nejpomalejší kategorie, protože každý snímek se musí znovu zakódovat. Krátký klip zabere sekundy, kdežto dlouhý soubor ve vysokém rozlišení může zabrat pár minut.',
    'faq.time.speed.archive': 'Archivy se převedou během sekund, i když velký trvá déle, protože každý soubor uvnitř se musí rozbalit a znovu zabalit.',
    'faq.time.speed.ebook': 'E-knihy jdou rychle — celý román se obvykle převede za pár sekund.',
    'faq.time.speed.subtitle': 'Přepis postupuje zhruba několika sekundami na minutu zvuku, takže desetiminutové video bývá otitulkováno výrazně do minuty.',
    'faq.time.suffix.standard': ' Přijímáme soubory do 200 MB.',
    'faq.time.suffix.smart': ' Chytré funkce přijímají soubory do 25 MB; běžné převody do 200 MB.',
    'faq.time.q.metadata': 'Jak dlouho trvá přečíst metadata souboru?',
    'faq.time.a.metadata': 'Sekundu nebo dvě, jakmile je soubor nahraný. Nic se nepřevádí ani znovu nekóduje — hlavičky se rozeberou a výsledek se vypíše rovnou na stránku — takže čekání je v podstatě jen nahrávání.',
    'faq.time.q.soon': 'Bude to stát navíc?',
    'faq.time.a.soon': 'Bude používat stejné kredity jako všechno ostatní na webu. Není třeba se hlásit do žádného zvláštního tarifu ani předplatného a kredity, které už na účtu máte, s ním budou fungovat od okamžiku, kdy se spustí.',

    'faq.safety.q.pair': 'Je bezpečné nahrát můj soubor {{from}}?',
    'faq.safety.q.tool': 'Je můj soubor v bezpečí?',
    'faq.safety.a.pair': 'Soubory putují po šifrovaném spojení TLS a nepoužívají se k ničemu jinému než k převodu, o který jste požádali. Jak váš původní soubor {{from}}, tak soubor {{to}}, který vám vracíme, se do 24 hodin automaticky smažou — trvale a bez uchovávání záloh — a obsah se nikdy nečte, neanalyzuje ani nesdílí. Službu provozujeme z Německa v režimu GDPR.',
    'faq.safety.a.tool': 'Soubory putují po šifrovaném spojení TLS a nepoužívají se k ničemu jinému než k převodu, o který jste požádali. Jak váš původní soubor, tak výsledek, který vám vracíme, se do 24 hodin automaticky smažou — trvale a bez uchovávání záloh — a obsah se nikdy nečte, neanalyzuje ani nesdílí. Službu provozujeme z Německa v režimu GDPR.',

    'quality.vectorRaster.q': 'Zůstane můj {{fn}} ostrý jako {{tn}}?',
    'quality.vectorRaster.a': 'Do velikosti, ve které ho vyexportujete, ano. {{fn}} ukládá tvary místo pixelů, a je tedy nekonečně škálovatelný, ale {{tn}} je pevná mřížka pixelů a rozmaže se, pokud ho někdo později zvětší za hranice té mřížky. Nastavte v pokročilém nastavení šířku a výšku, kterou opravdu potřebujete, ještě před převodem — export ve dvoj- či trojnásobku zobrazované velikosti je obvyklý trik pro obrazovky s vysokou hustotou pixelů. Uschovejte si původní soubor {{fn}}: zůstává hlavní kopií, ze které můžete znovu exportovat v jakémkoli rozlišení.',
    'quality.docToTxt.q': 'Přijdu o formátování při převodu {{fn}} na {{tn}}?',
    'quality.docToTxt.a': 'Ano, a je to záměr — soubor {{tn}} obsahuje znaky a nic víc. Písma, barvy, obrázky, tabulky, sloupce i zalomení stránek všechny odpadnou; zpět dostanete čitelný text dokumentu v pořadí čtení. Přesně to chcete pro vyhledávání, skriptování nebo podání textu jinému programu, a přesně to nechcete, pokud jste doufali, že si zachováte vzhled. Pozor: {{fn}}, který je ve skutečnosti naskenovaný obrázek, neobsahuje vůbec žádný text k vytažení — proženěte ho místo toho nástrojem OCR.',
    'quality.docToSheet.q': 'Jak přesně se z {{fn}} vytahují tabulky?',
    'quality.docToSheet.a': 'Čisté tabulky s linkami a rovnoměrnými sloupci — výpisy, faktury, vyexportované sestavy — projdou spolehlivě a každá hodnota přistane ve vlastní buňce, takže ji lze sečíst i seřadit. Tabulky bez viditelných rámečků, buňky přes několik řádků nebo čísla rozdělená zalomením stránky jsou případy, které se vyplatí si potom očima zkontrolovat. {{fn}} ukládá polohy, nikoli strukturu tabulky, takže převod musí odvodit, kde jeden sloupec končí a začíná další.',
    'quality.docToReflow.q': 'Přežije sazba převod {{fn}} na {{tn}}?',
    'quality.docToReflow.a': 'Ne úplně, a právě o to jde. {{fn}} přibíjí text k pevným souřadnicím na stránce; {{tn}} ho přesází podle obrazovky a velikosti písma čtenáře, takže pevná čísla stránek, záhlaví, zápatí a vícesloupcové sazby se spíš přeinterpretují, než reprodukují. Základní text, nadpisy, pořadí odstavců a obrázky projdou dobře. Dokumenty tvořené převážně souvislým textem se převádějí nádherně; jsou to graficky náročné stránky, formuláře a složité tabulky, na které je dobré se potom podívat.',
    'quality.docToFixed.q': 'Zachová se moje formátování v {{tn}}?',
    'quality.docToFixed.a': 'Ano — tenhle směr je ten bezpečný. {{tn}} zaznamenává výslednou vysázenou stránku, takže písma, mezery, tabulky, obrázky a zalomení stránek se zmrazí přesně tak, jak byly vysázeny, a budou vypadat stejně na každém zařízení i tiskárně. To je zároveň ta daň: výsledek už nejde volně upravovat, což je obvykle přesně důvod, proč se dokument před odesláním převádí do {{tn}}.',
    'quality.docToEditable.q': 'Jak přesný je převod {{fn}} na {{tn}}?',
    'quality.docToEditable.a': 'Text, nadpisy, seznamy, obrázky a jednoduché tabulky projdou spolehlivě a zůstanou plně upravitelné. Protože {{fn}} ukládá polohy, nikoli strukturu, musí převod tu strukturu znovu poskládat, takže graficky náročné stránky — několik sloupců, text obtékající obrázky, složité vnořené tabulky — mohou potom potřebovat lehké dočištění. Pokud je PDF sken zcela bez textové vrstvy, použijte místo toho nástroj OCR: rozpozná znaky v obrázku, místo aby hledal text, který tam není.',
    'quality.docGeneric.q': 'Přijdu o něco při převodu {{fn}} na {{tn}}?',
    'quality.docGeneric.a': 'Slova, nadpisy, seznamy i obrázky se přenesou nedotčené. {{tn}} má jinou zásobu formátovacích prostředků než {{fn}}, takže velmi specifická úprava se cestou může zjednodušit, ale samotný obsah se zachová.',
    'quality.archive.q': 'Změní se soubory uvnitř mého archivu {{fn}}?',
    'quality.archive.a': 'Ne. Archivní formáty jsou bezeztrátové kontejnery: {{fn}} se rozbalí a tytéž soubory se zabalí znovu jako {{tn}}, bajt po bajtu. Mění se jen metoda komprese a kontejner. Co se ale mění, je velikost samotného archivu — {{clause}}.',
    'quality.archive.clause.to7z': '7Z díky kompresi LZMA obvykle vytvoří menší archiv než ZIP',
    'quality.archive.clause.toZip': 'ZIP bývá o něco větší než 7Z nebo RAR, a to je daň za to, že jde otevřít všude bez dalšího softwaru',
    'quality.archive.clause.other': 'nový formát komprimuje jinak, takže se velikost souboru může posunout kterýmkoli směrem',
    'quality.imageToDoc.q': 'Ztratí moje fotky uvnitř {{tn}} kvalitu?',
    'quality.imageToDoc.a': 'Ne. Každý obrázek {{fn}} se do {{tn}} vloží tak, jak je, jeden na stránku, místo aby se znovu komprimoval, takže to, co v dokumentu vidíte, je to, co vyšlo z fotoaparátu. {{tn}} bude zhruba tak velký jako všechny obrázky dohromady, což se hodí vědět, než ho pošlete e-mailem — proženěte výsledek nástrojem Komprimovat PDF, pokud má být menší.',
    'quality.toGif.q': 'Proč můj GIF vypadá hůř než původní {{fn}}?',
    'quality.toGif.a': 'Protože GIF je omezen na 256 barev na snímek. Video nebo fotografie jich obsahují miliony, takže kodér musí vybrat paletu a všechno ostatní přiblížit, což se projeví jako pruhy v přechodech a na obloze. GIF navíc nenese vůbec žádnou zvukovou stopu. Obojí patří k formátu, nikoli k převodu — držte klip krátký, a pokud ztráta barev váží víc než vložené automatické přehrávání, MP4 bude vypadat mnohem lépe při menší velikosti.',
    'quality.lossyToLossless.q': 'Zlepší se kvalita převodem {{fn}} na {{tn}}?',
    'quality.lossyToLossless.a': 'Ne — a je to zdaleka nejrozšířenější omyl kolem tohohle převodu. {{fn}} je ztrátový: detaily, které jeho kodér zahodil, jsou nenávratně pryč a nic je neobnoví. {{tn}} vám dá bezeztrátový kontejner pro to, co zbylo, takže se soubor přestane zhoršovat s každým dalším uložením či úpravou. To je opravdu užitečné, když se chystáte {{clause}}, ale kvalitu, která už se ztratila, to nevrátí.',
    'quality.lossyToLossless.edit.audio': 'zvuk upravovat, masterovat nebo zpracovávat',
    'quality.lossyToLossless.edit.image': 'obrázek upravovat, retušovat nebo skládat',
    'quality.losslessToLossy.q': 'Přijdu o kvalitu při převodu {{fn}} na {{tn}}?',
    'quality.losslessToLossy.a.audio': 'O něco, a záměrně — právě tak se soubor zmenší. {{tn}} je ztrátový, takže kodér zahodí informace, které vyhodnotí jako nejméně postřehnutelné. Při rozumném nastavení je rozdíl velmi těžké sluchem zachytit a v pokročilém nastavení můžete zvýšit datový tok, pokud raději vyměníte velikost za věrnost. Uschovejte si původní soubor {{fn}}: zůstává hlavní kopií a pozdější opětovné zakódování {{tn}} by ztrátu prohloubilo.',
    'quality.losslessToLossy.a.visual': 'O něco, a záměrně — právě tak se soubor zmenší. {{tn}} je ztrátový, takže kodér zahodí informace, které vyhodnotí jako nejméně postřehnutelné. Při rozumném nastavení je rozdíl velmi těžké okem zachytit a v pokročilém nastavení můžete zvýšit hodnotu kvality, pokud raději vyměníte velikost za věrnost. Uschovejte si původní soubor {{fn}}: zůstává hlavní kopií a pozdější opětovné zakódování {{tn}} by ztrátu prohloubilo.',
    'quality.lossyToLossy.q': 'Přijdu o kvalitu při převodu {{fn}} na {{tn}}?',
    'quality.lossyToLossy.a.audio': 'Trošku. Oba formáty jsou ztrátové, takže se {{fn}} dekóduje a pak znovu zakóduje jako {{tn}}, a každá generace ztrátového kódování upustí trochu detailu. Při běžném nastavení si toho většina lidí při poslechu nevšimne a v pokročilém nastavení můžete zvýšit datový tok. Čemu byste se měli vyhnout, je opakované převádění téhož souboru tam a zpět — právě to učiní ztrátu slyšitelnou.',
    'quality.lossyToLossy.a.visual': 'Trošku. Oba formáty jsou ztrátové, takže se {{fn}} dekóduje a pak znovu zakóduje jako {{tn}}, a každá generace ztrátového kódování upustí trochu detailu. Při běžném nastavení si toho většina lidí nevšimne a v pokročilém nastavení můžete zvýšit kvalitu. Čemu byste se měli vyhnout, je opakované převádění téhož souboru tam a zpět — právě to učiní ztrátu viditelnou.',
    'quality.losslessToLossless.q': 'Přijdu o kvalitu při převodu {{fn}} na {{tn}}?',
    'quality.losslessToLossless.a.plain': 'Ne. {{fn}} i {{tn}} jsou bezeztrátové, takže {{unit}} zůstane zachován přesně a výsledek je totožný s originálem. Mění se jen velikost souboru. Můžete později převést zpět zcela bez zhoršení.',
    'quality.losslessToLossless.a.bulky': 'Ne. {{fn}} i {{tn}} jsou bezeztrátové, takže {{unit}} zůstane zachován přesně a výsledek je totožný s originálem. Mění se jen velikost souboru, obvykle dramaticky dolů, protože {{fn}} ukládá svá data prakticky bez komprese. Můžete později převést zpět zcela bez zhoršení.',
    'quality.fallback.q': 'Přijdu o kvalitu při převodu {{fn}} na {{tn}}?',
    'quality.fallback.a': 'U běžných souborů je výsledek vizuálně i funkčně rovnocenný originálu. Tam, kde oba formáty umí různé věci, převod zachová vše, co je {{tn}} schopen vyjádřit. Pokročilé nastavení vám umožní zvýšit kvalitu, pokud vám výchozí kompromis nesedí.',

    'relation.uncompressed.q': 'Proč je soubor {{tn}} o tolik větší než {{fn}}?',
    'relation.uncompressed.a': 'Protože {{tn}} je nekomprimovaný. {{fn}} zmenšuje zvuk zahazováním dat a efektivním zakódováním zbytku; {{tn}} vypisuje každý vzorek v plné velikosti, což vychází zhruba na 10 MB na minutu stereo záznamu v kvalitě CD. Desetinásobný nárůst je normální a očekávaný — je to daň za soubor, který střihový software zvládne zpracovávat, aniž by cokoli nejprve dekódoval. Pokud chcete bezeztrátový zvuk zhruba na poloviční velikosti, převeďte ho místo toho do FLAC.',
    'relation.extractAudio.q': 'Zůstane při tom video, nebo jen zvuk?',
    'relation.extractAudio.a': 'Jen zvuk. Zvuková stopa se vytáhne ze souboru {{fn}} a uloží jako {{tn}}; obrazová stopa se zahodí, a proto je výsledek zlomkem původní velikosti. Samotný zvuk se nenahrává znovu, takže si drží kvalitu, kterou měl uvnitř {{fn}} — z videa s nízkým datovým tokem nelze získat zvuk s vysokým.',
    'relation.videoContainer.q': 'Přehraje se moje {{tn}} na telefonech, televizích a sociálních sítích?',
    'relation.videoContainer.a.mp4': 'Přesně k tomu tenhle převod slouží. MP4 s videem H.264 je nejblíž tomu, co by se dalo nazvat univerzálním videoformátem: iPhony, telefony s Androidem, chytré televize, každý prohlížeč, Instagram, YouTube, TikTok i každý běžný střihový program ho přijmou bez dalších kodeků. {{fn}} byl ten formát, který vám dělal potíže; MP4 je ten, který je nedělá.',
    'relation.videoContainer.a.other': '{{tn}} je specializovanější než MP4. {{note}} Pokud je vaším cílem prostě „přehraje se všude“, MP4 je bezpečnější volba — sáhněte po {{tn}}, když si o něj konkrétní program nebo zařízení řeklo.',
    'relation.alphaLost.q': 'Co se stane s průhledností při převodu {{fn}} na {{tn}}?',
    'relation.alphaLost.a': '{{tn}} nemá alfa kanál, takže průhledné oblasti nelze přenést — při převodu se vyplní jednolitým pozadím (ve výchozím stavu bílým). Pokud průhledné pozadí ve vašem návrhu opravdu něco dělá, převeďte obrázek raději do PNG nebo WebP, které ho oba zachovají. Jestli je obrázek fotografie zcela bez průhlednosti, nehraje to vůbec žádnou roli.',
    'relation.alphaGained.q': 'Udělá převod {{fn}} na {{tn}} pozadí průhledným?',
    'relation.alphaGained.a': 'Ne — a spousta lidí na to naletí. {{tn}} průhlednost podporuje, jenže soubor {{fn}} žádnou informaci o průhlednosti nemá, kterou by přenesl, takže pozadí zůstane přesně takové, jaké bylo. Co vám převod dá, je soubor schopný průhlednost pojmout, jakmile pozadí v grafickém editoru vyříznete, a k tomu bezeztrátové pixely, které se při práci nezhorší.',
    'relation.reflow.q': 'Bude {{tn}} fungovat v mé čtečce?',
    'relation.reflow.a.epub': 'EPUB čtou Apple Books, Kobo, Google Play Knihy, Calibre a prakticky každá čtečka kromě Kindlu, který chce MOBI nebo AZW3 (Kindle dnes přijímá EPUB i e-mailem). Protože text přetéká, můžete na zařízení měnit velikost písma, aniž byste skončili u posouvání do stran — a to je celý důvod, proč se {{fn}} vůbec převádí.',
    'relation.reflow.a.kindle': '{{tn}} čtou ta zařízení a aplikace Kindle, pro která byl navržen. Protože text přetéká, můžete na zařízení měnit velikost písma, aniž byste skončili u posouvání do stran — a to je celý důvod, proč se {{fn}} vůbec převádí.',

    'compatibility.q': 'Čím soubor {{tn}} potom otevřu?',
    'compatibility.a': '{{note}} K samotnému převodu není třeba nic instalovat — běží na našich serverech a hotový {{tn}} se vrátí do vašeho prohlížeče připravený k otevření, úpravě nebo odeslání dál. Váš původní soubor {{fn}} se nikdy nemění; vždycky vracíme jen nový soubor.',
    'compatibility.noteFallback': '{{tn}} má širokou podporu.',

    'shapeFaq.pdf-merge.q1': 'Zhorší sloučení kvalitu mých PDF?',
    'shapeFaq.pdf-merge.a1': 'Ne. Stránky se do nového dokumentu zkopírují přesně tak, jak jsou, místo aby se znovu vykreslovaly, takže text zůstává označitelný a obrázky si drží původní rozlišení. Sloučený soubor je zhruba tak velký jako originály dohromady — proženěte ho potom nástrojem Komprimovat PDF, pokud na tom záleží.',
    'shapeFaq.pdf-merge.q2': 'Kolik PDF můžu sloučit najednou a záleží na pořadí?',
    'shapeFaq.pdf-merge.a2': 'Můžete najednou přidat tolik souborů, kolik potřebujete, a na pořadí rozhodně záleží: hotový dokument jde v pořadí zobrazeném v seznamu, které můžete před sloučením přetažením změnit. Nejdřív nastavte pořadí, pak slučte — je to rychlejší než to opravovat potom.',
    'shapeFaq.pdf-split.q1': 'Jak vyberu, které stránky se mají vytáhnout?',
    'shapeFaq.pdf-split.a1': 'Napište je do pole pro rozsahy stránek s čárkami a pomlčkami: „1-3, 5, 7-10“ vám dá stránky jedna až tři, stránku pět a stránky sedm až deset v jediném výstupním dokumentu. Čísla odkazují na vlastní stránky PDF počítané od jedničky, což nemusí být totéž jako číslo vytištěné na stránce.',
    'shapeFaq.pdf-split.q2': 'Změní rozdělení původní PDF?',
    'shapeFaq.pdf-split.a2': 'Ne. Soubor, který nahrajete, se nikdy nemění — vytažené stránky se zapíší do nového dokumentu a originál zůstane nedotčený, než se do 24 hodin spolu s výsledkem smaže z našich serverů.',
    'shapeFaq.pdf-compress.q1': 'O kolik se moje PDF zmenší?',
    'shapeFaq.pdf-compress.a1': 'Záleží to zcela na tom, co je uvnitř. PDF, kterým vévodí skeny nebo fotografie, se často zmenší o 50–90 %, protože právě tam je téměř celá velikost. Čistě textové PDF je už kompaktní a možná se skoro nezmění. Text a vektorová grafika zůstanou v obou případech ostré — úspora vzniká opětovným zakódováním obrázků a odstraněním nadbytečných vložených dat.',
    'shapeFaq.pdf-compress.q2': 'Zůstane text i nadále označitelný a prohledatelný?',
    'shapeFaq.pdf-compress.a2': 'Ano. Komprese pracuje na vložených obrázcích a na nadbytečných interních datech; textová vrstva, písma, odkazy a záložky zůstávají nedotčené, takže ve zkomprimovaném souboru budete moci dál hledat, označovat a kopírovat přesně jako předtím.',
    'shapeFaq.pdf-compress-ai.q1': 'Čím se to liší od běžné komprese PDF?',
    'shapeFaq.pdf-compress-ai.a1': 'Běžná komprese aplikuje jedno nastavení na celý soubor. Tenhle nástroj se nejdřív podívá, co každá stránka opravdu obsahuje, takže fotografické obrázky, plošné diagramy a čistě textové strany se každé zpracují tak, jak se ušetří nejvíc místa bez viditelného zhoršení. U smíšených dokumentů to obvykle znamená menší soubor při stejné vnímané kvalitě.',
    'shapeFaq.pdf-compress-ai.q2': 'Zůstane text i nadále označitelný a prohledatelný?',
    'shapeFaq.pdf-compress-ai.a2': 'Ano. Textová vrstva, písma, odkazy i záložky se zachovají — znovu se zakódují jen vložené obrázky a nadbytečná interní data, takže zkomprimované PDF zůstává plně prohledatelné a kopírovatelné.',
    'shapeFaq.pdf-rotate.q1': 'Ztrácí se otočením PDF kvalita?',
    'shapeFaq.pdf-rotate.a1': 'Vůbec ne. Otočení mění geometrii stránek zapsanou v souboru, místo aby cokoli znovu vykreslovalo, takže text zůstává vektorově ostrý, obrázky nedotčené a velikost souboru se sotva pohne. Můžete otáčet znovu i později bez jakéhokoli kumulovaného poškození.',
    'shapeFaq.pdf-rotate.q2': 'Můžu otočit jen některé stránky?',
    'shapeFaq.pdf-rotate.a2': 'Otočení, které zvolíte — o 90°, 180° nebo 270° — se aplikuje na dokument. Pokud jsou různé stránky natočené špatně různým směrem, obvyklý postup je PDF rozdělit, každou část otočit o potřebný úhel a výsledky zase spojit nástrojem Sloučit PDF.',
    'shapeFaq.pdf-protect.q1': 'Co se stane, když heslo zapomenu?',
    'shapeFaq.pdf-protect.a1': 'Soubor nepůjde otevřít. Šifrování se aplikuje na samotné PDF, takže neexistuje žádný odkaz na obnovení ani zadní vrátka — ani pro vás, ani pro nás. Uložte si heslo na bezpečné místo, než dokument pošlete dál, a pošlete ho jiným kanálem než samotný soubor.',
    'shapeFaq.pdf-protect.q2': 'Jak silná ta ochrana je?',
    'shapeFaq.pdf-protect.a2': 'PDF se šifruje oborovým standardem zabudovaným do formátu, takže jeho obsah nepřečte bez hesla žádná čtečka, která standard dodržuje. Praktickým slabým místem není nikdy algoritmus, nýbrž samotné heslo — krátké nebo očividné se rychle uhodne, takže na cokoli opravdu důvěrného použijte dlouhé.',
    'shapeFaq.pdf-unlock.q1': 'Umí to odstranit heslo, které neznám?',
    'shapeFaq.pdf-unlock.a1': 'Ne. Musíte zadat současné heslo; nástroj s ním soubor dešifruje, nikoli prolomí šifrování. Je určen pro dokumenty, které vlastníte nebo máte oprávnění otevřít — třeba výpis z vaší vlastní banky — kde omezení jen překáží.',
    'shapeFaq.pdf-unlock.q2': 'Co můžu se souborem potom dělat?',
    'shapeFaq.pdf-unlock.a2': 'Všechno, co ochrana blokovala: otevřít ho bez dotazu, vytisknout, kopírovat z něj text a upravovat ho v jiném softwaru. Samotný obsah stránek zůstává nezměněný — odstraní se jen šifrovací vrstva a její omezení použití.',
    'shapeFaq.metadata.q1': 'Změní to nějak můj soubor?',
    'shapeFaq.metadata.a1': 'Ne. Soubor se čte, nikoli převádí — nic se nezapisuje zpět a nevzniká nic nového kromě informací na obrazovce. Je to nejbezpečnější nástroj tady, kterým můžete namířit na soubor, kterým si nejste jistí.',
    'shapeFaq.metadata.q2': 'Jaké informace uvidím?',
    'shapeFaq.metadata.a2': 'Záleží na souboru. Obrázky ukážou rozměry, barevnou hloubku a data EXIF jako model fotoaparátu, objektiv, expozici a, pokud je fotoaparát zaznamenal, souřadnice GPS. Zvuk ukáže délku, datový tok, vzorkovací frekvenci a počet kanálů. Video přidá kodek, rozlišení a snímkovou frekvenci. Dokumenty ukážou počet stran, autora, tvůrce a datum vytvoření.',
    'shapeFaq.ocr.q1': 'Jak přesné je rozpoznávání textu?',
    'shapeFaq.ocr.a1': 'Čistý, rovný sken tištěného textu v rozumném rozlišení se rozpozná velmi přesně. Přesnost klesá u pokřivených či rozmazaných stránek, málo kontrastních fotografií, neobvyklých písem a rukopisu. Na volbě správného jazyka záleží, protože rozpoznávání ho používá k rozřešení nejednoznačných znaků.',
    'shapeFaq.ocr.q2': 'Jaký je rozdíl mezi prohledatelným PDF a výstupem v prostém textu?',
    'shapeFaq.ocr.a2': 'Prohledatelné PDF ponechá původní obraz stránky přesně tak, jak vypadá, a přidá pod něj neviditelnou textovou vrstvu, takže dokument vypadá nezměněně, ale nyní v něm lze hledat a kopírovat z něj — přesně to chcete pro archivaci. Prostý text zahodí sazbu a dá vám jen slova, což zase chcete pro úpravy, skriptování nebo podání jinému programu.',
    'shapeFaq.tts.q1': 'Jak přirozeně ty hlasy znějí?',
    'shapeFaq.tts.a1': 'Jde o neuronové hlasy, nikoli o starší slepovanou syntézu řeči, takže nesou větnou intonaci a přirozené pauzy, místo aby četly slovo po slově. K výběru je šest hlasů, od neutrálního přes vřelý po autoritativní, a rychlost řeči lze nastavit. Na interpunkci záleží víc, než si lidé myslí: čárky a tečky utvářejí frázování, takže dobře odinterpunktovaný text se čte znatelně lépe.',
    'shapeFaq.tts.q2': 'Kolik textu můžu převést najednou?',
    'shapeFaq.tts.a2': 'Až 4096 znaků na jeden převod — hrubě 600 až 700 slov, tedy asi pět minut řeči. U delších textů je rozdělte v přirozeném místě, třeba na nadpisu kapitoly nebo oddílu, a převádějte každou část zvlášť; nastavení hlasu a rychlosti zůstává mezi průchody stejné, takže kusy na sebe čistě navážou.',
    'shapeFaq.stt.q1': 'Jak přesný je přepis?',
    'shapeFaq.stt.a1': 'Zřetelná řeč v rozumně tichém prostředí se přepisuje velmi přesně, a to i u širokého spektra přízvuků. Přesnost klesá při silném hluku v pozadí, když si několik lidí skáče do řeči, nebo u velmi specializovaného žargonu a vlastních jmen. Nastavit mluvený jazyk místo automatické detekce znatelně pomáhá.',
    'shapeFaq.stt.q2': 'Můžu nahrávat rovnou z mikrofonu?',
    'shapeFaq.stt.a2': 'Ano — rekordér na téhle stránce zachytává zvuk přímo v prohlížeči, což bývá rychlejší než nejdřív hledat nahrávací aplikaci. Prohlížeč si při prvním použití vyžádá povolení k mikrofonu. Můžete také nahrát existující soubor a přepis se objeví na stránce, takže si ho můžete přečíst, než si ho stáhnete jako TXT nebo DOCX.',
    'shapeFaq.subtitle.q1': 'Jak přesné jsou vygenerované titulky?',
    'shapeFaq.subtitle.a1': 'Zřetelná řeč se přepisuje velmi přesně, i s přízvukem. Hudba v pozadí, překřikování a odborná terminologie jsou místa, kde se vloudí chyby, a nastavit mluvený jazyk místo automatické detekce pomáhá. Výstupem je titulkový soubor v prostém textu, takže opravit tu a tam slovo zabere v libovolném textovém editoru pár vteřin.',
    'shapeFaq.subtitle.q2': 'Mám zvolit SRT, nebo VTT?',
    'shapeFaq.subtitle.a2': 'SRT je bezpečnější výchozí volba: YouTube, Vimeo, Premiere, Final Cut, VLC a prakticky každý přehrávač ho přijmou. Zvolte VTT, pokud titulky míří do HTML5 videopřehrávače na webu, protože WebVTT je formát, který nativní titulková stopa prohlížeče očekává, a podporuje stylování i umístění, jaké SRT vyjádřit neumí.',
    'shapeFaq.soon.q1': 'Kdy to bude k dispozici?',
    'shapeFaq.soon.a1': 'Aktivně se na tom pracuje. Nástroj se tady objeví a začne přijímat soubory, jakmile bude hotový — na vaší straně není třeba nic instalovat ani zapínat.',
    'shapeFaq.soon.q2': 'Co můžu zatím používat?',
    'shapeFaq.soon.a2': 'Zbytek převodníku je plně k dispozici: dokumenty, obrázky, zvuk, video, archivy, GIFy i sada nástrojů pro PDF fungují už dnes, stejně jako chytré funkce pro OCR, přepis a titulky.',
    'shapeFaq.compress.q1': 'Bude zkomprimovaný soubor pořád {{fn}}?',
    'shapeFaq.compress.a1': 'Ano — formát se nemění, jen velikost. To, co si stáhnete, je obyčejný {{fn}}, který se otevře všude, kde se otevíral originál.{{alpha}} Kolik ušetříte, závisí na zdrojovém materiálu: {{source}}.',
    'shapeFaq.compress.alpha': ' Průhlednost i animace se zachovají.',
    'shapeFaq.compress.source.png': 'snímky obrazovky a plošná grafika rozhraní se komprimují dramaticky, kdežto z fotografií uložených jako PNG toho vypadne méně',
    'shapeFaq.compress.source.gif': 'dlouhé animace a neklidný materiál se komprimují nejvíc, protože je víc opakování k odstranění',
    'shapeFaq.compress.source.other': 'fotografie se komprimují dobře, kdežto obrázky, které už byly silně zkomprimované, toho mají méně co dát',
    'shapeFaq.compress.q2': 'O kolik se soubor zmenší?',
    'shapeFaq.compress.a2': 'Obvykle někam mezi třetinu a desetinu originálu, zcela podle toho, co soubor obsahuje a jak byl původně uložen. Po dokončení převodu stránka ukáže velikost před a po vedle sebe, takže vidíte skutečnou úsporu, místo abyste hádali.',
    'shapeFaq.hub.q1': 'Mezi jakými formáty můžu převádět?',
    'shapeFaq.hub.a1': 'Vstup: {{inputs}}. Výstup: {{outputs}}. Libovolný vstup může jít na libovolný výstup, takže nemusíte hledat zvláštní stránku pro každou kombinaci — vyberte soubor, vyberte cílový formát, převeďte.',
    'shapeFaq.hub.q2': 'Přijdu o kvalitu?',
    'shapeFaq.hub.a2': 'Záleží na dvojici. Přechod do bezeztrátového formátu zachová všechno, ale vytvoří větší soubor; přechod do komprimovaného formátu záměrně zahodí část dat výměnou za velikost a v pokročilém nastavení si určíte, kde na tomhle kompromisu chcete stát. Převod mezi dvěma komprimovanými formáty pokaždé upustí trochu detailu, takže se vyplatí ponechat si originál jako hlavní kopii.',
    'shapeFaq.hub-extract.q1': 'Zůstane při tom i video?',
    'shapeFaq.hub-extract.a1': 'Ne — jen zvuk. Zvuková stopa se z videa vyzvedne a uloží samostatně, a proto je výsledek zlomkem původní velikosti souboru. Zvuk se nenahrává znovu, takže si drží kvalitu, kterou už uvnitř videa měl; z klipu s nízkým datovým tokem nelze získat zvuk s vysokým.',
    'shapeFaq.hub-extract.q2': 'Který výstupní formát mám zvolit?',
    'shapeFaq.hub-extract.a2': 'MP3 pro maximální kompatibilitu — přehraje se v každém telefonu, autorádiu i přehrávači. AAC nebo M4A, pokud cílem je zařízení Applu nebo moderní aplikace, protože při stejném datovém toku znějí o něco lépe. WAV nebo FLAC jen tehdy, pokud budete zvuk upravovat, protože oba jsou bezeztrátové a odpovídajícím způsobem objemné.',
    'shapeFaq.hub-gif.q1': 'Proč GIF vypadá hůř než originál?',
    'shapeFaq.hub-gif.a1': 'Protože GIF povoluje jen 256 barev na snímek, kdežto video a fotografie jich obsahují miliony. Kodér vybere paletu a zbytek přiblíží, což se projeví jako pruhy v přechodech a na obloze. GIF navíc nenese vůbec žádný zvuk. Oba limity patří k formátu, nikoli k převodu.',
    'shapeFaq.hub-gif.q2': 'Proč je můj soubor GIF tak velký?',
    'shapeFaq.hub-gif.a2': 'GIF komprimuje mnohem méně účinně než moderní videokodeky, takže velikost souboru rychle roste s délkou, rozlišením a snímkovou frekvencí. Pár vteřin je ideální rozsah. Pokud je výsledek příliš těžký, klip zkraťte, a pokud velikost váží víc než vložené automatické přehrávání, MP4 ukáže tutéž animaci na zlomku velikosti.',
  },
};
