// Spanish content pack. Mirrors packs/en.js key for key — see the header there.
export default {
  lang: 'es',
  formats: {
    pdf: { about: 'El PDF es un formato de maquetación fija: guarda la posición exacta de cada carácter, cada línea y cada imagen, por eso un PDF se ve idéntico en cualquier pantalla o impresora pero resulta incómodo de editar.', note: 'El PDF fija la paginación, las tipografías y la maquetación, así que el destinatario ve exactamente lo que usted envió.' },
    docx: { about: 'DOCX es el formato moderno de Microsoft Word, donde el texto vive en párrafos y estilos editables en lugar de estar clavado a coordenadas de página fijas.', note: 'DOCX le devuelve párrafos realmente editables, control de cambios y comentarios en Word, Google Docs o LibreOffice.' },
    xlsx: { about: 'XLSX es el formato de hoja de cálculo de Excel, donde cada valor ocupa una celda direccionable que se puede ordenar, filtrar y usar en una fórmula.', note: 'Una vez que los datos están en XLSX puede sumarlos, ordenarlos, cruzarlos en tablas dinámicas y graficarlos en lugar de volver a teclearlos.' },
    pptx: { about: 'PPTX guarda una presentación como diapositivas independientes, con cuadros de texto editables, formas, notas del orador y transiciones.', note: 'PPTX le devuelve diapositivas que puede volver a editar, reordenar y presentar de nuevo.' },
    txt: { about: 'Un archivo TXT no es más que caracteres — sin tipografías, sin imágenes, sin estructura de página — lo que lo hace diminuto, legible en cualquier parte y trivial de buscar.', note: 'TXT elimina todo salvo las palabras, que es exactamente lo que quieren los scripts, los índices de búsqueda y los editores de texto.' },
    html: { about: 'HTML es el lenguaje de marcado de la web: texto envuelto en etiquetas que un navegador convierte en títulos, párrafos, enlaces e imágenes.', note: 'El HTML se abre en cualquier navegador y se puede pegar directamente en una web o un CMS.' },
    rtf: { about: 'RTF es un formato de documento abierto basado en texto plano que lleva formato básico — negrita, cursiva, tipografías, tablas — sin encerrarle en un único procesador de textos.', note: 'RTF se abre en Word, Pages, LibreOffice, WordPad y prácticamente cualquier procesador de textos jamás escrito.' },
    odt: { about: 'ODT es el formato de texto OpenDocument que usan LibreOffice y OpenOffice, y es una norma ISO en lugar de un formato de un fabricante.', note: 'ODT es el formato nativo y totalmente editable de LibreOffice y OpenOffice.' },
    epub: { about: 'EPUB es un formato de libro electrónico de texto fluido: no tiene tamaño de página fijo, así que el texto se reajusta a la pantalla y al tamaño de letra que use el lector.', note: 'EPUB permite al lector cambiar el tamaño de letra y reajustar el texto, que es lo que hace cómodos los documentos largos en el móvil o en un lector electrónico.' },
    jpg: { about: 'JPG usa compresión con pérdida pensada para fotografías: descarta el detalle que el ojo menos nota, lo que aligera las fotos pero añade artefactos blandos y cuadriculados alrededor de los bordes duros y del texto.', note: 'JPG produce archivos pequeños que se abren literalmente en todas partes, a costa de algo de detalle descartado para siempre y de no admitir transparencia.' },
    jfif: { about: 'JFIF es una imagen JPEG guardada con otra extensión; los píxeles de dentro son datos JPEG corrientes, pero Windows a menudo se niega a entregar el archivo a la aplicación que usted quiere.', note: 'JFIF en realidad no es más que JPEG con otro nombre.' },
    png: { about: 'PNG es sin pérdida: guarda cada píxel exactamente, admite un canal alfa completo para la transparencia y nunca se degrada al volver a guardarlo, por eso es el formato de referencia para capturas de pantalla, logotipos y gráficos de interfaz.', note: 'PNG conserva cada píxel tal cual y admite transparencia real, así que sobrevive a ediciones repetidas sin degradarse.' },
    webp: { about: 'WebP es el formato de imagen web moderno de Google; comprime bastante más que JPG o PNG con calidad parecida y admite transparencia y animación, pero muchos programas de escritorio y de imprenta todavía no pueden abrirlo.', note: 'WebP produce los archivos más pequeños de los formatos web habituales y admite transparencia.' },
    bmp: { about: 'BMP guarda datos de píxel en bruto, prácticamente sin comprimir, lo que lo hace perfectamente fiel y enormemente derrochador — una foto puede ocupar fácilmente diez veces más que la misma imagen en PNG.', note: 'BMP es puro y sin comprimir, que es lo que todavía esperan los programas antiguos de Windows y algunos escáneres.' },
    tiff: { about: 'TIFF es el formato de archivo y preimpresión: sin pérdida, gran profundidad de color, capaz de contener varias páginas o capas — y voluminoso en consecuencia.', note: 'TIFF es el formato que piden imprentas y archivos porque no se descarta nada.' },
    gif: { about: 'GIF está limitado a una paleta de 256 colores por fotograma, por eso las fotografías se ven con bandas, pero se anima y se reproduce solo dentro de casi cualquier sitio de internet.', note: 'GIF se anima y se reproduce solo dentro de aplicaciones de mensajería, gestores de incidencias y foros, aunque está limitado a 256 colores por fotograma.' },
    ico: { about: 'ICO es un contenedor de iconos de Windows que guarda el mismo dibujo en varios tamaños a la vez, para que el sistema pueda elegir 16×16 para una pestaña y 256×256 para un acceso directo del escritorio.', note: 'ICO agrupa varias resoluciones en un solo archivo, que es justo lo que necesitan los favicons y los iconos de aplicaciones de Windows.' },
    heic: { about: 'HEIC es el formato en el que los iPhone guardan las fotos por defecto; ofrece más o menos la misma calidad que JPG en aproximadamente la mitad de espacio, pero Windows, muchos formularios web y bastante software antiguo simplemente se niegan a abrirlo.', note: 'HEIC es compacto pero está mal soportado fuera de los dispositivos Apple.' },
    svg: { about: 'SVG no está hecho de píxeles en absoluto — es XML que describe formas, trazados y texto, así que se mantiene perfectamente nítido a cualquier tamaño y se puede editar o reestilizar con código.', note: 'SVG escala a cualquier tamaño sin volverse borroso nunca, porque guarda formas en lugar de píxeles.' },
    mp4: { about: 'MP4 es un contenedor — normalmente vídeo H.264 con audio AAC — y es el único formato de vídeo en el que coinciden móviles, navegadores, televisores, editores y plataformas sociales.', note: 'MP4 se reproduce en prácticamente cualquier móvil, navegador, televisor y editor sin instalar nada.' },
    avi: { about: 'AVI es un contenedor de Microsoft de los años noventa; los reproductores y suites de edición antiguos todavía lo leen, pero no tiene funciones modernas de transmisión y sus archivos suelen ser mucho más grandes que los MP4.', note: 'AVI es lo que esperan los reproductores antiguos, las herramientas de autoría de DVD y el software de edición heredado.' },
    mov: { about: 'MOV es el contenedor QuickTime de Apple, el formato en el que graban iPhone y Mac y el que Final Cut Pro e iMovie manejan con más comodidad.', note: 'MOV es el contenedor con el que las herramientas de edición de Apple trabajan con más soltura.' },
    mkv: { about: 'MKV (Matroska) es un contenedor abierto que puede albergar cualquier número de pistas de vídeo, audio y subtítulos en un solo archivo — excelente para archivar, pero rechazado por la mayoría de móviles, televisores y navegadores.', note: 'MKV puede llevar varias pistas de audio y de subtítulos en un único archivo.' },
    webm: { about: 'WebM es el contenedor libre de regalías creado para el vídeo HTML5, normalmente con VP9 o AV1; los navegadores lo adoran, pero los editores de escritorio y el software de Apple a menudo ni lo tocan.', note: 'WebM es ligero y se transmite de forma nativa en los navegadores.' },
    wmv: { about: 'WMV es el formato de vídeo Windows Media de Microsoft, en la práctica exclusivo de Windows y muy abandonado salvo en viejas grabaciones corporativas y capturas de pantalla.', note: 'WMV es un formato de Windows Media con muy poco soporte fuera de ahí.' },
    flv: { about: 'FLV era el contenedor detrás del vídeo Flash, y desde que Flash se retiró de todos los navegadores es en la práctica un formato de archivo irreproducible.', note: 'FLV es un contenedor muerto de la época de Flash.' },
    mp3: { about: 'MP3 es con pérdida: el codificador borra para siempre las partes de la señal que prevé que usted no oirá, lo que reduce una pista a alrededor de una décima parte de su tamaño y explica que se reproduzca absolutamente en todo.', note: 'MP3 es unas diez veces más pequeño que el audio sin comprimir y se reproduce en cualquier móvil, equipo de coche y reproductor de los últimos veinte años.' },
    wav: { about: 'WAV guarda el audio sin comprimir, muestra a muestra, exactamente como se grabó — por eso lo usan los estudios y por eso un minuto de estéreo con calidad de CD ocupa unos 10 MB.', note: 'WAV es sin comprimir y sin pérdida, así que los editores y las herramientas de masterización pueden procesarlo sin decodificar nada antes.' },
    flac: { about: 'FLAC comprime el audio sin pérdida: ocupa aproximadamente la mitad que un WAV y aun así se decodifica en una copia idéntica bit a bit de la grabación original.', note: 'FLAC es idéntico bit a bit pero ocupa alrededor de la mitad que un WAV.' },
    aac: { about: 'AAC es el códec con pérdida detrás de Apple Music, YouTube y la mayoría de servicios de streaming; a igual tasa de bits suele sonar mejor que MP3.', note: 'AAC suena mejor que MP3 a igual tasa de bits y es el estándar en las plataformas de Apple y de streaming.' },
    ogg: { about: 'OGG Vorbis es un códec con pérdida libre de patentes, favorito de los videojuegos, el software libre y Wikipedia, con calidad comparable a MP3 en menos espacio.', note: 'OGG está libre de restricciones de patentes, y por eso lo prefieren los motores de videojuegos y los proyectos de código abierto.' },
    m4a: { about: 'M4A es un contenedor MP4 que solo lleva audio, normalmente AAC — el formato que producen iTunes, Apple Music y las notas de voz del iPhone.', note: 'M4A es el archivo de audio estándar del ecosistema Apple.' },
    wma: { about: 'WMA es el códec de audio con pérdida de Microsoft de la época del Reproductor de Windows Media, rara vez soportado fuera de Windows y en la práctica descontinuado.', note: 'WMA es un códec de audio heredado y exclusivo de Windows.' },
    zip: { about: 'ZIP es el formato de archivo comprimido integrado en Windows, macOS y todos los móviles — basta un doble clic, sin instalar nada más.', note: 'ZIP se abre con un doble clic en Windows, macOS, Linux, iOS y Android sin instalar nada.' },
    rar: { about: 'RAR es un formato de archivo propietario con buena compresión y registros de recuperación, pero necesita WinRAR o una herramienta compatible para abrirse.', note: 'RAR necesita software de terceros para extraerse.' },
    '7z': { about: '7Z usa compresión LZMA, que de forma habitual produce archivos bastante más pequeños que ZIP — a cambio de requerir 7-Zip o una herramienta compatible para abrirlos.', note: '7Z comprime bastante más que ZIP, lo que importa con carpetas grandes y almacenamiento en la nube de pago.' },
    tar: { about: 'Un archivo TAR agrupa muchos archivos en uno sin comprimirlos; viene del mundo Unix y conserva permisos y estructura de directorios.', note: 'TAR conserva los permisos de Unix y la estructura de directorios.' },
    gz: { about: 'GZ (gzip) comprime un único flujo de datos y es lo que producen los servidores Linux y las herramientas de línea de comandos; en Windows resulta incómodo de abrir sin software adicional.', note: 'GZ es el formato de compresión estándar en Linux y en los servidores web.' },
    srt: { about: 'SRT es el formato de subtítulos en texto plano que entienden todos los editores de vídeo y todos los reproductores: entradas numeradas, un rango de código de tiempo y la línea de diálogo.', note: 'SRT lo aceptan YouTube, Vimeo, Premiere, Final Cut y todos los reproductores habituales.' },
  },
  reasons: {
    'pdf-to-word': 'El detonante habitual es un cambio que no se puede hacer en el propio PDF — una cláusula de contrato, una línea del currículum o un párrafo de un informe que hay que modificar sin volver a teclear el documento entero.',
    'word-to-pdf': 'Word se convierte a PDF al final de la vida del documento: al enviar un currículum, un presupuesto o un formulario firmado a alguien cuyas tipografías, versión de Word y márgenes usted no controla.',
    'pdf-to-excel': 'El caso típico es un extracto bancario, una factura o un informe que solo existe en PDF pero cuyos números necesita sumar, ordenar o representar.',
    'excel-to-pdf': 'Esto se hace antes de enviar un presupuesto o una lista de precios a alguien que debe leerla pero no cambiarla, y antes de imprimir: un PDF fija los saltos de página que Excel recalcularía en cada equipo.',
    'pptx-to-pdf': 'La mayoría convierte una presentación a PDF antes de enviarla o repartirla, para que las diapositivas no se descoloquen y nadie necesite tener PowerPoint instalado para abrirlas.',
    'pdf-to-pptx': 'Esto es lo que necesita cuando la única copia que sobrevive de una presentación es el PDF que circuló tras la reunión y tiene que actualizar o reutilizar las diapositivas.',
    'pdf-to-txt': 'Motivos habituales: alimentar un script, un índice de búsqueda o una herramienta de IA, o reducir un informe largo a algo que se pueda buscar, comparar y pegar en cualquier parte.',
    'pdf-to-html': 'Es la forma más rápida de publicar en una web un informe, un manual o un folleto ya existentes sin reconstruir la página a mano.',
    'html-to-pdf': 'Se hace para archivar una página web exactamente como se ve hoy, o para convertir una plantilla HTML de factura o informe en algo imprimible y enviable.',
    'rtf-to-pdf': 'El RTF suele salir de software antiguo o de plantillas de documentos jurídicos; pasarlo a PDF le da un archivo que se abre igual en todas partes y que no puede modificarse por accidente.',
    'pdf-to-rtf': 'Es la opción a la que recurrir cuando necesita una copia editable de un PDF pero no puede dar por hecho que el destinatario tenga Word: prácticamente cualquier procesador de textos jamás escrito abre RTF.',
    'odt-to-pdf': 'El caso típico: usted redactó el documento en LibreOffice u OpenOffice y quien lo recibe usa Microsoft Office, o nada en absoluto.',
    'pdf-to-epub': 'Leer un PDF en el móvil significa hacer zoom y desplazarse en horizontal sin parar; esta conversión trata sobre todo de hacer que un documento largo sea de verdad legible en una pantalla pequeña o en un lector electrónico.',
    'epub-to-pdf': 'EPUB se convierte a PDF cuando se quiere imprimir un libro, anotarlo con números de página fijos o enviárselo a alguien que no tiene ninguna aplicación de lectura instalada.',
    'document-converter': 'Es la herramienta que se abre cuando le entregan un documento en el formato que casualmente tenía el remitente y usted lo necesita en el que su propio software abre de verdad.',
    'ebook-converter': 'Las tiendas y los dispositivos de libros electrónicos favorecen cada uno su formato, así que esto es lo que se usa para mover un libro de su propiedad de un lector o una aplicación a otra.',
    'jpg-to-png': 'El detonante habitual es la edición: hay que recortar un fondo, colocar un logotipo sobre otra imagen o evitar que una captura de pantalla se vuelva más borrosa cada vez que se vuelve a guardar.',
    'png-to-jpg': 'Es la solución para una captura de pantalla o una exportación demasiado grande para adjuntarla a un correo o para pasar el límite de tamaño de un formulario de subida.',
    'webp-to-png': 'Normalmente se necesita después de guardar una imagen de una web: WebP se descarga sin problema, pero los editores antiguos, el software ofimático y algunos servicios de impresión todavía se niegan a abrirlo.',
    'webp-to-jpg': 'La mayoría hace esto para llevar una imagen de una web a algo aceptado universalmente: un correo, un CMS antiguo, un servicio de revelado fotográfico o el software prehistórico de un compañero.',
    'heic-to-jpg': 'Este es el problema clásico del iPhone: las fotos se ven perfectas en el móvil pero llegan a un PC con Windows o a un formulario web como archivos .heic imposibles de abrir.',
    'heic-to-png': 'Úselo cuando piense editar la foto y no solo compartirla — PNG le entrega a su editor píxeles sin pérdida en lugar de una copia recién recomprimida.',
    'svg-to-png': 'El motivo habitual es una herramienta que rechaza los vectores: una presentación, un anuncio en un marketplace, una firma de correo o una cadena de iconos de aplicación que solo acepta píxeles.',
    'svg-to-jpg': 'Esto es para sitios que quieren un archivo sencillo de tipo fotográfico — un documento, una publicación en redes o un formulario de subida que rechaza tanto el marcado SVG como la transparencia.',
    'bmp-to-png': 'Los archivos BMP salen de software antiguo de Windows y de escáneres con tamaños absurdos; PNG guarda exactamente los mismos píxeles en una fracción del espacio.',
    'tiff-to-jpg': 'Escáneres y cámaras profesionales producen TIFF demasiado grandes para el correo, así que JPG es lo que se envía una vez que la copia de archivo está a buen recaudo.',
    'gif-to-png': 'Esto es lo que se hace con un GIF estático — un logotipo, un icono o un fotograma exportado — que muestra bandas de color o un borde deshilachado por el límite de 256 colores.',
    'png-to-ico': 'Casi todo el que convierte PNG a ICO está creando un favicon o un icono de aplicación de Windows, y ambos esperan el contenedor ICO en lugar de un archivo de imagen sin más.',
    'jfif-to-png': 'Los archivos JFIF aparecen típicamente cuando una foto se guarda desde Outlook o desde un navegador y Windows luego se niega a entregarla a la aplicación que usted quería usar.',
    'heic-to-pdf': 'Práctico cuando fotografía documentos, recibos o una pizarra con el iPhone y tiene que entregarlos como un único archivo en lugar de una carpeta de imágenes.',
    'image-compressor': 'El motivo habitual es algún límite estricto — un formulario de subida, un tope de adjuntos de correo o una página web que carga demasiado lenta porque sus imágenes pesan mucho más de lo necesario.',
    'jpeg-compressor': 'Fotógrafos y responsables de webs lo usan cuando los JPEG a resolución completa ralentizan una página o no pasan un límite de subida.',
    'png-compressor': 'Las capturas de pantalla y los gráficos de interfaz exportados pesan a menudo varios megabytes sin buena razón; esto los reduce antes de que acaben en un documento, una incidencia o una página web.',
    'mp4-to-avi': 'El motivo es casi siempre un dispositivo antiguo o un programa concreto — algunos reproductores heredados, herramientas de autoría de DVD y utilidades de cámara leen AVI y nada más.',
    'mp4-to-mov': 'Normalmente es el primer paso antes de editar en un Mac, ya que Final Cut Pro e iMovie manejan los archivos QuickTime con más soltura.',
    'mov-to-mp4': 'iPhone y Mac graban en MOV; todo lo demás espera MP4, así que esta es la conversión que se hace antes de subir, enviar o publicar un clip.',
    'mkv-to-mp4': 'MKV es excelente para almacenar, pero móviles, televisores, navegadores y la mayoría de editores no lo reproducen — convertir a MP4 es lo que hace el archivo realmente utilizable.',
    'webm-to-mp4': 'Los archivos WebM guardados de la web a menudo se niegan a abrirse en QuickTime, en iOS o en Premiere; MP4 es el formato que todos aceptan.',
    'avi-to-mp4': 'Es el rescate estándar para material antiguo de videocámara y clips archivados que devoran gigabytes y no se reproducen en ningún móvil.',
    'flv-to-mp4': 'Flash ha desaparecido de todos los navegadores, así que cualquier FLV que conserve es en la práctica irreproducible — convertirlo a MP4 es lo que mantiene visible ese material archivado.',
    'wmv-to-mp4': 'WMV es un resto exclusivo de Windows, así que esto es lo que se hace antes de enviar una grabación antigua o una captura de pantalla a un Mac, un iPhone o una plataforma web.',
    'mp4-to-mp3': 'Lo que importa suele ser el sonido y no la imagen — una clase, una entrevista, un pódcast o un videoclip que quiere en el móvil sin cargar con el vídeo.',
    'video-to-mp3': 'Se recurre a esto cuando el audio es la parte que merece conservarse: una charla grabada, una entrevista, un ensayo o una banda sonora.',
    'mp4-converter': 'Es la herramienta a usar cuando un clip no se reproduce o no se sube, porque MP4 es el único formato de vídeo que móviles, navegadores, televisores y plataformas sociales aceptan todos.',
    'video-converter': 'Úselo cuando un clip tenga que cambiar de mundo — salir de un editor, entrar en un móvil, cargarse en un navegador o llegar a una plataforma que solo admite un contenedor concreto.',
    'mp3-to-wav': 'El motivo habitual es la edición: las estaciones de audio digital, las cadenas de masterización y muchos flujos de audio para radiodifusión o videojuegos quieren WAV sin comprimir para no decodificar un archivo comprimido en cada operación.',
    'wav-to-mp3': 'Las grabaciones salen de una grabadora de campo o de una estación de audio como enormes archivos WAV; MP3 es lo que las hace lo bastante pequeñas para enviarlas, subirlas o llevarlas en el móvil.',
    'flac-to-mp3': 'Una biblioteca FLAC suena estupenda en casa, pero los equipos de coche, los móviles antiguos y los reproductores baratos a menudo la rechazan — MP3 es la copia de compatibilidad que se lleva encima.',
    'aac-to-mp3': 'Es sobre todo una cuestión de compatibilidad: AAC viene de los ecosistemas de Apple y del streaming, mientras que los reproductores antiguos, las radios de coche y el software de DJ esperan MP3.',
    'ogg-to-mp3': 'OGG aparece en videojuegos, en Wikipedia y en software libre, y casi ninguno de los reproductores habituales de un móvil o de un coche lo abre.',
    'wma-to-mp3': 'WMA es una reliquia de la época del Reproductor de Windows Media, así que así es como se rescata una vieja colección de música extraída para el móvil o para una biblioteca de streaming.',
    'm4a-to-mp3': 'Es el paso habitual al sacar música o notas de voz del iPhone de los dispositivos Apple hacia software, coches o reproductores que solo entienden MP3.',
    'mp3-to-aac': 'Algunos dispositivos y aplicaciones — sobre todo en Apple y en las plataformas de streaming — prefieren AAC, así que esto es una conversión de compatibilidad y no una mejora de calidad.',
    'mp3-to-ogg': 'Se convierte a OGG para motores de videojuegos, proyectos de código abierto y plataformas donde se exige un códec libre de patentes.',
    'audio-converter': 'Es la herramienta para el momento en que un archivo no se reproduce: un único sitio para llevar el audio a cualquiera de los formatos habituales en el que insista su dispositivo, su editor o su formulario de subida.',
    'rar-to-zip': 'RAR necesita software adicional para abrirse, así que esto es lo que se hace antes de enviar un archivo comprimido a alguien que no va a instalar WinRAR.',
    '7z-to-zip': '7Z comprime mejor pero exige tener 7-Zip instalado; en ZIP, el destinatario puede simplemente hacer doble clic en el archivo.',
    'tar-to-zip': 'TAR viene de las líneas de comandos de Linux y macOS, mientras que ZIP es lo que un compañero con Windows puede abrir sin instalar absolutamente nada.',
    'gz-to-zip': 'Los archivos GZ suelen llegar de un servidor o de una herramienta de Linux y son incómodos en Windows, donde un ZIP se descomprime con un doble clic.',
    'zip-to-7z': 'Aquí la cuestión es el tamaño: la compresión de 7Z es notablemente más fuerte, lo que importa cuando archiva una carpeta grande o paga el almacenamiento en la nube por gigabyte.',
    'video-to-gif': 'El uso típico es un bucle corto para un mensaje de chat, un README, un informe de error o una publicación en redes — sitios donde un GIF se reproduce solo dentro y un archivo de vídeo no.',
    'mp4-to-gif': 'El uso típico es un bucle corto para un chat, un README, un informe de error o una publicación, donde un GIF se reproduce solo dentro mientras que un vídeo se quedaría ahí como un adjunto.',
    'webm-to-gif': 'Los clips WebM guardados de la web a menudo no se incrustan donde usted quiere, mientras que un GIF se reproduce dentro de aplicaciones de mensajería, gestores de incidencias y foros.',
    'mov-to-gif': 'Esto es lo que se hace con una grabación de pantalla de QuickTime que debe aparecer incrustada en una pull request, un ticket de soporte o una publicación.',
    'avi-to-gif': 'Convertir unos segundos de un clip AVI antiguo en un GIF es la forma más sencilla de meterlos en un documento, un hilo de chat o una página web.',
    'gif-to-mp4': 'Los GIF largos son enormes y se reproducen a tirones; MP4 muestra la misma animación por una fracción del tamaño, que es exactamente por lo que las plataformas sociales los convierten entre bastidores.',
    'image-to-gif': 'Útil cuando una plataforma o un sistema antiguo espera expresamente un GIF, o cuando necesita un fotograma fijo en el mismo formato que una serie de animaciones existente.',
    'gif-compressor': 'Los GIF animados se hinchan deprisa, y esta es la solución cuando uno pesa demasiado para un correo, un límite de subida en un chat o una página que tiene que cargar rápido.',
    'merge-pdf': 'El caso clásico es una solicitud o un parte: un formulario, un escaneo y un recibo que tienen que llegar todos como un único documento.',
    'split-pdf': 'Normalmente necesita exactamente una cosa de un archivo mucho más largo — un capítulo, una factura, una página firmada de un escaneo de cincuenta páginas.',
    'compress-pdf': 'Casi siempre un límite de tamaño: un tope de adjuntos de correo, un formulario de la administración o un portal que rechaza cualquier cosa que pase de unos pocos megabytes.',
    'rotate-pdf': 'Esto arregla el problema cotidiano del escáner: páginas que salieron de lado o boca abajo por cómo se introdujeron las hojas.',
    'protect-pdf': 'Los PDF se protegen con contraseña antes de enviar nóminas, contratos o informes médicos, para que el contenido no sea legible por quien reciba el mensaje reenviado a continuación.',
    'unlock-pdf': 'Úselo con documentos de su propiedad cuando conoce la contraseña pero la restricción estorba — un extracto bancario que no puede imprimir, por ejemplo.',
    'view-metadata': 'Responde a las preguntas que un archivo no le cuenta directamente: qué cámara hizo esta foto, cuánto dura realmente esta grabación, qué códec lleva dentro este vídeo, cuántas páginas tiene este PDF.',
    'ocr': 'La situación es siempre la misma: tiene un documento como imagen y necesita las palabras que contiene — para buscarlas, citarlas, editarlas o archivarlas como es debido.',
    'pdf-compress-ai': 'Recurra a él cuando ya haya probado la compresión normal y el archivo siga siendo demasiado grande para el límite de subida contra el que está peleando.',
    'text-to-speech': 'Se usa para escuchar algo en lugar de leerlo — un artículo en el trayecto al trabajo, un guion leído en voz alta para detectar frases forzadas, o una voz en off para un vídeo.',
    'speech-to-text': 'El caso habitual es una grabación que necesita por escrito: una reunión, una entrevista, una clase o una nota de voz que tiene que convertirse en apuntes, un acta o una transcripción citable.',
    'auto-subtitle': 'Los subtítulos son lo que hace un vídeo visible sin sonido y localizable por los buscadores, y teclearlos a mano lleva, incluso en un clip corto, mucho más tiempo del que la gente imagina.',
    'document-translation': 'El objetivo es leer o enviar un documento en otro idioma sin perder la maquetación que lo hace legible.',
  },
  t: {
    'list.and': 'y',
    'family.document': 'documento',
    'family.image': 'imagen',
    'family.video': 'vídeo',
    'family.audio': 'audio',
    'family.ebook': 'libro electrónico',
    'family.archive': 'archivo comprimido',
    'family.subtitle': 'subtítulos',
    'family.none': 'archivo',
    'unit.sample': 'cada muestra',
    'unit.pixel': 'cada píxel',

    'intro.convert': '{{fromAbout}} {{toAbout}} {{reason}} {{toNote}}',
    'intro.convert.noSource': 'El {{fn}} es el formato de origen de esta conversión.',
    'intro.lead': '{{lead}} {{reason}}',
    'intro.hub': 'Este es el conversor de {{category}} de uso general: acepta {{inputs}} y escribe {{outputs}}, así que no tiene que buscar la herramienta concreta que coincide con su par de formatos. {{reason}} Elija arriba su formato de salida y la conversión se resuelve en el servidor: nada que instalar.',
    'intro.hubExtract': 'Esta herramienta extrae la pista de audio de un archivo de vídeo y la guarda por separado, convirtiendo un vídeo en un simple archivo de audio que se reproduce en cualquier parte. Acepta {{inputs}} y escribe {{outputs}}. La pista de vídeo simplemente se descarta, y por eso el resultado ocupa una fracción del tamaño original. {{reason}}',
    'intro.hubGif': 'Esta herramienta convierte archivos {{inputs}} en GIF animados. {{gifAbout}} {{reason}}',
    'intro.hubGif.gifAbout': 'GIF está limitado a una paleta de 256 colores por fotograma, por eso las fotografías se ven con bandas, pero se anima y se reproduce solo dentro de casi cualquier sitio de internet.',
    'intro.compress': '{{about}} Esta herramienta vuelve a codificar su {{fn}} con un tamaño menor sin cambiar de formato, así que lo que descarga sigue siendo un {{fn}} corriente que se abre exactamente donde se abría el original. {{reason}}{{extra}}',
    'intro.compress.lossless': ' Como {{fn}} es sin pérdida, la mayor parte del ahorro viene de una codificación más inteligente y de reducir la paleta, y no de descartar detalle.',
    'intro.soon': '{{reason}} Esta herramienta todavía no está disponible — está en desarrollo activo y aparecerá aquí en cuanto esté lista.',
    'intro.lead.pdf-merge': 'Combinar une varios PDF en un solo archivo, en el orden que usted elija, sin volver a renderizar las páginas: el texto sigue siendo seleccionable y las imágenes conservan su calidad original. El PDF es un formato de maquetación fija: guarda la posición exacta de cada carácter, cada línea y cada imagen, por eso se ve idéntico en todas partes pero resulta incómodo de editar.',
    'intro.lead.pdf-split': 'Dividir extrae de un PDF las páginas que usted indique y las guarda como un documento nuevo, dejando el original intacto. El PDF es un formato de maquetación fija: guarda la posición exacta de cada carácter, cada línea y cada imagen, por eso se ve idéntico en todas partes pero resulta incómodo de editar.',
    'intro.lead.pdf-compress': 'Comprimir un PDF vuelve a codificar las imágenes que contiene y elimina datos incrustados redundantes, que es donde reside casi todo el peso de un PDF grande. El texto y los gráficos vectoriales quedan nítidos.',
    'intro.lead.pdf-compress-ai': 'Esta herramienta analiza qué hay dentro del PDF antes de comprimirlo, de modo que las imágenes fotográficas, los gráficos planos y las páginas de texto se traten cada uno de la forma que más espacio ahorra sin degradarlos de manera visible.',
    'intro.lead.pdf-rotate': 'Girar cambia el indicador de orientación y la geometría de página de un PDF para que las páginas se muestren e impriman del derecho. No se vuelve a renderizar nada, así que no se pierde calidad.',
    'intro.lead.pdf-protect': 'Proteger un PDF cifra su contenido para que no pueda abrirse sin la contraseña que usted establezca. El cifrado se aplica al propio archivo, no a una envoltura a su alrededor.',
    'intro.lead.pdf-unlock': 'Desbloquear elimina la contraseña y las restricciones de uso de un PDF cuya contraseña ya tiene, de modo que vuelva a poder abrirse, imprimirse y copiarse con normalidad.',
    'intro.lead.metadata': 'Todo archivo lleva información sobre sí mismo que no se ve al abrirlo: dimensiones de imagen y ajustes de la cámara, duración y tasa de bits del audio, códec y fotogramas por segundo del vídeo, autor y número de páginas del documento. Esta herramienta lee esos metadatos y se los muestra.',
    'intro.lead.ocr': 'El reconocimiento óptico de caracteres mira una imagen de texto — un escaneo, una foto, una página PDF sin capa de texto — y deduce cuáles son los caracteres, convirtiendo una imagen de palabras en palabras que un ordenador puede buscar, copiar y editar.',
    'intro.lead.tts': 'La síntesis de voz genera audio hablado a partir de texto escrito usando voces neuronales, así que obtiene una grabación de sonido natural en lugar de la salida robótica y plana de los sistemas antiguos.',
    'intro.lead.stt': 'El reconocimiento de voz transcribe el audio hablado a palabras escritas. Maneja el habla natural, los acentos y el ruido de fondo mucho mejor que el antiguo software de dictado, y devuelve una transcripción que usted puede editar.',
    'intro.lead.subtitle': 'El generador de subtítulos transcribe el habla de un vídeo y la escribe con códigos de tiempo, produciendo un archivo de subtítulos estándar en lugar de una simple transcripción.',

    'steps.convert.1.batch': 'Arrastre su archivo {{fn}} a la zona de subida de la parte superior de esta página, o haga clic en ella para buscarlo en su dispositivo. Puede añadir varios archivos — o una carpeta entera — y convertirlos todos de una vez.',
    'steps.convert.1.single': 'Arrastre su archivo {{fn}} a la zona de subida de la parte superior de esta página, o haga clic en ella para buscarlo en su dispositivo.',
    'steps.convert.2.direct': 'Elija {{tn}} como formato de salida y haga clic en Convertir.',
    'steps.convert.2.dropdown': 'Elija {{tn}} como formato de salida en el desplegable y haga clic en Convertir.',
    'steps.convert.2.directMedia': 'Elija {{tn}} como formato de salida, ajuste la calidad o el tamaño en los ajustes avanzados si lo necesita y haga clic en Convertir.',
    'steps.convert.2.dropdownMedia': 'Elija {{tn}} como formato de salida en el desplegable, ajuste la calidad o el tamaño en los ajustes avanzados si lo necesita y haga clic en Convertir.',
    'steps.convert.3': 'Descargue su archivo {{tn}} terminado. El enlace de descarga sigue activo 24 horas, tras lo cual ambos archivos se eliminan automáticamente.',
    'steps.hub.1.batch': 'Arrastre su archivo de {{category}} ({{inputs}} se aceptan todos) a la zona de subida de la parte superior de esta página, o haga clic en ella para buscarlo en su dispositivo. Puede añadir varios archivos — o una carpeta entera — y convertirlos todos de una vez.',
    'steps.hub.1.single': 'Arrastre su archivo de {{category}} ({{inputs}} se aceptan todos) a la zona de subida de la parte superior de esta página, o haga clic en ella para buscarlo en su dispositivo.',
    'steps.hub.2.direct': 'Elija el formato de salida que necesite y haga clic en Convertir.',
    'steps.hub.2.dropdown': 'Elija en el desplegable el formato de salida que necesite y haga clic en Convertir.',
    'steps.hub.2.directMedia': 'Elija el formato de salida que necesite, ajuste la calidad o el tamaño en los ajustes avanzados si lo precisa y haga clic en Convertir.',
    'steps.hub.2.dropdownMedia': 'Elija en el desplegable el formato de salida que necesite, ajuste la calidad o el tamaño en los ajustes avanzados si lo precisa y haga clic en Convertir.',
    'steps.hub.3': 'Descargue su archivo terminado. El enlace de descarga sigue activo 24 horas, tras lo cual ambos archivos se eliminan automáticamente.',
    'steps.pdf-merge.1': 'Añada todos los PDF que quiera combinar — arrástrelos juntos a la zona de subida, o haga clic para seleccionarlos uno tras otro.',
    'steps.pdf-merge.2': 'Arrastre los archivos hasta el orden en que quiere que aparezcan en el documento final.',
    'steps.pdf-merge.3': 'Haga clic en Combinar y descargue el único PDF resultante.',
    'steps.pdf-split.1': 'Suba el PDF del que quiere extraer páginas.',
    'steps.pdf-split.2': 'Escriba las páginas o intervalos que necesita en el campo de intervalos de páginas — por ejemplo 1-3, 5, 7-10.',
    'steps.pdf-split.3': 'Haga clic en Convertir y descargue las páginas extraídas.',
    'steps.pdf-compress.1': 'Arrastre su PDF a la zona de subida, o haga clic para buscarlo.',
    'steps.pdf-compress.2': 'Haga clic en Convertir — el archivo se analiza y sus imágenes y datos incrustados se vuelven a codificar con menor tamaño.',
    'steps.pdf-compress.3': 'Descargue el PDF comprimido y compruebe el ahorro de tamaño que se muestra junto a él.',
    'steps.pdf-rotate.1': 'Suba el PDF cuyas páginas están del revés.',
    'steps.pdf-rotate.2': 'Elija cuánto girarlas — 90°, 180° o 270°.',
    'steps.pdf-rotate.3': 'Haga clic en Convertir y descargue el PDF corregido.',
    'steps.pdf-protect.1': 'Suba el PDF que quiere proteger.',
    'steps.pdf-protect.2': 'Introduzca la contraseña que hará falta para abrirlo y guarde una copia en un lugar seguro.',
    'steps.pdf-protect.3': 'Haga clic en Convertir y descargue el PDF cifrado.',
    'steps.pdf-unlock.1': 'Suba el PDF protegido con contraseña.',
    'steps.pdf-unlock.2': 'Introduzca su contraseña actual para que el archivo pueda descifrarse.',
    'steps.pdf-unlock.3': 'Haga clic en Convertir y descargue el PDF desbloqueado.',
    'steps.metadata.1': 'Arrastre cualquier archivo a la zona de subida — una imagen, un vídeo, un archivo de audio o un documento.',
    'steps.metadata.2': 'El archivo se inspecciona, no se convierte, así que no se cambia nada de él.',
    'steps.metadata.3': 'Lea los metadatos directamente en la página: dimensiones, duración, códec, detalles de la cámara, número de páginas y más.',
    'steps.ocr.1': 'Suba el PDF escaneado o la foto del texto.',
    'steps.ocr.2': 'Elija el idioma del documento y si quiere un PDF con búsqueda o texto plano.',
    'steps.ocr.3': 'Haga clic en Convertir y descargue el resultado, con el texto reconocido ya seleccionable y localizable.',
    'steps.tts.1': 'Escriba o pegue su texto en el cuadro — hasta 4096 caracteres por conversión.',
    'steps.tts.2': 'Elija una voz, una velocidad de habla y un formato de salida.',
    'steps.tts.3': 'Haga clic en Convertir y descargue el archivo de audio terminado.',
    'steps.stt.1': 'Suba su grabación, o grabe directamente desde su micrófono con el botón de la página.',
    'steps.stt.2': 'Si quiere, indique el idioma hablado para mejorar la precisión, y elija salida TXT o DOCX.',
    'steps.stt.3': 'Haga clic en Convertir, lea la transcripción en la página y luego descárguela.',
    'steps.subtitle.1': 'Suba el vídeo que quiere subtitular.',
    'steps.subtitle.2': 'Elija SRT o VTT, e indique el idioma hablado si lo conoce.',
    'steps.subtitle.3': 'Haga clic en Convertir y descargue el archivo de subtítulos sincronizado, listo para su reproductor o su editor.',
    'steps.compress.1': 'Arrastre sus imágenes {{fn}} a la zona de subida, o haga clic para buscarlas. Puede añadir una carpeta entera de una vez.',
    'steps.compress.1.gif': 'Arrastre su animación {{fn}} a la zona de subida, o haga clic para buscarla. Puede añadir una carpeta entera de una vez.',
    'steps.compress.2': 'Haga clic en Convertir — el archivo se vuelve a codificar con menor tamaño manteniéndose en el mismo formato.',
    'steps.compress.3': 'Descargue el resultado y compárelo con el tamaño original que se muestra en la página.',
    'steps.soon.1': 'Elija la herramienta que necesite en la página de Herramientas — todo salvo esta ya está disponible hoy.',
    'steps.soon.2': 'Suba su archivo y elija un formato de salida.',
    'steps.soon.3': 'Descargue el resultado, o vuelva por aquí cuando la traducción de documentos esté disponible.',

    'faq.cost.q.pair': '¿Es gratis convertir {{from}} a {{to}}?',
    'faq.cost.q.tool': '¿{{label}} es gratis?',
    'faq.cost.a.pair': 'Las cuentas nuevas reciben un crédito de conversión gratuito, así que su primera conversión de {{from}} a {{to}} no cuesta nada. A partir de ahí, cada conversión usa un crédito de un pequeño paquete prepago: no hay suscripción, los créditos nunca caducan y una conversión fallida no se le cobra.',
    'faq.cost.a.tool': 'Las cuentas nuevas reciben un crédito de conversión gratuito, así que su primer archivo no cuesta nada. A partir de ahí, cada conversión usa un crédito de un pequeño paquete prepago: no hay suscripción, los créditos nunca caducan y una conversión fallida no se le cobra.',
    'faq.cost.a.smartTts': 'Las cuentas nuevas reciben un crédito de conversión gratuito para probar, y las funciones inteligentes se facturan por uso en lugar de por archivo: 1 crédito por cada 1000 caracteres de texto, redondeando hacia arriba. No hay suscripción: los créditos se compran en pequeños paquetes prepago, nunca caducan y una conversión fallida nunca cuesta nada.',
    'faq.cost.a.smartAv': 'Las cuentas nuevas reciben un crédito de conversión gratuito para probar, y las funciones inteligentes se facturan por uso en lugar de por archivo: 1 crédito por cada 5 minutos de audio o vídeo, redondeando hacia arriba. No hay suscripción: los créditos se compran en pequeños paquetes prepago, nunca caducan y una conversión fallida nunca cuesta nada.',
    'faq.cost.q.metadata': '¿La herramienta de información de archivo es gratis?',
    'faq.cost.a.metadata': 'Sí. Leer los metadatos de un archivo no es una conversión, así que no gasta ningún crédito — puede inspeccionar tantos archivos como quiera. Los créditos solo se gastan cuando una herramienta produce realmente un archivo nuevo para usted.',
    'faq.cost.q.soon': '¿{{label}} ya está disponible?',
    'faq.cost.a.soon': 'Todavía no — esta página es un marcador de posición mientras se construye la herramienta, así que hoy no hay nada que subir aquí. El precio seguirá el mismo modelo de créditos prepago que el resto del sitio: sin suscripción, con créditos que nunca caducan y sin cargo por una conversión fallida.',

    'faq.time.q.pair': '¿Cuánto tarda la conversión de {{from}} a {{to}}?',
    'faq.time.q.tool': '¿Cuánto tarda {{label}}?',
    'faq.time.a': '{{speed}} La velocidad de subida suele ser el factor limitante, así que un archivo grande con una conexión lenta tarda más que la propia conversión.{{suffix}}',
    'faq.time.speed.image': 'Las imágenes son lo más rápido que convertimos — una sola foto suele estar lista en menos de cinco segundos, y una carpeta entera tarda más o menos lo que la propia subida.',
    'faq.time.speed.document': 'La mayoría de los documentos terminan en unos segundos. Los archivos muy largos — unos cientos de páginas, o un escaneo cargado de imágenes — pueden llevar hasta un minuto.',
    'faq.time.speed.audio': 'Una canción normal se convierte en unos segundos. Una grabación completa, como una clase o un episodio de pódcast, suele tardar bastante menos de un minuto, y la mayor parte es la subida.',
    'faq.time.speed.video': 'El vídeo es la categoría más lenta porque hay que volver a codificar cada fotograma. Un clip corto tarda segundos, mientras que un archivo largo en alta resolución puede llevar unos minutos.',
    'faq.time.speed.archive': 'Los archivos comprimidos se convierten en segundos, aunque uno grande tarda más porque hay que descomprimir y volver a comprimir cada archivo de dentro.',
    'faq.time.speed.ebook': 'Los libros electrónicos son rápidos — una novela entera se convierte normalmente en unos segundos.',
    'faq.time.speed.subtitle': 'La transcripción avanza a razón de unos segundos por minuto de audio, así que un vídeo de diez minutos suele quedar subtitulado en bastante menos de un minuto.',
    'faq.time.suffix.standard': ' Se aceptan archivos de hasta 200 MB.',
    'faq.time.suffix.smart': ' Las funciones inteligentes aceptan archivos de hasta 25 MB; las conversiones normales, hasta 200 MB.',
    'faq.time.q.metadata': '¿Cuánto tarda leer los metadatos de un archivo?',
    'faq.time.a.metadata': 'Un segundo o dos una vez subido el archivo. No se convierte ni se vuelve a codificar nada — se analizan las cabeceras y el resultado se imprime directamente en la página —, así que la espera es esencialmente la subida.',
    'faq.time.q.soon': '¿Costará más?',
    'faq.time.a.soon': 'Usará los mismos créditos que todo lo demás del sitio. No hay un plan ni una suscripción aparte a la que apuntarse, y los créditos que ya tenga en su cuenta funcionarán con ella desde el momento en que se active.',

    'faq.safety.q.pair': '¿Es seguro subir mi archivo {{from}}?',
    'faq.safety.q.tool': '¿Mi archivo está seguro?',
    'faq.safety.a.pair': 'Los archivos viajan por una conexión TLS cifrada y no se usan para nada salvo la conversión que usted ha pedido. Tanto su archivo {{from}} original como el archivo {{to}} que le devolvemos se eliminan automáticamente en 24 horas — de forma permanente y sin copias de seguridad — y su contenido nunca se lee, se analiza ni se comparte. El servicio se opera desde Alemania bajo el RGPD.',
    'faq.safety.a.tool': 'Los archivos viajan por una conexión TLS cifrada y no se usan para nada salvo la conversión que usted ha pedido. Tanto su archivo original como el resultado que le devolvemos se eliminan automáticamente en 24 horas — de forma permanente y sin copias de seguridad — y su contenido nunca se lee, se analiza ni se comparte. El servicio se opera desde Alemania bajo el RGPD.',

    'quality.vectorRaster.q': '¿Mi {{fn}} seguirá siendo nítido como {{tn}}?',
    'quality.vectorRaster.a': 'Hasta el tamaño al que lo exporte, sí. El {{fn}} guarda formas en lugar de píxeles, así que es infinitamente escalable, pero un {{tn}} es una rejilla fija de píxeles y se volverá borroso si después se amplía más allá de esa rejilla. Fije en los ajustes avanzados el ancho y el alto que realmente necesita antes de convertir — exportar al doble o al triple del tamaño de visualización es el truco habitual para pantallas de alta densidad de píxeles. Conserve el archivo {{fn}} original: sigue siendo la copia maestra desde la que reexportar a cualquier resolución.',
    'quality.docToTxt.q': '¿Perderé el formato al convertir {{fn}} a {{tn}}?',
    'quality.docToTxt.a': 'Sí, y deliberadamente — un archivo {{tn}} contiene caracteres y nada más. Tipografías, colores, imágenes, tablas, columnas y saltos de página desaparecen todos; lo que recupera es el texto legible del documento en orden de lectura. Eso es exactamente lo que quiere para buscar, programar o alimentar otro programa, y exactamente lo que no quiere si esperaba conservar el diseño. Tenga en cuenta que un {{fn}} que en realidad es una imagen escaneada no contiene texto alguno que extraer — páselo por la herramienta de OCR en su lugar.',
    'quality.docToSheet.q': '¿Con qué precisión se extraen las tablas de un {{fn}}?',
    'quality.docToSheet.a': 'Las tablas limpias, con líneas y columnas consistentes — extractos, facturas, informes exportados — pasan de forma fiable, y cada valor cae en su propia celda para que pueda sumarlo y ordenarlo. Las tablas sin bordes visibles, las celdas que abarcan varias filas o las cifras partidas por un salto de página son los casos que conviene revisar a ojo después. El {{fn}} guarda posiciones y no estructura de tabla, así que la conversión tiene que deducir dónde acaba una columna y empieza la siguiente.',
    'quality.docToReflow.q': '¿Sobrevivirá la maquetación a la conversión de {{fn}} a {{tn}}?',
    'quality.docToReflow.a': 'No exactamente, y esa es precisamente la idea. El {{fn}} clava el texto a coordenadas de página fijas; el {{tn}} lo reajusta a la pantalla y al tamaño de letra del lector, así que los números de página fijos, los encabezados, los pies y las maquetaciones a varias columnas se reinterpretan en lugar de reproducirse. El cuerpo de texto, los títulos, el orden de los párrafos y las imágenes pasan bien. Los documentos que son sobre todo prosa se convierten de maravilla; las páginas muy diseñadas, los formularios y las tablas complejas son las que conviene revisar después.',
    'quality.docToFixed.q': '¿Se conservará mi formato en el {{tn}}?',
    'quality.docToFixed.a': 'Sí — este sentido es el seguro. El {{tn}} registra la página tal como queda renderizada, así que tipografías, espaciados, tablas, imágenes y saltos de página quedan congelados exactamente como se maquetaron y se verán igual en cualquier dispositivo e impresora. Ese es también el precio: el resultado ya no es libremente editable, que suele ser justo el motivo por el que se convierte a {{tn}} antes de enviar un documento.',
    'quality.docToEditable.q': '¿Con qué precisión se convierte de {{fn}} a {{tn}}?',
    'quality.docToEditable.a': 'El texto, los títulos, las listas, las imágenes y las tablas sencillas pasan de forma fiable y siguen siendo totalmente editables. Como el {{fn}} guarda posiciones y no estructura, la conversión tiene que reconstruir esa estructura, así que las páginas muy diseñadas — varias columnas, texto rodeando imágenes, tablas anidadas complejas — pueden necesitar un pequeño repaso después. Si el PDF es un escaneo sin ninguna capa de texto, use la herramienta de OCR en su lugar: reconoce los caracteres de la imagen en vez de buscar un texto que no está ahí.',
    'quality.docGeneric.q': '¿Pierdo algo al convertir {{fn}} a {{tn}}?',
    'quality.docGeneric.a': 'Las palabras, los títulos, las listas y las imágenes se trasladan intactos. El {{tn}} admite un vocabulario de formato distinto al del {{fn}}, así que un estilo muy específico puede simplificarse por el camino, pero el contenido en sí se conserva.',
    'quality.archive.q': '¿Se modificarán los archivos que hay dentro de mi {{fn}}?',
    'quality.archive.a': 'No. Los formatos comprimidos son contenedores sin pérdida: el {{fn}} se descomprime y los mismos archivos se vuelven a empaquetar como {{tn}}, byte a byte. Solo cambian el método de compresión y el contenedor. Lo que sí cambia es el tamaño del propio archivo comprimido — {{clause}}.',
    'quality.archive.clause.to7z': '7Z suele producir un archivo más pequeño que ZIP gracias a la compresión LZMA',
    'quality.archive.clause.toZip': 'ZIP suele quedar algo más grande que 7Z o RAR, que es el precio de poder abrirse en cualquier parte sin software adicional',
    'quality.archive.clause.other': 'el nuevo formato comprime de otra manera, así que el tamaño puede moverse en cualquiera de los dos sentidos',
    'quality.imageToDoc.q': '¿Perderán calidad mis fotos dentro del {{tn}}?',
    'quality.imageToDoc.a': 'No. Cada imagen {{fn}} se coloca en el {{tn}} tal cual, una por página, en lugar de recomprimirse, así que lo que ve en el documento es lo que salió de la cámara. El {{tn}} pesará aproximadamente la suma de las imágenes, lo cual conviene saber antes de enviarlo por correo — pase el resultado por Comprimir PDF si necesita que sea más pequeño.',
    'quality.toGif.q': '¿Por qué mi GIF se ve peor que el {{fn}} original?',
    'quality.toGif.a': 'Porque GIF está limitado a 256 colores por fotograma. Un vídeo o una foto contienen millones, así que el codificador tiene que elegir una paleta y aproximar todo lo demás, lo que se manifiesta como bandas en los degradados y en los cielos. GIF tampoco lleva pista de audio alguna. Ambas cosas son propias del formato, no de la conversión — mantenga el clip corto y, si la pérdida de color importa más que la reproducción automática incrustada, un MP4 se verá mucho mejor ocupando menos.',
    'quality.lossyToLossless.q': '¿Convertir {{fn}} a {{tn}} mejora la calidad?',
    'quality.lossyToLossless.a': 'No — y este es con diferencia el malentendido más habitual sobre esta conversión. El {{fn}} es con pérdida: el detalle que descartó su codificador ha desaparecido para siempre y nada puede reconstruirlo. Lo que el {{tn}} le da es un contenedor sin pérdida para lo que queda, de modo que el archivo deja de degradarse con cada guardado o edición posterior. Eso resulta realmente útil cuando está a punto de {{clause}}, pero no recuperará una calidad que ya se perdió.',
    'quality.lossyToLossless.edit.audio': 'editar, masterizar o procesar el audio',
    'quality.lossyToLossless.edit.image': 'editar, retocar o componer la imagen',
    'quality.losslessToLossy.q': '¿Perderé calidad al convertir {{fn}} a {{tn}}?',
    'quality.losslessToLossy.a.audio': 'Algo, y por diseño — así es como el archivo se hace más pequeño. El {{tn}} es con pérdida, así que el codificador descarta la información que considera menos perceptible. Con ajustes sensatos la diferencia es muy difícil de apreciar de oído, y puede subir la tasa de bits en los ajustes avanzados si prefiere cambiar tamaño por fidelidad. Conserve su archivo {{fn}} original: sigue siendo la copia maestra, y volver a codificar el {{tn}} más adelante agravaría la pérdida.',
    'quality.losslessToLossy.a.visual': 'Algo, y por diseño — así es como el archivo se hace más pequeño. El {{tn}} es con pérdida, así que el codificador descarta la información que considera menos perceptible. Con ajustes sensatos la diferencia es muy difícil de apreciar a la vista, y puede subir el valor de calidad en los ajustes avanzados si prefiere cambiar tamaño por fidelidad. Conserve su archivo {{fn}} original: sigue siendo la copia maestra, y volver a codificar el {{tn}} más adelante agravaría la pérdida.',
    'quality.lossyToLossy.q': '¿Perderé calidad al convertir {{fn}} a {{tn}}?',
    'quality.lossyToLossy.a.audio': 'Un poco. Ambos formatos son con pérdida, así que el {{fn}} se decodifica y luego se vuelve a codificar como {{tn}}, y cada generación de codificación con pérdida deja escapar algo de detalle. Con ajustes normales no es algo que la mayoría note al escuchar, y puede subir la tasa de bits en los ajustes avanzados. Lo que conviene evitar es convertir el mismo archivo de ida y vuelta repetidamente — eso es lo que hace audible la pérdida.',
    'quality.lossyToLossy.a.visual': 'Un poco. Ambos formatos son con pérdida, así que el {{fn}} se decodifica y luego se vuelve a codificar como {{tn}}, y cada generación de codificación con pérdida deja escapar algo de detalle. Con ajustes normales no es algo que la mayoría note, y puede subir la calidad en los ajustes avanzados. Lo que conviene evitar es convertir el mismo archivo de ida y vuelta repetidamente — eso es lo que hace visible la pérdida.',
    'quality.losslessToLossless.q': '¿Perderé calidad al convertir {{fn}} a {{tn}}?',
    'quality.losslessToLossless.a.plain': 'No. Tanto {{fn}} como {{tn}} son sin pérdida, así que {{unit}} se conserva exactamente y el resultado es idéntico al original. Solo cambia el tamaño del archivo. Puede volver a convertirlo más adelante sin degradación alguna.',
    'quality.losslessToLossless.a.bulky': 'No. Tanto {{fn}} como {{tn}} son sin pérdida, así que {{unit}} se conserva exactamente y el resultado es idéntico al original. Solo cambia el tamaño del archivo, normalmente a la baja de forma drástica, porque el {{fn}} guarda sus datos prácticamente sin comprimir. Puede volver a convertirlo más adelante sin degradación alguna.',
    'quality.fallback.q': '¿Perderé calidad al convertir {{fn}} a {{tn}}?',
    'quality.fallback.a': 'Para archivos normales el resultado es visual y funcionalmente equivalente al original. Allí donde los dos formatos admiten funciones distintas, la conversión conserva todo lo que el {{tn}} es capaz de representar. Los ajustes avanzados le permiten subir la calidad si el compromiso por defecto no es el que usted quiere.',

    'relation.uncompressed.q': '¿Por qué el archivo {{tn}} es mucho más grande que el {{fn}}?',
    'relation.uncompressed.a': 'Porque el {{tn}} no está comprimido. El {{fn}} reduce el audio descartando datos y codificando eficientemente lo que queda; el {{tn}} escribe cada muestra a tamaño completo, lo que sale a unos 10 MB por minuto de estéreo con calidad de CD. Un aumento de diez a uno es normal y esperable — es el precio de un archivo que el software de edición puede procesar sin decodificar nada antes. Si quiere audio sin pérdida ocupando aproximadamente la mitad, convierta a FLAC.',
    'relation.extractAudio.q': '¿Esto conserva el vídeo o solo el sonido?',
    'relation.extractAudio.a': 'Solo el sonido. La pista de audio se extrae del archivo {{fn}} y se guarda como {{tn}}; la pista de vídeo se descarta, y por eso el resultado ocupa una fracción del tamaño original. El audio en sí no se vuelve a grabar, así que conserva la calidad que tenía dentro del {{fn}} — extraer de un vídeo de baja tasa de bits no puede producir audio de alta tasa de bits.',
    'relation.videoContainer.q': '¿Se reproducirá mi {{tn}} en móviles, televisores y redes sociales?',
    'relation.videoContainer.a.mp4': 'Para eso sirve exactamente esta conversión. MP4 con vídeo H.264 es lo más parecido a un formato de vídeo universal: iPhone, móviles Android, televisores inteligentes, todos los navegadores, Instagram, YouTube, TikTok y todos los editores habituales lo aceptan sin códecs adicionales. El {{fn}} era el formato que le estaba dando problemas; MP4 es el que no los da.',
    'relation.videoContainer.a.other': 'El {{tn}} es más especializado que MP4. {{note}} Si su objetivo es simplemente «que se reproduzca en todas partes», MP4 es la opción más segura — elija {{tn}} cuando un programa o un aparato concreto se lo haya pedido.',
    'relation.alphaLost.q': '¿Qué pasa con la transparencia al convertir {{fn}} a {{tn}}?',
    'relation.alphaLost.a': 'El {{tn}} no tiene canal alfa, así que las zonas transparentes no pueden trasladarse — durante la conversión se rellenan con un fondo sólido (blanco por defecto). Si el fondo transparente cumple una función real en su diseño, convierta a PNG o WebP, que lo conservan ambos. Si la imagen es una fotografía sin transparencia alguna, esto no supone ninguna diferencia.',
    'relation.alphaGained.q': '¿Convertir {{fn}} a {{tn}} hace transparente el fondo?',
    'relation.alphaGained.a': 'No — y a mucha gente le pilla desprevenida. El {{tn}} admite transparencia, pero un archivo {{fn}} no tiene información de transparencia que trasladar, así que el fondo queda exactamente como estaba. Lo que la conversión le da es un archivo capaz de contener transparencia una vez que recorte el fondo en un editor de imágenes, además de píxeles sin pérdida que no se degradarán mientras trabaja.',
    'relation.reflow.q': '¿Funcionará el {{tn}} en mi lector electrónico?',
    'relation.reflow.a.epub': 'EPUB lo leen Apple Books, Kobo, Google Play Books, Calibre y prácticamente cualquier lector electrónico salvo el Kindle, que quiere MOBI o AZW3 (el Kindle también acepta EPUB por correo hoy en día). Como el texto se reajusta, puede cambiar el tamaño de letra en el dispositivo sin acabar desplazándose de lado — que es toda la razón para convertir un {{fn}} de entrada.',
    'relation.reflow.a.kindle': 'El {{tn}} lo leen los dispositivos y aplicaciones Kindle para los que fue diseñado. Como el texto se reajusta, puede cambiar el tamaño de letra en el dispositivo sin acabar desplazándose de lado — que es toda la razón para convertir un {{fn}} de entrada.',

    'compatibility.q': '¿Con qué podré abrir después el archivo {{tn}}?',
    'compatibility.a': '{{note}} No hace falta instalar nada para hacer la conversión — se ejecuta en nuestros servidores, y el {{tn}} terminado vuelve a su navegador listo para abrir, editar o reenviar. Su {{fn}} original nunca se modifica; solo devolvemos un archivo nuevo.',
    'compatibility.noteFallback': 'El {{tn}} está ampliamente soportado.',

    'shapeFaq.pdf-merge.q1': '¿Combinarlos reducirá la calidad de mis PDF?',
    'shapeFaq.pdf-merge.a1': 'No. Las páginas se copian al nuevo documento tal como están en lugar de volver a renderizarse, así que el texto sigue siendo seleccionable y las imágenes conservan su resolución original. El archivo combinado pesa aproximadamente la suma de los originales — páselo después por Comprimir PDF si eso importa.',
    'shapeFaq.pdf-merge.q2': '¿Cuántos PDF puedo combinar de una vez, e importa el orden?',
    'shapeFaq.pdf-merge.a2': 'Puede añadir tantos archivos como necesite de una vez, y el orden importa mucho: el documento final sigue el orden que se muestra en la lista, que puede reorganizar arrastrando antes de combinar. Fije primero el orden y combine después — es más rápido que corregirlo luego.',
    'shapeFaq.pdf-split.q1': '¿Cómo elijo qué páginas extraer?',
    'shapeFaq.pdf-split.a1': 'Escríbalas en el campo de intervalos de páginas usando comas y guiones: «1-3, 5, 7-10» le da las páginas de la una a la tres, la página cinco y las páginas de la siete a la diez en un único documento de salida. Los números se refieren a las páginas del propio PDF, contando desde uno, que no siempre es el número impreso en la página.',
    'shapeFaq.pdf-split.q2': '¿Dividir modifica el PDF original?',
    'shapeFaq.pdf-split.a2': 'No. El archivo que sube nunca se modifica — las páginas extraídas se escriben en un documento nuevo y el original queda intacto, antes de eliminarse de nuestros servidores en 24 horas junto con el resultado.',
    'shapeFaq.pdf-compress.q1': '¿Cuánto se reducirá mi PDF?',
    'shapeFaq.pdf-compress.a1': 'Depende por completo de lo que contenga. Los PDF dominados por escaneos o fotografías suelen reducirse entre un 50 y un 90 %, porque ahí reside casi todo el peso. Un PDF de solo texto ya es compacto y quizá apenas cambie. El texto y los gráficos vectoriales quedan nítidos en cualquier caso — el ahorro viene de recodificar las imágenes y de eliminar datos incrustados redundantes.',
    'shapeFaq.pdf-compress.q2': '¿El texto seguirá siendo seleccionable y localizable?',
    'shapeFaq.pdf-compress.a2': 'Sí. La compresión actúa sobre las imágenes incrustadas y sobre datos internos redundantes; la capa de texto, las tipografías, los enlaces y los marcadores quedan intactos, así que podrá seguir buscando, seleccionando y copiando del archivo comprimido exactamente igual que antes.',
    'shapeFaq.pdf-compress-ai.q1': '¿En qué se diferencia esto de la compresión normal de PDF?',
    'shapeFaq.pdf-compress-ai.a1': 'La compresión normal aplica un único ajuste a todo el archivo. Esta herramienta mira primero qué contiene realmente cada página, de modo que las imágenes fotográficas, los diagramas planos y las páginas de solo texto se traten cada uno de la forma que más espacio ahorra sin degradarlos de manera visible. En documentos mixtos eso suele significar un archivo más pequeño con la misma calidad aparente.',
    'shapeFaq.pdf-compress-ai.q2': '¿El texto seguirá siendo seleccionable y localizable?',
    'shapeFaq.pdf-compress-ai.a2': 'Sí. La capa de texto, las tipografías, los enlaces y los marcadores se conservan — solo se vuelven a codificar las imágenes incrustadas y los datos internos redundantes, así que el PDF comprimido sigue siendo totalmente localizable y copiable.',
    'shapeFaq.pdf-rotate.q1': '¿Girar un PDF hace perder calidad?',
    'shapeFaq.pdf-rotate.a1': 'En absoluto. El giro cambia la geometría de página registrada en el archivo en lugar de volver a renderizar nada, así que el texto sigue nítido como vector, las imágenes quedan intactas y el tamaño apenas se mueve. Puede volver a girarlo más adelante sin ningún daño acumulado.',
    'shapeFaq.pdf-rotate.q2': '¿Puedo girar solo algunas páginas?',
    'shapeFaq.pdf-rotate.a2': 'El giro que elija — 90°, 180° o 270° — se aplica al documento. Si distintas páginas están mal en distintas direcciones, lo habitual es dividir el PDF, girar cada parte el ángulo que necesite y volver a unir los resultados con la herramienta Combinar PDF.',
    'shapeFaq.pdf-protect.q1': '¿Qué pasa si olvido la contraseña?',
    'shapeFaq.pdf-protect.a1': 'El archivo no podrá abrirse. El cifrado se aplica al propio PDF, así que no hay enlace de restablecimiento ni puerta trasera — ni para usted ni para nosotros. Guarde la contraseña en un lugar seguro antes de reenviar el documento, y envíela por un canal distinto al del archivo.',
    'shapeFaq.pdf-protect.q2': '¿Cómo de fuerte es la protección?',
    'shapeFaq.pdf-protect.a2': 'El PDF se cifra con el esquema estándar del sector integrado en el formato, así que ningún lector conforme puede leer su contenido sin la contraseña. El punto débil práctico nunca es el algoritmo sino la propia contraseña — una corta u obvia se adivina rápido, así que use una larga para cualquier cosa realmente confidencial.',
    'shapeFaq.pdf-unlock.q1': '¿Puede esto quitar una contraseña que no conozco?',
    'shapeFaq.pdf-unlock.a1': 'No. Tiene que aportar la contraseña actual; la herramienta descifra el archivo con ella en lugar de romper el cifrado. Está pensada para documentos de su propiedad o que está autorizado a abrir — un extracto de su propio banco, por ejemplo — donde la restricción simplemente estorba.',
    'shapeFaq.pdf-unlock.q2': '¿Qué puedo hacer con el archivo después?',
    'shapeFaq.pdf-unlock.a2': 'Todo lo que la protección bloqueaba: abrirlo sin que pregunte, imprimirlo, copiar texto de él y editarlo en otro software. El contenido de las páginas en sí no cambia — solo se retiran la capa de cifrado y sus restricciones de uso.',
    'shapeFaq.metadata.q1': '¿Esto modifica mi archivo de alguna manera?',
    'shapeFaq.metadata.a1': 'No. El archivo se lee, no se convierte — no se reescribe nada y no se produce nada nuevo salvo la información que se muestra en pantalla. Es la herramienta más segura de aquí para apuntar a un archivo del que no está seguro.',
    'shapeFaq.metadata.q2': '¿Qué tipo de información voy a ver?',
    'shapeFaq.metadata.a2': 'Depende del archivo. Las imágenes muestran dimensiones, profundidad de color y datos EXIF como modelo de cámara, objetivo, exposición y, cuando la cámara las registró, coordenadas GPS. El audio muestra duración, tasa de bits, frecuencia de muestreo y número de canales. El vídeo añade códec, resolución y fotogramas por segundo. Los documentos muestran número de páginas, autor, productor y fecha de creación.',
    'shapeFaq.ocr.q1': '¿Con qué precisión reconoce el texto?',
    'shapeFaq.ocr.a1': 'Un escaneo limpio y recto de texto impreso a una resolución razonable se reconoce con mucha precisión. La precisión baja con páginas torcidas o borrosas, fotografías de poco contraste, tipografías poco habituales y escritura a mano. Elegir el idioma correcto importa, porque el reconocimiento lo usa para resolver caracteres ambiguos.',
    'shapeFaq.ocr.q2': '¿Cuál es la diferencia entre el PDF con búsqueda y la salida en texto plano?',
    'shapeFaq.ocr.a2': 'El PDF con búsqueda conserva la imagen de página original exactamente tal como se ve y añade debajo una capa de texto invisible, así que el documento parece igual pero ahora se puede buscar y copiar de él — esto es lo que quiere para archivar. El texto plano descarta la maquetación y le da solo las palabras, que es lo que quiere para editar, programar o alimentar otro programa.',
    'shapeFaq.tts.q1': '¿Qué tal de naturales suenan las voces?',
    'shapeFaq.tts.a1': 'Son voces neuronales y no la antigua síntesis por concatenación, así que llevan entonación a nivel de frase y pausas naturales en lugar de leer palabra por palabra. Hay seis voces disponibles, de neutra a cálida y a autoritaria, y la velocidad de habla es ajustable. La puntuación importa más de lo que la gente supone: las comas y los puntos moldean el fraseo, así que un texto bien puntuado se lee notablemente mejor.',
    'shapeFaq.tts.q2': '¿Cuánto texto puedo convertir de una vez?',
    'shapeFaq.tts.a2': 'Hasta 4096 caracteres por conversión — unas 600 a 700 palabras, o alrededor de cinco minutos de habla. Para textos más largos, córtelos en un punto natural como un título de capítulo o de sección y convierta cada parte por separado; los ajustes de voz y velocidad se mantienen constantes entre ejecuciones, así que las piezas encajan limpiamente.',
    'shapeFaq.stt.q1': '¿Con qué precisión transcribe?',
    'shapeFaq.stt.a1': 'El habla clara en un entorno razonablemente tranquilo se transcribe con mucha precisión, incluso con una amplia variedad de acentos. La precisión cae con mucho ruido de fondo, con varias personas hablando a la vez, o con jerga muy especializada y nombres propios. Indicar el idioma hablado en lugar de dejar la detección automática ayuda de forma notable.',
    'shapeFaq.stt.q2': '¿Puedo grabar directamente desde mi micrófono?',
    'shapeFaq.stt.a2': 'Sí — la grabadora de esta página capta el audio directamente en el navegador, lo que suele ser más rápido que buscar antes una aplicación de grabación. Su navegador pedirá permiso para el micrófono la primera vez. También puede subir un archivo existente, y la transcripción aparece en la página para que la lea antes de descargarla en TXT o DOCX.',
    'shapeFaq.subtitle.q1': '¿Con qué precisión se generan los subtítulos?',
    'shapeFaq.subtitle.a1': 'El habla clara se transcribe con mucha precisión, también con acentos. La música de fondo, las conversaciones solapadas y la terminología especializada son donde se cuelan los errores, e indicar el idioma hablado en vez de detectarlo automáticamente ayuda. La salida es un archivo de subtítulos en texto plano, así que corregir alguna palabra suelta lleva segundos en cualquier editor de texto.',
    'shapeFaq.subtitle.q2': '¿Debería elegir SRT o VTT?',
    'shapeFaq.subtitle.a2': 'SRT es la opción por defecto más segura: YouTube, Vimeo, Premiere, Final Cut, VLC y prácticamente cualquier reproductor lo aceptan. Elija VTT si los subtítulos son para un reproductor de vídeo HTML5 en una web, ya que WebVTT es el formato que espera la pista de subtítulos nativa del navegador y admite estilos y posicionamiento que SRT no puede expresar.',
    'shapeFaq.soon.q1': '¿Cuándo estará disponible?',
    'shapeFaq.soon.a1': 'Está en desarrollo activo. La herramienta aparecerá aquí y empezará a aceptar archivos en cuanto esté lista — no hace falta instalar ni activar nada por su parte.',
    'shapeFaq.soon.q2': '¿Qué puedo usar mientras tanto?',
    'shapeFaq.soon.a2': 'El resto del conversor está plenamente disponible: documentos, imágenes, audio, vídeo, archivos comprimidos, GIF y la caja de herramientas de PDF funcionan todos hoy, igual que las funciones inteligentes de OCR, transcripción y subtítulos.',
    'shapeFaq.compress.q1': '¿El archivo comprimido seguirá siendo un {{fn}}?',
    'shapeFaq.compress.a1': 'Sí — el formato no cambia, solo el tamaño. Lo que descarga es un {{fn}} corriente que se abre en cualquier sitio donde se abría el original.{{alpha}} Cuánto ahorre depende del material de partida: {{source}}.',
    'shapeFaq.compress.alpha': ' La transparencia y la animación se conservan.',
    'shapeFaq.compress.source.png': 'las capturas de pantalla y los gráficos planos de interfaz se comprimen de forma espectacular, mientras que las fotografías guardadas como PNG dan menos de sí',
    'shapeFaq.compress.source.gif': 'las animaciones largas y el material con mucho movimiento se comprimen más, porque hay más redundancia que eliminar',
    'shapeFaq.compress.source.other': 'las fotografías se comprimen bien, mientras que las imágenes que ya estaban muy comprimidas dan menos de sí',
    'shapeFaq.compress.q2': '¿Cuánto se reducirá el archivo?',
    'shapeFaq.compress.a2': 'Normalmente entre un tercio y una décima parte del original, dependiendo por completo de lo que contenga el archivo y de cómo se guardara en su momento. Cuando termina la conversión, la página muestra los tamaños de antes y de después uno junto a otro, así que ve el ahorro real en lugar de adivinarlo.',
    'shapeFaq.hub.q1': '¿Entre qué formatos puedo convertir?',
    'shapeFaq.hub.a1': 'Entrada: {{inputs}}. Salida: {{outputs}}. Cualquier entrada puede ir a cualquier salida, así que no necesita encontrar una página distinta para cada combinación — elija el archivo, elija el formato de destino y convierta.',
    'shapeFaq.hub.q2': '¿Perderé calidad?',
    'shapeFaq.hub.a2': 'Depende del par. Pasar a un formato sin pérdida lo conserva todo pero produce un archivo más grande; pasar a un formato comprimido descarta datos a propósito a cambio de tamaño, y los ajustes avanzados le dejan decidir dónde situarse en ese compromiso. Convertir entre dos formatos comprimidos pierde algo de detalle cada vez, así que merece la pena conservar el original como copia maestra.',
    'shapeFaq.hub-extract.q1': '¿Esto conserva también el vídeo?',
    'shapeFaq.hub-extract.a1': 'No — solo el sonido. La pista de audio se extrae del vídeo y se guarda por separado, y por eso el resultado ocupa una fracción del tamaño original. El audio no se vuelve a grabar, así que conserva la calidad que ya tenía dentro del vídeo; extraer de un clip de baja tasa de bits no puede producir audio de alta tasa de bits.',
    'shapeFaq.hub-extract.q2': '¿Qué formato de salida debería elegir?',
    'shapeFaq.hub-extract.a2': 'MP3 para máxima compatibilidad — se reproduce en cualquier móvil, equipo de coche y reproductor. AAC o M4A si el destino es un dispositivo Apple o una aplicación moderna, ya que suenan algo mejor a igual tasa de bits. WAV o FLAC solo si va a editar el audio, porque ambos son sin pérdida y, por tanto, voluminosos.',
    'shapeFaq.hub-gif.q1': '¿Por qué el GIF se ve peor que el original?',
    'shapeFaq.hub-gif.a1': 'Porque GIF solo admite 256 colores por fotograma, mientras que el vídeo y las fotografías contienen millones. El codificador elige una paleta y aproxima el resto, lo que se manifiesta como bandas en los degradados y en los cielos. GIF tampoco lleva sonido alguno. Ambos límites son propios del formato y no de la conversión.',
    'shapeFaq.hub-gif.q2': '¿Por qué mi archivo GIF es tan grande?',
    'shapeFaq.hub-gif.a2': 'GIF comprime mucho peor que los códecs de vídeo modernos, así que el tamaño crece deprisa con la duración, la resolución y los fotogramas por segundo. Unos pocos segundos es el punto óptimo. Si el resultado pesa demasiado, recorte el clip, y si el tamaño importa más que la reproducción automática incrustada, un MP4 mostrará la misma animación ocupando una fracción.',
  },
};
