// Finnish content pack. Mirrors packs/en.js key for key — see the header there.
// Format names are never inflected directly: Finnish case endings are attached
// to a following compound word ("{{fn}}-tiedoston", "{{tn}}-muotoon") so the
// untranslated format name always stays intact.
export default {
  lang: 'fi',
  formats: {
    pdf: { about: 'PDF on kiinteän taiton muoto: se tallentaa jokaisen merkin, viivan ja kuvan tarkan sijainnin, ja siksi PDF näyttää samalta millä tahansa näytöllä ja tulostimella mutta on hankala muokata.', note: 'PDF lukitsee sivutuksen, kirjasimet ja taiton, joten vastaanottaja näkee juuri sen, mitä lähetit.' },
    docx: { about: 'DOCX on Microsoft Wordin nykyaikainen muoto, jossa teksti elää muokattavissa kappaleissa ja tyyleissä sen sijaan, että se olisi naulattu kiinteisiin sivukoordinaatteihin.', note: 'DOCX antaa aidosti muokattavat kappaleet, muutosten seurannan ja kommentit Wordissa, Google Docsissa tai LibreOfficessa.' },
    xlsx: { about: 'XLSX on Excelin taulukkolaskentamuoto, jossa jokainen arvo istuu osoitettavassa solussa, jota voi lajitella, suodattaa ja käyttää kaavassa.', note: 'Kun tiedot ovat XLSX-muodossa, voit laskea, lajitella, pivotoida ja piirtää kaavioita sen sijaan, että näppäilisit ne uudelleen.' },
    pptx: { about: 'PPTX tallentaa esityksen erillisinä dioina, joissa on muokattavat tekstikentät, muodot, esittäjän muistiinpanot ja siirtymät.', note: 'PPTX antaa diat, joita voi todella muokata uudelleen, järjestää uusiksi ja esittää taas.' },
    txt: { about: 'TXT-tiedosto ei ole muuta kuin merkkejä — ei kirjasimia, ei kuvia, ei sivurakennetta — mikä tekee siitä pienen, kaikkialla luettavan ja triviaalisti haettavan.', note: 'TXT riisuu kaiken muun paitsi sanat, ja juuri sitä skriptit, hakemistot ja tekstieditorit haluavat.' },
    html: { about: 'HTML on verkon merkintäkieli: tekstiä tunnisteiden sisällä, joista selain tekee otsikoita, kappaleita, linkkejä ja kuvia.', note: 'HTML avautuu missä tahansa selaimessa ja sen voi liittää suoraan sivustolle tai julkaisujärjestelmään.' },
    rtf: { about: 'RTF on avoin, tavalliseen tekstiin perustuva asiakirjamuoto, joka kantaa mukanaan perusmuotoilun — lihavoinnin, kursiivin, kirjasimet, taulukot — sitomatta sinua yhteen tekstinkäsittelyohjelmaan.', note: 'RTF avautuu Wordissa, Pagesissa, LibreOfficessa, WordPadissa ja lähes jokaisessa koskaan kirjoitetussa tekstinkäsittelyohjelmassa.' },
    odt: { about: 'ODT on LibreOfficen ja OpenOfficen käyttämä OpenDocument-tekstimuoto, ja se on ISO-standardi eikä yhden valmistajan muoto.', note: 'ODT on LibreOfficen ja OpenOfficen oma, täysin muokattava muoto.' },
    epub: { about: 'EPUB on juoksevan tekstin e-kirjamuoto: sillä ei ole kiinteää sivukokoa, joten teksti rivittyy uudelleen sen näytön ja kirjasinkoon mukaan, jota lukija käyttää.', note: 'EPUB antaa lukijan muuttaa kirjasinkokoa ja rivittää tekstin uudelleen, ja juuri se tekee pitkistä asiakirjoista miellyttäviä puhelimella tai lukulaitteella.' },
    jpg: { about: 'JPG käyttää häviöllistä pakkausta, joka on viritetty valokuville: se heittää pois ne yksityiskohdat, jotka silmä huomaa vähiten, mikä tekee kuvista pieniä mutta lisää pehmeitä, lohkomaisia virheitä terävien reunojen ja tekstin ympärille.', note: 'JPG tuottaa pieniä tiedostoja, jotka avautuvat kirjaimellisesti kaikkialla, hintana pysyvästi hylätyt yksityiskohdat ja läpinäkyvyyden puute.' },
    jfif: { about: 'JFIF on JPEG-kuva, joka on tallennettu eri tiedostopäätteellä; sisällä olevat pikselit ovat tavallista JPEG-dataa, mutta Windows kieltäytyy usein antamasta tiedostoa haluamallesi sovellukselle.', note: 'JFIF on todellisuudessa vain JPEG toisella nimellä.' },
    png: { about: 'PNG on häviötön: se tallentaa jokaisen pikselin tarkasti, tukee täyttä alfakanavaa läpinäkyvyydelle eikä koskaan heikkene, kun tallennat sen uudelleen, ja siksi se on ensisijainen valinta kuvakaappauksille, logoille ja käyttöliittymägrafiikalle.', note: 'PNG säilyttää jokaisen pikselin täsmälleen sellaisena kuin se on ja tukee aitoa läpinäkyvyyttä, joten se kestää toistuvaa muokkausta heikkenemättä.' },
    webp: { about: 'WebP on Googlen nykyaikainen verkkokuvamuoto; se pakkaa selvästi tiukemmin kuin JPG tai PNG vastaavalla laadulla ja tukee läpinäkyvyyttä ja animaatiota, mutta moni työpöytä- ja painotalo-ohjelma ei vieläkään osaa avata sitä.', note: 'WebP tuottaa pienimmät tiedostot yleisistä verkkomuodoista ja tukee läpinäkyvyyttä.' },
    bmp: { about: 'BMP tallentaa raakaa, käytännössä pakkaamatonta pikselidataa, mikä tekee siitä täysin uskollisen ja valtavan tuhlaavan — valokuva voi helposti olla kymmenen kertaa suurempi kuin sama kuva PNG-muodossa.', note: 'BMP on raaka ja pakkaamaton, ja juuri sitä vanha Windows-ohjelmisto ja jotkin skannerit yhä odottavat.' },
    tiff: { about: 'TIFF on arkistoinnin ja painotuotannon muoto: häviötön, suuren värisyvyyden, useita sivuja tai tasoja mahtuu — ja vastaavasti kookas.', note: 'TIFF on se muoto, jota painot ja arkistot pyytävät, koska mitään ei heitetä pois.' },
    gif: { about: 'GIF on rajattu 256 väriin ruutua kohden, ja siksi valokuvat näyttävät siinä juovaisilta, mutta se animoituu ja käynnistyy itsestään upotettuna lähes kaikkialla internetissä.', note: 'GIF animoituu ja käynnistyy itsestään keskustelusovelluksissa, tikettijärjestelmissä ja foorumeilla, mutta on rajattu 256 väriin ruutua kohden.' },
    ico: { about: 'ICO on Windowsin kuvakesäiliö, joka sisältää saman grafiikan useassa koossa kerralla, jotta järjestelmä voi valita 16×16 välilehteen ja 256×256 työpöydän pikakuvakkeeseen.', note: 'ICO niputtaa useita tarkkuuksia yhteen tiedostoon, ja juuri sitä favicon-kuvakkeet ja Windows-sovellusten kuvakkeet tarvitsevat.' },
    heic: { about: 'HEIC on muoto, johon iPhone tallentaa kuvat oletuksena; se tarjoaa suunnilleen saman laadun kuin JPG noin puolella tilalla, mutta Windows, monet verkkolomakkeet ja melkoinen määrä vanhempia ohjelmia yksinkertaisesti kieltäytyvät avaamasta sitä.', note: 'HEIC on tiivis mutta huonosti tuettu Applen laitteiden ulkopuolella.' },
    svg: { about: 'SVG ei koostu pikseleistä lainkaan — se on XML:ää, joka kuvaa muotoja, polkuja ja tekstiä, joten se pysyy täysin terävänä missä tahansa koossa ja sitä voi muokata tai tyylitellä koodilla.', note: 'SVG skaalautuu mihin tahansa kokoon sumentumatta koskaan, koska se tallentaa muotoja pikselien sijaan.' },
    mp4: { about: 'MP4 on säiliö — yleensä H.264-video ja AAC-ääni — ja se on se yksi videomuoto, josta puhelimet, selaimet, televisiot, editointiohjelmat ja sosiaaliset alustat ovat kaikki yhtä mieltä.', note: 'MP4 toistuu käytännössä jokaisessa puhelimessa, selaimessa, televisiossa ja editointiohjelmassa ilman lisäohjelmia.' },
    avi: { about: 'AVI on Microsoftin säiliö 1990-luvulta; vanhemmat soittimet ja editointipaketit lukevat sitä yhä, mutta siinä ei ole nykyaikaisia suoratoisto-ominaisuuksia ja sen tiedostot ovat yleensä paljon suurempia kuin MP4.', note: 'AVI on se, mitä vanhemmat soittimet, DVD-työkalut ja vanha editointiohjelmisto odottavat.' },
    mov: { about: 'MOV on Applen QuickTime-säiliö, muoto johon iPhone ja Mac tallentavat ja jota Final Cut Pro ja iMovie käsittelevät sujuvimmin.', note: 'MOV on se säiliö, jonka kanssa Applen editointityökalut toimivat sujuvimmin.' },
    mkv: { about: 'MKV (Matroska) on avoin säiliö, johon mahtuu mikä tahansa määrä video-, ääni- ja tekstitysraitoja yhteen tiedostoon — erinomainen arkistointiin, mutta useimmat puhelimet, televisiot ja selaimet hylkäävät sen.', note: 'MKV voi kantaa useita ääni- ja tekstitysraitoja yhdessä tiedostossa.' },
    webm: { about: 'WebM on rojaltivapaa säiliö, joka on rakennettu HTML5-videolle, yleensä VP9:llä tai AV1:llä; selaimet rakastavat sitä, mutta työpöydän editointiohjelmat ja Applen ohjelmisto eivät useinkaan koske siihen.', note: 'WebM on pieni ja suoratoistuu selaimissa natiivisti.' },
    wmv: { about: 'WMV on Microsoftin Windows Media -videomuoto, käytännössä vain Windowsille ja suurelta osin hylätty vanhojen yritystallenteiden ja ruutukaappausten ulkopuolella.', note: 'WMV on Windows Media -muoto, jolla on hyvin heikko tuki muualla.' },
    flv: { about: 'FLV oli Flash-videon takana ollut säiliö, ja sen jälkeen kun Flash poistettiin kaikista selaimista, se on käytännössä toistokelvoton arkistomuoto.', note: 'FLV on kuollut Flash-ajan säiliö.' },
    mp3: { about: 'MP3 on häviöllinen: kooderi poistaa pysyvästi ne signaalin osat, joita se ennustaa ettet kuule, mikä kutistaa kappaleen noin kymmenesosaan ja on syy siihen, että se toistuu aivan kaikessa.', note: 'MP3 on noin kymmenen kertaa pienempi kuin pakkaamaton ääni ja toistuu jokaisessa puhelimessa, autostereossa ja soittimessa viimeisten kahdenkymmenen vuoden ajalta.' },
    wav: { about: 'WAV tallentaa äänen pakkaamattomana, näyte näytteeltä, täsmälleen sellaisena kuin se äänitettiin — siksi studiot käyttävät sitä ja siksi minuutti CD-laatuista stereoa vie noin 10 megatavua.', note: 'WAV on pakkaamaton ja häviötön, joten editointi- ja masterointiohjelmat voivat käsitellä sitä purkamatta ensin mitään.' },
    flac: { about: 'FLAC pakkaa äänen häviöttömästi: se on noin puolet WAVin koosta ja purkautuu silti bitilleen samanlaiseksi kopioksi alkuperäisestä äänityksestä.', note: 'FLAC on bitilleen sama mutta noin puolet WAVin koosta.' },
    aac: { about: 'AAC on häviöllinen koodekki Apple Musicin, YouTuben ja useimpien suoratoistopalvelujen taustalla; samalla bittinopeudella se kuulostaa yleensä paremmalta kuin MP3.', note: 'AAC kuulostaa paremmalta kuin MP3 samalla bittinopeudella ja on vakio Applen ja suoratoiston maailmassa.' },
    ogg: { about: 'OGG Vorbis on patenttivapaa häviöllinen koodekki, jota pelit, avoimen lähdekoodin ohjelmistot ja Wikipedia suosivat, laadultaan MP3:n veroinen pienemmällä koolla.', note: 'OGG on vapaa patenttirajoituksista, ja siksi pelimoottorit ja avoimen lähdekoodin projektit suosivat sitä.' },
    m4a: { about: 'M4A on MP4-säiliö, joka sisältää pelkkää ääntä, tavallisesti AAC:tä — muoto, jota iTunes, Apple Music ja iPhonen sanelut tuottavat.', note: 'M4A on Applen ekosysteemin vakioäänitiedosto.' },
    wma: { about: 'WMA on Microsoftin häviöllinen äänikoodekki Windows Media Playerin ajalta, harvoin tuettu Windowsin ulkopuolella ja käytännössä lopetettu.', note: 'WMA on vanhentunut, vain Windowsissa elävä äänikoodekki.' },
    zip: { about: 'ZIP on arkistomuoto, joka on sisäänrakennettu Windowsiin, macOSiin ja jokaiseen puhelimeen — kaksoisnapsautus riittää, mitään ei tarvitse asentaa.', note: 'ZIP avautuu kaksoisnapsautuksella Windowsissa, macOSissa, Linuxissa, iOSissa ja Androidissa ilman että mitään asennetaan.' },
    rar: { about: 'RAR on suljettu arkistomuoto, jossa on hyvä pakkaus ja palautustiedot, mutta sen avaamiseen tarvitaan WinRAR tai yhteensopiva työkalu.', note: 'RAR vaatii purkamiseen kolmannen osapuolen ohjelman.' },
    '7z': { about: '7Z käyttää LZMA-pakkausta, joka tuottaa säännönmukaisesti selvästi pienempiä arkistoja kuin ZIP — hintana se, että avaamiseen tarvitaan 7-Zip tai yhteensopiva työkalu.', note: '7Z pakkaa huomattavasti tiukemmin kuin ZIP, millä on merkitystä suurten kansioiden ja maksullisen pilvitallennuksen kanssa.' },
    tar: { about: 'TAR-tiedosto niputtaa monta tiedostoa yhdeksi pakkaamatta niitä; se tulee Unix-maailmasta ja säilyttää oikeudet ja hakemistorakenteen.', note: 'TAR säilyttää Unix-oikeudet ja hakemistorakenteen.' },
    gz: { about: 'GZ (gzip) pakkaa yhden datavirran ja on sitä, mitä Linux-palvelimet ja komentorivityökalut tuottavat; Windowsissa sen avaaminen on hankalaa ilman lisäohjelmia.', note: 'GZ on Linuxin ja verkkopalvelinten vakiopakkausmuoto.' },
    srt: { about: 'SRT on tavallisen tekstin tekstitysmuoto, jonka jokainen editointiohjelma ja jokainen soitin ymmärtää: numeroidut repliikit, aikakoodiväli ja dialogirivi.', note: 'SRT kelpaa YouTubelle, Vimeolle, Premierelle, Final Cutille ja jokaiselle tavalliselle soittimelle.' },
    avif: {
      about: "AVIF on moderni kuvamuoto, joka perustuu AV1-videokoodekkiin; se tuottaa tietyllä laadulla joitakin pienimmistä saatavilla olevista tiedostoista ja tukee läpinäkyvyyttä, mutta vanhemmat ohjelmat eivät usein pysty avaamaan sitä.",
      note: "AVIF antaa hyvin pieniä tiedostoja hyvällä laadulla nykyaikaisiin selaimiin ja sovelluksiin.",
    },
    md: {
      about: "Markdown on pelkkää tekstiä kevyin muotoilumerkein — # otsikoille, * korostukselle, - luetteloille — joten se pysyy luettavana raakatekstinä ja voidaan hahmontaa muotoilluksi asiakirjaksi.",
      note: "Markdown pitää sisältösi yksinkertaisena tekstinä, jota on helppo muokata ja seurata versionhallinnassa.",
    },
    aif: {
      about: "AIF on AIFF:n lyhyt tiedostopääte, Applen pakkaamaton äänimuoto: jokainen näyte tallennetaan täsmälleen sellaisena kuin se äänitettiin, mikä antaa studiolaadun ja hyvin suuret tiedostot.",
      note: "AIF pitää äänen pakkaamattomana ja valmiina editointiin Macilla.",
    },
  },
  reasons: {
    'pdf-to-word': 'Tavallinen sysäys on muutos, jota et voi tehdä itse PDF-tiedostoon — sopimuslauseke, ansioluettelon kohta tai raportin kappale, jonka on muututtava ilman että koko asiakirja näppäillään uudelleen.',
    'word-to-pdf': 'Word muunnetaan PDF-muotoon aivan asiakirjan elinkaaren lopussa: kun ansioluettelo, tarjous tai allekirjoitettu lomake lähtee jollekulle, jonka kirjasimiin, Word-versioon ja marginaaleihin et voi vaikuttaa.',
    'pdf-to-excel': 'Tyypillinen tapaus on tiliote, lasku tai raportti, joka on olemassa vain PDF-muodossa mutta jonka luvut pitää laskea yhteen, lajitella tai piirtää kaavioksi.',
    'excel-to-pdf': 'Tämä tehdään ennen kuin budjetti tai hinnasto lähetetään jollekulle, jonka pitää lukea se muttei muuttaa sitä, ja ennen tulostusta — PDF naulaa kiinni ne sivunvaihdot, jotka Excel muuten laskisi uudelleen jokaisella koneella.',
    'pptx-to-pdf': 'Useimmat muuntavat esityksen PDF-muotoon ennen lähettämistä tai jakamista, jotta diat eivät siirry ja jotta kenenkään ei tarvitse asentaa PowerPointia niiden avaamiseksi.',
    'pdf-to-pptx': 'Tätä tarvitset, kun esityksen ainoa säilynyt kopio on kokouksen jälkeen kierrätetty PDF ja diat pitää päivittää tai käyttää uudelleen.',
    'pdf-to-txt': 'Tavallisia syitä: asiakirjan syöttäminen skriptille, hakuindeksille tai tekoälytyökalulle, tai pitkän raportin kiteyttäminen joksikin, jota voi hakea, verrata ja liittää minne tahansa.',
    'pdf-to-html': 'Se on nopein tapa julkaista olemassa oleva raportti, käsikirja tai esite verkkosivustolla ilman että sivu rakennetaan käsin uudelleen.',
    'html-to-pdf': 'Tämä tehdään verkkosivun arkistoimiseksi juuri sellaisena kuin se tänään näyttää, tai HTML-muotoisen lasku- tai raporttipohjan muuttamiseksi joksikin tulostettavaksi ja lähetettäväksi.',
    'rtf-to-pdf': 'RTF tulee yleensä vanhemmasta ohjelmistosta tai juridisista asiakirjapohjista; PDF-muotoon vieminen antaa yhden tiedoston, joka avautuu kaikkialla samanlaisena eikä muutu vahingossa.',
    'pdf-to-rtf': 'Tämä on valinta silloin, kun tarvitset muokattavan kopion PDF-tiedostosta mutta et voi olettaa vastaanottajalla olevan Wordia — käytännössä jokainen koskaan kirjoitettu tekstinkäsittelyohjelma avaa RTF:n.',
    'odt-to-pdf': 'Tyypillinen tapaus: kirjoitit asiakirjan LibreOfficessa tai OpenOfficessa, ja sen vastaanottaja käyttää Microsoft Officea — tai ei mitään.',
    'pdf-to-epub': 'PDF-tiedoston lukeminen puhelimella tarkoittaa jatkuvaa zoomaamista ja vaakasuuntaista vierittämistä; tässä muunnoksessa on ennen kaikkea kyse siitä, että pitkästä asiakirjasta saadaan aidosti luettava pienellä näytöllä tai lukulaitteella.',
    'epub-to-pdf': 'EPUB muunnetaan PDF-muotoon, kun kirja halutaan tulostaa, siihen halutaan merkintöjä kiinteillä sivunumeroilla tai se halutaan lähettää jollekulle, jolla ei ole lukusovellusta.',
    'document-converter': 'Tämä on työkalu, jonka avaat, kun saat asiakirjan siinä muodossa, joka lähettäjällä sattui olemaan, ja tarvitset sen siinä muodossa, jonka oma ohjelmasi todella avaa.',
    'ebook-converter': 'E-kirjakaupat ja lukulaitteet suosivat kukin omaa muotoaan, joten tällä siirrät omistamasi kirjan yhdeltä lukulaitteelta tai sovellukselta toiselle.',
    'jpg-to-png': 'Tavallinen sysäys on muokkaus: pitää irrottaa tausta, asettaa logo toisen kuvan päälle tai estää kuvakaappausta sumentumasta joka kerta, kun se tallennetaan uudelleen.',
    'png-to-jpg': 'Tämä on ratkaisu kuvakaappaukseen tai vientiin, joka on liian suuri liitettäväksi sähköpostiin tai pääsemään latauslomakkeen kokorajan ohi.',
    'webp-to-png': 'Tätä tarvitaan yleensä sen jälkeen, kun kuva on tallennettu verkkosivustolta: WebP latautuu ongelmitta, mutta vanhemmat kuvankäsittelyohjelmat, toimisto-ohjelmat ja jotkin painopalvelut kieltäytyvät yhä avaamasta sitä.',
    'webp-to-jpg': 'Useimmat tekevät tämän saadakseen verkkosivuston kuvan johonkin yleisesti hyväksyttyyn — sähköpostiin, vanhempaan julkaisujärjestelmään, valokuvien tulostuspalveluun tai kollegan ikivanhaan ohjelmaan.',
    'heic-to-jpg': 'Tämä on klassinen iPhone-ongelma: kuvat näyttävät hyviltä puhelimessa mutta päätyvät Windows-koneelle tai verkkolomakkeeseen .heic-tiedostoina, joita ei saa auki.',
    'heic-to-png': 'Käytä tätä, kun aiot muokata kuvaa etkä vain jakaa sitä — PNG antaa kuvankäsittelyohjelmallesi häviöttömät pikselit vastikään uudelleen pakatun kopion sijaan.',
    'svg-to-png': 'Tavallinen syy on työkalu, joka torjuu vektorit: esitys, ilmoitus kauppapaikalla, sähköpostin allekirjoitus tai kuvaketuotantoketju, joka ottaa vastaan vain pikseleitä.',
    'svg-to-jpg': 'Tämä on paikkoihin, jotka haluavat yksinkertaisen valokuvamaisen tiedoston — asiakirjaan, sosiaalisen median julkaisuun tai latauslomakkeeseen, joka torjuu sekä SVG-merkinnän että läpinäkyvyyden.',
    'bmp-to-png': 'BMP-tiedostoja tulee vanhasta Windows-ohjelmistosta ja skannereista järjettömän kokoisina; PNG tallentaa täsmälleen samat pikselit murto-osaan tilasta.',
    'tiff-to-jpg': 'Skannerit ja ammattikamerat tuottavat TIFF-tiedostoja, jotka ovat aivan liian suuria sähköpostiin, joten JPG on se, minkä lähetät, kun arkistokopio on turvassa.',
    'gif-to-png': 'Tämä tehdään liikkumattomalle GIF-kuvalle — logolle, kuvakkeelle tai viedylle yksittäiselle ruudulle — joka näyttää värijuovia tai rispaantuneen reunan 256 värin rajan takia.',
    'png-to-ico': 'Lähes jokainen, joka muuntaa PNG:n ICO-muotoon, rakentaa favicon-kuvaketta tai Windows-sovelluksen kuvaketta, ja molemmat odottavat ICO-säiliötä eikä tavallista kuvatiedostoa.',
    'jfif-to-png': 'JFIF-tiedostoja ilmestyy tyypillisesti silloin, kun kuva tallennetaan Outlookista tai selaimesta ja Windows sitten kieltäytyy antamasta sitä sille sovellukselle, jota oikeasti halusit käyttää.',
    'heic-to-pdf': 'Kätevä, kun valokuvaat asiakirjoja, kuitteja tai valkotaulua iPhonella ja ne pitää toimittaa yhtenä tiedostona eikä kuvakansiona.',
    'image-compressor': 'Tavallinen syy on jokin kova raja — latauslomake, sähköpostiliitteen yläraja tai verkkosivu, joka latautuu liian hitaasti siksi, että sen kuvat ovat paljon suurempia kuin niiden tarvitsisi olla.',
    'jpeg-compressor': 'Valokuvaajat ja sivustojen omistajat käyttävät tätä, kun täysikokoiset JPEG-kuvat hidastavat sivua tai eivät mahdu latausrajan läpi.',
    'png-compressor': 'Kuvakaappaukset ja viety käyttöliittymägrafiikka painavat usein useita megatavuja ilman hyvää syytä; tämä kutistaa ne ennen kuin ne päätyvät asiakirjaan, tikettiin tai verkkosivulle.',
    'mp4-to-avi': 'Syy on lähes aina vanhempi laite tai tietty ohjelma — jotkin vanhat soittimet, DVD-työkalut ja kameraohjelmat lukevat AVI:a eivätkä mitään muuta.',
    'mp4-to-mov': 'Tämä on tavallisesti ensimmäinen askel ennen editointia Macilla, koska Final Cut Pro ja iMovie käsittelevät QuickTime-tiedostoja sujuvimmin.',
    'mov-to-mp4': 'iPhone ja Mac tallentavat MOV-muotoon; kaikki muu odottaa MP4:ää, joten tämä on se muunnos, joka ajetaan ennen kuin leike ladataan, lähetetään tai julkaistaan.',
    'mkv-to-mp4': 'MKV on erinomainen säilytykseen, mutta puhelimet, televisiot, selaimet ja useimmat editointiohjelmat eivät toista sitä — MP4-muotoon vieminen tekee tiedostosta vasta aidosti käyttökelpoisen.',
    'webm-to-mp4': 'Verkosta tallennetut WebM-tiedostot kieltäytyvät usein avautumasta QuickTimessa, iOSissa tai Premieressä; MP4 on se muoto, jonka ne kaikki hyväksyvät.',
    'avi-to-mp4': 'Tämä on vakiopelastus vanhoille videokameran otoksille ja arkistoiduille leikkeille, jotka nielevät gigatavuja eivätkä toistu millään puhelimella.',
    'flv-to-mp4': 'Flash on poissa jokaisesta selaimesta, joten jokainen jäljellä oleva FLV on käytännössä toistokelvoton — MP4-muotoon vieminen pitää arkistoidun materiaalin katsottavana.',
    'wmv-to-mp4': 'WMV on pelkästään Windowsissa elävä jäänne, joten tämä tehdään ennen kuin vanha tallenne tai ruutukaappaus lähetetään Macille, iPhonelle tai verkkoalustalle.',
    'mp4-to-mp3': 'Kyse on yleensä äänestä eikä kuvasta — luennosta, haastattelusta, podcastista tai musiikkivideosta, jonka haluat puhelimeesi ilman että raahaat videota mukana.',
    'video-to-mp3': 'Tähän tartutaan, kun ääni on se osa, joka kannattaa säilyttää: tallennettu esitelmä, haastattelu, harjoitus tai ääniraita.',
    'mp4-converter': 'Tämä on työkalu silloin, kun leike ei toistu tai ei lataudu, koska MP4 on se yksi videomuoto, jonka puhelimet, selaimet, televisiot ja sosiaaliset alustat kaikki hyväksyvät.',
    'video-converter': 'Käytä sitä, kun leikkeen pitää vaihtaa maailmaa — ulos editointiohjelmasta, puhelimeen, selaimeen tai alustalle, joka ottaa vastaan vain yhden tietyn säiliön.',
    'mp3-to-wav': 'Tavallinen syy on editointi: musiikkiohjelmat, masterointiketjut ja monet radion tai pelien ääniprosessit haluavat pakkaamattoman WAVin, jottei niiden tarvitse purkaa pakattua tiedostoa jokaisen yksittäisen toimenpiteen kohdalla.',
    'wav-to-mp3': 'Äänitykset tulevat kenttätallentimesta tai musiikkiohjelmasta valtavina WAV-tiedostoina; MP3 tekee niistä tarpeeksi pieniä lähetettäväksi, ladattavaksi tai puhelimeen mahtuviksi.',
    'flac-to-mp3': 'FLAC-kirjasto kuulostaa kotona erinomaiselta, mutta autostereot, vanhemmat puhelimet ja halvat soittimet torjuvat sen usein — MP3 on se yhteensopivuuskopio, jonka otat mukaan.',
    'aac-to-mp3': 'Tässä on enimmäkseen kyse yhteensopivuudesta: AAC tulee Applen ja suoratoiston maailmasta, kun taas vanhemmat soittimet, autoradiot ja DJ-ohjelmat odottavat MP3:a.',
    'ogg-to-mp3': 'OGG ilmestyy peleissä, Wikipediassa ja avoimen lähdekoodin ohjelmistoissa, eikä juuri mikään puhelimen tai auton tavallisista soittimista avaa sitä.',
    'wma-to-mp3': 'WMA on jäänne Windows Media Playerin ajalta, ja näin pelastetaan vanha ripattu musiikkikokoelma puhelimeen tai suoratoistokirjastoon.',
    'm4a-to-mp3': 'Tämä on tavallinen askel, kun musiikkia tai iPhonen saneluja siirretään Applen laitteilta ohjelmiin, autoihin tai soittimiin, jotka ymmärtävät vain MP3:a.',
    'mp3-to-aac': 'Jotkin laitteet ja sovellukset — erityisesti Applen ja suoratoistoalustojen piirissä — suosivat AAC:tä, joten tämä on yhteensopivuusmuunnos eikä laadun parannus.',
    'mp3-to-ogg': 'OGG-muotoon muunnetaan pelimoottoreita, avoimen lähdekoodin projekteja ja alustoja varten, joilla vaaditaan patenttivapaata koodekkia.',
    'audio-converter': 'Tämä on työkalu siihen hetkeen, kun tiedosto ei toistu: yksi paikka, jossa saat äänen juuri siihen yleisistä muodoista, jota laitteesi, editointiohjelmasi tai latauslomakkeesi vaatii.',
    'rar-to-zip': 'RAR vaatii avaamiseen lisäohjelman, joten tämä tehdään ennen kuin arkisto lähetetään jollekulle, joka ei aio asentaa WinRARia.',
    '7z-to-zip': '7Z pakkaa paremmin mutta vaatii asennetun 7-Zipin; ZIP-muodossa vastaanottaja voi yksinkertaisesti kaksoisnapsauttaa tiedostoa.',
    'tar-to-zip': 'TAR tulee Linuxin ja macOSin komentoriviltä, kun taas ZIP on se, jonka Windowsia käyttävä kollega saa auki asentamatta yhtään mitään.',
    'gz-to-zip': 'GZ-tiedostot saapuvat yleensä palvelimelta tai Linux-työkalusta ja ovat hankalia Windowsissa, jossa ZIP purkautuu kaksoisnapsautuksella.',
    'zip-to-7z': 'Tässä on kyse koosta: 7Z:n pakkaus on selvästi tiukempi, millä on merkitystä, kun arkistoit suurta kansiota tai maksat pilvitallennuksesta gigatavuittain.',
    'video-to-gif': 'Tyypillinen käyttö on lyhyt silmukka keskusteluviestiin, README-tiedostoon, virheraporttiin tai julkaisuun — paikkoihin, joissa GIF käynnistyy itsestään upotettuna eikä videotiedosto käynnisty.',
    'mp4-to-gif': 'Tyypillinen käyttö on lyhyt silmukka keskusteluun, README-tiedostoon, virheraporttiin tai julkaisuun, jossa GIF käynnistyy itsestään upotettuna, kun taas video jäisi vain liitteeksi.',
    'webm-to-gif': 'Verkosta tallennettuja WebM-leikkeitä ei useinkaan saa upotettua sinne, minne haluat, kun taas GIF käynnistyy upotettuna keskustelusovelluksissa, tikettijärjestelmissä ja foorumeilla.',
    'mov-to-gif': 'Tämä tehdään QuickTime-ruutukaappaukselle, jonka pitää näkyä upotettuna pull requestissa, tukipyynnössä tai julkaisussa.',
    'avi-to-gif': 'Muutaman sekunnin muuttaminen vanhasta AVI-leikkeestä GIF-kuvaksi on yksinkertaisin tapa saada ne asiakirjaan, keskusteluketjuun tai verkkosivulle.',
    'gif-to-mp4': 'Pitkät GIF-tiedostot ovat valtavia ja nykivät; MP4 näyttää saman animaation murto-osalla koosta, ja juuri siksi sosiaaliset alustat muuntavat ne kulissien takana.',
    'image-to-gif': 'Hyödyllinen, kun alusta tai vanhempi järjestelmä nimenomaan odottaa GIF-kuvaa, tai kun tarvitset pysäytyskuvan samassa muodossa kuin olemassa oleva animaatiosarja.',
    'gif-compressor': 'Animoidut GIF-kuvat paisuvat nopeasti, ja tämä on ratkaisu, kun jokin niistä on liian raskas sähköpostiin, keskustelun latausrajaan tai sivulle, jonka pitää latautua nopeasti.',
    'merge-pdf': 'Klassinen tapaus on hakemus tai vahinkoilmoitus: lomake, skannaus ja kuitti, joiden kaikkien pitää saapua yhtenä asiakirjana.',
    'split-pdf': 'Yleensä tarvitset täsmälleen yhden asian paljon pidemmästä tiedostosta — yhden luvun, yhden laskun, yhden allekirjoitetun sivun viidenkymmenen sivun skannauksesta.',
    'compress-pdf': 'Lähes aina kokoraja: sähköpostiliitteen yläraja, viranomaislomake tai portaali, joka torjuu kaiken yli muutaman megatavun.',
    'rotate-pdf': 'Tämä korjaa arkisen skanneriongelman — sivut, jotka tulivat ulos kyljellään tai ylösalaisin siksi, miten arkit syötettiin.',
    'protect-pdf': 'PDF-tiedostot suojataan salasanalla ennen palkkalaskelmien, sopimusten tai lääkärinlausuntojen lähettämistä, jottei sisältö ole luettavissa sille, jolle viesti seuraavaksi välitetään.',
    'unlock-pdf': 'Käytä tätä omistamiisi asiakirjoihin, kun salasana on tiedossa mutta rajoitus on tiellä — esimerkiksi tiliotteeseen, jota et saa tulostettua.',
    'view-metadata': 'Se vastaa kysymyksiin, joita tiedosto ei kerro suoraan: mikä kamera otti tämän kuvan, kuinka pitkä tämä tallenne todella on, mikä koodekki tässä videossa on, montako sivua tässä PDF-tiedostossa on.',
    'ocr': 'Tilanne on aina sama: sinulla on asiakirja kuvana ja tarvitset siitä sanat — hakeaksesi niistä, lainataksesi niitä, muokataksesi niitä tai arkistoidaksesi ne kunnolla.',
    'pdf-compress-ai': 'Tartu tähän, kun tavallista pakkausta on jo kokeiltu ja tiedosto on yhä liian suuri sille latausrajalle, jonka kanssa kamppailet.',
    'text-to-speech': 'Tätä käytetään jonkin kuuntelemiseen lukemisen sijaan — artikkelin työmatkalla, käsikirjoituksen ääneen luettuna kömpelöiden muotoilujen löytämiseksi, tai videon selostusäänen.',
    'speech-to-text': 'Tavallinen tapaus on tallenne, jonka tarvitset kirjallisena: kokous, haastattelu, luento tai sanelu, josta pitää tulla muistiinpanoja, pöytäkirja tai lainattava litterointi.',
    'auto-subtitle': 'Tekstitykset tekevät videosta katsottavan ilman ääntä ja löydettävän hakukoneille, ja niiden kirjoittaminen käsin vie lyhyessäkin leikkeessä paljon enemmän aikaa kuin luullaan.',
    'document-translation': 'Tavoitteena on lukea tai lähettää asiakirja toisella kielellä menettämättä sitä taittoa, joka tekee siitä luettavan.',
    "jpeg-to-jpg": "Tavallinen syy on lomake, kotisivukone tai vanhempi ohjelma, joka vaatii .jpg-päätteen ja hylkää täsmälleen saman kuvan, kun se on tallennettu .jpeg-muodossa.",
    "jpg-to-jpeg": "Jotkin latauslomakkeet, kuvalaboratoriot ja vanhemmat järjestelmät hyväksyvät ainoana päätteenä .jpeg ja hylkäävät .jpg-tiedoston, vaikka sisältö on identtinen.",
    "jpg-to-webp": "Useimmat haluavat tällä nopeuttaa verkkosivustoa: WebP-kuvat ovat tyypillisesti neljänneksen tai kolmanneksen pienempiä kuin sama JPG samankaltaisella visuaalisella laadulla, mikä tarkoittaa nopeampia sivuja ja parempia nopeustuloksia.",
    "png-to-webp": "Tavallinen tapaus on sivusto täynnä hitaasti latautuvia PNG-kuvakaappauksia, logoja ja grafiikkaa — WebP säilyttää läpinäkyvyyden mutta pienentää yleensä tiedostokokoa huomattavasti.",
    "avif-to-jpg": "Moderneilta sivustoilta tai uudemmista puhelimista tallennetut AVIF-kuvat eivät usein aukea vanhemmissa kuvankäsittelyohjelmissa, toimisto-ohjelmissa tai latauslomakkeissa, kun taas JPG toimii aivan kaikkialla.",
    "avif-to-png": "Tarvitset tätä yleensä silloin, kun AVIF-grafiikkaa pitää muokata, kerrostaa tai sijoittaa toiselle taustalle ohjelmassa, joka ei vielä osaa lukea AVIF-muotoa.",
    "bmp-to-jpg": "Vanhojen skannereiden, Windows Paintin tai teollisuusohjelmistojen BMP-tiedostot ovat valtavia, koska ne ovat pakkaamattomia; JPG-muotoon muunnettuina ne ovat tarpeeksi pieniä lähetettäviksi sähköpostilla tai ladattaviksi palveluun.",
    "tiff-to-png": "Skannaukset ja painovalmiit TIFF-tiedostot ovat verkkoon liian raskaita ja huonosti tuettuja; PNG pitää jokaisen pikselin terävänä ja aukeaa missä tahansa selaimessa.",
    "ico-to-png": "Tyypillinen syy on päästä käsiksi faviconin tai Windows-kuvakkeen sisältämään kuvaan, jotta sitä voi käyttää uudelleen suunnittelussa, asiakirjassa tai esityksessä.",
    "gif-to-jpg": "Yleensä tarvitset GIF-animaatiosta vain yhden pysäytyskuvan — pikkukuvaksi, asiakirjaan tai sivustolle, joka ei hyväksy animoituja kuvia.",
    "jpg-to-pdf": "Klassinen tilanne on hakemus tai korvausvaatimus, joka vaatii PDF-tiedoston, vaikka sinulla on vain puhelimella otettu kuva kuitista, henkilökortista tai allekirjoitetusta sivusta.",
    "png-to-pdf": "Sitä käytetään kuvakaappausten, kaavioiden tai skannattujen sivujen toimittamiseen kunnollisena asiakirjana — monet portaalit ja sähköpostin vastaanottajat odottavat PDF-tiedostoa eivätkä kuvaa.",
    "txt-to-pdf": "Pelkkä teksti näyttää erilaiselta jokaisessa editorissa; kun muunnat muistiinpanot, lokit tai luonnoksen PDF-muotoon, fontti ja asettelu lukittuvat, joten teksti näyttää ja tulostuu kaikille samanlaisena.",
    "markdown-to-pdf": "Kirjoittajat ja kehittäjät luonnostelevat Markdown-muodossa, mutta kollegat ja asiakkaat odottavat valmista asiakirjaa — README-tiedostoa, raporttia tai muistiinpanoja, jotka aukeavat ilman erityistyökaluja.",
    "csv-to-excel": "Pankkien, verkkokauppojen ja tietokantojen CSV-viennit aukeavat usein rikkinäisin sarakkein, kadonnein etunollin tai sekaisin päivämäärin; Excel-työkirja pitää tiedot kunnollisissa soluissa valmiina summille ja kaavioille.",
    "excel-to-csv": "Useimmat tuontityökalut — CRM-järjestelmät, uutiskirjepalvelut, verkkokaupat ja tietokannat — hyväksyvät vain CSV-muodon, joten laskentataulukko on litistettävä ennen kuin sen voi ladata.",
    "word-to-txt": "Tavallinen syy on käyttää tekstiä paikassa, joka ei ymmärrä Word-tiedostoja: koodieditorissa, sivuston julkaisujärjestelmässä, tekstitystyökalussa tai tekoälyn kehotteessa.",
    "mp4-to-webm": "Verkkokehittäjät muuntavat WebM-muotoon saadakseen avointa, rojaltivapaata videota, joka toistuu suoraan selaimissa ja on usein samalla laadulla pienempi kuin MP4.",
    "mp4-to-mkv": "MKV on suosituin säiliömuoto arkistoille ja mediapalvelimille, kuten Plexille tai Jellyfinille, koska yksi tiedosto voi sisältää useita ääniraitoja, tekstityksiä ja kappalejakoja.",
    "m4v-to-mp4": "iTunesista tai Applen laitteista peräisin olevat M4V-tiedostot eivät usein aukea Androidilla, Windowsissa tai videoeditoreissa, kun taas MP4 toistuu kaikkialla.",
    "3gp-to-mp4": "Vanhat puhelinvideot on usein tallennettu 3GP-muotoon, jota nykyaikaiset tietokoneet, puhelimet ja somepalvelut eivät usein pysty toistamaan tai vastaanottamaan.",
    "mpeg-to-mp4": "DVD-kopioiden, vanhojen videokameroiden ja TV-tallenteiden MPEG-tiedostot ovat suuria ja puhelimissa huonosti tuettuja; MP4 pienentää ne ja toistuu kaikkialla.",
    "m4a-to-wav": "Äänieditorit, samplerit ja jotkin lähetystyökalut vaativat pakkaamatonta WAV-ääntä, kun taas iPhonen äänimuistiot ja iTunes-lataukset tulevat M4A-muodossa.",
    "flac-to-wav": "Äänityöasemat, CD-polttoohjelmat ja jotkin laitesoittimet käsittelevät WAV-muotoa mutta eivät FLAC-muotoa, ja koska molemmat ovat häviöttömiä, mitään ei menetetä matkalla.",
    "wav-to-flac": "Muusikot ja arkistoijat käyttävät tätä pienentääkseen suuret WAV-äänitteet noin puoleen niin, että jokainen näyte säilyy bitilleen samana.",
    "aiff-to-mp3": "Logicin, GarageBandin tai Macin näytekirjastojen AIFF-äänitteet ovat suuria; MP3 tekee niistä tarpeeksi pieniä jaettaviksi, suoratoistettaviksi tai toistettaviksi millä tahansa laitteella.",
    "opus-to-mp3": "WhatsAppin ja Telegramin ääniviestit sekä monet verkkotallenteet tallennetaan OPUS-muotoon, jota autostereot, vanhemmat soittimet ja editorit eivät usein toista.",
    "mp3-to-m4a": "Tätä halutaan yleensä Applen laitteille — M4A toimii hyvin Apple Musicissa ja iTunesissa ja on lähtökohta iPhonen soittoäänelle.",
    "zip-to-tar": "Kehittäjät ja palvelinten ylläpitäjät tarvitsevat TAR-muotoa, kun he julkaisevat Linux-järjestelmiin, rakentavat konttikuvia tai käyttävät työkaluja, jotka odottavat ZIP-tiedoston sijaan tarballia.",
    "rar-to-7z": "RAR-arkistoja pakataan uudelleen 7Z-muotoon, jotta voidaan käyttää ilmaista ja avointa muotoa, jonka 7-Zip luo ja avaa suoraan, usein vielä paremmalla pakkauksella.",
    "pdf-to-images": "Se on tehty sosiaaliseen mediaan: Instagramin karusellit, LinkedIn-julkaisut ja tarinat vaativat kuvia eivätkä PDF-tiedostoja, joten esityksestä, ruokalistasta tai mainoslehtisestä on tehtävä yksi kuva sivua kohden.",
    "photo-collage": "Tavallinen syy on jakaa useita kuvia yhtenä — ennen ja jälkeen -vertailu, lomakooste tai tuotevalikoima, joka halutaan nähdä yhdellä silmäyksellä sen sijaan, että kuvia selattaisiin yksi kerrallaan.",
    "resize-for-social-media": "Jokainen alusta rajaa kuvat omaan muotoonsa: Story-julkaisuna jaettu vaakakuva saa mustat palkit tai menettää reunansa, ja korkea puhelinkuva leikataan syötteessä lyhyemmäksi — kun rajaat kuvan itse, päätät, mitä kuvaan jää.",
    "profile-picture-maker": "Profiilikuvat näytetään pieninä ja yleensä ympyräksi leikattuina, joten rennossa otoksessa kasvot päätyvät usein sivuun tai rajautuvat pois; oikein rajattu neliö korjaa tämän ennen latausta.",
    "social-media-image-compressor": "Puhelimen kuvat ovat usein 4000 pikseliä leveitä ja useiden megatavujen kokoisia; kun alusta pienentää ne itse näyttökokoonsa, se myös pakkaa ne voimakkaasti, ja siitä syntyvät sumeus ja palikoituneet taivaat.",
  },
  t: {
    'list.and': 'ja',
    'family.document': 'asiakirja',
    'family.image': 'kuva',
    'family.video': 'video',
    'family.audio': 'ääni',
    'family.ebook': 'e-kirja',
    'family.archive': 'arkisto',
    'family.subtitle': 'tekstitys',
    'family.none': 'tiedosto',
    'unit.sample': 'jokainen näyte',
    'unit.pixel': 'jokainen pikseli',

    'intro.convert': '{{fromAbout}} {{toAbout}} {{reason}} {{toNote}}',
    'intro.convert.noSource': '{{fn}} on tämän muunnoksen lähdemuoto.',
    'intro.lead': '{{lead}} {{reason}}',
    'intro.hub': 'Tämä on yleiskäyttöinen {{category}}muunnin: se ottaa vastaan {{inputs}} ja kirjoittaa {{outputs}}, joten sinun ei tarvitse metsästää sitä yhtä työkalua, joka sopii juuri sinun muotopariisi. {{reason}} Valitse kohdemuoto yllä — muunnos tehdään palvelimella, mitään ei tarvitse asentaa.',
    'intro.hubExtract': 'Tämä työkalu vetää ääniraidan ulos videotiedostosta ja tallentaa sen erikseen, jolloin videosta tulee tavallinen äänitiedosto, joka toistuu kaikkialla. Se ottaa vastaan {{inputs}} ja kirjoittaa {{outputs}}. Videoraita yksinkertaisesti hylätään, ja siksi tulos on murto-osa alkuperäisestä koosta. {{reason}}',
    'intro.hubGif': 'Tämä työkalu muuttaa {{inputs}}-tiedostot animoiduiksi GIF-kuviksi. {{gifAbout}} {{reason}}',
    'intro.hubGif.gifAbout': 'GIF on rajattu 256 väriin ruutua kohden, ja siksi valokuvat näyttävät siinä juovaisilta, mutta se animoituu ja käynnistyy itsestään upotettuna lähes kaikkialla internetissä.',
    'intro.compress': '{{about}} Tämä työkalu koodaa {{fn}}-tiedostosi uudelleen pienempään kokoon muuttamatta muotoa, joten lataamasi tiedosto on yhä tavallinen {{fn}}, joka avautuu täsmälleen siellä, missä alkuperäinenkin. {{reason}}{{extra}}',
    'intro.compress.lossless': ' Koska {{fn}} on häviötön, suurin osa säästöstä syntyy fiksummasta koodauksesta ja supistetusta väripaletista eikä yksityiskohtien heittämisestä pois.',
    'intro.soon': '{{reason}} Tämä työkalu ei ole vielä käytössä — se on kehitteillä ja ilmestyy tänne heti kun se on valmis.',
    'intro.lead.pdf-merge': 'Yhdistäminen kokoaa useita PDF-tiedostoja yhdeksi valitsemassasi järjestyksessä hahmontamatta sivuja uudelleen — teksti pysyy valittavana ja kuvat säilyttävät alkuperäisen laatunsa. PDF on kiinteän taiton muoto: se tallentaa jokaisen merkin, viivan ja kuvan tarkan sijainnin, ja siksi se näyttää kaikkialla samalta mutta on hankala muokata.',
    'intro.lead.pdf-split': 'Jakaminen poimii nimeämäsi sivut PDF-tiedostosta ja tallentaa ne uudeksi asiakirjaksi jättäen alkuperäisen koskemattomaksi. PDF on kiinteän taiton muoto: se tallentaa jokaisen merkin, viivan ja kuvan tarkan sijainnin, ja siksi se näyttää kaikkialla samalta mutta on hankala muokata.',
    'intro.lead.pdf-compress': 'PDF-tiedoston pakkaaminen koodaa sen sisällä olevat kuvat uudelleen ja karsii tarpeetonta upotettua dataa, ja juuri siellä lähes koko suuren PDF:n koko oikeasti piilee. Teksti ja vektorigrafiikka jäävät teräviksi.',
    'intro.lead.pdf-compress-ai': 'Tämä työkalu analysoi PDF-tiedoston sisällön ennen pakkaamista, joten valokuvamaiset kuvat, tasainen grafiikka ja pelkkää tekstiä sisältävät sivut käsitellään kukin siten, että tilaa säästyy eniten ilman näkyvää heikkenemistä.',
    'intro.lead.pdf-rotate': 'Kierto muuttaa PDF-tiedoston suuntamerkinnän ja sivugeometrian niin, että sivut näkyvät ja tulostuvat oikein päin. Mitään ei hahmonneta uudelleen, joten laatua ei menetetä.',
    'intro.lead.pdf-protect': 'PDF-tiedoston suojaaminen salaa sen sisällön, jolloin sitä ei voi avata ilman asettamaasi salasanaa. Salaus kohdistuu itse tiedostoon eikä sen ympärillä olevaan kuoreen.',
    'intro.lead.pdf-unlock': 'Lukituksen avaaminen poistaa salasanan ja käyttörajoitukset PDF-tiedostosta, jonka salasanan jo tiedät, jotta sen voi taas avata, tulostaa ja siitä voi kopioida normaalisti.',
    'intro.lead.metadata': 'Jokainen tiedosto kantaa mukanaan tietoa itsestään, joka ei näy sitä avattaessa: kuvan mitat ja kameran asetukset, äänen keston ja bittinopeuden, videon koodekin ja kuvataajuuden, asiakirjan tekijän ja sivumäärän. Tämä työkalu lukee nuo metatiedot ja näyttää ne sinulle.',
    'intro.lead.ocr': 'Optinen merkintunnistus katsoo tekstin kuvaa — skannausta, valokuvaa, PDF-sivua ilman tekstitasoa — ja päättelee, mitä merkkejä siinä on, jolloin sanojen kuvasta tulee sanoja, joista tietokone voi hakea, joita se voi kopioida ja muokata.',
    'intro.lead.tts': 'Teksti puheeksi tuottaa puhuttua ääntä kirjoitetusta tekstistä neuroverkkoäänillä, joten saat luonnolliselta kuulostavan tallenteen vanhojen järjestelmien litteän robottiäänen sijaan.',
    'intro.lead.stt': 'Puhe tekstiksi kirjoittaa puhutun äänen sanoiksi. Se selviää luonnollisesta puheesta, aksenteista ja taustamelusta paljon paremmin kuin vanhat sanelu-ohjelmat ja palauttaa litteroinnin, jota voit muokata.',
    'intro.lead.subtitle': 'Tekstitysgeneraattori litteroi videon puheen ja kirjoittaa sen aikakoodien kanssa, jolloin syntyy standardinmukainen tekstitystiedosto eikä pelkkä litterointi.',

    'steps.convert.1.batch': 'Pudota {{fn}}-tiedostosi tämän sivun yläreunan latausalueelle tai napsauta sitä selataksesi laitettasi. Voit lisätä useita tiedostoja — tai kokonaisen kansion — ja muuntaa ne kaikki kerralla.',
    'steps.convert.1.single': 'Pudota {{fn}}-tiedostosi tämän sivun yläreunan latausalueelle tai napsauta sitä selataksesi laitettasi.',
    'steps.convert.2.direct': 'Valitse {{tn}} kohdemuodoksi ja napsauta Muunna.',
    'steps.convert.2.dropdown': 'Valitse {{tn}} kohdemuodoksi pudotusvalikosta ja napsauta Muunna.',
    'steps.convert.2.directMedia': 'Valitse {{tn}} kohdemuodoksi, säädä tarvittaessa laatua tai kokoa lisäasetuksissa ja napsauta Muunna.',
    'steps.convert.2.dropdownMedia': 'Valitse {{tn}} kohdemuodoksi pudotusvalikosta, säädä tarvittaessa laatua tai kokoa lisäasetuksissa ja napsauta Muunna.',
    'steps.convert.3': 'Lataa valmis {{tn}}-tiedostosi. Latauslinkki on voimassa 24 tuntia, minkä jälkeen molemmat tiedostot poistetaan automaattisesti.',
    'steps.hub.1.batch': 'Pudota {{category}}tiedostosi ({{inputs}} kelpaavat kaikki) tämän sivun yläreunan latausalueelle tai napsauta sitä selataksesi laitettasi. Voit lisätä useita tiedostoja — tai kokonaisen kansion — ja muuntaa ne kaikki kerralla.',
    'steps.hub.1.single': 'Pudota {{category}}tiedostosi ({{inputs}} kelpaavat kaikki) tämän sivun yläreunan latausalueelle tai napsauta sitä selataksesi laitettasi.',
    'steps.hub.2.direct': 'Valitse tarvitsemasi kohdemuoto ja napsauta Muunna.',
    'steps.hub.2.dropdown': 'Valitse pudotusvalikosta tarvitsemasi kohdemuoto ja napsauta Muunna.',
    'steps.hub.2.directMedia': 'Valitse tarvitsemasi kohdemuoto, säädä tarvittaessa laatua tai kokoa lisäasetuksissa ja napsauta Muunna.',
    'steps.hub.2.dropdownMedia': 'Valitse pudotusvalikosta tarvitsemasi kohdemuoto, säädä tarvittaessa laatua tai kokoa lisäasetuksissa ja napsauta Muunna.',
    'steps.hub.3': 'Lataa valmis tiedostosi. Latauslinkki on voimassa 24 tuntia, minkä jälkeen molemmat tiedostot poistetaan automaattisesti.',
    'steps.pdf-merge.1': 'Lisää jokainen PDF, jonka haluat yhdistää — pudota ne yhdessä latausalueelle tai napsauta valitaksesi ne yksi kerrallaan.',
    'steps.pdf-merge.2': 'Vedä tiedostot siihen järjestykseen, jossa haluat niiden näkyvän valmiissa asiakirjassa.',
    'steps.pdf-merge.3': 'Napsauta Yhdistä ja lataa yksi yhdistetty PDF.',
    'steps.pdf-split.1': 'Lataa se PDF, josta haluat poimia sivuja.',
    'steps.pdf-split.2': 'Kirjoita tarvitsemasi sivut tai välit sivuvälikenttään — esimerkiksi 1-3, 5, 7-10.',
    'steps.pdf-split.3': 'Napsauta Muunna ja lataa poimitut sivut.',
    'steps.pdf-compress.1': 'Pudota PDF-tiedostosi latausalueelle tai napsauta etsiäksesi sen.',
    'steps.pdf-compress.2': 'Napsauta Muunna — tiedosto analysoidaan ja sen kuvat ja upotettu data koodataan uudelleen pienempään kokoon.',
    'steps.pdf-compress.3': 'Lataa pakattu PDF ja tarkista sen vieressä näkyvä kokosäästö.',
    'steps.pdf-rotate.1': 'Lataa se PDF, jonka sivut ovat väärin päin.',
    'steps.pdf-rotate.2': 'Valitse, kuinka paljon niitä käännetään — 90°, 180° vai 270°.',
    'steps.pdf-rotate.3': 'Napsauta Muunna ja lataa korjattu PDF.',
    'steps.pdf-protect.1': 'Lataa se PDF, jonka haluat suojata.',
    'steps.pdf-protect.2': 'Kirjoita salasana, joka sen avaamiseen vaaditaan, ja säilytä siitä kopio turvallisessa paikassa.',
    'steps.pdf-protect.3': 'Napsauta Muunna ja lataa salattu PDF.',
    'steps.pdf-unlock.1': 'Lataa salasanalla suojattu PDF.',
    'steps.pdf-unlock.2': 'Kirjoita sen nykyinen salasana, jotta tiedosto voidaan purkaa salauksesta.',
    'steps.pdf-unlock.3': 'Napsauta Muunna ja lataa avattu PDF.',
    'steps.metadata.1': 'Pudota mikä tahansa tiedosto latausalueelle — kuva, video, äänitiedosto tai asiakirja.',
    'steps.metadata.2': 'Tiedosto tutkitaan eikä muunneta, joten siihen ei muuteta mitään.',
    'steps.metadata.3': 'Lue metatiedot suoraan sivulta: mitat, kesto, koodekki, kameran tiedot, sivumäärä ja muuta.',
    'steps.ocr.1': 'Lataa skannattu PDF tai valokuva tekstistä.',
    'steps.ocr.2': 'Valitse asiakirjan kieli ja se, haluatko haettavan PDF:n vai pelkkää tekstiä.',
    'steps.ocr.3': 'Napsauta Muunna ja lataa tulos, jossa tunnistettu teksti on nyt valittavissa ja haettavissa.',
    'steps.tts.1': 'Kirjoita tai liitä tekstisi kenttään — enintään 4096 merkkiä muunnosta kohden.',
    'steps.tts.2': 'Valitse ääni, puhenopeus ja kohdemuoto.',
    'steps.tts.3': 'Napsauta Muunna ja lataa valmis äänitiedosto.',
    'steps.stt.1': 'Lataa tallenteesi tai äänitä suoraan mikrofonista sivun painikkeella.',
    'steps.stt.2': 'Aseta halutessasi puhuttu kieli tarkkuuden parantamiseksi ja valitse TXT- tai DOCX-tuloste.',
    'steps.stt.3': 'Napsauta Muunna, lue litterointi sivulta ja lataa se sitten.',
    'steps.subtitle.1': 'Lataa video, jonka haluat tekstittää.',
    'steps.subtitle.2': 'Valitse SRT tai VTT ja aseta puhuttu kieli, jos tiedät sen.',
    'steps.subtitle.3': 'Napsauta Muunna ja lataa aikakoodattu tekstitystiedosto, valmiina pudotettavaksi soittimeesi tai editointiohjelmaasi.',
    'steps.compress.1': 'Pudota {{fn}}-kuvasi latausalueelle tai napsauta selataksesi. Voit lisätä kokonaisen kansion kerralla.',
    'steps.compress.1.gif': 'Pudota {{fn}}-animaatiosi latausalueelle tai napsauta selataksesi. Voit lisätä kokonaisen kansion kerralla.',
    'steps.compress.2': 'Napsauta Muunna — tiedosto koodataan uudelleen pienempään kokoon pysyen samassa muodossa.',
    'steps.compress.3': 'Lataa tulos ja vertaa sitä sivulla näkyvään alkuperäiseen kokoon.',
    'steps.soon.1': 'Valitse tarvitsemasi työkalu työkalusivulta — kaikki paitsi tämä toimii jo tänään.',
    'steps.soon.2': 'Lataa tiedostosi ja valitse kohdemuoto.',
    'steps.soon.3': 'Lataa tulos tai palaa tänne, kun asiakirjojen kääntäminen otetaan käyttöön.',

    'faq.cost.q.pair': 'Onko {{from}}-tiedoston muuntaminen {{to}}-muotoon ilmaista?',
    'faq.cost.q.tool': 'Onko {{label}} ilmainen?',
    'faq.cost.a.pair': "Jokainen muunnos {{from}}-muodosta {{to}}-muotoon käyttää yhden krediitin pienestä ennakkoon maksetusta paketista — tilausta ei ole, krediitit eivät koskaan vanhene, eikä epäonnistuneesta muunnoksesta veloiteta.",
    'faq.cost.a.tool': "Jokainen muunnos käyttää yhden krediitin pienestä ennakkoon maksetusta paketista — tilausta ei ole, krediitit eivät koskaan vanhene, eikä epäonnistuneesta muunnoksesta veloiteta.",
    'faq.cost.a.smartTts': "Älytoiminnot laskutetaan käytön mukaan eikä tiedostoittain — 1 krediitti jokaista 1000 tekstimerkkiä kohden, ylöspäin pyöristettynä. Tilausta ei ole: krediittejä ostetaan pieninä ennakkoon maksettuina paketteina, ne eivät koskaan vanhene, eikä epäonnistunut muunnos maksa koskaan mitään.",
    'faq.cost.a.smartAv': "Älytoiminnot laskutetaan käytön mukaan eikä tiedostoittain — 1 krediitti jokaista 5 minuutin ääni- tai videojaksoa kohden, ylöspäin pyöristettynä. Tilausta ei ole: krediittejä ostetaan pieninä ennakkoon maksettuina paketteina, ne eivät koskaan vanhene, eikä epäonnistunut muunnos maksa koskaan mitään.",
    'faq.cost.q.metadata': 'Onko Tiedoston tiedot -työkalu ilmainen?',
    'faq.cost.a.metadata': 'Kyllä. Tiedoston metatietojen lukeminen ei ole muunnos eikä siis kuluta krediittiä — voit tutkia niin monta tiedostoa kuin haluat. Krediittejä kuluu vain silloin, kun työkalu todella tuottaa sinulle uuden tiedoston.',
    'faq.cost.q.soon': 'Onko {{label}} jo saatavilla?',
    'faq.cost.a.soon': 'Ei vielä — tämä sivu on paikanvaraaja työkalun rakentamisen ajan, joten täällä ei ole tänään mitään ladattavaa. Hinnoittelu noudattaa samaa ennakkoon maksettujen krediittien mallia kuin muukin sivusto: ei tilausta, krediitit eivät vanhene eikä epäonnistuneesta muunnoksesta veloiteta.',

    'faq.time.q.pair': 'Kauanko muunnos {{from}}-muodosta {{to}}-muotoon kestää?',
    'faq.time.q.tool': 'Kauanko {{label}} kestää?',
    'faq.time.a': '{{speed}} Latausnopeus on yleensä rajoittava tekijä, joten suuri tiedosto hitaalla yhteydellä vie enemmän aikaa kuin itse muunnos.{{suffix}}',
    'faq.time.speed.image': 'Kuvat ovat nopeinta, mitä muunnamme — yksittäinen valokuva on tavallisesti valmis alle viidessä sekunnissa, ja kokonainen kansio vie suunnilleen yhtä kauan kuin lataus itse.',
    'faq.time.speed.document': 'Useimmat asiakirjat ovat valmiita muutamassa sekunnissa. Hyvin pitkät tiedostot — muutama sata sivua tai kuvia täynnä oleva skannaus — voivat viedä jopa minuutin.',
    'faq.time.speed.audio': 'Tavallinen kappale muuntuu muutamassa sekunnissa. Täysimittainen tallenne, kuten luento tai podcast-jakso, vie yleensä selvästi alle minuutin, ja siitä suurin osa on lataus.',
    'faq.time.speed.video': 'Video on hitain luokka, koska jokainen ruutu on koodattava uudelleen. Lyhyt leike vie sekunteja, kun taas pitkä teräväpiirtotiedosto voi viedä muutaman minuutin.',
    'faq.time.speed.archive': 'Arkistot muuntuvat sekunneissa, joskin suuri vie kauemmin, koska jokainen sisällä oleva tiedosto on purettava ja pakattava uudelleen.',
    'faq.time.speed.ebook': 'E-kirjat käyvät nopeasti — kokonainen romaani muuntuu tavallisesti muutamassa sekunnissa.',
    'faq.time.speed.subtitle': 'Litterointi etenee suunnilleen muutaman sekunnin vauhtia äänen minuuttia kohden, joten kymmenminuuttinen video saa tekstitykset yleensä selvästi alle minuutissa.',
    'faq.time.suffix.standard': ' Enintään 200 megatavun tiedostot kelpaavat.',
    'faq.time.suffix.smart': ' Älytoiminnot ottavat vastaan enintään 25 megatavun tiedostoja; tavalliset muunnokset enintään 200 megatavua.',
    'faq.time.q.metadata': 'Kauanko tiedoston metatietojen lukeminen kestää?',
    'faq.time.a.metadata': 'Sekunnin tai kaksi sen jälkeen, kun tiedosto on ladattu. Mitään ei muunneta eikä koodata uudelleen — otsakkeet jäsennetään ja tulos kirjoitetaan suoraan sivulle — joten odotus on käytännössä pelkkä lataus.',
    'faq.time.q.soon': 'Maksaako se lisää?',
    'faq.time.a.soon': 'Se käyttää samoja krediittejä kuin kaikki muukin sivustolla. Erillistä pakettia tai tilausta ei tarvitse ottaa, ja tililläsi jo olevat krediitit toimivat sen kanssa siitä hetkestä, kun se otetaan käyttöön.',

    'faq.safety.q.pair': 'Onko {{from}}-tiedostoni lataaminen turvallista?',
    'faq.safety.q.tool': 'Onko tiedostoni turvassa?',
    'faq.safety.a.pair': 'Tiedostot kulkevat salatun TLS-yhteyden yli eikä niitä käytetä mihinkään muuhun kuin pyytämääsi muunnokseen. Sekä alkuperäinen {{from}}-tiedostosi että palauttamamme {{to}}-tiedosto poistetaan automaattisesti 24 tunnin kuluessa — pysyvästi ja ilman varmuuskopioita — eikä sisältöä koskaan lueta, analysoida tai jaeta. Palvelua ylläpidetään Saksasta GDPR:n alaisena.',
    'faq.safety.a.tool': 'Tiedostot kulkevat salatun TLS-yhteyden yli eikä niitä käytetä mihinkään muuhun kuin pyytämääsi muunnokseen. Sekä alkuperäinen tiedostosi että palauttamamme tulos poistetaan automaattisesti 24 tunnin kuluessa — pysyvästi ja ilman varmuuskopioita — eikä sisältöä koskaan lueta, analysoida tai jaeta. Palvelua ylläpidetään Saksasta GDPR:n alaisena.',

    'quality.vectorRaster.q': 'Pysyykö {{fn}}-kuvani terävänä {{tn}}-muodossa?',
    'quality.vectorRaster.a': 'Siihen kokoon asti, johon sen viet, kyllä. {{fn}} tallentaa muotoja pikselien sijaan ja on siten rajattomasti skaalautuva, mutta {{tn}} on kiinteä pikseliruudukko ja sumenee, jos sitä myöhemmin suurennetaan tuon ruudukon yli. Aseta lisäasetuksissa se leveys ja korkeus, jonka oikeasti tarvitset, ennen muunnosta — vienti kaksin- tai kolminkertaisena näyttökokoon nähden on tavallinen kikka tiheäpikselisille näytöille. Säilytä alkuperäinen {{fn}}-tiedosto: se pysyy alkuperäiskappaleena, josta voit viedä uudelleen missä tahansa tarkkuudessa.',
    'quality.docToTxt.q': 'Menetänkö muotoilun, kun muunnan {{fn}}-tiedoston {{tn}}-muotoon?',
    'quality.docToTxt.a': 'Kyllä, ja tarkoituksella — {{tn}}-tiedosto sisältää merkkejä eikä mitään muuta. Kirjasimet, värit, kuvat, taulukot, palstat ja sivunvaihdot katoavat kaikki; takaisin saat asiakirjan luettavan tekstin lukujärjestyksessä. Juuri sitä haluat hakuun, skripteihin tai tekstin syöttämiseen toiseen ohjelmaan, ja juuri sitä et halua, jos toivoit säilyttäväsi ulkoasun. Huomaa, että {{fn}}-tiedosto, joka on todellisuudessa skannattu kuva, ei sisällä lainkaan tekstiä poimittavaksi — aja se sen sijaan OCR-työkalun läpi.',
    'quality.docToSheet.q': 'Kuinka tarkasti taulukot poimitaan {{fn}}-tiedostosta?',
    'quality.docToSheet.a': 'Siistit, viivoitetut ja tasapalstaiset taulukot — tiliotteet, laskut, viedyt raportit — tulevat luotettavasti läpi, ja jokainen arvo päätyy omaan soluunsa, jotta voit laskea ja lajitella. Taulukot ilman näkyviä reunoja, useaa riviä ulottuvat solut tai sivunvaihdon halkaisemat luvut ovat ne tapaukset, jotka kannattaa tarkistaa silmällä jälkeenpäin. {{fn}} tallentaa sijainnit eikä taulukkorakennetta, joten muunnoksen on pääteltävä, mihin yksi palsta päättyy ja seuraava alkaa.',
    'quality.docToReflow.q': 'Säilyykö taitto muunnoksessa {{fn}}-muodosta {{tn}}-muotoon?',
    'quality.docToReflow.a': 'Ei aivan, ja juuri siinä on pointti. {{fn}} naulaa tekstin kiinteisiin sivukoordinaatteihin; {{tn}} rivittää sen uudelleen lukijan näytön ja kirjasinkoon mukaan, joten kiinteät sivunumerot, ylä- ja alatunnisteet sekä monipalstaiset taitot tulkitaan uudelleen eikä toisteta. Leipäteksti, otsikot, kappalejärjestys ja kuvat tulevat hyvin läpi. Enimmäkseen proosaa sisältävät asiakirjat muuntuvat loistavasti; raskaasti muotoillut sivut, lomakkeet ja monimutkaiset taulukot kannattaa katsoa läpi jälkeenpäin.',
    'quality.docToFixed.q': 'Säilyykö muotoiluni {{tn}}-tiedostossa?',
    'quality.docToFixed.a': 'Kyllä — tämä suunta on turvallinen. {{tn}} tallentaa lopullisesti hahmonnetun sivun, joten kirjasimet, välistykset, taulukot, kuvat ja sivunvaihdot jäädytetään täsmälleen sellaisiksi kuin ne taitettiin ja ne näyttävät samalta jokaisella laitteella ja tulostimella. Se on myös vastine: tulosta ei enää voi vapaasti muokata, ja juuri se on yleensä syy siihen, että asiakirja muunnetaan {{tn}}-muotoon ennen lähettämistä.',
    'quality.docToEditable.q': 'Kuinka tarkka muunnos {{fn}}-muodosta {{tn}}-muotoon on?',
    'quality.docToEditable.a': 'Teksti, otsikot, luettelot, kuvat ja yksinkertaiset taulukot tulevat luotettavasti läpi ja pysyvät täysin muokattavina. Koska {{fn}} tallentaa sijainnit eikä rakennetta, muunnoksen on rakennettava tuo rakenne uudelleen, joten raskaasti muotoillut sivut — useat palstat, kuvien ympäri kiertävä teksti, monimutkaiset sisäkkäiset taulukot — voivat vaatia kevyttä siistimistä jälkeenpäin. Jos PDF on skannaus ilman minkäänlaista tekstitasoa, käytä sen sijaan OCR-työkalua: se tunnistaa kuvassa olevat merkit sen sijaan, että etsisi tekstiä, jota siellä ei ole.',
    'quality.docGeneric.q': 'Menetänkö jotain, kun muunnan {{fn}}-tiedoston {{tn}}-muotoon?',
    'quality.docGeneric.a': 'Sanat, otsikot, luettelot ja kuvat siirtyvät ehjinä. {{tn}} tuntee eri muotoilusanaston kuin {{fn}}, joten hyvin erikoinen muotoilu voi matkalla yksinkertaistua, mutta itse sisältö säilyy.',
    'quality.archive.q': 'Muuttuvatko {{fn}}-arkistoni sisällä olevat tiedostot?',
    'quality.archive.a': 'Eivät. Arkistomuodot ovat häviöttömiä säiliöitä: {{fn}} puretaan ja täsmälleen samat tiedostot pakataan uudelleen {{tn}}-muotoon, tavu tavulta. Vain pakkausmenetelmä ja säiliö muuttuvat. Se, mikä muuttuu, on itse arkiston koko — {{clause}}.',
    'quality.archive.clause.to7z': '7Z tuottaa LZMA-pakkauksen ansiosta yleensä pienemmän arkiston kuin ZIP',
    'quality.archive.clause.toZip': 'ZIP jää yleensä hieman suuremmaksi kuin 7Z tai RAR, ja se on hinta siitä, että sen saa auki kaikkialla ilman lisäohjelmia',
    'quality.archive.clause.other': 'uusi muoto pakkaa eri tavalla, joten tiedostokoko voi liikkua kumpaan suuntaan tahansa',
    'quality.imageToDoc.q': 'Menettävätkö kuvani laatua {{tn}}-tiedoston sisällä?',
    'quality.imageToDoc.a': 'Eivät. Jokainen {{fn}}-kuva sijoitetaan {{tn}}-tiedostoon sellaisenaan, yksi sivua kohden, eikä sitä pakata uudelleen, joten se mitä asiakirjassa näet on se, mikä tuli kamerasta. {{tn}}-tiedostosta tulee suunnilleen kuvien yhteenlasketun koon kokoinen, mikä kannattaa tietää ennen sen lähettämistä sähköpostilla — aja tulos Pakkaa PDF -työkalun läpi, jos sen pitää olla pienempi.',
    'quality.toGif.q': 'Miksi GIF-kuvani näyttää huonommalta kuin alkuperäinen {{fn}}?',
    'quality.toGif.a': 'Koska GIF on rajattu 256 väriin ruutua kohden. Video tai valokuva sisältää niitä miljoonia, joten kooderin on valittava paletti ja arvioitava kaikki muu likimääräisesti, mikä näkyy juovina liukuväreissä ja taivaissa. GIF ei myöskään kanna lainkaan ääniraitaa. Molemmat kuuluvat muotoon eivätkä muunnokseen — pidä leike lyhyenä, ja jos värien menetys painaa enemmän kuin upotettu automaattinen toisto, MP4 näyttää huomattavasti paremmalta pienemmässä koossa.',
    'quality.lossyToLossless.q': 'Paraneeko laatu, kun {{fn}} muunnetaan {{tn}}-muotoon?',
    'quality.lossyToLossless.a': 'Ei — ja tämä on ylivoimaisesti yleisin väärinkäsitys tästä muunnoksesta. {{fn}} on häviöllinen: ne yksityiskohdat, jotka sen kooderi hylkäsi, ovat pysyvästi poissa eikä mikään voi palauttaa niitä. {{tn}} antaa sinulle häviöttömän säiliön sille, mitä on jäljellä, joten tiedosto lakkaa heikkenemästä jokaisen seuraavan tallennuksen tai muokkauksen myötä. Se on todella hyödyllistä, kun olet aikeissa {{clause}}, mutta se ei palauta laatua, joka on jo menetetty.',
    'quality.lossyToLossless.edit.audio': 'muokata, masteroida tai käsitellä ääntä',
    'quality.lossyToLossless.edit.image': 'muokata, retusoida tai koostaa kuvaa',
    'quality.losslessToLossy.q': 'Menetänkö laatua, kun muunnan {{fn}}-tiedoston {{tn}}-muotoon?',
    'quality.losslessToLossy.a.audio': 'Jonkin verran, ja tarkoituksella — juuri niin tiedosto pienenee. {{tn}} on häviöllinen, joten kooderi hylkää sen tiedon, jonka se arvioi vähiten huomattavaksi. Järkevillä asetuksilla eroa on hyvin vaikea kuulla, ja voit nostaa bittinopeutta lisäasetuksissa, jos vaihdat mieluummin kokoa uskollisuuteen. Säilytä alkuperäinen {{fn}}-tiedostosi: se pysyy alkuperäiskappaleena, ja {{tn}}-tiedoston uudelleen koodaaminen myöhemmin kasvattaisi menetystä.',
    'quality.losslessToLossy.a.visual': 'Jonkin verran, ja tarkoituksella — juuri niin tiedosto pienenee. {{tn}} on häviöllinen, joten kooderi hylkää sen tiedon, jonka se arvioi vähiten huomattavaksi. Järkevillä asetuksilla eroa on hyvin vaikea nähdä, ja voit nostaa laatuarvoa lisäasetuksissa, jos vaihdat mieluummin kokoa uskollisuuteen. Säilytä alkuperäinen {{fn}}-tiedostosi: se pysyy alkuperäiskappaleena, ja {{tn}}-tiedoston uudelleen koodaaminen myöhemmin kasvattaisi menetystä.',
    'quality.lossyToLossy.q': 'Menetänkö laatua, kun muunnan {{fn}}-tiedoston {{tn}}-muotoon?',
    'quality.lossyToLossy.a.audio': 'Hieman. Molemmat muodot ovat häviöllisiä, joten {{fn}} puretaan ja koodataan sitten uudelleen {{tn}}-muotoon, ja jokainen häviöllisen koodauksen sukupolvi menettää pienen määrän yksityiskohtia. Tavallisilla asetuksilla useimmat eivät huomaa sitä kuunnellessaan, ja voit nostaa bittinopeutta lisäasetuksissa. Vältettävää on saman tiedoston muuntaminen edestakaisin toistuvasti — juuri se tekee menetyksestä kuultavan.',
    'quality.lossyToLossy.a.visual': 'Hieman. Molemmat muodot ovat häviöllisiä, joten {{fn}} puretaan ja koodataan sitten uudelleen {{tn}}-muotoon, ja jokainen häviöllisen koodauksen sukupolvi menettää pienen määrän yksityiskohtia. Tavallisilla asetuksilla useimmat eivät huomaa sitä, ja voit nostaa laatua lisäasetuksissa. Vältettävää on saman tiedoston muuntaminen edestakaisin toistuvasti — juuri se tekee menetyksestä näkyvän.',
    'quality.losslessToLossless.q': 'Menetänkö laatua, kun muunnan {{fn}}-tiedoston {{tn}}-muotoon?',
    'quality.losslessToLossless.a.plain': 'Et. Sekä {{fn}} että {{tn}} ovat häviöttömiä, joten {{unit}} säilyy täsmälleen ja tulos on identtinen alkuperäisen kanssa. Vain tiedostokoko muuttuu. Voit muuntaa myöhemmin takaisin ilman minkäänlaista heikkenemistä.',
    'quality.losslessToLossless.a.bulky': 'Et. Sekä {{fn}} että {{tn}} ovat häviöttömiä, joten {{unit}} säilyy täsmälleen ja tulos on identtinen alkuperäisen kanssa. Vain tiedostokoko muuttuu, yleensä rajusti alaspäin, koska {{fn}} tallentaa datansa käytännössä pakkaamattomana. Voit muuntaa myöhemmin takaisin ilman minkäänlaista heikkenemistä.',
    'quality.fallback.q': 'Menetänkö laatua, kun muunnan {{fn}}-tiedoston {{tn}}-muotoon?',
    'quality.fallback.a': 'Tavallisilla tiedostoilla tulos vastaa alkuperäistä sekä visuaalisesti että toiminnallisesti. Siellä missä muodot tukevat eri ominaisuuksia, muunnos säilyttää kaiken, mitä {{tn}} kykenee esittämään. Lisäasetuksissa voit nostaa laatua, jos oletusarvoinen kompromissi ei ole sinun mieleesi.',

    'relation.uncompressed.q': 'Miksi {{tn}}-tiedosto on niin paljon suurempi kuin {{fn}}-tiedosto?',
    'relation.uncompressed.a': 'Koska {{tn}} on pakkaamaton. {{fn}} kutistaa ääntä hylkäämällä dataa ja koodaamalla jäljelle jäävän tehokkaasti; {{tn}} kirjoittaa jokaisen näytteen täydessä koossa, mikä tekee noin 10 megatavua minuuttia kohden CD-laatuista stereoa. Kymmenkertainen kasvu on normaali ja odotettu — se on hinta tiedostosta, jota editointiohjelmat voivat käsitellä purkamatta ensin mitään. Jos haluat häviötöntä ääntä noin puolella koolla, muunna sen sijaan FLAC-muotoon.',
    'relation.extractAudio.q': 'Säilyykö tässä video vai vain ääni?',
    'relation.extractAudio.a': 'Vain ääni. Ääniraita poimitaan {{fn}}-tiedostosta ja tallennetaan {{tn}}-muotoon; videoraita hylätään, ja siksi tulos on murto-osa alkuperäisestä koosta. Itse ääntä ei äänitetä uudelleen, joten se säilyttää sen laadun, joka sillä oli {{fn}}-tiedoston sisällä — matalan bittinopeuden videosta ei saa korkean bittinopeuden ääntä.',
    'relation.videoContainer.q': 'Toistuuko {{tn}}-tiedostoni puhelimissa, televisioissa ja sosiaalisessa mediassa?',
    'relation.videoContainer.a.mp4': 'Juuri sitä varten tämä muunnos on. MP4 ja H.264-video on lähinnä yleismaailmallista videomuotoa: iPhonet, Android-puhelimet, älytelevisiot, jokainen selain, Instagram, YouTube, TikTok ja jokainen valtavirran editointiohjelma ottavat sen vastaan ilman lisäkoodekkeja. {{fn}} oli se muoto, joka tuotti sinulle harmia; MP4 on se, joka ei tuota.',
    'relation.videoContainer.a.other': '{{tn}} on erikoistuneempi kuin MP4. {{note}} Jos tavoitteesi on yksinkertaisesti ”toistuu kaikkialla”, MP4 on turvallisempi valinta — ota {{tn}} silloin, kun tietty ohjelma tai laite on sitä pyytänyt.',
    'relation.alphaLost.q': 'Mitä läpinäkyvyydelle tapahtuu, kun {{fn}} muunnetaan {{tn}}-muotoon?',
    'relation.alphaLost.a': '{{tn}}-muodossa ei ole alfakanavaa, joten läpinäkyviä alueita ei voi siirtää — ne täytetään muunnoksen aikana yhtenäisellä taustalla (oletuksena valkoisella). Jos läpinäkyvä tausta tekee suunnittelussasi todellista työtä, muunna sen sijaan PNG- tai WebP-muotoon, jotka molemmat säilyttävät sen. Jos kuva on valokuva vailla mitään läpinäkyvyyttä, tällä ei ole lainkaan merkitystä.',
    'relation.alphaGained.q': 'Tuleeko taustasta läpinäkyvä, kun {{fn}} muunnetaan {{tn}}-muotoon?',
    'relation.alphaGained.a': 'Ei — ja tähän moni lankeaa. {{tn}} tukee läpinäkyvyyttä, mutta {{fn}}-tiedostossa ei ole mitään läpinäkyvyystietoa siirrettäväksi, joten tausta pysyy täsmälleen ennallaan. Muunnos antaa sinulle tiedoston, joka pystyy kantamaan läpinäkyvyyttä sen jälkeen, kun olet irrottanut taustan kuvankäsittelyohjelmassa, sekä häviöttömät pikselit, jotka eivät heikkene työskennellessäsi.',
    'relation.reflow.q': 'Toimiiko {{tn}} lukulaitteellani?',
    'relation.reflow.a.epub': 'EPUB-muotoa lukevat Apple Books, Kobo, Google Play Kirjat, Calibre ja käytännössä jokainen lukulaite paitsi Kindle, joka haluaa MOBI- tai AZW3-muotoa (Kindle ottaa nykyään vastaan myös EPUB-tiedostoja sähköpostitse). Koska teksti rivittyy uudelleen, voit muuttaa kirjasinkokoa laitteessa joutumatta vierittämään sivusuunnassa — ja juuri se on koko syy muuntaa {{fn}} alun perinkään.',
    'relation.reflow.a.kindle': '{{tn}}-muotoa lukevat ne Kindle-laitteet ja -sovellukset, joita varten se suunniteltiin. Koska teksti rivittyy uudelleen, voit muuttaa kirjasinkokoa laitteessa joutumatta vierittämään sivusuunnassa — ja juuri se on koko syy muuntaa {{fn}} alun perinkään.',

    'compatibility.q': 'Millä {{tn}}-tiedoston voi avata jälkeenpäin?',
    'compatibility.a': '{{note}} Itse muunnosta varten ei tarvitse asentaa mitään — se ajetaan palvelimillamme, ja valmis {{tn}}-tiedosto palaa selaimeesi valmiina avattavaksi, muokattavaksi tai edelleen lähetettäväksi. Alkuperäistä {{fn}}-tiedostoasi ei koskaan muuteta; palautamme aina vain uuden tiedoston.',
    'compatibility.noteFallback': '{{tn}} on laajasti tuettu.',

    'shapeFaq.pdf-merge.q1': 'Heikentääkö yhdistäminen PDF-tiedostojeni laatua?',
    'shapeFaq.pdf-merge.a1': 'Ei. Sivut kopioidaan uuteen asiakirjaan täsmälleen sellaisinaan eikä niitä hahmonneta uudelleen, joten teksti pysyy valittavana ja kuvat säilyttävät alkuperäisen tarkkuutensa. Yhdistetty tiedosto on suunnilleen alkuperäisten yhteenlasketun koon kokoinen — aja se jälkeenpäin Pakkaa PDF -työkalun läpi, jos sillä on merkitystä.',
    'shapeFaq.pdf-merge.q2': 'Kuinka monta PDF-tiedostoa voin yhdistää kerralla, ja onko järjestyksellä väliä?',
    'shapeFaq.pdf-merge.a2': 'Voit lisätä kerralla niin monta tiedostoa kuin tarvitset, ja järjestyksellä on ehdottomasti väliä: valmis asiakirja noudattaa luettelossa näkyvää järjestystä, jota voit vetämällä muuttaa ennen yhdistämistä. Aseta järjestys ensin ja yhdistä sitten — se käy nopeammin kuin korjaaminen jälkeenpäin.',
    'shapeFaq.pdf-split.q1': 'Miten valitsen, mitkä sivut poimitaan?',
    'shapeFaq.pdf-split.a1': 'Kirjoita ne sivuvälikenttään pilkkuja ja yhdysmerkkejä käyttäen: ”1-3, 5, 7-10” antaa sivut yhdestä kolmeen, sivun viisi ja sivut seitsemästä kymmeneen yhtenä tulosasiakirjana. Numerot viittaavat PDF-tiedoston omiin sivuihin ykkösestä laskettuna, mikä ei aina ole sama kuin sivulle painettu numero.',
    'shapeFaq.pdf-split.q2': 'Muuttaako jakaminen alkuperäistä PDF-tiedostoa?',
    'shapeFaq.pdf-split.a2': 'Ei. Lataamaasi tiedostoa ei koskaan muuteta — poimitut sivut kirjoitetaan uuteen asiakirjaan ja alkuperäinen jää koskemattomaksi, kunnes se poistetaan palvelimiltamme 24 tunnin kuluessa yhdessä tuloksen kanssa.',
    'shapeFaq.pdf-compress.q1': 'Kuinka paljon PDF-tiedostoni pienenee?',
    'shapeFaq.pdf-compress.a1': 'Se riippuu täysin siitä, mitä sen sisällä on. Skannauksia tai valokuvia täynnä olevat PDF-tiedostot kutistuvat usein 50–90 prosenttia, koska juuri siellä lähes koko koko on. Pelkkää tekstiä sisältävä PDF on jo tiivis eikä ehkä muutu juuri lainkaan. Teksti ja vektorigrafiikka pysyvät terävinä kummassakin tapauksessa — säästö syntyy kuvien uudelleen koodaamisesta ja tarpeettoman upotetun datan poistamisesta.',
    'shapeFaq.pdf-compress.q2': 'Pysyykö teksti edelleen valittavana ja haettavana?',
    'shapeFaq.pdf-compress.a2': 'Kyllä. Pakkaus kohdistuu upotettuihin kuviin ja tarpeettomaan sisäiseen dataan; tekstitaso, kirjasimet, linkit ja kirjanmerkit jäävät ehjiksi, joten voit yhä hakea, valita ja kopioida pakatusta tiedostosta täsmälleen kuten ennenkin.',
    'shapeFaq.pdf-compress-ai.q1': 'Miten tämä eroaa tavallisesta PDF-pakkauksesta?',
    'shapeFaq.pdf-compress-ai.a1': 'Tavallinen pakkaus soveltaa yhtä asetusta koko tiedostoon. Tämä työkalu katsoo ensin, mitä kukin sivu todella sisältää, jolloin valokuvamaiset kuvat, tasaiset kaaviot ja pelkkää tekstiä sisältävät sivut käsitellään kukin siten, että tilaa säästyy eniten ilman näkyvää heikkenemistä. Sekalaisissa asiakirjoissa se tarkoittaa yleensä pienempää tiedostoa samalla koetulla laadulla.',
    'shapeFaq.pdf-compress-ai.q2': 'Pysyykö teksti edelleen valittavana ja haettavana?',
    'shapeFaq.pdf-compress-ai.a2': 'Kyllä. Tekstitaso, kirjasimet, linkit ja kirjanmerkit säilyvät — vain upotetut kuvat ja tarpeeton sisäinen data koodataan uudelleen, joten pakattu PDF pysyy täysin haettavana ja kopioitavana.',
    'shapeFaq.pdf-rotate.q1': 'Menetetäänkö PDF-tiedoston kääntämisessä laatua?',
    'shapeFaq.pdf-rotate.a1': 'Ei lainkaan. Kierto muuttaa tiedostoon kirjattua sivugeometriaa sen sijaan, että mitään hahmonnettaisiin uudelleen, joten teksti pysyy vektoriterävänä, kuvat jäävät koskemattomiksi ja tiedostokoko tuskin liikahtaa. Voit kääntää uudelleen myöhemmin ilman minkäänlaista kasautuvaa vahinkoa.',
    'shapeFaq.pdf-rotate.q2': 'Voinko kääntää vain osan sivuista?',
    'shapeFaq.pdf-rotate.a2': 'Valitsemasi kierto — 90°, 180° tai 270° — kohdistetaan asiakirjaan. Jos eri sivut ovat väärin eri suuntiin, tavallinen tapa on jakaa PDF, kääntää kukin osa tarvitsemallaan kulmalla ja yhdistää tulokset takaisin Yhdistä PDF -työkalulla.',
    'shapeFaq.pdf-protect.q1': 'Mitä tapahtuu, jos unohdan salasanan?',
    'shapeFaq.pdf-protect.a1': 'Tiedostoa ei saa auki. Salaus kohdistuu itse PDF-tiedostoon, joten palautuslinkkiä ja takaovea ei ole — ei sinulle eikä meille. Säilytä salasana turvallisessa paikassa ennen kuin lähetät asiakirjan eteenpäin, ja lähetä se eri kanavaa pitkin kuin tiedosto.',
    'shapeFaq.pdf-protect.q2': 'Kuinka vahva suojaus on?',
    'shapeFaq.pdf-protect.a2': 'PDF salataan muotoon sisäänrakennetulla alan standardimenetelmällä, joten mikään standardia noudattava lukija ei voi lukea sen sisältöä ilman salasanaa. Käytännön heikko kohta ei ole koskaan algoritmi vaan itse salasana — lyhyt tai ilmeinen arvataan nopeasti, joten käytä pitkää kaikkeen todella luottamukselliseen.',
    'shapeFaq.pdf-unlock.q1': 'Voiko tämä poistaa salasanan, jota en tiedä?',
    'shapeFaq.pdf-unlock.a1': 'Ei. Sinun on annettava nykyinen salasana; työkalu purkaa tiedoston salauksen sillä eikä murra salausta. Se on tarkoitettu asiakirjoihin, jotka omistat tai jotka sinulla on oikeus avata — esimerkiksi oman pankkisi tiliotteeseen — joissa rajoitus vain on tiellä.',
    'shapeFaq.pdf-unlock.q2': 'Mitä voin tehdä tiedostolla jälkeenpäin?',
    'shapeFaq.pdf-unlock.a2': 'Kaiken sen, mitä suojaus esti: avata sen ilman kyselyä, tulostaa sen, kopioida siitä tekstiä ja muokata sitä muissa ohjelmissa. Itse sivujen sisältö on muuttumaton — vain salauskerros ja sen käyttörajoitukset poistetaan.',
    'shapeFaq.metadata.q1': 'Muuttaako tämä tiedostoani millään tavalla?',
    'shapeFaq.metadata.a1': 'Ei. Tiedosto luetaan eikä muunneta — mitään ei kirjoiteta takaisin eikä mitään uutta synny paitsi näytöllä näkyvät tiedot. Se on turvallisin täällä oleva työkalu kohdistaa tiedostoon, josta olet epävarma.',
    'shapeFaq.metadata.q2': 'Millaisia tietoja näen?',
    'shapeFaq.metadata.a2': 'Se riippuu tiedostosta. Kuvat näyttävät mitat, värisyvyyden ja EXIF-tiedot kuten kameran mallin, objektiivin, valotuksen ja, jos kamera tallensi ne, GPS-koordinaatit. Ääni näyttää keston, bittinopeuden, näytteenottotaajuuden ja kanavien määrän. Video lisää koodekin, tarkkuuden ja kuvataajuuden. Asiakirjat näyttävät sivumäärän, tekijän, tuottajan ja luontipäivän.',
    'shapeFaq.ocr.q1': 'Kuinka tarkka tekstintunnistus on?',
    'shapeFaq.ocr.a1': 'Siisti, suora skannaus painetusta tekstistä kohtuullisella tarkkuudella tunnistuu erittäin tarkasti. Tarkkuus laskee vinojen tai epätarkkojen sivujen, vähäkontrastisten valokuvien, epätavallisten kirjasinten ja käsialan kohdalla. Oikean kielen valinnalla on merkitystä, koska tunnistus käyttää sitä monitulkintaisten merkkien ratkaisemiseen.',
    'shapeFaq.ocr.q2': 'Mikä ero on haettavalla PDF:llä ja pelkällä tekstitulosteella?',
    'shapeFaq.ocr.a2': 'Haettava PDF säilyttää alkuperäisen sivukuvan täsmälleen sellaisena kuin se näyttää ja lisää sen alle näkymättömän tekstitason, joten asiakirja näyttää muuttumattomalta mutta siitä voi nyt hakea ja kopioida — juuri sitä haluat arkistointiin. Pelkkä teksti heittää taiton pois ja antaa sinulle vain sanat, ja juuri sitä haluat muokkaukseen, skripteihin tai toiseen ohjelmaan syöttämiseen.',
    'shapeFaq.tts.q1': 'Kuinka luonnollisilta äänet kuulostavat?',
    'shapeFaq.tts.a1': 'Nämä ovat neuroverkkoääniä eivätkä vanhaa yhteen liimattua puhesynteesiä, joten ne kantavat lausetason intonaatiota ja luonnollisia taukoja sen sijaan, että lukisivat sana sanalta. Valittavana on kuusi ääntä, neutraalista lämpimään ja arvovaltaiseen, ja puhenopeutta voi säätää. Välimerkeillä on enemmän väliä kuin luullaan: pilkut ja pisteet muotoilevat fraseerausta, joten hyvin välimerkitetty teksti luetaan huomattavasti paremmin.',
    'shapeFaq.tts.q2': 'Kuinka paljon tekstiä voin muuntaa kerralla?',
    'shapeFaq.tts.a2': 'Enintään 4096 merkkiä muunnosta kohden — karkeasti 600–700 sanaa eli noin viisi minuuttia puhetta. Pidemmät tekstit kannattaa katkaista luontevasta kohdasta kuten luvun tai osion otsikosta ja muuntaa kukin osa erikseen; ääni- ja nopeusasetukset pysyvät ajokertojen välillä samoina, joten palat liittyvät siististi yhteen.',
    'shapeFaq.stt.q1': 'Kuinka tarkka litterointi on?',
    'shapeFaq.stt.a1': 'Selkeä puhe kohtuullisen hiljaisessa ympäristössä litteroituu erittäin tarkasti, myös monenlaisilla aksenteilla. Tarkkuus laskee voimakkaassa taustamelussa, kun useampi puhuu päällekkäin, tai hyvin erikoistuneen ammattisanaston ja erisnimien kohdalla. Puhutun kielen asettaminen sen sijaan, että se tunnistettaisiin automaattisesti, auttaa huomattavasti.',
    'shapeFaq.stt.q2': 'Voinko äänittää suoraan mikrofonista?',
    'shapeFaq.stt.a2': 'Kyllä — tämän sivun nauhuri kaappaa äänen suoraan selaimessa, mikä on usein nopeampaa kuin etsiä ensin äänityssovellus. Selaimesi kysyy mikrofonilupaa ensimmäisellä kerralla. Voit myös ladata olemassa olevan tiedoston, ja litterointi ilmestyy sivulle, jotta voit lukea sen ennen kuin lataat sen TXT- tai DOCX-muodossa.',
    'shapeFaq.subtitle.q1': 'Kuinka tarkkoja luodut tekstitykset ovat?',
    'shapeFaq.subtitle.a1': 'Selkeä puhe litteroituu erittäin tarkasti, myös aksenteilla. Taustamusiikki, päällekkäin puhuminen ja erikoistunut sanasto ovat niitä kohtia, joihin virheitä livahtaa, ja puhutun kielen asettaminen automaattisen tunnistuksen sijaan auttaa. Tuloste on tavallisen tekstin tekstitystiedosto, joten yksittäisen sanan korjaaminen vie sekunteja missä tahansa tekstieditorissa.',
    'shapeFaq.subtitle.q2': 'Kannattaako valita SRT vai VTT?',
    'shapeFaq.subtitle.a2': 'SRT on turvallisempi oletusvalinta: YouTube, Vimeo, Premiere, Final Cut, VLC ja käytännössä jokainen soitin ottavat sen vastaan. Valitse VTT, jos tekstitykset menevät verkkosivuston HTML5-videosoittimeen, sillä WebVTT on se muoto, jota selaimen oma tekstitysraita odottaa, ja se tukee tyylittelyä ja sijoittelua, joita SRT ei osaa ilmaista.',
    'shapeFaq.soon.q1': 'Milloin tämä tulee saataville?',
    'shapeFaq.soon.a1': 'Sitä kehitetään aktiivisesti. Työkalu ilmestyy tänne ja alkaa ottaa tiedostoja vastaan heti kun se on valmis — sinun päässäsi ei tarvitse asentaa eikä ottaa mitään käyttöön.',
    'shapeFaq.soon.q2': 'Mitä voin käyttää sillä välin?',
    'shapeFaq.soon.a2': 'Muu muunnin on täysin käytettävissä: asiakirjat, kuvat, ääni, video, arkistot, GIF-kuvat ja PDF-työkalupakki toimivat kaikki jo tänään, samoin älytoiminnot OCR:ää, litterointia ja tekstityksiä varten.',
    'shapeFaq.compress.q1': 'Onko pakattu tiedosto edelleen {{fn}}?',
    'shapeFaq.compress.a1': 'On — muoto ei muutu, vain koko. Lataamasi tiedosto on tavallinen {{fn}}, joka avautuu kaikkialla, missä alkuperäinenkin.{{alpha}} Se, kuinka paljon säästät, riippuu lähdemateriaalista: {{source}}.',
    'shapeFaq.compress.alpha': ' Läpinäkyvyys ja animaatio säilyvät.',
    'shapeFaq.compress.source.png': 'kuvakaappaukset ja tasainen käyttöliittymägrafiikka pakkautuvat dramaattisesti, kun taas PNG-muodossa tallennetuista valokuvista irtoaa vähemmän',
    'shapeFaq.compress.source.gif': 'pitkät animaatiot ja levoton materiaali pakkautuvat eniten, koska poistettavaa toistoa on enemmän',
    'shapeFaq.compress.source.other': 'valokuvat pakkautuvat hyvin, kun taas jo voimakkaasti pakatuista kuvista on vähemmän irrotettavaa',
    'shapeFaq.compress.q2': 'Kuinka paljon tiedosto pienenee?',
    'shapeFaq.compress.a2': 'Tyypillisesti jonnekin kolmasosan ja kymmenesosan välille alkuperäisestä, riippuen täysin siitä, mitä tiedosto sisältää ja miten se alun perin tallennettiin. Kun muunnos on valmis, sivu näyttää koon ennen ja jälkeen rinnakkain, joten näet todellisen säästön arvailun sijaan.',
    'shapeFaq.hub.q1': 'Minkä muotojen välillä voin muuntaa?',
    'shapeFaq.hub.a1': 'Syöte: {{inputs}}. Tuloste: {{outputs}}. Mikä tahansa syöte voi mennä mihin tahansa tulosteeseen, joten sinun ei tarvitse etsiä erillistä sivua jokaiselle yhdistelmälle — valitse tiedosto, valitse kohdemuoto, muunna.',
    'shapeFaq.hub.q2': 'Menetänkö laatua?',
    'shapeFaq.hub.a2': 'Se riippuu parista. Häviöttömään muotoon siirtyminen säilyttää kaiken mutta tuottaa suuremman tiedoston; pakattuun muotoon siirtyminen hylkää tarkoituksella dataa kokoa vastaan, ja lisäasetuksissa päätät, mihin kohtaan tuota vaihtokauppaa asetut. Kahden pakatun muodon välinen muunnos menettää joka kerta hieman yksityiskohtia, joten alkuperäinen kannattaa säilyttää alkuperäiskappaleena.',
    'shapeFaq.hub-extract.q1': 'Säilyykö video myös?',
    'shapeFaq.hub-extract.a1': 'Ei — vain ääni. Ääniraita nostetaan ulos videosta ja tallennetaan erikseen, ja siksi tulos on murto-osa alkuperäisestä tiedostokoosta. Ääntä ei äänitetä uudelleen, joten se säilyttää sen laadun, joka sillä jo videon sisällä oli; matalan bittinopeuden leikkeestä ei saa korkean bittinopeuden ääntä.',
    'shapeFaq.hub-extract.q2': 'Minkä kohdemuodon kannattaa valita?',
    'shapeFaq.hub-extract.a2': 'MP3 parhaan yhteensopivuuden vuoksi — se toistuu jokaisessa puhelimessa, autostereossa ja soittimessa. AAC tai M4A, jos kohteena on Applen laite tai nykyaikainen sovellus, sillä ne kuulostavat hieman paremmilta samalla bittinopeudella. WAV tai FLAC vain, jos aiot muokata ääntä, sillä molemmat ovat häviöttömiä ja vastaavasti kookkaita.',
    'shapeFaq.hub-gif.q1': 'Miksi GIF näyttää huonommalta kuin alkuperäinen?',
    'shapeFaq.hub-gif.a1': 'Koska GIF sallii vain 256 väriä ruutua kohden, kun taas video ja valokuvat sisältävät niitä miljoonia. Kooderi valitsee paletin ja arvioi loput likimääräisesti, mikä näkyy juovina liukuväreissä ja taivaissa. GIF ei myöskään kanna lainkaan ääntä. Molemmat rajat kuuluvat muotoon eivätkä muunnokseen.',
    'shapeFaq.hub-gif.q2': 'Miksi GIF-tiedostoni on niin suuri?',
    'shapeFaq.hub-gif.a2': 'GIF pakkaa paljon tehottomammin kuin nykyaikaiset videokoodekit, joten tiedostokoko kasvaa nopeasti pituuden, tarkkuuden ja kuvataajuuden myötä. Muutama sekunti on paras kohta. Jos tulos on liian raskas, lyhennä leikettä, ja jos koko painaa enemmän kuin upotettu automaattinen toisto, MP4 näyttää saman animaation murto-osalla koosta.',
    "shapeFaq.rename.q1": "Heikentääkö {{fn}}-muodon muuntaminen {{tn}}-muotoon kuvani laatua?",
    "shapeFaq.rename.a1": "Ei. {{fn}} ja {{tn}} ovat saman kuvamuodon tiedostopäätteen kaksi kirjoitusasua, joten mitään ei pureta eikä pakata uudelleen. Tiedostosi kopioidaan tavu tavulta ja saa vain uuden päätteen, joten tulos on identtinen alkuperäisen kanssa EXIF-tietoja myöten.",
    "shapeFaq.rename.q2": "Jos {{fn}} ja {{tn}} ovat sama muoto, miksi muuntaa lainkaan?",
    "shapeFaq.rename.a2": "Koska jotkin ohjelmat tarkistavat tiedostopäätteen eivätkä sisältöä. Latauslomakkeet, vanhemmat ohjelmat ja jotkin kuvapalvelut hyväksyvät vain toisen kirjoitusasun ja hylkäävät toisen, vaikka kuva on täsmälleen sama. Päätteen vaihtaminen riittää, jotta tiedosto hyväksytään.",
    "intro.lead.pdf-images": "PDF kuviksi muuntaa PDF-tiedoston jokaisen sivun omaksi JPG- tai PNG-kuvakseen sivujärjestyksessä numeroituna, joten jokaisen sivun voi julkaista, jakaa tai muokata erikseen. PDF pitää sivut lukittuina yhteen kiinteän asettelun tiedostoon, ja juuri siksi sitä ei voi julkaista paikoissa, joihin saa ladata vain kuvia.",
    "steps.pdf-images.1": "Pudota PDF-tiedostosi tämän sivun yläreunan latausalueelle tai napsauta sitä valitaksesi tiedoston laitteeltasi.",
    "steps.pdf-images.2": "Valitse JPG pienempiä, valokuviin ja someen sopivia tiedostoja varten tai PNG terävää tekstiä ja grafiikkaa varten, ja napsauta sitten Muunna.",
    "steps.pdf-images.3": "Lataa jokainen sivu erikseen tai kaikki sivut kerralla ZIP-tiedostona. Linkit ovat voimassa 24 tuntia, minkä jälkeen kaikki poistetaan.",
    "shapeFaq.pdf-images.q1": "Tuleeko PDF-tiedostoni jokaisesta sivusta erillinen kuva?",
    "shapeFaq.pdf-images.a1": "Kyllä. Jokainen sivu hahmonnetaan omaksi kuvakseen ja numeroidaan järjestyksessä — page-01, page-02 ja niin edelleen — joten kymmensivuisesta PDF-tiedostosta saat kymmenen kuvaa. Voit ladata ne yksitellen tai yhdessä ZIP-tiedostossa, ja koko PDF maksaa yhden krediitin sivumäärästä riippumatta.",
    "shapeFaq.pdf-images.q2": "Sopivatko kuvat Instagramiin ja muuhun sosiaaliseen mediaan?",
    "shapeFaq.pdf-images.a2": "Kyllä. Sivut hahmonnetaan suurella tarkkuudella, joten ne pysyvät terävinä, vaikka Instagram, LinkedIn tai Facebook pienentää niitä. Pystysivut toimivat hyvin Instagram-karuselleina; parhaan tuloksen saat, kun suunnittelet diat 4:5- tai neliömuotoon ennen PDF-tiedoston vientiä ja valitset JPG-muodon, jotta lataukset pysyvät pieninä.",
    "intro.lead.collage": "Kuvakollaasi yhdistää useita kuvia yhdeksi: jokaisen kuvan kokoa muutetaan ja se sijoitetaan siistiin ruudukkoon tasaisin välein, joten kaiken näkee yhdellä silmäyksellä eikä kuvia tarvitse selata yksi kerrallaan. Valitse automaattinen asettelu tai kiinteä 2×2- tai 3×3-ruudukko, niin saat takaisin yhden JPG- tai PNG-tiedoston.",
    "steps.collage.1": "Lisää 2–16 kuvaa pudottamalla ne latausalueelle tai napsauttamalla valitaksesi ne, ja vedä ne sitten luettelossa haluamaasi järjestykseen.",
    "steps.collage.2": "Valitse asettelu — Automaattinen, 2×2 tai 3×3 — päätä, täyttävätkö kuvat ruutunsa vai näytetäänkö ne kokonaan, ja valitse JPG tai PNG.",
    "steps.collage.3": "Napsauta Luo kollaasi, tarkista esikatselu ja lataa valmis kuva. Se on saatavilla 24 tuntia.",
    "shapeFaq.collage.q1": "Rajataanko kuviani kollaasissa?",
    "shapeFaq.collage.a1": "Se on sinun päätettävissäsi. Vaihtoehdolla ”Täytä jokainen ruutu” jokainen kuva rajataan neliöksi kuvan kiinnostavimman kohdan ympäriltä, mikä antaa siisteimmän ruudukon. Vaihtoehdolla ”Näytä koko kuva” mitään ei leikata pois: kuva pienennetään sopivaksi, ja jäljelle jäävä tila täytetään valkoisella.",
    "shapeFaq.collage.q2": "Montako kuvaa yhteen kollaasiin mahtuu?",
    "shapeFaq.collage.a2": "Vähintään 2 ja enintään 16 Automaattinen-asettelulla, joka valitsee lisäämillesi kuville mahdollisimman neliömäisen ruudukon. 2×2-ruudukkoon mahtuu enintään 4 kuvaa ja 3×3-ruudukkoon enintään 9. Jokainen kollaasi maksaa yhden krediitin kuvien määrästä riippumatta.",
    "intro.rename": "{{fn}} ja {{tn}} ovat sama kuvamuoto kahdella eri tiedostopäätteellä, joten tämä muunnos vaihtaa vain nimen: kuva kopioidaan tavu tavulta ilman uudelleenpakkausta ja ilman laadun heikkenemistä. {{reason}}",
    "intro.lead.social-resize": "Koon muutos sosiaaliseen mediaan rajaa kuvan juuri siihen muotoon, jota alusta odottaa: 9:16 TikTok-, Reels-, Stories- ja Shorts-julkaisuihin, 1:1 neliönmuotoisiin syötejulkaisuihin, 4:5 pystysuuntaisiin Instagram-julkaisuihin ja 16:9 YouTube-videoihin. Sinä päätät, rajataanko kuva täyttämään kehys sen kiinnostavimpaan kohtaan keskitettynä vai näytetäänkö se kokonaan sumennetulla tai yksivärisellä taustalla.",
    "steps.social-resize.1": "Pudota valokuvasi tämän sivun yläreunan latausalueelle tai napsauta sitä valitaksesi kuvan laitteeltasi tai ottaaksesi uuden kuvan.",
    "steps.social-resize.2": "Valitse alustan muoto ja päätä sitten, rajataanko kuva täyttämään kehys vai sovitetaanko koko kuva taustalle.",
    "steps.social-resize.3": "Napsauta Muunna ja lataa uudelleen rajattu kuva. Latauslinkki on voimassa 24 tuntia.",
    "shapeFaq.social-resize.q1": "Pitäisikö kuva rajata vai sovittaa kokonaan?",
    "shapeFaq.social-resize.a1": "Rajaa, kun kohde mahtuu hyvin uuteen muotoon: kuva täyttää koko näytön ja näyttää alustalle luontevalta, ja rajaus keskitetään kuvan kiinnostavimpaan kohtaan. Sovita koko kuva, kun mitään ei saa leikata pois, esimerkiksi ryhmäkuvassa tai julisteessa, jonka teksti on lähellä reunoja; koko kuva pysyy näkyvissä oman sumennetun kopionsa päällä tai valkoisella tai mustalla taustalla.",
    "shapeFaq.social-resize.q2": "Minkä kokoisen kuvan kukin muoto tuottaa?",
    "shapeFaq.social-resize.a2": "9:16 tuottaa 1080 × 1920 pikseliä, 1:1 tuottaa 1080 × 1080, 4:5 tuottaa 1080 × 1350 ja 16:9 tuottaa 1920 × 1080 — juuri ne latauskoot, joita alustat itse suosittelevat. Kun kuva on täsmälleen tämän kokoinen, alustan ei tarvitse rajata tai skaalata sitä uudelleen.",
    "intro.lead.profile-picture": "Profiilikuvan tekijä rajaa kuvan kasvoihin tai pääkohteeseen keskitetyksi neliöksi ja skaalaa sen tavalliseen profiilikuvan kokoon: 400, 800 tai 1080 pikseliä. Jos valitset sen sijaan pyöreän version, kulmista tulee läpinäkyvät, joten profiilikuva näyttää hyvältä millä tahansa taustalla.",
    "steps.profile-picture.1": "Pudota kuva itsestäsi, logostasi tai brändistäsi latausalueelle tai napsauta sitä valitaksesi kuvan tai ottaaksesi uuden.",
    "steps.profile-picture.2": "Valitse neliö tai ympyrä ja koko — 800 × 800 pikseliä sopii kaikille suurille alustoille.",
    "steps.profile-picture.3": "Napsauta Muunna, tarkista neliön ja ympyrän esikatselu ja lataa sitten uusi profiilikuvasi.",
    "shapeFaq.profile-picture.q1": "Pitäisikö minun ladata neliön vai ympyrän muotoinen profiilikuva?",
    "shapeFaq.profile-picture.a1": "Yleensä neliön muotoinen. Instagram, Facebook, LinkedIn, X ja YouTube pyytävät kaikki neliökuvaa ja leikkaavat sen itse ympyräksi; pyöreä esikatselu näyttää, miltä se tulee näyttämään. Pyöreä PNG läpinäkyvine kulmineen on tarkoitettu paikkoihin, jotka näyttävät tiedoston täsmälleen sellaisenaan, kuten verkkosivustoille, sähköpostin allekirjoituksiin, esityksiin tai chat-sovelluksiin.",
    "shapeFaq.profile-picture.q2": "Minkä koon valitsisin?",
    "shapeFaq.profile-picture.a2": "800 × 800 pikseliä on varma valinta: terävämpi kuin yksikään alusta näyttää profiilikuvaa, mutta silti pieni tiedosto. 400 × 400 riittää LinkedIn-, X- ja Facebook-profiileihin, ja 1080 × 1080 tuo lisää yksityiskohtia tarkkoja näyttöjä varten tai painotuotteisiin.",
    "intro.lead.social-compress": "Kuvapakkaus sosiaaliseen mediaan pienentää kuvan suurimpaan kokoon, jonka alusta todella näyttää (Instagramissa 1080 pikseliä, Facebookissa 2048, X:ssä 4096), muuntaa sen sRGB-väreihin, joita jokainen sovellus odottaa, ja tallentaa sen laadukkaana JPG-kuvana. Valmiiksi pienempiä kuvia ei koskaan suurenneta.",
    "steps.social-compress.1": "Pudota valokuvasi tämän sivun yläreunan latausalueelle tai napsauta sitä valitaksesi kuvan. Voit lisätä useita kuvia kerralla.",
    "steps.social-compress.2": "Valitse alusta, jolle julkaiset, ja napsauta Muunna.",
    "steps.social-compress.3": "Lataa optimoitu JPG-kuva ja lähetä se alustalle. Linkki on voimassa 24 tuntia.",
    "shapeFaq.social-compress.q1": "Miksi pienempi tiedosto näyttäisi latauksen jälkeen paremmalta?",
    "shapeFaq.social-compress.a1": "Koska alustan ei enää tarvitse käsitellä sitä. Kun kuva on suurempi kuin alusta näyttää, se pienennetään ja pakataan automaattisesti uudelleen, usein heikolla laadulla, ja siitä syntyvät suttuiset yksityiskohdat ja palikoituneet taivaat. Kuva, joka saapuu valmiiksi oikean kokoisena ja sRGB-väreissä, tallennetaan lähes täsmälleen sellaisena kuin lähetit sen.",
    "shapeFaq.social-compress.q2": "Miten tämä eroaa tavallisesta kuvapakkauksesta?",
    "shapeFaq.social-compress.a2": "Tavallinen kuvapakkaus säilyttää tiedostosi mitat ja muodon ja vain tiivistää datan. Tämä työkalu myös muuttaa kuvan koon alustan näyttökokoon ja muuntaa sen sRGB-JPG:ksi, ja juuri se ratkaisee lopputuloksen sosiaalisessa mediassa. PNG-kuvan läpinäkyvät alueet muuttuvat valkoisiksi, koska JPG ei tue läpinäkyvyyttä.",
  },
};
