// Hungarian content pack. Mirrors packs/en.js key for key — see the header there.
// Format names are never preceded by a bare definite article: Hungarian picks
// a/az by pronunciation, which a placeholder cannot know, so the templates use
// "a(z)" or attach case endings to a following compound noun instead.
export default {
  lang: 'hu',
  formats: {
    pdf: { about: 'A PDF rögzített tördelésű formátum: minden karakter, vonal és kép pontos helyét eltárolja, ezért néz ki bármely képernyőn és nyomtatón azonosan, viszont kényelmetlen szerkeszteni.', note: 'A PDF rögzíti a lapozást, a betűtípusokat és a tördelést, így a címzett pontosan azt látja, amit elküldtél.' },
    docx: { about: 'A DOCX a Microsoft Word korszerű formátuma, amelyben a szöveg szerkeszthető bekezdésekben és stílusokban él, nem pedig rögzített oldalkoordinátákhoz szegezve.', note: 'A DOCX valóban szerkeszthető bekezdéseket, változáskövetést és megjegyzéseket ad a Wordben, a Google Dokumentumokban vagy a LibreOffice-ban.' },
    xlsx: { about: 'Az XLSX az Excel táblázatformátuma, amelyben minden érték egy megcímezhető cellában ül, ami rendezhető, szűrhető és képletben használható.', note: 'Amint az adatok XLSX-ben vannak, összegezheted, rendezheted, kimutatásba teheted és grafikonra viheted őket ahelyett, hogy újragépelnéd.' },
    pptx: { about: 'A PPTX a bemutatót külön diákként tárolja, szerkeszthető szövegdobozokkal, alakzatokkal, előadói jegyzetekkel és áttűnésekkel.', note: 'A PPTX olyan diákat ad vissza, amelyeket tényleg újraszerkeszthetsz, átrendezhetsz és újra levetíthetsz.' },
    txt: { about: 'Egy TXT-fájl nem más, mint karakterek — se betűtípus, se kép, se oldalszerkezet —, ettől lesz parányi, mindenhol olvasható és triviálisan kereshető.', note: 'A TXT a szavakon kívül mindent lehánt, és pontosan ezt akarják a szkriptek, a keresőindexek és a szövegszerkesztők.' },
    html: { about: 'A HTML a web jelölőnyelve: címkékbe csomagolt szöveg, amiből a böngésző címsorokat, bekezdéseket, hivatkozásokat és képeket csinál.', note: 'A HTML bármelyik böngészőben megnyílik, és közvetlenül beilleszthető egy weboldalba vagy tartalomkezelő rendszerbe.' },
    rtf: { about: 'Az RTF nyílt, egyszerű szövegre épülő dokumentumformátum, amely viszi magával az alapformázást — félkövér, dőlt, betűtípusok, táblázatok —, anélkül hogy egyetlen szövegszerkesztőbe zárna.', note: 'Az RTF megnyílik Wordben, Pagesben, LibreOffice-ban, WordPadben és szinte minden valaha írt szövegszerkesztőben.' },
    odt: { about: 'Az ODT a LibreOffice és az OpenOffice OpenDocument szövegformátuma, és ISO-szabvány, nem pedig egyetlen gyártó formátuma.', note: 'Az ODT a LibreOffice és az OpenOffice saját, teljesen szerkeszthető formátuma.' },
    epub: { about: 'Az EPUB folyó szövegű e-könyvformátum: nincs rögzített oldalmérete, így a szöveg újratördelődik ahhoz a képernyőhöz és betűmérethez, amit az olvasó használ.', note: 'Az EPUB engedi, hogy az olvasó átállítsa a betűméretet és újratördelje a szöveget, és épp ez teszi kényelmessé a hosszú dokumentumokat telefonon vagy e-könyv-olvasón.' },
    jpg: { about: 'A JPG fényképekre hangolt veszteséges tömörítést használ: eldobja azokat a részleteket, amiket a szem a legkevésbé vesz észre, ettől lesznek kicsik a fotók, viszont lágy, kockás hibákat tesz az éles peremek és a szöveg köré.', note: 'A JPG kis fájlokat ad, amelyek szó szerint mindenhol megnyílnak, cserébe véglegesen elveszett részletekért és a hiányzó átlátszóságért.' },
    jfif: { about: 'A JFIF más kiterjesztéssel mentett JPEG-kép; a benne lévő képpontok szokványos JPEG-adatok, a Windows viszont gyakran megtagadja, hogy átadja a fájlt annak az alkalmazásnak, amelyiket szeretnéd.', note: 'A JFIF valójában csak JPEG más néven.' },
    png: { about: 'A PNG veszteségmentes: minden képpontot pontosan tárol, teljes alfacsatornát támogat az átlátszósághoz, és soha nem romlik újramentéskor, ezért ez az első választás képernyőképekhez, logókhoz és felületi grafikához.', note: 'A PNG minden képpontot pontosan úgy őriz meg, ahogy van, és valódi átlátszóságot támogat, így romlás nélkül bírja az ismételt szerkesztést.' },
    webp: { about: 'A WebP a Google korszerű webes képformátuma; hasonló minőség mellett érezhetően jobban tömörít, mint a JPG vagy a PNG, és támogatja az átlátszóságot és az animációt, ám rengeteg asztali és nyomdai program máig nem tudja megnyitni.', note: 'A WebP adja a legkisebb fájlokat a szokásos webes formátumok közül, és támogatja az átlátszóságot.' },
    bmp: { about: 'A BMP nyers, gyakorlatilag tömörítetlen képpontadatot tárol, amitől tökéletesen hű és rettentően pazarló — egy fénykép könnyedén tízszer akkora lehet, mint ugyanaz a kép PNG-ben.', note: 'A BMP nyers és tömörítetlen, és pontosan ezt várja el máig a régi windowsos szoftver és néhány lapolvasó.' },
    tiff: { about: 'A TIFF az archiválás és a nyomdai előkészítés formátuma: veszteségmentes, nagy színmélységű, több oldalt vagy réteget is elbír — és ennek megfelelően testes.', note: 'A TIFF az a formátum, amit a nyomdák és az archívumok kérnek, mert semmi nem vész el belőle.' },
    gif: { about: 'A GIF képkockánként 256 színre van korlátozva, ezért látszanak benne sávosnak a fényképek, viszont animálódik és beágyazva magától elindul szinte mindenhol az interneten.', note: 'A GIF animálódik és magától elindul a csevegőalkalmazásokban, a hibajegyrendszerekben és a fórumokon, de képkockánként 256 színre korlátozott.' },
    ico: { about: 'Az ICO windowsos ikontároló, amely ugyanazt a grafikát több méretben tartja egyszerre, hogy a rendszer választhasson 16×16-ot egy lapfülhöz és 256×256-ot egy asztali parancsikonhoz.', note: 'Az ICO több felbontást fog össze egyetlen fájlban, és pontosan erre van szükségük a faviconoknak és a windowsos alkalmazásikonoknak.' },
    heic: { about: 'A HEIC az a formátum, amelybe az iPhone alapértelmezés szerint menti a fotókat; nagyjából a JPG minőségét adja körülbelül fele akkora helyen, viszont a Windows, sok webes űrlap és rengeteg régebbi program egyszerűen megtagadja a megnyitását.', note: 'A HEIC tömör, de az Apple eszközein kívül gyengén támogatott.' },
    svg: { about: 'Az SVG egyáltalán nem képpontokból áll — XML, amely alakzatokat, útvonalakat és szöveget ír le, ezért bármilyen méretben tökéletesen éles marad, és kóddal szerkeszthető vagy átstílusozható.', note: 'Az SVG bármekkorára nagyítható anélkül, hogy valaha elmosódna, mert alakzatokat tárol képpontok helyett.' },
    mp4: { about: 'Az MP4 tároló — általában H.264 videó AAC hanggal —, és ez az az egyetlen videoformátum, amelyben a telefonok, a böngészők, a tévék, a vágóprogramok és a közösségi platformok mind egyetértenek.', note: 'Az MP4 gyakorlatilag minden telefonon, böngészőben, tévén és vágóprogramban lejátszódik, külön szoftver nélkül.' },
    avi: { about: 'Az AVI a Microsoft kilencvenes évekbeli tárolója; a régebbi lejátszók és vágócsomagok még olvassák, de nincsenek korszerű adatfolyam-funkciói, és a fájljai jellemzően jóval nagyobbak az MP4-nél.', note: 'Az AVI az, amit a régebbi lejátszók, a DVD-készítő eszközök és az elavult vágószoftverek várnak.' },
    mov: { about: 'A MOV az Apple QuickTime tárolója, az a formátum, amelybe az iPhone és a Mac rögzít, és amellyel a Final Cut Pro és az iMovie a legsimábban bánik.', note: 'A MOV az a tároló, amellyel az Apple vágóeszközei a legsimábban dolgoznak.' },
    mkv: { about: 'Az MKV (Matroska) nyílt tároló, amely tetszőleges számú kép-, hang- és feliratsávot elbír egyetlen fájlban — archiválásra kiváló, de a telefonok, tévék és böngészők többsége elutasítja.', note: 'Az MKV több hang- és feliratsávot is elvisz egyetlen fájlban.' },
    webm: { about: 'A WebM a HTML5-videóhoz épített, jogdíjmentes tároló, általában VP9-cel vagy AV1-gyel; a böngészők imádják, az asztali vágóprogramok és az Apple szoftverei viszont gyakran hozzá sem nyúlnak.', note: 'A WebM kicsi, és a böngészőkben natívan streamelődik.' },
    wmv: { about: 'A WMV a Microsoft Windows Media videoformátuma, gyakorlatilag csak Windowsra, és a régi céges felvételeken és képernyőrögzítéseken kívül nagyrészt elhagyott.', note: 'A WMV Windows Media formátum, máshol nagyon gyenge támogatással.' },
    flv: { about: 'Az FLV a Flash-videó mögötti tároló volt, és mióta a Flasht minden böngészőből eltávolították, gyakorlatilag lejátszhatatlan archív formátum.', note: 'Az FLV halott tároló a Flash korszakából.' },
    mp3: { about: 'Az MP3 veszteséges: a kódoló véglegesen törli a jel azon részeit, amikről azt jósolja, hogy úgysem hallod, ettől zsugorodik egy szám nagyjából a tizedére, és ezért játszódik le tényleg mindenen.', note: 'Az MP3 körülbelül tízszer kisebb a tömörítetlen hangnál, és lejátszódik az elmúlt húsz év minden telefonján, autórádióján és lejátszóján.' },
    wav: { about: 'A WAV tömörítetlenül, mintáról mintára tárolja a hangot, pontosan úgy, ahogy felvették — ezért használják a stúdiók, és ezért foglal egy perc CD-minőségű sztereó nagyjából 10 MB-ot.', note: 'A WAV tömörítetlen és veszteségmentes, így a vágó- és masteringprogramok úgy dolgozhatnak vele, hogy előbb semmit nem kell dekódolniuk.' },
    flac: { about: 'A FLAC veszteségmentesen tömöríti a hangot: nagyjából feleakkora, mint a WAV, mégis bitre azonos másolattá dekódolódik vissza.', note: 'A FLAC bitre azonos, de nagyjából feleakkora, mint a WAV.' },
    aac: { about: 'Az AAC az a veszteséges kodek, amely az Apple Music, a YouTube és a legtöbb streamingszolgáltatás mögött áll; azonos bitsebességen általában jobban szól, mint az MP3.', note: 'Az AAC azonos bitsebességen jobban szól az MP3-nál, és szabvány az Apple és a streaming világában.' },
    ogg: { about: 'Az OGG Vorbis szabadalommentes veszteséges kodek, amit a játékok, a nyílt forrású szoftverek és a Wikipédia kedvelnek, minőségben az MP3-mal összemérhető, kisebb méret mellett.', note: 'Az OGG mentes a szabadalmi korlátoktól, ezért részesítik előnyben a játékmotorok és a nyílt forrású projektek.' },
    m4a: { about: 'Az M4A csak hangot tartalmazó MP4 tároló, rendes esetben AAC-vel — ezt a formátumot állítja elő az iTunes, az Apple Music és az iPhone hangjegyzete.', note: 'Az M4A az Apple ökoszisztémájának alapértelmezett hangfájlja.' },
    wma: { about: 'A WMA a Microsoft veszteséges hangkodeke a Windows Media Player korszakából, Windowson kívül ritkán támogatott, és gyakorlatilag megszűnt.', note: 'A WMA elavult, csak Windowson élő hangkodek.' },
    zip: { about: 'A ZIP az az archívumformátum, amely be van építve a Windowsba, a macOS-be és minden telefonba — elég rákattintani duplán, semmit nem kell telepíteni.', note: 'A ZIP dupla kattintással megnyílik Windowson, macOS-en, Linuxon, iOS-en és Androidon, telepítés nélkül.' },
    rar: { about: 'A RAR zárt archívumformátum jó tömörítéssel és helyreállítási adatokkal, de a megnyitásához WinRAR vagy azzal kompatibilis eszköz kell.', note: 'A RAR kicsomagolásához külső szoftver kell.' },
    '7z': { about: 'A 7Z LZMA-tömörítést használ, ami rendszeresen érezhetően kisebb archívumokat ad, mint a ZIP — cserébe a megnyitásukhoz 7-Zip vagy azzal kompatibilis eszköz kell.', note: 'A 7Z jelentősen szorosabban tömörít a ZIP-nél, ami nagy mappáknál és fizetős felhőtárhelynél számít.' },
    tar: { about: 'Egy TAR-fájl sok fájlt fog egybe anélkül, hogy tömörítené őket; a Unix világából származik, és megőrzi a jogosultságokat és a könyvtárszerkezetet.', note: 'A TAR megőrzi a Unix-jogosultságokat és a könyvtárszerkezetet.' },
    gz: { about: 'A GZ (gzip) egyetlen adatfolyamot tömörít, és ezt állítják elő a linuxos kiszolgálók és a parancssori eszközök; Windowson külön szoftver nélkül kényelmetlen megnyitni.', note: 'A GZ a Linux és a webkiszolgálók alapértelmezett tömörítési formátuma.' },
    srt: { about: 'Az SRT az az egyszerű szöveges feliratformátum, amit minden vágóprogram és minden lejátszó ért: sorszámozott feliratok, egy időkódtartomány és a párbeszéd sora.', note: 'Az SRT-t elfogadja a YouTube, a Vimeo, a Premiere, a Final Cut és minden szokásos lejátszó.' },
  },
  reasons: {
    'pdf-to-word': 'A szokásos kiváltó ok egy módosítás, amit magában a PDF-ben nem tudsz elvégezni — egy szerződéses kikötés, egy önéletrajzi pont vagy egy jelentésbeli bekezdés, aminek úgy kell megváltoznia, hogy ne kelljen az egész dokumentumot újragépelni.',
    'word-to-pdf': 'A Wordöt a dokumentum életének legvégén alakítják PDF-fé: amikor egy önéletrajz, egy árajánlat vagy egy aláírt űrlap olyasvalakihez indul, akinek a betűtípusait, Word-verzióját és margóit nem tudod befolyásolni.',
    'pdf-to-excel': 'A jellemző eset egy bankszámlakivonat, számla vagy jelentés, ami csak PDF-ként létezik, de a számait össze kell adnod, rendezned vagy grafikonra vinned.',
    'excel-to-pdf': 'Ezt akkor csinálod, mielőtt egy költségvetést vagy árlistát elküldenél valakinek, akinek olvasnia kell, de módosítania nem, és nyomtatás előtt — a PDF rögzíti az oldaltöréseket, amiket az Excel különben minden gépen újraszámolna.',
    'pptx-to-pdf': 'A legtöbben azelőtt alakítják PDF-fé a bemutatót, hogy elküldenék vagy szétosztanák, hogy a diák ne csússzanak el, és senkinek ne kelljen telepített PowerPoint a megnyitásukhoz.',
    'pdf-to-pptx': 'Erre akkor van szükséged, ha egy bemutató egyetlen fennmaradt példánya az az ülés után körbeküldött PDF, és a diákat frissítened vagy újra fel kell használnod.',
    'pdf-to-txt': 'Gyakori okok: dokumentumot adni egy szkriptnek, egy keresőindexnek vagy egy mesterségesintelligencia-eszköznek, vagy egy hosszú jelentést olyasmivé lepárolni, amiben kereshetsz, amit összevethetsz és bárhová beilleszthetsz.',
    'pdf-to-html': 'Ez a leggyorsabb mód arra, hogy egy meglévő jelentést, kézikönyvet vagy prospektust weboldalon közölj anélkül, hogy kézzel újraépítenéd az oldalt.',
    'html-to-pdf': 'Azért csinálják, hogy egy weboldalt pontosan úgy archiváljanak, ahogyan ma kinéz, vagy hogy egy HTML-es számla- vagy jelentéssablonból nyomtatható és elküldhető dolgot csináljanak.',
    'rtf-to-pdf': 'Az RTF általában régebbi szoftverből vagy jogi dokumentumsablonokból kerül elő; a PDF-fé alakítás egyetlen olyan fájlt ad, ami mindenhol ugyanúgy nyílik meg, és véletlenül nem módosítható.',
    'pdf-to-rtf': 'Ez a választás akkor, ha szerkeszthető másolatra van szükséged egy PDF-ből, de nem feltételezheted, hogy a címzettnek van Wordje — gyakorlatilag minden valaha írt szövegszerkesztő megnyitja az RTF-et.',
    'odt-to-pdf': 'A jellemző eset: a dokumentumot LibreOffice-ban vagy OpenOffice-ban írtad, az pedig, aki megkapja, Microsoft Office-t használ — vagy semmit.',
    'pdf-to-epub': 'PDF-et telefonon olvasni állandó nagyítást és vízszintes görgetést jelent; ez az átalakítás elsősorban arról szól, hogy egy hosszú dokumentum tényleg olvasható legyen kis képernyőn vagy e-könyv-olvasón.',
    'epub-to-pdf': 'Az EPUB-ot akkor alakítják PDF-fé, ha ki akarnak nyomtatni egy könyvet, rögzített oldalszámokhoz akarnak jegyzetelni, vagy olyasvalakinek küldenék, akinek nincs olvasóalkalmazása.',
    'document-converter': 'Ezt az eszközt akkor nyitod meg, amikor olyan formátumban kapsz egy dokumentumot, ami a feladónak épp kéznél volt, és neked abban kell, amit a saját szoftvered tényleg megnyit.',
    'ebook-converter': 'Az e-könyvboltok és az olvasók mind a saját formátumukat részesítik előnyben, így ezzel viszed át a tulajdonodban lévő könyvet egyik olvasóból vagy alkalmazásból a másikba.',
    'jpg-to-png': 'A szokásos kiváltó ok a szerkesztés: hátteret kell kivágnod, logót kell egy másik képre tenned, vagy meg kell akadályoznod, hogy egy képernyőkép minden újramentéssel homályosabb legyen.',
    'png-to-jpg': 'Ez a megoldás arra a képernyőképre vagy exportra, ami túl nagy ahhoz, hogy e-mailhez csatold, vagy hogy átférjen egy feltöltési űrlap méretkorlátján.',
    'webp-to-png': 'Erre általában azután van szükséged, hogy elmentettél egy képet egy weboldalról: a WebP gond nélkül letöltődik, de a régebbi képszerkesztők, az irodai programok és néhány nyomdai szolgáltatás máig megtagadja a megnyitását.',
    'webp-to-jpg': 'A legtöbben azért csinálják ezt, hogy egy weboldalról származó képet valami egyetemesen elfogadott dologba vigyenek — e-mailbe, régebbi tartalomkezelő rendszerbe, fotókidolgozó szolgáltatásba vagy egy kolléga ősrégi programjába.',
    'heic-to-jpg': 'Ez a klasszikus iPhone-probléma: a fotók jól néznek ki a telefonon, de egy Windowsos gépen vagy egy webes űrlapon megnyithatatlan .heic fájlokként landolnak.',
    'heic-to-png': 'Akkor használd, ha szerkeszteni akarod a fotót, nem csak megosztani — a PNG veszteségmentes képpontokat ad a szerkesztődnek egy frissen újratömörített másolat helyett.',
    'svg-to-png': 'A szokásos ok egy eszköz, ami elutasítja a vektorokat: egy bemutató, egy piactéri hirdetés, egy e-mail-aláírás vagy egy alkalmazásikon-gyártósor, ami csak képpontokat fogad.',
    'svg-to-jpg': 'Ez olyan helyekre való, amelyek egyszerű, fényképszerű fájlt akarnak — egy dokumentumba, egy közösségimédia-bejegyzésbe vagy egy feltöltési űrlapra, ami az SVG-jelölést és az átlátszóságot is elutasítja.',
    'bmp-to-png': 'A BMP-fájlok abszurd méretben kerülnek elő régi windowsos szoftverből és lapolvasókból; a PNG pontosan ugyanazokat a képpontokat tárolja a hely töredékén.',
    'tiff-to-jpg': 'A lapolvasók és a professzionális fényképezőgépek olyan TIFF-eket állítanak elő, amelyek messze túl nagyok e-mailhez, így a JPG az, amit elküldesz, amint az archív példány biztonságban van.',
    'gif-to-png': 'Ezt egy álló GIF-fel csinálod — egy logóval, egy ikonnal vagy egy exportált képkockával —, amelyen a 256 szín korlátja miatt színsávok vagy foszlott perem látszik.',
    'png-to-ico': 'Aki PNG-t alakít ICO-vá, az szinte mindig faviconon vagy windowsos alkalmazásikonon dolgozik, és mindkettő az ICO tárolót várja, nem sima képfájlt.',
    'jfif-to-png': 'A JFIF-fájlok jellemzően akkor bukkannak fel, amikor egy fotót az Outlookból vagy egy böngészőből mentenek, a Windows pedig utána megtagadja, hogy átadja annak az alkalmazásnak, amelyiket tényleg használni akartad.',
    'heic-to-pdf': 'Hasznos, ha iPhone-nal fényképezel dokumentumokat, blokkokat vagy egy táblát, és egyetlen fájlként kell beadnod őket egy képekkel teli mappa helyett.',
    'image-compressor': 'A szokásos ok valahol egy kemény korlát — egy feltöltési űrlap, egy e-mail-mellékletplafon vagy egy weboldal, ami azért tölt be túl lassan, mert a képei sokkal nagyobbak a kelleténél.',
    'jpeg-compressor': 'A fényképészek és a weboldal-tulajdonosok akkor használják, ha a teljes felbontású JPEG-ek lassítanak egy oldalt, vagy nem férnek át egy feltöltési korláton.',
    'png-compressor': 'A képernyőképek és az exportált felületi grafika gyakran több megabájt minden jó ok nélkül; ez lekicsinyíti őket, mielőtt dokumentumba, hibajegybe vagy weboldalra kerülnének.',
    'mp4-to-avi': 'Az ok szinte mindig egy régebbi eszköz vagy egy konkrét program — néhány régi lejátszó, DVD-készítő eszköz és fényképezőgépes segédprogram AVI-t olvas, és semmi mást.',
    'mp4-to-mov': 'Ez rendesen az első lépés Macen való vágás előtt, mivel a Final Cut Pro és az iMovie a QuickTime-fájlokkal bánik a legsimábban.',
    'mov-to-mp4': 'Az iPhone és a Mac MOV-ba rögzít; minden más MP4-et vár, így ezt az átalakítást futtatják, mielőtt egy klipet feltöltenének, elküldenének vagy közzétennének.',
    'mkv-to-mp4': 'Az MKV tárolásra kiváló, de a telefonok, a tévék, a böngészők és a legtöbb vágóprogram nem játssza le — az MP4-fé alakítás teszi a fájlt igazán használhatóvá.',
    'webm-to-mp4': 'A webről mentett WebM-fájlok gyakran megtagadják a megnyílást QuickTime-ban, iOS-en vagy Premiere-ben; az MP4 az a formátum, amit mind elfogadnak.',
    'avi-to-mp4': 'Ez a bevett mentőöv a régi kamerás felvételekhez és az archivált klipekhez, amelyek gigabájtokat nyelnek és egyetlen telefonon sem játszódnak le.',
    'flv-to-mp4': 'A Flash eltűnt minden böngészőből, így minden megmaradt FLV gyakorlatilag lejátszhatatlan — az MP4-fé alakítás tartja nézhetőként azt az archivált anyagot.',
    'wmv-to-mp4': 'A WMV kizárólag Windowson élő maradvány, így ezt azelőtt csinálod, hogy egy régi felvételt vagy képernyőrögzítést Macre, iPhone-ra vagy webes platformra küldenél.',
    'mp4-to-mp3': 'Rendszerint a hang számít, nem a kép — egy előadás, egy interjú, egy podcast vagy egy videóklip, amit a telefonodon akarsz anélkül, hogy cipelnéd a képet is.',
    'video-to-mp3': 'Akkor nyúlnak ehhez, ha a hang az a rész, amit érdemes megtartani: egy rögzített előadás, egy interjú, egy próba vagy egy filmzene.',
    'mp4-converter': 'Ez az az eszköz, amikor egy klip nem játszódik le vagy nem tölthető fel, mert az MP4 az az egyetlen videoformátum, amit a telefonok, a böngészők, a tévék és a közösségi platformok mind elfogadnak.',
    'video-converter': 'Akkor használd, amikor egy klipnek világot kell váltania — ki egy vágóprogramból, rá egy telefonra, be egy böngészőbe, vagy fel egy platformra, ami csak egyetlen konkrét tárolót fogad.',
    'mp3-to-wav': 'A szokásos ok a szerkesztés: a digitális hangállomások, a masteringláncok és sok műsorszórási vagy játékhangos munkafolyamat tömörítetlen WAV-ot akar, hogy ne kelljen minden egyes műveletnél tömörített fájlt dekódolniuk.',
    'wav-to-mp3': 'A felvételek hatalmas WAV-fájlokként kerülnek ki egy terepi rögzítőből vagy egy hangállomásból; az MP3 teszi őket elég kicsivé ahhoz, hogy elküldd, feltöltsd vagy elférjenek a telefonon.',
    'flac-to-mp3': 'Egy FLAC-gyűjtemény otthon remekül szól, de az autós hangrendszerek, a régebbi telefonok és az olcsó lejátszók gyakran elutasítják — az MP3 az a kompatibilitási példány, amit magaddal viszel.',
    'aac-to-mp3': 'Itt főként kompatibilitásról van szó: az AAC az Apple és a streaming világából jön, míg a régebbi lejátszók, az autórádiók és a lemezlovas szoftverek MP3-at várnak.',
    'ogg-to-mp3': 'Az OGG játékokban, a Wikipédián és nyílt forrású szoftverekben bukkan fel, és a telefonokon vagy autókban használt szokásos lejátszók közül szinte egyik sem nyitja meg.',
    'wma-to-mp3': 'A WMA a Windows Media Player korszakának relikviája, és így mentenek meg egy régi, lemezekről kimásolt zenei gyűjteményt telefonra vagy streamingkönyvtárba.',
    'm4a-to-mp3': 'Ez a szokásos lépés, amikor zenét vagy iPhone-os hangjegyzeteket viszel át Apple-eszközökről olyan programokba, autókba vagy lejátszókba, amelyek csak MP3-at értenek.',
    'mp3-to-aac': 'Néhány eszköz és alkalmazás — különösen az Apple és a streamingplatformok környékén — az AAC-t részesíti előnyben, tehát ez kompatibilitási átalakítás, nem minőségjavítás.',
    'mp3-to-ogg': 'OGG-ra játékmotorok, nyílt forrású projektek és olyan platformok miatt alakítanak, ahol szabadalommentes kodek a követelmény.',
    'audio-converter': 'Ez az az eszköz arra a pillanatra, amikor egy fájl nem játszódik le: egyetlen hely, ahol a hangot pontosan abba a szokásos formátumba viszed, amelyikhez az eszközöd, a szerkesztőd vagy a feltöltési űrlapod ragaszkodik.',
    'rar-to-zip': 'A RAR megnyitásához külön szoftver kell, tehát ezt azelőtt csinálod, hogy egy archívumot olyasvalakinek küldenél, aki nem fog WinRAR-t telepíteni.',
    '7z-to-zip': 'A 7Z jobban tömörít, de telepített 7-Zipet kíván; ZIP-ként a címzett egyszerűen duplán kattinthat a fájlra.',
    'tar-to-zip': 'A TAR a Linux és a macOS parancssorából jön, míg a ZIP az, amit egy windowsos kolléga bármi telepítése nélkül meg tud nyitni.',
    'gz-to-zip': 'A GZ-fájlok általában kiszolgálóról vagy linuxos eszközből érkeznek, és Windowson kényelmetlenek, ahol egy ZIP dupla kattintással kicsomagolódik.',
    'zip-to-7z': 'Itt a méretről van szó: a 7Z tömörítése érezhetően erősebb, ami akkor számít, ha nagy mappát archiválsz, vagy gigabájtonként fizetsz a felhőtárhelyért.',
    'video-to-gif': 'A jellemző használat egy rövid hurok csevegőüzenetbe, README-fájlba, hibajelentésbe vagy bejegyzésbe — olyan helyekre, ahol a GIF beágyazva magától elindul, egy videofájl viszont nem.',
    'mp4-to-gif': 'A jellemző használat egy rövid hurok csevegésbe, README-fájlba, hibajelentésbe vagy bejegyzésbe, ahol a GIF beágyazva magától elindul, míg egy videó csak ott heverne mellékletként.',
    'webm-to-gif': 'A webről mentett WebM-klipek gyakran nem ágyazhatók be oda, ahová szeretnéd, míg egy GIF beágyazva elindul a csevegőalkalmazásokban, a hibajegyrendszerekben és a fórumokon.',
    'mov-to-gif': 'Ezt egy QuickTime-os képernyőrögzítéssel csinálod, aminek beágyazva kell megjelennie egy pull requestben, egy ügyfélszolgálati jegyben vagy egy bejegyzésben.',
    'avi-to-gif': 'Egy régi AVI-klip néhány másodpercét GIF-fé alakítani a legegyszerűbb mód arra, hogy bekerüljenek egy dokumentumba, egy csevegésszálba vagy egy weboldalra.',
    'gif-to-mp4': 'A hosszú GIF-ek hatalmasak és akadozva játszódnak le; az MP4 ugyanazt az animációt a méret töredékén mutatja, és pontosan ezért alakítják át őket a közösségi platformok a háttérben.',
    'image-to-gif': 'Hasznos, ha egy platform vagy egy régebbi rendszer kifejezetten GIF-et vár, vagy ha egy állóképre van szükséged ugyanabban a formátumban, mint egy meglévő animációsorozat.',
    'gif-compressor': 'Az animált GIF-ek gyorsan felfúvódnak, és ez a megoldás, ha valamelyik túl nehéz egy e-mailhez, egy csevegés feltöltési korlátjához vagy egy oldalhoz, aminek gyorsan kell betöltődnie.',
    'merge-pdf': 'A klasszikus eset egy kérelem vagy egy kárbejelentés: egy űrlap, egy beolvasás és egy blokk, amiknek mind egyetlen dokumentumként kell megérkezniük.',
    'split-pdf': 'Rendszerint pontosan egy dolog kell egy sokkal hosszabb fájlból — egy fejezet, egy számla, egy aláírt oldal egy ötvenoldalas beolvasásból.',
    'compress-pdf': 'Szinte mindig méretkorlát: egy e-mail-mellékletplafon, egy hivatali űrlap vagy egy portál, ami néhány megabájt fölött mindent elutasít.',
    'rotate-pdf': 'Ez a hétköznapi lapolvasós gondot orvosolja — az oldalakat, amelyek oldalra dőlve vagy fejjel lefelé jöttek ki abból adódóan, ahogy a lapokat betolták.',
    'protect-pdf': 'A PDF-eket azelőtt védik jelszóval, hogy bérpapírokat, szerződéseket vagy orvosi leleteket küldenének el, hogy a tartalom ne legyen olvasható annak, akinek az üzenetet utána továbbküldik.',
    'unlock-pdf': 'Olyan dokumentumokon használd, amelyek a tieid, amikor a jelszó ismert, de a korlátozás útban van — például egy bankszámlakivonaton, amit nem tudsz kinyomtatni.',
    'view-metadata': 'Azokra a kérdésekre válaszol, amiket egy fájl nem mond meg egyenesen: milyen géppel készült ez a fotó, valójában milyen hosszú ez a felvétel, milyen kodek van ebben a videóban, hány oldalas ez a PDF.',
    'ocr': 'A helyzet mindig ugyanaz: van egy dokumentumod képként, és kellenek belőle a szavak — hogy keress bennük, idézd, szerkeszd vagy rendesen archiváld őket.',
    'pdf-compress-ai': 'Akkor nyúlj hozzá, ha a szokásos tömörítést már megpróbáltad, és a fájl még mindig túl nagy ahhoz a feltöltési korláthoz, amivel küzdesz.',
    'text-to-speech': 'Arra használják, hogy meghallgassanak valamit olvasás helyett — egy cikket a munkába menet, egy hangosan felolvasott forgatókönyvet, hogy kiszúrják a döcögős megfogalmazásokat, vagy egy narrációt egy videóhoz.',
    'speech-to-text': 'A szokásos eset egy felvétel, ami írásban kell: egy megbeszélés, egy interjú, egy előadás vagy egy hangjegyzet, amiből jegyzetnek, jegyzőkönyvnek vagy idézhető átiratnak kell lennie.',
    'auto-subtitle': 'A feliratok teszik a videót hang nélkül is nézhetővé és a keresőmotorok számára megtalálhatóvá, kézzel begépelni pedig még rövid klipnél is sokkal több idő, mint gondolnánk.',
    'document-translation': 'A cél az, hogy más nyelven olvass vagy küldj el egy dokumentumot anélkül, hogy elveszne az a tördelés, amitől olvasható.',
  },
  t: {
    'list.and': 'és',
    'family.document': 'dokumentum',
    'family.image': 'kép',
    'family.video': 'videó',
    'family.audio': 'hang',
    'family.ebook': 'e-könyv',
    'family.archive': 'archívum',
    'family.subtitle': 'felirat',
    'family.none': 'fájl',
    'unit.sample': 'minden minta',
    'unit.pixel': 'minden képpont',

    'intro.convert': '{{fromAbout}} {{toAbout}} {{reason}} {{toNote}}',
    'intro.convert.noSource': 'A(z) {{fn}} ennek az átalakításnak a forrásformátuma.',
    'intro.lead': '{{lead}} {{reason}}',
    'intro.hub': 'Ez az általános {{category}}átalakító: elfogadja a következőket — {{inputs}} —, és ezeket írja: {{outputs}}, így nem kell azt az egy konkrét eszközt vadásznod, ami épp a te formátumpárodhoz illik. {{reason}} Válaszd ki fent a kimeneti formátumot — az átalakítás a kiszolgálón fut, semmit nem kell telepíteni.',
    'intro.hubExtract': 'Ez az eszköz kihúzza a hangsávot egy videofájlból és külön menti, így a videóból egyszerű hangfájl lesz, ami bárhol lejátszódik. Elfogadja a következőket — {{inputs}} —, és ezeket írja: {{outputs}}. A képsávot egyszerűen eldobja, és ezért lesz az eredmény az eredeti méret töredéke. {{reason}}',
    'intro.hubGif': 'Ez az eszköz a(z) {{inputs}} fájlokat animált GIF-ekké alakítja. {{gifAbout}} {{reason}}',
    'intro.hubGif.gifAbout': 'A GIF képkockánként 256 színre van korlátozva, ezért látszanak benne sávosnak a fényképek, viszont animálódik és beágyazva magától elindul szinte mindenhol az interneten.',
    'intro.compress': '{{about}} Ez az eszköz kisebb fájlmérettel kódolja újra a(z) {{fn}} fájlodat anélkül, hogy formátumot váltana, tehát amit letöltesz, továbbra is közönséges {{fn}}, ami pontosan ott nyílik meg, ahol az eredeti is megnyílt. {{reason}}{{extra}}',
    'intro.compress.lossless': ' Mivel a(z) {{fn}} veszteségmentes, a megtakarítás nagyobb része okosabb kódolásból és szűkített színpalettából jön, nem részletek eldobásából.',
    'intro.soon': '{{reason}} Ez az eszköz még nem üzemel — most készül, és amint kész lesz, itt fog megjelenni.',
    'intro.lead.pdf-merge': 'Az egyesítés több PDF-et fűz egyetlen fájlba, az általad választott sorrendben, anélkül hogy újrarajzolná az oldalakat — a szöveg kijelölhető marad, a képek pedig megtartják eredeti minőségüket. A PDF rögzített tördelésű formátum: minden karakter, vonal és kép pontos helyét eltárolja, ezért néz ki mindenhol azonosan, viszont kényelmetlen szerkeszteni.',
    'intro.lead.pdf-split': 'A szétbontás kiveszi a megnevezett oldalakat egy PDF-ből, és új dokumentumként menti őket, az eredetit érintetlenül hagyva. A PDF rögzített tördelésű formátum: minden karakter, vonal és kép pontos helyét eltárolja, ezért néz ki mindenhol azonosan, viszont kényelmetlen szerkeszteni.',
    'intro.lead.pdf-compress': 'Egy PDF tömörítése újrakódolja a benne lévő képeket, és kitakarítja a felesleges beágyazott adatokat, márpedig egy nagy PDF mérete szinte teljes egészében ott lakik. A szöveg és a vektorgrafika élesen marad.',
    'intro.lead.pdf-compress-ai': 'Ez az eszköz tömörítés előtt megnézi, mi van a PDF-ben, így a fényképszerű képek, a síkgrafika és a csak szöveget tartalmazó oldalak mindegyike úgy kezelhető, ahogy a legtöbb helyet spórolja, láthatóan rontás nélkül.',
    'intro.lead.pdf-rotate': 'A forgatás megváltoztatja a PDF tájolásjelzőjét és oldalgeometriáját, hogy az oldalak a helyes irányban jelenjenek meg és nyomtatódjanak. Semmit nem rajzol újra, tehát nem vész el minőség.',
    'intro.lead.pdf-protect': 'Egy PDF védelme titkosítja a tartalmát, hogy az általad megadott jelszó nélkül ne lehessen megnyitni. A titkosítás magára a fájlra vonatkozik, nem egy köré húzott burokra.',
    'intro.lead.pdf-unlock': 'A feloldás eltávolítja a jelszót és a használati korlátozásokat egy olyan PDF-ből, amelynek a jelszavát már ismered, hogy újra a szokásos módon lehessen megnyitni, nyomtatni és másolni belőle.',
    'intro.lead.metadata': 'Minden fájl hordoz magáról olyan információt, ami megnyitáskor nem látszik: a kép méretét és a fényképezőgép beállításait, a hang hosszát és bitsebességét, a videó kodekjét és képkockasebességét, a dokumentum szerzőjét és oldalszámát. Ez az eszköz beolvassa ezeket a metaadatokat, és megmutatja neked.',
    'intro.lead.ocr': 'Az optikai karakterfelismerés ránéz egy szöveget ábrázoló képre — egy beolvasásra, egy fényképre, egy szövegréteg nélküli PDF-oldalra —, és kikövetkezteti, milyen karakterek vannak rajta, így a szavak képéből olyan szavak lesznek, amikben a számítógép kereshet, amiket másolhat és szerkeszthet.',
    'intro.lead.tts': 'A szövegfelolvasás írott szövegből állít elő beszédhangot neurális hangokkal, így természetes hangzású felvételt kapsz a régebbi rendszerek lapos, robotos kimenete helyett.',
    'intro.lead.stt': 'A beszédfelismerés a kimondott hangot írott szavakká írja át. A természetes beszéddel, az akcentusokkal és a háttérzajjal sokkal jobban boldogul, mint egykor a diktálószoftverek, és olyan átiratot ad vissza, amit szerkeszthetsz.',
    'intro.lead.subtitle': 'A feliratgenerátor átírja a videóban elhangzó beszédet, és időkódokkal együtt írja ki, így szabványos feliratfájl születik, nem pusztán egy átirat.',

    'steps.convert.1.batch': 'Húzd a(z) {{fn}} fájlodat az oldal tetején lévő feltöltési területre, vagy kattints rá, és tallózz az eszközödön. Több fájlt — vagy akár egy egész mappát — is hozzáadhatsz, és egyszerre átalakíthatod mindet.',
    'steps.convert.1.single': 'Húzd a(z) {{fn}} fájlodat az oldal tetején lévő feltöltési területre, vagy kattints rá, és tallózz az eszközödön.',
    'steps.convert.2.direct': 'Válaszd a(z) {{tn}} formátumot kimenetnek, és kattints az Átalakítás gombra.',
    'steps.convert.2.dropdown': 'Válaszd a legördülő listából a(z) {{tn}} formátumot kimenetnek, és kattints az Átalakítás gombra.',
    'steps.convert.2.directMedia': 'Válaszd a(z) {{tn}} formátumot kimenetnek, szükség esetén állítsd a minőséget vagy a méretet a speciális beállításokban, majd kattints az Átalakítás gombra.',
    'steps.convert.2.dropdownMedia': 'Válaszd a legördülő listából a(z) {{tn}} formátumot kimenetnek, szükség esetén állítsd a minőséget vagy a méretet a speciális beállításokban, majd kattints az Átalakítás gombra.',
    'steps.convert.3': 'Töltsd le az elkészült {{tn}} fájlodat. A letöltési hivatkozás 24 órán át él, utána mindkét fájl automatikusan törlődik.',
    'steps.hub.1.batch': 'Húzd a fájlodat az oldal tetején lévő feltöltési területre, vagy kattints rá, és tallózz az eszközödön — a(z) {{category}}átalakító a következőket fogadja: {{inputs}}. Több fájlt — vagy akár egy egész mappát — is hozzáadhatsz, és egyszerre átalakíthatod mindet.',
    'steps.hub.1.single': 'Húzd a fájlodat az oldal tetején lévő feltöltési területre, vagy kattints rá, és tallózz az eszközödön — a(z) {{category}}átalakító a következőket fogadja: {{inputs}}.',
    'steps.hub.2.direct': 'Válaszd ki a szükséges kimeneti formátumot, és kattints az Átalakítás gombra.',
    'steps.hub.2.dropdown': 'Válaszd ki a legördülő listából a szükséges kimeneti formátumot, és kattints az Átalakítás gombra.',
    'steps.hub.2.directMedia': 'Válaszd ki a szükséges kimeneti formátumot, szükség esetén állítsd a minőséget vagy a méretet a speciális beállításokban, majd kattints az Átalakítás gombra.',
    'steps.hub.2.dropdownMedia': 'Válaszd ki a legördülő listából a szükséges kimeneti formátumot, szükség esetén állítsd a minőséget vagy a méretet a speciális beállításokban, majd kattints az Átalakítás gombra.',
    'steps.hub.3': 'Töltsd le az elkészült fájlodat. A letöltési hivatkozás 24 órán át él, utána mindkét fájl automatikusan törlődik.',
    'steps.pdf-merge.1': 'Add hozzá az összes PDF-et, amit egyesíteni szeretnél — húzd őket együtt a feltöltési területre, vagy kattints, és válaszd ki őket egymás után.',
    'steps.pdf-merge.2': 'Húzd a fájlokat abba a sorrendbe, amelyben az elkészült dokumentumban meg kell jelenniük.',
    'steps.pdf-merge.3': 'Kattints az Egyesítés gombra, és töltsd le az egyetlen, összefűzött PDF-et.',
    'steps.pdf-split.1': 'Töltsd fel azt a PDF-et, amelyikből oldalakat szeretnél kivenni.',
    'steps.pdf-split.2': 'Írd be a szükséges oldalakat vagy tartományokat az oldaltartomány mezőbe — például 1-3, 5, 7-10.',
    'steps.pdf-split.3': 'Kattints az Átalakítás gombra, és töltsd le a kivett oldalakat.',
    'steps.pdf-compress.1': 'Húzd a PDF-edet a feltöltési területre, vagy kattints, és keresd meg.',
    'steps.pdf-compress.2': 'Kattints az Átalakítás gombra — a rendszer elemzi a fájlt, és kisebb méretben kódolja újra a képeit és a beágyazott adatait.',
    'steps.pdf-compress.3': 'Töltsd le a tömörített PDF-et, és nézd meg a mellette megjelenő méretmegtakarítást.',
    'steps.pdf-rotate.1': 'Töltsd fel azt a PDF-et, amelyiknek rossz irányban állnak az oldalai.',
    'steps.pdf-rotate.2': 'Válaszd ki, mennyivel forduljanak el — 90°, 180° vagy 270°.',
    'steps.pdf-rotate.3': 'Kattints az Átalakítás gombra, és töltsd le a kijavított PDF-et.',
    'steps.pdf-protect.1': 'Töltsd fel azt a PDF-et, amelyiket védeni szeretnéd.',
    'steps.pdf-protect.2': 'Add meg a jelszót, ami a megnyitásához kelleni fog, és tegyél el belőle egy másolatot biztos helyre.',
    'steps.pdf-protect.3': 'Kattints az Átalakítás gombra, és töltsd le a titkosított PDF-et.',
    'steps.pdf-unlock.1': 'Töltsd fel a jelszóval védett PDF-et.',
    'steps.pdf-unlock.2': 'Add meg a jelenlegi jelszavát, hogy a fájlt vissza lehessen fejteni.',
    'steps.pdf-unlock.3': 'Kattints az Átalakítás gombra, és töltsd le a feloldott PDF-et.',
    'steps.metadata.1': 'Húzz bármilyen fájlt a feltöltési területre — képet, videót, hangfájlt vagy dokumentumot.',
    'steps.metadata.2': 'A rendszer megvizsgálja a fájlt, nem alakítja át, tehát semmi nem változik meg rajta.',
    'steps.metadata.3': 'Olvasd le a metaadatokat közvetlenül az oldalon: méretek, hossz, kodek, fényképezőgép-adatok, oldalszám és még sok más.',
    'steps.ocr.1': 'Töltsd fel a beolvasott PDF-et vagy a szövegről készült fényképet.',
    'steps.ocr.2': 'Válaszd ki a dokumentum nyelvét, és azt, hogy kereshető PDF-et vagy egyszerű szöveget szeretnél.',
    'steps.ocr.3': 'Kattints az Átalakítás gombra, és töltsd le az eredményt, amelyben a felismert szöveg immár kijelölhető és kereshető.',
    'steps.tts.1': 'Írd vagy illeszd be a szövegedet a mezőbe — átalakításonként legfeljebb 4096 karaktert.',
    'steps.tts.2': 'Válassz hangot, beszédtempót és kimeneti formátumot.',
    'steps.tts.3': 'Kattints az Átalakítás gombra, és töltsd le az elkészült hangfájlt.',
    'steps.stt.1': 'Töltsd fel a felvételedet, vagy vegyél fel közvetlenül a mikrofonoddal az oldalon lévő gombbal.',
    'steps.stt.2': 'Ha szeretnéd, add meg a beszélt nyelvet a pontosság javításához, és válassz TXT vagy DOCX kimenetet.',
    'steps.stt.3': 'Kattints az Átalakítás gombra, olvasd el az átiratot az oldalon, majd töltsd le.',
    'steps.subtitle.1': 'Töltsd fel a videót, amelyikhez feliratot szeretnél.',
    'steps.subtitle.2': 'Válaszd az SRT vagy a VTT formátumot, és add meg a beszélt nyelvet, ha tudod.',
    'steps.subtitle.3': 'Kattints az Átalakítás gombra, és töltsd le az időkódolt feliratfájlt, készen arra, hogy betedd a lejátszódba vagy a vágóprogramodba.',
    'steps.compress.1': 'Húzd a(z) {{fn}} képeidet a feltöltési területre, vagy kattints a tallózáshoz. Egyszerre egy egész mappát is hozzáadhatsz.',
    'steps.compress.1.gif': 'Húzd a(z) {{fn}} animációdat a feltöltési területre, vagy kattints a tallózáshoz. Egyszerre egy egész mappát is hozzáadhatsz.',
    'steps.compress.2': 'Kattints az Átalakítás gombra — a fájl kisebb méretben kódolódik újra, miközben ugyanabban a formátumban marad.',
    'steps.compress.3': 'Töltsd le az eredményt, és vesd össze az oldalon látható eredeti mérettel.',
    'steps.soon.1': 'Válaszd ki a szükséges eszközt az Eszközök oldalon — ezen az egyen kívül minden működik már ma.',
    'steps.soon.2': 'Töltsd fel a fájlodat, és válassz kimeneti formátumot.',
    'steps.soon.3': 'Töltsd le az eredményt, vagy nézz vissza ide, amikor a dokumentumfordítás elindul.',

    'faq.cost.q.pair': 'Ingyenes a(z) {{from}} átalakítása {{to}} formátumba?',
    'faq.cost.q.tool': 'Ingyenes a(z) {{label}} használata?',
    'faq.cost.a.pair': 'Az új fiókok kapnak egy ingyenes átalakítási kreditet, tehát az első {{from}} – {{to}} átalakításod semmibe nem kerül. Utána minden átalakítás egy kreditet használ el egy kis előre fizetett csomagból — nincs előfizetés, a kreditek soha nem járnak le, és a sikertelen átalakítást nem számoljuk fel.',
    'faq.cost.a.tool': 'Az új fiókok kapnak egy ingyenes átalakítási kreditet, tehát az első fájlod semmibe nem kerül. Utána minden átalakítás egy kreditet használ el egy kis előre fizetett csomagból — nincs előfizetés, a kreditek soha nem járnak le, és a sikertelen átalakítást nem számoljuk fel.',
    'faq.cost.a.smartTts': 'Az új fiókok kapnak egy ingyenes átalakítási kreditet kipróbálásra, az intelligens funkciókat pedig használat szerint számoljuk, nem fájlonként — 1 kredit minden 1000 szövegkarakterért, felfelé kerekítve. Nincs előfizetés: a krediteket kis, előre fizetett csomagokban lehet megvenni, soha nem járnak le, és egy sikertelen átalakítás soha nem kerül semmibe.',
    'faq.cost.a.smartAv': 'Az új fiókok kapnak egy ingyenes átalakítási kreditet kipróbálásra, az intelligens funkciókat pedig használat szerint számoljuk, nem fájlonként — 1 kredit minden 5 perc hangért vagy videóért, felfelé kerekítve. Nincs előfizetés: a krediteket kis, előre fizetett csomagokban lehet megvenni, soha nem járnak le, és egy sikertelen átalakítás soha nem kerül semmibe.',
    'faq.cost.q.metadata': 'Ingyenes a Fájladatok eszköz?',
    'faq.cost.a.metadata': 'Igen. Egy fájl metaadatainak beolvasása nem átalakítás, tehát nem használ el kreditet — annyi fájlt vizsgálhatsz meg, amennyit csak akarsz. Kreditet csak akkor költesz, amikor egy eszköz tényleg új fájlt állít elő neked.',
    'faq.cost.q.soon': 'Elérhető már a(z) {{label}}?',
    'faq.cost.a.soon': 'Még nem — ez az oldal helytartó, amíg az eszköz készül, tehát ma nincs itt mit feltölteni. Az árazás ugyanazt az előre fizetett kreditmodellt fogja követni, mint az oldal többi része: nincs előfizetés, a kreditek soha nem járnak le, és a sikertelen átalakításért nem számolunk fel semmit.',

    'faq.time.q.pair': 'Mennyi ideig tart a(z) {{from}} – {{to}} átalakítás?',
    'faq.time.q.tool': 'Mennyi ideig tart a(z) {{label}}?',
    'faq.time.a': '{{speed}} Rendszerint a feltöltési sebesség a szűk keresztmetszet, tehát egy nagy fájl lassú kapcsolaton tovább tart, mint maga az átalakítás.{{suffix}}',
    'faq.time.speed.image': 'A képek átalakítása a leggyorsabb — egyetlen fénykép rendesen öt másodpercen belül kész, egy egész mappa pedig nagyjából annyi ideig tart, mint maga a feltöltés.',
    'faq.time.speed.document': 'A legtöbb dokumentum néhány másodperc alatt elkészül. A nagyon hosszú fájlok — néhány száz oldal vagy egy képekkel teli beolvasás — akár egy percig is eltarthatnak.',
    'faq.time.speed.audio': 'Egy szokásos szám néhány másodperc alatt átalakul. Egy teljes hosszúságú felvétel, például egy előadás vagy egy podcastrész, rendesen jóval egy percen belül végez, és ennek nagy része a feltöltés.',
    'faq.time.speed.video': 'A videó a leglassabb kategória, mert minden képkockát újra kell kódolni. Egy rövid klip másodpercekig tart, míg egy hosszú, nagy felbontású fájl akár néhány percig is.',
    'faq.time.speed.archive': 'Az archívumok másodpercek alatt átalakulnak, bár egy nagy tovább tart, mert minden benne lévő fájlt ki kell csomagolni és újra be kell csomagolni.',
    'faq.time.speed.ebook': 'Az e-könyvek gyorsan mennek — egy teljes regény rendesen néhány másodperc alatt átalakul.',
    'faq.time.speed.subtitle': 'Az átírás nagyjából néhány másodperc percenkénti hangtempóban halad, tehát egy tízperces videó rendesen jóval egy percen belül feliratot kap.',
    'faq.time.suffix.standard': ' A 200 MB-ig terjedő fájlokat fogadjuk.',
    'faq.time.suffix.smart': ' Az intelligens funkciók 25 MB-ig fogadnak fájlokat; a szokásos átalakítások 200 MB-ig.',
    'faq.time.q.metadata': 'Mennyi ideig tart beolvasni egy fájl metaadatait?',
    'faq.time.a.metadata': 'Egy-két másodpercig, amint a fájl feltöltődött. Semmit nem alakítunk át és nem kódolunk újra — a fejléceket elemezzük, az eredményt pedig egyenesen az oldalra írjuk —, tehát a várakozás lényegében maga a feltöltés.',
    'faq.time.q.soon': 'Kerül majd többe?',
    'faq.time.a.soon': 'Ugyanazokat a krediteket fogja használni, mint az oldal minden más része. Nincs külön csomag vagy előfizetés, amire fel kellene iratkozni, és a fiókodon már meglévő kreditek attól a pillanattól működni fognak vele, amint elindul.',

    'faq.safety.q.pair': 'Biztonságos feltölteni a(z) {{from}} fájlomat?',
    'faq.safety.q.tool': 'Biztonságban van a fájlom?',
    'faq.safety.a.pair': 'A fájlok titkosított TLS-kapcsolaton utaznak, és semmi másra nem használjuk őket, mint arra az átalakításra, amit kértél. Az eredeti {{from}} fájlodat és az általunk visszaadott {{to}} fájlt is 24 órán belül automatikusan töröljük — véglegesen, biztonsági mentés megőrzése nélkül —, a tartalmat pedig soha nem olvassuk, nem elemezzük és nem osztjuk meg. A szolgáltatást Németországból üzemeltetjük, a GDPR hatálya alatt.',
    'faq.safety.a.tool': 'A fájlok titkosított TLS-kapcsolaton utaznak, és semmi másra nem használjuk őket, mint arra az átalakításra, amit kértél. Az eredeti fájlodat és az általunk visszaadott eredményt is 24 órán belül automatikusan töröljük — véglegesen, biztonsági mentés megőrzése nélkül —, a tartalmat pedig soha nem olvassuk, nem elemezzük és nem osztjuk meg. A szolgáltatást Németországból üzemeltetjük, a GDPR hatálya alatt.',

    'quality.vectorRaster.q': 'Éles marad a(z) {{fn}} fájlom {{tn}} formátumban?',
    'quality.vectorRaster.a': 'Addig a méretig, amekkorára exportálod, igen. A(z) {{fn}} alakzatokat tárol képpontok helyett, ezért végtelenül nagyítható, egy {{tn}} viszont rögzített képpontrács, és elmosódik, ha később ezen a rácson túl nagyítják. Állítsd be a speciális beállításokban azt a szélességet és magasságot, amire tényleg szükséged van, még az átalakítás előtt — a megjelenítési méret két- vagy háromszorosára exportálás a szokásos trükk a nagy képpontsűrűségű képernyőkhöz. Őrizd meg az eredeti {{fn}} fájlt: az marad a mesterpéldány, amiből bármilyen felbontásban újra exportálhatsz.',
    'quality.docToTxt.q': 'Elveszítem a formázást, ha a(z) {{fn}} fájlt {{tn}} formátumba alakítom?',
    'quality.docToTxt.a': 'Igen, és szándékosan — egy {{tn}} fájl karaktereket tartalmaz, semmi mást. A betűtípusok, színek, képek, táblázatok, hasábok és oldaltörések mind elmaradnak; amit visszakapsz, az a dokumentum olvasható szövege olvasási sorrendben. Pontosan ezt akarod kereséshez, szkriptekhez vagy ahhoz, hogy a szöveget egy másik programnak add, és pontosan ezt nem akarod, ha reménykedtél a látvány megőrzésében. Jegyezd meg: egy {{fn}}, ami valójában beolvasott kép, egyáltalán nem tartalmaz kinyerhető szöveget — inkább futtasd át az OCR-eszközön.',
    'quality.docToSheet.q': 'Mennyire pontosan nyerhetők ki a táblázatok a(z) {{fn}} fájlból?',
    'quality.docToSheet.a': 'A tiszta, vonalazott, egyenletes hasábú táblázatok — kivonatok, számlák, exportált jelentések — megbízhatóan átjönnek, és minden érték a saját cellájába kerül, hogy összegezni és rendezni tudd. A látható szegély nélküli táblázatok, a több soron átnyúló cellák vagy az oldaltörés által kettévágott számok azok az esetek, amiket utána érdemes szemmel ellenőrizni. A(z) {{fn}} pozíciókat tárol, nem táblázatszerkezetet, így az átalakításnak kell kikövetkeztetnie, hol ér véget az egyik hasáb és hol kezdődik a következő.',
    'quality.docToReflow.q': 'Túléli a tördelés a(z) {{fn}} – {{tn}} átalakítást?',
    'quality.docToReflow.a': 'Nem pontosan, és épp ez a lényeg. A(z) {{fn}} rögzített oldalkoordinátákhoz szegezi a szöveget; a(z) {{tn}} újratördeli az olvasó képernyőjéhez és betűméretéhez, így a rögzített oldalszámokat, élőfejeket, élőlábakat és többhasábos tördeléseket inkább újraértelmezi, mint reprodukálja. A kenyérszöveg, a címsorok, a bekezdések sorrendje és a képek jól átjönnek. A javarészt folyószövegből álló dokumentumok gyönyörűen átalakulnak; az erősen megtervezett oldalakat, az űrlapokat és az összetett táblázatokat érdemes utána megnézni.',
    'quality.docToFixed.q': 'Megmarad a formázásom a(z) {{tn}} fájlban?',
    'quality.docToFixed.a': 'Igen — ez az irány a biztonságos. A(z) {{tn}} a véglegesen kirajzolt oldalt rögzíti, tehát a betűtípusok, térközök, táblázatok, képek és oldaltörések pontosan úgy fagynak be, ahogy megtördelték őket, és minden eszközön és nyomtatón ugyanúgy néznek ki. Ez egyben az ára is: az eredmény már nem szerkeszthető szabadon, márpedig rendszerint épp ezért alakítanak egy dokumentumot {{tn}} formátumba, mielőtt elküldenék.',
    'quality.docToEditable.q': 'Mennyire pontos a(z) {{fn}} – {{tn}} átalakítás?',
    'quality.docToEditable.a': 'A szöveg, a címsorok, a listák, a képek és az egyszerű táblázatok megbízhatóan átjönnek, és teljesen szerkeszthetők maradnak. Mivel a(z) {{fn}} pozíciókat tárol, nem szerkezetet, az átalakításnak újra kell építenie ezt a szerkezetet, így az erősen megtervezett oldalak — több hasáb, képek körül futó szöveg, összetett egymásba ágyazott táblázatok — utána igényelhetnek némi rendezgetést. Ha a PDF olyan beolvasás, amiben egyáltalán nincs szövegréteg, inkább az OCR-eszközt használd: az a képen lévő karaktereket ismeri fel ahelyett, hogy olyan szöveget keresne, ami nincs ott.',
    'quality.docGeneric.q': 'Elveszítek valamit, ha a(z) {{fn}} fájlt {{tn}} formátumba alakítom?',
    'quality.docGeneric.a': 'A szavak, a címsorok, a listák és a képek sértetlenül átjönnek. A(z) {{tn}} más formázási készlettel rendelkezik, mint a(z) {{fn}}, így a nagyon egyedi megjelenés útközben egyszerűsödhet, de maga a tartalom megmarad.',
    'quality.archive.q': 'Megváltoznak a(z) {{fn}} archívumomban lévő fájlok?',
    'quality.archive.a': 'Nem. Az archívumformátumok veszteségmentes tárolók: a(z) {{fn}} kicsomagolódik, és ugyanazok a fájlok csomagolódnak újra {{tn}} formátumba, bájtról bájtra. Csak a tömörítési eljárás és a tároló változik. Ami viszont megváltozik, az magának az archívumnak a mérete — {{clause}}.',
    'quality.archive.clause.to7z': 'a 7Z az LZMA-tömörítésnek köszönhetően általában kisebb archívumot ad, mint a ZIP',
    'quality.archive.clause.toZip': 'a ZIP rendszerint kicsit nagyobb lesz, mint a 7Z vagy a RAR, és ez az ára annak, hogy mindenhol megnyitható külön szoftver nélkül',
    'quality.archive.clause.other': 'az új formátum másképp tömörít, így a fájlméret bármelyik irányba elmozdulhat',
    'quality.imageToDoc.q': 'Veszítenek a fényképeim a minőségükből a(z) {{tn}} fájlon belül?',
    'quality.imageToDoc.a': 'Nem. Minden {{fn}} kép úgy, ahogy van, kerül a(z) {{tn}} fájlba, oldalanként egy, ahelyett hogy újratömörítenénk, tehát amit a dokumentumban látsz, az az, ami a fényképezőgépből kijött. A(z) {{tn}} nagyjából akkora lesz, mint a képek együtt, amit érdemes tudni, mielőtt e-mailben elküldenéd — futtasd át az eredményt a PDF tömörítése eszközön, ha kisebbnek kell lennie.',
    'quality.toGif.q': 'Miért néz ki rosszabbul a GIF-em az eredeti {{fn}} fájlnál?',
    'quality.toGif.a': 'Mert a GIF képkockánként 256 színre korlátozott. Egy videó vagy fénykép milliókat tartalmaz, így a kódolónak palettát kell választania, és minden mást közelítenie, ami sávosodásként jelenik meg az átmenetekben és az égen. A GIF ráadásul egyáltalán nem visz hangsávot. Mindkettő a formátum sajátja, nem az átalakításé — tartsd rövidre a klipet, és ha a színvesztés többet nyom a latban, mint a beágyazott automatikus lejátszás, egy MP4 sokkal jobban fog kinézni kisebb méretben.',
    'quality.lossyToLossless.q': 'Javul a minőség, ha a(z) {{fn}} fájlt {{tn}} formátumba alakítom?',
    'quality.lossyToLossless.a': 'Nem — és ez messze a leggyakoribb félreértés ezzel az átalakítással kapcsolatban. A(z) {{fn}} veszteséges: azok a részletek, amiket a kódolója eldobott, véglegesen odavannak, és semmi nem tudja őket visszaállítani. Amit a(z) {{tn}} ad, az egy veszteségmentes tároló a megmaradt anyagnak, így a fájl megszűnik romlani minden további mentéssel vagy szerkesztéssel. Ez tényleg hasznos, amikor arra készülsz, hogy {{clause}}, de nem hozza vissza a már elveszett minőséget.',
    'quality.lossyToLossless.edit.audio': 'szerkeszd, masterizáld vagy feldolgozd a hangot',
    'quality.lossyToLossless.edit.image': 'szerkeszd, retusáld vagy komponáld a képet',
    'quality.losslessToLossy.q': 'Veszítek minőséget, ha a(z) {{fn}} fájlt {{tn}} formátumba alakítom?',
    'quality.losslessToLossy.a.audio': 'Valamennyit, és szándékosan — így lesz kisebb a fájl. A(z) {{tn}} veszteséges, tehát a kódoló eldobja azt az információt, amit a legkevésbé észrevehetőnek ítél. Ésszerű beállítások mellett a különbséget nagyon nehéz füllel elkapni, és a speciális beállításokban feljebb vihetted a bitsebességet, ha inkább a méretet adnád a hűségért. Őrizd meg az eredeti {{fn}} fájlodat: az marad a mesterpéldány, és a(z) {{tn}} későbbi újrakódolása mélyítené a veszteséget.',
    'quality.losslessToLossy.a.visual': 'Valamennyit, és szándékosan — így lesz kisebb a fájl. A(z) {{tn}} veszteséges, tehát a kódoló eldobja azt az információt, amit a legkevésbé észrevehetőnek ítél. Ésszerű beállítások mellett a különbséget nagyon nehéz szemmel elkapni, és a speciális beállításokban feljebb vihetted a minőségértéket, ha inkább a méretet adnád a hűségért. Őrizd meg az eredeti {{fn}} fájlodat: az marad a mesterpéldány, és a(z) {{tn}} későbbi újrakódolása mélyítené a veszteséget.',
    'quality.lossyToLossy.q': 'Veszítek minőséget, ha a(z) {{fn}} fájlt {{tn}} formátumba alakítom?',
    'quality.lossyToLossy.a.audio': 'Egy keveset. Mindkét formátum veszteséges, tehát a(z) {{fn}} dekódolódik, majd {{tn}} formátumba kódolódik újra, és a veszteséges kódolás minden nemzedéke elejt egy kevés részletet. Szokásos beállítások mellett hallgatás közben a legtöbben nem veszik észre, és a speciális beállításokban feljebb viheted a bitsebességet. Amit kerülnöd kell, az ugyanannak a fájlnak az ismételt oda-vissza alakítása — épp ez teszi a veszteséget hallhatóvá.',
    'quality.lossyToLossy.a.visual': 'Egy keveset. Mindkét formátum veszteséges, tehát a(z) {{fn}} dekódolódik, majd {{tn}} formátumba kódolódik újra, és a veszteséges kódolás minden nemzedéke elejt egy kevés részletet. Szokásos beállítások mellett a legtöbben nem veszik észre, és a speciális beállításokban feljebb viheted a minőséget. Amit kerülnöd kell, az ugyanannak a fájlnak az ismételt oda-vissza alakítása — épp ez teszi a veszteséget láthatóvá.',
    'quality.losslessToLossless.q': 'Veszítek minőséget, ha a(z) {{fn}} fájlt {{tn}} formátumba alakítom?',
    'quality.losslessToLossless.a.plain': 'Nem. A(z) {{fn}} és a(z) {{tn}} is veszteségmentes, tehát {{unit}} pontosan megmarad, és az eredmény azonos az eredetivel. Csak a fájlméret változik. Később bármikor visszaalakíthatod bárminemű romlás nélkül.',
    'quality.losslessToLossless.a.bulky': 'Nem. A(z) {{fn}} és a(z) {{tn}} is veszteségmentes, tehát {{unit}} pontosan megmarad, és az eredmény azonos az eredetivel. Csak a fájlméret változik, rendszerint drámaian lefelé, mert a(z) {{fn}} gyakorlatilag tömörítetlenül tárolja az adatait. Később bármikor visszaalakíthatod bárminemű romlás nélkül.',
    'quality.fallback.q': 'Veszítek minőséget, ha a(z) {{fn}} fájlt {{tn}} formátumba alakítom?',
    'quality.fallback.a': 'Szokásos fájloknál az eredmény látványban és működésben egyenértékű az eredetivel. Ahol a két formátum mást tud, az átalakítás mindent megőriz, amit a(z) {{tn}} képes megjeleníteni. A speciális beállításokban feljebb viheted a minőséget, ha az alapértelmezett kompromisszum nem az, amit szeretnél.',

    'relation.uncompressed.q': 'Miért ekkora a(z) {{tn}} fájl a(z) {{fn}} fájlhoz képest?',
    'relation.uncompressed.a': 'Mert a(z) {{tn}} tömörítetlen. A(z) {{fn}} úgy zsugorítja a hangot, hogy adatokat dob el, és hatékonyan kódolja a maradékot; a(z) {{tn}} minden mintát teljes méretben ír ki, ami nagyjából 10 MB-ot tesz ki percenként CD-minőségű sztereóból. A tízszeres növekedés normális és várható — ez az ára egy olyan fájlnak, amit a vágószoftverek úgy tudnak feldolgozni, hogy előbb semmit nem kell dekódolniuk. Ha veszteségmentes hangot szeretnél nagyjából fele akkorán, inkább FLAC formátumba alakítsd.',
    'relation.extractAudio.q': 'Megmarad ilyenkor a videó, vagy csak a hang?',
    'relation.extractAudio.a': 'Csak a hang. A hangsávot kivesszük a(z) {{fn}} fájlból, és {{tn}} formátumban mentjük; a képsáv eldobódik, és ezért lesz az eredmény az eredeti méret töredéke. Magát a hangot nem vesszük fel újra, tehát megtartja azt a minőséget, amivel a(z) {{fn}} fájlon belül rendelkezett — alacsony bitsebességű videóból nem lehet magas bitsebességű hangot kinyerni.',
    'relation.videoContainer.q': 'Le fog játszódni a(z) {{tn}} fájlom telefonokon, tévéken és a közösségi médiában?',
    'relation.videoContainer.a.mp4': 'Pontosan erre való ez az átalakítás. Az MP4 H.264 videóval áll a legközelebb egy egyetemes videoformátumhoz: az iPhone-ok, az androidos telefonok, az okostévék, minden böngésző, az Instagram, a YouTube, a TikTok és minden elterjedt vágóprogram elfogadja külön kodek nélkül. A(z) {{fn}} volt az a formátum, ami gondot okozott; az MP4 az, ami nem okoz.',
    'relation.videoContainer.a.other': 'A(z) {{tn}} szakosodottabb, mint az MP4. {{note}} Ha a célod egyszerűen az, hogy „mindenhol lejátszódjon”, az MP4 a biztonságosabb választás — a(z) {{tn}} akkor jön szóba, ha egy konkrét program vagy készülék kérte.',
    'relation.alphaLost.q': 'Mi történik az átlátszósággal, amikor a(z) {{fn}} {{tn}} formátumba kerül?',
    'relation.alphaLost.a': 'A(z) {{tn}} formátumnak nincs alfacsatornája, tehát az átlátszó területek nem vihetők át — az átalakítás során egyszínű háttérrel (alapértelmezés szerint fehérrel) töltődnek ki. Ha az átlátszó háttér valódi szerepet játszik a tervedben, inkább PNG vagy WebP formátumba alakíts, mert mindkettő megőrzi. Ha a kép olyan fénykép, amin egyáltalán nincs átlátszóság, ez semmiféle különbséget nem jelent.',
    'relation.alphaGained.q': 'Átlátszóvá teszi a hátteret, ha a(z) {{fn}} {{tn}} formátumba kerül?',
    'relation.alphaGained.a': 'Nem — és sokan bedőlnek ennek. A(z) {{tn}} támogatja az átlátszóságot, de egy {{fn}} fájlban nincs átvihető átlátszósági információ, tehát a háttér pontosan olyan marad, amilyen volt. Amit az átalakítás ad, az egy olyan fájl, amely képes átlátszóságot hordozni, amint egy képszerkesztőben kivágod a hátteret, ráadásul veszteségmentes képpontokkal, amik munka közben nem romlanak.',
    'relation.reflow.q': 'Működni fog a(z) {{tn}} az e-könyv-olvasómon?',
    'relation.reflow.a.epub': 'Az EPUB-ot olvassa az Apple Books, a Kobo, a Google Play Könyvek, a Calibre és gyakorlatilag minden e-könyv-olvasó a Kindle kivételével, ami MOBI-t vagy AZW3-at kér (a Kindle mostanában e-mailben EPUB-ot is elfogad). Mivel a szöveg újratördelődik, a készüléken átállíthatod a betűméretet anélkül, hogy oldalra kellene görgetned — és eleve pontosan ezért alakít az ember át egy {{fn}} fájlt.',
    'relation.reflow.a.kindle': 'A(z) {{tn}} formátumot azok a Kindle-készülékek és -alkalmazások olvassák, amelyekhez tervezték. Mivel a szöveg újratördelődik, a készüléken átállíthatod a betűméretet anélkül, hogy oldalra kellene görgetned — és eleve pontosan ezért alakít az ember át egy {{fn}} fájlt.',

    'compatibility.q': 'Mivel lehet utána megnyitni a(z) {{tn}} fájlt?',
    'compatibility.a': '{{note}} Magához az átalakításhoz semmit nem kell telepíteni — a kiszolgálóinkon fut, az elkészült {{tn}} pedig visszatér a böngésződbe, készen a megnyitásra, szerkesztésre vagy továbbküldésre. Az eredeti {{fn}} fájlodat soha nem módosítjuk; mindig csak egy új fájlt adunk vissza.',
    'compatibility.noteFallback': 'A(z) {{tn}} széles körben támogatott.',

    'shapeFaq.pdf-merge.q1': 'Rontja az egyesítés a PDF-jeim minőségét?',
    'shapeFaq.pdf-merge.a1': 'Nem. Az oldalak pontosan úgy másolódnak az új dokumentumba, ahogy vannak, ahelyett hogy újrarajzolódnának, tehát a szöveg kijelölhető marad, a képek pedig megtartják eredeti felbontásukat. Az egyesített fájl nagyjából akkora, mint az eredetik együtt — futtasd át utána a PDF tömörítése eszközön, ha ez számít.',
    'shapeFaq.pdf-merge.q2': 'Hány PDF-et egyesíthetek egyszerre, és számít a sorrend?',
    'shapeFaq.pdf-merge.a2': 'Egyszerre annyi fájlt adhatsz hozzá, amennyi kell, és a sorrend nagyon is számít: az elkészült dokumentum a listában látható sorrendet követi, amit egyesítés előtt húzással átrendezhetsz. Előbb állítsd be a sorrendet, aztán egyesíts — így gyorsabb, mint utólag javítani.',
    'shapeFaq.pdf-split.q1': 'Hogyan választom ki, mely oldalak kerüljenek kivételre?',
    'shapeFaq.pdf-split.a1': 'Írd be őket az oldaltartomány mezőbe vesszőkkel és kötőjelekkel: az „1-3, 5, 7-10” az egytől háromig terjedő oldalakat, az ötödik oldalt és a héttől tízig terjedő oldalakat adja egyetlen kimeneti dokumentumban. A számok a PDF saját oldalaira vonatkoznak, egytől számolva, ami nem mindig azonos az oldalra nyomtatott számmal.',
    'shapeFaq.pdf-split.q2': 'Megváltoztatja a szétbontás az eredeti PDF-et?',
    'shapeFaq.pdf-split.a2': 'Nem. A feltöltött fájlodat soha nem módosítjuk — a kivett oldalak új dokumentumba íródnak, az eredeti pedig érintetlen marad, majd az eredménnyel együtt 24 órán belül törlődik a kiszolgálóinkról.',
    'shapeFaq.pdf-compress.q1': 'Mennyivel lesz kisebb a PDF-em?',
    'shapeFaq.pdf-compress.a1': 'Ez teljes egészében attól függ, mi van benne. A beolvasások vagy fényképek uralta PDF-ek gyakran 50–90%-kal zsugorodnak, mert szinte a teljes méret ott lakik. Egy csak szöveget tartalmazó PDF már eleve tömör, és talán alig változik. A szöveg és a vektorgrafika mindkét esetben éles marad — a megtakarítás a képek újrakódolásából és a felesleges beágyazott adatok elhagyásából jön.',
    'shapeFaq.pdf-compress.q2': 'Kijelölhető és kereshető marad a szöveg?',
    'shapeFaq.pdf-compress.a2': 'Igen. A tömörítés a beágyazott képeken és a felesleges belső adatokon dolgozik; a szövegréteg, a betűtípusok, a hivatkozások és a könyvjelzők érintetlenek maradnak, tehát a tömörített fájlban is pontosan úgy kereshetsz, jelölhetsz ki és másolhatsz, mint korábban.',
    'shapeFaq.pdf-compress-ai.q1': 'Miben más ez, mint a szokásos PDF-tömörítés?',
    'shapeFaq.pdf-compress-ai.a1': 'A szokásos tömörítés egyetlen beállítást alkalmaz az egész fájlra. Ez az eszköz előbb megnézi, mit tartalmaz valójában minden egyes oldal, így a fényképszerű képeket, a sík ábrákat és a csak szöveget tartalmazó oldalakat mind úgy kezeli, ahogy a legtöbb helyet spórolja, láthatóan rontás nélkül. Vegyes dokumentumoknál ez rendszerint kisebb fájlt jelent azonos érzékelt minőség mellett.',
    'shapeFaq.pdf-compress-ai.q2': 'Kijelölhető és kereshető marad a szöveg?',
    'shapeFaq.pdf-compress-ai.a2': 'Igen. A szövegréteg, a betűtípusok, a hivatkozások és a könyvjelzők megmaradnak — csak a beágyazott képek és a felesleges belső adatok kódolódnak újra, tehát a tömörített PDF teljesen kereshető és másolható marad.',
    'shapeFaq.pdf-rotate.q1': 'Vész el minőség, ha egy PDF-et elforgatnak?',
    'shapeFaq.pdf-rotate.a1': 'Egyáltalán nem. A forgatás a fájlban rögzített oldalgeometriát változtatja meg ahelyett, hogy bármit újrarajzolna, tehát a szöveg vektorélesen marad, a képek érintetlenek, a fájlméret pedig alig mozdul. Később újra forgathatsz, mindenféle halmozódó kár nélkül.',
    'shapeFaq.pdf-rotate.q2': 'Elforgathatom csak az oldalak egy részét?',
    'shapeFaq.pdf-rotate.a2': 'A választott forgatás — 90°, 180° vagy 270° — a dokumentumra vonatkozik. Ha különböző oldalak különböző irányba állnak rosszul, a szokásos megoldás az, hogy szétbontod a PDF-et, minden részt a neki kellő szöggel elforgatsz, majd az eredményeket a PDF egyesítése eszközzel újra összefűzöd.',
    'shapeFaq.pdf-protect.q1': 'Mi történik, ha elfelejtem a jelszót?',
    'shapeFaq.pdf-protect.a1': 'A fájl nem lesz megnyitható. A titkosítás magára a PDF-re vonatkozik, tehát nincs visszaállító hivatkozás és nincs hátsó ajtó — sem neked, sem nekünk. Tedd el a jelszót biztos helyre, mielőtt továbbküldenéd a dokumentumot, és a fájltól eltérő csatornán küldd el.',
    'shapeFaq.pdf-protect.q2': 'Mennyire erős a védelem?',
    'shapeFaq.pdf-protect.a2': 'A PDF a formátumba épített iparági szabvánnyal titkosítódik, tehát a tartalmát jelszó nélkül egyetlen szabványkövető olvasó sem tudja elolvasni. A gyakorlati gyenge pont sosem az algoritmus, hanem maga a jelszó — a rövidet vagy kézenfekvőt gyorsan kitalálják, tehát bármi igazán bizalmashoz hosszút használj.',
    'shapeFaq.pdf-unlock.q1': 'Eltávolít ez egy olyan jelszót, amit nem ismerek?',
    'shapeFaq.pdf-unlock.a1': 'Nem. Meg kell adnod a jelenlegi jelszót; az eszköz azzal fejti vissza a fájlt, nem töri fel a titkosítást. Olyan dokumentumokhoz készült, amelyek a tieid, vagy amelyeket jogosult vagy megnyitni — például a saját bankod kivonatához —, ahol a korlátozás egyszerűen csak útban van.',
    'shapeFaq.pdf-unlock.q2': 'Mit tehetek utána a fájllal?',
    'shapeFaq.pdf-unlock.a2': 'Mindent, amit a védelem tiltott: megnyithatod kérdés nélkül, kinyomtathatod, szöveget másolhatsz belőle és más szoftverben szerkesztheted. Maga az oldalak tartalma változatlan — csak a titkosítási réteg és annak használati korlátozásai kerülnek le.',
    'shapeFaq.metadata.q1': 'Megváltoztatja ez bármilyen módon a fájlomat?',
    'shapeFaq.metadata.a1': 'Nem. A fájlt beolvassuk, nem alakítjuk át — semmit nem írunk vissza, és a képernyőn megjelenő információn kívül semmi új nem keletkezik. Ez a legbiztonságosabb eszköz itt ahhoz, hogy ráirányítsd egy fájlra, amiben nem vagy biztos.',
    'shapeFaq.metadata.q2': 'Milyen információt fogok látni?',
    'shapeFaq.metadata.a2': 'A fájltól függ. A képek méreteket, színmélységet és EXIF-adatokat mutatnak, például fényképezőgép-típust, objektívet, expozíciót és — ha a gép rögzítette — GPS-koordinátákat. A hang hosszt, bitsebességet, mintavételi frekvenciát és csatornaszámot mutat. A videó ehhez kodeket, felbontást és képkockasebességet tesz. A dokumentumok oldalszámot, szerzőt, előállítót és létrehozási dátumot mutatnak.',
    'shapeFaq.ocr.q1': 'Mennyire pontos a szövegfelismerés?',
    'shapeFaq.ocr.a1': 'Egy tiszta, egyenes, ésszerű felbontású beolvasás nyomtatott szövegről nagyon pontosan felismerhető. A pontosság romlik ferde vagy homályos oldalaknál, gyenge kontrasztú fényképeknél, szokatlan betűtípusoknál és kézírásnál. A helyes nyelv kiválasztása számít, mert a felismerés ezzel oldja fel a többértelmű karaktereket.',
    'shapeFaq.ocr.q2': 'Mi a különbség a kereshető PDF és az egyszerű szöveges kimenet között?',
    'shapeFaq.ocr.a2': 'A kereshető PDF pontosan úgy tartja meg az eredeti oldalképet, ahogy kinéz, és alá tesz egy láthatatlan szövegréteget, tehát a dokumentum változatlannak tűnik, de most már kereshető és másolható belőle — archiváláshoz ezt akarod. Az egyszerű szöveg eldobja a tördelést, és csak a szavakat adja, márpedig szerkesztéshez, szkriptekhez vagy másik programnak való átadáshoz épp ezt akarod.',
    'shapeFaq.tts.q1': 'Mennyire természetesen szólnak a hangok?',
    'shapeFaq.tts.a1': 'Ezek neurális hangok, nem a régebbi, összeragasztott beszédszintézis, tehát mondatszintű hanglejtést és természetes szüneteket hordoznak ahelyett, hogy szóról szóra olvasnának. Hat hang érhető el, a semlegestől a melegen át a tekintélyesig, a beszédtempó pedig állítható. A központozás többet számít, mint gondolnánk: a vesszők és a pontok alakítják a tagolást, tehát a jól központozott szöveg érezhetően jobban szólal meg.',
    'shapeFaq.tts.q2': 'Mennyi szöveget alakíthatok át egyszerre?',
    'shapeFaq.tts.a2': 'Átalakításonként legfeljebb 4096 karaktert — nagyjából 600–700 szót, vagyis körülbelül öt perc beszédet. Hosszabb szövegeknél vágd el természetes helyen, például fejezet- vagy szakaszcímnél, és alakítsd át külön-külön a részeket; a hang és a tempó beállításai a futtatások között ugyanazok maradnak, így a darabok tisztán illeszkednek egymáshoz.',
    'shapeFaq.stt.q1': 'Mennyire pontos az átirat?',
    'shapeFaq.stt.a1': 'A tiszta beszéd ésszerűen csendes környezetben nagyon pontosan átírható, akcentusok széles skáláján is. A pontosság romlik erős háttérzajnál, amikor többen beszélnek egymás szavába, illetve nagyon szakmai zsargonnál és tulajdonneveknél. A beszélt nyelv megadása az automatikus felismerés helyett érezhetően segít.',
    'shapeFaq.stt.q2': 'Felvehetek közvetlenül a mikrofonommal?',
    'shapeFaq.stt.a2': 'Igen — az oldalon lévő felvevő közvetlenül a böngészőben rögzíti a hangot, ami gyakran gyorsabb, mint előbb felvevő alkalmazást keresni. A böngésződ első alkalommal engedélyt fog kérni a mikrofonhoz. Feltölthetsz meglévő fájlt is, az átirat pedig megjelenik az oldalon, hogy elolvashasd, mielőtt TXT vagy DOCX formátumban letöltenéd.',
    'shapeFaq.subtitle.q1': 'Mennyire pontosak a létrehozott feliratok?',
    'shapeFaq.subtitle.a1': 'A tiszta beszéd nagyon pontosan átírható, akcentussal is. A háttérzene, az egymás szavába vágás és a szakkifejezések azok a helyek, ahol a hibák becsúsznak, és a beszélt nyelv megadása az automatikus felismerés helyett segít. A kimenet egyszerű szöveges feliratfájl, tehát egy-egy szó javítása másodpercek bármelyik szövegszerkesztőben.',
    'shapeFaq.subtitle.q2': 'SRT-t vagy VTT-t válasszak?',
    'shapeFaq.subtitle.a2': 'Az SRT a biztonságosabb alapértelmezés: a YouTube, a Vimeo, a Premiere, a Final Cut, a VLC és gyakorlatilag minden lejátszó elfogadja. Akkor válaszd a VTT-t, ha a felirat egy weboldal HTML5-videolejátszójába megy, mivel a WebVTT az a formátum, amit a böngésző saját feliratsávja vár, és olyan stílusozást és pozicionálást támogat, amit az SRT nem tud kifejezni.',
    'shapeFaq.soon.q1': 'Mikor lesz ez elérhető?',
    'shapeFaq.soon.a1': 'Aktívan fejlesztjük. Az eszköz itt fog megjelenni, és amint kész lesz, elkezd fájlokat fogadni — a te oldaladon semmit nem kell telepíteni vagy bekapcsolni.',
    'shapeFaq.soon.q2': 'Mit használhatok addig?',
    'shapeFaq.soon.a2': 'Az átalakító többi része teljesen elérhető: a dokumentumok, a képek, a hang, a videó, az archívumok, a GIF-ek és a PDF-eszköztár mind működnek már ma, ahogy az OCR-hez, az átíráshoz és a feliratozáshoz való intelligens funkciók is.',
    'shapeFaq.compress.q1': 'A tömörített fájl továbbra is {{fn}} lesz?',
    'shapeFaq.compress.a1': 'Igen — a formátum nem változik, csak a méret. Amit letöltesz, az közönséges {{fn}}, ami mindenhol megnyílik, ahol az eredeti is megnyílt.{{alpha}} Hogy mennyit spórolsz, a kiindulási anyagtól függ: {{source}}.',
    'shapeFaq.compress.alpha': ' Az átlátszóság és az animáció megmarad.',
    'shapeFaq.compress.source.png': 'a képernyőképek és a sík felületi grafika drámaian tömöríthetők, míg a PNG-ként mentett fényképek kevesebbet adnak',
    'shapeFaq.compress.source.gif': 'a hosszú animációk és a mozgalmas felvételek tömöríthetők a legjobban, mert több az eltávolítható ismétlődés',
    'shapeFaq.compress.source.other': 'a fényképek jól tömöríthetők, míg a már eleve erősen tömörített képeknek kevesebb maradt adni',
    'shapeFaq.compress.q2': 'Mennyivel lesz kisebb a fájl?',
    'shapeFaq.compress.a2': 'Rendszerint az eredeti harmada és tizede között, teljes egészében attól függően, mit tartalmaz a fájl és hogyan mentették eredetileg. Amint az átalakítás befejeződik, az oldal egymás mellett mutatja az előtte és utána méretet, tehát a valódi megtakarítást látod ahelyett, hogy találgatnál.',
    'shapeFaq.hub.q1': 'Mely formátumok között alakíthatok át?',
    'shapeFaq.hub.a1': 'Bemenet: {{inputs}}. Kimenet: {{outputs}}. Bármelyik bemenet mehet bármelyik kimenetre, tehát nem kell külön oldalt keresned minden kombinációhoz — válaszd ki a fájlt, válaszd ki a célformátumot, alakítsd át.',
    'shapeFaq.hub.q2': 'Veszítek minőséget?',
    'shapeFaq.hub.a2': 'A pártól függ. Veszteségmentes formátumba lépve minden megmarad, de nagyobb fájl születik; tömörített formátumba lépve a rendszer szándékosan eldob adatokat a méretért cserébe, a speciális beállításokban pedig te döntöd el, hol állsz ezen a kompromisszumon. Két tömörített formátum közti átalakítás minden alkalommal elejt egy kevés részletet, tehát érdemes megtartani az eredetit mesterpéldánynak.',
    'shapeFaq.hub-extract.q1': 'Megmarad a videó is?',
    'shapeFaq.hub-extract.a1': 'Nem — csak a hang. A hangsávot kiemeljük a videóból és külön mentjük, és ezért lesz az eredmény az eredeti fájlméret töredéke. A hangot nem vesszük fel újra, tehát megtartja azt a minőséget, amivel a videón belül már rendelkezett; alacsony bitsebességű klipből nem lehet magas bitsebességű hangot kinyerni.',
    'shapeFaq.hub-extract.q2': 'Melyik kimeneti formátumot válasszam?',
    'shapeFaq.hub-extract.a2': 'MP3-at a legnagyobb kompatibilitásért — minden telefonon, autós hangrendszeren és lejátszón lejátszódik. AAC-t vagy M4A-t, ha a cél Apple-eszköz vagy modern alkalmazás, mivel azonos bitsebességen valamivel jobban szólnak. WAV-ot vagy FLAC-et csak akkor, ha szerkeszteni fogod a hangot, mivel mindkettő veszteségmentes és ennek megfelelően testes.',
    'shapeFaq.hub-gif.q1': 'Miért néz ki a GIF rosszabbul az eredetinél?',
    'shapeFaq.hub-gif.a1': 'Mert a GIF képkockánként csak 256 színt enged, míg a videó és a fényképek milliókat tartalmaznak. A kódoló palettát választ, a többit pedig közelíti, ami sávosodásként jelenik meg az átmenetekben és az égen. A GIF ráadásul egyáltalán nem visz hangot. Mindkét korlát a formátum sajátja, nem az átalakításé.',
    'shapeFaq.hub-gif.q2': 'Miért ekkora a GIF-fájlom?',
    'shapeFaq.hub-gif.a2': 'A GIF sokkal kevésbé hatékonyan tömörít, mint a korszerű videokodekek, tehát a fájlméret gyorsan nő a hosszal, a felbontással és a képkockasebességgel. Néhány másodperc az ideális tartomány. Ha az eredmény túl nehéz, rövidítsd meg a klipet, és ha a méret többet nyom a latban, mint a beágyazott automatikus lejátszás, egy MP4 ugyanazt az animációt a méret töredékén fogja mutatni.',
  },
};
