// Italian content pack. Mirrors packs/en.js key for key — see the header there.
export default {
  lang: 'it',
  formats: {
    pdf: { about: 'Il PDF è un formato a impaginazione fissa: memorizza la posizione esatta di ogni carattere, linea e immagine, ed è per questo che un PDF appare identico su qualsiasi schermo o stampante ma risulta scomodo da modificare.', note: 'Il PDF blocca impaginazione, caratteri e layout, così il destinatario vede esattamente ciò che avete inviato.' },
    docx: { about: 'Il DOCX è il formato moderno di Microsoft Word, in cui il testo vive dentro paragrafi e stili modificabili invece di essere fissato a coordinate di pagina rigide.', note: 'Il DOCX vi restituisce paragrafi davvero modificabili, revisioni e commenti in Word, Google Docs o LibreOffice.' },
    xlsx: { about: 'L’XLSX è il formato foglio di calcolo di Excel, in cui ogni valore occupa una cella indirizzabile che si può ordinare, filtrare e usare in una formula.', note: 'Una volta che i dati sono in XLSX potete sommarli, ordinarli, incrociarli in tabelle pivot e trasformarli in grafici invece di ridigitarli.' },
    pptx: { about: 'Il PPTX salva una presentazione come diapositive separate, con caselle di testo modificabili, forme, note del relatore e transizioni.', note: 'Il PPTX vi restituisce diapositive che potete davvero rimodificare, riordinare e ripresentare.' },
    txt: { about: 'Un file TXT non è altro che caratteri — niente caratteri tipografici, niente immagini, nessuna struttura di pagina — il che lo rende minuscolo, leggibile ovunque e banale da cercare.', note: 'Il TXT toglie tutto tranne le parole, che è esattamente ciò che vogliono script, indici di ricerca ed editor di testo.' },
    html: { about: 'L’HTML è il linguaggio di marcatura del web: testo racchiuso in tag che un browser trasforma in titoli, paragrafi, collegamenti e immagini.', note: 'L’HTML si apre in qualsiasi browser e si incolla direttamente in un sito o in un CMS.' },
    rtf: { about: 'L’RTF è un formato di documento aperto basato su testo semplice che trasporta la formattazione essenziale — grassetto, corsivo, caratteri, tabelle — senza legarvi a un solo programma di videoscrittura.', note: 'L’RTF si apre in Word, Pages, LibreOffice, WordPad e praticamente in ogni programma di videoscrittura mai scritto.' },
    odt: { about: 'L’ODT è il formato testo OpenDocument usato da LibreOffice e OpenOffice, ed è uno standard ISO anziché un formato proprietario.', note: 'L’ODT è il formato nativo e pienamente modificabile di LibreOffice e OpenOffice.' },
    epub: { about: 'L’EPUB è un formato di libro digitale a testo fluido: non ha una dimensione di pagina fissa, quindi il testo si riadatta allo schermo e al corpo del carattere scelti dal lettore.', note: 'L’EPUB permette al lettore di cambiare il corpo del carattere e far rifluire il testo, ed è questo a rendere comodi i documenti lunghi su telefono o e-reader.' },
    jpg: { about: 'Il JPG usa una compressione con perdita pensata per le fotografie: scarta i dettagli che l’occhio nota meno, il che alleggerisce le foto ma introduce artefatti morbidi e squadrati attorno ai bordi netti e al testo.', note: 'Il JPG produce file piccoli che si aprono letteralmente ovunque, al prezzo di qualche dettaglio scartato per sempre e dell’assenza di trasparenza.' },
    jfif: { about: 'Il JFIF è un’immagine JPEG salvata con un’altra estensione; i pixel al suo interno sono normali dati JPEG, ma Windows spesso si rifiuta di passare il file all’applicazione che volete.', note: 'Il JFIF in realtà non è che JPEG sotto un altro nome.' },
    png: { about: 'Il PNG è senza perdita: memorizza ogni pixel esattamente, supporta un canale alfa completo per la trasparenza e non si degrada mai quando lo risalvate, ed è per questo che è il formato d’elezione per screenshot, loghi e grafica d’interfaccia.', note: 'Il PNG conserva ogni pixel così com’è e supporta la vera trasparenza, quindi sopravvive a modifiche ripetute senza degradarsi.' },
    webp: { about: 'Il WebP è il formato immagine web moderno di Google; comprime sensibilmente più di JPG o PNG a parità di qualità e supporta trasparenza e animazione, ma molti programmi desktop e di stampa ancora non riescono ad aprirlo.', note: 'Il WebP produce i file più leggeri fra i formati web comuni e supporta la trasparenza.' },
    bmp: { about: 'Il BMP memorizza dati di pixel grezzi, praticamente non compressi, il che lo rende perfettamente fedele ed enormemente sprecone — una foto può facilmente pesare dieci volte più della stessa immagine in PNG.', note: 'Il BMP è grezzo e non compresso, ed è ciò che si aspettano ancora i vecchi programmi Windows e alcuni scanner.' },
    tiff: { about: 'Il TIFF è il formato dell’archiviazione e della prestampa: senza perdita, ad alta profondità di colore, capace di contenere più pagine o livelli — e di conseguenza voluminoso.', note: 'Il TIFF è il formato che tipografie e archivi richiedono, perché non viene scartato nulla.' },
    gif: { about: 'Il GIF è limitato a una tavolozza di 256 colori per fotogramma, ed è per questo che le fotografie vi appaiono a bande, ma si anima e parte da solo in linea quasi ovunque su internet.', note: 'Il GIF si anima e parte da solo dentro app di messaggistica, sistemi di ticket e forum, ma resta limitato a 256 colori per fotogramma.' },
    ico: { about: 'L’ICO è un contenitore di icone Windows che conserva la stessa grafica in più dimensioni contemporaneamente, così il sistema può scegliere 16×16 per una scheda e 256×256 per un collegamento sul desktop.', note: 'L’ICO raccoglie più risoluzioni in un solo file, che è esattamente ciò di cui hanno bisogno le favicon e le icone delle applicazioni Windows.' },
    heic: { about: 'L’HEIC è il formato in cui gli iPhone salvano le foto per impostazione predefinita; offre più o meno la stessa qualità del JPG in circa metà dello spazio, ma Windows, molti moduli web e parecchio software datato semplicemente si rifiutano di aprirlo.', note: 'L’HEIC è compatto ma mal supportato fuori dai dispositivi Apple.' },
    svg: { about: 'L’SVG non è fatto di pixel: è XML che descrive forme, tracciati e testo, quindi resta perfettamente nitido a qualunque dimensione e può essere modificato o ristilizzato via codice.', note: 'L’SVG si ingrandisce a qualsiasi dimensione senza diventare mai sfocato, perché memorizza forme anziché pixel.' },
    mp4: { about: 'L’MP4 è un contenitore — di solito video H.264 con audio AAC — ed è l’unico formato video su cui telefoni, browser, televisori, programmi di montaggio e piattaforme social vanno tutti d’accordo.', note: 'L’MP4 si riproduce praticamente su ogni telefono, browser, televisore e programma di montaggio senza installare nulla.' },
    avi: { about: 'L’AVI è un contenitore Microsoft degli anni Novanta; i lettori e le suite di montaggio più vecchi lo leggono ancora, ma non ha funzioni di streaming moderne e i suoi file tendono a essere molto più grandi degli MP4.', note: 'L’AVI è ciò che si aspettano i lettori datati, gli strumenti di authoring DVD e il software di montaggio d’epoca.' },
    mov: { about: 'Il MOV è il contenitore QuickTime di Apple, il formato in cui registrano iPhone e Mac e quello che Final Cut Pro e iMovie gestiscono più agevolmente.', note: 'Il MOV è il contenitore con cui gli strumenti di montaggio Apple lavorano più agevolmente.' },
    mkv: { about: 'L’MKV (Matroska) è un contenitore aperto capace di ospitare un numero qualsiasi di tracce video, audio e sottotitoli in un unico file — ottimo per archiviare, ma rifiutato dalla maggior parte di telefoni, televisori e browser.', note: 'L’MKV può trasportare più tracce audio e di sottotitoli in un unico file.' },
    webm: { about: 'Il WebM è il contenitore esente da royalty creato per il video HTML5, di solito con VP9 o AV1; i browser lo adorano, ma i programmi di montaggio desktop e il software Apple spesso non lo toccano.', note: 'Il WebM è leggero e si trasmette in modo nativo nei browser.' },
    wmv: { about: 'Il WMV è il formato video Windows Media di Microsoft, di fatto limitato a Windows e in gran parte abbandonato fuori da vecchie registrazioni aziendali e catture dello schermo.', note: 'Il WMV è un formato Windows Media con pochissimo supporto altrove.' },
    flv: { about: 'L’FLV era il contenitore dietro il video Flash e, da quando Flash è stato rimosso da tutti i browser, è di fatto un formato d’archivio non riproducibile.', note: 'L’FLV è un contenitore morto dell’era Flash.' },
    mp3: { about: 'L’MP3 è con perdita: il codificatore cancella definitivamente le parti del segnale che prevede non sentirete, riducendo un brano a circa un decimo delle dimensioni originali, ed è per questo che si riproduce assolutamente ovunque.', note: 'L’MP3 è circa dieci volte più piccolo dell’audio non compresso e si riproduce su ogni telefono, autoradio e lettore degli ultimi vent’anni.' },
    wav: { about: 'Il WAV memorizza l’audio senza compressione, campione per campione, esattamente com’è stato registrato — ecco perché gli studi lo usano ed ecco perché un minuto di stereo in qualità CD occupa circa 10 MB.', note: 'Il WAV è non compresso e senza perdita, così i programmi di montaggio e mastering possono elaborarlo senza dover prima decodificare nulla.' },
    flac: { about: 'Il FLAC comprime l’audio senza perdita: pesa all’incirca la metà di un WAV e si decodifica comunque in una copia identica bit per bit della registrazione originale.', note: 'Il FLAC è identico bit per bit ma pesa circa la metà di un WAV.' },
    aac: { about: 'L’AAC è il codec con perdita dietro Apple Music, YouTube e la maggior parte dei servizi di streaming; a parità di bitrate suona in genere meglio dell’MP3.', note: 'L’AAC suona meglio dell’MP3 a parità di bitrate ed è lo standard di fatto nel mondo Apple e dello streaming.' },
    ogg: { about: 'L’OGG Vorbis è un codec con perdita libero da brevetti, prediletto da videogiochi, software libero e Wikipedia, con qualità paragonabile all’MP3 a parità di spazio minore.', note: 'L’OGG è libero da vincoli di brevetto, motivo per cui motori di gioco e progetti open source lo preferiscono.' },
    m4a: { about: 'L’M4A è un contenitore MP4 che ospita solo audio, normalmente AAC — il formato prodotto da iTunes, Apple Music e i memo vocali dell’iPhone.', note: 'L’M4A è il file audio standard dell’ecosistema Apple.' },
    wma: { about: 'Il WMA è il codec audio con perdita di Microsoft dell’epoca di Windows Media Player, raramente supportato fuori da Windows e di fatto abbandonato.', note: 'Il WMA è un codec audio datato e limitato a Windows.' },
    zip: { about: 'Lo ZIP è il formato di archivio integrato in Windows, macOS e ogni telefono — basta un doppio clic, senza installare altro.', note: 'Lo ZIP si apre con un doppio clic su Windows, macOS, Linux, iOS e Android senza installare nulla.' },
    rar: { about: 'Il RAR è un formato di archivio proprietario con buona compressione e dati di ripristino, ma per aprirlo serve WinRAR o uno strumento compatibile.', note: 'Il RAR richiede software di terze parti per essere estratto.' },
    '7z': { about: 'Il 7Z usa la compressione LZMA, che produce regolarmente archivi sensibilmente più piccoli dello ZIP — al prezzo di richiedere 7-Zip o uno strumento compatibile per aprirli.', note: 'Il 7Z comprime notevolmente più dello ZIP, il che conta con cartelle grandi e archiviazione cloud a pagamento.' },
    tar: { about: 'Un file TAR raccoglie molti file in uno solo senza comprimerli; viene dal mondo Unix e preserva permessi e struttura delle cartelle.', note: 'Il TAR preserva i permessi Unix e la struttura delle cartelle.' },
    gz: { about: 'Il GZ (gzip) comprime un singolo flusso di dati ed è ciò che producono i server Linux e gli strumenti a riga di comando; su Windows è scomodo da aprire senza software aggiuntivo.', note: 'Il GZ è il formato di compressione standard su Linux e sui server web.' },
    srt: { about: 'L’SRT è il formato di sottotitoli in testo semplice che ogni programma di montaggio e ogni lettore comprende: battute numerate, un intervallo di time-code e la riga di dialogo.', note: 'L’SRT è accettato da YouTube, Vimeo, Premiere, Final Cut e da ogni lettore comune.' },
  },
  reasons: {
    'pdf-to-word': 'L’innesco tipico è una modifica impossibile da fare nel PDF stesso — una clausola contrattuale, una riga del curriculum o un paragrafo di una relazione da cambiare senza ridigitare l’intero documento.',
    'word-to-pdf': 'Si converte Word in PDF proprio alla fine della vita del documento: quando si invia un curriculum, un preventivo o un modulo firmato a qualcuno di cui non si controllano caratteri, versione di Word e margini.',
    'pdf-to-excel': 'Il caso tipico è un estratto conto, una fattura o una relazione che esiste solo in PDF ma i cui numeri dovete sommare, ordinare o mettere a grafico.',
    'excel-to-pdf': 'È ciò che si fa prima di inviare un budget o un listino a chi deve leggerlo ma non modificarlo, e prima di stampare: un PDF fissa le interruzioni di pagina che Excel ricalcolerebbe su ogni computer.',
    'pptx-to-pdf': 'La maggior parte delle persone converte una presentazione in PDF prima di inviarla o distribuirla, così le diapositive non si scompongono e nessuno ha bisogno di PowerPoint installato per aprirle.',
    'pdf-to-pptx': 'Serve quando l’unica copia sopravvissuta di una presentazione è il PDF fatto circolare dopo la riunione e dovete aggiornare o riutilizzare le diapositive.',
    'pdf-to-txt': 'Motivi comuni: dare in pasto un documento a uno script, a un indice di ricerca o a uno strumento di IA, oppure ridurre una relazione lunga a qualcosa da cercare, confrontare e incollare ovunque.',
    'pdf-to-html': 'È il modo più rapido per pubblicare su un sito una relazione, un manuale o una brochure già esistenti senza ricostruire la pagina a mano.',
    'html-to-pdf': 'Si fa per archiviare una pagina web esattamente com’è oggi, oppure per trasformare un modello HTML di fattura o relazione in qualcosa di stampabile e inviabile.',
    'rtf-to-pdf': 'L’RTF esce di solito da software datato o da modelli di documenti legali; portarlo in PDF vi dà un file che si apre identico ovunque e non può essere modificato per sbaglio.',
    'pdf-to-rtf': 'È l’opzione da scegliere quando serve una copia modificabile di un PDF ma non si può dare per scontato che il destinatario abbia Word: praticamente ogni programma di videoscrittura mai scritto apre l’RTF.',
    'odt-to-pdf': 'Il caso tipico: avete scritto il documento in LibreOffice o OpenOffice e chi lo riceve usa Microsoft Office, oppure niente del tutto.',
    'pdf-to-epub': 'Leggere un PDF sul telefono significa zoomare e scorrere in orizzontale di continuo; questa conversione serve soprattutto a rendere un documento lungo davvero leggibile su schermo piccolo o su e-reader.',
    'epub-to-pdf': 'Si converte l’EPUB in PDF quando si vuole stampare un libro, annotarlo con numeri di pagina fissi o inviarlo a chi non ha alcuna app di lettura installata.',
    'document-converter': 'È lo strumento da aprire quando vi consegnano un documento nel formato che il mittente aveva per caso e vi serve in quello che il vostro software apre davvero.',
    'ebook-converter': 'Negozi e dispositivi per libri digitali preferiscono ciascuno il proprio formato, quindi è ciò che si usa per spostare un libro di vostra proprietà da un lettore o un’app a un’altra.',
    'jpg-to-png': 'L’innesco tipico è la modifica: dovete scontornare uno sfondo, appoggiare un logo su un’altra immagine o impedire a uno screenshot di diventare più sfocato a ogni salvataggio.',
    'png-to-jpg': 'È la soluzione per uno screenshot o un’esportazione troppo pesante da allegare a un’e-mail o da far passare attraverso il limite di dimensione di un modulo di caricamento.',
    'webp-to-png': 'Di solito serve dopo aver salvato un’immagine da un sito: il WebP si scarica senza problemi, ma editor datati, suite per ufficio e alcuni servizi di stampa continuano a rifiutarsi di aprirlo.',
    'webp-to-jpg': 'La maggior parte lo fa per portare un’immagine presa da un sito in qualcosa di accettato universalmente — un’e-mail, un CMS datato, un servizio di stampa fotografica o il software preistorico di un collega.',
    'heic-to-jpg': 'È il classico problema dell’iPhone: le foto sono perfette sul telefono ma arrivano su un PC Windows o in un modulo web come file .heic impossibili da aprire.',
    'heic-to-png': 'Usatelo quando intendete modificare la foto e non soltanto condividerla — il PNG consegna al vostro editor pixel senza perdita anziché una copia appena ricompressa.',
    'svg-to-png': 'Il motivo tipico è uno strumento che rifiuta i vettori: una presentazione, un annuncio su un marketplace, una firma e-mail o una catena di produzione di icone che accetta solo pixel.',
    'svg-to-jpg': 'È per i contesti che vogliono un semplice file di tipo fotografico — un documento, un post sui social o un modulo di caricamento che rifiuta sia il markup SVG sia la trasparenza.',
    'bmp-to-png': 'I file BMP escono da vecchi programmi Windows e dagli scanner con dimensioni assurde; il PNG memorizza esattamente gli stessi pixel in una frazione dello spazio.',
    'tiff-to-jpg': 'Scanner e fotocamere professionali producono TIFF troppo pesanti per l’e-mail, quindi il JPG è ciò che si invia una volta messa al sicuro la copia d’archivio.',
    'gif-to-png': 'È ciò che si fa con un GIF statico — un logo, un’icona o un singolo fotogramma esportato — che mostra bande di colore o un bordo sfrangiato a causa del limite di 256 colori.',
    'png-to-ico': 'Quasi tutti quelli che convertono PNG in ICO stanno costruendo una favicon o un’icona di applicazione Windows, ed entrambe si aspettano il contenitore ICO anziché un semplice file immagine.',
    'jfif-to-png': 'I file JFIF compaiono tipicamente quando una foto viene salvata da Outlook o da un browser e Windows poi si rifiuta di consegnarla all’applicazione che volevate davvero usare.',
    'heic-to-pdf': 'Comodo quando fotografate documenti, ricevute o una lavagna con l’iPhone e dovete consegnarli come un unico file anziché come una cartella di immagini.',
    'image-compressor': 'Il motivo tipico è un limite rigido da qualche parte — un modulo di caricamento, un tetto per gli allegati e-mail o una pagina web che carica troppo lentamente perché le sue immagini sono ben più pesanti del necessario.',
    'jpeg-compressor': 'Fotografi e proprietari di siti lo usano quando i JPEG a piena risoluzione rallentano una pagina o non passano un limite di caricamento.',
    'png-compressor': 'Screenshot e grafica d’interfaccia esportata pesano spesso diversi megabyte senza una buona ragione; questo li alleggerisce prima che finiscano in un documento, in un ticket o in una pagina web.',
    'mp4-to-avi': 'Il motivo è quasi sempre un dispositivo datato o un programma specifico — alcuni lettori d’epoca, strumenti di authoring DVD e utility per fotocamere leggono AVI e nient’altro.',
    'mp4-to-mov': 'Di norma è il primo passo prima del montaggio su Mac, perché Final Cut Pro e iMovie gestiscono i file QuickTime con più scioltezza.',
    'mov-to-mp4': 'iPhone e Mac registrano in MOV; tutto il resto si aspetta MP4, quindi è la conversione che si esegue prima di caricare, inviare o pubblicare una clip.',
    'mkv-to-mp4': 'L’MKV è eccellente per archiviare, ma telefoni, televisori, browser e gran parte dei programmi di montaggio non lo riproducono — convertirlo in MP4 è ciò che rende il file davvero utilizzabile.',
    'webm-to-mp4': 'I file WebM salvati dal web spesso si rifiutano di aprirsi in QuickTime, su iOS o in Premiere; l’MP4 è il formato che tutti accettano.',
    'avi-to-mp4': 'È il salvataggio standard per vecchie riprese da videocamera e clip archiviate che divorano gigabyte e non si riproducono su nessun telefono.',
    'flv-to-mp4': 'Flash è sparito da tutti i browser, quindi qualunque FLV vi sia rimasto è di fatto non riproducibile — convertirlo in MP4 è ciò che mantiene guardabile quel materiale d’archivio.',
    'wmv-to-mp4': 'Il WMV è un residuo esclusivo di Windows, quindi è ciò che si fa prima di inviare una vecchia registrazione o una cattura dello schermo a un Mac, a un iPhone o a una piattaforma web.',
    'mp4-to-mp3': 'Di solito conta il suono più dell’immagine — una lezione, un’intervista, un podcast o un videoclip che volete sul telefono senza portarvi dietro il video.',
    'video-to-mp3': 'Ci si ricorre quando l’audio è la parte che vale la pena conservare: una conferenza registrata, un’intervista, una prova o una colonna sonora.',
    'mp4-converter': 'È lo strumento da usare quando una clip non parte o non si carica, perché l’MP4 è l’unico formato video che telefoni, browser, televisori e piattaforme social accettano tutti.',
    'video-converter': 'Usatelo quando una clip deve cambiare mondo — uscire da un programma di montaggio, finire su un telefono, entrare in un browser o approdare su una piattaforma che accetta un solo contenitore preciso.',
    'mp3-to-wav': 'Il motivo tipico è il montaggio: le stazioni audio digitali, le catene di mastering e molti flussi audio per la radiodiffusione o i videogiochi vogliono WAV non compresso, per non decodificare un file compresso a ogni singola operazione.',
    'wav-to-mp3': 'Le registrazioni escono da un registratore da campo o da una stazione audio come enormi file WAV; l’MP3 li rende abbastanza leggeri da inviarli, caricarli o tenerli sul telefono.',
    'flac-to-mp3': 'Una libreria FLAC suona benissimo a casa, ma autoradio, telefoni datati e lettori economici spesso la rifiutano — l’MP3 è la copia di compatibilità che ci si porta dietro.',
    'aac-to-mp3': 'È soprattutto una questione di compatibilità: l’AAC viene dagli ecosistemi Apple e dallo streaming, mentre lettori datati, autoradio e software per DJ si aspettano MP3.',
    'ogg-to-mp3': 'L’OGG spunta nei videogiochi, su Wikipedia e nel software libero, e quasi nessuno dei lettori comuni su un telefono o in auto lo apre.',
    'wma-to-mp3': 'Il WMA è un reperto dell’era di Windows Media Player, ed è così che si recupera una vecchia raccolta musicale estratta per il telefono o per una libreria in streaming.',
    'm4a-to-mp3': 'È il passaggio abituale quando si spostano musica o memo vocali dell’iPhone dai dispositivi Apple verso software, automobili o lettori che capiscono solo MP3.',
    'mp3-to-aac': 'Alcuni dispositivi e applicazioni — in particolare nel mondo Apple e dello streaming — preferiscono l’AAC, quindi questa è una conversione di compatibilità e non un miglioramento di qualità.',
    'mp3-to-ogg': 'Si converte in OGG per motori di gioco, progetti open source e piattaforme dove serve un codec libero da brevetti.',
    'audio-converter': 'È lo strumento per il momento in cui un file non parte: un unico posto per portare l’audio in quello dei formati comuni su cui insistono il vostro dispositivo, il vostro programma di montaggio o il vostro modulo di caricamento.',
    'rar-to-zip': 'Il RAR richiede software aggiuntivo per aprirsi, quindi è ciò che si fa prima di inviare un archivio a qualcuno che non installerà WinRAR.',
    '7z-to-zip': 'Il 7Z comprime meglio ma richiede 7-Zip installato; in ZIP il destinatario può semplicemente fare doppio clic sul file.',
    'tar-to-zip': 'Il TAR viene dalle righe di comando di Linux e macOS, mentre lo ZIP è ciò che un collega su Windows può aprire senza installare assolutamente nulla.',
    'gz-to-zip': 'I file GZ arrivano di solito da un server o da uno strumento Linux e sono scomodi su Windows, dove uno ZIP si estrae con un doppio clic.',
    'zip-to-7z': 'Qui la questione è la dimensione: la compressione del 7Z è sensibilmente più forte, il che conta quando archiviate una cartella grande o pagate lo spazio cloud al gigabyte.',
    'video-to-gif': 'L’uso tipico è un breve loop per un messaggio in chat, un README, una segnalazione di bug o un post — luoghi dove un GIF parte da solo in linea mentre un file video no.',
    'mp4-to-gif': 'L’uso tipico è un breve loop per una chat, un README, una segnalazione di bug o un post, dove un GIF parte da solo in linea mentre un video resterebbe lì come allegato.',
    'webm-to-gif': 'Le clip WebM salvate dal web spesso non si incorporano dove vorreste, mentre un GIF parte in linea dentro app di messaggistica, sistemi di ticket e forum.',
    'mov-to-gif': 'È ciò che si fa con una registrazione dello schermo QuickTime che deve comparire in linea in una pull request, in un ticket di assistenza o in un post.',
    'avi-to-gif': 'Trasformare qualche secondo di una vecchia clip AVI in un GIF è il modo più semplice per farla entrare in un documento, in una conversazione o in una pagina web.',
    'gif-to-mp4': 'I GIF lunghi sono enormi e scattano; l’MP4 mostra la stessa animazione a una frazione del peso, ed è esattamente per questo che le piattaforme social li convertono dietro le quinte.',
    'image-to-gif': 'Utile quando una piattaforma o un sistema datato si aspetta espressamente un GIF, o quando vi serve un fotogramma fisso nello stesso formato di una serie di animazioni già esistente.',
    'gif-compressor': 'I GIF animati si gonfiano in fretta, e questa è la soluzione quando uno è troppo pesante per un’e-mail, per il limite di caricamento di una chat o per una pagina che deve caricare veloce.',
    'merge-pdf': 'Il caso classico è una domanda o una pratica: un modulo, una scansione e una ricevuta che devono arrivare tutti come un unico documento.',
    'split-pdf': 'Di solito vi serve esattamente una cosa da un file molto più lungo — un capitolo, una fattura, una pagina firmata da una scansione di cinquanta pagine.',
    'compress-pdf': 'Quasi sempre un limite di dimensione: un tetto per gli allegati e-mail, un modulo della pubblica amministrazione o un portale che rifiuta qualsiasi cosa superi pochi megabyte.',
    'rotate-pdf': 'Risolve il problema quotidiano dello scanner — pagine venute di traverso o capovolte per come sono stati inseriti i fogli.',
    'protect-pdf': 'Si proteggono i PDF con password prima di inviare buste paga, contratti o referti medici, così il contenuto non è leggibile da chi riceverà poi il messaggio inoltrato.',
    'unlock-pdf': 'Usatelo su documenti di vostra proprietà quando la password è nota ma la restrizione è d’intralcio — un estratto conto che non riuscite a stampare, per esempio.',
    'view-metadata': 'Risponde alle domande che un file non vi dice direttamente: quale fotocamera ha scattato questa foto, quanto dura davvero questa registrazione, quale codec c’è dentro questo video, quante pagine ha questo PDF.',
    'ocr': 'La situazione è sempre la stessa: avete un documento sotto forma di immagine e vi servono le parole che contiene — per cercarle, citarle, modificarle o archiviarle come si deve.',
    'pdf-compress-ai': 'Ricorreteci quando la compressione normale è già stata provata e il file è ancora troppo pesante per il limite di caricamento contro cui state combattendo.',
    'text-to-speech': 'Si usa per ascoltare qualcosa invece di leggerlo — un articolo durante il tragitto, un copione riletto ad alta voce per scovare frasi goffe, o una voce fuori campo per un video.',
    'speech-to-text': 'Il caso tipico è una registrazione che vi serve per iscritto: una riunione, un’intervista, una lezione o un memo vocale che deve diventare appunti, un verbale o una trascrizione citabile.',
    'auto-subtitle': 'I sottotitoli sono ciò che rende un video guardabile senza audio e rintracciabile dai motori di ricerca, e digitarli a mano richiede, anche per una clip breve, molto più tempo di quanto si immagini.',
    'document-translation': 'L’obiettivo è leggere o inviare un documento in un’altra lingua senza perdere l’impaginazione che lo rende leggibile.',
  },
  t: {
    'list.and': 'e',
    'family.document': 'documento',
    'family.image': 'immagine',
    'family.video': 'video',
    'family.audio': 'audio',
    'family.ebook': 'libro digitale',
    'family.archive': 'archivio',
    'family.subtitle': 'sottotitoli',
    'family.none': 'file',
    'unit.sample': 'ogni campione',
    'unit.pixel': 'ogni pixel',

    'intro.convert': '{{fromAbout}} {{toAbout}} {{reason}} {{toNote}}',
    'intro.convert.noSource': 'Il {{fn}} è il formato di partenza di questa conversione.',
    'intro.lead': '{{lead}} {{reason}}',
    'intro.hub': 'Questo è il convertitore {{category}} universale: accetta {{inputs}} e scrive {{outputs}}, così non dovete andare a caccia dello strumento specifico che corrisponde alla vostra coppia di formati. {{reason}} Scegliete qui sopra il formato di uscita: la conversione avviene sul server, non c’è nulla da installare.',
    'intro.hubExtract': 'Questo strumento estrae la traccia audio da un file video e la salva a parte, trasformando un video in un semplice file audio riproducibile ovunque. Accetta {{inputs}} e scrive {{outputs}}. La traccia video viene semplicemente scartata, ed è per questo che il risultato pesa una frazione dell’originale. {{reason}}',
    'intro.hubGif': 'Questo strumento trasforma i file {{inputs}} in GIF animate. {{gifAbout}} {{reason}}',
    'intro.hubGif.gifAbout': 'Il GIF è limitato a una tavolozza di 256 colori per fotogramma, ed è per questo che le fotografie vi appaiono a bande, ma si anima e parte da solo in linea quasi ovunque su internet.',
    'intro.compress': '{{about}} Questo strumento ricodifica il vostro {{fn}} in un file più leggero senza cambiare formato, quindi ciò che scaricate resta un normale {{fn}} che si apre esattamente dove si apriva l’originale. {{reason}}{{extra}}',
    'intro.compress.lossless': ' Poiché il {{fn}} è senza perdita, gran parte del risparmio viene da una codifica più intelligente e da una tavolozza ridotta, non dallo scartare dettagli.',
    'intro.soon': '{{reason}} Questo strumento non è ancora attivo — è in fase di sviluppo e comparirà qui non appena sarà pronto.',
    'intro.lead.pdf-merge': 'Unire combina più PDF in un unico file, nell’ordine che scegliete, senza rigenerare le pagine: il testo resta selezionabile e le immagini conservano la qualità originale. Il PDF è un formato a impaginazione fissa: memorizza la posizione esatta di ogni carattere, linea e immagine, ed è per questo che appare identico ovunque ma risulta scomodo da modificare.',
    'intro.lead.pdf-split': 'Dividere estrae da un PDF le pagine che indicate e le salva come nuovo documento, lasciando intatto l’originale. Il PDF è un formato a impaginazione fissa: memorizza la posizione esatta di ogni carattere, linea e immagine, ed è per questo che appare identico ovunque ma risulta scomodo da modificare.',
    'intro.lead.pdf-compress': 'Comprimere un PDF ricodifica le immagini al suo interno ed elimina dati incorporati ridondanti, dove risiede quasi tutto il peso di un PDF grande. Testo e grafica vettoriale restano nitidi.',
    'intro.lead.pdf-compress-ai': 'Questo strumento analizza il contenuto del PDF prima di comprimerlo, così immagini fotografiche, grafica piatta e pagine di solo testo vengono trattate ciascuna nel modo che risparmia più spazio senza degradarle in modo visibile.',
    'intro.lead.pdf-rotate': 'La rotazione cambia l’indicatore di orientamento e la geometria di pagina di un PDF, così le pagine si visualizzano e si stampano dritte. Non viene rigenerato nulla, quindi non si perde qualità.',
    'intro.lead.pdf-protect': 'Proteggere un PDF ne cifra il contenuto, così non può essere aperto senza la password che impostate. La cifratura si applica al file stesso, non a un involucro attorno a esso.',
    'intro.lead.pdf-unlock': 'Lo sblocco rimuove la password e le restrizioni d’uso da un PDF di cui avete già la password, così può tornare a essere aperto, stampato e copiato normalmente.',
    'intro.lead.metadata': 'Ogni file porta con sé informazioni su se stesso che non si vedono quando lo aprite: dimensioni dell’immagine e impostazioni della fotocamera, durata e bitrate dell’audio, codec e frequenza dei fotogrammi del video, autore e numero di pagine del documento. Questo strumento legge quei metadati e ve li mostra.',
    'intro.lead.ocr': 'Il riconoscimento ottico dei caratteri guarda un’immagine di testo — una scansione, una foto, una pagina PDF priva di livello testuale — e deduce quali siano i caratteri, trasformando un’immagine di parole in parole che un computer può cercare, copiare e modificare.',
    'intro.lead.tts': 'La sintesi vocale genera audio parlato a partire da testo scritto usando voci neurali, così ottenete una registrazione dal suono naturale invece della resa piatta e robotica dei vecchi sistemi.',
    'intro.lead.stt': 'Il riconoscimento vocale trascrive l’audio parlato in parole scritte. Gestisce parlato naturale, accenti e rumore di fondo molto meglio di quanto facessero i vecchi software di dettatura, e restituisce una trascrizione che potete modificare.',
    'intro.lead.subtitle': 'Il generatore di sottotitoli trascrive il parlato di un video e lo scrive con i time-code, producendo un file di sottotitoli standard anziché una semplice trascrizione.',

    'steps.convert.1.batch': 'Trascinate il vostro file {{fn}} sull’area di caricamento in cima a questa pagina, oppure fateci clic per cercarlo sul dispositivo. Potete aggiungere più file — o un’intera cartella — e convertirli tutti in una volta.',
    'steps.convert.1.single': 'Trascinate il vostro file {{fn}} sull’area di caricamento in cima a questa pagina, oppure fateci clic per cercarlo sul dispositivo.',
    'steps.convert.2.direct': 'Scegliete {{tn}} come formato di uscita e fate clic su Converti.',
    'steps.convert.2.dropdown': 'Scegliete {{tn}} come formato di uscita dal menu a discesa e fate clic su Converti.',
    'steps.convert.2.directMedia': 'Scegliete {{tn}} come formato di uscita, regolate se serve qualità o dimensioni nelle impostazioni avanzate e fate clic su Converti.',
    'steps.convert.2.dropdownMedia': 'Scegliete {{tn}} come formato di uscita dal menu a discesa, regolate se serve qualità o dimensioni nelle impostazioni avanzate e fate clic su Converti.',
    'steps.convert.3': 'Scaricate il vostro file {{tn}} finito. Il link di download resta attivo 24 ore, dopodiché entrambi i file vengono eliminati automaticamente.',
    'steps.hub.1.batch': 'Trascinate il vostro file {{category}} ({{inputs}} sono tutti accettati) sull’area di caricamento in cima a questa pagina, oppure fateci clic per cercarlo sul dispositivo. Potete aggiungere più file — o un’intera cartella — e convertirli tutti in una volta.',
    'steps.hub.1.single': 'Trascinate il vostro file {{category}} ({{inputs}} sono tutti accettati) sull’area di caricamento in cima a questa pagina, oppure fateci clic per cercarlo sul dispositivo.',
    'steps.hub.2.direct': 'Scegliete il formato di uscita che vi serve e fate clic su Converti.',
    'steps.hub.2.dropdown': 'Scegliete dal menu a discesa il formato di uscita che vi serve e fate clic su Converti.',
    'steps.hub.2.directMedia': 'Scegliete il formato di uscita che vi serve, regolate se occorre qualità o dimensioni nelle impostazioni avanzate e fate clic su Converti.',
    'steps.hub.2.dropdownMedia': 'Scegliete dal menu a discesa il formato di uscita che vi serve, regolate se occorre qualità o dimensioni nelle impostazioni avanzate e fate clic su Converti.',
    'steps.hub.3': 'Scaricate il vostro file finito. Il link di download resta attivo 24 ore, dopodiché entrambi i file vengono eliminati automaticamente.',
    'steps.pdf-merge.1': 'Aggiungete ogni PDF che volete combinare — trascinateli insieme sull’area di caricamento, oppure fate clic per selezionarli uno dopo l’altro.',
    'steps.pdf-merge.2': 'Trascinate i file nell’ordine in cui volete che compaiano nel documento finito.',
    'steps.pdf-merge.3': 'Fate clic su Unisci e scaricate l’unico PDF combinato.',
    'steps.pdf-split.1': 'Caricate il PDF da cui volete estrarre delle pagine.',
    'steps.pdf-split.2': 'Digitate le pagine o gli intervalli che vi servono nel campo degli intervalli di pagina — per esempio 1-3, 5, 7-10.',
    'steps.pdf-split.3': 'Fate clic su Converti e scaricate le pagine estratte.',
    'steps.pdf-compress.1': 'Trascinate il vostro PDF sull’area di caricamento, oppure fate clic per cercarlo.',
    'steps.pdf-compress.2': 'Fate clic su Converti — il file viene analizzato e le sue immagini e i dati incorporati vengono ricodificati in dimensioni minori.',
    'steps.pdf-compress.3': 'Scaricate il PDF compresso e controllate il risparmio di dimensione mostrato accanto.',
    'steps.pdf-rotate.1': 'Caricate il PDF le cui pagine sono nel verso sbagliato.',
    'steps.pdf-rotate.2': 'Scegliete di quanto ruotarle — 90°, 180° o 270°.',
    'steps.pdf-rotate.3': 'Fate clic su Converti e scaricate il PDF corretto.',
    'steps.pdf-protect.1': 'Caricate il PDF che volete proteggere.',
    'steps.pdf-protect.2': 'Inserite la password che servirà per aprirlo e conservatene una copia in un posto sicuro.',
    'steps.pdf-protect.3': 'Fate clic su Converti e scaricate il PDF cifrato.',
    'steps.pdf-unlock.1': 'Caricate il PDF protetto da password.',
    'steps.pdf-unlock.2': 'Inserite la password attuale perché il file possa essere decifrato.',
    'steps.pdf-unlock.3': 'Fate clic su Converti e scaricate il PDF sbloccato.',
    'steps.metadata.1': 'Trascinate un file qualsiasi sull’area di caricamento — un’immagine, un video, un file audio o un documento.',
    'steps.metadata.2': 'Il file viene esaminato e non convertito, quindi non gli viene cambiato nulla.',
    'steps.metadata.3': 'Leggete i metadati direttamente nella pagina: dimensioni, durata, codec, dettagli della fotocamera, numero di pagine e altro ancora.',
    'steps.ocr.1': 'Caricate il PDF scansionato o la foto del testo.',
    'steps.ocr.2': 'Scegliete la lingua del documento e se volete un PDF ricercabile o testo semplice.',
    'steps.ocr.3': 'Fate clic su Converti e scaricate il risultato, con il testo riconosciuto ora selezionabile e ricercabile.',
    'steps.tts.1': 'Digitate o incollate il vostro testo nel riquadro — fino a 4096 caratteri per conversione.',
    'steps.tts.2': 'Scegliete una voce, una velocità di lettura e un formato di uscita.',
    'steps.tts.3': 'Fate clic su Converti e scaricate il file audio finito.',
    'steps.stt.1': 'Caricate la vostra registrazione, oppure registrate direttamente dal microfono con il pulsante presente nella pagina.',
    'steps.stt.2': 'Se volete, indicate la lingua parlata per migliorare la precisione e scegliete l’uscita in TXT o DOCX.',
    'steps.stt.3': 'Fate clic su Converti, leggete la trascrizione nella pagina e poi scaricatela.',
    'steps.subtitle.1': 'Caricate il video da sottotitolare.',
    'steps.subtitle.2': 'Scegliete SRT o VTT e indicate la lingua parlata se la conoscete.',
    'steps.subtitle.3': 'Fate clic su Converti e scaricate il file di sottotitoli sincronizzato, pronto da inserire nel vostro lettore o nel vostro programma di montaggio.',
    'steps.compress.1': 'Trascinate le vostre immagini {{fn}} sull’area di caricamento, oppure fate clic per cercarle. Potete aggiungere un’intera cartella in una volta.',
    'steps.compress.1.gif': 'Trascinate la vostra animazione {{fn}} sull’area di caricamento, oppure fate clic per cercarla. Potete aggiungere un’intera cartella in una volta.',
    'steps.compress.2': 'Fate clic su Converti — il file viene ricodificato in dimensioni minori restando nello stesso formato.',
    'steps.compress.3': 'Scaricate il risultato e confrontatelo con la dimensione originale mostrata nella pagina.',
    'steps.soon.1': 'Scegliete lo strumento che vi serve nella pagina Strumenti — tutto tranne questo è già attivo oggi.',
    'steps.soon.2': 'Caricate il vostro file e scegliete un formato di uscita.',
    'steps.soon.3': 'Scaricate il risultato, oppure tornate qui quando la traduzione di documenti sarà attiva.',

    'faq.cost.q.pair': 'Convertire {{from}} in {{to}} è gratis?',
    'faq.cost.q.tool': '{{label}} è gratuito?',
    'faq.cost.a.pair': "Ogni conversione da {{from}} a {{to}} consuma un credito di un piccolo pacchetto prepagato: nessun abbonamento, i crediti non scadono mai e una conversione fallita non vi viene addebitata.",
    'faq.cost.a.tool': "Ogni conversione consuma un credito di un piccolo pacchetto prepagato: nessun abbonamento, i crediti non scadono mai e una conversione fallita non vi viene addebitata.",
    'faq.cost.a.smartTts': "Le funzioni intelligenti si pagano a consumo anziché a file: 1 credito ogni 1000 caratteri di testo, arrotondati per eccesso. Nessun abbonamento: i crediti si acquistano in piccoli pacchetti prepagati, non scadono mai e una conversione fallita non costa mai nulla.",
    'faq.cost.a.smartAv': "Le funzioni intelligenti si pagano a consumo anziché a file: 1 credito ogni 5 minuti di audio o video, arrotondati per eccesso. Nessun abbonamento: i crediti si acquistano in piccoli pacchetti prepagati, non scadono mai e una conversione fallita non costa mai nulla.",
    'faq.cost.q.metadata': 'Lo strumento Info file è gratuito?',
    'faq.cost.a.metadata': 'Sì. Leggere i metadati di un file non è una conversione, quindi non consuma crediti — potete esaminare tutti i file che volete. I crediti si spendono solo quando uno strumento produce davvero un nuovo file per voi.',
    'faq.cost.q.soon': '{{label}} è già disponibile?',
    'faq.cost.a.soon': 'Non ancora — questa pagina è un segnaposto mentre lo strumento viene costruito, quindi oggi qui non c’è nulla da caricare. Il prezzo seguirà lo stesso modello a crediti prepagati del resto del sito: nessun abbonamento, crediti che non scadono mai e nessun addebito per una conversione fallita.',

    'faq.time.q.pair': 'Quanto tempo richiede la conversione da {{from}} a {{to}}?',
    'faq.time.q.tool': 'Quanto tempo richiede {{label}}?',
    'faq.time.a': '{{speed}} La velocità di caricamento è di solito il fattore limitante, quindi un file grande su una connessione lenta richiede più tempo della conversione stessa.{{suffix}}',
    'faq.time.speed.image': 'Le immagini sono la cosa più rapida che convertiamo — una singola foto è normalmente pronta in meno di cinque secondi, e un’intera cartella richiede all’incirca il tempo del caricamento.',
    'faq.time.speed.document': 'La maggior parte dei documenti è pronta in pochi secondi. I file molto lunghi — qualche centinaio di pagine, o una scansione carica di immagini — possono arrivare a un minuto.',
    'faq.time.speed.audio': 'Un brano normale si converte in pochi secondi. Una registrazione integrale, come una lezione o una puntata di podcast, richiede di solito ben meno di un minuto, per lo più dedicato al caricamento.',
    'faq.time.speed.video': 'Il video è la categoria più lenta perché ogni fotogramma va ricodificato. Una clip breve richiede secondi, mentre un file lungo ad alta risoluzione può richiedere qualche minuto.',
    'faq.time.speed.archive': 'Gli archivi si convertono in pochi secondi, anche se uno grande richiede più tempo perché ogni file al suo interno va estratto e reimpacchettato.',
    'faq.time.speed.ebook': 'I libri digitali sono rapidi — un romanzo intero si converte normalmente in pochi secondi.',
    'faq.time.speed.subtitle': 'La trascrizione procede al ritmo di pochi secondi per minuto di audio, quindi un video di dieci minuti è di solito sottotitolato in ben meno di un minuto.',
    'faq.time.suffix.standard': ' Sono accettati file fino a 200 MB.',
    'faq.time.suffix.smart': ' Le funzioni intelligenti accettano file fino a 25 MB; le conversioni normali fino a 200 MB.',
    'faq.time.q.metadata': 'Quanto tempo serve per leggere i metadati di un file?',
    'faq.time.a.metadata': 'Un secondo o due, una volta caricato il file. Non viene convertito né ricodificato nulla — le intestazioni vengono analizzate e il risultato viene stampato direttamente nella pagina — quindi l’attesa coincide in sostanza con il caricamento.',
    'faq.time.q.soon': 'Costerà di più?',
    'faq.time.a.soon': 'Userà gli stessi crediti di tutto il resto del sito. Non c’è un piano o un abbonamento separato a cui iscriversi, e i crediti già presenti nel vostro account funzioneranno con esso dal momento in cui sarà attivo.',

    'faq.safety.q.pair': 'È sicuro caricare il mio file {{from}}?',
    'faq.safety.q.tool': 'Il mio file è al sicuro?',
    'faq.safety.a.pair': 'I file viaggiano su una connessione TLS cifrata e non vengono usati per nient’altro che la conversione richiesta. Sia il vostro file {{from}} originale sia il file {{to}} che vi restituiamo vengono eliminati automaticamente entro 24 ore — in modo definitivo e senza conservare backup — e il contenuto non viene mai letto, analizzato o condiviso. Il servizio è gestito dalla Germania in regime di GDPR.',
    'faq.safety.a.tool': 'I file viaggiano su una connessione TLS cifrata e non vengono usati per nient’altro che la conversione richiesta. Sia il vostro file originale sia il risultato che vi restituiamo vengono eliminati automaticamente entro 24 ore — in modo definitivo e senza conservare backup — e il contenuto non viene mai letto, analizzato o condiviso. Il servizio è gestito dalla Germania in regime di GDPR.',

    'quality.vectorRaster.q': 'Il mio {{fn}} resterà nitido come {{tn}}?',
    'quality.vectorRaster.a': 'Fino alla dimensione a cui lo esportate, sì. Il {{fn}} memorizza forme anziché pixel, quindi è infinitamente scalabile, ma un {{tn}} è una griglia fissa di pixel e diventerà sfocato se in seguito viene ingrandito oltre quella griglia. Impostate nelle impostazioni avanzate la larghezza e l’altezza che vi servono davvero prima di convertire — esportare a due o tre volte la dimensione di visualizzazione è il trucco abituale per schermi ad alta densità di pixel. Conservate il file {{fn}} originale: resta la copia madre da cui riesportare a qualsiasi risoluzione.',
    'quality.docToTxt.q': 'Perderò la formattazione convertendo {{fn}} in {{tn}}?',
    'quality.docToTxt.a': 'Sì, e di proposito — un file {{tn}} contiene caratteri e nient’altro. Font, colori, immagini, tabelle, colonne e interruzioni di pagina spariscono tutti; ciò che riavete è il testo leggibile del documento nell’ordine di lettura. È esattamente quello che volete per cercare, per gli script o per dare il testo in pasto a un altro programma, ed esattamente quello che non volete se speravate di conservare l’impaginazione. Attenzione: un {{fn}} che in realtà è un’immagine scansionata non contiene alcun testo da estrarre — passatelo invece dallo strumento OCR.',
    'quality.docToSheet.q': 'Quanto è precisa l’estrazione delle tabelle da un {{fn}}?',
    'quality.docToSheet.a': 'Le tabelle pulite, con righe di contorno e colonne regolari — estratti conto, fatture, report esportati — passano in modo affidabile, con ogni valore che finisce nella propria cella così potete sommarlo e ordinarlo. Le tabelle senza bordi visibili, le celle che occupano più righe o le cifre spezzate da un’interruzione di pagina sono i casi da controllare a vista dopo. Il {{fn}} memorizza posizioni e non struttura tabellare, quindi la conversione deve dedurre dove finisce una colonna e comincia la successiva.',
    'quality.docToReflow.q': 'L’impaginazione sopravviverà alla conversione da {{fn}} a {{tn}}?',
    'quality.docToReflow.a': 'Non esattamente, ed è proprio questo il punto. Il {{fn}} fissa il testo a coordinate di pagina rigide; il {{tn}} lo fa rifluire per adattarsi allo schermo e al corpo del carattere del lettore, quindi numeri di pagina fissi, intestazioni, piè di pagina e impaginazioni su più colonne vengono reinterpretati anziché riprodotti. Corpo del testo, titoli, ordine dei paragrafi e immagini passano bene. I documenti composti soprattutto di prosa si convertono benissimo; sono le pagine molto curate graficamente, i moduli e le tabelle complesse a meritare un controllo dopo.',
    'quality.docToFixed.q': 'La mia formattazione verrà conservata nel {{tn}}?',
    'quality.docToFixed.a': 'Sì — questa direzione è quella sicura. Il {{tn}} registra la pagina come viene resa alla fine, quindi caratteri, spaziature, tabelle, immagini e interruzioni di pagina restano congelati esattamente come impaginati e appariranno uguali su ogni dispositivo e stampante. È anche il compromesso: il risultato non è più liberamente modificabile, che di solito è proprio il motivo per cui si converte in {{tn}} prima di spedire un documento.',
    'quality.docToEditable.q': 'Quanto è precisa la conversione da {{fn}} a {{tn}}?',
    'quality.docToEditable.a': 'Testo, titoli, elenchi, immagini e tabelle semplici passano in modo affidabile e restano pienamente modificabili. Poiché il {{fn}} memorizza posizioni anziché struttura, la conversione deve ricostruire quella struttura, quindi le pagine molto curate — più colonne, testo che avvolge le immagini, tabelle annidate complesse — possono richiedere una leggera sistemata dopo. Se il PDF è una scansione priva di qualsiasi livello testuale, usate invece lo strumento OCR: riconosce i caratteri nell’immagine anziché cercare un testo che non c’è.',
    'quality.docGeneric.q': 'Perdo qualcosa convertendo {{fn}} in {{tn}}?',
    'quality.docGeneric.a': 'Le parole, i titoli, gli elenchi e le immagini passano intatti. Il {{tn}} dispone di un vocabolario di formattazione diverso da quello del {{fn}}, quindi una formattazione molto specifica può essere semplificata lungo il percorso, ma il contenuto in sé viene conservato.',
    'quality.archive.q': 'I file dentro il mio {{fn}} verranno modificati?',
    'quality.archive.a': 'No. I formati di archivio sono contenitori senza perdita: il {{fn}} viene estratto e gli stessi identici file vengono reimpacchettati come {{tn}}, byte per byte. Cambiano solo il metodo di compressione e il contenitore. Ciò che cambia è la dimensione dell’archivio stesso — {{clause}}.',
    'quality.archive.clause.to7z': 'il 7Z produce in genere un archivio più piccolo dello ZIP grazie alla compressione LZMA',
    'quality.archive.clause.toZip': 'lo ZIP risulta di solito un po’ più grande di 7Z o RAR, ed è il prezzo per potersi aprire ovunque senza software aggiuntivo',
    'quality.archive.clause.other': 'il nuovo formato comprime in modo diverso, quindi la dimensione può spostarsi in entrambe le direzioni',
    'quality.imageToDoc.q': 'Le mie foto perderanno qualità dentro il {{tn}}?',
    'quality.imageToDoc.a': 'No. Ogni immagine {{fn}} viene inserita nel {{tn}} così com’è, una per pagina, senza essere ricompressa, quindi ciò che vedete nel documento è ciò che è uscito dalla fotocamera. Il {{tn}} peserà all’incirca la somma delle immagini, cosa che conviene sapere prima di inviarlo per e-mail — passate il risultato da Comprimi PDF se serve più leggero.',
    'quality.toGif.q': 'Perché il mio GIF appare peggiore del {{fn}} originale?',
    'quality.toGif.a': 'Perché il GIF è limitato a 256 colori per fotogramma. Un video o una foto ne contengono milioni, quindi il codificatore deve scegliere una tavolozza e approssimare tutto il resto, il che si manifesta come bande nelle sfumature e nei cieli. Il GIF inoltre non trasporta alcuna traccia audio. Entrambe le cose dipendono dal formato, non dalla conversione — tenete la clip breve e, se la perdita di colore conta più della riproduzione automatica in linea, un MP4 apparirà molto meglio pesando meno.',
    'quality.lossyToLossless.q': 'Convertire {{fn}} in {{tn}} migliora la qualità?',
    'quality.lossyToLossless.a': 'No — ed è di gran lunga il fraintendimento più comune su questa conversione. Il {{fn}} è con perdita: i dettagli che il suo codificatore ha scartato sono spariti per sempre e nulla può ricostruirli. Ciò che il {{tn}} vi dà è un contenitore senza perdita per quel che resta, così il file smette di degradarsi a ogni salvataggio o modifica successiva. È davvero utile quando state per {{clause}}, ma non recupererà una qualità già perduta.',
    'quality.lossyToLossless.edit.audio': 'montare, masterizzare o elaborare l’audio',
    'quality.lossyToLossless.edit.image': 'modificare, ritoccare o comporre l’immagine',
    'quality.losslessToLossy.q': 'Perderò qualità convertendo {{fn}} in {{tn}}?',
    'quality.losslessToLossy.a.audio': 'Un po’, ed è voluto: è così che il file si alleggerisce. Il {{tn}} è con perdita, quindi il codificatore scarta le informazioni che giudica meno percepibili. Con impostazioni ragionevoli la differenza è difficilissima da cogliere a orecchio, e potete alzare il bitrate nelle impostazioni avanzate se preferite scambiare dimensione con fedeltà. Conservate il file {{fn}} originale: resta la copia madre, e ricodificare il {{tn}} in seguito aggraverebbe la perdita.',
    'quality.losslessToLossy.a.visual': 'Un po’, ed è voluto: è così che il file si alleggerisce. Il {{tn}} è con perdita, quindi il codificatore scarta le informazioni che giudica meno percepibili. Con impostazioni ragionevoli la differenza è difficilissima da cogliere a occhio, e potete alzare il valore di qualità nelle impostazioni avanzate se preferite scambiare dimensione con fedeltà. Conservate il file {{fn}} originale: resta la copia madre, e ricodificare il {{tn}} in seguito aggraverebbe la perdita.',
    'quality.lossyToLossy.q': 'Perderò qualità convertendo {{fn}} in {{tn}}?',
    'quality.lossyToLossy.a.audio': 'Un poco. Entrambi i formati sono con perdita, quindi il {{fn}} viene decodificato e poi ricodificato come {{tn}}, e ogni generazione di codifica con perdita lascia andare un po’ di dettaglio. Con impostazioni normali non è qualcosa che la maggior parte delle persone nota all’ascolto, e potete alzare il bitrate nelle impostazioni avanzate. Da evitare è convertire lo stesso file avanti e indietro ripetutamente — è questo a rendere la perdita udibile.',
    'quality.lossyToLossy.a.visual': 'Un poco. Entrambi i formati sono con perdita, quindi il {{fn}} viene decodificato e poi ricodificato come {{tn}}, e ogni generazione di codifica con perdita lascia andare un po’ di dettaglio. Con impostazioni normali non è qualcosa che la maggior parte delle persone nota, e potete alzare la qualità nelle impostazioni avanzate. Da evitare è convertire lo stesso file avanti e indietro ripetutamente — è questo a rendere la perdita visibile.',
    'quality.losslessToLossless.q': 'Perderò qualità convertendo {{fn}} in {{tn}}?',
    'quality.losslessToLossless.a.plain': 'No. Sia {{fn}} sia {{tn}} sono senza perdita, quindi {{unit}} viene conservato esattamente e il risultato è identico all’originale. Cambia solo la dimensione del file. Potete riconvertire in seguito senza alcun degrado.',
    'quality.losslessToLossless.a.bulky': 'No. Sia {{fn}} sia {{tn}} sono senza perdita, quindi {{unit}} viene conservato esattamente e il risultato è identico all’originale. Cambia solo la dimensione del file, di solito in modo drastico verso il basso, perché il {{fn}} memorizza i suoi dati praticamente senza compressione. Potete riconvertire in seguito senza alcun degrado.',
    'quality.fallback.q': 'Perderò qualità convertendo {{fn}} in {{tn}}?',
    'quality.fallback.a': 'Per file normali il risultato è visivamente e funzionalmente equivalente all’originale. Dove i due formati supportano funzioni diverse, la conversione conserva tutto ciò che il {{tn}} è in grado di rappresentare. Le impostazioni avanzate vi permettono di alzare la qualità se il compromesso predefinito non è quello che volete.',

    'relation.uncompressed.q': 'Perché il file {{tn}} è molto più grande del {{fn}}?',
    'relation.uncompressed.a': 'Perché il {{tn}} non è compresso. Il {{fn}} alleggerisce l’audio scartando dati e codificando in modo efficiente ciò che resta; il {{tn}} scrive ogni campione a grandezza naturale, il che fa circa 10 MB per minuto di stereo in qualità CD. Un aumento di dieci volte è normale e previsto — è il prezzo di un file che il software di montaggio può elaborare senza decodificare prima nulla. Se volete audio senza perdita a circa metà del peso, convertite invece in FLAC.',
    'relation.extractAudio.q': 'Questo conserva il video o soltanto l’audio?',
    'relation.extractAudio.a': 'Soltanto l’audio. La traccia sonora viene estratta dal file {{fn}} e salvata come {{tn}}; la traccia video viene scartata, ed è per questo che il risultato pesa una frazione dell’originale. L’audio in sé non viene registrato di nuovo, quindi conserva la qualità che aveva dentro il {{fn}} — estrarre da un video a basso bitrate non può produrre audio ad alto bitrate.',
    'relation.videoContainer.q': 'Il mio {{tn}} si riprodurrà su telefoni, televisori e social?',
    'relation.videoContainer.a.mp4': 'È esattamente a questo che serve questa conversione. L’MP4 con video H.264 è la cosa più vicina a un formato video universale: iPhone, telefoni Android, smart TV, ogni browser, Instagram, YouTube, TikTok e ogni programma di montaggio diffuso lo accettano senza codec aggiuntivi. Il {{fn}} è il formato che vi stava dando problemi; l’MP4 è quello che non ne dà.',
    'relation.videoContainer.a.other': 'Il {{tn}} è più specializzato dell’MP4. {{note}} Se il vostro obiettivo è semplicemente «riprodursi ovunque», l’MP4 è la scelta più sicura — prendete il {{tn}} quando un programma o un apparecchio preciso lo ha richiesto.',
    'relation.alphaLost.q': 'Che fine fa la trasparenza convertendo {{fn}} in {{tn}}?',
    'relation.alphaLost.a': 'Il {{tn}} non ha canale alfa, quindi le aree trasparenti non possono essere trasferite: durante la conversione vengono riempite con uno sfondo pieno (bianco per impostazione predefinita). Se lo sfondo trasparente svolge un ruolo reale nel vostro progetto, convertite invece in PNG o WebP, che lo preservano entrambi. Se l’immagine è una fotografia senza alcuna trasparenza, non fa la minima differenza.',
    'relation.alphaGained.q': 'Convertire {{fn}} in {{tn}} rende trasparente lo sfondo?',
    'relation.alphaGained.a': 'No — e in molti ci cascano. Il {{tn}} supporta la trasparenza, ma un file {{fn}} non ha alcuna informazione di trasparenza da trasferire, quindi lo sfondo resta esattamente com’era. Ciò che la conversione vi dà è un file capace di contenere trasparenza una volta che avrete scontornato lo sfondo in un editor di immagini, oltre a pixel senza perdita che non si degraderanno mentre lavorate.',
    'relation.reflow.q': 'Il {{tn}} funzionerà sul mio e-reader?',
    'relation.reflow.a.epub': 'L’EPUB è letto da Apple Books, Kobo, Google Play Books, Calibre e praticamente ogni e-reader tranne il Kindle, che vuole MOBI o AZW3 (il Kindle ormai accetta anche EPUB via e-mail). Poiché il testo rifluisce, potete cambiare il corpo del carattere sul dispositivo senza finire per scorrere di lato — che è tutto il motivo per cui si converte un {{fn}} in partenza.',
    'relation.reflow.a.kindle': 'Il {{tn}} è letto dai dispositivi e dalle app Kindle per cui è stato progettato. Poiché il testo rifluisce, potete cambiare il corpo del carattere sul dispositivo senza finire per scorrere di lato — che è tutto il motivo per cui si converte un {{fn}} in partenza.',

    'compatibility.q': 'Con cosa potrò aprire poi il file {{tn}}?',
    'compatibility.a': '{{note}} Per fare la conversione non serve installare nulla — gira sui nostri server, e il {{tn}} finito torna nel vostro browser pronto da aprire, modificare o inoltrare. Il vostro {{fn}} originale non viene mai modificato; restituiamo sempre e solo un file nuovo.',
    'compatibility.noteFallback': 'Il {{tn}} è ampiamente supportato.',

    'shapeFaq.pdf-merge.q1': 'Unirli ridurrà la qualità dei miei PDF?',
    'shapeFaq.pdf-merge.a1': 'No. Le pagine vengono copiate nel nuovo documento esattamente come sono anziché essere rigenerate, quindi il testo resta selezionabile e le immagini conservano la risoluzione originale. Il file unito pesa all’incirca la somma degli originali — passatelo poi da Comprimi PDF se la cosa vi interessa.',
    'shapeFaq.pdf-merge.q2': 'Quanti PDF posso unire in una volta, e l’ordine conta?',
    'shapeFaq.pdf-merge.a2': 'Potete aggiungere tutti i file che vi servono in una sola volta, e l’ordine conta eccome: il documento finito segue l’ordine mostrato nell’elenco, che potete riordinare trascinando prima di unire. Fissate prima l’ordine, poi unite — è più rapido che correggerlo dopo.',
    'shapeFaq.pdf-split.q1': 'Come scelgo quali pagine estrarre?',
    'shapeFaq.pdf-split.a1': 'Digitatele nel campo degli intervalli di pagina usando virgole e trattini: «1-3, 5, 7-10» vi dà le pagine da uno a tre, la pagina cinque e le pagine da sette a dieci in un unico documento di uscita. I numeri si riferiscono alle pagine del PDF stesso, contate da uno, che non sempre coincidono con il numero stampato sulla pagina.',
    'shapeFaq.pdf-split.q2': 'Dividere modifica il PDF originale?',
    'shapeFaq.pdf-split.a2': 'No. Il file che caricate non viene mai modificato — le pagine estratte vengono scritte in un nuovo documento e l’originale resta intatto, prima di essere eliminato dai nostri server entro 24 ore insieme al risultato.',
    'shapeFaq.pdf-compress.q1': 'Di quanto si alleggerirà il mio PDF?',
    'shapeFaq.pdf-compress.a1': 'Dipende interamente da cosa c’è dentro. I PDF dominati da scansioni o fotografie spesso si riducono del 50-90%, perché è lì che risiede quasi tutto il peso. Un PDF di solo testo è già compatto e potrebbe cambiare a malapena. Testo e grafica vettoriale restano nitidi in ogni caso — il risparmio viene dalla ricodifica delle immagini e dall’eliminazione di dati incorporati ridondanti.',
    'shapeFaq.pdf-compress.q2': 'Il testo resterà selezionabile e ricercabile?',
    'shapeFaq.pdf-compress.a2': 'Sì. La compressione agisce sulle immagini incorporate e sui dati interni ridondanti; il livello testuale, i caratteri, i collegamenti e i segnalibri restano intatti, quindi potrete continuare a cercare, selezionare e copiare dal file compresso esattamente come prima.',
    'shapeFaq.pdf-compress-ai.q1': 'In cosa differisce dalla normale compressione PDF?',
    'shapeFaq.pdf-compress-ai.a1': 'La compressione normale applica un’unica impostazione a tutto il file. Questo strumento guarda prima cosa contiene davvero ogni pagina, così immagini fotografiche, diagrammi piatti e pagine di solo testo vengono trattati ciascuno nel modo che risparmia più spazio senza degradarli visibilmente. Sui documenti misti questo di solito significa un file più leggero a parità di qualità percepita.',
    'shapeFaq.pdf-compress-ai.q2': 'Il testo resterà selezionabile e ricercabile?',
    'shapeFaq.pdf-compress-ai.a2': 'Sì. Il livello testuale, i caratteri, i collegamenti e i segnalibri vengono conservati — vengono ricodificate solo le immagini incorporate e i dati interni ridondanti, quindi il PDF compresso resta pienamente ricercabile e copiabile.',
    'shapeFaq.pdf-rotate.q1': 'Ruotare un PDF fa perdere qualità?',
    'shapeFaq.pdf-rotate.a1': 'Assolutamente no. La rotazione cambia la geometria di pagina registrata nel file anziché rigenerare alcunché, quindi il testo resta nitido come vettoriale, le immagini restano intatte e la dimensione del file si muove appena. Potete ruotare di nuovo in seguito senza alcun danno cumulativo.',
    'shapeFaq.pdf-rotate.q2': 'Posso ruotare solo alcune pagine?',
    'shapeFaq.pdf-rotate.a2': 'La rotazione che scegliete — 90°, 180° o 270° — viene applicata al documento. Se pagine diverse sono sbagliate in direzioni diverse, l’approccio consueto è dividere il PDF, ruotare ogni parte dell’angolo che le serve e riunire i risultati con lo strumento Unisci PDF.',
    'shapeFaq.pdf-protect.q1': 'Cosa succede se dimentico la password?',
    'shapeFaq.pdf-protect.a1': 'Il file non potrà essere aperto. La cifratura si applica al PDF stesso, quindi non esiste alcun link di reimpostazione né alcuna porta di servizio — né per voi né per noi. Conservate la password in un posto sicuro prima di inoltrare il documento, e inviatela attraverso un canale diverso da quello del file.',
    'shapeFaq.pdf-protect.q2': 'Quanto è robusta la protezione?',
    'shapeFaq.pdf-protect.a2': 'Il PDF viene cifrato con lo schema standard di settore integrato nel formato, quindi il suo contenuto non può essere letto senza la password da alcun lettore conforme. Il punto debole pratico non è mai l’algoritmo ma la password stessa — una corta o ovvia si indovina in fretta, quindi usatene una lunga per qualsiasi cosa davvero riservata.',
    'shapeFaq.pdf-unlock.q1': 'Può rimuovere una password che non conosco?',
    'shapeFaq.pdf-unlock.a1': 'No. Dovete fornire la password attuale; lo strumento decifra il file con essa anziché forzare la cifratura. È pensato per documenti di vostra proprietà o che siete autorizzati ad aprire — un estratto conto della vostra banca, per esempio — dove la restrizione è semplicemente d’intralcio.',
    'shapeFaq.pdf-unlock.q2': 'Cosa posso fare con il file dopo?',
    'shapeFaq.pdf-unlock.a2': 'Tutto ciò che la protezione bloccava: aprirlo senza richiesta, stamparlo, copiarne il testo e modificarlo in altri programmi. Il contenuto delle pagine in sé è invariato — vengono rimossi solo il livello di cifratura e le sue restrizioni d’uso.',
    'shapeFaq.metadata.q1': 'Questo modifica il mio file in qualche modo?',
    'shapeFaq.metadata.a1': 'No. Il file viene letto, non convertito — non viene riscritto nulla e non viene prodotto nulla di nuovo tranne le informazioni mostrate a schermo. È lo strumento più sicuro qui da puntare su un file di cui non siete certi.',
    'shapeFaq.metadata.q2': 'Che tipo di informazioni vedrò?',
    'shapeFaq.metadata.a2': 'Dipende dal file. Le immagini mostrano dimensioni, profondità di colore e dati EXIF come modello di fotocamera, obiettivo, esposizione e, quando la fotocamera le ha registrate, coordinate GPS. L’audio mostra durata, bitrate, frequenza di campionamento e numero di canali. Il video aggiunge codec, risoluzione e frequenza dei fotogrammi. I documenti mostrano numero di pagine, autore, produttore e data di creazione.',
    'shapeFaq.ocr.q1': 'Quanto è preciso il riconoscimento del testo?',
    'shapeFaq.ocr.a1': 'Una scansione pulita e dritta di testo stampato a risoluzione ragionevole viene riconosciuta con grande precisione. La precisione cala con pagine storte o sfocate, fotografie poco contrastate, caratteri insoliti e scrittura a mano. Scegliere la lingua giusta conta, perché il riconoscimento la usa per sciogliere i caratteri ambigui.',
    'shapeFaq.ocr.q2': 'Qual è la differenza fra il PDF ricercabile e l’uscita in testo semplice?',
    'shapeFaq.ocr.a2': 'Il PDF ricercabile conserva l’immagine di pagina originale esattamente com’è e aggiunge sotto un livello di testo invisibile, così il documento appare invariato ma ora si può cercare e copiare — è ciò che serve per archiviare. Il testo semplice butta via l’impaginazione e vi dà solo le parole, che è ciò che serve per modificare, per gli script o per dare in pasto a un altro programma.',
    'shapeFaq.tts.q1': 'Quanto suonano naturali le voci?',
    'shapeFaq.tts.a1': 'Sono voci neurali e non la vecchia sintesi per concatenazione, quindi portano intonazione a livello di frase e pause naturali invece di leggere parola per parola. Sono disponibili sei voci, dalla neutra alla calda all’autorevole, e la velocità di lettura è regolabile. La punteggiatura conta più di quanto si pensi: virgole e punti danno forma al fraseggio, quindi un testo ben punteggiato viene letto sensibilmente meglio.',
    'shapeFaq.tts.q2': 'Quanto testo posso convertire in una volta?',
    'shapeFaq.tts.a2': 'Fino a 4096 caratteri per conversione — all’incirca 600-700 parole, ovvero circa cinque minuti di parlato. Per testi più lunghi, spezzateli in un punto naturale come un titolo di capitolo o di sezione e convertite ogni parte separatamente; le impostazioni di voce e velocità restano identiche fra un’esecuzione e l’altra, così i pezzi si raccordano puliti.',
    'shapeFaq.stt.q1': 'Quanto è precisa la trascrizione?',
    'shapeFaq.stt.a1': 'Il parlato chiaro in un ambiente ragionevolmente silenzioso viene trascritto con grande precisione, anche con un’ampia varietà di accenti. La precisione cala con molto rumore di fondo, con più persone che si sovrappongono, o con gergo molto specialistico e nomi propri. Indicare la lingua parlata anziché lasciare il rilevamento automatico aiuta sensibilmente.',
    'shapeFaq.stt.q2': 'Posso registrare direttamente dal microfono?',
    'shapeFaq.stt.a2': 'Sì — il registratore in questa pagina cattura l’audio direttamente nel browser, cosa spesso più rapida che andare a cercare prima un’app di registrazione. Il browser chiederà il permesso per il microfono la prima volta. Potete anche caricare un file esistente, e la trascrizione compare nella pagina così potete leggerla prima di scaricarla in TXT o DOCX.',
    'shapeFaq.subtitle.q1': 'Quanto sono precisi i sottotitoli generati?',
    'shapeFaq.subtitle.a1': 'Il parlato chiaro viene trascritto con grande precisione, anche con gli accenti. Musica di sottofondo, voci sovrapposte e terminologia specialistica sono i punti dove si insinuano gli errori, e indicare la lingua parlata anziché rilevarla automaticamente aiuta. L’uscita è un file di sottotitoli in testo semplice, quindi correggere qualche parola richiede secondi in un qualsiasi editor di testo.',
    'shapeFaq.subtitle.q2': 'Meglio SRT o VTT?',
    'shapeFaq.subtitle.a2': 'L’SRT è la scelta predefinita più sicura: YouTube, Vimeo, Premiere, Final Cut, VLC e praticamente ogni lettore lo accettano. Scegliete il VTT se i sottotitoli sono destinati a un lettore video HTML5 su un sito, perché il WebVTT è il formato che si aspetta la traccia sottotitoli nativa del browser e supporta stili e posizionamento che l’SRT non sa esprimere.',
    'shapeFaq.soon.q1': 'Quando sarà disponibile?',
    'shapeFaq.soon.a1': 'È in fase di sviluppo attivo. Lo strumento comparirà qui e comincerà ad accettare file non appena sarà pronto — dalla vostra parte non c’è nulla da installare o da attivare.',
    'shapeFaq.soon.q2': 'Cosa posso usare nel frattempo?',
    'shapeFaq.soon.a2': 'Il resto del convertitore è pienamente disponibile: documenti, immagini, audio, video, archivi, GIF e la cassetta degli attrezzi PDF funzionano tutti già oggi, così come le funzioni intelligenti per OCR, trascrizione e sottotitoli.',
    'shapeFaq.compress.q1': 'Il file compresso resterà un {{fn}}?',
    'shapeFaq.compress.a1': 'Sì — il formato non cambia, solo la dimensione. Ciò che scaricate è un normale {{fn}} che si apre ovunque si aprisse l’originale.{{alpha}} Quanto risparmiate dipende dal materiale di partenza: {{source}}.',
    'shapeFaq.compress.alpha': ' Trasparenza e animazione vengono conservate.',
    'shapeFaq.compress.source.png': 'screenshot e grafica d’interfaccia a tinte piatte si comprimono in modo spettacolare, mentre le fotografie salvate come PNG rendono meno',
    'shapeFaq.compress.source.gif': 'le animazioni lunghe e le riprese molto mosse si comprimono di più, perché c’è più ridondanza da eliminare',
    'shapeFaq.compress.source.other': 'le fotografie si comprimono bene, mentre le immagini già fortemente compresse hanno meno da dare',
    'shapeFaq.compress.q2': 'Di quanto si alleggerirà il file?',
    'shapeFaq.compress.a2': 'Di norma fra un terzo e un decimo dell’originale, a seconda interamente di cosa contiene il file e di come era stato salvato all’inizio. A conversione conclusa la pagina mostra affiancate le dimensioni prima e dopo, così vedete il risparmio reale invece di indovinarlo.',
    'shapeFaq.hub.q1': 'Fra quali formati posso convertire?',
    'shapeFaq.hub.a1': 'Ingresso: {{inputs}}. Uscita: {{outputs}}. Qualsiasi ingresso può andare verso qualsiasi uscita, quindi non dovete trovare una pagina diversa per ogni combinazione — scegliete il file, scegliete il formato di destinazione, convertite.',
    'shapeFaq.hub.q2': 'Perderò qualità?',
    'shapeFaq.hub.a2': 'Dipende dalla coppia. Passare a un formato senza perdita conserva tutto ma produce un file più grande; passare a un formato compresso scarta di proposito dei dati in cambio di dimensione, e le impostazioni avanzate vi lasciano decidere dove collocarvi su quel compromesso. Convertire fra due formati compressi lascia andare un po’ di dettaglio ogni volta, quindi vale la pena tenere l’originale come copia madre.',
    'shapeFaq.hub-extract.q1': 'Questo conserva anche il video?',
    'shapeFaq.hub-extract.a1': 'No — soltanto l’audio. La traccia sonora viene estratta dal video e salvata a parte, ed è per questo che il risultato pesa una frazione del file originale. L’audio non viene registrato di nuovo, quindi conserva la qualità che aveva già dentro il video; estrarre da una clip a basso bitrate non può produrre audio ad alto bitrate.',
    'shapeFaq.hub-extract.q2': 'Quale formato di uscita conviene scegliere?',
    'shapeFaq.hub-extract.a2': 'MP3 per la massima compatibilità — si riproduce su ogni telefono, autoradio e lettore. AAC o M4A se la destinazione è un dispositivo Apple o un’app moderna, perché suonano leggermente meglio a parità di bitrate. WAV o FLAC solo se avete intenzione di montare l’audio, perché sono entrambi senza perdita e quindi voluminosi.',
    'shapeFaq.hub-gif.q1': 'Perché il GIF appare peggiore dell’originale?',
    'shapeFaq.hub-gif.a1': 'Perché il GIF ammette solo 256 colori per fotogramma, mentre video e fotografie ne contengono milioni. Il codificatore sceglie una tavolozza e approssima il resto, il che si manifesta come bande nelle sfumature e nei cieli. Il GIF inoltre non trasporta alcun suono. Entrambi i limiti dipendono dal formato e non dalla conversione.',
    'shapeFaq.hub-gif.q2': 'Perché il mio file GIF è così grande?',
    'shapeFaq.hub-gif.a2': 'Il GIF comprime molto meno efficacemente dei codec video moderni, quindi la dimensione cresce in fretta con durata, risoluzione e frequenza dei fotogrammi. Pochi secondi sono il punto ideale. Se il risultato è troppo pesante, accorciate la clip, e se la dimensione conta più della riproduzione automatica in linea, un MP4 mostrerà la stessa animazione a una frazione del peso.',
  },
};
