// Dutch content pack. Mirrors packs/en.js key for key — see the header there.
export default {
  lang: 'nl',
  formats: {
    pdf: { about: 'PDF is een formaat met een vaste opmaak: het bewaart de exacte positie van elk teken, elke lijn en elke afbeelding, en daarom ziet een PDF er op elk scherm en elke printer identiek uit maar is hij lastig te bewerken.', note: 'PDF zet paginering, lettertypen en opmaak vast, zodat de ontvanger precies ziet wat u hebt verstuurd.' },
    docx: { about: 'DOCX is het moderne formaat van Microsoft Word, waarin tekst in bewerkbare alinea’s en stijlen leeft in plaats van vastgepind te zitten op vaste paginacoördinaten.', note: 'DOCX geeft u echte bewerkbare alinea’s, wijzigingen bijhouden en opmerkingen in Word, Google Docs of LibreOffice.' },
    xlsx: { about: 'XLSX is het spreadsheetformaat van Excel, waarin elke waarde in een adresseerbare cel staat die u kunt sorteren, filteren en in een formule gebruiken.', note: 'Zodra de gegevens in XLSX staan kunt u ze optellen, sorteren, in draaitabellen zetten en in grafieken tonen in plaats van ze over te typen.' },
    pptx: { about: 'PPTX bewaart een presentatie als losse dia’s met bewerkbare tekstvakken, vormen, sprekersnotities en overgangen.', note: 'PPTX geeft u dia’s die u echt opnieuw kunt bewerken, herschikken en presenteren.' },
    txt: { about: 'Een TXT-bestand is niets anders dan tekens — geen lettertypen, geen afbeeldingen, geen paginastructuur — waardoor het piepklein is, overal leesbaar en triviaal doorzoekbaar.', note: 'TXT haalt alles weg behalve de woorden, en dat is precies wat scripts, zoekindexen en teksteditors willen.' },
    html: { about: 'HTML is de opmaaktaal van het web: tekst verpakt in tags die een browser omzet in koppen, alinea’s, links en afbeeldingen.', note: 'HTML opent in elke browser en is rechtstreeks in een website of CMS te plakken.' },
    rtf: { about: 'RTF is een open documentformaat op basis van platte tekst dat basisopmaak meeneemt — vet, cursief, lettertypen, tabellen — zonder u aan één tekstverwerker vast te ketenen.', note: 'RTF opent in Word, Pages, LibreOffice, WordPad en vrijwel elke tekstverwerker die ooit is geschreven.' },
    odt: { about: 'ODT is het OpenDocument-tekstformaat van LibreOffice en OpenOffice, en het is een ISO-standaard in plaats van een fabrikantsformaat.', note: 'ODT is het eigen, volledig bewerkbare formaat van LibreOffice en OpenOffice.' },
    epub: { about: 'EPUB is een e-boekformaat met vloeiende tekst: het heeft geen vaste paginagrootte, dus de tekst loopt opnieuw door naar het scherm en de lettergrootte die de lezer gebruikt.', note: 'EPUB laat de lezer de lettergrootte wijzigen en de tekst opnieuw laten doorlopen, en dat maakt lange documenten prettig op een telefoon of e-reader.' },
    jpg: { about: 'JPG gebruikt compressie met kwaliteitsverlies die op foto’s is afgestemd: het gooit het detail weg dat het oog het minst opvalt, wat foto’s klein maakt maar zachte, blokkerige artefacten toevoegt rond harde randen en tekst.', note: 'JPG levert kleine bestanden die letterlijk overal openen, ten koste van wat permanent weggegooid detail en zonder transparantie.' },
    jfif: { about: 'JFIF is een JPEG-afbeelding die met een andere extensie is opgeslagen; de pixels erin zijn gewone JPEG-gegevens, maar Windows weigert vaak het bestand aan de app te geven die u wilt.', note: 'JFIF is eigenlijk gewoon JPEG onder een andere naam.' },
    png: { about: 'PNG is verliesvrij: het bewaart elke pixel exact, ondersteunt een volledig alfakanaal voor transparantie en gaat nooit achteruit als u het opnieuw opslaat, en daarom is het het formaat bij uitstek voor schermafbeeldingen, logo’s en interfacegrafiek.', note: 'PNG bewaart elke pixel precies zoals hij is en ondersteunt echte transparantie, dus het doorstaat herhaald bewerken zonder achteruit te gaan.' },
    webp: { about: 'WebP is het moderne webafbeeldingsformaat van Google; het comprimeert merkbaar sterker dan JPG of PNG bij vergelijkbare kwaliteit en ondersteunt transparantie en animatie, maar heel wat desktop- en drukwerksoftware kan het nog steeds niet openen.', note: 'WebP levert de kleinste bestanden van de gangbare webformaten en ondersteunt transparantie.' },
    bmp: { about: 'BMP bewaart ruwe, praktisch ongecomprimeerde pixelgegevens, wat het volmaakt getrouw en enorm verkwistend maakt — een foto is makkelijk tien keer groter dan diezelfde afbeelding als PNG.', note: 'BMP is ruw en ongecomprimeerd, en dat is wat oude Windows-software en sommige scanners nog steeds verwachten.' },
    tiff: { about: 'TIFF is het archief- en prepressformaat: verliesvrij, met hoge kleurdiepte, in staat meerdere pagina’s of lagen te bevatten — en navenant omvangrijk.', note: 'TIFF is het formaat waar drukkerijen en archieven om vragen, omdat er niets wordt weggegooid.' },
    gif: { about: 'GIF is beperkt tot een palet van 256 kleuren per frame, en daarom vertonen foto’s erin banden, maar het animeert en speelt bijna overal op internet vanzelf in de pagina af.', note: 'GIF animeert en speelt vanzelf af in chatapps, ticketsystemen en fora, maar zit vast aan 256 kleuren per frame.' },
    ico: { about: 'ICO is een Windows-pictogramcontainer die dezelfde afbeelding in meerdere formaten tegelijk bevat, zodat het systeem 16×16 kan kiezen voor een tabblad en 256×256 voor een bureaubladsnelkoppeling.', note: 'ICO bundelt meerdere resoluties in één bestand, en dat is precies wat favicons en Windows-programmapictogrammen nodig hebben.' },
    heic: { about: 'HEIC is het formaat waarin iPhones foto’s standaard opslaan; het levert ongeveer dezelfde kwaliteit als JPG in ongeveer de helft van de ruimte, maar Windows, veel webformulieren en een hoop oudere software weigeren het simpelweg te openen.', note: 'HEIC is compact maar wordt buiten Apple-apparaten slecht ondersteund.' },
    svg: { about: 'SVG bestaat helemaal niet uit pixels — het is XML die vormen, paden en tekst beschrijft, dus het blijft bij elk formaat haarscherp en kan met code worden bewerkt of opnieuw gestyled.', note: 'SVG schaalt naar elk formaat zonder ooit wazig te worden, omdat het vormen bewaart in plaats van pixels.' },
    mp4: { about: 'MP4 is een container — meestal H.264-video met AAC-audio — en het is het enige videoformaat waar telefoons, browsers, tv’s, montageprogramma’s en sociale platformen het allemaal over eens zijn.', note: 'MP4 speelt op vrijwel elke telefoon, browser, tv en montageprogramma zonder extra software.' },
    avi: { about: 'AVI is een Microsoft-container uit de jaren negentig; oude spelers en montagesuites lezen hem nog, maar hij heeft geen moderne streamingfuncties en zijn bestanden zijn doorgaans veel groter dan MP4.', note: 'AVI is wat oudere spelers, dvd-authoringgereedschap en verouderde montagesoftware verwachten.' },
    mov: { about: 'MOV is de QuickTime-container van Apple, het formaat waarin iPhones en Macs opnemen en waar Final Cut Pro en iMovie het soepelst mee omgaan.', note: 'MOV is de container waarmee de montagegereedschappen van Apple het soepelst werken.' },
    mkv: { about: 'MKV (Matroska) is een open container die een willekeurig aantal video-, audio- en ondertitelsporen in één bestand kan bevatten — uitstekend om te archiveren, maar geweigerd door de meeste telefoons, tv’s en browsers.', note: 'MKV kan meerdere audio- en ondertitelsporen in één bestand meedragen.' },
    webm: { about: 'WebM is de royaltyvrije container die voor HTML5-video is gemaakt, meestal met VP9 of AV1; browsers zijn er dol op, maar desktopmontageprogramma’s en Apple-software raken hem vaak niet aan.', note: 'WebM is klein en streamt van nature in browsers.' },
    wmv: { about: 'WMV is het Windows Media-videoformaat van Microsoft, feitelijk alleen voor Windows en grotendeels verlaten buiten oude bedrijfsopnames en schermopnames.', note: 'WMV is een Windows Media-formaat met erg weinig ondersteuning elders.' },
    flv: { about: 'FLV was de container achter Flash-video, en sinds Flash uit elke browser is verwijderd is het feitelijk een onafspeelbaar archiefformaat.', note: 'FLV is een dode container uit het Flash-tijdperk.' },
    mp3: { about: 'MP3 werkt met kwaliteitsverlies: de encoder wist definitief de delen van het signaal die u volgens zijn voorspelling toch niet hoort, waardoor een nummer tot ongeveer een tiende krimpt en het op werkelijk alles afspeelt.', note: 'MP3 is ongeveer tien keer kleiner dan ongecomprimeerde audio en speelt op elke telefoon, autoradio en speler van de afgelopen twintig jaar.' },
    wav: { about: 'WAV bewaart audio ongecomprimeerd, sample voor sample, precies zoals het is opgenomen — daarom gebruiken studio’s het, en daarom neemt één minuut stereo op cd-kwaliteit ongeveer 10 MB in beslag.', note: 'WAV is ongecomprimeerd en verliesvrij, zodat montage- en masteringprogramma’s het kunnen verwerken zonder eerst iets te decoderen.' },
    flac: { about: 'FLAC comprimeert audio verliesvrij: het is ongeveer half zo groot als WAV en decodeert toch terug naar een bit-voor-bit identieke kopie van de oorspronkelijke opname.', note: 'FLAC is bit-voor-bit identiek maar ongeveer half zo groot als WAV.' },
    aac: { about: 'AAC is de codec met kwaliteitsverlies achter Apple Music, YouTube en de meeste streamingdiensten; bij dezelfde bitrate klinkt hij doorgaans beter dan MP3.', note: 'AAC klinkt beter dan MP3 bij dezelfde bitrate en is de standaard binnen Apple en de streamingwereld.' },
    ogg: { about: 'OGG Vorbis is een octrooivrije codec met kwaliteitsverlies die geliefd is bij games, opensourcesoftware en Wikipedia, met een kwaliteit vergelijkbaar met MP3 bij kleinere bestanden.', note: 'OGG is vrij van octrooibeperkingen, en daarom geven game-engines en opensourceprojecten er de voorkeur aan.' },
    m4a: { about: 'M4A is een MP4-container die alleen audio bevat, normaal gesproken AAC — het formaat dat iTunes, Apple Music en de spraakmemo’s van de iPhone opleveren.', note: 'M4A is het standaard audiobestand van het Apple-ecosysteem.' },
    wma: { about: 'WMA is de audiocodec met kwaliteitsverlies van Microsoft uit het Windows Media Player-tijdperk, buiten Windows zelden ondersteund en feitelijk gestaakt.', note: 'WMA is een verouderde audiocodec die alleen op Windows leeft.' },
    zip: { about: 'ZIP is het archiefformaat dat in Windows, macOS en elke telefoon is ingebouwd — dubbelklikken werkt gewoon, zonder extra software te installeren.', note: 'ZIP opent met een dubbelklik op Windows, macOS, Linux, iOS en Android zonder dat er iets geïnstalleerd hoeft te worden.' },
    rar: { about: 'RAR is een gesloten archiefformaat met goede compressie en herstelgegevens, maar u hebt WinRAR of een compatibel programma nodig om het te openen.', note: 'RAR heeft software van derden nodig om uitgepakt te worden.' },
    '7z': { about: '7Z gebruikt LZMA-compressie, die geregeld merkbaar kleinere archieven oplevert dan ZIP — ten koste van 7-Zip of een compatibel programma om ze te openen.', note: '7Z comprimeert aanzienlijk strakker dan ZIP, wat telt bij grote mappen en betaalde cloudopslag.' },
    tar: { about: 'Een TAR-bestand bundelt veel bestanden tot één zonder ze te comprimeren; het komt uit de Unix-wereld en behoudt rechten en mappenstructuur.', note: 'TAR behoudt Unix-rechten en de mappenstructuur.' },
    gz: { about: 'GZ (gzip) comprimeert één enkele gegevensstroom en is wat Linux-servers en opdrachtregelgereedschap opleveren; op Windows is het zonder extra software lastig te openen.', note: 'GZ is het standaard compressieformaat op Linux en op webservers.' },
    srt: { about: 'SRT is het ondertitelformaat in platte tekst dat elk montageprogramma en elke speler begrijpt: genummerde regels, een tijdcodebereik en de dialoogregel.', note: 'SRT wordt geaccepteerd door YouTube, Vimeo, Premiere, Final Cut en elke gangbare speler.' },
  },
  reasons: {
    'pdf-to-word': 'De gebruikelijke aanleiding is een wijziging die u in de PDF zelf niet kunt maken — een contractbepaling, een regel in een cv of een alinea in een rapport die moet veranderen zonder het hele document over te typen.',
    'word-to-pdf': 'Mensen zetten Word om naar PDF helemaal aan het eind van de levensloop van een document: bij het versturen van een cv, een offerte of een ondertekend formulier naar iemand van wie u de lettertypen, Word-versie en marges niet in de hand hebt.',
    'pdf-to-excel': 'Het typische geval is een bankafschrift, een factuur of een rapport dat alleen als PDF bestaat maar waarvan u de getallen moet optellen, sorteren of in een grafiek zetten.',
    'excel-to-pdf': 'Dit doet u voordat u een begroting of prijslijst stuurt naar iemand die hem moet lezen maar niet wijzigen, en vóór het afdrukken — een PDF legt de pagina-einden vast die Excel anders op elke computer opnieuw zou berekenen.',
    'pptx-to-pdf': 'De meeste mensen zetten een presentatie om naar PDF voordat ze hem mailen of uitdelen, zodat de dia’s niet verschuiven en niemand PowerPoint hoeft te hebben om ze te openen.',
    'pdf-to-pptx': 'Dit hebt u nodig wanneer de enige overgebleven kopie van een presentatie de PDF is die na de vergadering rondging en u de dia’s moet bijwerken of hergebruiken.',
    'pdf-to-txt': 'Veelvoorkomende redenen: een document invoeren in een script, een zoekindex of een AI-hulpmiddel, of een lang rapport terugbrengen tot iets dat u kunt doorzoeken, vergelijken en overal plakken.',
    'pdf-to-html': 'Het is de snelste manier om een bestaand rapport, handboek of brochure op een website te publiceren zonder de pagina met de hand na te bouwen.',
    'html-to-pdf': 'Mensen doen dit om een webpagina precies te archiveren zoals hij er vandaag uitziet, of om een HTML-sjabloon voor een factuur of rapport om te zetten in iets afdrukbaars en verstuurbaars.',
    'rtf-to-pdf': 'RTF komt meestal uit oudere software of juridische documentsjablonen; er een PDF van maken geeft u één bestand dat overal identiek opent en niet per ongeluk gewijzigd kan worden.',
    'pdf-to-rtf': 'Dit is de keuze wanneer u een bewerkbare kopie van een PDF nodig hebt maar niet kunt aannemen dat de ontvanger Word heeft — praktisch elke tekstverwerker die ooit is geschreven opent RTF.',
    'odt-to-pdf': 'Het typische geval: u hebt het document in LibreOffice of OpenOffice geschreven en de ontvanger gebruikt Microsoft Office, of helemaal niets.',
    'pdf-to-epub': 'Een PDF op een telefoon lezen betekent voortdurend in- en uitzoomen en zijwaarts scrollen; deze omzetting draait er vooral om een lang document echt leesbaar te maken op een klein scherm of een e-reader.',
    'epub-to-pdf': 'Mensen zetten EPUB om naar PDF wanneer ze een boek willen afdrukken, het willen annoteren op vaste paginanummers, of het willen sturen naar iemand zonder e-readerapp.',
    'document-converter': 'Dit is het hulpmiddel dat u opent wanneer u een document krijgt in het formaat dat de afzender toevallig had en u het nodig hebt in het formaat dat uw eigen software daadwerkelijk opent.',
    'ebook-converter': 'E-boekwinkels en apparaten geven elk de voorkeur aan hun eigen formaat, dus dit gebruikt u om een boek dat van u is van de ene lezer of app naar de andere te verplaatsen.',
    'jpg-to-png': 'De gebruikelijke aanleiding is bewerken: u moet een achtergrond uitsnijden, een logo over een andere afbeelding leggen, of voorkomen dat een schermafbeelding bij elke keer opslaan waziger wordt.',
    'png-to-jpg': 'Dit is de oplossing voor een schermafbeelding of export die te groot is om als bijlage mee te sturen of om langs de groottelimiet van een uploadformulier te komen.',
    'webp-to-png': 'U hebt dit meestal nodig nadat u een afbeelding van een website hebt opgeslagen: WebP downloadt prima, maar oudere editors, kantoorsoftware en sommige drukwerkdiensten weigeren het nog altijd te openen.',
    'webp-to-jpg': 'De meeste mensen doen dit om een afbeelding van een website in iets universeel geaccepteerds te krijgen — een e-mail, een ouder CMS, een fotoafdrukdienst of de eeuwenoude software van een collega.',
    'heic-to-jpg': 'Dit is het klassieke iPhone-probleem: foto’s zien er prima uit op de telefoon maar belanden op een Windows-pc of in een webformulier als niet te openen .heic-bestanden.',
    'heic-to-png': 'Gebruik dit wanneer u de foto wilt bewerken en niet alleen delen — PNG geeft uw editor verliesvrije pixels in plaats van een vers opnieuw gecomprimeerde kopie.',
    'svg-to-png': 'De gebruikelijke reden is een programma dat vectoren weigert: een presentatie, een advertentie op een marktplaats, een e-mailhandtekening of een pictogrampijplijn die alleen pixels accepteert.',
    'svg-to-jpg': 'Dit is voor plekken die een gewoon fotoachtig bestand willen — een document, een bericht op sociale media of een uploadformulier dat zowel SVG-opmaak als transparantie weigert.',
    'bmp-to-png': 'BMP-bestanden komen uit oude Windows-software en scanners met absurde afmetingen; PNG bewaart precies dezelfde pixels in een fractie van de ruimte.',
    'tiff-to-jpg': 'Scanners en professionele camera’s leveren TIFF’s die veel te groot zijn om te mailen, dus JPG is wat u stuurt zodra de archiefkopie veilig is opgeborgen.',
    'gif-to-png': 'Dit doet u met een stilstaande GIF — een logo, een pictogram of een geëxporteerd frame — die kleurbanden of een gerafelde rand vertoont door de limiet van 256 kleuren.',
    'png-to-ico': 'Bijna iedereen die PNG naar ICO omzet maakt een favicon of een Windows-programmapictogram, en beide verwachten de ICO-container in plaats van een gewoon afbeeldingsbestand.',
    'jfif-to-png': 'JFIF-bestanden duiken meestal op wanneer een foto uit Outlook of een browser wordt opgeslagen en Windows hem vervolgens weigert door te geven aan de app die u eigenlijk wilde gebruiken.',
    'heic-to-pdf': 'Handig wanneer u documenten, bonnetjes of een whiteboard met een iPhone fotografeert en ze als één bestand moet indienen in plaats van als een map vol afbeeldingen.',
    'image-compressor': 'De gebruikelijke reden is ergens een harde limiet — een uploadformulier, een maximum voor e-mailbijlagen, of een webpagina die te traag laadt omdat de afbeeldingen veel groter zijn dan nodig.',
    'jpeg-compressor': 'Fotografen en site-eigenaren gebruiken dit wanneer JPEG’s op volle resolutie een pagina afremmen of niet door een uploadlimiet passen.',
    'png-compressor': 'Schermafbeeldingen en geëxporteerde interfacegrafiek zijn vaak zonder goede reden enkele megabytes groot; dit krimpt ze voordat ze in een document, een ticket of een webpagina belanden.',
    'mp4-to-avi': 'De reden is bijna altijd een ouder apparaat of een specifiek programma — sommige oude spelers, dvd-authoringgereedschappen en camerahulpprogramma’s lezen AVI en verder niets.',
    'mp4-to-mov': 'Dit is normaal de eerste stap voordat u op een Mac gaat monteren, omdat Final Cut Pro en iMovie het soepelst met QuickTime-bestanden omgaan.',
    'mov-to-mp4': 'iPhones en Macs nemen op in MOV; al het andere verwacht MP4, dus dit is de omzetting die mensen doen voordat ze een clip uploaden, mailen of plaatsen.',
    'mkv-to-mp4': 'MKV is uitstekend om op te slaan, maar telefoons, tv’s, browsers en de meeste montageprogramma’s spelen het niet af — omzetten naar MP4 is wat het bestand daadwerkelijk bruikbaar maakt.',
    'webm-to-mp4': 'WebM-bestanden die van het web zijn opgeslagen weigeren vaak te openen in QuickTime, op iOS of in Premiere; MP4 is het formaat dat ze allemaal accepteren.',
    'avi-to-mp4': 'Dit is de standaardredding voor oude camcorderbeelden en gearchiveerde clips die gigabytes opslokken en op geen enkele telefoon afspelen.',
    'flv-to-mp4': 'Flash is uit elke browser verdwenen, dus elke FLV die u nog hebt is feitelijk onafspeelbaar — omzetten naar MP4 houdt dat gearchiveerde materiaal kijkbaar.',
    'wmv-to-mp4': 'WMV is een restant dat alleen op Windows leeft, dus dit doet u voordat u een oude opname of schermopname naar een Mac, een iPhone of een webplatform stuurt.',
    'mp4-to-mp3': 'Het gaat meestal om het geluid en niet om het beeld — een college, een interview, een podcast of een videoclip die u op uw telefoon wilt zonder de video mee te sjouwen.',
    'video-to-mp3': 'Mensen grijpen hiernaar wanneer de audio het deel is dat het bewaren waard is: een opgenomen lezing, een interview, een repetitie of een soundtrack.',
    'mp4-converter': 'Dit is het hulpmiddel wanneer een clip niet afspeelt of niet uploadt, want MP4 is het enige videoformaat dat telefoons, browsers, tv’s en sociale platformen allemaal accepteren.',
    'video-converter': 'Gebruik het wanneer een clip van wereld moet wisselen — uit een montageprogramma, naar een telefoon, een browser in, of naar een platform dat maar één specifieke container aanneemt.',
    'mp3-to-wav': 'De gebruikelijke reden is bewerken: DAW’s, masteringketens en veel audiopijplijnen voor omroep of games willen ongecomprimeerde WAV, zodat ze niet bij elke bewerking een gecomprimeerd bestand hoeven te decoderen.',
    'wav-to-mp3': 'Opnames komen als enorme WAV-bestanden uit een veldrecorder of DAW; MP3 maakt ze klein genoeg om te mailen, te uploaden of op een telefoon te zetten.',
    'flac-to-mp3': 'Een FLAC-bibliotheek klinkt thuis uitstekend, maar autoradio’s, oudere telefoons en goedkope spelers weigeren hem vaak — MP3 is de compatibiliteitskopie die u meeneemt.',
    'aac-to-mp3': 'Dit is vooral een kwestie van compatibiliteit: AAC komt uit de Apple- en streamingwereld, terwijl oudere spelers, autoradio’s en dj-software MP3 verwachten.',
    'ogg-to-mp3': 'OGG duikt op in games, op Wikipedia en in opensourcesoftware, en vrijwel geen van de gangbare spelers op een telefoon of in een auto opent het.',
    'wma-to-mp3': 'WMA is een overblijfsel uit het Windows Media Player-tijdperk, en zo redt men een oude geripte muziekverzameling voor een telefoon of een streamingbibliotheek.',
    'm4a-to-mp3': 'Dit is de gebruikelijke stap bij het verplaatsen van muziek of iPhone-spraakmemo’s van Apple-apparaten naar software, auto’s of spelers die alleen MP3 begrijpen.',
    'mp3-to-aac': 'Sommige apparaten en apps — vooral binnen Apple en de streamingplatformen — geven de voorkeur aan AAC, dus dit is een compatibiliteitsomzetting en geen kwaliteitsverbetering.',
    'mp3-to-ogg': 'Mensen zetten om naar OGG voor game-engines, opensourceprojecten en platformen waar een octrooivrije codec vereist is.',
    'audio-converter': 'Dit is het hulpmiddel voor het moment waarop een bestand niet afspeelt: één plek om audio om te zetten naar precies dat gangbare formaat waar uw apparaat, uw editor of uw uploadformulier op staat.',
    'rar-to-zip': 'RAR heeft extra software nodig om te openen, dus dit doet u voordat u een archief stuurt naar iemand die WinRAR niet gaat installeren.',
    '7z-to-zip': '7Z comprimeert beter maar vereist dat 7-Zip is geïnstalleerd; als ZIP kan de ontvanger simpelweg op het bestand dubbelklikken.',
    'tar-to-zip': 'TAR komt van de Linux- en macOS-opdrachtregel, terwijl ZIP is wat een collega op Windows kan openen zonder ook maar iets te installeren.',
    'gz-to-zip': 'GZ-bestanden komen meestal van een server of uit een Linux-programma en zijn lastig op Windows, waar een ZIP met een dubbelklik uitpakt.',
    'zip-to-7z': 'Hier gaat het om grootte: de compressie van 7Z is merkbaar sterker, wat telt wanneer u een grote map archiveert of per gigabyte voor cloudopslag betaalt.',
    'video-to-gif': 'Het typische gebruik is een korte lus voor een chatbericht, een README, een bugmelding of een bericht op sociale media — plekken waar een GIF vanzelf in de pagina afspeelt en een videobestand niet.',
    'mp4-to-gif': 'Het typische gebruik is een korte lus voor een chat, een README, een bugmelding of een bericht, waar een GIF vanzelf in de pagina afspeelt terwijl een video er alleen als bijlage bij zou hangen.',
    'webm-to-gif': 'WebM-clips die van het web zijn opgeslagen laten zich vaak niet insluiten waar u ze wilt, terwijl een GIF gewoon afspeelt in chatapps, ticketsystemen en fora.',
    'mov-to-gif': 'Dit doet u met een QuickTime-schermopname die ingesloten moet verschijnen in een pull request, een supportticket of een bericht.',
    'avi-to-gif': 'Een paar seconden van een oude AVI-clip in een GIF veranderen is de makkelijkste manier om ze in een document, een chatdraad of een webpagina te krijgen.',
    'gif-to-mp4': 'Lange GIF’s zijn enorm en spelen schokkerig af; MP4 laat dezelfde animatie zien voor een fractie van de grootte, en precies daarom zetten sociale platformen ze achter de schermen om.',
    'image-to-gif': 'Handig wanneer een platform of een ouder systeem uitdrukkelijk een GIF verwacht, of wanneer u een stilstaand beeld nodig hebt in hetzelfde formaat als een bestaande reeks animaties.',
    'gif-compressor': 'Geanimeerde GIF’s zwellen snel op, en dit is de oplossing wanneer er een te zwaar is voor een e-mail, een uploadlimiet in een chat of een pagina die snel moet laden.',
    'merge-pdf': 'Het klassieke geval is een aanvraag of een schademelding: een formulier, een scan en een bon die allemaal als één document moeten aankomen.',
    'split-pdf': 'Meestal hebt u precies één ding nodig uit een veel langer bestand — één hoofdstuk, één factuur, één ondertekende pagina uit een scan van vijftig pagina’s.',
    'compress-pdf': 'Bijna altijd een groottelimiet: een maximum voor e-mailbijlagen, een uploadformulier van de overheid, of een portaal dat alles boven een paar megabytes weigert.',
    'rotate-pdf': 'Dit lost het alledaagse scannerprobleem op — pagina’s die er zijwaarts of ondersteboven uitkwamen door de manier waarop de vellen zijn ingevoerd.',
    'protect-pdf': 'Mensen beveiligen PDF’s met een wachtwoord voordat ze loonstroken, contracten of medische brieven mailen, zodat de inhoud niet leesbaar is voor degene naar wie het bericht daarna wordt doorgestuurd.',
    'unlock-pdf': 'Gebruik het op documenten die van u zijn wanneer het wachtwoord bekend is maar de beperking in de weg zit — een bankafschrift dat u niet kunt afdrukken, bijvoorbeeld.',
    'view-metadata': 'Het beantwoordt de vragen die een bestand u niet rechtstreeks vertelt: welke camera heeft deze foto gemaakt, hoe lang is deze opname echt, welke codec zit er in deze video, hoeveel pagina’s heeft deze PDF.',
    'ocr': 'De situatie is altijd dezelfde: u hebt een document als afbeelding en u hebt de woorden eruit nodig — om te doorzoeken, te citeren, te bewerken of fatsoenlijk te archiveren.',
    'pdf-compress-ai': 'Grijp ernaar wanneer gewone compressie al is geprobeerd en het bestand nog steeds te groot is voor de uploadlimiet waar u tegenaan loopt.',
    'text-to-speech': 'Mensen gebruiken het om ergens naar te luisteren in plaats van het te lezen — een artikel onderweg naar het werk, een script hardop teruggelezen om houterige zinnen te vinden, of een voice-over voor een video.',
    'speech-to-text': 'Het gebruikelijke geval is een opname die u op schrift nodig hebt: een vergadering, een interview, een college of een spraakmemo dat aantekeningen, notulen of een citeerbaar transcript moet worden.',
    'auto-subtitle': 'Ondertitels maken een video kijkbaar zonder geluid en vindbaar voor zoekmachines, en ze met de hand typen kost zelfs bij een korte clip veel meer tijd dan mensen denken.',
    'document-translation': 'Het doel is een document in een andere taal te lezen of te versturen zonder de opmaak te verliezen die het leesbaar maakt.',
  },
  t: {
    'list.and': 'en',
    'family.document': 'document',
    'family.image': 'afbeeldings',
    'family.video': 'video',
    'family.audio': 'audio',
    'family.ebook': 'e-boek',
    'family.archive': 'archief',
    'family.subtitle': 'ondertitel',
    'family.none': 'bestands',
    'unit.sample': 'elke sample',
    'unit.pixel': 'elke pixel',

    'intro.convert': '{{fromAbout}} {{toAbout}} {{reason}} {{toNote}}',
    'intro.convert.noSource': '{{fn}} is het bronformaat van deze omzetting.',
    'intro.lead': '{{lead}} {{reason}}',
    'intro.hub': 'Dit is de algemene {{category}}converter: hij accepteert {{inputs}} en schrijft {{outputs}}, zodat u niet op zoek hoeft naar dat ene specifieke hulpmiddel dat bij uw formaatpaar past. {{reason}} Kies hierboven uw uitvoerformaat; de omzetting gebeurt op de server — u hoeft niets te installeren.',
    'intro.hubExtract': 'Dit hulpmiddel haalt het geluidsspoor uit een videobestand en slaat het apart op, waarmee een video een gewoon audiobestand wordt dat overal afspeelt. Het accepteert {{inputs}} en schrijft {{outputs}}. Het videospoor wordt eenvoudigweg weggegooid, en daarom is het resultaat een fractie van de oorspronkelijke grootte. {{reason}}',
    'intro.hubGif': 'Dit hulpmiddel maakt van {{inputs}}-bestanden geanimeerde GIF’s. {{gifAbout}} {{reason}}',
    'intro.hubGif.gifAbout': 'GIF is beperkt tot een palet van 256 kleuren per frame, en daarom vertonen foto’s erin banden, maar het animeert en speelt bijna overal op internet vanzelf in de pagina af.',
    'intro.compress': '{{about}} Dit hulpmiddel codeert uw {{fn}} opnieuw met een kleinere bestandsgrootte zonder het formaat te veranderen, dus wat u downloadt is nog steeds een gewone {{fn}} die precies daar opent waar het origineel ook opende. {{reason}}{{extra}}',
    'intro.compress.lossless': ' Omdat {{fn}} verliesvrij is, komt de meeste besparing uit slimmere codering en een kleiner kleurenpalet en niet uit het weggooien van detail.',
    'intro.soon': '{{reason}} Dit hulpmiddel is nog niet beschikbaar — het wordt momenteel ontwikkeld en verschijnt hier zodra het klaar is.',
    'intro.lead.pdf-merge': 'Samenvoegen combineert meerdere PDF’s tot één bestand, in de volgorde die u kiest, zonder de pagina’s opnieuw op te bouwen — tekst blijft selecteerbaar en afbeeldingen behouden hun oorspronkelijke kwaliteit. PDF is een formaat met een vaste opmaak: het bewaart de exacte positie van elk teken, elke lijn en elke afbeelding, en daarom ziet het er overal identiek uit maar is het lastig te bewerken.',
    'intro.lead.pdf-split': 'Splitsen haalt de pagina’s die u noemt uit een PDF en bewaart ze als een nieuw document, terwijl het origineel onaangeroerd blijft. PDF is een formaat met een vaste opmaak: het bewaart de exacte positie van elk teken, elke lijn en elke afbeelding, en daarom ziet het er overal identiek uit maar is het lastig te bewerken.',
    'intro.lead.pdf-compress': 'Een PDF comprimeren codeert de afbeeldingen erin opnieuw en verwijdert overbodige ingesloten gegevens — daar zit bij een grote PDF vrijwel de hele omvang. Tekst en vectorafbeeldingen blijven haarscherp.',
    'intro.lead.pdf-compress-ai': 'Dit hulpmiddel analyseert eerst wat er in de PDF zit voordat het comprimeert, zodat fotografische afbeeldingen, vlakke grafiek en tekstpagina’s elk behandeld worden op de manier die de meeste ruimte bespaart zonder ze zichtbaar te verslechteren.',
    'intro.lead.pdf-rotate': 'Draaien verandert de oriëntatiemarkering en paginageometrie van een PDF zodat de pagina’s rechtop worden weergegeven en afgedrukt. Er wordt niets opnieuw opgebouwd, dus er gaat geen kwaliteit verloren.',
    'intro.lead.pdf-protect': 'Een PDF beveiligen versleutelt de inhoud zodat hij niet geopend kan worden zonder het wachtwoord dat u instelt. De versleuteling wordt op het bestand zelf toegepast, niet op een omhulsel eromheen.',
    'intro.lead.pdf-unlock': 'Ontgrendelen verwijdert het wachtwoord en de gebruiksbeperkingen uit een PDF waarvan u het wachtwoord al hebt, zodat hij weer normaal geopend, afgedrukt en gekopieerd kan worden.',
    'intro.lead.metadata': 'Elk bestand draagt informatie over zichzelf mee die u niet ziet als u het opent: afbeeldingsafmetingen en camera-instellingen, audioduur en bitrate, videocodec en beeldsnelheid, documentauteur en paginaaantal. Dit hulpmiddel leest die metagegevens en laat ze u zien.',
    'intro.lead.ocr': 'Optische tekenherkenning kijkt naar een afbeelding van tekst — een scan, een foto, een PDF-pagina zonder tekstlaag — en leidt af welke tekens er staan, waarmee een plaatje van woorden verandert in woorden die een computer kan doorzoeken, kopiëren en bewerken.',
    'intro.lead.tts': 'Tekst-naar-spraak genereert gesproken audio uit geschreven tekst met neurale stemmen, zodat u een natuurlijk klinkende opname krijgt in plaats van de vlakke, robotachtige uitvoer van oudere systemen.',
    'intro.lead.stt': 'Spraak-naar-tekst zet gesproken audio om in geschreven woorden. Het gaat veel beter om met natuurlijke spraak, accenten en achtergrondgeluid dan dicteersoftware vroeger deed, en levert een transcript dat u kunt bewerken.',
    'intro.lead.subtitle': 'De ondertitelgenerator transcribeert de spraak in een video en schrijft die weg met tijdcodes, wat een gangbaar ondertitelbestand oplevert in plaats van een kaal transcript.',

    'steps.convert.1.batch': 'Sleep uw {{fn}}-bestand naar het uploadvak boven aan deze pagina, of klik erop om op uw apparaat te bladeren. U kunt meerdere bestanden — of een hele map — toevoegen en ze in één keer omzetten.',
    'steps.convert.1.single': 'Sleep uw {{fn}}-bestand naar het uploadvak boven aan deze pagina, of klik erop om op uw apparaat te bladeren.',
    'steps.convert.2.direct': 'Kies {{tn}} als uitvoerformaat en klik op Converteren.',
    'steps.convert.2.dropdown': 'Kies {{tn}} als uitvoerformaat in de keuzelijst en klik op Converteren.',
    'steps.convert.2.directMedia': 'Kies {{tn}} als uitvoerformaat, pas zo nodig kwaliteit of afmetingen aan bij de geavanceerde instellingen en klik op Converteren.',
    'steps.convert.2.dropdownMedia': 'Kies {{tn}} als uitvoerformaat in de keuzelijst, pas zo nodig kwaliteit of afmetingen aan bij de geavanceerde instellingen en klik op Converteren.',
    'steps.convert.3': 'Download uw voltooide {{tn}}-bestand. De downloadlink blijft 24 uur actief, daarna worden beide bestanden automatisch verwijderd.',
    'steps.hub.1.batch': 'Sleep uw {{category}}bestand ({{inputs}} worden allemaal geaccepteerd) naar het uploadvak boven aan deze pagina, of klik erop om op uw apparaat te bladeren. U kunt meerdere bestanden — of een hele map — toevoegen en ze in één keer omzetten.',
    'steps.hub.1.single': 'Sleep uw {{category}}bestand ({{inputs}} worden allemaal geaccepteerd) naar het uploadvak boven aan deze pagina, of klik erop om op uw apparaat te bladeren.',
    'steps.hub.2.direct': 'Kies het uitvoerformaat dat u nodig hebt en klik op Converteren.',
    'steps.hub.2.dropdown': 'Kies in de keuzelijst het uitvoerformaat dat u nodig hebt en klik op Converteren.',
    'steps.hub.2.directMedia': 'Kies het uitvoerformaat dat u nodig hebt, pas zo nodig kwaliteit of afmetingen aan bij de geavanceerde instellingen en klik op Converteren.',
    'steps.hub.2.dropdownMedia': 'Kies in de keuzelijst het uitvoerformaat dat u nodig hebt, pas zo nodig kwaliteit of afmetingen aan bij de geavanceerde instellingen en klik op Converteren.',
    'steps.hub.3': 'Download uw voltooide bestand. De downloadlink blijft 24 uur actief, daarna worden beide bestanden automatisch verwijderd.',
    'steps.pdf-merge.1': 'Voeg elke PDF toe die u wilt combineren — sleep ze samen naar het uploadvak, of klik om ze een voor een te selecteren.',
    'steps.pdf-merge.2': 'Sleep de bestanden in de volgorde waarin u ze in het voltooide document wilt zien.',
    'steps.pdf-merge.3': 'Klik op Samenvoegen en download de ene gecombineerde PDF.',
    'steps.pdf-split.1': 'Upload de PDF waar u pagina’s uit wilt halen.',
    'steps.pdf-split.2': 'Typ de pagina’s of reeksen die u nodig hebt in het veld voor paginabereiken — bijvoorbeeld 1-3, 5, 7-10.',
    'steps.pdf-split.3': 'Klik op Converteren en download de uitgenomen pagina’s.',
    'steps.pdf-compress.1': 'Sleep uw PDF naar het uploadvak, of klik om ernaar te bladeren.',
    'steps.pdf-compress.2': 'Klik op Converteren — het bestand wordt geanalyseerd en de afbeeldingen en ingesloten gegevens worden kleiner gecodeerd.',
    'steps.pdf-compress.3': 'Download de gecomprimeerde PDF en bekijk de besparing die ernaast wordt getoond.',
    'steps.pdf-rotate.1': 'Upload de PDF waarvan de pagina’s verkeerd om staan.',
    'steps.pdf-rotate.2': 'Kies hoe ver u ze wilt draaien — 90°, 180° of 270°.',
    'steps.pdf-rotate.3': 'Klik op Converteren en download de gecorrigeerde PDF.',
    'steps.pdf-protect.1': 'Upload de PDF die u wilt beveiligen.',
    'steps.pdf-protect.2': 'Voer het wachtwoord in dat nodig zal zijn om hem te openen, en bewaar er een kopie van op een veilige plek.',
    'steps.pdf-protect.3': 'Klik op Converteren en download de versleutelde PDF.',
    'steps.pdf-unlock.1': 'Upload de met een wachtwoord beveiligde PDF.',
    'steps.pdf-unlock.2': 'Voer het huidige wachtwoord in zodat het bestand ontsleuteld kan worden.',
    'steps.pdf-unlock.3': 'Klik op Converteren en download de ontgrendelde PDF.',
    'steps.metadata.1': 'Sleep een willekeurig bestand naar het uploadvak — een afbeelding, een video, een audiobestand of een document.',
    'steps.metadata.2': 'Het bestand wordt onderzocht en niet omgezet, dus er verandert niets aan.',
    'steps.metadata.3': 'Lees de metagegevens rechtstreeks op de pagina: afmetingen, duur, codec, cameradetails, paginaaantal en meer.',
    'steps.ocr.1': 'Upload de gescande PDF of de foto van de tekst.',
    'steps.ocr.2': 'Kies de taal van het document en of u een doorzoekbare PDF of platte tekst wilt.',
    'steps.ocr.3': 'Klik op Converteren en download het resultaat, met de herkende tekst nu selecteerbaar en doorzoekbaar.',
    'steps.tts.1': 'Typ of plak uw tekst in het vak — tot 4096 tekens per omzetting.',
    'steps.tts.2': 'Kies een stem, een spreeksnelheid en een uitvoerformaat.',
    'steps.tts.3': 'Klik op Converteren en download het voltooide audiobestand.',
    'steps.stt.1': 'Upload uw opname, of neem rechtstreeks op met uw microfoon via de knop op deze pagina.',
    'steps.stt.2': 'Stel desgewenst de gesproken taal in voor meer nauwkeurigheid, en kies TXT- of DOCX-uitvoer.',
    'steps.stt.3': 'Klik op Converteren, lees het transcript op de pagina en download het daarna.',
    'steps.subtitle.1': 'Upload de video die u wilt ondertitelen.',
    'steps.subtitle.2': 'Kies SRT of VTT, en stel de gesproken taal in als u die kent.',
    'steps.subtitle.3': 'Klik op Converteren en download het ondertitelbestand met tijdcodes, klaar om in uw speler of montageprogramma te zetten.',
    'steps.compress.1': 'Sleep uw {{fn}}-afbeeldingen naar het uploadvak, of klik om te bladeren. U kunt een hele map in één keer toevoegen.',
    'steps.compress.1.gif': 'Sleep uw {{fn}}-animatie naar het uploadvak, of klik om te bladeren. U kunt een hele map in één keer toevoegen.',
    'steps.compress.2': 'Klik op Converteren — het bestand wordt kleiner gecodeerd en blijft in hetzelfde formaat.',
    'steps.compress.3': 'Download het resultaat en vergelijk het met de oorspronkelijke grootte die op de pagina staat.',
    'steps.soon.1': 'Kies het hulpmiddel dat u nodig hebt op de pagina Hulpmiddelen — alles behalve dit werkt vandaag al.',
    'steps.soon.2': 'Upload uw bestand en kies een uitvoerformaat.',
    'steps.soon.3': 'Download het resultaat, of kijk hier weer even wanneer documentvertaling live gaat.',

    'faq.cost.q.pair': 'Is {{from}} naar {{to}} converteren gratis?',
    'faq.cost.q.tool': 'Is {{label}} gratis te gebruiken?',
    'faq.cost.a.pair': "Elke omzetting van {{from}} naar {{to}} gebruikt één tegoed uit een klein vooruitbetaald pakket — er is geen abonnement, tegoeden verlopen nooit, en voor een mislukte omzetting betaalt u niets.",
    'faq.cost.a.tool': "Elke omzetting gebruikt één tegoed uit een klein vooruitbetaald pakket — er is geen abonnement, tegoeden verlopen nooit, en voor een mislukte omzetting betaalt u niets.",
    'faq.cost.a.smartTts': "De slimme functies worden per gebruik afgerekend in plaats van per bestand — 1 tegoed per 1000 tekens tekst, naar boven afgerond. Er is geen abonnement: tegoeden koopt u in kleine vooruitbetaalde pakketten, ze verlopen nooit, en een mislukte omzetting kost nooit iets.",
    'faq.cost.a.smartAv': "De slimme functies worden per gebruik afgerekend in plaats van per bestand — 1 tegoed per 5 minuten audio of video, naar boven afgerond. Er is geen abonnement: tegoeden koopt u in kleine vooruitbetaalde pakketten, ze verlopen nooit, en een mislukte omzetting kost nooit iets.",
    'faq.cost.q.metadata': 'Is het hulpmiddel Bestandsinfo gratis?',
    'faq.cost.a.metadata': 'Ja. De metagegevens van een bestand lezen is geen omzetting en kost dus geen tegoed — u kunt zoveel bestanden bekijken als u wilt. Tegoeden worden alleen besteed wanneer een hulpmiddel daadwerkelijk een nieuw bestand voor u maakt.',
    'faq.cost.q.soon': 'Is {{label}} al beschikbaar?',
    'faq.cost.a.soon': 'Nog niet — deze pagina is een plaatshouder terwijl het hulpmiddel wordt gebouwd, dus er valt hier vandaag niets te uploaden. De prijs volgt hetzelfde vooruitbetaalde tegoedmodel als de rest van de site: geen abonnement, tegoeden die nooit verlopen, en geen kosten voor een mislukte omzetting.',

    'faq.time.q.pair': 'Hoe lang duurt de omzetting van {{from}} naar {{to}}?',
    'faq.time.q.tool': 'Hoe lang duurt {{label}}?',
    'faq.time.a': '{{speed}} De uploadsnelheid is meestal de beperkende factor, dus een groot bestand op een trage verbinding kost meer tijd dan de omzetting zelf.{{suffix}}',
    'faq.time.speed.image': 'Afbeeldingen zijn het snelste wat we omzetten — één foto is normaal binnen vijf seconden klaar, en een hele map kost ongeveer net zo veel tijd als de upload zelf.',
    'faq.time.speed.document': 'De meeste documenten zijn binnen een paar seconden klaar. Erg lange bestanden — een paar honderd pagina’s, of een scan vol afbeeldingen — kunnen tot een minuut duren.',
    'faq.time.speed.audio': 'Een gewoon nummer is in een paar seconden omgezet. Een opname van volledige lengte, zoals een college of een podcastaflevering, duurt meestal ruim onder een minuut, waarvan het meeste de upload is.',
    'faq.time.speed.video': 'Video is de traagste categorie omdat elk frame opnieuw gecodeerd moet worden. Een korte clip duurt seconden, terwijl een lang bestand in hoge resolutie een paar minuten kan kosten.',
    'faq.time.speed.archive': 'Archieven zijn in seconden omgezet, al kost een groot archief langer omdat elk bestand erin uitgepakt en opnieuw ingepakt moet worden.',
    'faq.time.speed.ebook': 'E-boeken gaan snel — een hele roman is normaal in een paar seconden omgezet.',
    'faq.time.speed.subtitle': 'Transcriberen gaat met ongeveer een paar seconden per minuut audio, dus een video van tien minuten is meestal ruim binnen een minuut ondertiteld.',
    'faq.time.suffix.standard': ' Bestanden tot 200 MB worden geaccepteerd.',
    'faq.time.suffix.smart': ' Slimme functies accepteren bestanden tot 25 MB; gewone omzettingen tot 200 MB.',
    'faq.time.q.metadata': 'Hoe lang duurt het om de metagegevens van een bestand te lezen?',
    'faq.time.a.metadata': 'Een seconde of twee zodra het bestand geüpload is. Er wordt niets omgezet of opnieuw gecodeerd — de headers worden gelezen en het resultaat wordt direct op de pagina gezet — dus het wachten is in wezen de upload.',
    'faq.time.q.soon': 'Gaat het extra kosten?',
    'faq.time.a.soon': 'Het gebruikt dezelfde tegoeden als al het andere op de site. Er is geen apart pakket of abonnement waarvoor u zich moet aanmelden, en tegoeden die al op uw account staan werken ermee vanaf het moment dat het live gaat.',

    'faq.safety.q.pair': 'Is het veilig om mijn {{from}}-bestand te uploaden?',
    'faq.safety.q.tool': 'Is mijn bestand veilig?',
    'faq.safety.a.pair': 'Bestanden reizen over een versleutelde TLS-verbinding en worden voor niets anders gebruikt dan de omzetting waar u om vroeg. Zowel uw oorspronkelijke {{from}}-bestand als het {{to}}-bestand dat wij teruggeven worden binnen 24 uur automatisch verwijderd — definitief en zonder back-ups — en de inhoud wordt nooit gelezen, geanalyseerd of gedeeld. De dienst wordt vanuit Duitsland geëxploiteerd onder de AVG.',
    'faq.safety.a.tool': 'Bestanden reizen over een versleutelde TLS-verbinding en worden voor niets anders gebruikt dan de omzetting waar u om vroeg. Zowel uw oorspronkelijke bestand als het resultaat dat wij teruggeven worden binnen 24 uur automatisch verwijderd — definitief en zonder back-ups — en de inhoud wordt nooit gelezen, geanalyseerd of gedeeld. De dienst wordt vanuit Duitsland geëxploiteerd onder de AVG.',

    'quality.vectorRaster.q': 'Blijft mijn {{fn}} scherp als {{tn}}?',
    'quality.vectorRaster.a': 'Tot de grootte waarop u hem exporteert, ja. {{fn}} bewaart vormen in plaats van pixels en is dus oneindig schaalbaar, maar een {{tn}} is een vast raster van pixels en wordt wazig als hij later verder dan dat raster wordt vergroot. Stel bij de geavanceerde instellingen de breedte en hoogte in die u echt nodig hebt voordat u omzet — exporteren op twee- of driemaal de weergavegrootte is de gebruikelijke truc voor schermen met een hoge pixeldichtheid. Bewaar het oorspronkelijke {{fn}}-bestand: dat blijft het origineel waaruit u op elke resolutie opnieuw kunt exporteren.',
    'quality.docToTxt.q': 'Verlies ik opmaak bij het omzetten van {{fn}} naar {{tn}}?',
    'quality.docToTxt.a': 'Ja, en met opzet — een {{tn}}-bestand bevat tekens en verder niets. Lettertypen, kleuren, afbeeldingen, tabellen, kolommen en pagina-einden vervallen allemaal; wat u terugkrijgt is de leesbare tekst van het document in leesvolgorde. Dat is precies wat u wilt om te doorzoeken, te scripten of de tekst aan een ander programma te voeren, en precies wat u niet wilt als u hoopte de vormgeving te behouden. Let op: een {{fn}} die in werkelijkheid een gescande afbeelding is bevat helemaal geen tekst om uit te halen — gebruik daarvoor het OCR-hulpmiddel.',
    'quality.docToSheet.q': 'Hoe nauwkeurig worden tabellen uit een {{fn}} gehaald?',
    'quality.docToSheet.a': 'Nette tabellen met lijnen en gelijkmatige kolommen — afschriften, facturen, geëxporteerde rapporten — komen betrouwbaar door, waarbij elke waarde in een eigen cel belandt zodat u kunt optellen en sorteren. Tabellen zonder zichtbare randen, cellen die meerdere rijen beslaan of getallen die door een pagina-einde worden gesplitst zijn de gevallen die u daarna even met het oog moet nalopen. {{fn}} bewaart posities en geen tabelstructuur, dus de omzetting moet afleiden waar de ene kolom eindigt en de volgende begint.',
    'quality.docToReflow.q': 'Overleeft de opmaak de omzetting van {{fn}} naar {{tn}}?',
    'quality.docToReflow.a': 'Niet precies, en dat is juist de bedoeling. {{fn}} pint tekst vast op vaste paginacoördinaten; {{tn}} laat hem opnieuw doorlopen naar het scherm en de lettergrootte van de lezer, dus vaste paginanummers, kop- en voetteksten en opmaak met meerdere kolommen worden geherinterpreteerd in plaats van gereproduceerd. Broodtekst, koppen, alineavolgorde en afbeeldingen komen goed door. Documenten die vooral uit lopende tekst bestaan zetten prachtig om; het zijn de sterk vormgegeven pagina’s, formulieren en complexe tabellen die u daarna even moet bekijken.',
    'quality.docToFixed.q': 'Blijft mijn opmaak behouden in de {{tn}}?',
    'quality.docToFixed.a': 'Ja — deze richting is de veilige. {{tn}} legt de uiteindelijk opgebouwde pagina vast, dus lettertypen, witruimte, tabellen, afbeeldingen en pagina-einden worden precies bevroren zoals ze zijn opgemaakt en zien er op elk apparaat en elke printer hetzelfde uit. Dat is ook de prijs: het resultaat is niet langer vrij bewerkbaar, en dat is meestal precies de reden waarom mensen naar {{tn}} omzetten voordat ze een document versturen.',
    'quality.docToEditable.q': 'Hoe nauwkeurig is de omzetting van {{fn}} naar {{tn}}?',
    'quality.docToEditable.a': 'Tekst, koppen, lijsten, afbeeldingen en eenvoudige tabellen komen betrouwbaar door en blijven volledig bewerkbaar. Omdat {{fn}} posities bewaart en geen structuur, moet de omzetting die structuur reconstrueren, dus sterk vormgegeven pagina’s — meerdere kolommen, tekst die om afbeeldingen loopt, complexe geneste tabellen — kunnen daarna wat opruimwerk vragen. Is de PDF een scan zonder enige tekstlaag, gebruik dan het OCR-hulpmiddel: dat herkent de tekens in de afbeelding in plaats van te zoeken naar tekst die er niet is.',
    'quality.docGeneric.q': 'Verlies ik iets bij het omzetten van {{fn}} naar {{tn}}?',
    'quality.docGeneric.a': 'De woorden, koppen, lijsten en afbeeldingen komen ongeschonden mee. {{tn}} kent een andere opmaakwoordenschat dan {{fn}}, dus heel specifieke vormgeving kan onderweg vereenvoudigd worden, maar de inhoud zelf blijft behouden.',
    'quality.archive.q': 'Worden de bestanden in mijn {{fn}} gewijzigd?',
    'quality.archive.a': 'Nee. Archiefformaten zijn verliesvrije containers: de {{fn}} wordt uitgepakt en dezelfde bestanden worden byte voor byte opnieuw ingepakt als {{tn}}. Alleen de compressiemethode en de container veranderen. Wat wél verandert is de grootte van het archief zelf — {{clause}}.',
    'quality.archive.clause.to7z': '7Z levert dankzij LZMA-compressie doorgaans een kleiner archief op dan ZIP',
    'quality.archive.clause.toZip': 'ZIP is meestal iets groter dan 7Z of RAR, en dat is de prijs van overal te openen zijn zonder extra software',
    'quality.archive.clause.other': 'het nieuwe formaat comprimeert anders, dus de bestandsgrootte kan beide kanten op bewegen',
    'quality.imageToDoc.q': 'Verliezen mijn foto’s kwaliteit binnen de {{tn}}?',
    'quality.imageToDoc.a': 'Nee. Elke {{fn}}-afbeelding wordt onveranderd in de {{tn}} geplaatst, één per pagina, in plaats van opnieuw gecomprimeerd, dus wat u in het document ziet is wat er uit de camera kwam. De {{tn}} wordt ongeveer zo groot als alle afbeeldingen samen, en dat is handig om te weten voordat u hem mailt — haal het resultaat door PDF comprimeren als het kleiner moet.',
    'quality.toGif.q': 'Waarom ziet mijn GIF er slechter uit dan de oorspronkelijke {{fn}}?',
    'quality.toGif.a': 'Omdat GIF beperkt is tot 256 kleuren per frame. Een video of foto bevat er miljoenen, dus de encoder moet een palet kiezen en al het andere benaderen, wat zich uit als banden in verlopen en luchten. GIF draagt bovendien helemaal geen geluidsspoor mee. Beide horen bij het formaat, niet bij de omzetting — houd de clip kort, en als het kleurverlies zwaarder weegt dan automatisch afspelen in de pagina, ziet een MP4 er veel beter uit bij een kleinere omvang.',
    'quality.lossyToLossless.q': 'Wordt de kwaliteit beter door {{fn}} naar {{tn}} om te zetten?',
    'quality.lossyToLossless.a': 'Nee — en dit is verreweg het meest voorkomende misverstand over deze omzetting. {{fn}} werkt met kwaliteitsverlies: het detail dat de encoder heeft weggegooid is definitief weg en niets kan het terughalen. Wat {{tn}} u geeft is een verliesvrije container voor wat er over is, zodat het bestand niet verder achteruitgaat bij elke volgende keer opslaan of bewerken. Dat is echt nuttig wanneer u op het punt staat {{clause}}, maar het haalt geen kwaliteit terug die al verloren is.',
    'quality.lossyToLossless.edit.audio': 'de audio te bewerken, te masteren of te verwerken',
    'quality.lossyToLossless.edit.image': 'de afbeelding te bewerken, te retoucheren of samen te stellen',
    'quality.losslessToLossy.q': 'Verlies ik kwaliteit bij het omzetten van {{fn}} naar {{tn}}?',
    'quality.losslessToLossy.a.audio': 'Een beetje, en dat hoort zo — zo wordt het bestand kleiner. {{tn}} werkt met kwaliteitsverlies, dus de encoder gooit de informatie weg die hij het minst hoorbaar acht. Bij verstandige instellingen is het verschil met het oor heel moeilijk te horen, en u kunt de bitrate verhogen bij de geavanceerde instellingen als u liever grootte inruilt voor getrouwheid. Bewaar uw oorspronkelijke {{fn}}-bestand: dat blijft het origineel, en de {{tn}} later opnieuw coderen zou het verlies versterken.',
    'quality.losslessToLossy.a.visual': 'Een beetje, en dat hoort zo — zo wordt het bestand kleiner. {{tn}} werkt met kwaliteitsverlies, dus de encoder gooit de informatie weg die hij het minst zichtbaar acht. Bij verstandige instellingen is het verschil met het oog heel moeilijk te zien, en u kunt de kwaliteitswaarde verhogen bij de geavanceerde instellingen als u liever grootte inruilt voor getrouwheid. Bewaar uw oorspronkelijke {{fn}}-bestand: dat blijft het origineel, en de {{tn}} later opnieuw coderen zou het verlies versterken.',
    'quality.lossyToLossy.q': 'Verlies ik kwaliteit bij het omzetten van {{fn}} naar {{tn}}?',
    'quality.lossyToLossy.a.audio': 'Een klein beetje. Beide formaten werken met kwaliteitsverlies, dus de {{fn}} wordt gedecodeerd en daarna opnieuw gecodeerd als {{tn}}, en elke generatie codering met verlies laat wat detail vallen. Bij normale instellingen merken de meeste mensen dat bij het luisteren niet, en u kunt de bitrate verhogen bij de geavanceerde instellingen. Wat u moet vermijden is hetzelfde bestand herhaaldelijk heen en weer omzetten — dát maakt het verlies hoorbaar.',
    'quality.lossyToLossy.a.visual': 'Een klein beetje. Beide formaten werken met kwaliteitsverlies, dus de {{fn}} wordt gedecodeerd en daarna opnieuw gecodeerd als {{tn}}, en elke generatie codering met verlies laat wat detail vallen. Bij normale instellingen merken de meeste mensen dat niet, en u kunt de kwaliteit verhogen bij de geavanceerde instellingen. Wat u moet vermijden is hetzelfde bestand herhaaldelijk heen en weer omzetten — dát maakt het verlies zichtbaar.',
    'quality.losslessToLossless.q': 'Verlies ik kwaliteit bij het omzetten van {{fn}} naar {{tn}}?',
    'quality.losslessToLossless.a.plain': 'Nee. Zowel {{fn}} als {{tn}} zijn verliesvrij, dus {{unit}} blijft exact behouden en het resultaat is identiek aan het origineel. Alleen de bestandsgrootte verandert. U kunt later zonder enige achteruitgang terug omzetten.',
    'quality.losslessToLossless.a.bulky': 'Nee. Zowel {{fn}} als {{tn}} zijn verliesvrij, dus {{unit}} blijft exact behouden en het resultaat is identiek aan het origineel. Alleen de bestandsgrootte verandert, meestal drastisch omlaag, omdat {{fn}} zijn gegevens praktisch ongecomprimeerd bewaart. U kunt later zonder enige achteruitgang terug omzetten.',
    'quality.fallback.q': 'Verlies ik kwaliteit bij het omzetten van {{fn}} naar {{tn}}?',
    'quality.fallback.a': 'Voor gewone bestanden is het resultaat visueel en functioneel gelijkwaardig aan het origineel. Waar de twee formaten verschillende mogelijkheden hebben, behoudt de omzetting alles wat {{tn}} kan weergeven. Met de geavanceerde instellingen kunt u de kwaliteit verhogen als de standaardafweging niet de uwe is.',

    'relation.uncompressed.q': 'Waarom is het {{tn}}-bestand zoveel groter dan de {{fn}}?',
    'relation.uncompressed.a': 'Omdat {{tn}} ongecomprimeerd is. {{fn}} maakt audio kleiner door gegevens weg te gooien en de rest efficiënt te coderen; {{tn}} schrijft elke sample op volle grootte weg, wat neerkomt op ongeveer 10 MB per minuut stereo op cd-kwaliteit. Een verzesvoudiging of vertienvoudiging is normaal en te verwachten — het is de prijs van een bestand dat montagesoftware kan verwerken zonder eerst iets te decoderen. Wilt u verliesvrije audio op ongeveer de helft van de grootte, zet dan om naar FLAC.',
    'relation.extractAudio.q': 'Blijft de video hierbij behouden, of alleen het geluid?',
    'relation.extractAudio.a': 'Alleen het geluid. Het geluidsspoor wordt uit het {{fn}}-bestand gehaald en als {{tn}} opgeslagen; het videospoor wordt weggegooid, en daarom is het resultaat een fractie van de oorspronkelijke grootte. De audio zelf wordt niet opnieuw opgenomen, dus die behoudt de kwaliteit die hij in de {{fn}} had — uit een video met lage bitrate valt geen audio met hoge bitrate te halen.',
    'relation.videoContainer.q': 'Speelt mijn {{tn}} af op telefoons, tv’s en sociale media?',
    'relation.videoContainer.a.mp4': 'Daar is deze omzetting precies voor. MP4 met H.264-video komt het dichtst in de buurt van een universeel videoformaat: iPhones, Android-telefoons, smart-tv’s, elke browser, Instagram, YouTube, TikTok en elk gangbaar montageprogramma accepteren het zonder extra codecs. {{fn}} was het formaat dat u last bezorgde; MP4 is het formaat dat dat niet doet.',
    'relation.videoContainer.a.other': '{{tn}} is specialistischer dan MP4. {{note}} Als uw doel simpelweg is dat het „overal afspeelt”, is MP4 de veiligere keuze — kies {{tn}} wanneer een specifiek programma of apparaat erom heeft gevraagd.',
    'relation.alphaLost.q': 'Wat gebeurt er met de transparantie bij het omzetten van {{fn}} naar {{tn}}?',
    'relation.alphaLost.a': '{{tn}} heeft geen alfakanaal, dus transparante gebieden kunnen niet mee — ze worden tijdens de omzetting gevuld met een effen achtergrond (standaard wit). Speelt de transparante achtergrond een echte rol in uw ontwerp, zet dan om naar PNG of WebP, die hem allebei behouden. Is de afbeelding een foto zonder enige transparantie, dan maakt dit helemaal geen verschil.',
    'relation.alphaGained.q': 'Wordt de achtergrond transparant door {{fn}} naar {{tn}} om te zetten?',
    'relation.alphaGained.a': 'Nee — en hier lopen veel mensen tegenaan. {{tn}} ondersteunt transparantie, maar een {{fn}}-bestand heeft geen transparantie-informatie om mee te nemen, dus de achtergrond blijft precies zoals hij was. Wat de omzetting u wél geeft is een bestand dat transparantie kan bevatten zodra u de achtergrond in een afbeeldingsprogramma uitsnijdt, plus verliesvrije pixels die tijdens uw werk niet achteruitgaan.',
    'relation.reflow.q': 'Werkt de {{tn}} op mijn e-reader?',
    'relation.reflow.a.epub': 'EPUB wordt gelezen door Apple Books, Kobo, Google Play Books, Calibre en vrijwel elke e-reader behalve de Kindle, die MOBI of AZW3 wil (de Kindle accepteert tegenwoordig ook EPUB per e-mail). Omdat de tekst opnieuw doorloopt, kunt u de lettergrootte op het apparaat wijzigen zonder zijwaarts te moeten scrollen — en dat is de hele reden om een {{fn}} überhaupt om te zetten.',
    'relation.reflow.a.kindle': '{{tn}} wordt gelezen door de Kindle-apparaten en -apps waarvoor het is ontworpen. Omdat de tekst opnieuw doorloopt, kunt u de lettergrootte op het apparaat wijzigen zonder zijwaarts te moeten scrollen — en dat is de hele reden om een {{fn}} überhaupt om te zetten.',

    'compatibility.q': 'Waarmee kan ik het {{tn}}-bestand daarna openen?',
    'compatibility.a': '{{note}} Voor de omzetting zelf hoeft u niets te installeren — die draait op onze servers, en de voltooide {{tn}} komt terug in uw browser, klaar om te openen, te bewerken of door te sturen. Uw oorspronkelijke {{fn}} wordt nooit gewijzigd; wij geven altijd alleen een nieuw bestand terug.',
    'compatibility.noteFallback': '{{tn}} wordt breed ondersteund.',

    'shapeFaq.pdf-merge.q1': 'Vermindert samenvoegen de kwaliteit van mijn PDF’s?',
    'shapeFaq.pdf-merge.a1': 'Nee. De pagina’s worden precies zoals ze zijn naar het nieuwe document gekopieerd in plaats van opnieuw opgebouwd, dus tekst blijft selecteerbaar en afbeeldingen behouden hun oorspronkelijke resolutie. Het samengevoegde bestand is ongeveer zo groot als alle originelen samen — haal het daarna door PDF comprimeren als dat uitmaakt.',
    'shapeFaq.pdf-merge.q2': 'Hoeveel PDF’s kan ik in één keer samenvoegen, en maakt de volgorde uit?',
    'shapeFaq.pdf-merge.a2': 'U kunt in één keer zoveel bestanden toevoegen als u nodig hebt, en de volgorde maakt zeker uit: het voltooide document volgt de volgorde in de lijst, die u vóór het samenvoegen kunt herschikken door te slepen. Zet eerst de volgorde goed en voeg dan samen — dat is sneller dan het achteraf herstellen.',
    'shapeFaq.pdf-split.q1': 'Hoe kies ik welke pagina’s eruit gehaald worden?',
    'shapeFaq.pdf-split.a1': 'Typ ze in het veld voor paginabereiken met komma’s en streepjes: „1-3, 5, 7-10” geeft u pagina één tot en met drie, pagina vijf en pagina zeven tot en met tien in één uitvoerdocument. De nummers verwijzen naar de pagina’s van de PDF zelf, geteld vanaf één, en dat is niet altijd het nummer dat op de pagina gedrukt staat.',
    'shapeFaq.pdf-split.q2': 'Verandert splitsen de oorspronkelijke PDF?',
    'shapeFaq.pdf-split.a2': 'Nee. Het bestand dat u uploadt wordt nooit gewijzigd — de uitgenomen pagina’s worden naar een nieuw document geschreven en het origineel blijft onaangeroerd, waarna het samen met het resultaat binnen 24 uur van onze servers wordt verwijderd.',
    'shapeFaq.pdf-compress.q1': 'Hoeveel kleiner wordt mijn PDF?',
    'shapeFaq.pdf-compress.a1': 'Dat hangt volledig af van wat erin zit. PDF’s die vooral uit scans of foto’s bestaan krimpen vaak met 50 tot 90 %, omdat daar vrijwel de hele omvang zit. Een PDF met alleen tekst is al compact en verandert misschien nauwelijks. Tekst en vectorafbeeldingen blijven hoe dan ook haarscherp — de besparing komt uit het opnieuw coderen van afbeeldingen en het weglaten van overbodige ingesloten gegevens.',
    'shapeFaq.pdf-compress.q2': 'Blijft de tekst selecteerbaar en doorzoekbaar?',
    'shapeFaq.pdf-compress.a2': 'Ja. De compressie werkt op de ingesloten afbeeldingen en op overbodige interne gegevens; de tekstlaag, lettertypen, links en bladwijzers blijven intact, dus u kunt in het gecomprimeerde bestand nog precies zo zoeken, selecteren en kopiëren als daarvoor.',
    'shapeFaq.pdf-compress-ai.q1': 'Waarin verschilt dit van gewone PDF-compressie?',
    'shapeFaq.pdf-compress-ai.a1': 'Gewone compressie past één instelling toe op het hele bestand. Dit hulpmiddel kijkt eerst wat elke pagina daadwerkelijk bevat, zodat fotografische afbeeldingen, vlakke diagrammen en pagina’s met alleen tekst elk behandeld worden op de manier die de meeste ruimte bespaart zonder ze zichtbaar te verslechteren. Bij gemengde documenten betekent dat meestal een kleiner bestand bij dezelfde waargenomen kwaliteit.',
    'shapeFaq.pdf-compress-ai.q2': 'Blijft de tekst selecteerbaar en doorzoekbaar?',
    'shapeFaq.pdf-compress-ai.a2': 'Ja. De tekstlaag, lettertypen, links en bladwijzers blijven behouden — alleen de ingesloten afbeeldingen en overbodige interne gegevens worden opnieuw gecodeerd, dus de gecomprimeerde PDF blijft volledig doorzoekbaar en kopieerbaar.',
    'shapeFaq.pdf-rotate.q1': 'Gaat er kwaliteit verloren bij het draaien van een PDF?',
    'shapeFaq.pdf-rotate.a1': 'Helemaal niet. Draaien verandert de paginageometrie die in het bestand staat in plaats van iets opnieuw op te bouwen, dus tekst blijft vectorscherp, afbeeldingen blijven onaangeroerd en de bestandsgrootte verandert nauwelijks. U kunt later opnieuw draaien zonder enige opgestapelde schade.',
    'shapeFaq.pdf-rotate.q2': 'Kan ik maar een deel van de pagina’s draaien?',
    'shapeFaq.pdf-rotate.a2': 'De draaiing die u kiest — 90°, 180° of 270° — wordt op het document toegepast. Staan verschillende pagina’s in verschillende richtingen verkeerd, dan is de gebruikelijke aanpak: de PDF splitsen, elk deel over de benodigde hoek draaien en de resultaten weer samenvoegen met het hulpmiddel PDF samenvoegen.',
    'shapeFaq.pdf-protect.q1': 'Wat gebeurt er als ik het wachtwoord vergeet?',
    'shapeFaq.pdf-protect.a1': 'Het bestand kan niet geopend worden. De versleuteling wordt op de PDF zelf toegepast, dus er is geen herstellink en geen achterdeur — niet voor u en niet voor ons. Bewaar het wachtwoord op een veilige plek voordat u het document doorstuurt, en stuur het via een ander kanaal dan het bestand.',
    'shapeFaq.pdf-protect.q2': 'Hoe sterk is de beveiliging?',
    'shapeFaq.pdf-protect.a2': 'De PDF wordt versleuteld met het industriestandaardschema dat in het formaat is ingebouwd, dus de inhoud kan door geen enkele conforme lezer zonder wachtwoord gelezen worden. De praktische zwakke plek is nooit het algoritme maar het wachtwoord zelf — een kort of voor de hand liggend wachtwoord is snel geraden, dus gebruik een lang wachtwoord voor alles wat echt vertrouwelijk is.',
    'shapeFaq.pdf-unlock.q1': 'Kan dit een wachtwoord verwijderen dat ik niet ken?',
    'shapeFaq.pdf-unlock.a1': 'Nee. U moet het huidige wachtwoord opgeven; het hulpmiddel ontsleutelt het bestand daarmee in plaats van de versleuteling te breken. Het is bedoeld voor documenten die van u zijn of die u mag openen — een afschrift van uw eigen bank bijvoorbeeld — waar de beperking simpelweg in de weg zit.',
    'shapeFaq.pdf-unlock.q2': 'Wat kan ik daarna met het bestand doen?',
    'shapeFaq.pdf-unlock.a2': 'Alles wat de beveiliging blokkeerde: het openen zonder prompt, afdrukken, er tekst uit kopiëren en het in andere software bewerken. De pagina-inhoud zelf blijft onveranderd — alleen de versleutelingslaag en de bijbehorende gebruiksbeperkingen worden verwijderd.',
    'shapeFaq.metadata.q1': 'Verandert dit mijn bestand op enige manier?',
    'shapeFaq.metadata.a1': 'Nee. Het bestand wordt gelezen, niet omgezet — er wordt niets teruggeschreven en er ontstaat niets nieuws behalve de informatie op het scherm. Het is het veiligste hulpmiddel hier om op een bestand te richten waarover u twijfelt.',
    'shapeFaq.metadata.q2': 'Wat voor informatie krijg ik te zien?',
    'shapeFaq.metadata.a2': 'Dat hangt van het bestand af. Afbeeldingen tonen afmetingen, kleurdiepte en EXIF-gegevens zoals cameramodel, objectief, belichting en, als de camera ze heeft vastgelegd, GPS-coördinaten. Audio toont duur, bitrate, samplefrequentie en aantal kanalen. Video voegt codec, resolutie en beeldsnelheid toe. Documenten tonen paginaaantal, auteur, producent en aanmaakdatum.',
    'shapeFaq.ocr.q1': 'Hoe nauwkeurig is de tekstherkenning?',
    'shapeFaq.ocr.a1': 'Een schone, rechte scan van gedrukte tekst op een redelijke resolutie wordt zeer nauwkeurig herkend. De nauwkeurigheid daalt bij scheve of onscherpe pagina’s, foto’s met weinig contrast, ongebruikelijke lettertypen en handschrift. De juiste taal kiezen is belangrijk, omdat de herkenning die gebruikt om dubbelzinnige tekens te onderscheiden.',
    'shapeFaq.ocr.q2': 'Wat is het verschil tussen de doorzoekbare PDF en de uitvoer in platte tekst?',
    'shapeFaq.ocr.a2': 'De doorzoekbare PDF behoudt de oorspronkelijke pagina-afbeelding precies zoals hij eruitziet en voegt er een onzichtbare tekstlaag onder toe, dus het document ziet er onveranderd uit maar is nu doorzoekbaar en kopieerbaar — dat is wat u wilt om te archiveren. Platte tekst gooit de opmaak weg en geeft u alleen de woorden, en dat is wat u wilt om te bewerken, te scripten of aan een ander programma te voeren.',
    'shapeFaq.tts.q1': 'Hoe natuurlijk klinken de stemmen?',
    'shapeFaq.tts.a1': 'Dit zijn neurale stemmen en niet de oudere aan elkaar geplakte spraaksynthese, dus ze dragen intonatie op zinsniveau en natuurlijke pauzes in plaats van woord voor woord voor te lezen. Er zijn zes stemmen beschikbaar, van neutraal tot warm tot gezaghebbend, en de spreeksnelheid is instelbaar. Interpunctie telt meer dan mensen verwachten: komma’s en punten bepalen de frasering, dus goed geïnterpuncteerde tekst wordt merkbaar beter voorgelezen.',
    'shapeFaq.tts.q2': 'Hoeveel tekst kan ik in één keer omzetten?',
    'shapeFaq.tts.a2': 'Tot 4096 tekens per omzetting — grofweg 600 tot 700 woorden, of ongeveer vijf minuten spraak. Voor langere teksten knipt u op een natuurlijke plek zoals een hoofdstuk- of paragraaftitel en zet u elk deel apart om; de stem- en snelheidsinstellingen blijven tussen de runs gelijk, dus de stukken sluiten netjes op elkaar aan.',
    'shapeFaq.stt.q1': 'Hoe nauwkeurig is de transcriptie?',
    'shapeFaq.stt.a1': 'Duidelijke spraak in een redelijk rustige omgeving wordt zeer nauwkeurig getranscribeerd, ook bij een breed scala aan accenten. De nauwkeurigheid daalt bij veel achtergrondgeluid, meerdere mensen die door elkaar praten, of erg specialistisch jargon en eigennamen. De gesproken taal instellen in plaats van hem automatisch te laten detecteren helpt merkbaar.',
    'shapeFaq.stt.q2': 'Kan ik rechtstreeks met mijn microfoon opnemen?',
    'shapeFaq.stt.a2': 'Ja — de recorder op deze pagina neemt audio rechtstreeks in de browser op, wat vaak sneller is dan eerst een opname-app zoeken. Uw browser vraagt de eerste keer om toestemming voor de microfoon. U kunt ook een bestaand bestand uploaden, en het transcript verschijnt op de pagina zodat u het kunt lezen voordat u het als TXT of DOCX downloadt.',
    'shapeFaq.subtitle.q1': 'Hoe nauwkeurig zijn de gegenereerde ondertitels?',
    'shapeFaq.subtitle.a1': 'Duidelijke spraak wordt zeer nauwkeurig getranscribeerd, ook bij accenten. Achtergrondmuziek, door elkaar heen praten en specialistische terminologie zijn de plekken waar fouten binnensluipen, en de gesproken taal instellen in plaats van hem automatisch te detecteren helpt. De uitvoer is een ondertitelbestand in platte tekst, dus een enkel woord corrigeren kost in elke teksteditor seconden.',
    'shapeFaq.subtitle.q2': 'Moet ik SRT of VTT kiezen?',
    'shapeFaq.subtitle.a2': 'SRT is de veiligere standaardkeuze: YouTube, Vimeo, Premiere, Final Cut, VLC en vrijwel elke speler accepteren het. Kies VTT als de ondertitels bedoeld zijn voor een HTML5-videospeler op een website, want WebVTT is het formaat dat het eigen ondertitelspoor van de browser verwacht en het ondersteunt opmaak en positionering die SRT niet kan uitdrukken.',
    'shapeFaq.soon.q1': 'Wanneer komt dit beschikbaar?',
    'shapeFaq.soon.a1': 'Het wordt actief ontwikkeld. Het hulpmiddel verschijnt hier en begint bestanden te accepteren zodra het klaar is — aan uw kant hoeft niets geïnstalleerd of ingeschakeld te worden.',
    'shapeFaq.soon.q2': 'Wat kan ik ondertussen gebruiken?',
    'shapeFaq.soon.a2': 'De rest van de converter is volledig beschikbaar: documenten, afbeeldingen, audio, video, archieven, GIF’s en de PDF-gereedschapskist werken vandaag al, net als de slimme functies voor OCR, transcriptie en ondertitels.',
    'shapeFaq.compress.q1': 'Blijft het gecomprimeerde bestand een {{fn}}?',
    'shapeFaq.compress.a1': 'Ja — het formaat verandert niet, alleen de grootte. Wat u downloadt is een gewone {{fn}} die overal opent waar het origineel ook opende.{{alpha}} Hoeveel u bespaart hangt af van het uitgangsmateriaal: {{source}}.',
    'shapeFaq.compress.alpha': ' Transparantie en animatie blijven behouden.',
    'shapeFaq.compress.source.png': 'schermafbeeldingen en vlakke interfacegrafiek comprimeren spectaculair, terwijl foto’s die als PNG zijn opgeslagen minder opleveren',
    'shapeFaq.compress.source.gif': 'lange animaties en onrustige beelden comprimeren het sterkst, omdat er meer redundantie te verwijderen valt',
    'shapeFaq.compress.source.other': 'foto’s comprimeren goed, terwijl afbeeldingen die al zwaar gecomprimeerd waren minder opleveren',
    'shapeFaq.compress.q2': 'Hoeveel kleiner wordt het bestand?',
    'shapeFaq.compress.a2': 'Meestal ergens tussen een derde en een tiende van het origineel, volledig afhankelijk van wat het bestand bevat en hoe het oorspronkelijk is opgeslagen. Zodra de omzetting klaar is toont de pagina de grootte voor en na naast elkaar, dus u ziet de echte besparing in plaats van ernaar te gissen.',
    'shapeFaq.hub.q1': 'Tussen welke formaten kan ik omzetten?',
    'shapeFaq.hub.a1': 'Invoer: {{inputs}}. Uitvoer: {{outputs}}. Elke invoer kan naar elke uitvoer, dus u hoeft geen aparte pagina te zoeken voor elke combinatie — kies het bestand, kies het doelformaat, converteer.',
    'shapeFaq.hub.q2': 'Verlies ik kwaliteit?',
    'shapeFaq.hub.a2': 'Dat hangt van het paar af. Naar een verliesvrij formaat gaan behoudt alles maar levert een groter bestand op; naar een gecomprimeerd formaat gaan gooit met opzet gegevens weg in ruil voor grootte, en met de geavanceerde instellingen bepaalt u waar op die afweging u wilt zitten. Omzetten tussen twee gecomprimeerde formaten laat elke keer wat detail vallen, dus het loont om het origineel als hoofdkopie te bewaren.',
    'shapeFaq.hub-extract.q1': 'Blijft de video hierbij ook behouden?',
    'shapeFaq.hub-extract.a1': 'Nee — alleen het geluid. Het geluidsspoor wordt uit de video gelicht en apart opgeslagen, en daarom is het resultaat een fractie van de oorspronkelijke bestandsgrootte. De audio wordt niet opnieuw opgenomen, dus die behoudt de kwaliteit die hij al in de video had; uit een clip met lage bitrate valt geen audio met hoge bitrate te halen.',
    'shapeFaq.hub-extract.q2': 'Welk uitvoerformaat kan ik het beste kiezen?',
    'shapeFaq.hub-extract.a2': 'MP3 voor maximale compatibiliteit — het speelt op elke telefoon, autoradio en speler. AAC of M4A als de bestemming een Apple-apparaat of een moderne app is, want die klinken bij dezelfde bitrate iets beter. WAV of FLAC alleen als u de audio gaat bewerken, want beide zijn verliesvrij en navenant groot.',
    'shapeFaq.hub-gif.q1': 'Waarom ziet de GIF er slechter uit dan het origineel?',
    'shapeFaq.hub-gif.a1': 'Omdat GIF maar 256 kleuren per frame toestaat, terwijl video en foto’s er miljoenen bevatten. De encoder kiest een palet en benadert de rest, wat zich uit als banden in verlopen en luchten. GIF draagt bovendien helemaal geen geluid mee. Beide beperkingen horen bij het formaat en niet bij de omzetting.',
    'shapeFaq.hub-gif.q2': 'Waarom is mijn GIF-bestand zo groot?',
    'shapeFaq.hub-gif.a2': 'GIF comprimeert veel minder efficiënt dan moderne videocodecs, dus de bestandsgrootte groeit snel met lengte, resolutie en beeldsnelheid. Een paar seconden is het ideale bereik. Is het resultaat te zwaar, kort de clip dan in, en telt grootte zwaarder dan automatisch afspelen in de pagina, dan laat een MP4 dezelfde animatie zien voor een fractie van de omvang.',
  },
};
