// Norwegian (Bokmål) content pack. Mirrors packs/en.js key for key — see the header there.
export default {
  lang: 'no',
  formats: {
    pdf: { about: 'PDF er et format med fast ombrekking: det lagrer den nøyaktige posisjonen til hvert tegn, hver strek og hvert bilde, og derfor ser en PDF lik ut på enhver skjerm og skriver, men er tungvint å redigere.', note: 'PDF låser sideinndeling, skrifter og ombrekking, så mottakeren ser nøyaktig det du sendte.' },
    docx: { about: 'DOCX er Microsoft Words moderne format, der teksten lever i redigerbare avsnitt og stiler i stedet for å være spikret fast til faste sidekoordinater.', note: 'DOCX gir deg ekte redigerbare avsnitt, sporede endringer og kommentarer i Word, Google Dokumenter eller LibreOffice.' },
    xlsx: { about: 'XLSX er Excels regnearkformat, der hver verdi sitter i en adresserbar celle som kan sorteres, filtreres og brukes i en formel.', note: 'Når dataene først ligger i XLSX kan du summere, sortere, pivotere og lage diagrammer i stedet for å skrive dem inn på nytt.' },
    pptx: { about: 'PPTX lagrer en presentasjon som separate lysbilder med redigerbare tekstbokser, former, notater og overganger.', note: 'PPTX gir deg lysbilder du faktisk kan redigere om, stokke om og presentere på nytt.' },
    txt: { about: 'En TXT-fil er ikke annet enn tegn — ingen skrifter, ingen bilder, ingen sidestruktur — noe som gjør den bitteliten, lesbar overalt og trivielt søkbar.', note: 'TXT fjerner alt bortsett fra ordene, og det er nøyaktig det skript, søkeindekser og tekstredigerere vil ha.' },
    html: { about: 'HTML er nettets merkespråk: tekst pakket inn i merker som en nettleser gjør om til overskrifter, avsnitt, lenker og bilder.', note: 'HTML åpnes i enhver nettleser og kan limes rett inn i et nettsted eller et CMS.' },
    rtf: { about: 'RTF er et åpent dokumentformat bygget på ren tekst som bærer med seg grunnleggende formatering — halvfet, kursiv, skrifter, tabeller — uten å låse deg til én tekstbehandler.', note: 'RTF åpnes i Word, Pages, LibreOffice, WordPad og nesten enhver tekstbehandler som noen gang er skrevet.' },
    odt: { about: 'ODT er OpenDocument-tekstformatet som LibreOffice og OpenOffice bruker, og det er en ISO-standard snarere enn et leverandørformat.', note: 'ODT er det innebygde, fullt redigerbare formatet for LibreOffice og OpenOffice.' },
    epub: { about: 'EPUB er et e-bokformat med flytende tekst: det har ingen fast sidestørrelse, så teksten brytes om etter skjermen og skriftstørrelsen leseren bruker.', note: 'EPUB lar leseren endre skriftstørrelse og la teksten flyte om, og det er nettopp dette som gjør lange dokumenter behagelige på en telefon eller lesebrett.' },
    jpg: { about: 'JPG bruker tapsgivende komprimering tilpasset fotografier: den kaster bort de detaljene øyet merker minst, noe som gjør bilder små, men legger til myke, klossete artefakter rundt skarpe kanter og tekst.', note: 'JPG gir små filer som åpnes bokstavelig talt overalt, til prisen av permanent bortkastede detaljer og ingen gjennomsiktighet.' },
    jfif: { about: 'JFIF er et JPEG-bilde lagret med en annen filendelse; pikslene inni er vanlige JPEG-data, men Windows nekter ofte å gi filen videre til appen du vil bruke.', note: 'JFIF er egentlig bare JPEG under et annet navn.' },
    png: { about: 'PNG er tapsfritt: det lagrer hver piksel nøyaktig, støtter en full alfakanal for gjennomsiktighet og forringes aldri når du lagrer på nytt, og derfor er det førstevalget for skjermbilder, logoer og grensesnittgrafikk.', note: 'PNG bevarer hver piksel nøyaktig slik den er og støtter ekte gjennomsiktighet, så det tåler gjentatt redigering uten å forringes.' },
    webp: { about: 'WebP er Googles moderne bildeformat for nettet; det komprimerer merkbart hardere enn JPG eller PNG ved tilsvarende kvalitet og støtter gjennomsiktighet og animasjon, men mange skrivebords- og trykkeriprogrammer klarer fortsatt ikke å åpne det.', note: 'WebP gir de minste filene blant de vanlige nettformatene og støtter gjennomsiktighet.' },
    bmp: { about: 'BMP lagrer rå, praktisk talt ukomprimerte pikseldata, noe som gjør det fullkomment tro mot originalen og enormt sløsende — et bilde kan lett bli ti ganger større enn det samme bildet som PNG.', note: 'BMP er rått og ukomprimert, og det er det gammel Windows-programvare og enkelte skannere fortsatt forventer.' },
    tiff: { about: 'TIFF er arkiv- og trykkformatet: tapsfritt, med høy fargedybde, i stand til å romme flere sider eller lag — og tilsvarende stort.', note: 'TIFF er formatet trykkerier og arkiver ber om, fordi ingenting kastes bort.' },
    gif: { about: 'GIF er begrenset til en palett på 256 farger per bilderute, og derfor ser fotografier stripete ut i det, men det animerer og spilles av selv innebygd nesten overalt på internett.', note: 'GIF animerer og spilles av selv i chatteapper, sakssystemer og fora, men er begrenset til 256 farger per bilderute.' },
    ico: { about: 'ICO er en Windows-ikonbeholder som rommer den samme grafikken i flere størrelser samtidig, slik at systemet kan velge 16×16 for en fane og 256×256 for en skrivebordssnarvei.', note: 'ICO samler flere oppløsninger i én fil, og det er akkurat det favikoner og Windows-programikoner trenger.' },
    heic: { about: 'HEIC er formatet iPhone lagrer bilder i som standard; det gir omtrent samme kvalitet som JPG på omtrent halvparten av plassen, men Windows, mange nettskjemaer og en god del eldre programvare nekter rett og slett å åpne det.', note: 'HEIC er kompakt, men dårlig støttet utenfor Apples enheter.' },
    svg: { about: 'SVG består ikke av piksler i det hele tatt — det er XML som beskriver former, baner og tekst, så det forblir knivskarpt i enhver størrelse og kan redigeres eller omstilles med kode.', note: 'SVG skalerer til enhver størrelse uten noen gang å bli uskarpt, fordi det lagrer former i stedet for piksler.' },
    mp4: { about: 'MP4 er en beholder — som regel H.264-video med AAC-lyd — og det er det ene videoformatet som telefoner, nettlesere, TV-er, redigeringsprogrammer og sosiale plattformer alle er enige om.', note: 'MP4 spilles av på så godt som enhver telefon, nettleser, TV og redigeringsprogram uten ekstra programvare.' },
    avi: { about: 'AVI er en Microsoft-beholder fra 1990-tallet; eldre spillere og redigeringspakker leser den fortsatt, men den har ingen moderne strømmefunksjoner og filene har en tendens til å bli langt større enn MP4.', note: 'AVI er det eldre spillere, DVD-verktøy og gammel redigeringsprogramvare forventer.' },
    mov: { about: 'MOV er Apples QuickTime-beholder, formatet iPhone og Mac spiller inn i og det Final Cut Pro og iMovie håndterer mest smidig.', note: 'MOV er beholderen Apples redigeringsverktøy arbeider mest smidig med.' },
    mkv: { about: 'MKV (Matroska) er en åpen beholder som kan romme et vilkårlig antall video-, lyd- og undertekstspor i én fil — utmerket til arkivering, men avvist av de fleste telefoner, TV-er og nettlesere.', note: 'MKV kan bære flere lyd- og undertekstspor i én enkelt fil.' },
    webm: { about: 'WebM er den royaltyfrie beholderen bygget for HTML5-video, som regel med VP9 eller AV1; nettlesere elsker den, men skrivebordsredigerere og Apple-programvare rører den ofte ikke.', note: 'WebM er lite og strømmes innebygd i nettlesere.' },
    wmv: { about: 'WMV er Microsofts Windows Media-videoformat, i praksis bare for Windows og i stor grad forlatt utenfor gamle bedriftsopptak og skjermopptak.', note: 'WMV er et Windows Media-format med svært svak støtte andre steder.' },
    flv: { about: 'FLV var beholderen bak Flash-video, og siden Flash ble fjernet fra alle nettlesere er det i praksis et uspillbart arkivformat.', note: 'FLV er en død beholder fra Flash-tiden.' },
    mp3: { about: 'MP3 er tapsgivende: koderen sletter permanent de delene av signalet den forutsier at du ikke hører, noe som krymper et spor til rundt en tidel og er grunnen til at det spilles av på absolutt alt.', note: 'MP3 er omtrent ti ganger mindre enn ukomprimert lyd og spilles av på enhver telefon, bilstereo og spiller fra de siste tjue årene.' },
    wav: { about: 'WAV lagrer lyd ukomprimert, sample for sample, nøyaktig slik det ble spilt inn — derfor bruker studioer det, og derfor tar ett minutt stereo i CD-kvalitet omtrent 10 MB.', note: 'WAV er ukomprimert og tapsfritt, så redigerings- og masteringprogrammer kan behandle det uten å dekode noe først.' },
    flac: { about: 'FLAC komprimerer lyd tapsfritt: det er omtrent halvparten så stort som WAV og dekodes likevel tilbake til en bit-for-bit identisk kopi av originalopptaket.', note: 'FLAC er bit-for-bit identisk, men omtrent halvparten så stort som WAV.' },
    aac: { about: 'AAC er den tapsgivende kodeken bak Apple Music, YouTube og de fleste strømmetjenester; ved samme bitrate høres den vanligvis bedre ut enn MP3.', note: 'AAC høres bedre ut enn MP3 ved samme bitrate og er standarden i Apple- og strømmeverdenen.' },
    ogg: { about: 'OGG Vorbis er en patentfri tapsgivende kodek som favoriseres av spill, åpen kildekode og Wikipedia, med kvalitet på høyde med MP3 ved mindre størrelse.', note: 'OGG er fri for patentbegrensninger, og derfor foretrekker spillmotorer og åpen kildekode det.' },
    m4a: { about: 'M4A er en MP4-beholder som bare inneholder lyd, normalt AAC — formatet iTunes, Apple Music og iPhones talememoer lager.', note: 'M4A er Apple-økosystemets standard lydfil.' },
    wma: { about: 'WMA er Microsofts tapsgivende lydkodek fra Windows Media Player-tiden, sjelden støttet utenfor Windows og i praksis avviklet.', note: 'WMA er en utdatert lydkodek som bare lever på Windows.' },
    zip: { about: 'ZIP er arkivformatet som er innebygd i Windows, macOS og enhver telefon — det holder å dobbeltklikke, uten å installere noe ekstra.', note: 'ZIP åpnes med et dobbeltklikk på Windows, macOS, Linux, iOS og Android uten at noe installeres.' },
    rar: { about: 'RAR er et lukket arkivformat med god komprimering og gjenopprettingsdata, men det trenger WinRAR eller et kompatibelt verktøy for å åpnes.', note: 'RAR krever programvare fra tredjepart for å pakkes ut.' },
    '7z': { about: '7Z bruker LZMA-komprimering, som jevnlig gir merkbart mindre arkiver enn ZIP — til prisen av at det kreves 7-Zip eller et kompatibelt verktøy for å åpne dem.', note: '7Z komprimerer betydelig hardere enn ZIP, noe som betyr noe for store mapper og betalt skylagring.' },
    tar: { about: 'En TAR-fil samler mange filer til én uten å komprimere dem; den kommer fra Unix-verdenen og bevarer rettigheter og katalogstruktur.', note: 'TAR bevarer Unix-rettigheter og katalogstruktur.' },
    gz: { about: 'GZ (gzip) komprimerer én enkelt datastrøm og er det Linux-tjenere og kommandolinjeverktøy produserer; på Windows er det tungvint å åpne uten ekstra programvare.', note: 'GZ er standardformatet for komprimering på Linux og på nettservere.' },
    srt: { about: 'SRT er undertekstformatet i ren tekst som ethvert redigeringsprogram og enhver spiller forstår: nummererte replikker, et tidkodeintervall og dialoglinjen.', note: 'SRT godtas av YouTube, Vimeo, Premiere, Final Cut og enhver vanlig spiller.' },
  },
  reasons: {
    'pdf-to-word': 'Den vanlige foranledningen er en endring du ikke får gjort i selve PDF-en — en kontraktsklausul, et punkt i en CV eller et avsnitt i en rapport som må endres uten at hele dokumentet skrives om.',
    'word-to-pdf': 'Word gjøres om til PDF helt på slutten av et dokuments liv: når en CV, et tilbud eller et signert skjema skal til noen hvis skrifter, Word-versjon og marger du ikke rår over.',
    'pdf-to-excel': 'Det typiske tilfellet er et kontoutdrag, en faktura eller en rapport som bare finnes som PDF, men hvis tall du må summere, sortere eller lage diagram av.',
    'excel-to-pdf': 'Dette gjør man før et budsjett eller en prisliste sendes til noen som skal lese den, men ikke endre den, og før utskrift — en PDF spikrer sideskiftene som Excel ellers ville regnet om på hver maskin.',
    'pptx-to-pdf': 'De fleste gjør en presentasjon om til PDF før de sender eller deler den ut, slik at lysbildene ikke forskyver seg og ingen trenger PowerPoint installert for å åpne dem.',
    'pdf-to-pptx': 'Dette trenger du når den eneste gjenværende kopien av en presentasjon er PDF-en som ble sendt rundt etter møtet, og du må oppdatere eller gjenbruke lysbildene.',
    'pdf-to-txt': 'Vanlige grunner: å mate et dokument inn i et skript, en søkeindeks eller et KI-verktøy, eller å koke ned en lang rapport til noe du kan søke i, sammenligne og lime inn hvor som helst.',
    'pdf-to-html': 'Det er den raskeste måten å publisere en eksisterende rapport, håndbok eller brosjyre på et nettsted uten å bygge siden opp igjen for hånd.',
    'html-to-pdf': 'Man gjør det for å arkivere en nettside nøyaktig slik den ser ut i dag, eller for å gjøre en HTML-mal for faktura eller rapport om til noe som kan skrives ut og sendes.',
    'rtf-to-pdf': 'RTF kommer som regel ut av eldre programvare eller juridiske dokumentmaler; å gjøre det om til PDF gir deg én fil som åpnes likt overalt og ikke kan endres ved et uhell.',
    'pdf-to-rtf': 'Dette er valget når du trenger en redigerbar kopi av en PDF, men ikke kan gå ut fra at mottakeren har Word — praktisk talt enhver tekstbehandler som noen gang er skrevet åpner RTF.',
    'odt-to-pdf': 'Det typiske tilfellet: du skrev dokumentet i LibreOffice eller OpenOffice, og den som mottar det bruker Microsoft Office — eller ingenting i det hele tatt.',
    'pdf-to-epub': 'Å lese en PDF på telefonen betyr stadig kniping og sideveis rulling; denne konverteringen handler først og fremst om å gjøre et langt dokument virkelig lesbart på en liten skjerm eller et lesebrett.',
    'epub-to-pdf': 'Man gjør EPUB om til PDF når man vil skrive ut en bok, kommentere den mot faste sidetall eller sende den til noen uten leseapp installert.',
    'document-converter': 'Det er verktøyet du åpner når du får et dokument i det formatet avsenderen tilfeldigvis hadde, og trenger det i det formatet din egen programvare faktisk åpner.',
    'ebook-converter': 'E-bokbutikker og lesebrett favoriserer hvert sitt format, så dette bruker du for å flytte en bok du eier fra én leser eller app til en annen.',
    'jpg-to-png': 'Den vanlige foranledningen er redigering: du må frigjøre en bakgrunn, legge en logo over et annet bilde, eller hindre et skjermbilde i å bli uskarpere hver gang det lagres på nytt.',
    'png-to-jpg': 'Dette er løsningen på et skjermbilde eller en eksport som er for stor til å legges ved i en e-post eller til å komme forbi størrelsesgrensen i et opplastingsskjema.',
    'webp-to-png': 'Du trenger som regel dette etter å ha lagret et bilde fra et nettsted: WebP lastes ned uten problemer, men eldre bilderedigerere, kontorprogrammer og enkelte trykkeritjenester nekter fortsatt å åpne det.',
    'webp-to-jpg': 'De fleste gjør dette for å få et nettstedbilde over i noe universelt akseptert — en e-post, et eldre CMS, en fotofremkallingstjeneste eller en kollegas eldgamle programvare.',
    'heic-to-jpg': 'Dette er det klassiske iPhone-problemet: bilder ser fine ut på telefonen, men lander på en Windows-PC eller i et nettskjema som .heic-filer som ikke lar seg åpne.',
    'heic-to-png': 'Bruk dette når du har tenkt å redigere bildet og ikke bare dele det — PNG gir bilderedigereren tapsfrie piksler i stedet for en nettopp omkomprimert kopi.',
    'svg-to-png': 'Den vanlige grunnen er et verktøy som nekter vektorer: en presentasjon, en annonse på en markedsplass, en e-postsignatur eller en ikonproduksjonskjede som bare tar imot piksler.',
    'svg-to-jpg': 'Dette er for steder som vil ha en enkel fotolignende fil — et dokument, et innlegg i sosiale medier eller et opplastingsskjema som avviser både SVG-kode og gjennomsiktighet.',
    'bmp-to-png': 'BMP-filer kommer ut av gammel Windows-programvare og skannere i absurde størrelser; PNG lagrer nøyaktig de samme pikslene på en brøkdel av plassen.',
    'tiff-to-jpg': 'Skannere og profesjonelle kameraer lager TIFF-filer som er altfor store til å sendes på e-post, så JPG er det man sender når arkivkopien først ligger trygt.',
    'gif-to-png': 'Dette gjør man med en stillestående GIF — en logo, et ikon eller en eksportert bilderute — som viser fargestriper eller en frynsete kant på grunn av 256-fargegrensen.',
    'png-to-ico': 'Nesten alle som gjør PNG om til ICO lager en favikon eller et Windows-programikon, og begge forventer ICO-beholderen snarere enn en vanlig bildefil.',
    'jfif-to-png': 'JFIF-filer dukker typisk opp når et bilde lagres fra Outlook eller en nettleser, og Windows deretter nekter å gi det videre til appen du faktisk ville bruke.',
    'heic-to-pdf': 'Praktisk når du fotograferer dokumenter, kvitteringer eller en tavle med iPhone og må levere dem som én enkelt fil i stedet for en mappe med bilder.',
    'image-compressor': 'Den vanlige grunnen er en hard grense et sted — et opplastingsskjema, et tak for e-postvedlegg, eller en nettside som laster for tregt fordi bildene er langt større enn de trenger å være.',
    'jpeg-compressor': 'Fotografer og nettstedeiere bruker dette når JPEG-filer i full oppløsning bremser en side eller ikke kommer gjennom en opplastingsgrense.',
    'png-compressor': 'Skjermbilder og eksportert grensesnittgrafikk veier ofte flere megabyte uten god grunn; dette krymper dem før de havner i et dokument, en sak eller på en nettside.',
    'mp4-to-avi': 'Grunnen er nesten alltid en eldre enhet eller et bestemt program — enkelte gamle spillere, DVD-verktøy og kameraprogrammer leser AVI og ingenting annet.',
    'mp4-to-mov': 'Dette er normalt første steg før redigering på en Mac, siden Final Cut Pro og iMovie håndterer QuickTime-filer mest smidig.',
    'mov-to-mp4': 'iPhone og Mac spiller inn i MOV; alt annet forventer MP4, så dette er konverteringen man kjører før man laster opp, sender eller publiserer et klipp.',
    'mkv-to-mp4': 'MKV er utmerket til lagring, men telefoner, TV-er, nettlesere og de fleste redigeringsprogrammer spiller det ikke av — å gjøre det om til MP4 er det som gjør filen virkelig brukbar.',
    'webm-to-mp4': 'WebM-filer lagret fra nettet nekter ofte å åpne seg i QuickTime, på iOS eller i Premiere; MP4 er formatet alle godtar.',
    'avi-to-mp4': 'Dette er standardredningen for gammelt videokameraopptak og arkiverte klipp som sluker gigabyte og ikke spilles av på noen telefon.',
    'flv-to-mp4': 'Flash er borte fra enhver nettleser, så enhver FLV du fortsatt har er i praksis uspillbar — å gjøre den om til MP4 holder det arkiverte materialet seelig.',
    'wmv-to-mp4': 'WMV er en levning som bare lever på Windows, så dette gjør man før et gammelt opptak eller skjermopptak sendes til en Mac, en iPhone eller en nettplattform.',
    'mp4-to-mp3': 'Poenget er som regel lyden snarere enn bildet — en forelesning, et intervju, en podkast eller en musikkvideo du vil ha på telefonen uten å slepe med videoen.',
    'video-to-mp3': 'Man tyr til dette når lyden er den delen som er verdt å beholde: et innspilt foredrag, et intervju, en øving eller et lydspor.',
    'mp4-converter': 'Dette er verktøyet når et klipp ikke spilles av eller ikke lar seg laste opp, fordi MP4 er det ene videoformatet som telefoner, nettlesere, TV-er og sosiale plattformer alle godtar.',
    'video-converter': 'Bruk det når et klipp må bytte verden — ut av et redigeringsprogram, inn på en telefon, inn i en nettleser, eller over på en plattform som bare tar imot én bestemt beholder.',
    'mp3-to-wav': 'Den vanlige grunnen er redigering: lydprogrammer, masteringkjeder og mange lydarbeidsflyter for kringkasting eller spill vil ha ukomprimert WAV, slik at de slipper å dekode en komprimert fil ved hver eneste operasjon.',
    'wav-to-mp3': 'Opptak kommer ut av en feltopptaker eller et lydprogram som enorme WAV-filer; MP3 er det som gjør dem små nok til å sendes, lastes opp eller få plass på telefonen.',
    'flac-to-mp3': 'Et FLAC-bibliotek høres utmerket ut hjemme, men bilstereoer, eldre telefoner og billige spillere nekter ofte å ta imot det — MP3 er kompatibilitetskopien du tar med deg.',
    'aac-to-mp3': 'Dette handler mest om kompatibilitet: AAC kommer ut av Apple- og strømmeverdenen, mens eldre spillere, bilradioer og DJ-programvare forventer MP3.',
    'ogg-to-mp3': 'OGG dukker opp i spill, på Wikipedia og i programvare med åpen kildekode, og nesten ingen av de vanlige spillerne på en telefon eller i en bil åpner det.',
    'wma-to-mp3': 'WMA er en levning fra Windows Media Player-tiden, og slik redder man en gammel rippet musikksamling over til en telefon eller et strømmebibliotek.',
    'm4a-to-mp3': 'Dette er det vanlige steget når musikk eller iPhone-talememoer skal flyttes fra Apple-enheter over til programmer, biler eller spillere som bare forstår MP3.',
    'mp3-to-aac': 'Enkelte enheter og apper — særlig innen Apple og strømmeplattformene — foretrekker AAC, så dette er en kompatibilitetskonvertering og ingen kvalitetsforbedring.',
    'mp3-to-ogg': 'Man gjør om til OGG for spillmotorer, prosjekter med åpen kildekode og plattformer der en patentfri kodek kreves.',
    'audio-converter': 'Dette er verktøyet for øyeblikket da en fil ikke spilles av: ett sted å flytte lyd over til nettopp det av de vanlige formatene som enheten din, redigeringsprogrammet ditt eller opplastingsskjemaet ditt insisterer på.',
    'rar-to-zip': 'RAR trenger ekstra programvare for å åpnes, så dette gjør man før et arkiv sendes til noen som ikke kommer til å installere WinRAR.',
    '7z-to-zip': '7Z komprimerer bedre, men krever at 7-Zip er installert; som ZIP kan mottakeren rett og slett dobbeltklikke på filen.',
    'tar-to-zip': 'TAR kommer fra kommandolinjen i Linux og macOS, mens ZIP er det en kollega på Windows kan åpne uten å installere noe som helst.',
    'gz-to-zip': 'GZ-filer kommer som regel fra en tjener eller et Linux-verktøy og er tungvinte på Windows, der en ZIP pakkes ut med et dobbeltklikk.',
    'zip-to-7z': 'Her handler det om størrelse: komprimeringen i 7Z er merkbart hardere, noe som betyr noe når du arkiverer en stor mappe eller betaler for skylagring per gigabyte.',
    'video-to-gif': 'Den typiske bruken er en kort løkke til en chattemelding, en README, en feilrapport eller et innlegg — steder der en GIF spilles av selv innebygd mens en videofil ikke gjør det.',
    'mp4-to-gif': 'Den typiske bruken er en kort løkke til en chat, en README, en feilrapport eller et innlegg, der en GIF spilles av selv innebygd mens en video bare ville ligget der som et vedlegg.',
    'webm-to-gif': 'WebM-klipp lagret fra nettet lar seg ofte ikke bygge inn der du vil ha dem, mens en GIF spilles av innebygd i chatteapper, sakssystemer og fora.',
    'mov-to-gif': 'Dette gjør man med et QuickTime-skjermopptak som skal vises innebygd i en pull request, en supportsak eller et innlegg.',
    'avi-to-gif': 'Å gjøre noen sekunder av et gammelt AVI-klipp om til en GIF er den enkleste måten å få dem inn i et dokument, en chattetråd eller en nettside.',
    'gif-to-mp4': 'Lange GIF-filer er enorme og spilles hakkete; MP4 viser den samme animasjonen på en brøkdel av størrelsen, og det er nettopp derfor sosiale plattformer gjør dem om i kulissene.',
    'image-to-gif': 'Nyttig når en plattform eller et eldre system uttrykkelig forventer en GIF, eller når du trenger et stillbilde i samme format som en eksisterende serie animasjoner.',
    'gif-compressor': 'Animerte GIF-filer sveller raskt, og dette er løsningen når en av dem er for tung for en e-post, en opplastingsgrense i en chat eller en side som må laste raskt.',
    'merge-pdf': 'Det klassiske tilfellet er en søknad eller en skademelding: et skjema, en skanning og en kvittering som alle må komme fram som ett enkelt dokument.',
    'split-pdf': 'Som regel trenger du nøyaktig én ting ut av en mye lengre fil — ett kapittel, én faktura, én signert side fra en femtisiders skanning.',
    'compress-pdf': 'Nesten alltid en størrelsesgrense: et tak for e-postvedlegg, et offentlig skjema eller en portal som avviser alt over noen få megabyte.',
    'rotate-pdf': 'Dette løser det dagligdagse skannerproblemet — sider som kom ut på siden eller opp-ned på grunn av hvordan arkene ble matet inn.',
    'protect-pdf': 'Man passordbeskytter PDF-er før man sender lønnsslipper, kontrakter eller legeerklæringer, slik at innholdet ikke er lesbart for den meldingen deretter videresendes til.',
    'unlock-pdf': 'Bruk det på dokumenter du eier når passordet er kjent, men begrensningen er i veien — et kontoutdrag du ikke får skrevet ut, for eksempel.',
    'view-metadata': 'Det svarer på spørsmålene en fil ikke forteller deg rett ut: hvilket kamera tok dette bildet, hvor langt er dette opptaket egentlig, hvilken kodek sitter i denne videoen, hvor mange sider har denne PDF-en.',
    'ocr': 'Situasjonen er alltid den samme: du har et dokument som bilde og trenger ordene ut av det — for å søke i dem, sitere dem, redigere dem eller arkivere dem skikkelig.',
    'pdf-compress-ai': 'Ty til det når vanlig komprimering allerede er prøvd og filen fortsatt er for stor for opplastingsgrensen du sloss mot.',
    'text-to-speech': 'Man bruker det for å høre på noe i stedet for å lese det — en artikkel på vei til jobb, et manus lest opp for å fange klossete formuleringer, eller en speakerstemme til en video.',
    'speech-to-text': 'Det vanlige tilfellet er et opptak du trenger skriftlig: et møte, et intervju, en forelesning eller et talememo som skal bli notater, referat eller en siterbar utskrift.',
    'auto-subtitle': 'Undertekster er det som gjør en video seelig uten lyd og søkbar for søkemotorer, og å skrive dem for hånd tar selv for et kort klipp langt mer tid enn folk tror.',
    'document-translation': 'Målet er å kunne lese eller sende et dokument på et annet språk uten å miste ombrekkingen som gjør det lesbart.',
  },
  t: {
    'list.and': 'og',
    'family.document': 'dokument',
    'family.image': 'bilde',
    'family.video': 'video',
    'family.audio': 'lyd',
    'family.ebook': 'e-bok',
    'family.archive': 'arkiv',
    'family.subtitle': 'undertekst',
    'family.none': 'fil',
    'unit.sample': 'hver sample',
    'unit.pixel': 'hver piksel',

    'intro.convert': '{{fromAbout}} {{toAbout}} {{reason}} {{toNote}}',
    'intro.convert.noSource': '{{fn}} er kildeformatet for denne konverteringen.',
    'intro.lead': '{{lead}} {{reason}}',
    'intro.hub': 'Dette er den generelle {{category}}konvertereren: den tar imot {{inputs}} og skriver {{outputs}}, så du slipper å lete etter det ene verktøyet som passer akkurat ditt formatpar. {{reason}} Velg utdataformat ovenfor — konverteringen skjer på serveren, ingenting skal installeres.',
    'intro.hubExtract': 'Dette verktøyet trekker lydsporet ut av en videofil og lagrer det for seg, slik at en video blir en vanlig lydfil som spilles av overalt. Det tar imot {{inputs}} og skriver {{outputs}}. Videosporet forkastes rett og slett, og derfor blir resultatet en brøkdel av den opprinnelige størrelsen. {{reason}}',
    'intro.hubGif': 'Dette verktøyet gjør {{inputs}}-filer om til animerte GIF-er. {{gifAbout}} {{reason}}',
    'intro.hubGif.gifAbout': 'GIF er begrenset til en palett på 256 farger per bilderute, og derfor ser fotografier stripete ut i det, men det animerer og spilles av selv innebygd nesten overalt på internett.',
    'intro.compress': '{{about}} Dette verktøyet koder {{fn}}-filen din om til en mindre filstørrelse uten å bytte format, så det du laster ned er fortsatt en vanlig {{fn}} som åpnes nøyaktig der originalen gjorde det. {{reason}}{{extra}}',
    'intro.compress.lossless': ' Siden {{fn}} er tapsfritt, kommer det meste av besparelsen fra smartere koding og redusert palett snarere enn fra at detaljer kastes bort.',
    'intro.soon': '{{reason}} Dette verktøyet er ikke i drift ennå — det bygges nå og dukker opp her så snart det er klart.',
    'intro.lead.pdf-merge': 'Sammenslåing kombinerer flere PDF-er til én fil, i den rekkefølgen du velger, uten å tegne sidene på nytt — teksten kan fortsatt merkes og bildene beholder sin opprinnelige kvalitet. PDF er et format med fast ombrekking: det lagrer den nøyaktige posisjonen til hvert tegn, hver strek og hvert bilde, og derfor ser det likt ut overalt, men er tungvint å redigere.',
    'intro.lead.pdf-split': 'Deling henter ut de sidene du oppgir fra en PDF og lagrer dem som et nytt dokument, mens originalen blir liggende urørt. PDF er et format med fast ombrekking: det lagrer den nøyaktige posisjonen til hvert tegn, hver strek og hvert bilde, og derfor ser det likt ut overalt, men er tungvint å redigere.',
    'intro.lead.pdf-compress': 'Å komprimere en PDF koder om bildene inne i den og rydder bort overflødige innebygde data, og det er der nesten hele størrelsen i en stor PDF faktisk ligger. Tekst og vektorgrafikk forblir knivskarpe.',
    'intro.lead.pdf-compress-ai': 'Dette verktøyet analyserer hva som finnes i PDF-en før det komprimerer, slik at fotografiske bilder, flat grafikk og rene tekstsider hver for seg håndteres på den måten som sparer mest plass uten å forringe dem synlig.',
    'intro.lead.pdf-rotate': 'Rotasjon endrer orienteringsmerket og sidegeometrien i en PDF slik at sidene vises og skrives ut riktig vei. Ingenting tegnes på nytt, så ingen kvalitet går tapt.',
    'intro.lead.pdf-protect': 'Å beskytte en PDF krypterer innholdet slik at den ikke kan åpnes uten passordet du setter. Krypteringen legges på selve filen, ikke på et hylster rundt den.',
    'intro.lead.pdf-unlock': 'Opplåsing fjerner passordet og bruksbegrensningene fra en PDF du allerede har passordet til, slik at den igjen kan åpnes, skrives ut og kopieres fra som normalt.',
    'intro.lead.metadata': 'Enhver fil bærer med seg opplysninger om seg selv som ikke synes når du åpner den: bildets mål og kameraets innstillinger, lydens varighet og bitrate, videoens kodek og bildefrekvens, dokumentets forfatter og sideantall. Dette verktøyet leser de metadataene og viser dem til deg.',
    'intro.lead.ocr': 'Optisk tegngjenkjenning ser på et bilde av tekst — en skanning, et fotografi, en PDF-side uten tekstlag — og finner ut hvilke tegn det er, slik at et bilde av ord blir til ord en datamaskin kan søke i, kopiere og redigere.',
    'intro.lead.tts': 'Tekst til tale lager talt lyd ut av skrevet tekst med nevrale stemmer, så du får et naturlig klingende opptak i stedet for den flate robotstemmen eldre systemer ga.',
    'intro.lead.stt': 'Tale til tekst skriver ut talt lyd som ord. Den takler naturlig tale, dialekter og bakgrunnsstøy langt bedre enn gamle dikteringsprogrammer gjorde, og gir en utskrift du kan redigere.',
    'intro.lead.subtitle': 'Undertekstgeneratoren skriver ut talen i en video og legger til tidkoder, noe som gir en standardisert undertekstfil snarere enn en ren utskrift.',

    'steps.convert.1.batch': 'Slipp {{fn}}-filen din på opplastingsfeltet øverst på denne siden, eller klikk på det for å bla på enheten din. Du kan legge til flere filer — eller en hel mappe — og konvertere dem alle på én gang.',
    'steps.convert.1.single': 'Slipp {{fn}}-filen din på opplastingsfeltet øverst på denne siden, eller klikk på det for å bla på enheten din.',
    'steps.convert.2.direct': 'Velg {{tn}} som utdataformat og klikk på Konverter.',
    'steps.convert.2.dropdown': 'Velg {{tn}} som utdataformat i nedtrekkslisten og klikk på Konverter.',
    'steps.convert.2.directMedia': 'Velg {{tn}} som utdataformat, juster ved behov kvalitet eller størrelse under avanserte innstillinger, og klikk på Konverter.',
    'steps.convert.2.dropdownMedia': 'Velg {{tn}} som utdataformat i nedtrekkslisten, juster ved behov kvalitet eller størrelse under avanserte innstillinger, og klikk på Konverter.',
    'steps.convert.3': 'Last ned den ferdige {{tn}}-filen din. Nedlastingslenken er aktiv i 24 timer, deretter slettes begge filene automatisk.',
    'steps.hub.1.batch': 'Slipp {{category}}filen din ({{inputs}} tas alle imot) på opplastingsfeltet øverst på denne siden, eller klikk på det for å bla på enheten din. Du kan legge til flere filer — eller en hel mappe — og konvertere dem alle på én gang.',
    'steps.hub.1.single': 'Slipp {{category}}filen din ({{inputs}} tas alle imot) på opplastingsfeltet øverst på denne siden, eller klikk på det for å bla på enheten din.',
    'steps.hub.2.direct': 'Velg utdataformatet du trenger og klikk på Konverter.',
    'steps.hub.2.dropdown': 'Velg i nedtrekkslisten utdataformatet du trenger og klikk på Konverter.',
    'steps.hub.2.directMedia': 'Velg utdataformatet du trenger, juster ved behov kvalitet eller størrelse under avanserte innstillinger, og klikk på Konverter.',
    'steps.hub.2.dropdownMedia': 'Velg i nedtrekkslisten utdataformatet du trenger, juster ved behov kvalitet eller størrelse under avanserte innstillinger, og klikk på Konverter.',
    'steps.hub.3': 'Last ned den ferdige filen din. Nedlastingslenken er aktiv i 24 timer, deretter slettes begge filene automatisk.',
    'steps.pdf-merge.1': 'Legg til hver PDF du vil slå sammen — slipp dem samlet på opplastingsfeltet, eller klikk for å velge dem én etter én.',
    'steps.pdf-merge.2': 'Dra filene til den rekkefølgen du vil de skal stå i det ferdige dokumentet.',
    'steps.pdf-merge.3': 'Klikk på Slå sammen og last ned den ene samlede PDF-en.',
    'steps.pdf-split.1': 'Last opp PDF-en du vil hente sider ut av.',
    'steps.pdf-split.2': 'Skriv inn sidene eller intervallene du trenger i feltet for sideintervall — for eksempel 1-3, 5, 7-10.',
    'steps.pdf-split.3': 'Klikk på Konverter og last ned de uthentede sidene.',
    'steps.pdf-compress.1': 'Slipp PDF-en din på opplastingsfeltet, eller klikk for å finne den.',
    'steps.pdf-compress.2': 'Klikk på Konverter — filen analyseres og bildene og de innebygde dataene kodes om til mindre størrelse.',
    'steps.pdf-compress.3': 'Last ned den komprimerte PDF-en og se besparelsen som vises ved siden av.',
    'steps.pdf-rotate.1': 'Last opp PDF-en der sidene ligger feil vei.',
    'steps.pdf-rotate.2': 'Velg hvor mye de skal dreies — 90°, 180° eller 270°.',
    'steps.pdf-rotate.3': 'Klikk på Konverter og last ned den rettede PDF-en.',
    'steps.pdf-protect.1': 'Last opp PDF-en du vil sikre.',
    'steps.pdf-protect.2': 'Skriv inn passordet som vil kreves for å åpne den, og oppbevar en kopi et trygt sted.',
    'steps.pdf-protect.3': 'Klikk på Konverter og last ned den krypterte PDF-en.',
    'steps.pdf-unlock.1': 'Last opp den passordbeskyttede PDF-en.',
    'steps.pdf-unlock.2': 'Skriv inn det gjeldende passordet slik at filen kan dekrypteres.',
    'steps.pdf-unlock.3': 'Klikk på Konverter og last ned den opplåste PDF-en.',
    'steps.metadata.1': 'Slipp hvilken som helst fil på opplastingsfeltet — et bilde, en video, en lydfil eller et dokument.',
    'steps.metadata.2': 'Filen undersøkes i stedet for å konverteres, så ingenting i den endres.',
    'steps.metadata.3': 'Les metadataene rett på siden: mål, varighet, kodek, kameradetaljer, sideantall og mer.',
    'steps.ocr.1': 'Last opp den skannede PDF-en eller fotografiet av teksten.',
    'steps.ocr.2': 'Velg dokumentets språk og om du vil ha en søkbar PDF eller ren tekst.',
    'steps.ocr.3': 'Klikk på Konverter og last ned resultatet, der den gjenkjente teksten nå kan merkes og søkes i.',
    'steps.tts.1': 'Skriv eller lim inn teksten din i feltet — opptil 4096 tegn per konvertering.',
    'steps.tts.2': 'Velg en stemme, et taletempo og et utdataformat.',
    'steps.tts.3': 'Klikk på Konverter og last ned den ferdige lydfilen.',
    'steps.stt.1': 'Last opp opptaket ditt, eller ta opp direkte fra mikrofonen med knappen på siden.',
    'steps.stt.2': 'Angi gjerne det talte språket for bedre treffsikkerhet, og velg TXT- eller DOCX-utdata.',
    'steps.stt.3': 'Klikk på Konverter, les utskriften på siden, og last den så ned.',
    'steps.subtitle.1': 'Last opp videoen du vil tekste.',
    'steps.subtitle.2': 'Velg SRT eller VTT, og angi det talte språket hvis du kjenner det.',
    'steps.subtitle.3': 'Klikk på Konverter og last ned den tidkodede undertekstfilen, klar til å legges inn i spilleren eller redigeringsprogrammet ditt.',
    'steps.compress.1': 'Slipp {{fn}}-bildene dine på opplastingsfeltet, eller klikk for å bla. Du kan legge til en hel mappe på én gang.',
    'steps.compress.1.gif': 'Slipp {{fn}}-animasjonen din på opplastingsfeltet, eller klikk for å bla. Du kan legge til en hel mappe på én gang.',
    'steps.compress.2': 'Klikk på Konverter — filen kodes om til mindre størrelse, men blir værende i samme format.',
    'steps.compress.3': 'Last ned resultatet og sammenlign det med den opprinnelige størrelsen som vises på siden.',
    'steps.soon.1': 'Velg verktøyet du trenger på verktøysiden — alt bortsett fra dette virker allerede i dag.',
    'steps.soon.2': 'Last opp filen din og velg et utdataformat.',
    'steps.soon.3': 'Last ned resultatet, eller stikk innom her igjen når dokumentoversettelse settes i drift.',

    'faq.cost.q.pair': 'Er det gratis å konvertere {{from}} til {{to}}?',
    'faq.cost.q.tool': 'Er {{label}} gratis å bruke?',
    'faq.cost.a.pair': "Hver konvertering fra {{from}} til {{to}} bruker én kreditt fra en liten forhåndsbetalt pakke — det finnes ikke noe abonnement, kreditter utløper aldri, og en mislykket konvertering belastes ikke.",
    'faq.cost.a.tool': "Hver konvertering bruker én kreditt fra en liten forhåndsbetalt pakke — det finnes ikke noe abonnement, kreditter utløper aldri, og en mislykket konvertering belastes ikke.",
    'faq.cost.a.smartTts': "De smarte funksjonene faktureres etter bruk i stedet for per fil — 1 kreditt per 1000 tegn tekst, rundet opp. Ingen abonnement: kreditter kjøpes i små forhåndsbetalte pakker, utløper aldri, og en mislykket konvertering koster aldri noe.",
    'faq.cost.a.smartAv': "De smarte funksjonene faktureres etter bruk i stedet for per fil — 1 kreditt per 5 minutter lyd eller video, rundet opp. Ingen abonnement: kreditter kjøpes i små forhåndsbetalte pakker, utløper aldri, og en mislykket konvertering koster aldri noe.",
    'faq.cost.q.metadata': 'Er verktøyet Filinfo gratis?',
    'faq.cost.a.metadata': 'Ja. Å lese metadataene til en fil er ingen konvertering og bruker derfor ingen kreditt — du kan undersøke så mange filer du vil. Kreditter brukes bare når et verktøy faktisk lager en ny fil til deg.',
    'faq.cost.q.soon': 'Er {{label}} tilgjengelig ennå?',
    'faq.cost.a.soon': 'Ikke ennå — denne siden er en plassholder mens verktøyet bygges, så det finnes ingenting å laste opp her i dag. Prisingen vil følge den samme forhåndsbetalte kredittmodellen som resten av nettstedet: ingen abonnement, kreditter som aldri utløper, og ingen betaling for en mislykket konvertering.',

    'faq.time.q.pair': 'Hvor lang tid tar konverteringen fra {{from}} til {{to}}?',
    'faq.time.q.tool': 'Hvor lang tid tar {{label}}?',
    'faq.time.a': '{{speed}} Opplastingshastigheten er som regel den begrensende faktoren, så en stor fil på en treg forbindelse tar lengre tid enn selve konverteringen.{{suffix}}',
    'faq.time.speed.image': 'Bilder er det raskeste vi konverterer — ett enkelt fotografi er normalt ferdig på under fem sekunder, og en hel mappe tar omtrent like lang tid som selve opplastingen.',
    'faq.time.speed.document': 'De fleste dokumenter er ferdige på noen få sekunder. Svært lange filer — noen hundre sider, eller en skanning full av bilder — kan ta opptil et minutt.',
    'faq.time.speed.audio': 'En vanlig låt konverteres på noen få sekunder. Et opptak i full lengde, som en forelesning eller en podkastepisode, tar normalt godt under ett minutt, og det meste av det er opplastingen.',
    'faq.time.speed.video': 'Video er den tregeste kategorien fordi hver bilderute må kodes om. Et kort klipp tar sekunder, mens en lang fil i høy oppløsning kan ta noen minutter.',
    'faq.time.speed.archive': 'Arkiver konverteres på sekunder, selv om et stort tar lengre tid fordi hver fil inni må pakkes ut og pakkes om.',
    'faq.time.speed.ebook': 'E-bøker går raskt — en hel roman konverteres normalt på noen få sekunder.',
    'faq.time.speed.subtitle': 'Utskrift går i omtrent noen sekunder per minutt lyd, så en ti minutter lang video tekstes gjerne på godt under ett minutt.',
    'faq.time.suffix.standard': ' Filer opptil 200 MB tas imot.',
    'faq.time.suffix.smart': ' Smarte funksjoner tar imot filer opptil 25 MB; vanlige konverteringer opptil 200 MB.',
    'faq.time.q.metadata': 'Hvor lang tid tar det å lese metadataene til en fil?',
    'faq.time.a.metadata': 'Ett eller to sekunder når filen først er lastet opp. Ingenting konverteres eller kodes om — hodene leses og resultatet skrives rett til siden — så ventetiden er i praksis opplastingen.',
    'faq.time.q.soon': 'Kommer det til å koste ekstra?',
    'faq.time.a.soon': 'Det vil bruke de samme kredittene som alt annet på nettstedet. Det finnes ingen egen plan eller abonnement å melde seg på, og kreditter du allerede har på kontoen vil virke med det fra det øyeblikket det settes i drift.',

    'faq.safety.q.pair': 'Er det trygt å laste opp {{from}}-filen min?',
    'faq.safety.q.tool': 'Er filen min trygg?',
    'faq.safety.a.pair': 'Filer sendes over en kryptert TLS-forbindelse og brukes ikke til noe annet enn den konverteringen du ba om. Både den opprinnelige {{from}}-filen din og {{to}}-filen vi leverer tilbake slettes automatisk innen 24 timer — permanent og uten at det tas sikkerhetskopier — og innholdet leses, analyseres eller deles aldri. Tjenesten drives fra Tyskland under GDPR.',
    'faq.safety.a.tool': 'Filer sendes over en kryptert TLS-forbindelse og brukes ikke til noe annet enn den konverteringen du ba om. Både den opprinnelige filen din og resultatet vi leverer tilbake slettes automatisk innen 24 timer — permanent og uten at det tas sikkerhetskopier — og innholdet leses, analyseres eller deles aldri. Tjenesten drives fra Tyskland under GDPR.',

    'quality.vectorRaster.q': 'Forblir {{fn}}-filen min skarp som {{tn}}?',
    'quality.vectorRaster.a': 'Opp til den størrelsen du eksporterer den i, ja. {{fn}} lagrer former snarere enn piksler og er dermed uendelig skalerbar, men en {{tn}} er et fast rutenett av piksler og blir uskarp hvis den senere forstørres utover det rutenettet. Still inn bredden og høyden du faktisk trenger under avanserte innstillinger før du konverterer — å eksportere i to eller tre ganger visningsstørrelsen er det vanlige knepet for skjermer med høy pikseltetthet. Ta vare på den opprinnelige {{fn}}-filen: den forblir malkopien du kan eksportere på nytt fra i hvilken som helst oppløsning.',
    'quality.docToTxt.q': 'Mister jeg formatering når jeg konverterer {{fn}} til {{tn}}?',
    'quality.docToTxt.a': 'Ja, og det er selve poenget — en {{tn}}-fil inneholder tegn og ingenting annet. Skrifter, farger, bilder, tabeller, spalter og sideskift faller alle bort; det du får tilbake er dokumentets lesbare tekst i leserekkefølge. Det er akkurat det du vil ha for å søke, skripte eller mate teksten inn i et annet program, og akkurat det du ikke vil ha hvis du håpet å beholde utformingen. Merk at en {{fn}} som egentlig er et innskannet bilde ikke inneholder tekst i det hele tatt å hente ut — kjør den gjennom OCR-verktøyet i stedet.',
    'quality.docToSheet.q': 'Hvor presist hentes tabeller ut av en {{fn}}?',
    'quality.docToSheet.a': 'Rene tabeller med streker og jevne spalter — kontoutdrag, fakturaer, eksporterte rapporter — kommer pålitelig gjennom, og hver verdi lander i sin egen celle slik at du kan summere og sortere. Tabeller uten synlige rammer, celler som strekker seg over flere rader eller tall som deles av et sideskift er tilfellene det er verdt å se over etterpå. {{fn}} lagrer posisjoner og ikke tabellstruktur, så konverteringen må slutte seg til hvor én spalte slutter og den neste begynner.',
    'quality.docToReflow.q': 'Overlever ombrekkingen konverteringen fra {{fn}} til {{tn}}?',
    'quality.docToReflow.a': 'Ikke helt, og det er nettopp poenget. {{fn}} spikrer teksten til faste sidekoordinater; {{tn}} lar den flyte om etter leserens skjerm og skriftstørrelse, så faste sidetall, topptekster, bunntekster og flerspaltede oppsett tolkes om snarere enn gjengis. Brødtekst, overskrifter, avsnittsrekkefølge og bilder kommer godt gjennom. Dokumenter som stort sett består av løpende tekst konverteres utmerket; det er tungt utformede sider, skjemaer og komplekse tabeller som er verdt et blikk etterpå.',
    'quality.docToFixed.q': 'Blir formateringen min bevart i {{tn}}?',
    'quality.docToFixed.a': 'Ja — denne retningen er den trygge. {{tn}} lagrer den ferdig gjengitte siden, så skrifter, avstander, tabeller, bilder og sideskift fryses nøyaktig slik de ble satt og vil se like ut på enhver enhet og skriver. Det er også avveiningen: resultatet lar seg ikke lenger fritt redigere, noe som gjerne er akkurat grunnen til at man gjør om til {{tn}} før et dokument sendes av gårde.',
    'quality.docToEditable.q': 'Hvor presis er konverteringen fra {{fn}} til {{tn}}?',
    'quality.docToEditable.a': 'Tekst, overskrifter, lister, bilder og enkle tabeller kommer pålitelig gjennom og forblir fullt redigerbare. Siden {{fn}} lagrer posisjoner snarere enn struktur, må konverteringen bygge den strukturen opp igjen, så tungt utformede sider — flere spalter, tekst som løper rundt bilder, komplekse nøstede tabeller — kan trenge litt opprydding etterpå. Er PDF-en en skanning helt uten tekstlag, bruk OCR-verktøyet i stedet: det gjenkjenner tegnene i bildet i stedet for å lete etter tekst som ikke er der.',
    'quality.docGeneric.q': 'Mister jeg noe når jeg konverterer {{fn}} til {{tn}}?',
    'quality.docGeneric.a': 'Ordene, overskriftene, listene og bildene følger med urørt. {{tn}} har et annet formateringsvokabular enn {{fn}}, så svært spesifikk utforming kan bli forenklet underveis, men selve innholdet bevares.',
    'quality.archive.q': 'Blir filene inne i {{fn}}-arkivet mitt endret?',
    'quality.archive.a': 'Nei. Arkivformater er tapsfrie beholdere: {{fn}} pakkes ut og de identiske filene pakkes om som {{tn}}, byte for byte. Bare komprimeringsmetoden og beholderen endres. Det som derimot endrer seg er arkivets egen størrelse — {{clause}}.',
    'quality.archive.clause.to7z': '7Z gir vanligvis et mindre arkiv enn ZIP takket være LZMA-komprimering',
    'quality.archive.clause.toZip': 'ZIP blir som regel litt større enn 7Z eller RAR, og det er prisen for å kunne åpnes overalt uten ekstra programvare',
    'quality.archive.clause.other': 'det nye formatet komprimerer annerledes, så filstørrelsen kan bevege seg begge veier',
    'quality.imageToDoc.q': 'Mister bildene mine kvalitet inne i {{tn}}-filen?',
    'quality.imageToDoc.a': 'Nei. Hvert {{fn}}-bilde plasseres i {{tn}}-filen slik det er, ett per side, i stedet for å komprimeres om, så det du ser i dokumentet er det som kom ut av kameraet. {{tn}}-filen blir omtrent like stor som bildene til sammen, noe som er verdt å vite før du sender den på e-post — kjør resultatet gjennom Komprimer PDF hvis den må bli mindre.',
    'quality.toGif.q': 'Hvorfor ser GIF-en min dårligere ut enn originalen i {{fn}}?',
    'quality.toGif.a': 'Fordi GIF er begrenset til 256 farger per bilderute. En video eller et fotografi inneholder millioner, så koderen må velge en palett og tilnærme alt annet, noe som viser seg som striper i overganger og himler. GIF bærer heller ikke noe lydspor i det hele tatt. Begge deler hører til formatet og ikke til konverteringen — hold klippet kort, og hvis fargetapet veier tyngre enn innebygd automatisk avspilling, vil en MP4 se langt bedre ut ved mindre størrelse.',
    'quality.lossyToLossless.q': 'Blir kvaliteten bedre av å konvertere {{fn}} til {{tn}}?',
    'quality.lossyToLossless.a': 'Nei — og dette er med god margin den vanligste misforståelsen rundt denne konverteringen. {{fn}} er tapsgivende: detaljene koderen kastet bort er borte for godt, og ingenting kan gjenskape dem. Det {{tn}} gir deg er en tapsfri beholder for det som er igjen, slik at filen slutter å forringes ved hver påfølgende lagring eller redigering. Det er virkelig nyttig når du er i ferd med å {{clause}}, men det henter ikke tilbake kvalitet som allerede er tapt.',
    'quality.lossyToLossless.edit.audio': 'redigere, mastre eller behandle lyden',
    'quality.lossyToLossless.edit.image': 'redigere, retusjere eller montere bildet',
    'quality.losslessToLossy.q': 'Mister jeg kvalitet når jeg konverterer {{fn}} til {{tn}}?',
    'quality.losslessToLossy.a.audio': 'Noe, og med hensikt — det er slik filen blir mindre. {{tn}} er tapsgivende, så koderen kaster den informasjonen den vurderer som minst merkbar. Med fornuftige innstillinger er forskjellen svært vanskelig å høre, og du kan heve bitraten under avanserte innstillinger hvis du heller bytter størrelse mot troskap. Ta vare på den opprinnelige {{fn}}-filen din: den forblir malkopien, og å kode {{tn}} om igjen senere ville forsterket tapet.',
    'quality.losslessToLossy.a.visual': 'Noe, og med hensikt — det er slik filen blir mindre. {{tn}} er tapsgivende, så koderen kaster den informasjonen den vurderer som minst merkbar. Med fornuftige innstillinger er forskjellen svært vanskelig å se, og du kan heve kvalitetsverdien under avanserte innstillinger hvis du heller bytter størrelse mot troskap. Ta vare på den opprinnelige {{fn}}-filen din: den forblir malkopien, og å kode {{tn}} om igjen senere ville forsterket tapet.',
    'quality.lossyToLossy.q': 'Mister jeg kvalitet når jeg konverterer {{fn}} til {{tn}}?',
    'quality.lossyToLossy.a.audio': 'Litt. Begge formatene er tapsgivende, så {{fn}} dekodes og kodes deretter om som {{tn}}, og hver generasjon tapsgivende koding mister en liten mengde detaljer. Ved normale innstillinger er det ikke noe de fleste merker når de lytter, og du kan heve bitraten under avanserte innstillinger. Det du bør unngå er å konvertere den samme filen fram og tilbake gang på gang — det er det som gjør tapet hørbart.',
    'quality.lossyToLossy.a.visual': 'Litt. Begge formatene er tapsgivende, så {{fn}} dekodes og kodes deretter om som {{tn}}, og hver generasjon tapsgivende koding mister en liten mengde detaljer. Ved normale innstillinger er det ikke noe de fleste merker, og du kan heve kvaliteten under avanserte innstillinger. Det du bør unngå er å konvertere den samme filen fram og tilbake gang på gang — det er det som gjør tapet synlig.',
    'quality.losslessToLossless.q': 'Mister jeg kvalitet når jeg konverterer {{fn}} til {{tn}}?',
    'quality.losslessToLossless.a.plain': 'Nei. Både {{fn}} og {{tn}} er tapsfrie, så {{unit}} bevares nøyaktig og resultatet er identisk med originalen. Bare filstørrelsen endres. Du kan konvertere tilbake senere uten noen som helst forringelse.',
    'quality.losslessToLossless.a.bulky': 'Nei. Både {{fn}} og {{tn}} er tapsfrie, så {{unit}} bevares nøyaktig og resultatet er identisk med originalen. Bare filstørrelsen endres, som regel dramatisk nedover, fordi {{fn}} lagrer dataene sine praktisk talt ukomprimert. Du kan konvertere tilbake senere uten noen som helst forringelse.',
    'quality.fallback.q': 'Mister jeg kvalitet når jeg konverterer {{fn}} til {{tn}}?',
    'quality.fallback.a': 'For vanlige filer er resultatet visuelt og funksjonelt likeverdig med originalen. Der de to formatene støtter ulike ting, beholder konverteringen alt som {{tn}} er i stand til å representere. Med avanserte innstillinger kan du heve kvaliteten hvis standardavveiningen ikke er den du vil ha.',

    'relation.uncompressed.q': 'Hvorfor er {{tn}}-filen så mye større enn {{fn}}-filen?',
    'relation.uncompressed.a': 'Fordi {{tn}} er ukomprimert. {{fn}} krymper lyd ved å kaste data og kode resten effektivt; {{tn}} skriver ut hver sample i full størrelse, noe som blir omtrent 10 MB per minutt stereo i CD-kvalitet. En tidobling er normal og ventet — det er prisen for en fil som redigeringsprogrammer kan behandle uten å dekode noe først. Vil du ha tapsfri lyd på omtrent halve størrelsen, konverter til FLAC i stedet.',
    'relation.extractAudio.q': 'Beholder dette videoen, eller bare lyden?',
    'relation.extractAudio.a': 'Bare lyden. Lydsporet hentes ut av {{fn}}-filen og lagres som {{tn}}; videosporet forkastes, og derfor blir resultatet en brøkdel av den opprinnelige størrelsen. Selve lyden spilles ikke inn på nytt, så den beholder den kvaliteten den hadde inne i {{fn}}-filen — å hente ut fra en video med lav bitrate kan ikke gi lyd med høy bitrate.',
    'relation.videoContainer.q': 'Vil {{tn}}-filen min spilles av på telefoner, TV-er og i sosiale medier?',
    'relation.videoContainer.a.mp4': 'Det er nøyaktig det denne konverteringen er til for. MP4 med H.264-video er det nærmeste man kommer et universelt videoformat: iPhone, Android-telefoner, smart-TV-er, enhver nettleser, Instagram, YouTube, TikTok og ethvert gjengs redigeringsprogram tar imot det uten ekstra kodeker. {{fn}} var formatet som skapte trøbbel; MP4 er det som ikke gjør det.',
    'relation.videoContainer.a.other': '{{tn}} er mer spesialisert enn MP4. {{note}} Er målet ditt rett og slett at det skal «spilles av overalt», er MP4 det tryggere valget — ta {{tn}} når et bestemt program eller en bestemt enhet har bedt om det.',
    'relation.alphaLost.q': 'Hva skjer med gjennomsiktigheten når {{fn}} gjøres om til {{tn}}?',
    'relation.alphaLost.a': '{{tn}} har ingen alfakanal, så gjennomsiktige områder kan ikke følge med — de fylles med en ensfarget bakgrunn (hvit som standard) under konverteringen. Hvis den gjennomsiktige bakgrunnen gjør en reell jobb i utformingen din, konverter til PNG eller WebP i stedet, som begge bevarer den. Er bildet et fotografi uten gjennomsiktighet i det hele tatt, gjør dette ingen forskjell.',
    'relation.alphaGained.q': 'Blir bakgrunnen gjennomsiktig av å gjøre {{fn}} om til {{tn}}?',
    'relation.alphaGained.a': 'Nei — og her går mange i baret. {{tn}} støtter gjennomsiktighet, men en {{fn}}-fil har ingen gjennomsiktighetsinformasjon å ta med seg, så bakgrunnen forblir nøyaktig som den var. Det konverteringen gir deg er en fil som kan bære gjennomsiktighet når du først har frigjort bakgrunnen i en bilderedigerer, pluss tapsfrie piksler som ikke forringes mens du arbeider.',
    'relation.reflow.q': 'Vil {{tn}} virke på lesebrettet mitt?',
    'relation.reflow.a.epub': 'EPUB leses av Apple Books, Kobo, Google Play Bøker, Calibre og så godt som ethvert lesebrett bortsett fra Kindle, som vil ha MOBI eller AZW3 (Kindle tar for tiden også imot EPUB på e-post). Fordi teksten flyter om kan du endre skriftstørrelse på enheten uten å ende opp med å rulle sideveis — som er hele poenget med å konvertere en {{fn}} i utgangspunktet.',
    'relation.reflow.a.kindle': '{{tn}} leses av de Kindle-enhetene og -appene det ble laget for. Fordi teksten flyter om kan du endre skriftstørrelse på enheten uten å ende opp med å rulle sideveis — som er hele poenget med å konvertere en {{fn}} i utgangspunktet.',

    'compatibility.q': 'Hva kan åpne {{tn}}-filen etterpå?',
    'compatibility.a': '{{note}} Ingenting må installeres for å gjøre konverteringen — den kjøres på våre servere, og den ferdige {{tn}}-filen kommer tilbake i nettleseren din, klar til å åpnes, redigeres eller sendes videre. Den opprinnelige {{fn}}-filen din endres aldri; vi leverer alltid bare tilbake en ny fil.',
    'compatibility.noteFallback': '{{tn}} har bred støtte.',

    'shapeFaq.pdf-merge.q1': 'Forringer sammenslåingen kvaliteten på PDF-ene mine?',
    'shapeFaq.pdf-merge.a1': 'Nei. Sidene kopieres inn i det nye dokumentet nøyaktig slik de er i stedet for å tegnes på nytt, så teksten kan fortsatt merkes og bildene beholder sin opprinnelige oppløsning. Den sammenslåtte filen blir omtrent like stor som originalene til sammen — kjør den gjennom Komprimer PDF etterpå hvis det har noe å si.',
    'shapeFaq.pdf-merge.q2': 'Hvor mange PDF-er kan jeg slå sammen på én gang, og har rekkefølgen noe å si?',
    'shapeFaq.pdf-merge.a2': 'Du kan legge til så mange filer du trenger på én gang, og rekkefølgen har absolutt noe å si: det ferdige dokumentet følger rekkefølgen i listen, som du kan dra om før du slår sammen. Sett rekkefølgen først og slå sammen etterpå — det går raskere enn å rette det opp i ettertid.',
    'shapeFaq.pdf-split.q1': 'Hvordan velger jeg hvilke sider som skal hentes ut?',
    'shapeFaq.pdf-split.a1': 'Skriv dem inn i feltet for sideintervall med komma og bindestrek: «1-3, 5, 7-10» gir deg side én til tre, side fem og side sju til ti i ett enkelt utdatadokument. Numrene viser til PDF-ens egne sider, talt fra én, noe som ikke alltid er nummeret som står trykt på siden.',
    'shapeFaq.pdf-split.q2': 'Endrer delingen den opprinnelige PDF-en?',
    'shapeFaq.pdf-split.a2': 'Nei. Filen du laster opp endres aldri — de uthentede sidene skrives til et nytt dokument og originalen blir liggende urørt, før den slettes fra våre servere innen 24 timer sammen med resultatet.',
    'shapeFaq.pdf-compress.q1': 'Hvor mye mindre blir PDF-en min?',
    'shapeFaq.pdf-compress.a1': 'Det avhenger helt av hva som er i den. PDF-er som domineres av skanninger eller fotografier krymper ofte med 50–90 %, for det er der nesten hele størrelsen sitter. En PDF med bare tekst er allerede kompakt og endrer seg kanskje knapt. Tekst og vektorgrafikk forblir knivskarpe uansett — besparelsen kommer av at bilder kodes om og at overflødige innebygde data fjernes.',
    'shapeFaq.pdf-compress.q2': 'Kan teksten fortsatt merkes og søkes i?',
    'shapeFaq.pdf-compress.a2': 'Ja. Komprimeringen arbeider på de innebygde bildene og på overflødige interne data; tekstlaget, skriftene, lenkene og bokmerkene blir liggende urørt, så du kan fortsatt søke, merke og kopiere fra den komprimerte filen akkurat som før.',
    'shapeFaq.pdf-compress-ai.q1': 'Hvordan skiller dette seg fra vanlig PDF-komprimering?',
    'shapeFaq.pdf-compress-ai.a1': 'Vanlig komprimering legger én og samme innstilling over hele filen. Dette verktøyet ser først på hva hver side faktisk inneholder, slik at fotografiske bilder, flate diagrammer og rene tekstsider hver for seg håndteres på den måten som sparer mest plass uten å forringe dem synlig. I blandede dokumenter betyr det som regel en mindre fil ved samme opplevde kvalitet.',
    'shapeFaq.pdf-compress-ai.q2': 'Kan teksten fortsatt merkes og søkes i?',
    'shapeFaq.pdf-compress-ai.a2': 'Ja. Tekstlaget, skriftene, lenkene og bokmerkene bevares — bare de innebygde bildene og overflødige interne data kodes om, så den komprimerte PDF-en forblir fullt søkbar og kopierbar.',
    'shapeFaq.pdf-rotate.q1': 'Går det tapt kvalitet når en PDF roteres?',
    'shapeFaq.pdf-rotate.a1': 'Ikke i det hele tatt. Rotasjonen endrer sidegeometrien som står i filen i stedet for å tegne noe på nytt, så teksten forblir vektorskarp, bildene er urørte og filstørrelsen beveger seg knapt. Du kan rotere igjen senere uten noen oppsamlet skade.',
    'shapeFaq.pdf-rotate.q2': 'Kan jeg rotere bare noen av sidene?',
    'shapeFaq.pdf-rotate.a2': 'Rotasjonen du velger — 90°, 180° eller 270° — legges på dokumentet. Hvis ulike sider ligger feil hver sin vei, er den vanlige framgangsmåten å dele PDF-en, rotere hver del den vinkelen den trenger, og slå resultatene sammen igjen med verktøyet Slå sammen PDF.',
    'shapeFaq.pdf-protect.q1': 'Hva skjer hvis jeg glemmer passordet?',
    'shapeFaq.pdf-protect.a1': 'Filen lar seg ikke åpne. Krypteringen legges på selve PDF-en, så det finnes ingen tilbakestillingslenke og ingen bakdør — verken for deg eller for oss. Oppbevar passordet et trygt sted før du sender dokumentet videre, og send det gjennom en annen kanal enn filen.',
    'shapeFaq.pdf-protect.q2': 'Hvor sterk er beskyttelsen?',
    'shapeFaq.pdf-protect.a2': 'PDF-en krypteres med den bransjestandarden som er innebygd i formatet, så innholdet kan ikke leses uten passordet av noen leser som følger standarden. Det praktiske svake punktet er aldri algoritmen, men selve passordet — et kort eller opplagt passord gjettes raskt, så bruk et langt til alt som virkelig er fortrolig.',
    'shapeFaq.pdf-unlock.q1': 'Kan dette fjerne et passord jeg ikke kjenner?',
    'shapeFaq.pdf-unlock.a1': 'Nei. Du må oppgi det gjeldende passordet; verktøyet dekrypterer filen med det snarere enn å knekke krypteringen. Det er ment for dokumenter du eier eller har rett til å åpne — et kontoutdrag fra din egen bank, for eksempel — der begrensningen bare står i veien.',
    'shapeFaq.pdf-unlock.q2': 'Hva kan jeg gjøre med filen etterpå?',
    'shapeFaq.pdf-unlock.a2': 'Alt beskyttelsen blokkerte: åpne den uten spørsmål, skrive den ut, kopiere tekst fra den og redigere den i andre programmer. Selve sideinnholdet er uendret — bare krypteringslaget og bruksbegrensningene fjernes.',
    'shapeFaq.metadata.q1': 'Endrer dette filen min på noen måte?',
    'shapeFaq.metadata.a1': 'Nei. Filen leses, ikke konverteres — ingenting skrives tilbake og ingenting nytt lages utover opplysningene på skjermen. Det er det tryggeste verktøyet her å rette mot en fil du er usikker på.',
    'shapeFaq.metadata.q2': 'Hva slags opplysninger får jeg se?',
    'shapeFaq.metadata.a2': 'Det avhenger av filen. Bilder viser mål, fargedybde og EXIF-data som kameramodell, objektiv, eksponering og, når kameraet registrerte dem, GPS-koordinater. Lyd viser varighet, bitrate, samplingsfrekvens og antall kanaler. Video legger til kodek, oppløsning og bildefrekvens. Dokumenter viser sideantall, forfatter, produsent og opprettelsesdato.',
    'shapeFaq.ocr.q1': 'Hvor treffsikker er tekstgjenkjenningen?',
    'shapeFaq.ocr.a1': 'En ren, rett skanning av trykt tekst i rimelig oppløsning gjenkjennes svært treffsikkert. Treffsikkerheten faller med skjeve eller uskarpe sider, kontrastsvake fotografier, uvanlige skrifter og håndskrift. Å velge riktig språk har noe å si, fordi gjenkjenningen bruker det til å avgjøre tvetydige tegn.',
    'shapeFaq.ocr.q2': 'Hva er forskjellen mellom den søkbare PDF-en og utdata i ren tekst?',
    'shapeFaq.ocr.a2': 'Den søkbare PDF-en beholder det opprinnelige sidebildet nøyaktig slik det ser ut og legger et usynlig tekstlag under det, så dokumentet ser uendret ut, men kan nå søkes i og kopieres fra — det er det du vil ha til arkivering. Ren tekst kaster ombrekkingen og gir deg bare ordene, som er det du vil ha til redigering, skripting eller for å mate inn i et annet program.',
    'shapeFaq.tts.q1': 'Hvor naturlig høres stemmene ut?',
    'shapeFaq.tts.a1': 'Dette er nevrale stemmer og ikke den eldre sammenklipte talesyntesen, så de bærer setningsmelodi og naturlige pauser i stedet for å lese ord for ord. Seks stemmer er tilgjengelige, fra nøytral til varm til autoritativ, og taletempoet lar seg stille inn. Tegnsetting betyr mer enn folk tror: komma og punktum former frasering, så velinterpungert tekst leses opp merkbart bedre.',
    'shapeFaq.tts.q2': 'Hvor mye tekst kan jeg konvertere på én gang?',
    'shapeFaq.tts.a2': 'Opptil 4096 tegn per konvertering — grovt regnet 600 til 700 ord, eller omtrent fem minutters tale. For lengre tekster deler du på et naturlig sted som en kapittel- eller avsnittsoverskrift og konverterer hver del for seg; stemme- og tempoinnstillingene er de samme mellom kjøringene, så bitene føyer seg pent sammen.',
    'shapeFaq.stt.q1': 'Hvor treffsikker er utskriften?',
    'shapeFaq.stt.a1': 'Tydelig tale i et rimelig stille miljø skrives ut svært treffsikkert, også ved et bredt spekter av dialekter og aksenter. Treffsikkerheten faller ved kraftig bakgrunnsstøy, når flere snakker i munnen på hverandre, eller ved svært spesialisert sjargong og egennavn. Å angi det talte språket i stedet for å la det oppdages automatisk hjelper merkbart.',
    'shapeFaq.stt.q2': 'Kan jeg ta opp direkte fra mikrofonen?',
    'shapeFaq.stt.a2': 'Ja — opptakeren på denne siden fanger lyd direkte i nettleseren, noe som ofte går raskere enn å først finne en opptaksapp. Nettleseren din spør om mikrofontillatelse første gang. Du kan også laste opp en eksisterende fil, og utskriften vises på siden slik at du kan lese den før du laster den ned som TXT eller DOCX.',
    'shapeFaq.subtitle.q1': 'Hvor treffsikre er undertekstene som genereres?',
    'shapeFaq.subtitle.a1': 'Tydelig tale skrives ut svært treffsikkert, også med aksent. Bakgrunnsmusikk, overlappende prat og spesialisert terminologi er der feilene sniker seg inn, og å angi det talte språket i stedet for å oppdage det automatisk hjelper. Utdata er en undertekstfil i ren tekst, så å rette et og annet ord tar sekunder i hvilken som helst tekstredigerer.',
    'shapeFaq.subtitle.q2': 'Bør jeg velge SRT eller VTT?',
    'shapeFaq.subtitle.a2': 'SRT er det tryggere standardvalget: YouTube, Vimeo, Premiere, Final Cut, VLC og praktisk talt enhver spiller tar imot det. Velg VTT hvis undertekstene skal til en HTML5-videospiller på et nettsted, siden WebVTT er formatet nettleserens innebygde undertekstspor forventer, og det støtter stilsetting og plassering som SRT ikke kan uttrykke.',
    'shapeFaq.soon.q1': 'Når blir dette tilgjengelig?',
    'shapeFaq.soon.a1': 'Det er under aktiv utvikling. Verktøyet dukker opp her og begynner å ta imot filer så snart det er klart — hos deg må ingenting installeres eller slås på.',
    'shapeFaq.soon.q2': 'Hva kan jeg bruke i mellomtiden?',
    'shapeFaq.soon.a2': 'Resten av konvertereren er fullt tilgjengelig: dokumenter, bilder, lyd, video, arkiver, GIF-er og PDF-verktøykassen virker alle i dag, det samme gjør de smarte funksjonene for OCR, utskrift og undertekster.',
    'shapeFaq.compress.q1': 'Er den komprimerte filen fortsatt en {{fn}}?',
    'shapeFaq.compress.a1': 'Ja — formatet endres ikke, bare størrelsen. Det du laster ned er en vanlig {{fn}} som åpnes overalt der originalen gjorde det.{{alpha}} Hvor mye du sparer avhenger av kildematerialet: {{source}}.',
    'shapeFaq.compress.alpha': ' Gjennomsiktighet og animasjon bevares.',
    'shapeFaq.compress.source.png': 'skjermbilder og flat grensesnittgrafikk komprimeres dramatisk, mens fotografier lagret som PNG gir mindre',
    'shapeFaq.compress.source.gif': 'lange animasjoner og urolig materiale komprimeres mest, fordi det er mer gjentakelse å fjerne',
    'shapeFaq.compress.source.other': 'fotografier komprimeres godt, mens bilder som allerede var hardt komprimert har mindre igjen å gi',
    'shapeFaq.compress.q2': 'Hvor mye mindre blir filen?',
    'shapeFaq.compress.a2': 'Vanligvis et sted mellom en tredjedel og en tidel av originalen, helt avhengig av hva filen inneholder og hvordan den ble lagret i utgangspunktet. Når konverteringen er ferdig viser siden størrelsen før og etter side om side, så du ser den faktiske besparelsen i stedet for å gjette.',
    'shapeFaq.hub.q1': 'Mellom hvilke formater kan jeg konvertere?',
    'shapeFaq.hub.a1': 'Inndata: {{inputs}}. Utdata: {{outputs}}. Enhver inndata kan gå til enhver utdata, så du trenger ikke finne en egen side for hver kombinasjon — velg filen, velg målformatet, konverter.',
    'shapeFaq.hub.q2': 'Mister jeg kvalitet?',
    'shapeFaq.hub.a2': 'Det avhenger av paret. Å gå til et tapsfritt format beholder alt, men gir en større fil; å gå til et komprimert format kaster med hensikt data i bytte mot størrelse, og med avanserte innstillinger bestemmer du hvor på den avveiningen du vil ligge. Å konvertere mellom to komprimerte formater mister litt detaljer hver gang, så det lønner seg å beholde originalen som malkopi.',
    'shapeFaq.hub-extract.q1': 'Beholdes videoen også?',
    'shapeFaq.hub-extract.a1': 'Nei — bare lyden. Lydsporet løftes ut av videoen og lagres for seg, og derfor blir resultatet en brøkdel av den opprinnelige filstørrelsen. Lyden spilles ikke inn på nytt, så den beholder den kvaliteten den allerede hadde inne i videoen; å hente ut fra et klipp med lav bitrate kan ikke gi lyd med høy bitrate.',
    'shapeFaq.hub-extract.q2': 'Hvilket utdataformat bør jeg velge?',
    'shapeFaq.hub-extract.a2': 'MP3 for størst mulig kompatibilitet — det spilles av på enhver telefon, bilstereo og spiller. AAC eller M4A hvis målet er en Apple-enhet eller en moderne app, siden de høres litt bedre ut ved samme bitrate. WAV eller FLAC bare hvis du har tenkt å redigere lyden, siden begge er tapsfrie og dermed store.',
    'shapeFaq.hub-gif.q1': 'Hvorfor ser GIF-en dårligere ut enn originalen?',
    'shapeFaq.hub-gif.a1': 'Fordi GIF bare tillater 256 farger per bilderute, mens video og fotografier inneholder millioner. Koderen velger en palett og tilnærmer resten, noe som viser seg som striper i overganger og himler. GIF bærer heller ikke lyd i det hele tatt. Begge grensene hører til formatet og ikke til konverteringen.',
    'shapeFaq.hub-gif.q2': 'Hvorfor er GIF-filen min så stor?',
    'shapeFaq.hub-gif.a2': 'GIF komprimerer langt dårligere enn moderne videokodeker, så filstørrelsen vokser raskt med lengde, oppløsning og bildefrekvens. Noen få sekunder er det ideelle. Blir resultatet for tungt, korter du klippet, og veier størrelsen tyngre enn innebygd automatisk avspilling, vil en MP4 vise den samme animasjonen på en brøkdel av størrelsen.',
  },
};
