// Polish content pack. Mirrors packs/en.js key for key — see the header there.
export default {
  lang: 'pl',
  formats: {
    pdf: { about: 'PDF to format o stałym układzie: zapisuje dokładną pozycję każdego znaku, każdej linii i każdego obrazu, dlatego wygląda identycznie na dowolnym ekranie i drukarce, ale jest niewygodny w edycji.', note: 'PDF blokuje podział na strony, czcionki i układ, więc odbiorca widzi dokładnie to, co zostało wysłane.' },
    docx: { about: 'DOCX to nowoczesny format Microsoft Word, w którym tekst żyje w edytowalnych akapitach i stylach, zamiast być przypięty do sztywnych współrzędnych strony.', note: 'DOCX daje prawdziwe edytowalne akapity, śledzenie zmian i komentarze w Wordzie, Dokumentach Google lub LibreOffice.' },
    xlsx: { about: 'XLSX to format arkusza kalkulacyjnego Excela, w którym każda wartość zajmuje adresowalną komórkę, którą można sortować, filtrować i wykorzystać w formule.', note: 'Gdy dane trafią do XLSX, można je sumować, sortować, analizować tabelami przestawnymi i przedstawiać na wykresach zamiast przepisywać.' },
    pptx: { about: 'PPTX zapisuje prezentację jako osobne slajdy z edytowalnymi polami tekstowymi, kształtami, notatkami prelegenta i przejściami.', note: 'PPTX daje slajdy, które można naprawdę ponownie edytować, przestawiać i pokazywać.' },
    txt: { about: 'Plik TXT to nic poza znakami — bez czcionek, bez obrazów, bez struktury strony — co czyni go maleńkim, czytelnym wszędzie i banalnie łatwym do przeszukania.', note: 'TXT usuwa wszystko poza słowami, a dokładnie tego oczekują skrypty, indeksy wyszukiwania i edytory tekstu.' },
    html: { about: 'HTML to język znaczników sieci: tekst opakowany w znaczniki, które przeglądarka zamienia w nagłówki, akapity, odnośniki i obrazy.', note: 'HTML otwiera się w każdej przeglądarce i można go wkleić prosto na stronę lub do systemu CMS.' },
    rtf: { about: 'RTF to otwarty format dokumentu oparty na zwykłym tekście, który niesie podstawowe formatowanie — pogrubienie, kursywę, czcionki, tabele — nie zamykając użytkownika w jednym edytorze.', note: 'RTF otwiera się w Wordzie, Pages, LibreOffice, WordPadzie i praktycznie każdym edytorze tekstu, jaki kiedykolwiek powstał.' },
    odt: { about: 'ODT to format tekstowy OpenDocument używany przez LibreOffice i OpenOffice, będący normą ISO, a nie formatem jednego producenta.', note: 'ODT to natywny, w pełni edytowalny format LibreOffice i OpenOffice.' },
    epub: { about: 'EPUB to format e-booka z płynnym tekstem: nie ma stałego rozmiaru strony, więc tekst dopasowuje się do ekranu i wielkości czcionki, jakiej używa czytelnik.', note: 'EPUB pozwala czytelnikowi zmienić rozmiar czcionki i przelać tekst na nowo, co sprawia, że długie dokumenty są wygodne na telefonie lub czytniku.' },
    jpg: { about: 'JPG stosuje kompresję stratną dostrojoną do fotografii: odrzuca szczegóły, których oko najmniej zauważa, przez co zdjęcia są małe, ale wokół ostrych krawędzi i tekstu pojawiają się miękkie, kwadratowe artefakty.', note: 'JPG daje małe pliki, które otwierają się dosłownie wszędzie, kosztem bezpowrotnie odrzuconych szczegółów i braku przezroczystości.' },
    jfif: { about: 'JFIF to obraz JPEG zapisany z innym rozszerzeniem; piksele w środku to zwykłe dane JPEG, ale Windows często odmawia przekazania pliku wybranej aplikacji.', note: 'JFIF to w istocie po prostu JPEG pod inną nazwą.' },
    png: { about: 'PNG jest bezstratny: zapisuje każdy piksel dokładnie, obsługuje pełny kanał alfa dla przezroczystości i nigdy nie traci jakości przy ponownym zapisie, dlatego jest formatem pierwszego wyboru dla zrzutów ekranu, logotypów i grafiki interfejsu.', note: 'PNG zachowuje każdy piksel dokładnie takim, jaki jest, i obsługuje prawdziwą przezroczystość, więc przetrwa wielokrotną edycję bez utraty jakości.' },
    webp: { about: 'WebP to nowoczesny format obrazu internetowego od Google; kompresuje wyraźnie mocniej niż JPG czy PNG przy podobnej jakości i obsługuje przezroczystość oraz animację, ale wiele programów biurkowych i poligraficznych wciąż nie potrafi go otworzyć.', note: 'WebP daje najmniejsze pliki spośród popularnych formatów internetowych i obsługuje przezroczystość.' },
    bmp: { about: 'BMP przechowuje surowe, praktycznie nieskompresowane dane pikseli, co czyni go doskonale wiernym i ogromnie rozrzutnym — zdjęcie potrafi z łatwością zajmować dziesięć razy więcej niż ten sam obraz w PNG.', note: 'BMP jest surowy i nieskompresowany, czego wciąż oczekują stare programy Windows i niektóre skanery.' },
    tiff: { about: 'TIFF to format archiwalny i poligraficzny: bezstratny, o dużej głębi kolorów, zdolny pomieścić wiele stron lub warstw — i odpowiednio duży.', note: 'TIFF to format, o który proszą drukarnie i archiwa, ponieważ nic nie jest w nim odrzucane.' },
    gif: { about: 'GIF jest ograniczony do palety 256 kolorów na klatkę, dlatego zdjęcia wyglądają w nim pasmowo, ale animuje się i odtwarza samoczynnie w treści niemal wszędzie w internecie.', note: 'GIF animuje się i odtwarza samoczynnie w komunikatorach, systemach zgłoszeń i na forach, ale jest ograniczony do 256 kolorów na klatkę.' },
    ico: { about: 'ICO to kontener ikon Windows, który mieści tę samą grafikę w kilku rozmiarach naraz, aby system mógł wybrać 16×16 dla karty i 256×256 dla skrótu na pulpicie.', note: 'ICO łączy kilka rozdzielczości w jednym pliku, a dokładnie tego potrzebują favicony i ikony aplikacji Windows.' },
    heic: { about: 'HEIC to format, w którym iPhone domyślnie zapisuje zdjęcia; daje mniej więcej tę samą jakość co JPG przy około połowie miejsca, ale Windows, wiele formularzy internetowych i sporo starszego oprogramowania po prostu odmawia jego otwarcia.', note: 'HEIC jest kompaktowy, ale słabo obsługiwany poza urządzeniami Apple.' },
    svg: { about: 'SVG w ogóle nie składa się z pikseli — to XML opisujący kształty, ścieżki i tekst, więc pozostaje idealnie ostry w każdym rozmiarze i można go edytować lub przestylować kodem.', note: 'SVG skaluje się do dowolnego rozmiaru, nigdy nie tracąc ostrości, ponieważ przechowuje kształty zamiast pikseli.' },
    mp4: { about: 'MP4 to kontener — zwykle wideo H.264 z dźwiękiem AAC — i jest jedynym formatem wideo, co do którego zgadzają się telefony, przeglądarki, telewizory, programy montażowe i platformy społecznościowe.', note: 'MP4 odtwarza się praktycznie na każdym telefonie, w każdej przeglądarce, telewizorze i programie montażowym bez dodatkowego oprogramowania.' },
    avi: { about: 'AVI to kontener Microsoftu z lat dziewięćdziesiątych; starsze odtwarzacze i pakiety montażowe wciąż go czytają, ale nie ma nowoczesnych funkcji strumieniowania, a jego pliki bywają znacznie większe niż MP4.', note: 'AVI to format, jakiego oczekują starsze odtwarzacze, narzędzia do tworzenia DVD i wiekowe oprogramowanie montażowe.' },
    mov: { about: 'MOV to kontener QuickTime firmy Apple, format, w którym nagrywają iPhone i Mac, i ten, z którym Final Cut Pro oraz iMovie radzą sobie najwygodniej.', note: 'MOV to kontener, z którym narzędzia montażowe Apple pracują najpłynniej.' },
    mkv: { about: 'MKV (Matroska) to otwarty kontener mieszczący dowolną liczbę ścieżek wideo, audio i napisów w jednym pliku — świetny do archiwizacji, lecz odrzucany przez większość telefonów, telewizorów i przeglądarek.', note: 'MKV potrafi przenosić wiele ścieżek dźwiękowych i napisów w jednym pliku.' },
    webm: { about: 'WebM to wolny od opłat licencyjnych kontener stworzony dla wideo HTML5, zwykle z VP9 lub AV1; przeglądarki go uwielbiają, ale biurkowe programy montażowe i oprogramowanie Apple często go nie tykają.', note: 'WebM jest lekki i strumieniuje natywnie w przeglądarkach.' },
    wmv: { about: 'WMV to format wideo Windows Media firmy Microsoft, praktycznie ograniczony do Windows i w dużej mierze porzucony poza starymi nagraniami firmowymi i zapisami ekranu.', note: 'WMV to format Windows Media o bardzo słabym wsparciu gdzie indziej.' },
    flv: { about: 'FLV był kontenerem stojącym za wideo Flash, a odkąd Flash usunięto ze wszystkich przeglądarek, jest w praktyce nieodtwarzalnym formatem archiwalnym.', note: 'FLV to martwy kontener z epoki Flasha.' },
    mp3: { about: 'MP3 jest stratny: koder trwale usuwa te fragmenty sygnału, których według swoich przewidywań i tak nie usłyszysz, przez co utwór kurczy się do mniej więcej jednej dziesiątej, i dlatego odtwarza się absolutnie wszędzie.', note: 'MP3 jest około dziesięć razy mniejszy niż dźwięk nieskompresowany i odtwarza się na każdym telefonie, w każdym radiu samochodowym i odtwarzaczu z ostatnich dwudziestu lat.' },
    wav: { about: 'WAV przechowuje dźwięk bez kompresji, próbka po próbce, dokładnie tak, jak został nagrany — dlatego używają go studia i dlatego minuta stereo w jakości CD zajmuje około 10 MB.', note: 'WAV jest nieskompresowany i bezstratny, więc programy montażowe i masteringowe mogą go przetwarzać, nie dekodując wcześniej niczego.' },
    flac: { about: 'FLAC kompresuje dźwięk bezstratnie: zajmuje mniej więcej połowę tego co WAV, a mimo to dekoduje się do idealnie identycznej bitowo kopii oryginalnego nagrania.', note: 'FLAC jest identyczny bit po bicie, lecz zajmuje około połowy tego co WAV.' },
    aac: { about: 'AAC to stratny kodek stojący za Apple Music, YouTube i większością serwisów strumieniowych; przy tej samej przepływności brzmi zwykle lepiej niż MP3.', note: 'AAC brzmi lepiej niż MP3 przy tej samej przepływności i jest standardem w świecie Apple oraz serwisów strumieniowych.' },
    ogg: { about: 'OGG Vorbis to wolny od patentów kodek stratny, ulubiony przez gry, oprogramowanie open source i Wikipedię, o jakości porównywalnej z MP3 przy mniejszych rozmiarach.', note: 'OGG jest wolny od ograniczeń patentowych, dlatego wolą go silniki gier i projekty open source.' },
    m4a: { about: 'M4A to kontener MP4 zawierający wyłącznie dźwięk, zwykle AAC — format tworzony przez iTunes, Apple Music i notatki głosowe iPhone’a.', note: 'M4A to standardowy plik dźwiękowy ekosystemu Apple.' },
    wma: { about: 'WMA to stratny kodek dźwięku Microsoftu z epoki Windows Media Player, rzadko obsługiwany poza Windows i w praktyce zaniechany.', note: 'WMA to przestarzały kodek dźwięku ograniczony do Windows.' },
    zip: { about: 'ZIP to format archiwum wbudowany w Windows, macOS i każdy telefon — wystarczy dwukrotne kliknięcie, bez instalowania czegokolwiek.', note: 'ZIP otwiera się dwukrotnym kliknięciem w Windows, macOS, Linuksie, iOS i Androidzie bez instalowania czegokolwiek.' },
    rar: { about: 'RAR to zamknięty format archiwum z dobrą kompresją i danymi naprawczymi, ale do otwarcia potrzebuje WinRAR-a lub zgodnego narzędzia.', note: 'RAR wymaga do rozpakowania oprogramowania innej firmy.' },
    '7z': { about: '7Z używa kompresji LZMA, która regularnie daje zauważalnie mniejsze archiwa niż ZIP — kosztem konieczności posiadania 7-Zipa lub zgodnego narzędzia do otwarcia.', note: '7Z kompresuje znacznie mocniej niż ZIP, co ma znaczenie przy dużych folderach i płatnym magazynie w chmurze.' },
    tar: { about: 'Plik TAR łączy wiele plików w jeden, nie kompresując ich; pochodzi ze świata Uniksa i zachowuje uprawnienia oraz strukturę katalogów.', note: 'TAR zachowuje uprawnienia uniksowe i strukturę katalogów.' },
    gz: { about: 'GZ (gzip) kompresuje pojedynczy strumień danych i jest tym, co tworzą serwery linuksowe oraz narzędzia wiersza poleceń; w Windows jest niewygodny do otwarcia bez dodatkowego oprogramowania.', note: 'GZ to standardowy format kompresji w Linuksie i na serwerach internetowych.' },
    srt: { about: 'SRT to tekstowy format napisów rozumiany przez każdy program montażowy i każdy odtwarzacz: numerowane wpisy, zakres kodu czasowego i linia dialogu.', note: 'SRT akceptują YouTube, Vimeo, Premiere, Final Cut i każdy popularny odtwarzacz.' },
  },
  reasons: {
    'pdf-to-word': 'Zwykłym powodem jest zmiana, której nie da się wprowadzić w samym PDF-ie — klauzula umowy, punkt w CV albo akapit raportu, który musi się zmienić bez przepisywania całego dokumentu.',
    'word-to-pdf': 'Word zamienia się na PDF na samym końcu życia dokumentu: przy wysyłaniu CV, oferty czy podpisanego formularza do kogoś, na czyje czcionki, wersję Worda i marginesy nie masz wpływu.',
    'pdf-to-excel': 'Typowy przypadek to wyciąg bankowy, faktura lub raport istniejący wyłącznie jako PDF, którego liczby trzeba zsumować, posortować albo przedstawić na wykresie.',
    'excel-to-pdf': 'To robi się przed wysłaniem budżetu lub cennika komuś, kto ma go przeczytać, ale nie zmieniać, i przed drukiem — PDF utrwala podziały stron, które Excel inaczej przeliczyłby na każdym komputerze od nowa.',
    'pptx-to-pdf': 'Większość osób zamienia prezentację na PDF przed wysłaniem lub rozdaniem, żeby slajdy się nie rozjechały i żeby nikt nie musiał mieć zainstalowanego PowerPointa, by je otworzyć.',
    'pdf-to-pptx': 'To jest potrzebne, gdy jedyną zachowaną kopią prezentacji jest PDF rozesłany po spotkaniu, a slajdy trzeba zaktualizować albo wykorzystać ponownie.',
    'pdf-to-txt': 'Typowe powody: podanie dokumentu skryptowi, indeksowi wyszukiwania albo narzędziu AI, albo sprowadzenie długiego raportu do czegoś, co można przeszukać, porównać i wkleić gdziekolwiek.',
    'pdf-to-html': 'To najszybszy sposób, by opublikować istniejący raport, instrukcję lub broszurę na stronie bez odtwarzania jej ręcznie.',
    'html-to-pdf': 'Robi się to, aby zarchiwizować stronę internetową dokładnie taką, jaka jest dziś, albo by zamienić szablon faktury lub raportu w HTML w coś nadającego się do druku i wysyłki.',
    'rtf-to-pdf': 'RTF zwykle wychodzi ze starszego oprogramowania albo z szablonów dokumentów prawnych; zamiana na PDF daje jeden plik otwierający się wszędzie identycznie, którego nie da się przypadkiem zmienić.',
    'pdf-to-rtf': 'To wybór, gdy potrzebna jest edytowalna kopia PDF-a, ale nie można zakładać, że odbiorca ma Worda — praktycznie każdy edytor tekstu, jaki kiedykolwiek napisano, otwiera RTF.',
    'odt-to-pdf': 'Typowy przypadek: dokument powstał w LibreOffice lub OpenOffice, a osoba odbierająca używa Microsoft Office — albo niczego.',
    'pdf-to-epub': 'Czytanie PDF-a na telefonie oznacza ciągłe powiększanie i przewijanie w bok; ta konwersja służy przede wszystkim temu, by długi dokument dało się naprawdę czytać na małym ekranie lub czytniku.',
    'epub-to-pdf': 'EPUB zamienia się na PDF, gdy chce się wydrukować książkę, opatrzyć ją notatkami przy stałej numeracji stron albo wysłać komuś, kto nie ma żadnej aplikacji czytnika.',
    'document-converter': 'To narzędzie otwiera się, gdy dostajesz dokument w formacie, jaki akurat miał nadawca, a potrzebujesz go w tym, który naprawdę otwiera twoje własne oprogramowanie.',
    'ebook-converter': 'Księgarnie i czytniki e-booków każdy preferuje swój własny format, więc tego używa się, by przenieść posiadaną książkę z jednego czytnika lub aplikacji do innej.',
    'jpg-to-png': 'Zwykłym powodem jest edycja: trzeba wyciąć tło, nałożyć logo na inny obraz albo powstrzymać zrzut ekranu przed rozmywaniem się przy każdym kolejnym zapisie.',
    'png-to-jpg': 'To rozwiązanie dla zrzutu ekranu lub eksportu zbyt dużego, by dołączyć go do wiadomości albo przejść limit rozmiaru formularza przesyłania.',
    'webp-to-png': 'Zwykle potrzeba tego po zapisaniu obrazu ze strony: WebP pobiera się bez problemu, ale starsze edytory, pakiety biurowe i niektóre usługi drukarskie wciąż odmawiają jego otwarcia.',
    'webp-to-jpg': 'Większość robi to, by przenieść obraz ze strony do czegoś powszechnie akceptowanego — wiadomości e-mail, starszego CMS-a, usługi wywoływania zdjęć albo prehistorycznego oprogramowania współpracownika.',
    'heic-to-jpg': 'To klasyczny problem iPhone’a: zdjęcia wyglądają dobrze na telefonie, ale trafiają na komputer z Windows lub do formularza internetowego jako niemożliwe do otwarcia pliki .heic.',
    'heic-to-png': 'Użyj tego, gdy zamierzasz zdjęcie edytować, a nie tylko udostępnić — PNG podaje edytorowi bezstratne piksele zamiast świeżo skompresowanej ponownie kopii.',
    'svg-to-png': 'Zwykłym powodem jest narzędzie odrzucające wektory: prezentacja, ogłoszenie na platformie handlowej, stopka e-mail albo proces produkcji ikon aplikacji, który przyjmuje wyłącznie piksele.',
    'svg-to-jpg': 'To dla miejsc oczekujących zwykłego pliku typu zdjęciowego — dokumentu, wpisu w mediach społecznościowych albo formularza przesyłania odrzucającego zarówno znaczniki SVG, jak i przezroczystość.',
    'bmp-to-png': 'Pliki BMP wychodzą ze starego oprogramowania Windows i ze skanerów w absurdalnych rozmiarach; PNG zapisuje dokładnie te same piksele w ułamku miejsca.',
    'tiff-to-jpg': 'Skanery i profesjonalne aparaty tworzą pliki TIFF o wiele za duże do wysłania mailem, więc JPG jest tym, co się wysyła, gdy kopia archiwalna jest już bezpiecznie zapisana.',
    'gif-to-png': 'To robi się z nieruchomym GIF-em — logotypem, ikoną albo wyeksportowaną klatką — który pokazuje pasma kolorów lub postrzępioną krawędź przez ograniczenie do 256 kolorów.',
    'png-to-ico': 'Niemal każdy, kto zamienia PNG na ICO, buduje faviconę albo ikonę aplikacji Windows, a oba przypadki oczekują kontenera ICO, a nie zwykłego pliku obrazu.',
    'jfif-to-png': 'Pliki JFIF pojawiają się zwykle wtedy, gdy zdjęcie zostaje zapisane z Outlooka lub przeglądarki, a Windows następnie odmawia przekazania go aplikacji, której naprawdę chciałeś użyć.',
    'heic-to-pdf': 'Przydatne, gdy fotografujesz iPhone’em dokumenty, paragony albo tablicę i musisz złożyć je jako jeden plik, a nie folder obrazów.',
    'image-compressor': 'Zwykłym powodem jest gdzieś twardy limit — formularz przesyłania, górna granica załącznika w poczcie albo strona, która ładuje się zbyt wolno, bo jej obrazy są znacznie większe, niż trzeba.',
    'jpeg-compressor': 'Fotografowie i właściciele stron sięgają po to, gdy pliki JPEG w pełnej rozdzielczości spowalniają stronę albo nie mieszczą się w limicie przesyłania.',
    'png-compressor': 'Zrzuty ekranu i wyeksportowana grafika interfejsu często ważą po kilka megabajtów bez żadnego powodu; to je zmniejsza, zanim trafią do dokumentu, zgłoszenia albo na stronę.',
    'mp4-to-avi': 'Powodem jest niemal zawsze starsze urządzenie albo konkretny program — niektóre wiekowe odtwarzacze, narzędzia do tworzenia DVD i programy do aparatów czytają AVI i nic poza tym.',
    'mp4-to-mov': 'To zwykle pierwszy krok przed montażem na Macu, bo Final Cut Pro i iMovie radzą sobie z plikami QuickTime najpłynniej.',
    'mov-to-mp4': 'iPhone i Mac nagrywają w MOV; wszystko inne oczekuje MP4, więc tę konwersję wykonuje się przed przesłaniem, wysłaniem lub opublikowaniem klipu.',
    'mkv-to-mp4': 'MKV jest doskonały do przechowywania, ale telefony, telewizory, przeglądarki i większość programów montażowych go nie odtworzą — zamiana na MP4 sprawia, że plik staje się naprawdę użyteczny.',
    'webm-to-mp4': 'Pliki WebM zapisane z sieci często odmawiają otwarcia w QuickTime, na iOS lub w Premiere; MP4 to format, który akceptują wszystkie.',
    'avi-to-mp4': 'To standardowy ratunek dla starych nagrań z kamery i archiwalnych klipów, które pochłaniają gigabajty i nie odtworzą się na żadnym telefonie.',
    'flv-to-mp4': 'Flash zniknął ze wszystkich przeglądarek, więc każdy pozostały plik FLV jest w praktyce nieodtwarzalny — zamiana na MP4 utrzymuje to archiwalne nagranie w stanie do oglądania.',
    'wmv-to-mp4': 'WMV to pozostałość wyłącznie windowsowa, więc to robi się przed wysłaniem starego nagrania lub zapisu ekranu na Maca, iPhone’a albo platformę internetową.',
    'mp4-to-mp3': 'Zwykle chodzi o dźwięk, a nie o obraz — wykład, wywiad, podcast albo teledysk, który chcesz mieć w telefonie bez dźwigania wideo.',
    'video-to-mp3': 'Sięga się po to, gdy warto zachować właśnie dźwięk: nagrany wykład, wywiad, próbę albo ścieżkę muzyczną.',
    'mp4-converter': 'To narzędzie do sytuacji, gdy klip się nie odtwarza albo nie da się go przesłać, bo MP4 to jedyny format wideo akceptowany zarówno przez telefony, przeglądarki, telewizory, jak i platformy społecznościowe.',
    'video-converter': 'Użyj go, gdy klip musi zmienić świat — wyjść z programu montażowego, trafić na telefon, do przeglądarki albo na platformę przyjmującą tylko jeden konkretny kontener.',
    'mp3-to-wav': 'Zwykłym powodem jest edycja: programy DAW, łańcuchy masteringowe i wiele procesów dźwiękowych dla radia czy gier oczekuje nieskompresowanego WAV-a, żeby nie dekodować skompresowanego pliku przy każdej operacji.',
    'wav-to-mp3': 'Nagrania wychodzą z rejestratora terenowego lub programu DAW jako ogromne pliki WAV; MP3 sprawia, że stają się dość małe, by je wysłać, przesłać albo zmieścić w telefonie.',
    'flac-to-mp3': 'Biblioteka FLAC brzmi znakomicie w domu, ale radia samochodowe, starsze telefony i tanie odtwarzacze często jej odmawiają — MP3 to kopia zgodnościowa, którą bierze się ze sobą.',
    'aac-to-mp3': 'To głównie kwestia zgodności: AAC pochodzi z ekosystemu Apple i serwisów strumieniowych, podczas gdy starsze odtwarzacze, radia samochodowe i oprogramowanie didżejskie oczekują MP3.',
    'ogg-to-mp3': 'OGG pojawia się w grach, na Wikipedii i w oprogramowaniu open source, a prawie żaden z popularnych odtwarzaczy w telefonie czy samochodzie go nie otwiera.',
    'wma-to-mp3': 'WMA to relikt epoki Windows Media Player, więc tak ratuje się starą, zgraną kolekcję muzyki na telefon albo do biblioteki strumieniowej.',
    'm4a-to-mp3': 'To typowy krok przy przenoszeniu muzyki lub notatek głosowych iPhone’a z urządzeń Apple do programów, samochodów albo odtwarzaczy rozumiejących wyłącznie MP3.',
    'mp3-to-aac': 'Niektóre urządzenia i aplikacje — zwłaszcza w świecie Apple i serwisów strumieniowych — wolą AAC, więc to konwersja zgodnościowa, a nie poprawa jakości.',
    'mp3-to-ogg': 'Na OGG zamienia się dla silników gier, projektów open source i platform wymagających kodeka wolnego od patentów.',
    'audio-converter': 'To narzędzie na chwilę, gdy plik się nie odtwarza: jedno miejsce, by przenieść dźwięk do tego z popularnych formatów, przy którym upiera się twoje urządzenie, edytor albo formularz przesyłania.',
    'rar-to-zip': 'RAR wymaga dodatkowego oprogramowania do otwarcia, więc to robi się przed wysłaniem archiwum komuś, kto nie zainstaluje WinRAR-a.',
    '7z-to-zip': '7Z kompresuje lepiej, ale wymaga zainstalowanego 7-Zipa; w postaci ZIP odbiorca może po prostu kliknąć plik dwukrotnie.',
    'tar-to-zip': 'TAR pochodzi z wiersza poleceń Linuksa i macOS, natomiast ZIP to coś, co współpracownik na Windows otworzy bez instalowania czegokolwiek.',
    'gz-to-zip': 'Pliki GZ przychodzą zwykle z serwera albo z narzędzia linuksowego i są niewygodne w Windows, gdzie ZIP rozpakowuje się dwukrotnym kliknięciem.',
    'zip-to-7z': 'Tu chodzi o rozmiar: kompresja 7Z jest wyraźnie mocniejsza, co ma znaczenie, gdy archiwizujesz duży folder albo płacisz za magazyn w chmurze od gigabajta.',
    'video-to-gif': 'Typowe zastosowanie to krótka pętla do wiadomości na czacie, pliku README, zgłoszenia błędu albo wpisu w mediach społecznościowych — miejsc, gdzie GIF odtwarza się sam w treści, a plik wideo nie.',
    'mp4-to-gif': 'Typowe zastosowanie to krótka pętla do czatu, pliku README, zgłoszenia błędu albo wpisu, gdzie GIF odtwarza się sam w treści, a wideo leżałoby tylko jako załącznik.',
    'webm-to-gif': 'Klipy WebM zapisane z sieci często nie chcą się osadzić tam, gdzie trzeba, podczas gdy GIF odtwarza się w treści w komunikatorach, systemach zgłoszeń i na forach.',
    'mov-to-gif': 'To robi się z nagraniem ekranu z QuickTime, które ma pojawić się w treści pull requesta, zgłoszenia do pomocy technicznej albo wpisu.',
    'avi-to-gif': 'Zamiana kilku sekund starego klipu AVI w GIF-a to najprostszy sposób, by trafiły do dokumentu, wątku na czacie albo na stronę.',
    'gif-to-mp4': 'Długie GIF-y są ogromne i odtwarzają się skokowo; MP4 pokazuje tę samą animację przy ułamku rozmiaru, i dokładnie dlatego platformy społecznościowe zamieniają je po cichu.',
    'image-to-gif': 'Przydatne, gdy platforma albo starszy system wyraźnie oczekuje GIF-a, albo gdy potrzebna jest nieruchoma klatka w tym samym formacie co istniejąca seria animacji.',
    'gif-compressor': 'Animowane GIF-y szybko puchną, a to jest rozwiązanie, gdy któryś jest zbyt ciężki na e-mail, limit przesyłania w czacie albo stronę, która musi szybko się ładować.',
    'merge-pdf': 'Klasyczny przypadek to wniosek albo zgłoszenie szkody: formularz, skan i paragon, które muszą dotrzeć jako jeden dokument.',
    'split-pdf': 'Zwykle potrzebujesz dokładnie jednej rzeczy z o wiele dłuższego pliku — jednego rozdziału, jednej faktury, jednej podpisanej strony z pięćdziesięciostronicowego skanu.',
    'compress-pdf': 'Niemal zawsze limit rozmiaru: górna granica załącznika w poczcie, formularz urzędowy albo portal odrzucający wszystko powyżej kilku megabajtów.',
    'rotate-pdf': 'To naprawia codzienny problem ze skanerem — strony, które wyszły bokiem albo do góry nogami przez sposób podania arkuszy.',
    'protect-pdf': 'Pliki PDF zabezpiecza się hasłem przed wysłaniem pasków płacowych, umów albo pism medycznych, żeby treść nie była czytelna dla tego, komu wiadomość zostanie potem przekazana dalej.',
    'unlock-pdf': 'Używaj go do własnych dokumentów, gdy hasło jest znane, ale ograniczenie przeszkadza — na przykład wyciągu bankowego, którego nie da się wydrukować.',
    'view-metadata': 'Odpowiada na pytania, których plik nie zdradza wprost: jaki aparat zrobił to zdjęcie, ile naprawdę trwa to nagranie, jaki kodek siedzi w tym wideo, ile stron ma ten PDF.',
    'ocr': 'Sytuacja jest zawsze ta sama: masz dokument jako obraz i potrzebujesz zawartych w nim słów — żeby je przeszukać, zacytować, edytować albo porządnie zarchiwizować.',
    'pdf-compress-ai': 'Sięgnij po to, gdy zwykła kompresja została już wypróbowana, a plik wciąż jest zbyt duży dla limitu przesyłania, z którym się zmagasz.',
    'text-to-speech': 'Używa się tego, by czegoś posłuchać zamiast czytać — artykułu w drodze do pracy, scenariusza odczytanego na głos, by wyłapać niezgrabne sformułowania, albo lektora do filmu.',
    'speech-to-text': 'Typowy przypadek to nagranie potrzebne na piśmie: spotkanie, wywiad, wykład albo notatka głosowa, która ma stać się notatkami, protokołem lub zdatnym do cytowania zapisem.',
    'auto-subtitle': 'Napisy sprawiają, że film da się oglądać bez dźwięku i że znajdują go wyszukiwarki, a wpisywanie ich ręcznie zajmuje nawet przy krótkim klipie znacznie więcej czasu, niż się wydaje.',
    'document-translation': 'Celem jest przeczytanie lub wysłanie dokumentu w innym języku bez utraty układu, który czyni go czytelnym.',
  },
  t: {
    'list.and': 'oraz',
    'family.document': 'dokumentów',
    'family.image': 'obrazów',
    'family.video': 'wideo',
    'family.audio': 'dźwięku',
    'family.ebook': 'e-booków',
    'family.archive': 'archiwów',
    'family.subtitle': 'napisów',
    'family.none': 'plików',
    'unit.sample': 'każda próbka',
    'unit.pixel': 'każdy piksel',

    'intro.convert': '{{fromAbout}} {{toAbout}} {{reason}} {{toNote}}',
    'intro.convert.noSource': '{{fn}} jest formatem źródłowym tej konwersji.',
    'intro.lead': '{{lead}} {{reason}}',
    'intro.hub': 'To uniwersalny konwerter {{category}}: przyjmuje {{inputs}} i zapisuje {{outputs}}, więc nie musisz szukać jednego konkretnego narzędzia pasującego do twojej pary formatów. {{reason}} Wybierz powyżej format wyjściowy — konwersja odbywa się na serwerze, nie ma czego instalować.',
    'intro.hubExtract': 'To narzędzie wyciąga ścieżkę dźwiękową z pliku wideo i zapisuje ją osobno, zamieniając film w zwykły plik dźwiękowy, który odtworzysz wszędzie. Przyjmuje {{inputs}} i zapisuje {{outputs}}. Ścieżka wideo jest po prostu odrzucana, dlatego wynik zajmuje ułamek pierwotnego rozmiaru. {{reason}}',
    'intro.hubGif': 'To narzędzie zamienia pliki {{inputs}} w animowane GIF-y. {{gifAbout}} {{reason}}',
    'intro.hubGif.gifAbout': 'GIF jest ograniczony do palety 256 kolorów na klatkę, dlatego zdjęcia wyglądają w nim pasmowo, ale animuje się i odtwarza samoczynnie w treści niemal wszędzie w internecie.',
    'intro.compress': '{{about}} To narzędzie koduje twój plik {{fn}} ponownie w mniejszym rozmiarze bez zmiany formatu, więc to, co pobierzesz, wciąż jest zwykłym plikiem {{fn}}, otwierającym się dokładnie tam, gdzie otwierał się oryginał. {{reason}}{{extra}}',
    'intro.compress.lossless': ' Ponieważ {{fn}} jest bezstratny, większość oszczędności bierze się z mądrzejszego kodowania i ograniczenia palety, a nie z odrzucania szczegółów.',
    'intro.soon': '{{reason}} To narzędzie jeszcze nie działa — jest w trakcie budowy i pojawi się tutaj, gdy tylko będzie gotowe.',
    'intro.lead.pdf-merge': 'Łączenie scala kilka plików PDF w jeden, w wybranej przez ciebie kolejności, bez ponownego renderowania stron — tekst pozostaje zaznaczalny, a obrazy zachowują pierwotną jakość. PDF to format o stałym układzie: zapisuje dokładną pozycję każdego znaku, każdej linii i każdego obrazu, dlatego wygląda identycznie wszędzie, ale jest niewygodny w edycji.',
    'intro.lead.pdf-split': 'Dzielenie wyciąga z PDF-a wskazane strony i zapisuje je jako nowy dokument, pozostawiając oryginał nietknięty. PDF to format o stałym układzie: zapisuje dokładną pozycję każdego znaku, każdej linii i każdego obrazu, dlatego wygląda identycznie wszędzie, ale jest niewygodny w edycji.',
    'intro.lead.pdf-compress': 'Kompresja PDF-a koduje na nowo znajdujące się w nim obrazy i usuwa zbędne dane osadzone, a to właśnie tam kryje się niemal cały rozmiar dużego pliku PDF. Tekst i grafika wektorowa pozostają ostre.',
    'intro.lead.pdf-compress-ai': 'To narzędzie najpierw analizuje zawartość PDF-a, zanim go skompresuje, dzięki czemu obrazy fotograficzne, płaska grafika i strony z samym tekstem są traktowane każde w sposób oszczędzający najwięcej miejsca bez widocznego pogorszenia.',
    'intro.lead.pdf-rotate': 'Obracanie zmienia znacznik orientacji i geometrię stron PDF-a, aby wyświetlały się i drukowały właściwą stroną. Nic nie jest renderowane od nowa, więc nie traci się jakości.',
    'intro.lead.pdf-protect': 'Zabezpieczenie PDF-a szyfruje jego zawartość, tak że nie da się go otworzyć bez ustawionego przez ciebie hasła. Szyfrowanie stosuje się do samego pliku, a nie do opakowania wokół niego.',
    'intro.lead.pdf-unlock': 'Odblokowanie usuwa hasło i ograniczenia użycia z PDF-a, którego hasło już posiadasz, aby można było go znów normalnie otwierać, drukować i kopiować.',
    'intro.lead.metadata': 'Każdy plik niesie informacje o sobie, których nie widać po otwarciu: wymiary obrazu i ustawienia aparatu, czas trwania i przepływność dźwięku, kodek i liczbę klatek wideo, autora i liczbę stron dokumentu. To narzędzie odczytuje te metadane i pokazuje je tobie.',
    'intro.lead.ocr': 'Optyczne rozpoznawanie znaków patrzy na obraz tekstu — skan, zdjęcie, stronę PDF bez warstwy tekstowej — i ustala, jakie to znaki, zamieniając obrazek ze słowami w słowa, które komputer może przeszukiwać, kopiować i edytować.',
    'intro.lead.tts': 'Zamiana tekstu na mowę generuje mówiony dźwięk z zapisanego tekstu przy użyciu głosów neuronowych, więc otrzymujesz naturalnie brzmiące nagranie zamiast płaskiego, robotycznego efektu starszych systemów.',
    'intro.lead.stt': 'Zamiana mowy na tekst przepisuje mówiony dźwięk na słowa. Radzi sobie z naturalną mową, akcentami i szumem tła znacznie lepiej niż dawne oprogramowanie do dyktowania, i zwraca zapis, który możesz edytować.',
    'intro.lead.subtitle': 'Generator napisów przepisuje mowę z filmu i zapisuje ją z kodami czasowymi, tworząc standardowy plik napisów, a nie zwykły zapis rozmowy.',

    'steps.convert.1.batch': 'Przeciągnij plik {{fn}} na obszar przesyłania u góry tej strony albo kliknij go, by wybrać plik z urządzenia. Możesz dodać kilka plików — albo cały folder — i przekonwertować wszystkie naraz.',
    'steps.convert.1.single': 'Przeciągnij plik {{fn}} na obszar przesyłania u góry tej strony albo kliknij go, by wybrać plik z urządzenia.',
    'steps.convert.2.direct': 'Wybierz {{tn}} jako format wyjściowy i kliknij Konwertuj.',
    'steps.convert.2.dropdown': 'Wybierz {{tn}} jako format wyjściowy z listy rozwijanej i kliknij Konwertuj.',
    'steps.convert.2.directMedia': 'Wybierz {{tn}} jako format wyjściowy, w razie potrzeby dostosuj jakość lub rozmiar w ustawieniach zaawansowanych i kliknij Konwertuj.',
    'steps.convert.2.dropdownMedia': 'Wybierz {{tn}} jako format wyjściowy z listy rozwijanej, w razie potrzeby dostosuj jakość lub rozmiar w ustawieniach zaawansowanych i kliknij Konwertuj.',
    'steps.convert.3': 'Pobierz gotowy plik {{tn}}. Odnośnik do pobrania działa przez 24 godziny, po czym oba pliki zostają automatycznie usunięte.',
    'steps.hub.1.batch': 'Przeciągnij plik na obszar przesyłania u góry tej strony albo kliknij go, by wybrać plik z urządzenia — konwerter {{category}} akceptuje formaty {{inputs}}. Możesz dodać kilka plików — albo cały folder — i przekonwertować wszystkie naraz.',
    'steps.hub.1.single': 'Przeciągnij plik na obszar przesyłania u góry tej strony albo kliknij go, by wybrać plik z urządzenia — konwerter {{category}} akceptuje formaty {{inputs}}.',
    'steps.hub.2.direct': 'Wybierz potrzebny format wyjściowy i kliknij Konwertuj.',
    'steps.hub.2.dropdown': 'Wybierz potrzebny format wyjściowy z listy rozwijanej i kliknij Konwertuj.',
    'steps.hub.2.directMedia': 'Wybierz potrzebny format wyjściowy, w razie potrzeby dostosuj jakość lub rozmiar w ustawieniach zaawansowanych i kliknij Konwertuj.',
    'steps.hub.2.dropdownMedia': 'Wybierz potrzebny format wyjściowy z listy rozwijanej, w razie potrzeby dostosuj jakość lub rozmiar w ustawieniach zaawansowanych i kliknij Konwertuj.',
    'steps.hub.3': 'Pobierz gotowy plik. Odnośnik do pobrania działa przez 24 godziny, po czym oba pliki zostają automatycznie usunięte.',
    'steps.pdf-merge.1': 'Dodaj każdy plik PDF, który chcesz połączyć — przeciągnij je razem na obszar przesyłania albo kliknij, by wybierać je kolejno.',
    'steps.pdf-merge.2': 'Przeciągnij pliki w kolejności, w jakiej mają się pojawić w gotowym dokumencie.',
    'steps.pdf-merge.3': 'Kliknij Połącz i pobierz jeden scalony plik PDF.',
    'steps.pdf-split.1': 'Prześlij PDF, z którego chcesz wyjąć strony.',
    'steps.pdf-split.2': 'Wpisz potrzebne strony lub zakresy w polu zakresów stron — na przykład 1-3, 5, 7-10.',
    'steps.pdf-split.3': 'Kliknij Konwertuj i pobierz wyodrębnione strony.',
    'steps.pdf-compress.1': 'Przeciągnij plik PDF na obszar przesyłania albo kliknij, by go odszukać.',
    'steps.pdf-compress.2': 'Kliknij Konwertuj — plik zostanie przeanalizowany, a jego obrazy i dane osadzone zakodowane ponownie w mniejszym rozmiarze.',
    'steps.pdf-compress.3': 'Pobierz skompresowany PDF i sprawdź oszczędność rozmiaru pokazaną obok.',
    'steps.pdf-rotate.1': 'Prześlij PDF, którego strony są ustawione niewłaściwą stroną.',
    'steps.pdf-rotate.2': 'Wybierz, o ile je obrócić — 90°, 180° albo 270°.',
    'steps.pdf-rotate.3': 'Kliknij Konwertuj i pobierz poprawiony plik PDF.',
    'steps.pdf-protect.1': 'Prześlij PDF, który chcesz zabezpieczyć.',
    'steps.pdf-protect.2': 'Wpisz hasło, które będzie potrzebne do jego otwarcia, i zachowaj jego kopię w bezpiecznym miejscu.',
    'steps.pdf-protect.3': 'Kliknij Konwertuj i pobierz zaszyfrowany plik PDF.',
    'steps.pdf-unlock.1': 'Prześlij PDF zabezpieczony hasłem.',
    'steps.pdf-unlock.2': 'Wpisz jego bieżące hasło, aby plik dało się odszyfrować.',
    'steps.pdf-unlock.3': 'Kliknij Konwertuj i pobierz odblokowany plik PDF.',
    'steps.metadata.1': 'Przeciągnij dowolny plik na obszar przesyłania — obraz, wideo, plik dźwiękowy albo dokument.',
    'steps.metadata.2': 'Plik jest badany, a nie konwertowany, więc nic w nim się nie zmienia.',
    'steps.metadata.3': 'Odczytaj metadane bezpośrednio na stronie: wymiary, czas trwania, kodek, dane aparatu, liczbę stron i więcej.',
    'steps.ocr.1': 'Prześlij zeskanowany plik PDF albo zdjęcie tekstu.',
    'steps.ocr.2': 'Wybierz język dokumentu i to, czy chcesz przeszukiwalny PDF, czy zwykły tekst.',
    'steps.ocr.3': 'Kliknij Konwertuj i pobierz wynik — rozpoznany tekst będzie już zaznaczalny i przeszukiwalny.',
    'steps.tts.1': 'Wpisz lub wklej tekst w polu — do 4096 znaków na jedną konwersję.',
    'steps.tts.2': 'Wybierz głos, tempo mowy i format wyjściowy.',
    'steps.tts.3': 'Kliknij Konwertuj i pobierz gotowy plik dźwiękowy.',
    'steps.stt.1': 'Prześlij nagranie albo nagraj prosto z mikrofonu przyciskiem na tej stronie.',
    'steps.stt.2': 'Opcjonalnie ustaw język mówiony, by poprawić dokładność, i wybierz wynik w TXT lub DOCX.',
    'steps.stt.3': 'Kliknij Konwertuj, przeczytaj zapis na stronie, a potem go pobierz.',
    'steps.subtitle.1': 'Prześlij film, do którego chcesz napisy.',
    'steps.subtitle.2': 'Wybierz SRT albo VTT i podaj język mówiony, jeśli go znasz.',
    'steps.subtitle.3': 'Kliknij Konwertuj i pobierz plik napisów z kodami czasowymi, gotowy do wrzucenia do odtwarzacza lub programu montażowego.',
    'steps.compress.1': 'Przeciągnij obrazy {{fn}} na obszar przesyłania albo kliknij, by je wybrać. Możesz dodać cały folder naraz.',
    'steps.compress.1.gif': 'Przeciągnij animację {{fn}} na obszar przesyłania albo kliknij, by ją wybrać. Możesz dodać cały folder naraz.',
    'steps.compress.2': 'Kliknij Konwertuj — plik zostanie zakodowany ponownie w mniejszym rozmiarze, pozostając w tym samym formacie.',
    'steps.compress.3': 'Pobierz wynik i porównaj go z pierwotnym rozmiarem pokazanym na stronie.',
    'steps.soon.1': 'Wybierz potrzebne narzędzie na stronie Narzędzia — wszystko poza tym działa już dziś.',
    'steps.soon.2': 'Prześlij plik i wybierz format wyjściowy.',
    'steps.soon.3': 'Pobierz wynik albo zajrzyj tu ponownie, gdy tłumaczenie dokumentów zacznie działać.',

    'faq.cost.q.pair': 'Czy konwersja {{from}} na {{to}} jest darmowa?',
    'faq.cost.q.tool': 'Czy {{label}} jest darmowe?',
    'faq.cost.a.pair': 'Nowe konta dostają jeden darmowy kredyt konwersji, więc pierwsza konwersja {{from}} na {{to}} nic nie kosztuje. Później każda konwersja zużywa jeden kredyt z małego pakietu przedpłaconego — nie ma abonamentu, kredyty nigdy nie wygasają, a za nieudaną konwersję nie płacisz.',
    'faq.cost.a.tool': 'Nowe konta dostają jeden darmowy kredyt konwersji, więc pierwszy plik nic nie kosztuje. Później każda konwersja zużywa jeden kredyt z małego pakietu przedpłaconego — nie ma abonamentu, kredyty nigdy nie wygasają, a za nieudaną konwersję nie płacisz.',
    'faq.cost.a.smartTts': 'Nowe konta dostają jeden darmowy kredyt konwersji na próbę, a funkcje inteligentne rozliczane są za zużycie, a nie za plik — 1 kredyt za każde 1000 znaków tekstu, zaokrąglone w górę. Nie ma abonamentu: kredyty kupuje się w małych pakietach przedpłaconych, nigdy nie wygasają, a nieudana konwersja nigdy nic nie kosztuje.',
    'faq.cost.a.smartAv': 'Nowe konta dostają jeden darmowy kredyt konwersji na próbę, a funkcje inteligentne rozliczane są za zużycie, a nie za plik — 1 kredyt za każde 5 minut dźwięku lub wideo, zaokrąglone w górę. Nie ma abonamentu: kredyty kupuje się w małych pakietach przedpłaconych, nigdy nie wygasają, a nieudana konwersja nigdy nic nie kosztuje.',
    'faq.cost.q.metadata': 'Czy narzędzie Informacje o pliku jest darmowe?',
    'faq.cost.a.metadata': 'Tak. Odczyt metadanych pliku nie jest konwersją, więc nie zużywa kredytu — możesz sprawdzić dowolnie wiele plików. Kredyty wydaje się tylko wtedy, gdy narzędzie faktycznie tworzy dla ciebie nowy plik.',
    'faq.cost.q.soon': 'Czy {{label}} jest już dostępne?',
    'faq.cost.a.soon': 'Jeszcze nie — ta strona jest miejscem zarezerwowanym na czas budowy narzędzia, więc dziś nie ma tu czego przesyłać. Cennik będzie taki sam jak w reszcie serwisu: model przedpłaconych kredytów, bez abonamentu, kredyty nigdy nie wygasają, a nieudana konwersja nic nie kosztuje.',

    'faq.time.q.pair': 'Ile trwa konwersja {{from}} na {{to}}?',
    'faq.time.q.tool': 'Ile trwa {{label}}?',
    'faq.time.a': '{{speed}} Zwykle to prędkość wysyłania jest czynnikiem ograniczającym, więc duży plik na wolnym łączu zajmuje więcej czasu niż sama konwersja.{{suffix}}',
    'faq.time.speed.image': 'Obrazy konwertujemy najszybciej — pojedyncze zdjęcie jest zwykle gotowe w mniej niż pięć sekund, a cały folder zajmuje mniej więcej tyle, ile samo wysyłanie.',
    'faq.time.speed.document': 'Większość dokumentów jest gotowa w kilka sekund. Bardzo długie pliki — kilkaset stron albo skan pełen obrazów — mogą zająć nawet minutę.',
    'faq.time.speed.audio': 'Typowy utwór konwertuje się w kilka sekund. Pełne nagranie, takie jak wykład albo odcinek podcastu, zajmuje zwykle znacznie mniej niż minutę, a większość tego to wysyłanie.',
    'faq.time.speed.video': 'Wideo to najwolniejsza kategoria, bo każdą klatkę trzeba zakodować od nowa. Krótki klip zajmuje sekundy, a długi plik w wysokiej rozdzielczości może zająć kilka minut.',
    'faq.time.speed.archive': 'Archiwa konwertują się w sekundy, choć duże trwa dłużej, bo każdy plik w środku trzeba rozpakować i spakować ponownie.',
    'faq.time.speed.ebook': 'E-booki idą szybko — cała powieść konwertuje się zwykle w kilka sekund.',
    'faq.time.speed.subtitle': 'Transkrypcja postępuje w tempie mniej więcej kilku sekund na minutę dźwięku, więc dziesięciominutowy film zwykle dostaje napisy w znacznie mniej niż minutę.',
    'faq.time.suffix.standard': ' Przyjmujemy pliki do 200 MB.',
    'faq.time.suffix.smart': ' Funkcje inteligentne przyjmują pliki do 25 MB; zwykłe konwersje do 200 MB.',
    'faq.time.q.metadata': 'Ile trwa odczytanie metadanych pliku?',
    'faq.time.a.metadata': 'Sekundę lub dwie, gdy plik już się prześle. Nic nie jest konwertowane ani kodowane od nowa — nagłówki zostają odczytane, a wynik trafia prosto na stronę — więc czekanie to w istocie samo wysyłanie.',
    'faq.time.q.soon': 'Czy to będzie kosztować dodatkowo?',
    'faq.time.a.soon': 'Będzie korzystać z tych samych kredytów co wszystko inne w serwisie. Nie ma osobnego planu ani abonamentu, do którego trzeba by przystąpić, a kredyty już zapisane na twoim koncie zadziałają z nim od chwili uruchomienia.',

    'faq.safety.q.pair': 'Czy przesłanie mojego pliku {{from}} jest bezpieczne?',
    'faq.safety.q.tool': 'Czy mój plik jest bezpieczny?',
    'faq.safety.a.pair': 'Pliki podróżują szyfrowanym połączeniem TLS i nie służą do niczego poza konwersją, o którą poprosiłeś. Zarówno twój pierwotny plik {{from}}, jak i zwracany przez nas plik {{to}} zostają automatycznie usunięte w ciągu 24 godzin — trwale i bez zachowywania kopii zapasowych — a ich treść nigdy nie jest czytana, analizowana ani udostępniana. Serwis prowadzony jest z Niemiec, zgodnie z RODO.',
    'faq.safety.a.tool': 'Pliki podróżują szyfrowanym połączeniem TLS i nie służą do niczego poza konwersją, o którą poprosiłeś. Zarówno twój pierwotny plik, jak i zwracany przez nas wynik zostają automatycznie usunięte w ciągu 24 godzin — trwale i bez zachowywania kopii zapasowych — a ich treść nigdy nie jest czytana, analizowana ani udostępniana. Serwis prowadzony jest z Niemiec, zgodnie z RODO.',

    'quality.vectorRaster.q': 'Czy mój {{fn}} pozostanie ostry jako {{tn}}?',
    'quality.vectorRaster.a': 'Do rozmiaru, w jakim go wyeksportujesz — tak. {{fn}} przechowuje kształty zamiast pikseli, więc skaluje się bez końca, ale {{tn}} to stała siatka pikseli i rozmyje się, jeśli potem powiększysz go ponad tę siatkę. Przed konwersją ustaw w ustawieniach zaawansowanych szerokość i wysokość, których naprawdę potrzebujesz — eksport w dwu- lub trzykrotnym rozmiarze wyświetlania to typowa sztuczka dla ekranów o dużej gęstości pikseli. Zachowaj pierwotny plik {{fn}}: pozostaje kopią wzorcową, z której możesz eksportować w dowolnej rozdzielczości.',
    'quality.docToTxt.q': 'Czy stracę formatowanie, konwertując {{fn}} na {{tn}}?',
    'quality.docToTxt.a': 'Tak, i to celowo — plik {{tn}} zawiera znaki i nic więcej. Czcionki, kolory, obrazy, tabele, kolumny i podziały stron znikają; wracasz z czytelnym tekstem dokumentu w kolejności czytania. Dokładnie tego chcesz do wyszukiwania, skryptów albo podania tekstu innemu programowi, i dokładnie tego nie chcesz, jeśli liczyłeś na zachowanie układu. Uwaga: {{fn}}, który w istocie jest zeskanowanym obrazem, nie zawiera żadnego tekstu do wyciągnięcia — przepuść go zamiast tego przez narzędzie OCR.',
    'quality.docToSheet.q': 'Jak dokładne jest wyciąganie tabel z {{fn}}?',
    'quality.docToSheet.a': 'Czyste tabele z liniami i równymi kolumnami — wyciągi, faktury, wyeksportowane raporty — przechodzą niezawodnie, a każda wartość ląduje we własnej komórce, więc da się ją zsumować i posortować. Tabele bez widocznych obramowań, komórki obejmujące kilka wierszy albo liczby rozdzielone podziałem strony warto potem sprawdzić wzrokiem. {{fn}} przechowuje pozycje, a nie strukturę tabeli, więc konwersja musi wywnioskować, gdzie kończy się jedna kolumna, a zaczyna następna.',
    'quality.docToReflow.q': 'Czy układ przetrwa konwersję {{fn}} na {{tn}}?',
    'quality.docToReflow.a': 'Nie do końca — i o to właśnie chodzi. {{fn}} przypina tekst do sztywnych współrzędnych strony; {{tn}} przelewa go tak, by pasował do ekranu i rozmiaru czcionki czytelnika, więc stałe numery stron, nagłówki, stopki i układy wielołamowe są reinterpretowane, a nie odtwarzane. Tekst główny, nagłówki, kolejność akapitów i obrazy przechodzą dobrze. Dokumenty złożone głównie z prozy konwertują się znakomicie; to mocno zaprojektowane strony, formularze i złożone tabele wymagają potem spojrzenia.',
    'quality.docToFixed.q': 'Czy moje formatowanie zostanie zachowane w {{tn}}?',
    'quality.docToFixed.a': 'Tak — ten kierunek jest bezpieczny. {{tn}} zapisuje stronę w postaci ostatecznie wyrenderowanej, więc czcionki, odstępy, tabele, obrazy i podziały stron zostają zamrożone dokładnie tak, jak je złożono, i będą wyglądać tak samo na każdym urządzeniu i drukarce. To zarazem cena: wynik przestaje być swobodnie edytowalny, a to zwykle właśnie powód, dla którego zamienia się dokument na {{tn}} przed wysłaniem.',
    'quality.docToEditable.q': 'Jak dokładna jest konwersja {{fn}} na {{tn}}?',
    'quality.docToEditable.a': 'Tekst, nagłówki, listy, obrazy i proste tabele przechodzą niezawodnie i pozostają w pełni edytowalne. Ponieważ {{fn}} przechowuje pozycje, a nie strukturę, konwersja musi tę strukturę odtworzyć, więc mocno zaprojektowane strony — kilka łamów, tekst opływający obrazy, złożone tabele zagnieżdżone — mogą wymagać potem lekkiego uporządkowania. Jeśli PDF jest skanem zupełnie bez warstwy tekstowej, użyj zamiast tego narzędzia OCR: rozpoznaje ono znaki na obrazie, zamiast szukać tekstu, którego tam nie ma.',
    'quality.docGeneric.q': 'Czy coś stracę, konwertując {{fn}} na {{tn}}?',
    'quality.docGeneric.a': 'Słowa, nagłówki, listy i obrazy przechodzą nienaruszone. {{tn}} dysponuje innym słownikiem formatowania niż {{fn}}, więc bardzo szczególne style mogą zostać po drodze uproszczone, ale sama treść zostaje zachowana.',
    'quality.archive.q': 'Czy pliki w moim archiwum {{fn}} zostaną zmienione?',
    'quality.archive.a': 'Nie. Formaty archiwów to bezstratne kontenery: {{fn}} zostaje rozpakowany, a te same pliki spakowane ponownie jako {{tn}}, bajt po bajcie. Zmienia się tylko metoda kompresji i kontener. Zmienia się natomiast rozmiar samego archiwum — {{clause}}.',
    'quality.archive.clause.to7z': '7Z dzięki kompresji LZMA daje zwykle mniejsze archiwum niż ZIP',
    'quality.archive.clause.toZip': 'ZIP jest zwykle nieco większy niż 7Z czy RAR, i to cena za to, że otwiera się wszędzie bez dodatkowego oprogramowania',
    'quality.archive.clause.other': 'nowy format kompresuje inaczej, więc rozmiar pliku może zmienić się w dowolną stronę',
    'quality.imageToDoc.q': 'Czy moje zdjęcia stracą jakość wewnątrz {{tn}}?',
    'quality.imageToDoc.a': 'Nie. Każdy obraz {{fn}} trafia do {{tn}} w postaci niezmienionej, po jednym na stronę, zamiast być kompresowany ponownie, więc to, co widzisz w dokumencie, jest tym, co wyszło z aparatu. {{tn}} będzie ważył mniej więcej tyle, co wszystkie obrazy razem, o czym warto wiedzieć przed wysłaniem go mailem — przepuść wynik przez Kompresję PDF, jeśli ma być mniejszy.',
    'quality.toGif.q': 'Dlaczego mój GIF wygląda gorzej niż pierwotny {{fn}}?',
    'quality.toGif.a': 'Bo GIF jest ograniczony do 256 kolorów na klatkę. Film albo zdjęcie zawiera ich miliony, więc koder musi wybrać paletę i przybliżyć całą resztę, co objawia się pasmami w gradientach i na niebie. GIF nie niesie też żadnej ścieżki dźwiękowej. Jedno i drugie wynika z formatu, a nie z konwersji — trzymaj klip krótko, a jeśli utrata kolorów waży więcej niż samoczynne odtwarzanie w treści, MP4 będzie wyglądać znacznie lepiej przy mniejszym rozmiarze.',
    'quality.lossyToLossless.q': 'Czy konwersja {{fn}} na {{tn}} poprawia jakość?',
    'quality.lossyToLossless.a': 'Nie — i jest to zdecydowanie najczęstsze nieporozumienie wokół tej konwersji. {{fn}} jest stratny: szczegóły odrzucone przez jego koder przepadły na zawsze i nic ich nie odtworzy. {{tn}} daje ci bezstratny kontener na to, co zostało, więc plik przestaje tracić jakość przy każdym kolejnym zapisie czy edycji. To naprawdę przydatne, gdy zaraz zamierzasz {{clause}}, ale nie odzyska jakości, która już przepadła.',
    'quality.lossyToLossless.edit.audio': 'edytować, masterować albo przetwarzać dźwięk',
    'quality.lossyToLossless.edit.image': 'edytować, retuszować albo składać obraz',
    'quality.losslessToLossy.q': 'Czy stracę jakość, konwertując {{fn}} na {{tn}}?',
    'quality.losslessToLossy.a.audio': 'Trochę, i z założenia — właśnie tak plik staje się mniejszy. {{tn}} jest stratny, więc koder odrzuca informacje, które uzna za najmniej zauważalne. Przy rozsądnych ustawieniach różnicę bardzo trudno wychwycić uchem, a w ustawieniach zaawansowanych możesz podnieść przepływność, jeśli wolisz oddać rozmiar za wierność. Zachowaj pierwotny plik {{fn}}: pozostaje kopią wzorcową, a ponowne kodowanie {{tn}} w przyszłości pogłębiłoby stratę.',
    'quality.losslessToLossy.a.visual': 'Trochę, i z założenia — właśnie tak plik staje się mniejszy. {{tn}} jest stratny, więc koder odrzuca informacje, które uzna za najmniej zauważalne. Przy rozsądnych ustawieniach różnicę bardzo trudno wychwycić okiem, a w ustawieniach zaawansowanych możesz podnieść wartość jakości, jeśli wolisz oddać rozmiar za wierność. Zachowaj pierwotny plik {{fn}}: pozostaje kopią wzorcową, a ponowne kodowanie {{tn}} w przyszłości pogłębiłoby stratę.',
    'quality.lossyToLossy.q': 'Czy stracę jakość, konwertując {{fn}} na {{tn}}?',
    'quality.lossyToLossy.a.audio': 'Odrobinę. Oba formaty są stratne, więc {{fn}} zostaje zdekodowany, a następnie zakodowany ponownie jako {{tn}}, i każde pokolenie kodowania stratnego gubi trochę szczegółów. Przy zwykłych ustawieniach większość osób tego nie słyszy, a przepływność możesz podnieść w ustawieniach zaawansowanych. Unikaj natomiast wielokrotnego konwertowania tego samego pliku tam i z powrotem — to właśnie sprawia, że strata staje się słyszalna.',
    'quality.lossyToLossy.a.visual': 'Odrobinę. Oba formaty są stratne, więc {{fn}} zostaje zdekodowany, a następnie zakodowany ponownie jako {{tn}}, i każde pokolenie kodowania stratnego gubi trochę szczegółów. Przy zwykłych ustawieniach większość osób tego nie zauważa, a jakość możesz podnieść w ustawieniach zaawansowanych. Unikaj natomiast wielokrotnego konwertowania tego samego pliku tam i z powrotem — to właśnie sprawia, że strata staje się widoczna.',
    'quality.losslessToLossless.q': 'Czy stracę jakość, konwertując {{fn}} na {{tn}}?',
    'quality.losslessToLossless.a.plain': 'Nie. Zarówno {{fn}}, jak i {{tn}} są bezstratne, więc {{unit}} zostaje zachowany dokładnie, a wynik jest identyczny z oryginałem. Zmienia się tylko rozmiar pliku. Możesz później przekonwertować z powrotem bez żadnej utraty jakości.',
    'quality.losslessToLossless.a.bulky': 'Nie. Zarówno {{fn}}, jak i {{tn}} są bezstratne, więc {{unit}} zostaje zachowany dokładnie, a wynik jest identyczny z oryginałem. Zmienia się tylko rozmiar pliku, zwykle drastycznie w dół, ponieważ {{fn}} przechowuje swoje dane praktycznie bez kompresji. Możesz później przekonwertować z powrotem bez żadnej utraty jakości.',
    'quality.fallback.q': 'Czy stracę jakość, konwertując {{fn}} na {{tn}}?',
    'quality.fallback.a': 'W przypadku zwykłych plików wynik jest wizualnie i funkcjonalnie równoważny oryginałowi. Tam, gdzie oba formaty obsługują różne możliwości, konwersja zachowuje wszystko, co {{tn}} potrafi przedstawić. Ustawienia zaawansowane pozwalają podnieść jakość, jeśli domyślny kompromis ci nie odpowiada.',

    'relation.uncompressed.q': 'Dlaczego plik {{tn}} jest o tyle większy niż {{fn}}?',
    'relation.uncompressed.a': 'Bo {{tn}} jest nieskompresowany. {{fn}} zmniejsza dźwięk, odrzucając dane i wydajnie kodując resztę; {{tn}} zapisuje każdą próbkę w pełnym rozmiarze, co daje mniej więcej 10 MB na minutę stereo w jakości CD. Dziesięciokrotny wzrost jest normalny i spodziewany — to cena pliku, który oprogramowanie montażowe potrafi przetwarzać, nie dekodując wcześniej niczego. Jeśli chcesz dźwięku bezstratnego przy mniej więcej połowie rozmiaru, przekonwertuj zamiast tego na FLAC.',
    'relation.extractAudio.q': 'Czy zostaje przy tym wideo, czy tylko dźwięk?',
    'relation.extractAudio.a': 'Tylko dźwięk. Ścieżka dźwiękowa zostaje wyciągnięta z pliku {{fn}} i zapisana jako {{tn}}; ścieżka wideo jest odrzucana, dlatego wynik zajmuje ułamek pierwotnego rozmiaru. Samego dźwięku nie nagrywa się od nowa, więc zachowuje jakość, jaką miał wewnątrz {{fn}} — z filmu o niskiej przepływności nie da się uzyskać dźwięku o wysokiej.',
    'relation.videoContainer.q': 'Czy mój {{tn}} odtworzy się na telefonach, telewizorach i w mediach społecznościowych?',
    'relation.videoContainer.a.mp4': 'Dokładnie po to jest ta konwersja. MP4 z wideo H.264 to najbliższa rzecz uniwersalnemu formatowi wideo: iPhone’y, telefony z Androidem, telewizory smart, każda przeglądarka, Instagram, YouTube, TikTok i każdy popularny program montażowy przyjmują go bez dodatkowych kodeków. {{fn}} był formatem, który sprawiał kłopoty; MP4 jest tym, który ich nie sprawia.',
    'relation.videoContainer.a.other': '{{tn}} jest bardziej wyspecjalizowany niż MP4. {{note}} Jeśli twoim celem jest po prostu „odtworzy się wszędzie”, MP4 to bezpieczniejszy wybór — wybierz {{tn}}, gdy konkretny program albo sprzęt o niego poprosił.',
    'relation.alphaLost.q': 'Co dzieje się z przezroczystością przy konwersji {{fn}} na {{tn}}?',
    'relation.alphaLost.a': '{{tn}} nie ma kanału alfa, więc obszarów przezroczystych nie da się przenieść — podczas konwersji zostają wypełnione jednolitym tłem (domyślnie białym). Jeśli przezroczyste tło pełni w twoim projekcie realną rolę, przekonwertuj zamiast tego na PNG lub WebP, bo oba je zachowują. Jeśli obraz jest zdjęciem bez żadnej przezroczystości, nie robi to najmniejszej różnicy.',
    'relation.alphaGained.q': 'Czy konwersja {{fn}} na {{tn}} sprawia, że tło staje się przezroczyste?',
    'relation.alphaGained.a': 'Nie — i wiele osób się na tym łapie. {{tn}} obsługuje przezroczystość, ale plik {{fn}} nie ma żadnej informacji o przezroczystości do przeniesienia, więc tło zostaje dokładnie takie, jakie było. Konwersja daje ci plik zdolny pomieścić przezroczystość, gdy już wytniesz tło w edytorze obrazu, a do tego bezstratne piksele, które nie tracą jakości podczas pracy.',
    'relation.reflow.q': 'Czy {{tn}} zadziała na moim czytniku?',
    'relation.reflow.a.epub': 'EPUB czytają Apple Books, Kobo, Google Play Books, Calibre i praktycznie każdy czytnik poza Kindle’em, który chce MOBI albo AZW3 (Kindle przyjmuje dziś EPUB także pocztą). Ponieważ tekst przelewa się na nowo, możesz zmienić rozmiar czcionki na urządzeniu, nie kończąc na przewijaniu w bok — a to cały powód, by w ogóle konwertować {{fn}}.',
    'relation.reflow.a.kindle': '{{tn}} czytają urządzenia i aplikacje Kindle, dla których go zaprojektowano. Ponieważ tekst przelewa się na nowo, możesz zmienić rozmiar czcionki na urządzeniu, nie kończąc na przewijaniu w bok — a to cały powód, by w ogóle konwertować {{fn}}.',

    'compatibility.q': 'Czym otworzę potem plik {{tn}}?',
    'compatibility.a': '{{note}} Do samej konwersji nie trzeba niczego instalować — działa na naszych serwerach, a gotowy plik {{tn}} wraca do twojej przeglądarki, gotowy do otwarcia, edycji albo przesłania dalej. Twój pierwotny plik {{fn}} nigdy nie jest zmieniany; zawsze zwracamy wyłącznie nowy plik.',
    'compatibility.noteFallback': '{{tn}} jest szeroko obsługiwany.',

    'shapeFaq.pdf-merge.q1': 'Czy łączenie obniży jakość moich plików PDF?',
    'shapeFaq.pdf-merge.a1': 'Nie. Strony trafiają do nowego dokumentu dokładnie takie, jakie są, zamiast być renderowane od nowa, więc tekst pozostaje zaznaczalny, a obrazy zachowują pierwotną rozdzielczość. Połączony plik waży mniej więcej tyle, co oryginały razem — przepuść go potem przez Kompresję PDF, jeśli to ma znaczenie.',
    'shapeFaq.pdf-merge.q2': 'Ile plików PDF mogę połączyć naraz i czy kolejność ma znaczenie?',
    'shapeFaq.pdf-merge.a2': 'Możesz dodać naraz tyle plików, ile potrzebujesz, a kolejność ma ogromne znaczenie: gotowy dokument idzie w kolejności widocznej na liście, którą przed połączeniem możesz przestawić przeciąganiem. Najpierw ustaw kolejność, potem łącz — to szybsze niż poprawianie później.',
    'shapeFaq.pdf-split.q1': 'Jak wybrać strony do wyodrębnienia?',
    'shapeFaq.pdf-split.a1': 'Wpisz je w polu zakresów stron, używając przecinków i myślników: „1-3, 5, 7-10” daje strony od pierwszej do trzeciej, stronę piątą oraz strony od siódmej do dziesiątej w jednym dokumencie wynikowym. Numery odnoszą się do stron samego PDF-a, liczonych od jednego, co nie zawsze pokrywa się z numerem wydrukowanym na stronie.',
    'shapeFaq.pdf-split.q2': 'Czy dzielenie zmienia oryginalny plik PDF?',
    'shapeFaq.pdf-split.a2': 'Nie. Przesłany przez ciebie plik nigdy nie jest zmieniany — wyodrębnione strony trafiają do nowego dokumentu, a oryginał pozostaje nietknięty, po czym w ciągu 24 godzin znika z naszych serwerów wraz z wynikiem.',
    'shapeFaq.pdf-compress.q1': 'O ile zmniejszy się mój plik PDF?',
    'shapeFaq.pdf-compress.a1': 'To zależy wyłącznie od tego, co jest w środku. Pliki PDF zdominowane przez skany albo zdjęcia często kurczą się o 50–90%, bo tam kryje się niemal cały rozmiar. PDF z samym tekstem jest już zwarty i może się prawie nie zmienić. Tekst i grafika wektorowa w obu przypadkach pozostają ostre — oszczędność bierze się z ponownego kodowania obrazów i usuwania zbędnych danych osadzonych.',
    'shapeFaq.pdf-compress.q2': 'Czy tekst nadal będzie zaznaczalny i przeszukiwalny?',
    'shapeFaq.pdf-compress.a2': 'Tak. Kompresja działa na obrazach osadzonych i na zbędnych danych wewnętrznych; warstwa tekstowa, czcionki, odnośniki i zakładki pozostają nietknięte, więc w skompresowanym pliku nadal wyszukasz, zaznaczysz i skopiujesz tekst dokładnie tak jak wcześniej.',
    'shapeFaq.pdf-compress-ai.q1': 'Czym to się różni od zwykłej kompresji PDF?',
    'shapeFaq.pdf-compress-ai.a1': 'Zwykła kompresja stosuje jedno ustawienie do całego pliku. To narzędzie najpierw sprawdza, co faktycznie zawiera każda strona, dzięki czemu obrazy fotograficzne, płaskie diagramy i strony z samym tekstem są traktowane każde w sposób oszczędzający najwięcej miejsca bez widocznego pogorszenia. W dokumentach mieszanych oznacza to zwykle mniejszy plik przy tej samej postrzeganej jakości.',
    'shapeFaq.pdf-compress-ai.q2': 'Czy tekst nadal będzie zaznaczalny i przeszukiwalny?',
    'shapeFaq.pdf-compress-ai.a2': 'Tak. Warstwa tekstowa, czcionki, odnośniki i zakładki zostają zachowane — kodowane ponownie są wyłącznie obrazy osadzone i zbędne dane wewnętrzne, więc skompresowany PDF pozostaje w pełni przeszukiwalny i możliwy do skopiowania.',
    'shapeFaq.pdf-rotate.q1': 'Czy obracanie PDF-a powoduje utratę jakości?',
    'shapeFaq.pdf-rotate.a1': 'Absolutnie nie. Obrót zmienia geometrię stron zapisaną w pliku, zamiast cokolwiek renderować od nowa, więc tekst pozostaje wektorowo ostry, obrazy są nietknięte, a rozmiar pliku ledwie drgnie. Możesz obrócić go później ponownie bez żadnych kumulujących się szkód.',
    'shapeFaq.pdf-rotate.q2': 'Czy mogę obrócić tylko część stron?',
    'shapeFaq.pdf-rotate.a2': 'Wybrany obrót — 90°, 180° albo 270° — stosuje się do dokumentu. Jeśli różne strony są przekręcone w różne strony, typowe podejście to podzielić PDF, obrócić każdą część o potrzebny kąt i połączyć wyniki narzędziem Połącz PDF.',
    'shapeFaq.pdf-protect.q1': 'Co się stanie, jeśli zapomnę hasła?',
    'shapeFaq.pdf-protect.a1': 'Pliku nie da się otworzyć. Szyfrowanie stosuje się do samego PDF-a, więc nie ma odnośnika resetującego ani tylnej furtki — ani dla ciebie, ani dla nas. Zapisz hasło w bezpiecznym miejscu, zanim prześlesz dokument dalej, i wyślij je innym kanałem niż sam plik.',
    'shapeFaq.pdf-protect.q2': 'Jak mocna jest ta ochrona?',
    'shapeFaq.pdf-protect.a2': 'PDF szyfrowany jest branżowym standardem wbudowanym w format, więc żaden zgodny czytnik nie odczyta jego treści bez hasła. Praktycznym słabym punktem nigdy nie jest algorytm, lecz samo hasło — krótkie albo oczywiste szybko się odgaduje, więc do rzeczy naprawdę poufnych używaj długiego.',
    'shapeFaq.pdf-unlock.q1': 'Czy to usunie hasło, którego nie znam?',
    'shapeFaq.pdf-unlock.a1': 'Nie. Musisz podać bieżące hasło; narzędzie odszyfrowuje nim plik, zamiast łamać szyfrowanie. Jest przeznaczone do dokumentów, które są twoje albo do których masz uprawnienia — na przykład wyciągu z twojego banku — gdzie ograniczenie zwyczajnie przeszkadza.',
    'shapeFaq.pdf-unlock.q2': 'Co mogę potem zrobić z plikiem?',
    'shapeFaq.pdf-unlock.a2': 'Wszystko, co blokowała ochrona: otworzyć bez pytania o hasło, wydrukować, skopiować z niego tekst i edytować w innym oprogramowaniu. Sama treść stron pozostaje niezmieniona — usuwana jest wyłącznie warstwa szyfrowania i jej ograniczenia użycia.',
    'shapeFaq.metadata.q1': 'Czy to w jakikolwiek sposób zmienia mój plik?',
    'shapeFaq.metadata.a1': 'Nie. Plik jest odczytywany, a nie konwertowany — nic nie zostaje zapisane z powrotem i nie powstaje nic nowego poza informacjami na ekranie. To najbezpieczniejsze narzędzie tutaj, by wycelować nim w plik, co do którego masz wątpliwości.',
    'shapeFaq.metadata.q2': 'Jakiego rodzaju informacje zobaczę?',
    'shapeFaq.metadata.a2': 'To zależy od pliku. Obrazy pokazują wymiary, głębię kolorów i dane EXIF, takie jak model aparatu, obiektyw, ekspozycję i — jeśli aparat je zapisał — współrzędne GPS. Dźwięk pokazuje czas trwania, przepływność, częstotliwość próbkowania i liczbę kanałów. Wideo dokłada kodek, rozdzielczość i liczbę klatek. Dokumenty pokazują liczbę stron, autora, producenta i datę utworzenia.',
    'shapeFaq.ocr.q1': 'Jak dokładne jest rozpoznawanie tekstu?',
    'shapeFaq.ocr.a1': 'Czysty, prosty skan drukowanego tekstu w rozsądnej rozdzielczości rozpoznawany jest bardzo dokładnie. Dokładność spada przy stronach przekrzywionych lub nieostrych, zdjęciach o niskim kontraście, nietypowych krojach pisma i piśmie odręcznym. Wybór właściwego języka ma znaczenie, bo rozpoznawanie używa go do rozstrzygania niejednoznacznych znaków.',
    'shapeFaq.ocr.q2': 'Czym różni się przeszukiwalny PDF od wyniku w zwykłym tekście?',
    'shapeFaq.ocr.a2': 'Przeszukiwalny PDF zachowuje pierwotny obraz strony dokładnie takim, jaki jest, i dokłada pod spodem niewidoczną warstwę tekstową, więc dokument wygląda tak samo, ale da się go teraz przeszukiwać i z niego kopiować — to wybór do archiwizacji. Zwykły tekst odrzuca układ i daje same słowa, a to wybór do edycji, skryptów albo podania innemu programowi.',
    'shapeFaq.tts.q1': 'Jak naturalnie brzmią głosy?',
    'shapeFaq.tts.a1': 'To głosy neuronowe, a nie dawna synteza sklejana z fragmentów, więc niosą intonację na poziomie zdania i naturalne pauzy zamiast czytać słowo po słowie. Do wyboru jest sześć głosów, od neutralnego przez ciepły po autorytatywny, a tempo mowy da się ustawić. Interpunkcja znaczy więcej, niż się wydaje: przecinki i kropki kształtują frazowanie, więc dobrze zinterpunktowany tekst czyta się zauważalnie lepiej.',
    'shapeFaq.tts.q2': 'Ile tekstu mogę przekonwertować naraz?',
    'shapeFaq.tts.a2': 'Do 4096 znaków na jedną konwersję — z grubsza 600 do 700 słów, czyli około pięciu minut mowy. Przy dłuższych tekstach potnij je w naturalnym miejscu, na przykład na tytule rozdziału albo sekcji, i konwertuj każdą część osobno; ustawienia głosu i tempa pozostają między przebiegami takie same, więc fragmenty łączą się czysto.',
    'shapeFaq.stt.q1': 'Jak dokładna jest transkrypcja?',
    'shapeFaq.stt.a1': 'Wyraźna mowa w miarę cichym otoczeniu jest przepisywana bardzo dokładnie, także przy szerokim wachlarzu akcentów. Dokładność spada przy silnym szumie tła, gdy kilka osób mówi jednocześnie, albo przy bardzo specjalistycznym żargonie i nazwach własnych. Ustawienie języka mówionego zamiast pozostawienia wykrywania automatycznego pomaga zauważalnie.',
    'shapeFaq.stt.q2': 'Czy mogę nagrywać prosto z mikrofonu?',
    'shapeFaq.stt.a2': 'Tak — rejestrator na tej stronie nagrywa dźwięk bezpośrednio w przeglądarce, co często jest szybsze niż szukanie najpierw aplikacji do nagrywania. Przeglądarka poprosi za pierwszym razem o zgodę na dostęp do mikrofonu. Możesz też przesłać istniejący plik, a zapis pojawia się na stronie, żebyś przeczytał go przed pobraniem jako TXT lub DOCX.',
    'shapeFaq.subtitle.q1': 'Jak dokładne są generowane napisy?',
    'shapeFaq.subtitle.a1': 'Wyraźna mowa przepisywana jest bardzo dokładnie, także przy akcentach. Muzyka w tle, mówienie jeden przez drugiego i specjalistyczna terminologia to miejsca, gdzie wkradają się błędy, a ustawienie języka mówionego zamiast wykrywania automatycznego pomaga. Wynik to plik napisów w zwykłym tekście, więc poprawienie pojedynczego słowa zajmuje sekundy w dowolnym edytorze.',
    'shapeFaq.subtitle.q2': 'Wybrać SRT czy VTT?',
    'shapeFaq.subtitle.a2': 'SRT to bezpieczniejszy wybór domyślny: YouTube, Vimeo, Premiere, Final Cut, VLC i praktycznie każdy odtwarzacz go akceptują. Wybierz VTT, jeśli napisy trafią do odtwarzacza wideo HTML5 na stronie, bo WebVTT to format, jakiego oczekuje natywna ścieżka napisów przeglądarki, i obsługuje style oraz pozycjonowanie, których SRT nie potrafi wyrazić.',
    'shapeFaq.soon.q1': 'Kiedy to będzie dostępne?',
    'shapeFaq.soon.a1': 'Jest w aktywnej budowie. Narzędzie pojawi się tutaj i zacznie przyjmować pliki, gdy tylko będzie gotowe — po twojej stronie nie trzeba niczego instalować ani włączać.',
    'shapeFaq.soon.q2': 'Z czego mogę korzystać w międzyczasie?',
    'shapeFaq.soon.a2': 'Reszta konwertera jest w pełni dostępna: dokumenty, obrazy, dźwięk, wideo, archiwa, GIF-y i zestaw narzędzi PDF działają już dziś, podobnie jak funkcje inteligentne do OCR, transkrypcji i napisów.',
    'shapeFaq.compress.q1': 'Czy skompresowany plik nadal będzie plikiem {{fn}}?',
    'shapeFaq.compress.a1': 'Tak — format się nie zmienia, tylko rozmiar. To, co pobierasz, jest zwykłym plikiem {{fn}}, otwierającym się wszędzie tam, gdzie otwierał się oryginał.{{alpha}} To, ile zaoszczędzisz, zależy od materiału źródłowego: {{source}}.',
    'shapeFaq.compress.alpha': ' Przezroczystość i animacja zostają zachowane.',
    'shapeFaq.compress.source.png': 'zrzuty ekranu i płaska grafika interfejsu kompresują się znakomicie, a zdjęcia zapisane jako PNG dają mniej',
    'shapeFaq.compress.source.gif': 'długie animacje i niespokojny materiał kompresują się najmocniej, bo jest więcej nadmiarowości do usunięcia',
    'shapeFaq.compress.source.other': 'zdjęcia kompresują się dobrze, a obrazy już mocno skompresowane mają mniej do oddania',
    'shapeFaq.compress.q2': 'O ile zmniejszy się plik?',
    'shapeFaq.compress.a2': 'Zwykle gdzieś między jedną trzecią a jedną dziesiątą oryginału, w zależności wyłącznie od tego, co plik zawiera i jak został pierwotnie zapisany. Po zakończeniu konwersji strona pokazuje rozmiary przed i po obok siebie, więc widzisz rzeczywistą oszczędność, zamiast jej zgadywać.',
    'shapeFaq.hub.q1': 'Między jakimi formatami mogę konwertować?',
    'shapeFaq.hub.a1': 'Wejście: {{inputs}}. Wyjście: {{outputs}}. Każde wejście może trafić do każdego wyjścia, więc nie musisz szukać osobnej strony dla każdej kombinacji — wybierz plik, wybierz format docelowy, konwertuj.',
    'shapeFaq.hub.q2': 'Czy stracę jakość?',
    'shapeFaq.hub.a2': 'To zależy od pary. Przejście do formatu bezstratnego zachowuje wszystko, ale daje większy plik; przejście do formatu skompresowanego z założenia odrzuca część danych w zamian za rozmiar, a ustawienia zaawansowane pozwalają zdecydować, gdzie na tym kompromisie chcesz się znaleźć. Konwersja między dwoma formatami skompresowanymi za każdym razem gubi trochę szczegółów, więc warto zachować oryginał jako kopię wzorcową.',
    'shapeFaq.hub-extract.q1': 'Czy zostaje przy tym także wideo?',
    'shapeFaq.hub-extract.a1': 'Nie — tylko dźwięk. Ścieżka dźwiękowa zostaje wyjęta z filmu i zapisana osobno, dlatego wynik zajmuje ułamek pierwotnego rozmiaru pliku. Dźwięku nie nagrywa się od nowa, więc zachowuje jakość, jaką miał już w filmie; z klipu o niskiej przepływności nie da się uzyskać dźwięku o wysokiej.',
    'shapeFaq.hub-extract.q2': 'Który format wyjściowy wybrać?',
    'shapeFaq.hub-extract.a2': 'MP3 dla maksymalnej zgodności — odtworzy się na każdym telefonie, w każdym radiu samochodowym i odtwarzaczu. AAC albo M4A, jeśli celem jest urządzenie Apple albo nowoczesna aplikacja, bo brzmią przy tej samej przepływności nieco lepiej. WAV albo FLAC tylko wtedy, gdy zamierzasz dźwięk edytować, bo oba są bezstratne i odpowiednio duże.',
    'shapeFaq.hub-gif.q1': 'Dlaczego GIF wygląda gorzej niż oryginał?',
    'shapeFaq.hub-gif.a1': 'Bo GIF dopuszcza tylko 256 kolorów na klatkę, podczas gdy wideo i zdjęcia zawierają ich miliony. Koder wybiera paletę i przybliża resztę, co objawia się pasmami w gradientach i na niebie. GIF nie niesie też żadnego dźwięku. Oba ograniczenia wynikają z formatu, a nie z konwersji.',
    'shapeFaq.hub-gif.q2': 'Dlaczego mój plik GIF jest tak duży?',
    'shapeFaq.hub-gif.a2': 'GIF kompresuje znacznie mniej wydajnie niż nowoczesne kodeki wideo, więc rozmiar szybko rośnie wraz z długością, rozdzielczością i liczbą klatek. Kilka sekund to punkt optymalny. Jeśli wynik jest zbyt ciężki, skróć klip, a jeśli rozmiar liczy się bardziej niż samoczynne odtwarzanie w treści, MP4 pokaże tę samą animację przy ułamku rozmiaru.',
  },
};
