// Portuguese content pack. Mirrors packs/en.js key for key — see the header there.
export default {
  lang: 'pt',
  formats: {
    pdf: { about: 'O PDF é um formato de maquetação fixa: guarda a posição exacta de cada caractere, cada linha e cada imagem, e é por isso que um PDF aparece idêntico em qualquer ecrã ou impressora mas é incómodo de editar.', note: 'O PDF fixa a paginação, os tipos de letra e a maquetação, por isso o destinatário vê exactamente o que enviou.' },
    docx: { about: 'O DOCX é o formato moderno do Microsoft Word, em que o texto vive em parágrafos e estilos editáveis em vez de estar preso a coordenadas de página fixas.', note: 'O DOCX devolve-lhe parágrafos realmente editáveis, registo de alterações e comentários no Word, Google Docs ou LibreOffice.' },
    xlsx: { about: 'O XLSX é o formato de folha de cálculo do Excel, em que cada valor ocupa uma célula endereçável que se pode ordenar, filtrar e usar numa fórmula.', note: 'Assim que os dados estão em XLSX pode somá-los, ordená-los, cruzá-los em tabelas dinâmicas e representá-los em gráficos em vez de os voltar a escrever.' },
    pptx: { about: 'O PPTX guarda uma apresentação como diapositivos separados, com caixas de texto editáveis, formas, notas do orador e transições.', note: 'O PPTX devolve-lhe diapositivos que pode mesmo voltar a editar, reordenar e apresentar de novo.' },
    txt: { about: 'Um ficheiro TXT não é mais do que caracteres — sem tipos de letra, sem imagens, sem estrutura de página — o que o torna minúsculo, legível em qualquer lado e trivial de pesquisar.', note: 'O TXT retira tudo excepto as palavras, que é exactamente o que scripts, índices de pesquisa e editores de texto querem.' },
    html: { about: 'O HTML é a linguagem de marcação da web: texto envolto em etiquetas que um navegador transforma em títulos, parágrafos, ligações e imagens.', note: 'O HTML abre em qualquer navegador e cola-se directamente num site ou num CMS.' },
    rtf: { about: 'O RTF é um formato de documento aberto, baseado em texto simples, que transporta formatação básica — negrito, itálico, tipos de letra, tabelas — sem o prender a um único processador de texto.', note: 'O RTF abre no Word, no Pages, no LibreOffice, no WordPad e em praticamente todos os processadores de texto alguma vez escritos.' },
    odt: { about: 'O ODT é o formato de texto OpenDocument usado pelo LibreOffice e pelo OpenOffice, e é uma norma ISO em vez de um formato proprietário.', note: 'O ODT é o formato nativo e totalmente editável do LibreOffice e do OpenOffice.' },
    epub: { about: 'O EPUB é um formato de livro digital de texto fluido: não tem tamanho de página fixo, por isso o texto reajusta-se ao ecrã e ao tamanho de letra que o leitor estiver a usar.', note: 'O EPUB permite ao leitor mudar o tamanho da letra e refluir o texto, que é o que torna os documentos longos confortáveis no telemóvel ou num leitor de livros digitais.' },
    jpg: { about: 'O JPG usa compressão com perdas pensada para fotografia: deita fora o detalhe que o olho menos nota, o que aligeira as fotos mas acrescenta artefactos suaves e quadriculados à volta de contornos nítidos e de texto.', note: 'O JPG produz ficheiros pequenos que abrem literalmente em todo o lado, ao preço de algum detalhe descartado para sempre e de não haver transparência.' },
    jfif: { about: 'O JFIF é uma imagem JPEG guardada com outra extensão; os píxeis lá dentro são dados JPEG normais, mas o Windows recusa-se muitas vezes a entregar o ficheiro à aplicação que quer.', note: 'O JFIF é na verdade apenas JPEG com outro nome.' },
    png: { about: 'O PNG é sem perdas: guarda cada píxel exactamente, suporta um canal alfa completo para transparência e nunca se degrada quando o volta a gravar, e é por isso que é o formato de eleição para capturas de ecrã, logótipos e gráficos de interface.', note: 'O PNG conserva cada píxel tal como está e suporta transparência verdadeira, por isso sobrevive a edições repetidas sem se degradar.' },
    webp: { about: 'O WebP é o formato de imagem web moderno da Google; comprime bastante mais do que o JPG ou o PNG com qualidade semelhante e suporta transparência e animação, mas muitos programas de secretária e de impressão ainda não conseguem abri-lo.', note: 'O WebP produz os ficheiros mais leves dos formatos web comuns e suporta transparência.' },
    bmp: { about: 'O BMP guarda dados de píxel em bruto, praticamente sem compressão, o que o torna perfeitamente fiel e enormemente desperdiçador — uma foto pode facilmente ocupar dez vezes mais do que a mesma imagem em PNG.', note: 'O BMP é bruto e sem compressão, que é o que os programas antigos do Windows e alguns digitalizadores ainda esperam.' },
    tiff: { about: 'O TIFF é o formato de arquivo e de pré-impressão: sem perdas, com grande profundidade de cor, capaz de conter várias páginas ou camadas — e consequentemente volumoso.', note: 'O TIFF é o formato que as gráficas e os arquivos pedem, porque nada é deitado fora.' },
    gif: { about: 'O GIF está limitado a uma paleta de 256 cores por fotograma, e é por isso que as fotografias aparecem com bandas, mas anima-se e reproduz-se sozinho dentro de quase todo o lado na internet.', note: 'O GIF anima-se e reproduz-se sozinho dentro de aplicações de mensagens, gestores de incidências e fóruns, mas está limitado a 256 cores por fotograma.' },
    ico: { about: 'O ICO é um contentor de ícones do Windows que guarda a mesma arte em vários tamanhos ao mesmo tempo, para que o sistema possa escolher 16×16 para um separador e 256×256 para um atalho do ambiente de trabalho.', note: 'O ICO junta várias resoluções num só ficheiro, que é exactamente o que os favicons e os ícones de aplicações do Windows precisam.' },
    heic: { about: 'O HEIC é o formato em que os iPhone guardam fotos por predefinição; oferece mais ou menos a mesma qualidade do JPG em cerca de metade do espaço, mas o Windows, muitos formulários web e bastante software antigo simplesmente recusam abri-lo.', note: 'O HEIC é compacto mas mal suportado fora dos dispositivos Apple.' },
    svg: { about: 'O SVG não é feito de píxeis de todo — é XML que descreve formas, traçados e texto, por isso mantém-se perfeitamente nítido em qualquer tamanho e pode ser editado ou reestilizado por código.', note: 'O SVG amplia para qualquer tamanho sem nunca ficar desfocado, porque guarda formas em vez de píxeis.' },
    mp4: { about: 'O MP4 é um contentor — normalmente vídeo H.264 com áudio AAC — e é o único formato de vídeo em que telemóveis, navegadores, televisores, programas de edição e plataformas sociais concordam todos.', note: 'O MP4 reproduz-se praticamente em qualquer telemóvel, navegador, televisor e programa de edição sem instalar nada.' },
    avi: { about: 'O AVI é um contentor da Microsoft dos anos noventa; os leitores e suites de edição mais antigos ainda o lêem, mas não tem funcionalidades modernas de transmissão e os seus ficheiros tendem a ser muito maiores do que os MP4.', note: 'O AVI é o que os leitores antigos, as ferramentas de autoria de DVD e o software de edição legado esperam.' },
    mov: { about: 'O MOV é o contentor QuickTime da Apple, o formato em que iPhone e Mac gravam e aquele que o Final Cut Pro e o iMovie tratam com mais à-vontade.', note: 'O MOV é o contentor com que as ferramentas de edição da Apple trabalham com mais fluidez.' },
    mkv: { about: 'O MKV (Matroska) é um contentor aberto capaz de albergar qualquer número de faixas de vídeo, áudio e legendas num só ficheiro — excelente para arquivar, mas rejeitado pela maioria dos telemóveis, televisores e navegadores.', note: 'O MKV pode transportar várias faixas de áudio e de legendas num único ficheiro.' },
    webm: { about: 'O WebM é o contentor livre de royalties criado para o vídeo HTML5, normalmente com VP9 ou AV1; os navegadores adoram-no, mas os programas de edição de secretária e o software da Apple muitas vezes nem lhe tocam.', note: 'O WebM é leve e transmite de forma nativa nos navegadores.' },
    wmv: { about: 'O WMV é o formato de vídeo Windows Media da Microsoft, na prática exclusivo do Windows e largamente abandonado fora de gravações empresariais antigas e capturas de ecrã.', note: 'O WMV é um formato Windows Media com muito pouco suporte noutros sítios.' },
    flv: { about: 'O FLV era o contentor por trás do vídeo Flash e, desde que o Flash foi retirado de todos os navegadores, é na prática um formato de arquivo impossível de reproduzir.', note: 'O FLV é um contentor morto da era Flash.' },
    mp3: { about: 'O MP3 é com perdas: o codificador apaga definitivamente as partes do sinal que prevê que não vai ouvir, o que reduz uma faixa a cerca de um décimo do seu tamanho e explica que se reproduza absolutamente em tudo.', note: 'O MP3 é cerca de dez vezes mais pequeno do que áudio sem compressão e reproduz-se em qualquer telemóvel, auto-rádio e leitor dos últimos vinte anos.' },
    wav: { about: 'O WAV guarda o áudio sem compressão, amostra a amostra, exactamente como foi gravado — daí ser usado nos estúdios e daí um minuto de estéreo com qualidade de CD ocupar cerca de 10 MB.', note: 'O WAV é sem compressão e sem perdas, por isso os programas de edição e de masterização podem processá-lo sem descodificar nada primeiro.' },
    flac: { about: 'O FLAC comprime o áudio sem perdas: ocupa aproximadamente metade de um WAV e mesmo assim descodifica numa cópia idêntica bit a bit da gravação original.', note: 'O FLAC é idêntico bit a bit mas ocupa cerca de metade de um WAV.' },
    aac: { about: 'O AAC é o codec com perdas por trás do Apple Music, do YouTube e da maioria dos serviços de streaming; à mesma taxa de bits soa em geral melhor do que o MP3.', note: 'O AAC soa melhor do que o MP3 à mesma taxa de bits e é o padrão nas plataformas da Apple e de streaming.' },
    ogg: { about: 'O OGG Vorbis é um codec com perdas livre de patentes, preferido por videojogos, software livre e pela Wikipédia, com qualidade comparável à do MP3 em menos espaço.', note: 'O OGG está livre de restrições de patentes, e é por isso que os motores de jogo e os projectos de código aberto o preferem.' },
    m4a: { about: 'O M4A é um contentor MP4 que transporta apenas áudio, normalmente AAC — o formato que o iTunes, o Apple Music e os memorandos de voz do iPhone produzem.', note: 'O M4A é o ficheiro de áudio padrão do ecossistema Apple.' },
    wma: { about: 'O WMA é o codec de áudio com perdas da Microsoft da era do Windows Media Player, raramente suportado fora do Windows e na prática descontinuado.', note: 'O WMA é um codec de áudio antigo e exclusivo do Windows.' },
    zip: { about: 'O ZIP é o formato de arquivo integrado no Windows, no macOS e em todos os telemóveis — basta um duplo clique, sem instalar mais nada.', note: 'O ZIP abre com um duplo clique no Windows, macOS, Linux, iOS e Android sem instalar nada.' },
    rar: { about: 'O RAR é um formato de arquivo proprietário com boa compressão e registos de recuperação, mas precisa do WinRAR ou de uma ferramenta compatível para abrir.', note: 'O RAR precisa de software de terceiros para ser extraído.' },
    '7z': { about: 'O 7Z usa compressão LZMA, que produz regularmente arquivos bastante mais pequenos do que o ZIP — ao preço de exigir o 7-Zip ou uma ferramenta compatível para abrir.', note: 'O 7Z comprime bastante mais do que o ZIP, o que conta com pastas grandes e armazenamento na nuvem pago.' },
    tar: { about: 'Um ficheiro TAR junta muitos ficheiros num só sem os comprimir; vem do mundo Unix e preserva permissões e estrutura de pastas.', note: 'O TAR preserva as permissões Unix e a estrutura de pastas.' },
    gz: { about: 'O GZ (gzip) comprime um único fluxo de dados e é o que os servidores Linux e as ferramentas de linha de comandos produzem; no Windows é incómodo de abrir sem software adicional.', note: 'O GZ é o formato de compressão padrão em Linux e nos servidores web.' },
    srt: { about: 'O SRT é o formato de legendas em texto simples que todos os programas de edição e todos os leitores entendem: entradas numeradas, um intervalo de código de tempo e a linha de diálogo.', note: 'O SRT é aceite pelo YouTube, Vimeo, Premiere, Final Cut e por todos os leitores comuns.' },
  },
  reasons: {
    'pdf-to-word': 'O motivo habitual é uma alteração impossível de fazer no próprio PDF — uma cláusula de contrato, uma linha do currículo ou um parágrafo de um relatório que tem de mudar sem voltar a escrever o documento inteiro.',
    'word-to-pdf': 'Converte-se Word para PDF mesmo no fim da vida do documento: ao enviar um currículo, um orçamento ou um formulário assinado a alguém cujos tipos de letra, versão do Word e margens não controla.',
    'pdf-to-excel': 'O caso típico é um extracto bancário, uma factura ou um relatório que só existe em PDF mas cujos números precisa de somar, ordenar ou representar em gráfico.',
    'excel-to-pdf': 'É o que se faz antes de enviar um orçamento ou uma tabela de preços a alguém que deve lê-la mas não alterá-la, e antes de imprimir: um PDF fixa as quebras de página que o Excel recalcularia em cada computador.',
    'pptx-to-pdf': 'A maioria converte uma apresentação para PDF antes de a enviar ou distribuir, para que os diapositivos não se desalinhem e ninguém precise de ter o PowerPoint instalado para os abrir.',
    'pdf-to-pptx': 'É o que precisa quando a única cópia sobrevivente de uma apresentação é o PDF que circulou depois da reunião e tem de actualizar ou reaproveitar os diapositivos.',
    'pdf-to-txt': 'Motivos comuns: alimentar um script, um índice de pesquisa ou uma ferramenta de IA, ou reduzir um relatório longo a algo que se possa pesquisar, comparar e colar em qualquer lado.',
    'pdf-to-html': 'É a forma mais rápida de publicar num site um relatório, um manual ou um folheto já existentes sem reconstruir a página à mão.',
    'html-to-pdf': 'Faz-se para arquivar uma página web exactamente como está hoje, ou para transformar um modelo HTML de factura ou relatório em algo imprimível e enviável.',
    'rtf-to-pdf': 'O RTF sai normalmente de software antigo ou de modelos de documentos jurídicos; passá-lo a PDF dá-lhe um ficheiro que abre igual em todo o lado e que não pode ser alterado por acidente.',
    'pdf-to-rtf': 'É a opção a escolher quando precisa de uma cópia editável de um PDF mas não pode assumir que o destinatário tem Word: praticamente qualquer processador de texto alguma vez escrito abre RTF.',
    'odt-to-pdf': 'O caso típico: escreveu o documento no LibreOffice ou no OpenOffice e quem o recebe usa Microsoft Office, ou nada de todo.',
    'pdf-to-epub': 'Ler um PDF no telemóvel significa ampliar e deslizar na horizontal sem parar; esta conversão serve sobretudo para tornar um documento longo verdadeiramente legível num ecrã pequeno ou num leitor de livros digitais.',
    'epub-to-pdf': 'Converte-se EPUB para PDF quando se quer imprimir um livro, anotá-lo com números de página fixos ou enviá-lo a alguém sem qualquer aplicação de leitura instalada.',
    'document-converter': 'É a ferramenta a abrir quando lhe entregam um documento no formato que o remetente por acaso tinha e precisa dele naquele que o seu próprio software abre de facto.',
    'ebook-converter': 'As lojas e os aparelhos de livros digitais preferem cada um o seu formato, por isso é o que se usa para mover um livro que lhe pertence de um leitor ou aplicação para outro.',
    'jpg-to-png': 'O motivo habitual é edição: precisa de recortar um fundo, colocar um logótipo sobre outra imagem ou impedir que uma captura de ecrã fique mais desfocada de cada vez que é gravada.',
    'png-to-jpg': 'É a solução para uma captura de ecrã ou uma exportação demasiado pesada para anexar a um e-mail ou para passar o limite de tamanho de um formulário de carregamento.',
    'webp-to-png': 'Normalmente precisa disto depois de guardar uma imagem de um site: o WebP transfere-se sem problema, mas editores antigos, software de escritório e alguns serviços de impressão continuam a recusar-se a abri-lo.',
    'webp-to-jpg': 'A maioria faz isto para levar uma imagem de um site para algo universalmente aceite — um e-mail, um CMS antigo, um serviço de revelação fotográfica ou o software pré-histórico de um colega.',
    'heic-to-jpg': 'Este é o problema clássico do iPhone: as fotos ficam impecáveis no telemóvel mas chegam a um PC com Windows ou a um formulário web como ficheiros .heic impossíveis de abrir.',
    'heic-to-png': 'Use isto quando tenciona editar a foto e não apenas partilhá-la — o PNG entrega ao seu editor píxeis sem perdas em vez de uma cópia acabada de recomprimir.',
    'svg-to-png': 'O motivo habitual é uma ferramenta que recusa vectores: uma apresentação, um anúncio num marketplace, uma assinatura de e-mail ou uma cadeia de produção de ícones que só aceita píxeis.',
    'svg-to-jpg': 'É para sítios que querem um simples ficheiro de tipo fotográfico — um documento, uma publicação nas redes ou um formulário de carregamento que rejeita tanto a marcação SVG como a transparência.',
    'bmp-to-png': 'Os ficheiros BMP saem de software antigo do Windows e de digitalizadores com tamanhos absurdos; o PNG guarda exactamente os mesmos píxeis numa fracção do espaço.',
    'tiff-to-jpg': 'Digitalizadores e câmaras profissionais produzem TIFF demasiado pesados para e-mail, por isso o JPG é o que se envia depois de a cópia de arquivo estar guardada em segurança.',
    'gif-to-png': 'É o que se faz com um GIF estático — um logótipo, um ícone ou um fotograma exportado — que mostra bandas de cor ou um contorno desfiado por causa do limite de 256 cores.',
    'png-to-ico': 'Quase toda a gente que converte PNG para ICO está a criar um favicon ou um ícone de aplicação do Windows, e ambos esperam o contentor ICO em vez de um simples ficheiro de imagem.',
    'jfif-to-png': 'Os ficheiros JFIF aparecem tipicamente quando uma foto é guardada a partir do Outlook ou de um navegador e o Windows depois se recusa a entregá-la à aplicação que queria mesmo usar.',
    'heic-to-pdf': 'Prático quando fotografa documentos, recibos ou um quadro branco com o iPhone e tem de os entregar como um único ficheiro em vez de uma pasta de imagens.',
    'image-compressor': 'O motivo habitual é algum limite rígido — um formulário de carregamento, um tecto para anexos de e-mail, ou uma página web que carrega devagar demais porque as suas imagens pesam muito mais do que precisam.',
    'jpeg-compressor': 'Fotógrafos e responsáveis de sites usam isto quando os JPEG em resolução total abrandam uma página ou não passam num limite de carregamento.',
    'png-compressor': 'Capturas de ecrã e gráficos de interface exportados pesam frequentemente vários megabytes sem boa razão; isto aligeira-os antes de irem para um documento, uma incidência ou uma página web.',
    'mp4-to-avi': 'O motivo é quase sempre um aparelho antigo ou um programa específico — alguns leitores antigos, ferramentas de autoria de DVD e utilitários de câmaras lêem AVI e mais nada.',
    'mp4-to-mov': 'É normalmente o primeiro passo antes de editar num Mac, já que o Final Cut Pro e o iMovie lidam com ficheiros QuickTime com mais à-vontade.',
    'mov-to-mp4': 'iPhone e Mac gravam em MOV; tudo o resto espera MP4, por isso é a conversão que se faz antes de carregar, enviar ou publicar um clipe.',
    'mkv-to-mp4': 'O MKV é excelente para armazenar, mas telemóveis, televisores, navegadores e a maioria dos programas de edição não o reproduzem — converter para MP4 é o que torna o ficheiro realmente utilizável.',
    'webm-to-mp4': 'Os ficheiros WebM guardados da web recusam-se muitas vezes a abrir no QuickTime, no iOS ou no Premiere; o MP4 é o formato que todos aceitam.',
    'avi-to-mp4': 'É o resgate padrão para material antigo de câmara de vídeo e clipes arquivados que devoram gigabytes e não se reproduzem em telemóvel nenhum.',
    'flv-to-mp4': 'O Flash desapareceu de todos os navegadores, por isso qualquer FLV que ainda tenha é na prática irreproduzível — convertê-lo para MP4 é o que mantém esse material de arquivo visível.',
    'wmv-to-mp4': 'O WMV é um resto exclusivo do Windows, por isso é o que se faz antes de enviar uma gravação antiga ou uma captura de ecrã para um Mac, um iPhone ou uma plataforma web.',
    'mp4-to-mp3': 'O que interessa é normalmente o som e não a imagem — uma aula, uma entrevista, um podcast ou um videoclipe que quer no telemóvel sem carregar com o vídeo.',
    'video-to-mp3': 'Recorre-se a isto quando o áudio é a parte que vale a pena guardar: uma palestra gravada, uma entrevista, um ensaio ou uma banda sonora.',
    'mp4-converter': 'É a ferramenta a usar quando um clipe não reproduz ou não carrega, porque o MP4 é o único formato de vídeo que telemóveis, navegadores, televisores e plataformas sociais aceitam todos.',
    'video-converter': 'Use-a quando um clipe tem de mudar de mundo — sair de um programa de edição, ir para um telemóvel, entrar num navegador, ou chegar a uma plataforma que só aceita um contentor específico.',
    'mp3-to-wav': 'O motivo habitual é edição: as estações de áudio digital, as cadeias de masterização e muitos fluxos de áudio para radiodifusão ou videojogos querem WAV sem compressão, para não descodificarem um ficheiro comprimido em cada operação.',
    'wav-to-mp3': 'As gravações saem de um gravador de campo ou de uma estação de áudio como ficheiros WAV enormes; o MP3 é o que os torna suficientemente leves para enviar, carregar ou levar no telemóvel.',
    'flac-to-mp3': 'Uma biblioteca FLAC soa muito bem em casa, mas auto-rádios, telemóveis antigos e leitores baratos recusam-na muitas vezes — o MP3 é a cópia de compatibilidade que se leva consigo.',
    'aac-to-mp3': 'É sobretudo uma questão de compatibilidade: o AAC vem dos ecossistemas da Apple e do streaming, enquanto leitores antigos, rádios de automóvel e software de DJ esperam MP3.',
    'ogg-to-mp3': 'O OGG aparece em videojogos, na Wikipédia e em software livre, e quase nenhum dos leitores comuns num telemóvel ou num carro o abre.',
    'wma-to-mp3': 'O WMA é uma relíquia da era do Windows Media Player, e é assim que se resgata uma colecção de música antiga extraída para o telemóvel ou para uma biblioteca de streaming.',
    'm4a-to-mp3': 'É o passo habitual ao tirar música ou memorandos de voz do iPhone dos aparelhos Apple para software, automóveis ou leitores que só entendem MP3.',
    'mp3-to-aac': 'Alguns aparelhos e aplicações — sobretudo na Apple e nas plataformas de streaming — preferem AAC, por isso esta é uma conversão de compatibilidade e não uma melhoria de qualidade.',
    'mp3-to-ogg': 'Converte-se para OGG para motores de jogo, projectos de código aberto e plataformas onde se exige um codec livre de patentes.',
    'audio-converter': 'É a ferramenta para o momento em que um ficheiro não reproduz: um único sítio para levar o áudio até qualquer um dos formatos comuns em que o seu aparelho, o seu editor ou o seu formulário de carregamento insistam.',
    'rar-to-zip': 'O RAR precisa de software adicional para abrir, por isso é o que se faz antes de enviar um arquivo a alguém que não vai instalar o WinRAR.',
    '7z-to-zip': 'O 7Z comprime melhor mas exige o 7-Zip instalado; em ZIP, o destinatário pode simplesmente fazer duplo clique no ficheiro.',
    'tar-to-zip': 'O TAR vem das linhas de comandos do Linux e do macOS, enquanto o ZIP é o que um colega em Windows consegue abrir sem instalar absolutamente nada.',
    'gz-to-zip': 'Os ficheiros GZ chegam normalmente de um servidor ou de uma ferramenta Linux e são incómodos no Windows, onde um ZIP se descompacta com um duplo clique.',
    'zip-to-7z': 'Aqui a questão é o tamanho: a compressão do 7Z é bastante mais forte, o que conta quando arquiva uma pasta grande ou paga o armazenamento na nuvem ao gigabyte.',
    'video-to-gif': 'O uso típico é um pequeno ciclo para uma mensagem de conversa, um README, um relatório de erro ou uma publicação — sítios onde um GIF arranca sozinho embutido e um ficheiro de vídeo não.',
    'mp4-to-gif': 'O uso típico é um pequeno ciclo para uma conversa, um README, um relatório de erro ou uma publicação, onde um GIF arranca sozinho embutido enquanto um vídeo ficaria ali como anexo.',
    'webm-to-gif': 'Os clipes WebM guardados da web muitas vezes não se incorporam onde quer, ao passo que um GIF arranca embutido em aplicações de mensagens, gestores de incidências e fóruns.',
    'mov-to-gif': 'É o que se faz com uma gravação de ecrã do QuickTime que tem de aparecer embutida num pull request, num pedido de apoio ou numa publicação.',
    'avi-to-gif': 'Transformar alguns segundos de um clipe AVI antigo num GIF é a forma mais simples de os meter num documento, numa conversa ou numa página web.',
    'gif-to-mp4': 'GIF longos são enormes e reproduzem-se aos solavancos; o MP4 mostra a mesma animação por uma fracção do tamanho, que é precisamente por isso que as plataformas sociais os convertem nos bastidores.',
    'image-to-gif': 'Útil quando uma plataforma ou um sistema antigo espera expressamente um GIF, ou quando precisa de um fotograma fixo no mesmo formato de uma série de animações já existente.',
    'gif-compressor': 'Os GIF animados incham depressa, e esta é a solução quando um deles é demasiado pesado para um e-mail, para o limite de carregamento de uma conversa ou para uma página que tem de carregar depressa.',
    'merge-pdf': 'O caso clássico é uma candidatura ou uma participação: um formulário, uma digitalização e um recibo que têm de chegar todos como um único documento.',
    'split-pdf': 'Normalmente precisa exactamente de uma coisa dentro de um ficheiro muito mais longo — um capítulo, uma factura, uma página assinada de uma digitalização de cinquenta páginas.',
    'compress-pdf': 'Quase sempre um limite de tamanho: um tecto para anexos de e-mail, um formulário da administração pública ou um portal que rejeita qualquer coisa acima de alguns megabytes.',
    'rotate-pdf': 'Isto resolve o problema do dia-a-dia do digitalizador — páginas que saíram de lado ou ao contrário por causa da forma como as folhas foram introduzidas.',
    'protect-pdf': 'Protegem-se PDF com palavra-passe antes de enviar recibos de vencimento, contratos ou relatórios médicos, para que o conteúdo não seja legível por quem receber a mensagem reencaminhada a seguir.',
    'unlock-pdf': 'Use-o em documentos que lhe pertencem quando a palavra-passe é conhecida mas a restrição atrapalha — um extracto bancário que não consegue imprimir, por exemplo.',
    'view-metadata': 'Responde às perguntas que um ficheiro não lhe conta directamente: que câmara tirou esta foto, quanto dura realmente esta gravação, que codec está dentro deste vídeo, quantas páginas tem este PDF.',
    'ocr': 'A situação é sempre a mesma: tem um documento como imagem e precisa das palavras que ele contém — para as pesquisar, citar, editar ou arquivar como deve ser.',
    'pdf-compress-ai': 'Recorra a ele quando já tiver experimentado a compressão normal e o ficheiro continuar demasiado pesado para o limite de carregamento contra o qual está a lutar.',
    'text-to-speech': 'Usa-se para ouvir algo em vez de o ler — um artigo no caminho para o trabalho, um guião lido em voz alta para apanhar frases desajeitadas, ou uma locução para um vídeo.',
    'speech-to-text': 'O caso habitual é uma gravação de que precisa por escrito: uma reunião, uma entrevista, uma aula ou um memorando de voz que tem de virar apontamentos, uma acta ou uma transcrição citável.',
    'auto-subtitle': 'As legendas são o que torna um vídeo visível sem som e localizável pelos motores de busca, e escrevê-las à mão demora, mesmo num clipe curto, muito mais tempo do que se imagina.',
    'document-translation': 'O objectivo é ler ou enviar um documento noutra língua sem perder a maquetação que o torna legível.',
  },
  t: {
    'list.and': 'e',
    'family.document': 'documento',
    'family.image': 'imagem',
    'family.video': 'vídeo',
    'family.audio': 'áudio',
    'family.ebook': 'livro digital',
    'family.archive': 'arquivo',
    'family.subtitle': 'legendas',
    'family.none': 'ficheiro',
    'unit.sample': 'cada amostra',
    'unit.pixel': 'cada píxel',

    'intro.convert': '{{fromAbout}} {{toAbout}} {{reason}} {{toNote}}',
    'intro.convert.noSource': 'O {{fn}} é o formato de origem desta conversão.',
    'intro.lead': '{{lead}} {{reason}}',
    'intro.hub': 'Este é o conversor de {{category}} de uso geral: aceita {{inputs}} e escreve {{outputs}}, por isso não tem de procurar a ferramenta específica que corresponde ao seu par de formatos. {{reason}} Escolha acima o formato de saída e a conversão é tratada no servidor — nada para instalar.',
    'intro.hubExtract': 'Esta ferramenta retira a faixa de áudio de um ficheiro de vídeo e guarda-a à parte, transformando um vídeo num simples ficheiro de áudio que se reproduz em qualquer lado. Aceita {{inputs}} e escreve {{outputs}}. A faixa de vídeo é simplesmente descartada, e é por isso que o resultado ocupa uma fracção do tamanho original. {{reason}}',
    'intro.hubGif': 'Esta ferramenta transforma ficheiros {{inputs}} em GIF animados. {{gifAbout}} {{reason}}',
    'intro.hubGif.gifAbout': 'O GIF está limitado a uma paleta de 256 cores por fotograma, e é por isso que as fotografias aparecem com bandas, mas anima-se e reproduz-se sozinho dentro de quase todo o lado na internet.',
    'intro.compress': '{{about}} Esta ferramenta recodifica o seu {{fn}} num ficheiro mais leve sem mudar de formato, por isso o que descarrega continua a ser um {{fn}} normal, que abre exactamente onde o original abria. {{reason}}{{extra}}',
    'intro.compress.lossless': ' Como o {{fn}} é sem perdas, a maior parte da poupança vem de uma codificação mais inteligente e de uma paleta reduzida, e não de deitar fora detalhe.',
    'intro.soon': '{{reason}} Esta ferramenta ainda não está activa — está em desenvolvimento e aparecerá aqui assim que estiver pronta.',
    'intro.lead.pdf-merge': 'Juntar combina vários PDF num só ficheiro, pela ordem que escolher, sem voltar a compor as páginas: o texto continua seleccionável e as imagens mantêm a qualidade original. O PDF é um formato de maquetação fixa: guarda a posição exacta de cada caractere, cada linha e cada imagem, e é por isso que aparece idêntico em todo o lado mas é incómodo de editar.',
    'intro.lead.pdf-split': 'Dividir extrai de um PDF as páginas que indicar e guarda-as como um novo documento, deixando o original intacto. O PDF é um formato de maquetação fixa: guarda a posição exacta de cada caractere, cada linha e cada imagem, e é por isso que aparece idêntico em todo o lado mas é incómodo de editar.',
    'intro.lead.pdf-compress': 'Comprimir um PDF recodifica as imagens que ele contém e elimina dados incorporados redundantes, que é onde reside quase todo o peso de um PDF grande. O texto e os gráficos vectoriais ficam nítidos.',
    'intro.lead.pdf-compress-ai': 'Esta ferramenta analisa o que está dentro do PDF antes de o comprimir, para que imagens fotográficas, gráficos planos e páginas só de texto sejam tratados cada um da forma que mais espaço poupa sem os degradar de modo visível.',
    'intro.lead.pdf-rotate': 'Rodar altera o indicador de orientação e a geometria de página de um PDF, para que as páginas sejam mostradas e impressas do lado certo. Nada é recomposto, por isso não se perde qualidade.',
    'intro.lead.pdf-protect': 'Proteger um PDF cifra o seu conteúdo, para que não possa ser aberto sem a palavra-passe que definir. A cifra aplica-se ao próprio ficheiro, não a um invólucro à sua volta.',
    'intro.lead.pdf-unlock': 'Desbloquear remove a palavra-passe e as restrições de utilização de um PDF cuja palavra-passe já possui, para que volte a poder ser aberto, impresso e copiado normalmente.',
    'intro.lead.metadata': 'Todos os ficheiros transportam informação sobre si próprios que não se vê ao abri-los: dimensões da imagem e definições da câmara, duração e taxa de bits do áudio, codec e cadência do vídeo, autor e número de páginas do documento. Esta ferramenta lê esses metadados e mostra-os.',
    'intro.lead.ocr': 'O reconhecimento óptico de caracteres olha para uma imagem de texto — uma digitalização, uma foto, uma página PDF sem camada de texto — e deduz quais são os caracteres, transformando uma imagem de palavras em palavras que um computador pode pesquisar, copiar e editar.',
    'intro.lead.tts': 'A síntese de voz gera áudio falado a partir de texto escrito usando vozes neuronais, por isso obtém uma gravação de som natural em vez da saída plana e robótica dos sistemas antigos.',
    'intro.lead.stt': 'O reconhecimento de voz transcreve áudio falado em palavras escritas. Lida com fala natural, sotaques e ruído de fundo muito melhor do que o antigo software de ditado, e devolve uma transcrição que pode editar.',
    'intro.lead.subtitle': 'O gerador de legendas transcreve a fala de um vídeo e escreve-a com códigos de tempo, produzindo um ficheiro de legendas normalizado em vez de uma simples transcrição.',

    'steps.convert.1.batch': 'Arraste o seu ficheiro {{fn}} para a área de carregamento no topo desta página, ou clique nela para procurar no seu dispositivo. Pode adicionar vários ficheiros — ou uma pasta inteira — e converter tudo de uma vez.',
    'steps.convert.1.single': 'Arraste o seu ficheiro {{fn}} para a área de carregamento no topo desta página, ou clique nela para procurar no seu dispositivo.',
    'steps.convert.2.direct': 'Escolha {{tn}} como formato de saída e clique em Converter.',
    'steps.convert.2.dropdown': 'Escolha {{tn}} como formato de saída na lista pendente e clique em Converter.',
    'steps.convert.2.directMedia': 'Escolha {{tn}} como formato de saída, ajuste a qualidade ou o tamanho nas definições avançadas se precisar e clique em Converter.',
    'steps.convert.2.dropdownMedia': 'Escolha {{tn}} como formato de saída na lista pendente, ajuste a qualidade ou o tamanho nas definições avançadas se precisar e clique em Converter.',
    'steps.convert.3': 'Descarregue o seu ficheiro {{tn}} terminado. A ligação de transferência mantém-se activa 24 horas, findas as quais ambos os ficheiros são eliminados automaticamente.',
    'steps.hub.1.batch': 'Arraste o seu ficheiro de {{category}} ({{inputs}} são todos aceites) para a área de carregamento no topo desta página, ou clique nela para procurar no seu dispositivo. Pode adicionar vários ficheiros — ou uma pasta inteira — e converter tudo de uma vez.',
    'steps.hub.1.single': 'Arraste o seu ficheiro de {{category}} ({{inputs}} são todos aceites) para a área de carregamento no topo desta página, ou clique nela para procurar no seu dispositivo.',
    'steps.hub.2.direct': 'Escolha o formato de saída de que precisa e clique em Converter.',
    'steps.hub.2.dropdown': 'Escolha na lista pendente o formato de saída de que precisa e clique em Converter.',
    'steps.hub.2.directMedia': 'Escolha o formato de saída de que precisa, ajuste a qualidade ou o tamanho nas definições avançadas se for necessário e clique em Converter.',
    'steps.hub.2.dropdownMedia': 'Escolha na lista pendente o formato de saída de que precisa, ajuste a qualidade ou o tamanho nas definições avançadas se for necessário e clique em Converter.',
    'steps.hub.3': 'Descarregue o seu ficheiro terminado. A ligação de transferência mantém-se activa 24 horas, findas as quais ambos os ficheiros são eliminados automaticamente.',
    'steps.pdf-merge.1': 'Adicione todos os PDF que quer combinar — arraste-os em conjunto para a área de carregamento, ou clique para os seleccionar um após outro.',
    'steps.pdf-merge.2': 'Arraste os ficheiros para a ordem pela qual quer que apareçam no documento final.',
    'steps.pdf-merge.3': 'Clique em Juntar e descarregue o único PDF combinado.',
    'steps.pdf-split.1': 'Carregue o PDF de onde quer retirar páginas.',
    'steps.pdf-split.2': 'Escreva as páginas ou intervalos de que precisa no campo de intervalos de páginas — por exemplo 1-3, 5, 7-10.',
    'steps.pdf-split.3': 'Clique em Converter e descarregue as páginas extraídas.',
    'steps.pdf-compress.1': 'Arraste o seu PDF para a área de carregamento, ou clique para o procurar.',
    'steps.pdf-compress.2': 'Clique em Converter — o ficheiro é analisado e as suas imagens e dados incorporados são recodificados num tamanho menor.',
    'steps.pdf-compress.3': 'Descarregue o PDF comprimido e verifique a poupança de tamanho mostrada ao lado.',
    'steps.pdf-rotate.1': 'Carregue o PDF cujas páginas estão ao contrário.',
    'steps.pdf-rotate.2': 'Escolha quanto rodá-las — 90°, 180° ou 270°.',
    'steps.pdf-rotate.3': 'Clique em Converter e descarregue o PDF corrigido.',
    'steps.pdf-protect.1': 'Carregue o PDF que quer proteger.',
    'steps.pdf-protect.2': 'Introduza a palavra-passe que será necessária para o abrir e guarde uma cópia num sítio seguro.',
    'steps.pdf-protect.3': 'Clique em Converter e descarregue o PDF cifrado.',
    'steps.pdf-unlock.1': 'Carregue o PDF protegido por palavra-passe.',
    'steps.pdf-unlock.2': 'Introduza a palavra-passe actual para que o ficheiro possa ser decifrado.',
    'steps.pdf-unlock.3': 'Clique em Converter e descarregue o PDF desbloqueado.',
    'steps.metadata.1': 'Arraste qualquer ficheiro para a área de carregamento — uma imagem, um vídeo, um ficheiro de áudio ou um documento.',
    'steps.metadata.2': 'O ficheiro é inspeccionado e não convertido, por isso nada nele é alterado.',
    'steps.metadata.3': 'Leia os metadados directamente na página: dimensões, duração, codec, detalhes da câmara, número de páginas e mais.',
    'steps.ocr.1': 'Carregue o PDF digitalizado ou a fotografia do texto.',
    'steps.ocr.2': 'Escolha o idioma do documento e se quer um PDF pesquisável ou texto simples.',
    'steps.ocr.3': 'Clique em Converter e descarregue o resultado, com o texto reconhecido agora seleccionável e pesquisável.',
    'steps.tts.1': 'Escreva ou cole o seu texto na caixa — até 4096 caracteres por conversão.',
    'steps.tts.2': 'Escolha uma voz, uma velocidade de fala e um formato de saída.',
    'steps.tts.3': 'Clique em Converter e descarregue o ficheiro de áudio terminado.',
    'steps.stt.1': 'Carregue a sua gravação, ou grave directamente do microfone com o botão da página.',
    'steps.stt.2': 'Se quiser, indique o idioma falado para melhorar a precisão, e escolha saída em TXT ou DOCX.',
    'steps.stt.3': 'Clique em Converter, leia a transcrição na página e depois descarregue-a.',
    'steps.subtitle.1': 'Carregue o vídeo que quer legendar.',
    'steps.subtitle.2': 'Escolha SRT ou VTT, e indique o idioma falado se o conhecer.',
    'steps.subtitle.3': 'Clique em Converter e descarregue o ficheiro de legendas sincronizado, pronto a colocar no seu leitor ou no seu programa de edição.',
    'steps.compress.1': 'Arraste as suas imagens {{fn}} para a área de carregamento, ou clique para as procurar. Pode adicionar uma pasta inteira de uma vez.',
    'steps.compress.1.gif': 'Arraste a sua animação {{fn}} para a área de carregamento, ou clique para a procurar. Pode adicionar uma pasta inteira de uma vez.',
    'steps.compress.2': 'Clique em Converter — o ficheiro é recodificado num tamanho menor mantendo-se no mesmo formato.',
    'steps.compress.3': 'Descarregue o resultado e compare-o com o tamanho original mostrado na página.',
    'steps.soon.1': 'Escolha a ferramenta de que precisa na página de Ferramentas — tudo excepto esta já está activo hoje.',
    'steps.soon.2': 'Carregue o seu ficheiro e escolha um formato de saída.',
    'steps.soon.3': 'Descarregue o resultado, ou volte aqui quando a tradução de documentos estiver activa.',

    'faq.cost.q.pair': 'Converter {{from}} para {{to}} é gratuito?',
    'faq.cost.q.tool': 'O {{label}} é gratuito?',
    'faq.cost.a.pair': "Cada conversão de {{from}} para {{to}} usa um crédito de um pequeno pacote pré-pago — não há subscrição, os créditos nunca expiram, e uma conversão que falhe não lhe é cobrada.",
    'faq.cost.a.tool': "Cada conversão usa um crédito de um pequeno pacote pré-pago — não há subscrição, os créditos nunca expiram, e uma conversão que falhe não lhe é cobrada.",
    'faq.cost.a.smartTts': "As funções inteligentes são cobradas por utilização em vez de por ficheiro — 1 crédito por cada 1000 caracteres de texto, arredondados para cima. Não há subscrição: os créditos compram-se em pequenos pacotes pré-pagos, nunca expiram, e uma conversão que falhe nunca custa nada.",
    'faq.cost.a.smartAv': "As funções inteligentes são cobradas por utilização em vez de por ficheiro — 1 crédito por cada 5 minutos de áudio ou vídeo, arredondados para cima. Não há subscrição: os créditos compram-se em pequenos pacotes pré-pagos, nunca expiram, e uma conversão que falhe nunca custa nada.",
    'faq.cost.q.metadata': 'A ferramenta de informação de ficheiro é gratuita?',
    'faq.cost.a.metadata': 'Sim. Ler os metadados de um ficheiro não é uma conversão, por isso não gasta crédito — pode inspeccionar tantos ficheiros quantos quiser. Os créditos só são gastos quando uma ferramenta produz mesmo um ficheiro novo para si.',
    'faq.cost.q.soon': 'O {{label}} já está disponível?',
    'faq.cost.a.soon': 'Ainda não — esta página é um marcador enquanto a ferramenta está a ser construída, por isso hoje não há nada para carregar aqui. O preço seguirá o mesmo modelo de créditos pré-pagos do resto do site: sem subscrição, com créditos que nunca expiram e sem cobrança por uma conversão que falhe.',

    'faq.time.q.pair': 'Quanto tempo demora a conversão de {{from}} para {{to}}?',
    'faq.time.q.tool': 'Quanto tempo demora o {{label}}?',
    'faq.time.a': '{{speed}} A velocidade de carregamento é normalmente o factor limitante, por isso um ficheiro grande numa ligação lenta demora mais do que a própria conversão.{{suffix}}',
    'faq.time.speed.image': 'As imagens são o que convertemos mais depressa — uma única foto fica normalmente pronta em menos de cinco segundos, e uma pasta inteira demora mais ou menos o tempo do próprio carregamento.',
    'faq.time.speed.document': 'A maioria dos documentos fica pronta em poucos segundos. Ficheiros muito longos — algumas centenas de páginas, ou uma digitalização carregada de imagens — podem levar até um minuto.',
    'faq.time.speed.audio': 'Uma música normal converte-se em poucos segundos. Uma gravação completa, como uma aula ou um episódio de podcast, demora normalmente bem menos de um minuto, sendo a maior parte o carregamento.',
    'faq.time.speed.video': 'O vídeo é a categoria mais lenta porque cada fotograma tem de ser recodificado. Um clipe curto demora segundos, enquanto um ficheiro longo em alta resolução pode levar alguns minutos.',
    'faq.time.speed.archive': 'Os arquivos convertem-se em segundos, embora um grande demore mais porque cada ficheiro lá dentro tem de ser extraído e voltado a empacotar.',
    'faq.time.speed.ebook': 'Os livros digitais são rápidos — um romance inteiro converte-se normalmente em poucos segundos.',
    'faq.time.speed.subtitle': 'A transcrição avança ao ritmo de poucos segundos por minuto de áudio, por isso um vídeo de dez minutos fica normalmente legendado em bem menos de um minuto.',
    'faq.time.suffix.standard': ' São aceites ficheiros até 200 MB.',
    'faq.time.suffix.smart': ' As funções inteligentes aceitam ficheiros até 25 MB; as conversões normais até 200 MB.',
    'faq.time.q.metadata': 'Quanto tempo demora a ler os metadados de um ficheiro?',
    'faq.time.a.metadata': 'Um ou dois segundos assim que o ficheiro estiver carregado. Nada é convertido nem recodificado — os cabeçalhos são analisados e o resultado é impresso directamente na página — por isso a espera é essencialmente o carregamento.',
    'faq.time.q.soon': 'Vai custar mais?',
    'faq.time.a.soon': 'Vai usar os mesmos créditos que tudo o resto do site. Não há um plano nem uma subscrição à parte para aderir, e os créditos que já tiver na sua conta funcionarão com ela a partir do momento em que ficar activa.',

    'faq.safety.q.pair': 'É seguro carregar o meu ficheiro {{from}}?',
    'faq.safety.q.tool': 'O meu ficheiro está seguro?',
    'faq.safety.a.pair': 'Os ficheiros viajam por uma ligação TLS cifrada e não são usados para mais nada além da conversão que pediu. Tanto o seu ficheiro {{from}} original como o ficheiro {{to}} que lhe devolvemos são eliminados automaticamente em 24 horas — de forma permanente e sem cópias de segurança guardadas — e o conteúdo nunca é lido, analisado nem partilhado. O serviço é operado a partir da Alemanha, ao abrigo do RGPD.',
    'faq.safety.a.tool': 'Os ficheiros viajam por uma ligação TLS cifrada e não são usados para mais nada além da conversão que pediu. Tanto o seu ficheiro original como o resultado que lhe devolvemos são eliminados automaticamente em 24 horas — de forma permanente e sem cópias de segurança guardadas — e o conteúdo nunca é lido, analisado nem partilhado. O serviço é operado a partir da Alemanha, ao abrigo do RGPD.',

    'quality.vectorRaster.q': 'O meu {{fn}} continuará nítido como {{tn}}?',
    'quality.vectorRaster.a': 'Até ao tamanho a que o exportar, sim. O {{fn}} guarda formas em vez de píxeis, por isso é infinitamente ampliável, mas um {{tn}} é uma grelha fixa de píxeis e ficará desfocado se depois for ampliado para além dessa grelha. Defina nas definições avançadas a largura e a altura de que realmente precisa antes de converter — exportar ao dobro ou ao triplo do tamanho de apresentação é o truque habitual para ecrãs de alta densidade de píxeis. Guarde o ficheiro {{fn}} original: continua a ser a cópia-mestra a partir da qual pode reexportar em qualquer resolução.',
    'quality.docToTxt.q': 'Vou perder a formatação ao converter {{fn}} para {{tn}}?',
    'quality.docToTxt.a': 'Sim, e de propósito — um ficheiro {{tn}} contém caracteres e mais nada. Tipos de letra, cores, imagens, tabelas, colunas e quebras de página desaparecem todos; o que recupera é o texto legível do documento pela ordem de leitura. É exactamente o que quer para pesquisar, para scripts ou para alimentar outro programa, e exactamente o que não quer se esperava manter o desenho. Note que um {{fn}} que na verdade é uma imagem digitalizada não contém texto nenhum para extrair — passe-o antes pela ferramenta de OCR.',
    'quality.docToSheet.q': 'Com que precisão se extraem tabelas de um {{fn}}?',
    'quality.docToSheet.a': 'Tabelas limpas, com traços e colunas regulares — extractos, facturas, relatórios exportados — passam de forma fiável, com cada valor a cair na sua própria célula para que possa somá-lo e ordená-lo. Tabelas sem contornos visíveis, células que abrangem várias linhas ou números partidos por uma quebra de página são os casos que vale a pena verificar a olho depois. O {{fn}} guarda posições e não estrutura de tabela, por isso a conversão tem de deduzir onde acaba uma coluna e começa a seguinte.',
    'quality.docToReflow.q': 'A maquetação sobrevive à conversão de {{fn}} para {{tn}}?',
    'quality.docToReflow.a': 'Não exactamente, e é precisamente essa a ideia. O {{fn}} prende o texto a coordenadas de página fixas; o {{tn}} reajusta-o ao ecrã e ao tamanho de letra do leitor, por isso números de página fixos, cabeçalhos, rodapés e maquetações a várias colunas são reinterpretados em vez de reproduzidos. O corpo do texto, os títulos, a ordem dos parágrafos e as imagens passam bem. Documentos sobretudo de prosa convertem-se lindamente; são as páginas muito trabalhadas graficamente, os formulários e as tabelas complexas que merecem uma vista de olhos depois.',
    'quality.docToFixed.q': 'A minha formatação será mantida no {{tn}}?',
    'quality.docToFixed.a': 'Sim — este sentido é o seguro. O {{tn}} regista a página tal como fica composta no fim, por isso tipos de letra, espaçamentos, tabelas, imagens e quebras de página ficam congelados exactamente como foram maquetados e terão o mesmo aspecto em qualquer dispositivo e impressora. Esse é também o compromisso: o resultado deixa de ser livremente editável, que costuma ser precisamente a razão pela qual se converte para {{tn}} antes de enviar um documento.',
    'quality.docToEditable.q': 'Com que precisão se converte de {{fn}} para {{tn}}?',
    'quality.docToEditable.a': 'Texto, títulos, listas, imagens e tabelas simples passam de forma fiável e continuam totalmente editáveis. Como o {{fn}} guarda posições e não estrutura, a conversão tem de reconstruir essa estrutura, por isso páginas muito trabalhadas — várias colunas, texto a contornar imagens, tabelas encaixadas complexas — podem precisar de um pequeno acerto depois. Se o PDF for uma digitalização sem qualquer camada de texto, use antes a ferramenta de OCR: reconhece os caracteres na imagem em vez de procurar um texto que não está lá.',
    'quality.docGeneric.q': 'Perco alguma coisa ao converter {{fn}} para {{tn}}?',
    'quality.docGeneric.a': 'As palavras, os títulos, as listas e as imagens passam intactas. O {{tn}} tem um vocabulário de formatação diferente do do {{fn}}, por isso um estilo muito específico pode ser simplificado pelo caminho, mas o conteúdo em si é preservado.',
    'quality.archive.q': 'Os ficheiros dentro do meu {{fn}} serão alterados?',
    'quality.archive.a': 'Não. Os formatos de arquivo são contentores sem perdas: o {{fn}} é extraído e os mesmos ficheiros são reempacotados como {{tn}}, byte a byte. Só mudam o método de compressão e o contentor. O que muda é o tamanho do próprio arquivo — {{clause}}.',
    'quality.archive.clause.to7z': 'o 7Z produz em geral um arquivo mais pequeno do que o ZIP graças à compressão LZMA',
    'quality.archive.clause.toZip': 'o ZIP fica normalmente um pouco maior do que o 7Z ou o RAR, que é o preço de poder abrir em todo o lado sem software adicional',
    'quality.archive.clause.other': 'o novo formato comprime de outra maneira, por isso o tamanho pode mexer-se em qualquer dos dois sentidos',
    'quality.imageToDoc.q': 'As minhas fotos vão perder qualidade dentro do {{tn}}?',
    'quality.imageToDoc.a': 'Não. Cada imagem {{fn}} é colocada no {{tn}} tal como está, uma por página, em vez de ser recomprimida, por isso o que vê no documento é o que saiu da câmara. O {{tn}} pesará aproximadamente a soma das imagens, o que convém saber antes de o enviar por e-mail — passe o resultado por Comprimir PDF se precisar dele mais leve.',
    'quality.toGif.q': 'Porque é que o meu GIF fica pior do que o {{fn}} original?',
    'quality.toGif.a': 'Porque o GIF está limitado a 256 cores por fotograma. Um vídeo ou uma foto contêm milhões, por isso o codificador tem de escolher uma paleta e aproximar tudo o resto, o que se nota como bandas nos degradés e nos céus. O GIF também não transporta qualquer faixa de áudio. Ambas as coisas são próprias do formato e não da conversão — mantenha o clipe curto e, se a perda de cor pesar mais do que a reprodução automática embutida, um MP4 ficará muito melhor ocupando menos.',
    'quality.lossyToLossless.q': 'Converter {{fn}} para {{tn}} melhora a qualidade?',
    'quality.lossyToLossless.a': 'Não — e este é de longe o equívoco mais comum sobre esta conversão. O {{fn}} é com perdas: o detalhe que o seu codificador descartou desapareceu para sempre e nada o consegue reconstruir. O que o {{tn}} lhe dá é um contentor sem perdas para o que resta, de modo que o ficheiro deixa de se degradar a cada gravação ou edição seguinte. Isso é mesmo útil quando está prestes a {{clause}}, mas não recuperará qualidade que já se perdeu.',
    'quality.lossyToLossless.edit.audio': 'editar, masterizar ou processar o áudio',
    'quality.lossyToLossless.edit.image': 'editar, retocar ou compor a imagem',
    'quality.losslessToLossy.q': 'Vou perder qualidade ao converter {{fn}} para {{tn}}?',
    'quality.losslessToLossy.a.audio': 'Alguma, por desenho — é assim que o ficheiro fica mais pequeno. O {{tn}} é com perdas, por isso o codificador descarta a informação que julga menos perceptível. Com definições sensatas a diferença é muito difícil de notar de ouvido, e pode subir a taxa de bits nas definições avançadas se preferir trocar tamanho por fidelidade. Guarde o seu ficheiro {{fn}} original: continua a ser a cópia-mestra, e voltar a codificar o {{tn}} mais tarde agravaria a perda.',
    'quality.losslessToLossy.a.visual': 'Alguma, por desenho — é assim que o ficheiro fica mais pequeno. O {{tn}} é com perdas, por isso o codificador descarta a informação que julga menos perceptível. Com definições sensatas a diferença é muito difícil de notar a olho, e pode subir o valor de qualidade nas definições avançadas se preferir trocar tamanho por fidelidade. Guarde o seu ficheiro {{fn}} original: continua a ser a cópia-mestra, e voltar a codificar o {{tn}} mais tarde agravaria a perda.',
    'quality.lossyToLossy.q': 'Vou perder qualidade ao converter {{fn}} para {{tn}}?',
    'quality.lossyToLossy.a.audio': 'Um pouco. Ambos os formatos são com perdas, por isso o {{fn}} é descodificado e depois recodificado como {{tn}}, e cada geração de codificação com perdas larga uma pequena quantidade de detalhe. Com definições normais não é algo que a maioria note ao ouvir, e pode subir a taxa de bits nas definições avançadas. O que convém evitar é converter o mesmo ficheiro para trás e para a frente repetidamente — é isso que torna a perda audível.',
    'quality.lossyToLossy.a.visual': 'Um pouco. Ambos os formatos são com perdas, por isso o {{fn}} é descodificado e depois recodificado como {{tn}}, e cada geração de codificação com perdas larga uma pequena quantidade de detalhe. Com definições normais não é algo que a maioria note, e pode subir a qualidade nas definições avançadas. O que convém evitar é converter o mesmo ficheiro para trás e para a frente repetidamente — é isso que torna a perda visível.',
    'quality.losslessToLossless.q': 'Vou perder qualidade ao converter {{fn}} para {{tn}}?',
    'quality.losslessToLossless.a.plain': 'Não. Tanto o {{fn}} como o {{tn}} são sem perdas, por isso {{unit}} é preservada exactamente e o resultado é idêntico ao original. Só muda o tamanho do ficheiro. Pode voltar a converter mais tarde sem qualquer degradação.',
    'quality.losslessToLossless.a.bulky': 'Não. Tanto o {{fn}} como o {{tn}} são sem perdas, por isso {{unit}} é preservada exactamente e o resultado é idêntico ao original. Só muda o tamanho do ficheiro, normalmente de forma drástica para menos, porque o {{fn}} guarda os seus dados praticamente sem compressão. Pode voltar a converter mais tarde sem qualquer degradação.',
    'quality.fallback.q': 'Vou perder qualidade ao converter {{fn}} para {{tn}}?',
    'quality.fallback.a': 'Para ficheiros normais o resultado é visual e funcionalmente equivalente ao original. Onde os dois formatos suportam funcionalidades diferentes, a conversão mantém tudo o que o {{tn}} é capaz de representar. As definições avançadas permitem-lhe subir a qualidade se o compromisso predefinido não for o que quer.',

    'relation.uncompressed.q': 'Porque é que o ficheiro {{tn}} é muito maior do que o {{fn}}?',
    'relation.uncompressed.a': 'Porque o {{tn}} não é comprimido. O {{fn}} aligeira o áudio descartando dados e codificando eficientemente o que resta; o {{tn}} escreve cada amostra em tamanho real, o que dá cerca de 10 MB por minuto de estéreo com qualidade de CD. Um aumento de dez para um é normal e esperado — é o preço de um ficheiro que o software de edição consegue processar sem descodificar nada primeiro. Se quiser áudio sem perdas por cerca de metade do peso, converta antes para FLAC.',
    'relation.extractAudio.q': 'Isto mantém o vídeo ou apenas o som?',
    'relation.extractAudio.a': 'Apenas o som. A faixa de áudio é extraída do ficheiro {{fn}} e guardada como {{tn}}; a faixa de vídeo é descartada, e é por isso que o resultado ocupa uma fracção do tamanho original. O áudio em si não é gravado de novo, por isso mantém a qualidade que tinha dentro do {{fn}} — extrair de um vídeo de baixa taxa de bits não pode produzir áudio de alta taxa de bits.',
    'relation.videoContainer.q': 'O meu {{tn}} vai reproduzir em telemóveis, televisores e redes sociais?',
    'relation.videoContainer.a.mp4': 'É exactamente para isso que serve esta conversão. O MP4 com vídeo H.264 é o mais próximo que há de um formato de vídeo universal: iPhone, telemóveis Android, televisores inteligentes, todos os navegadores, Instagram, YouTube, TikTok e todos os programas de edição comuns aceitam-no sem codecs adicionais. O {{fn}} era o formato que lhe estava a dar problemas; o MP4 é o que não dá.',
    'relation.videoContainer.a.other': 'O {{tn}} é mais especializado do que o MP4. {{note}} Se o seu objectivo é simplesmente «reproduzir em todo o lado», o MP4 é a escolha mais segura — escolha o {{tn}} quando um programa ou um aparelho específico o tiver pedido.',
    'relation.alphaLost.q': 'O que acontece à transparência ao converter {{fn}} para {{tn}}?',
    'relation.alphaLost.a': 'O {{tn}} não tem canal alfa, por isso as áreas transparentes não podem passar — durante a conversão são preenchidas com um fundo sólido (branco por predefinição). Se o fundo transparente tem um papel real no seu desenho, converta antes para PNG ou WebP, que o preservam ambos. Se a imagem for uma fotografia sem qualquer transparência, isto não faz diferença nenhuma.',
    'relation.alphaGained.q': 'Converter {{fn}} para {{tn}} torna o fundo transparente?',
    'relation.alphaGained.a': 'Não — e isto apanha muita gente desprevenida. O {{tn}} suporta transparência, mas um ficheiro {{fn}} não tem qualquer informação de transparência para passar, por isso o fundo fica exactamente como estava. O que a conversão lhe dá é um ficheiro capaz de conter transparência assim que recortar o fundo num editor de imagem, mais píxeis sem perdas que não se degradarão enquanto trabalha.',
    'relation.reflow.q': 'O {{tn}} vai funcionar no meu leitor de livros digitais?',
    'relation.reflow.a.epub': 'O EPUB é lido pelo Apple Books, Kobo, Google Play Books, Calibre e praticamente todos os leitores excepto o Kindle, que quer MOBI ou AZW3 (o Kindle também aceita EPUB por e-mail hoje em dia). Como o texto reflui, pode mudar o tamanho da letra no aparelho sem acabar a deslizar para o lado — que é toda a razão para converter um {{fn}} logo à partida.',
    'relation.reflow.a.kindle': 'O {{tn}} é lido pelos aparelhos e aplicações Kindle para que foi concebido. Como o texto reflui, pode mudar o tamanho da letra no aparelho sem acabar a deslizar para o lado — que é toda a razão para converter um {{fn}} logo à partida.',

    'compatibility.q': 'Com o que poderei abrir depois o ficheiro {{tn}}?',
    'compatibility.a': '{{note}} Não é preciso instalar nada para fazer a conversão — corre nos nossos servidores, e o {{tn}} terminado volta no seu navegador pronto a abrir, editar ou reencaminhar. O seu {{fn}} original nunca é alterado; devolvemos sempre apenas um ficheiro novo.',
    'compatibility.noteFallback': 'O {{tn}} é amplamente suportado.',

    'shapeFaq.pdf-merge.q1': 'Juntá-los vai reduzir a qualidade dos meus PDF?',
    'shapeFaq.pdf-merge.a1': 'Não. As páginas são copiadas para o novo documento exactamente como estão em vez de serem recompostas, por isso o texto continua seleccionável e as imagens mantêm a resolução original. O ficheiro juntado pesa aproximadamente a soma dos originais — passe-o depois por Comprimir PDF se isso lhe interessar.',
    'shapeFaq.pdf-merge.q2': 'Quantos PDF posso juntar de uma vez, e a ordem interessa?',
    'shapeFaq.pdf-merge.a2': 'Pode adicionar tantos ficheiros quantos precisar de uma só vez, e a ordem interessa muito: o documento final segue a ordem mostrada na lista, que pode reorganizar arrastando antes de juntar. Fixe primeiro a ordem e junte depois — é mais rápido do que corrigi-la a seguir.',
    'shapeFaq.pdf-split.q1': 'Como escolho que páginas extrair?',
    'shapeFaq.pdf-split.a1': 'Escreva-as no campo de intervalos de páginas usando vírgulas e hífenes: «1-3, 5, 7-10» dá-lhe as páginas de um a três, a página cinco e as páginas de sete a dez num único documento de saída. Os números referem-se às páginas do próprio PDF, contadas a partir de um, o que nem sempre é o número impresso na página.',
    'shapeFaq.pdf-split.q2': 'Dividir altera o PDF original?',
    'shapeFaq.pdf-split.a2': 'Não. O ficheiro que carrega nunca é alterado — as páginas extraídas são escritas num documento novo e o original fica intacto, antes de ser eliminado dos nossos servidores em 24 horas juntamente com o resultado.',
    'shapeFaq.pdf-compress.q1': 'Quanto é que o meu PDF vai encolher?',
    'shapeFaq.pdf-compress.a1': 'Depende inteiramente do que está lá dentro. PDF dominados por digitalizações ou fotografias encolhem muitas vezes entre 50 e 90 %, porque é aí que reside quase todo o peso. Um PDF só de texto já é compacto e talvez mal mude. Texto e gráficos vectoriais ficam nítidos em qualquer dos casos — a poupança vem de recodificar as imagens e de eliminar dados incorporados redundantes.',
    'shapeFaq.pdf-compress.q2': 'O texto continuará seleccionável e pesquisável?',
    'shapeFaq.pdf-compress.a2': 'Sim. A compressão actua sobre as imagens incorporadas e sobre dados internos redundantes; a camada de texto, os tipos de letra, as ligações e os marcadores ficam intactos, por isso poderá continuar a pesquisar, seleccionar e copiar do ficheiro comprimido exactamente como antes.',
    'shapeFaq.pdf-compress-ai.q1': 'Em que é que isto difere da compressão normal de PDF?',
    'shapeFaq.pdf-compress-ai.a1': 'A compressão normal aplica uma única definição a todo o ficheiro. Esta ferramenta olha primeiro para o que cada página contém de facto, para que imagens fotográficas, diagramas planos e páginas só de texto sejam tratados cada um da forma que mais espaço poupa sem os degradar visivelmente. Em documentos mistos isso significa normalmente um ficheiro mais pequeno com a mesma qualidade aparente.',
    'shapeFaq.pdf-compress-ai.q2': 'O texto continuará seleccionável e pesquisável?',
    'shapeFaq.pdf-compress-ai.a2': 'Sim. A camada de texto, os tipos de letra, as ligações e os marcadores são preservados — só as imagens incorporadas e os dados internos redundantes são recodificados, por isso o PDF comprimido continua totalmente pesquisável e copiável.',
    'shapeFaq.pdf-rotate.q1': 'Rodar um PDF faz perder qualidade?',
    'shapeFaq.pdf-rotate.a1': 'De todo. A rotação altera a geometria de página registada no ficheiro em vez de recompor o que quer que seja, por isso o texto continua nítido como vectorial, as imagens ficam intactas e o tamanho do ficheiro mal se mexe. Pode rodar outra vez mais tarde sem qualquer dano acumulado.',
    'shapeFaq.pdf-rotate.q2': 'Posso rodar apenas algumas páginas?',
    'shapeFaq.pdf-rotate.a2': 'A rotação que escolher — 90°, 180° ou 270° — é aplicada ao documento. Se páginas diferentes estiverem erradas em direcções diferentes, a abordagem habitual é dividir o PDF, rodar cada parte pelo ângulo de que precisa e voltar a juntar os resultados com a ferramenta Juntar PDF.',
    'shapeFaq.pdf-protect.q1': 'O que acontece se me esquecer da palavra-passe?',
    'shapeFaq.pdf-protect.a1': 'O ficheiro não poderá ser aberto. A cifra aplica-se ao próprio PDF, por isso não há ligação de reposição nem porta das traseiras — nem para si nem para nós. Guarde a palavra-passe num sítio seguro antes de reencaminhar o documento, e envie-a por um canal diferente do do ficheiro.',
    'shapeFaq.pdf-protect.q2': 'Quão forte é a protecção?',
    'shapeFaq.pdf-protect.a2': 'O PDF é cifrado com o esquema padrão do sector integrado no formato, por isso o seu conteúdo não pode ser lido sem a palavra-passe por nenhum leitor conforme. O ponto fraco prático nunca é o algoritmo mas a própria palavra-passe — uma curta ou óbvia adivinha-se depressa, por isso use uma longa para o que for mesmo confidencial.',
    'shapeFaq.pdf-unlock.q1': 'Isto consegue remover uma palavra-passe que eu não conheço?',
    'shapeFaq.pdf-unlock.a1': 'Não. Tem de fornecer a palavra-passe actual; a ferramenta decifra o ficheiro com ela em vez de quebrar a cifra. Destina-se a documentos que lhe pertencem ou que está autorizado a abrir — um extracto do seu próprio banco, por exemplo — em que a restrição está simplesmente a atrapalhar.',
    'shapeFaq.pdf-unlock.q2': 'O que posso fazer com o ficheiro depois?',
    'shapeFaq.pdf-unlock.a2': 'Tudo o que a protecção bloqueava: abri-lo sem pedido, imprimi-lo, copiar texto dele e editá-lo noutro software. O conteúdo das páginas em si não muda — só a camada de cifra e as suas restrições de utilização são removidas.',
    'shapeFaq.metadata.q1': 'Isto altera o meu ficheiro de alguma maneira?',
    'shapeFaq.metadata.a1': 'Não. O ficheiro é lido e não convertido — nada é reescrito e nada de novo é produzido além da informação mostrada no ecrã. É a ferramenta mais segura daqui para apontar a um ficheiro de que não tem a certeza.',
    'shapeFaq.metadata.q2': 'Que tipo de informação vou ver?',
    'shapeFaq.metadata.a2': 'Depende do ficheiro. As imagens mostram dimensões, profundidade de cor e dados EXIF como modelo da câmara, objectiva, exposição e, quando a câmara os registou, coordenadas GPS. O áudio mostra duração, taxa de bits, frequência de amostragem e número de canais. O vídeo acrescenta codec, resolução e cadência de fotogramas. Os documentos mostram número de páginas, autor, produtor e data de criação.',
    'shapeFaq.ocr.q1': 'Com que precisão reconhece o texto?',
    'shapeFaq.ocr.a1': 'Uma digitalização limpa e direita de texto impresso numa resolução razoável é reconhecida com muita precisão. A precisão desce com páginas tortas ou desfocadas, fotografias de pouco contraste, tipos de letra invulgares e escrita à mão. Escolher o idioma certo interessa, porque o reconhecimento usa-o para resolver caracteres ambíguos.',
    'shapeFaq.ocr.q2': 'Qual é a diferença entre o PDF pesquisável e a saída em texto simples?',
    'shapeFaq.ocr.a2': 'O PDF pesquisável mantém a imagem de página original exactamente como está e acrescenta por baixo uma camada de texto invisível, por isso o documento parece igual mas agora pode ser pesquisado e copiado — é o que quer para arquivar. O texto simples deita fora a maquetação e dá-lhe só as palavras, que é o que quer para editar, para scripts ou para alimentar outro programa.',
    'shapeFaq.tts.q1': 'Quão naturais soam as vozes?',
    'shapeFaq.tts.a1': 'São vozes neuronais e não a antiga síntese por concatenação, por isso levam entoação ao nível da frase e pausas naturais em vez de lerem palavra a palavra. Há seis vozes disponíveis, da neutra à quente e à autoritária, e a velocidade de fala é ajustável. A pontuação interessa mais do que se pensa: vírgulas e pontos moldam o fraseado, por isso um texto bem pontuado é lido nitidamente melhor.',
    'shapeFaq.tts.q2': 'Quanto texto posso converter de uma vez?',
    'shapeFaq.tts.a2': 'Até 4096 caracteres por conversão — cerca de 600 a 700 palavras, ou aproximadamente cinco minutos de fala. Para textos mais longos, corte-os num ponto natural como um título de capítulo ou de secção e converta cada parte em separado; as definições de voz e velocidade mantêm-se iguais entre execuções, por isso as peças encaixam de forma limpa.',
    'shapeFaq.stt.q1': 'Com que precisão transcreve?',
    'shapeFaq.stt.a1': 'Fala clara num ambiente razoavelmente sossegado é transcrita com muita precisão, incluindo com uma grande variedade de sotaques. A precisão cai com muito ruído de fundo, com várias pessoas a falar por cima umas das outras, ou com jargão muito especializado e nomes próprios. Indicar o idioma falado em vez de deixar a detecção automática ajuda de forma notória.',
    'shapeFaq.stt.q2': 'Posso gravar directamente do meu microfone?',
    'shapeFaq.stt.a2': 'Sim — o gravador desta página capta o áudio directamente no navegador, o que é muitas vezes mais rápido do que ir procurar primeiro uma aplicação de gravação. O seu navegador vai pedir autorização para o microfone da primeira vez. Também pode carregar um ficheiro existente, e a transcrição aparece na página para que a leia antes de a descarregar em TXT ou DOCX.',
    'shapeFaq.subtitle.q1': 'Com que precisão são geradas as legendas?',
    'shapeFaq.subtitle.a1': 'Fala clara é transcrita com muita precisão, incluindo com sotaques. Música de fundo, conversas sobrepostas e terminologia especializada são onde os erros se infiltram, e indicar o idioma falado em vez de o detectar automaticamente ajuda. A saída é um ficheiro de legendas em texto simples, por isso corrigir uma palavra ou outra demora segundos em qualquer editor de texto.',
    'shapeFaq.subtitle.q2': 'Devo escolher SRT ou VTT?',
    'shapeFaq.subtitle.a2': 'O SRT é a escolha predefinida mais segura: YouTube, Vimeo, Premiere, Final Cut, VLC e praticamente qualquer leitor aceitam-no. Escolha VTT se as legendas forem para um leitor de vídeo HTML5 num site, já que o WebVTT é o formato que a faixa de legendas nativa do navegador espera e suporta estilos e posicionamento que o SRT não consegue exprimir.',
    'shapeFaq.soon.q1': 'Quando é que isto vai estar disponível?',
    'shapeFaq.soon.a1': 'Está em desenvolvimento activo. A ferramenta aparecerá aqui e começará a aceitar ficheiros assim que estiver pronta — do seu lado não é preciso instalar nem activar nada.',
    'shapeFaq.soon.q2': 'O que posso usar entretanto?',
    'shapeFaq.soon.a2': 'O resto do conversor está totalmente disponível: documentos, imagens, áudio, vídeo, arquivos, GIF e a caixa de ferramentas de PDF funcionam todos hoje, tal como as funções inteligentes de OCR, transcrição e legendas.',
    'shapeFaq.compress.q1': 'O ficheiro comprimido continuará a ser um {{fn}}?',
    'shapeFaq.compress.a1': 'Sim — o formato não muda, só o tamanho. O que descarrega é um {{fn}} normal que abre em qualquer sítio onde o original abria.{{alpha}} Quanto poupa depende do material de partida: {{source}}.',
    'shapeFaq.compress.alpha': ' A transparência e a animação são preservadas.',
    'shapeFaq.compress.source.png': 'capturas de ecrã e gráficos planos de interface comprimem-se de forma espectacular, ao passo que fotografias guardadas como PNG dão menos',
    'shapeFaq.compress.source.gif': 'animações longas e imagens muito agitadas comprimem-se mais, porque há mais redundância para retirar',
    'shapeFaq.compress.source.other': 'fotografias comprimem-se bem, ao passo que imagens já muito comprimidas têm menos para dar',
    'shapeFaq.compress.q2': 'Quanto é que o ficheiro vai encolher?',
    'shapeFaq.compress.a2': 'Normalmente entre um terço e um décimo do original, dependendo inteiramente do que o ficheiro contém e de como foi guardado à partida. Quando a conversão termina, a página mostra os tamanhos de antes e de depois lado a lado, por isso vê a poupança real em vez de a adivinhar.',
    'shapeFaq.hub.q1': 'Entre que formatos posso converter?',
    'shapeFaq.hub.a1': 'Entrada: {{inputs}}. Saída: {{outputs}}. Qualquer entrada pode ir para qualquer saída, por isso não precisa de encontrar uma página diferente para cada combinação — escolha o ficheiro, escolha o formato de destino, converta.',
    'shapeFaq.hub.q2': 'Vou perder qualidade?',
    'shapeFaq.hub.a2': 'Depende do par. Ir para um formato sem perdas mantém tudo mas produz um ficheiro maior; ir para um formato comprimido descarta dados de propósito em troca de tamanho, e as definições avançadas deixam-no decidir onde se colocar nesse compromisso. Converter entre dois formatos comprimidos larga um pouco de detalhe de cada vez, por isso vale a pena guardar o original como cópia-mestra.',
    'shapeFaq.hub-extract.q1': 'Isto mantém também o vídeo?',
    'shapeFaq.hub-extract.a1': 'Não — apenas o som. A faixa de áudio é retirada do vídeo e guardada à parte, e é por isso que o resultado ocupa uma fracção do tamanho do ficheiro original. O áudio não é gravado de novo, por isso mantém a qualidade que já tinha dentro do vídeo; extrair de um clipe de baixa taxa de bits não pode produzir áudio de alta taxa de bits.',
    'shapeFaq.hub-extract.q2': 'Que formato de saída devo escolher?',
    'shapeFaq.hub-extract.a2': 'MP3 para compatibilidade máxima — reproduz em qualquer telemóvel, auto-rádio e leitor. AAC ou M4A se o destino for um aparelho Apple ou uma aplicação moderna, já que soam ligeiramente melhor à mesma taxa de bits. WAV ou FLAC apenas se for editar o áudio, porque ambos são sem perdas e, por isso, volumosos.',
    'shapeFaq.hub-gif.q1': 'Porque é que o GIF fica pior do que o original?',
    'shapeFaq.hub-gif.a1': 'Porque o GIF só permite 256 cores por fotograma, enquanto o vídeo e as fotografias contêm milhões. O codificador escolhe uma paleta e aproxima o resto, o que se nota como bandas nos degradés e nos céus. O GIF também não transporta qualquer som. Ambos os limites são próprios do formato e não da conversão.',
    'shapeFaq.hub-gif.q2': 'Porque é que o meu ficheiro GIF é tão grande?',
    'shapeFaq.hub-gif.a2': 'O GIF comprime muito menos eficazmente do que os codecs de vídeo modernos, por isso o tamanho cresce depressa com a duração, a resolução e a cadência de fotogramas. Alguns segundos são o ponto ideal. Se o resultado ficar demasiado pesado, encurte o clipe, e se o tamanho contar mais do que a reprodução automática embutida, um MP4 mostrará a mesma animação ocupando uma fracção.',
  },
};
