// Romanian content pack. Mirrors packs/en.js key for key — see the header there.
export default {
  lang: 'ro',
  formats: {
    pdf: { about: 'PDF este un format cu aşezare fixă în pagină: reţine poziţia exactă a fiecărui caracter, a fiecărei linii şi a fiecărei imagini, motiv pentru care arată identic pe orice ecran şi la orice imprimantă, dar se editează greu.', note: 'PDF blochează paginaţia, fonturile şi aşezarea în pagină, aşa că destinatarul vede exact ce ai trimis.' },
    docx: { about: 'DOCX este formatul modern al Microsoft Word, în care textul trăieşte în paragrafe şi stiluri editabile, în loc să fie ţintuit la coordonate fixe de pagină.', note: 'DOCX îţi dă paragrafe cu adevărat editabile, urmărirea modificărilor şi comentarii în Word, Google Docs sau LibreOffice.' },
    xlsx: { about: 'XLSX este formatul de calcul tabelar al Excel, în care fiecare valoare stă într-o celulă adresabilă ce poate fi sortată, filtrată şi folosită într-o formulă.', note: 'Odată ce datele sunt în XLSX poţi să le însumezi, să le sortezi, să faci tabele pivot şi grafice, în loc să le retastezi.' },
    pptx: { about: 'PPTX salvează o prezentare ca diapozitive separate, cu casete de text editabile, forme, note ale vorbitorului şi tranziţii.', note: 'PPTX îţi dă diapozitive pe care chiar le poţi reedita, reordona şi prezenta din nou.' },
    txt: { about: 'Un fişier TXT nu este altceva decât caractere — fără fonturi, fără imagini, fără structură de pagină — ceea ce îl face minuscul, lizibil oriunde şi banal de căutat.', note: 'TXT înlătură tot în afară de cuvinte, exact ce vor scripturile, indexurile de căutare şi editoarele de text.' },
    html: { about: 'HTML este limbajul de marcare al webului: text învelit în etichete pe care un browser le transformă în titluri, paragrafe, legături şi imagini.', note: 'HTML se deschide în orice browser şi poate fi lipit direct într-un site sau într-un CMS.' },
    rtf: { about: 'RTF este un format de document deschis, construit pe text simplu, care duce cu el formatarea de bază — aldin, cursiv, fonturi, tabele — fără să te închidă într-un singur procesor de text.', note: 'RTF se deschide în Word, Pages, LibreOffice, WordPad şi aproape în orice procesor de text scris vreodată.' },
    odt: { about: 'ODT este formatul de text OpenDocument folosit de LibreOffice şi OpenOffice şi este un standard ISO, nu un format al unui producător anume.', note: 'ODT este formatul nativ, pe deplin editabil, al LibreOffice şi OpenOffice.' },
    epub: { about: 'EPUB este un format de carte electronică cu text curgător: nu are dimensiune fixă de pagină, aşa că textul se rearanjează după ecranul şi mărimea de font pe care le foloseşte cititorul.', note: 'EPUB îi permite cititorului să schimbe mărimea fontului şi să lase textul să curgă din nou, iar asta face documentele lungi confortabile pe telefon sau pe un e-reader.' },
    jpg: { about: 'JPG foloseşte compresie cu pierderi calibrată pentru fotografii: aruncă detaliile pe care ochiul le observă cel mai puţin, ceea ce face pozele mici, dar adaugă artefacte moi şi pătrăţoase în jurul muchiilor dure şi al textului.', note: 'JPG produce fişiere mici care se deschid literalmente peste tot, cu preţul unor detalii pierdute definitiv şi al lipsei transparenţei.' },
    jfif: { about: 'JFIF este o imagine JPEG salvată cu altă extensie; pixelii dinăuntru sunt date JPEG obişnuite, dar Windows refuză adesea să predea fişierul aplicaţiei pe care o vrei.', note: 'JFIF este în realitate doar JPEG sub alt nume.' },
    png: { about: 'PNG este fără pierderi: reţine fiecare pixel exact, acceptă un canal alfa complet pentru transparenţă şi nu se degradează niciodată când îl salvezi din nou, motiv pentru care este prima alegere pentru capturi de ecran, sigle şi grafică de interfaţă.', note: 'PNG păstrează fiecare pixel exact aşa cum este şi acceptă transparenţă reală, aşa că rezistă la editări repetate fără să se degradeze.' },
    webp: { about: 'WebP este formatul de imagine web modern al Google; comprimă vizibil mai tare decât JPG sau PNG la o calitate similară şi acceptă transparenţă şi animaţie, dar destule programe de birou şi de tipar tot nu îl pot deschide.', note: 'WebP produce cele mai mici fişiere dintre formatele web obişnuite şi acceptă transparenţă.' },
    bmp: { about: 'BMP păstrează date de pixeli brute, practic necomprimate, ceea ce îl face perfect fidel şi enorm de risipitor — o fotografie poate ocupa uşor de zece ori mai mult decât aceeaşi imagine în PNG.', note: 'BMP este brut şi necomprimat, exact ce aşteaptă încă programele vechi de Windows şi unele scanere.' },
    tiff: { about: 'TIFF este formatul de arhivă şi de pretipar: fără pierderi, cu adâncime mare de culoare, capabil să cuprindă mai multe pagini sau straturi — şi pe măsură de voluminos.', note: 'TIFF este formatul pe care îl cer tipografiile şi arhivele, pentru că nu se aruncă nimic.' },
    gif: { about: 'GIF este limitat la o paletă de 256 de culori pe cadru, motiv pentru care fotografiile apar cu benzi în el, dar se animă şi porneşte singur, încorporat, aproape peste tot pe internet.', note: 'GIF se animă şi porneşte singur în aplicaţiile de chat, în sistemele de tichete şi pe forumuri, dar este limitat la 256 de culori pe cadru.' },
    ico: { about: 'ICO este un container de pictograme Windows care ţine aceeaşi grafică în mai multe mărimi deodată, ca sistemul să poată alege 16×16 pentru o filă şi 256×256 pentru o scurtătură de pe desktop.', note: 'ICO adună mai multe rezoluţii într-un singur fişier, exact ce le trebuie faviconurilor şi pictogramelor aplicaţiilor Windows.' },
    heic: { about: 'HEIC este formatul în care iPhone salvează pozele în mod implicit; oferă cam aceeaşi calitate ca JPG pe aproximativ jumătate din spaţiu, dar Windows, multe formulare web şi o grămadă de programe mai vechi pur şi simplu refuză să îl deschidă.', note: 'HEIC este compact, dar prost susţinut în afara dispozitivelor Apple.' },
    svg: { about: 'SVG nu este alcătuit deloc din pixeli — este XML care descrie forme, trasee şi text, aşa că rămâne perfect clar la orice dimensiune şi poate fi editat sau restilizat prin cod.', note: 'SVG se scalează la orice dimensiune fără să devină vreodată neclar, pentru că reţine forme în loc de pixeli.' },
    mp4: { about: 'MP4 este un container — de obicei video H.264 cu sunet AAC — şi este singurul format video asupra căruia telefoanele, browserele, televizoarele, programele de montaj şi platformele sociale cad toate de acord.', note: 'MP4 rulează practic pe orice telefon, browser, televizor şi program de montaj fără software suplimentar.' },
    avi: { about: 'AVI este un container Microsoft din anii nouăzeci; playerele şi suitele de montaj mai vechi încă îl citesc, dar nu are funcţii moderne de streaming, iar fişierele lui tind să fie mult mai mari decât MP4.', note: 'AVI este ce aşteaptă playerele mai vechi, uneltele de creare DVD şi software-ul de montaj vechi.' },
    mov: { about: 'MOV este containerul QuickTime al Apple, formatul în care înregistrează iPhone şi Mac şi cel cu care Final Cut Pro şi iMovie se descurcă cel mai lin.', note: 'MOV este containerul cu care uneltele de montaj Apple lucrează cel mai lin.' },
    mkv: { about: 'MKV (Matroska) este un container deschis care poate găzdui oricâte piste video, audio şi de subtitrare într-un singur fişier — excelent pentru arhivare, dar respins de majoritatea telefoanelor, televizoarelor şi browserelor.', note: 'MKV poate purta mai multe piste audio şi de subtitrare într-un singur fişier.' },
    webm: { about: 'WebM este containerul fără redevenţe construit pentru video HTML5, de obicei cu VP9 sau AV1; browserele îl adoră, dar programele de montaj de birou şi software-ul Apple adesea nici nu îl ating.', note: 'WebM este mic şi se transmite nativ în browsere.' },
    wmv: { about: 'WMV este formatul video Windows Media al Microsoft, practic doar pentru Windows şi în mare parte abandonat în afara vechilor înregistrări de firmă şi a capturilor de ecran.', note: 'WMV este un format Windows Media cu foarte puţin sprijin în altă parte.' },
    flv: { about: 'FLV a fost containerul din spatele videoclipurilor Flash, iar de când Flash a fost scos din toate browserele este practic un format de arhivă imposibil de redat.', note: 'FLV este un container mort din era Flash.' },
    mp3: { about: 'MP3 este cu pierderi: codorul şterge definitiv acele părţi din semnal pe care prezice că nu le vei auzi, ceea ce micşorează o piesă la circa o zecime şi este motivul pentru care rulează absolut pe orice.', note: 'MP3 este de aproximativ zece ori mai mic decât sunetul necomprimat şi rulează pe orice telefon, casetofon auto şi player din ultimii douăzeci de ani.' },
    wav: { about: 'WAV păstrează sunetul necomprimat, eşantion cu eşantion, exact aşa cum a fost înregistrat — de aceea îl folosesc studiourile şi de aceea un minut de stereo la calitate CD ocupă circa 10 MB.', note: 'WAV este necomprimat şi fără pierderi, aşa că programele de montaj şi de masterizare îl pot prelucra fără să decodeze mai întâi nimic.' },
    flac: { about: 'FLAC comprimă sunetul fără pierderi: ocupă aproximativ jumătate cât un WAV şi totuşi se decodează înapoi într-o copie identică bit cu bit a înregistrării originale.', note: 'FLAC este identic bit cu bit, dar ocupă aproximativ jumătate cât un WAV.' },
    aac: { about: 'AAC este codecul cu pierderi din spatele Apple Music, YouTube şi al majorităţii serviciilor de streaming; la acelaşi debit sună în general mai bine decât MP3.', note: 'AAC sună mai bine decât MP3 la acelaşi debit şi este standardul în lumea Apple şi a streamingului.' },
    ogg: { about: 'OGG Vorbis este un codec cu pierderi liber de brevete, preferat de jocuri, de software-ul cu sursă deschisă şi de Wikipedia, cu o calitate comparabilă cu MP3 la dimensiuni mai mici.', note: 'OGG este liber de restricţii de brevet, motiv pentru care motoarele de joc şi proiectele cu sursă deschisă îl preferă.' },
    m4a: { about: 'M4A este un container MP4 care conţine doar sunet, în mod normal AAC — formatul pe care îl produc iTunes, Apple Music şi memourile vocale de pe iPhone.', note: 'M4A este fişierul audio standard al ecosistemului Apple.' },
    wma: { about: 'WMA este codecul audio cu pierderi al Microsoft din era Windows Media Player, rar susţinut în afara Windows şi practic abandonat.', note: 'WMA este un codec audio învechit care trăieşte doar pe Windows.' },
    zip: { about: 'ZIP este formatul de arhivă încorporat în Windows, macOS şi în orice telefon — un dublu clic e de ajuns, fără să instalezi nimic în plus.', note: 'ZIP se deschide cu un dublu clic pe Windows, macOS, Linux, iOS şi Android, fără să se instaleze nimic.' },
    rar: { about: 'RAR este un format de arhivă închis, cu compresie bună şi date de recuperare, dar are nevoie de WinRAR sau de o unealtă compatibilă ca să fie deschis.', note: 'RAR are nevoie de software terţ ca să fie dezarhivat.' },
    '7z': { about: '7Z foloseşte compresie LZMA, care produce constant arhive vizibil mai mici decât ZIP — cu preţul de a avea nevoie de 7-Zip sau de o unealtă compatibilă ca să le deschizi.', note: '7Z comprimă considerabil mai strâns decât ZIP, ceea ce contează la dosare mari şi la stocare în cloud cu plată.' },
    tar: { about: 'Un fişier TAR strânge multe fişiere într-unul singur fără să le comprime; vine din lumea Unix şi păstrează drepturile şi structura de directoare.', note: 'TAR păstrează drepturile Unix şi structura de directoare.' },
    gz: { about: 'GZ (gzip) comprimă un singur flux de date şi este ce produc serverele Linux şi uneltele din linia de comandă; pe Windows se deschide greu fără software suplimentar.', note: 'GZ este formatul standard de compresie pe Linux şi pe serverele web.' },
    srt: { about: 'SRT este formatul de subtitrare în text simplu pe care îl înţelege orice program de montaj şi orice player: replici numerotate, un interval de cod de timp şi rândul de dialog.', note: 'SRT este acceptat de YouTube, Vimeo, Premiere, Final Cut şi de orice player obişnuit.' },
  },
  reasons: {
    'pdf-to-word': 'Declanşatorul obişnuit este o modificare pe care nu o poţi face chiar în PDF — o clauză de contract, un rând din CV sau un paragraf de raport care trebuie schimbat fără să retastezi tot documentul.',
    'word-to-pdf': 'Word se transformă în PDF chiar la capătul vieţii unui document: când un CV, o ofertă sau un formular semnat pleacă spre cineva ale cărui fonturi, versiune de Word şi margini nu le controlezi.',
    'pdf-to-excel': 'Cazul tipic este un extras de cont, o factură sau un raport care există doar ca PDF, dar ale cărui cifre trebuie însumate, sortate sau puse în grafic.',
    'excel-to-pdf': 'Asta faci înainte de a trimite un buget sau o listă de preţuri cuiva care trebuie să o citească, dar nu să o modifice, şi înainte de tipărire — un PDF fixează sfârşiturile de pagină pe care Excel le-ar recalcula altfel pe fiecare calculator.',
    'pptx-to-pdf': 'Cei mai mulţi transformă o prezentare în PDF înainte de a o trimite sau împărţi, ca diapozitivele să nu se deplaseze şi ca nimeni să nu aibă nevoie de PowerPoint instalat ca să le deschidă.',
    'pdf-to-pptx': 'De asta ai nevoie când singura copie rămasă a unei prezentări este PDF-ul care a circulat după şedinţă şi trebuie să actualizezi sau să refoloseşti diapozitivele.',
    'pdf-to-txt': 'Motive frecvente: să dai un document unui script, unui index de căutare sau unei unelte de inteligenţă artificială, ori să reduci un raport lung la ceva prin care poţi căuta, pe care îl poţi compara şi lipi oriunde.',
    'pdf-to-html': 'Este cel mai rapid mod de a publica pe un site un raport, un manual sau o broşură deja existente, fără să reconstruieşti pagina de mână.',
    'html-to-pdf': 'Se face ca să arhivezi o pagină web exact aşa cum arată azi, sau ca să transformi un şablon HTML de factură ori de raport în ceva ce poate fi tipărit şi trimis.',
    'rtf-to-pdf': 'RTF iese de obicei din software mai vechi sau din şabloane de documente juridice; trecerea în PDF îţi dă un singur fişier care se deschide la fel peste tot şi nu poate fi modificat din greşeală.',
    'pdf-to-rtf': 'Aceasta este opţiunea când ai nevoie de o copie editabilă a unui PDF, dar nu poţi presupune că destinatarul are Word — practic orice procesor de text scris vreodată deschide RTF.',
    'odt-to-pdf': 'Cazul tipic: ai scris documentul în LibreOffice sau OpenOffice, iar cel care îl primeşte foloseşte Microsoft Office — sau nimic.',
    'pdf-to-epub': 'Cititul unui PDF pe telefon înseamnă mărire şi derulare pe orizontală la nesfârşit; conversia asta este în primul rând despre a face un document lung cu adevărat lizibil pe un ecran mic sau pe un e-reader.',
    'epub-to-pdf': 'EPUB se transformă în PDF când vrei să tipăreşti o carte, să o adnotezi pe numere de pagină fixe sau să o trimiţi cuiva care nu are nicio aplicaţie de citit instalată.',
    'document-converter': 'Aceasta este unealta pe care o deschizi când primeşti un document în formatul pe care expeditorul îl avea la îndemână şi îţi trebuie în cel pe care software-ul tău chiar îl deschide.',
    'ebook-converter': 'Librăriile de cărţi electronice şi dispozitivele preferă fiecare formatul propriu, aşa că asta foloseşti ca să muţi o carte care îţi aparţine de la un cititor sau o aplicaţie la alta.',
    'jpg-to-png': 'Declanşatorul obişnuit este editarea: trebuie să decupezi un fundal, să pui o siglă peste altă imagine sau să împiedici o captură de ecran să devină mai neclară la fiecare salvare.',
    'png-to-jpg': 'Aceasta este soluţia pentru o captură de ecran sau un export prea mare ca să fie ataşat la un e-mail sau ca să treacă de limita de dimensiune a unui formular de încărcare.',
    'webp-to-png': 'De obicei ai nevoie de asta după ce ai salvat o imagine de pe un site: WebP se descarcă fără probleme, dar editoarele mai vechi, programele de birotică şi unele servicii de tipar tot refuză să îl deschidă.',
    'webp-to-jpg': 'Cei mai mulţi fac asta ca să ducă o imagine de pe un site în ceva acceptat universal — un e-mail, un CMS mai vechi, un serviciu de developat fotografii sau programul preistoric al unui coleg.',
    'heic-to-jpg': 'Aceasta este problema clasică a iPhone-ului: pozele arată bine pe telefon, dar ajung pe un PC cu Windows sau într-un formular web ca fişiere .heic care nu se deschid.',
    'heic-to-png': 'Foloseşte asta când ai de gând să editezi fotografia, nu doar să o distribui — PNG îi dă editorului tău pixeli fără pierderi în loc de o copie proaspăt recomprimată.',
    'svg-to-png': 'Motivul obişnuit este o unealtă care refuză vectorii: o prezentare, un anunţ pe o piaţă online, o semnătură de e-mail sau un lanţ de producţie de pictograme care acceptă doar pixeli.',
    'svg-to-jpg': 'Aceasta este pentru locurile care vor un simplu fişier de tip fotografic — un document, o postare pe reţele sociale sau un formular de încărcare care respinge şi marcajul SVG, şi transparenţa.',
    'bmp-to-png': 'Fişierele BMP ies din software vechi de Windows şi din scanere la dimensiuni absurde; PNG reţine exact aceiaşi pixeli pe o fracţiune din spaţiu.',
    'tiff-to-jpg': 'Scanerele şi aparatele foto profesionale produc fişiere TIFF mult prea mari pentru e-mail, aşa că JPG este ce trimiţi odată ce copia de arhivă stă la loc sigur.',
    'gif-to-png': 'Asta faci cu un GIF static — o siglă, o pictogramă sau un cadru exportat — care arată benzi de culoare sau o margine zdrenţuită din cauza limitei de 256 de culori.',
    'png-to-ico': 'Aproape toţi cei care transformă PNG în ICO construiesc un favicon sau o pictogramă de aplicaţie Windows, iar amândouă aşteaptă containerul ICO, nu un simplu fişier de imagine.',
    'jfif-to-png': 'Fişierele JFIF apar de obicei când o fotografie este salvată din Outlook sau dintr-un browser, iar Windows refuză apoi să o predea aplicaţiei pe care chiar voiai să o foloseşti.',
    'heic-to-pdf': 'Util când fotografiezi documente, bonuri sau o tablă cu iPhone-ul şi trebuie să le depui ca un singur fişier, nu ca un dosar de imagini.',
    'image-compressor': 'Motivul obişnuit este o limită dură undeva — un formular de încărcare, un plafon pentru ataşamentele de e-mail sau o pagină web care se încarcă prea încet fiindcă imaginile ei sunt mult mai mari decât ar trebui.',
    'jpeg-compressor': 'Fotografii şi proprietarii de site-uri folosesc asta când fişierele JPEG la rezoluţie completă încetinesc o pagină sau nu trec de o limită de încărcare.',
    'png-compressor': 'Capturile de ecran şi grafica de interfaţă exportată cântăresc adesea câţiva megaocteţi fără motiv; asta le micşorează înainte să ajungă într-un document, într-un tichet sau pe o pagină web.',
    'mp4-to-avi': 'Motivul este aproape întotdeauna un aparat mai vechi sau un program anume — unele playere vechi, unelte de creare DVD şi programe pentru aparate foto citesc AVI şi nimic altceva.',
    'mp4-to-mov': 'Acesta este de obicei primul pas înainte de montaj pe Mac, fiindcă Final Cut Pro şi iMovie se descurcă cel mai lin cu fişierele QuickTime.',
    'mov-to-mp4': 'iPhone şi Mac înregistrează în MOV; tot restul aşteaptă MP4, aşa că asta este conversia pe care o rulezi înainte să încarci, să trimiţi sau să publici un clip.',
    'mkv-to-mp4': 'MKV este excelent pentru păstrare, dar telefoanele, televizoarele, browserele şi majoritatea programelor de montaj nu îl redau — trecerea în MP4 este cea care face fişierul cu adevărat utilizabil.',
    'webm-to-mp4': 'Fişierele WebM salvate de pe web refuză adesea să se deschidă în QuickTime, pe iOS sau în Premiere; MP4 este formatul pe care îl acceptă toate.',
    'avi-to-mp4': 'Aceasta este salvarea standard pentru filmările vechi de cameră video şi clipurile arhivate care înghit gigaocteţi şi nu rulează pe niciun telefon.',
    'flv-to-mp4': 'Flash a dispărut din orice browser, aşa că orice FLV mai ai este practic imposibil de redat — trecerea în MP4 ţine acel material arhivat vizionabil.',
    'wmv-to-mp4': 'WMV este o rămăşiţă care trăieşte doar pe Windows, aşa că asta faci înainte să trimiţi o înregistrare veche sau o captură de ecran spre un Mac, un iPhone sau o platformă web.',
    'mp4-to-mp3': 'De obicei contează sunetul, nu imaginea — un curs, un interviu, un podcast sau un videoclip pe care îl vrei în telefon fără să cari şi imaginea după tine.',
    'video-to-mp3': 'Se apelează la asta când sunetul este partea care merită păstrată: o conferinţă înregistrată, un interviu, o repetiţie sau o coloană sonoră.',
    'mp4-converter': 'Aceasta este unealta pentru momentul în care un clip nu rulează sau nu se încarcă, fiindcă MP4 este singurul format video pe care telefoanele, browserele, televizoarele şi platformele sociale îl acceptă toate.',
    'video-converter': 'Foloseşte-o când un clip trebuie să schimbe lumea — să iasă dintr-un program de montaj, să ajungă pe un telefon, într-un browser sau pe o platformă care primeşte un singur container anume.',
    'mp3-to-wav': 'Motivul obişnuit este montajul: staţiile audio digitale, lanţurile de masterizare şi multe fluxuri audio pentru radio sau jocuri vor WAV necomprimat, ca să nu decodeze un fişier comprimat la fiecare operaţie în parte.',
    'wav-to-mp3': 'Înregistrările ies dintr-un reportofon de teren sau dintr-o staţie audio ca fişiere WAV enorme; MP3 le face destul de mici încât să le trimiţi, să le încarci sau să încapă în telefon.',
    'flac-to-mp3': 'O bibliotecă FLAC sună excelent acasă, dar sistemele audio auto, telefoanele mai vechi şi playerele ieftine o refuză adesea — MP3 este copia de compatibilitate pe care o iei cu tine.',
    'aac-to-mp3': 'Aici e vorba mai ales de compatibilitate: AAC vine din ecosistemul Apple şi din streaming, în timp ce playerele mai vechi, radiourile auto şi programele de DJ aşteaptă MP3.',
    'ogg-to-mp3': 'OGG apare în jocuri, pe Wikipedia şi în software-ul cu sursă deschisă, iar aproape niciunul dintre playerele obişnuite de pe un telefon sau din maşină nu îl deschide.',
    'wma-to-mp3': 'WMA este o relicvă a erei Windows Media Player, iar aşa se salvează o colecţie veche de muzică extrasă de pe CD-uri pentru un telefon sau o bibliotecă de streaming.',
    'm4a-to-mp3': 'Acesta este pasul obişnuit când muţi muzică sau memouri vocale de pe iPhone de pe dispozitivele Apple în programe, maşini sau playere care înţeleg doar MP3.',
    'mp3-to-aac': 'Unele dispozitive şi aplicaţii — mai ales din zona Apple şi a platformelor de streaming — preferă AAC, aşa că aceasta este o conversie de compatibilitate, nu o îmbunătăţire a calităţii.',
    'mp3-to-ogg': 'Se trece în OGG pentru motoare de joc, proiecte cu sursă deschisă şi platforme unde se cere un codec liber de brevete.',
    'audio-converter': 'Aceasta este unealta pentru clipa în care un fişier nu rulează: un singur loc în care duci sunetul exact în acel format obişnuit pe care îl cere dispozitivul tău, programul tău de montaj sau formularul tău de încărcare.',
    'rar-to-zip': 'RAR are nevoie de software suplimentar ca să fie deschis, aşa că asta faci înainte să trimiţi o arhivă cuiva care nu are de gând să instaleze WinRAR.',
    '7z-to-zip': '7Z comprimă mai bine, dar cere 7-Zip instalat; sub formă de ZIP, destinatarul poate pur şi simplu să dea dublu clic pe fişier.',
    'tar-to-zip': 'TAR vine din linia de comandă a Linux şi macOS, în timp ce ZIP este ce poate deschide un coleg pe Windows fără să instaleze absolut nimic.',
    'gz-to-zip': 'Fişierele GZ vin de obicei de pe un server sau dintr-o unealtă Linux şi sunt incomode pe Windows, unde un ZIP se dezarhivează cu un dublu clic.',
    'zip-to-7z': 'Aici este vorba de dimensiune: compresia 7Z este vizibil mai puternică, ceea ce contează când arhivezi un dosar mare sau plăteşti stocarea în cloud la gigaoctet.',
    'video-to-gif': 'Folosinţa tipică este o buclă scurtă pentru un mesaj de chat, un README, un raport de eroare sau o postare — locuri unde un GIF porneşte singur, încorporat, iar un fişier video nu.',
    'mp4-to-gif': 'Folosinţa tipică este o buclă scurtă pentru un chat, un README, un raport de eroare sau o postare, unde un GIF porneşte singur, încorporat, în timp ce un videoclip ar sta acolo ca un simplu ataşament.',
    'webm-to-gif': 'Clipurile WebM salvate de pe web adesea nu se pot încorpora unde ai vrea, în timp ce un GIF porneşte încorporat în aplicaţiile de chat, în sistemele de tichete şi pe forumuri.',
    'mov-to-gif': 'Asta faci cu o înregistrare de ecran QuickTime care trebuie să apară încorporată într-un pull request, într-un tichet de asistenţă sau într-o postare.',
    'avi-to-gif': 'Transformarea câtorva secunde dintr-un clip AVI vechi într-un GIF este cel mai simplu mod de a le duce într-un document, într-un fir de chat sau pe o pagină web.',
    'gif-to-mp4': 'GIF-urile lungi sunt enorme şi se redau sacadat; MP4 arată aceeaşi animaţie la o fracţiune din dimensiune, exact motivul pentru care platformele sociale le convertesc în culise.',
    'image-to-gif': 'Util când o platformă sau un sistem mai vechi aşteaptă explicit un GIF, ori când îţi trebuie un cadru fix în acelaşi format ca o serie de animaţii deja existentă.',
    'gif-compressor': 'GIF-urile animate se umflă repede, iar aceasta este soluţia când unul este prea greu pentru un e-mail, pentru limita de încărcare dintr-un chat sau pentru o pagină care trebuie să se încarce rapid.',
    'merge-pdf': 'Cazul clasic este o cerere sau o notificare de daună: un formular, o scanare şi o chitanţă care trebuie să ajungă toate ca un singur document.',
    'split-pdf': 'De obicei îţi trebuie exact un lucru dintr-un fişier mult mai lung — un capitol, o factură, o pagină semnată dintr-o scanare de cincizeci de pagini.',
    'compress-pdf': 'Aproape întotdeauna o limită de dimensiune: un plafon pentru ataşamentele de e-mail, un formular al administraţiei sau un portal care respinge orice depăşeşte câţiva megaocteţi.',
    'rotate-pdf': 'Asta rezolvă problema de zi cu zi a scanerului — pagini ieşite pe lat sau cu susul în jos din cauza felului în care au fost introduse colile.',
    'protect-pdf': 'PDF-urile se protejează cu parolă înainte de a trimite fluturaşi de salariu, contracte sau scrisori medicale, ca să nu fie citite de cel căruia i se va redirecţiona mesajul mai departe.',
    'unlock-pdf': 'Foloseşte-o pe documente care îţi aparţin când parola este cunoscută, dar restricţia stă în cale — un extras de cont pe care nu îl poţi tipări, de exemplu.',
    'view-metadata': 'Răspunde la întrebările pe care un fişier nu ţi le spune direct: ce aparat a făcut fotografia asta, cât durează de fapt înregistrarea asta, ce codec se află în videoclipul ăsta, câte pagini are PDF-ul ăsta.',
    'ocr': 'Situaţia este mereu aceeaşi: ai un document ca imagine şi îţi trebuie cuvintele din el — ca să cauţi prin ele, să le citezi, să le editezi sau să le arhivezi cum trebuie.',
    'pdf-compress-ai': 'Apelează la ea când compresia obişnuită a fost deja încercată, iar fişierul e tot prea mare pentru limita de încărcare cu care te lupţi.',
    'text-to-speech': 'Se foloseşte ca să asculţi ceva în loc să citeşti — un articol în drum spre serviciu, un scenariu citit cu voce tare ca să prinzi formulările stângace, sau o voce din off pentru un videoclip.',
    'speech-to-text': 'Cazul obişnuit este o înregistrare de care ai nevoie în scris: o şedinţă, un interviu, un curs sau un memo vocal care trebuie să devină notiţe, un proces-verbal ori o transcriere citabilă.',
    'auto-subtitle': 'Subtitrările sunt ceea ce face un videoclip vizionabil fără sunet şi găsibil de motoarele de căutare, iar scrierea lor de mână ia, chiar şi pentru un clip scurt, mult mai mult timp decât se aşteaptă lumea.',
    'document-translation': 'Scopul este să citeşti sau să trimiţi un document în altă limbă fără să pierzi aşezarea în pagină care îl face lizibil.',
  },
  t: {
    'list.and': 'şi',
    'family.document': 'documente',
    'family.image': 'imagini',
    'family.video': 'video',
    'family.audio': 'audio',
    'family.ebook': 'cărţi electronice',
    'family.archive': 'arhive',
    'family.subtitle': 'subtitrări',
    'family.none': 'fişiere',
    'unit.sample': 'fiecare eşantion',
    'unit.pixel': 'fiecare pixel',

    'intro.convert': '{{fromAbout}} {{toAbout}} {{reason}} {{toNote}}',
    'intro.convert.noSource': '{{fn}} este formatul-sursă al acestei conversii.',
    'intro.lead': '{{lead}} {{reason}}',
    'intro.hub': 'Acesta este convertorul general de {{category}}: primeşte {{inputs}} şi scrie {{outputs}}, aşa că nu trebuie să vânezi unealta anume care se potriveşte perechii tale de formate. {{reason}} Alege mai sus formatul de ieşire — conversia se face pe server, nu ai nimic de instalat.',
    'intro.hubExtract': 'Unealta aceasta scoate pista audio dintr-un fişier video şi o salvează separat, transformând un videoclip într-un simplu fişier audio care rulează oriunde. Primeşte {{inputs}} şi scrie {{outputs}}. Pista video este pur şi simplu aruncată, şi de aceea rezultatul este o fracţiune din dimensiunea originală. {{reason}}',
    'intro.hubGif': 'Unealta aceasta transformă fişierele {{inputs}} în GIF-uri animate. {{gifAbout}} {{reason}}',
    'intro.hubGif.gifAbout': 'GIF este limitat la o paletă de 256 de culori pe cadru, motiv pentru care fotografiile apar cu benzi în el, dar se animă şi porneşte singur, încorporat, aproape peste tot pe internet.',
    'intro.compress': '{{about}} Unealta aceasta îţi recodează fişierul {{fn}} la o dimensiune mai mică fără să schimbe formatul, aşa că ce descarci este tot un {{fn}} obişnuit, care se deschide exact acolo unde se deschidea originalul. {{reason}}{{extra}}',
    'intro.compress.lossless': ' Fiindcă {{fn}} este fără pierderi, cea mai mare parte a economiei vine dintr-o codare mai inteligentă şi dintr-o paletă redusă, nu din aruncarea detaliilor.',
    'intro.soon': '{{reason}} Unealta aceasta nu este încă activă — se construieşte chiar acum şi va apărea aici de îndată ce va fi gata.',
    'intro.lead.pdf-merge': 'Îmbinarea uneşte mai multe PDF-uri într-un singur fişier, în ordinea aleasă de tine, fără să reproceseze paginile — textul rămâne selectabil, iar imaginile îşi păstrează calitatea originală. PDF este un format cu aşezare fixă în pagină: reţine poziţia exactă a fiecărui caracter, a fiecărei linii şi a fiecărei imagini, motiv pentru care arată identic peste tot, dar se editează greu.',
    'intro.lead.pdf-split': 'Împărţirea scoate din PDF paginile pe care le indici şi le salvează ca document nou, lăsând originalul neatins. PDF este un format cu aşezare fixă în pagină: reţine poziţia exactă a fiecărui caracter, a fiecărei linii şi a fiecărei imagini, motiv pentru care arată identic peste tot, dar se editează greu.',
    'intro.lead.pdf-compress': 'Comprimarea unui PDF recodează imaginile dinăuntru şi curăţă datele încorporate redundante, acolo unde stă de fapt aproape toată dimensiunea unui PDF mare. Textul şi grafica vectorială rămân clare.',
    'intro.lead.pdf-compress-ai': 'Unealta aceasta analizează ce se află în PDF înainte să comprime, aşa că imaginile fotografice, grafica plată şi paginile doar cu text sunt tratate fiecare în felul care economiseşte cel mai mult spaţiu fără să le degradeze vizibil.',
    'intro.lead.pdf-rotate': 'Rotirea schimbă marcajul de orientare şi geometria paginilor dintr-un PDF, ca paginile să se afişeze şi să se tipărească în poziţia corectă. Nu se reprocesează nimic, aşa că nu se pierde calitate.',
    'intro.lead.pdf-protect': 'Protejarea unui PDF îi criptează conţinutul, ca să nu poată fi deschis fără parola pe care o stabileşti. Criptarea se aplică fişierului în sine, nu unui înveliş din jurul lui.',
    'intro.lead.pdf-unlock': 'Deblocarea înlătură parola şi restricţiile de utilizare dintr-un PDF a cărui parolă o ai deja, ca să poată fi din nou deschis, tipărit şi copiat normal.',
    'intro.lead.metadata': 'Orice fişier poartă cu el informaţii despre sine care nu se văd când îl deschizi: dimensiunile imaginii şi setările aparatului, durata şi debitul sunetului, codecul şi cadenţa videoclipului, autorul şi numărul de pagini ale documentului. Unealta aceasta citeşte acele metadate şi ţi le arată.',
    'intro.lead.ocr': 'Recunoaşterea optică a caracterelor se uită la o imagine cu text — o scanare, o fotografie, o pagină PDF fără strat de text — şi deduce ce caractere sunt, transformând o poză cu cuvinte în cuvinte prin care un calculator poate căuta, pe care le poate copia şi edita.',
    'intro.lead.tts': 'Conversia textului în vorbire generează sunet vorbit din text scris folosind voci neurale, aşa că obţii o înregistrare cu sonoritate naturală în locul ieşirii robotice şi plate a sistemelor mai vechi.',
    'intro.lead.stt': 'Conversia vorbirii în text transcrie sunetul vorbit în cuvinte. Se descurcă cu vorbirea naturală, cu accentele şi cu zgomotul de fond mult mai bine decât o făceau programele de dictare de altădată şi returnează o transcriere pe care o poţi edita.',
    'intro.lead.subtitle': 'Generatorul de subtitrări transcrie vorbirea dintr-un videoclip şi o scrie cu coduri de timp, obţinând un fişier de subtitrare standard, nu o simplă transcriere.',

    'steps.convert.1.batch': 'Trage fişierul tău {{fn}} în zona de încărcare din partea de sus a acestei pagini sau dă clic pe ea ca să răsfoieşti dispozitivul. Poţi adăuga mai multe fişiere — sau un dosar întreg — şi să le converteşti pe toate deodată.',
    'steps.convert.1.single': 'Trage fişierul tău {{fn}} în zona de încărcare din partea de sus a acestei pagini sau dă clic pe ea ca să răsfoieşti dispozitivul.',
    'steps.convert.2.direct': 'Alege {{tn}} ca format de ieşire şi dă clic pe Convertire.',
    'steps.convert.2.dropdown': 'Alege {{tn}} ca format de ieşire din lista derulantă şi dă clic pe Convertire.',
    'steps.convert.2.directMedia': 'Alege {{tn}} ca format de ieşire, ajustează la nevoie calitatea sau dimensiunea din setările avansate şi dă clic pe Convertire.',
    'steps.convert.2.dropdownMedia': 'Alege {{tn}} ca format de ieşire din lista derulantă, ajustează la nevoie calitatea sau dimensiunea din setările avansate şi dă clic pe Convertire.',
    'steps.convert.3': 'Descarcă fişierul {{tn}} finalizat. Legătura de descărcare rămâne activă 24 de ore, după care ambele fişiere sunt şterse automat.',
    'steps.hub.1.batch': 'Trage fişierul tău în zona de încărcare din partea de sus a acestei pagini sau dă clic pe ea ca să răsfoieşti dispozitivul — convertorul de {{category}} primeşte {{inputs}}. Poţi adăuga mai multe fişiere — sau un dosar întreg — şi să le converteşti pe toate deodată.',
    'steps.hub.1.single': 'Trage fişierul tău în zona de încărcare din partea de sus a acestei pagini sau dă clic pe ea ca să răsfoieşti dispozitivul — convertorul de {{category}} primeşte {{inputs}}.',
    'steps.hub.2.direct': 'Alege formatul de ieşire de care ai nevoie şi dă clic pe Convertire.',
    'steps.hub.2.dropdown': 'Alege din lista derulantă formatul de ieşire de care ai nevoie şi dă clic pe Convertire.',
    'steps.hub.2.directMedia': 'Alege formatul de ieşire de care ai nevoie, ajustează la nevoie calitatea sau dimensiunea din setările avansate şi dă clic pe Convertire.',
    'steps.hub.2.dropdownMedia': 'Alege din lista derulantă formatul de ieşire de care ai nevoie, ajustează la nevoie calitatea sau dimensiunea din setările avansate şi dă clic pe Convertire.',
    'steps.hub.3': 'Descarcă fişierul finalizat. Legătura de descărcare rămâne activă 24 de ore, după care ambele fişiere sunt şterse automat.',
    'steps.pdf-merge.1': 'Adaugă fiecare PDF pe care vrei să îl combini — trage-le împreună în zona de încărcare sau dă clic ca să le selectezi unul câte unul.',
    'steps.pdf-merge.2': 'Trage fişierele în ordinea în care vrei să apară în documentul final.',
    'steps.pdf-merge.3': 'Dă clic pe Îmbinare şi descarcă singurul PDF combinat.',
    'steps.pdf-split.1': 'Încarcă PDF-ul din care vrei să scoţi pagini.',
    'steps.pdf-split.2': 'Scrie paginile sau intervalele de care ai nevoie în câmpul pentru intervale de pagini — de exemplu 1-3, 5, 7-10.',
    'steps.pdf-split.3': 'Dă clic pe Convertire şi descarcă paginile extrase.',
    'steps.pdf-compress.1': 'Trage PDF-ul în zona de încărcare sau dă clic ca să îl cauţi.',
    'steps.pdf-compress.2': 'Dă clic pe Convertire — fişierul este analizat, iar imaginile şi datele lui încorporate sunt recodate la o dimensiune mai mică.',
    'steps.pdf-compress.3': 'Descarcă PDF-ul comprimat şi verifică economia de dimensiune afişată alături.',
    'steps.pdf-rotate.1': 'Încarcă PDF-ul ale cărui pagini stau invers.',
    'steps.pdf-rotate.2': 'Alege cât să fie rotite — 90°, 180° sau 270°.',
    'steps.pdf-rotate.3': 'Dă clic pe Convertire şi descarcă PDF-ul corectat.',
    'steps.pdf-protect.1': 'Încarcă PDF-ul pe care vrei să îl securizezi.',
    'steps.pdf-protect.2': 'Introdu parola care va fi cerută pentru a-l deschide şi păstrează o copie într-un loc sigur.',
    'steps.pdf-protect.3': 'Dă clic pe Convertire şi descarcă PDF-ul criptat.',
    'steps.pdf-unlock.1': 'Încarcă PDF-ul protejat cu parolă.',
    'steps.pdf-unlock.2': 'Introdu parola lui curentă, ca fişierul să poată fi decriptat.',
    'steps.pdf-unlock.3': 'Dă clic pe Convertire şi descarcă PDF-ul deblocat.',
    'steps.metadata.1': 'Trage orice fişier în zona de încărcare — o imagine, un videoclip, un fişier audio sau un document.',
    'steps.metadata.2': 'Fişierul este examinat, nu convertit, aşa că nu i se schimbă nimic.',
    'steps.metadata.3': 'Citeşte metadatele direct în pagină: dimensiuni, durată, codec, detalii despre aparatul foto, număr de pagini şi altele.',
    'steps.ocr.1': 'Încarcă PDF-ul scanat sau fotografia textului.',
    'steps.ocr.2': 'Alege limba documentului şi dacă vrei un PDF în care se poate căuta ori text simplu.',
    'steps.ocr.3': 'Dă clic pe Convertire şi descarcă rezultatul, în care textul recunoscut poate fi acum selectat şi căutat.',
    'steps.tts.1': 'Scrie sau lipeşte textul în casetă — până la 4096 de caractere pe conversie.',
    'steps.tts.2': 'Alege o voce, o viteză de vorbire şi un format de ieşire.',
    'steps.tts.3': 'Dă clic pe Convertire şi descarcă fişierul audio finalizat.',
    'steps.stt.1': 'Încarcă înregistrarea ta sau înregistrează direct de la microfon cu butonul din pagină.',
    'steps.stt.2': 'Opţional, indică limba vorbită pentru mai multă precizie şi alege ieşirea TXT sau DOCX.',
    'steps.stt.3': 'Dă clic pe Convertire, citeşte transcrierea în pagină, apoi descarc-o.',
    'steps.subtitle.1': 'Încarcă videoclipul pe care vrei să îl subtitrezi.',
    'steps.subtitle.2': 'Alege SRT sau VTT şi indică limba vorbită dacă o cunoşti.',
    'steps.subtitle.3': 'Dă clic pe Convertire şi descarcă fişierul de subtitrare cu coduri de timp, gata de pus în playerul sau în programul tău de montaj.',
    'steps.compress.1': 'Trage imaginile tale {{fn}} în zona de încărcare sau dă clic ca să răsfoieşti. Poţi adăuga un dosar întreg deodată.',
    'steps.compress.1.gif': 'Trage animaţia ta {{fn}} în zona de încărcare sau dă clic ca să răsfoieşti. Poţi adăuga un dosar întreg deodată.',
    'steps.compress.2': 'Dă clic pe Convertire — fişierul este recodat la o dimensiune mai mică rămânând în acelaşi format.',
    'steps.compress.3': 'Descarcă rezultatul şi compară-l cu dimensiunea originală afişată în pagină.',
    'steps.soon.1': 'Alege unealta de care ai nevoie din pagina de unelte — tot în afară de aceasta funcţionează deja astăzi.',
    'steps.soon.2': 'Încarcă fişierul şi alege un format de ieşire.',
    'steps.soon.3': 'Descarcă rezultatul sau treci din nou pe aici când traducerea documentelor va porni.',

    'faq.cost.q.pair': 'Este gratuită conversia din {{from}} în {{to}}?',
    'faq.cost.q.tool': 'Este {{label}} gratuit?',
    'faq.cost.a.pair': 'Conturile noi primesc un credit de conversie gratuit, aşa că prima ta conversie din {{from}} în {{to}} nu costă nimic. După aceea, fiecare conversie foloseşte un credit dintr-un pachet mic preplătit — nu există abonament, creditele nu expiră niciodată, iar o conversie eşuată nu se taxează.',
    'faq.cost.a.tool': 'Conturile noi primesc un credit de conversie gratuit, aşa că primul tău fişier nu costă nimic. După aceea, fiecare conversie foloseşte un credit dintr-un pachet mic preplătit — nu există abonament, creditele nu expiră niciodată, iar o conversie eşuată nu se taxează.',
    'faq.cost.a.smartTts': 'Conturile noi primesc un credit de conversie gratuit ca să încerci, iar funcţiile inteligente se taxează după consum, nu pe fişier — 1 credit la fiecare 1000 de caractere de text, rotunjit în sus. Fără abonament: creditele se cumpără în pachete mici preplătite, nu expiră niciodată, iar o conversie eşuată nu costă nimic.',
    'faq.cost.a.smartAv': 'Conturile noi primesc un credit de conversie gratuit ca să încerci, iar funcţiile inteligente se taxează după consum, nu pe fişier — 1 credit la fiecare 5 minute de sunet sau video, rotunjit în sus. Fără abonament: creditele se cumpără în pachete mici preplătite, nu expiră niciodată, iar o conversie eşuată nu costă nimic.',
    'faq.cost.q.metadata': 'Este gratuită unealta Informaţii fişier?',
    'faq.cost.a.metadata': 'Da. Citirea metadatelor unui fişier nu este o conversie, aşa că nu consumă niciun credit — poţi examina câte fişiere vrei. Creditele se cheltuiesc doar când o unealtă produce cu adevărat un fişier nou pentru tine.',
    'faq.cost.q.soon': 'Este {{label}} deja disponibil?',
    'faq.cost.a.soon': 'Încă nu — pagina aceasta este un loc rezervat cât timp unealta se construieşte, aşa că azi nu ai ce încărca aici. Preţul va urma acelaşi model de credite preplătite ca restul site-ului: fără abonament, cu credite care nu expiră niciodată şi fără taxă pentru o conversie eşuată.',

    'faq.time.q.pair': 'Cât durează conversia din {{from}} în {{to}}?',
    'faq.time.q.tool': 'Cât durează {{label}}?',
    'faq.time.a': '{{speed}} De obicei viteza de încărcare este factorul limitativ, aşa că un fişier mare pe o conexiune lentă ia mai mult timp decât conversia în sine.{{suffix}}',
    'faq.time.speed.image': 'Imaginile sunt cel mai rapid lucru pe care îl convertim — o singură fotografie este gata în mod normal în sub cinci secunde, iar un dosar întreg ia cam cât încărcarea propriu-zisă.',
    'faq.time.speed.document': 'Majoritatea documentelor sunt gata în câteva secunde. Fişierele foarte lungi — câteva sute de pagini sau o scanare plină de imagini — pot ajunge la un minut.',
    'faq.time.speed.audio': 'O piesă obişnuită se converteşte în câteva secunde. O înregistrare completă, cum ar fi un curs sau un episod de podcast, ia de regulă mult sub un minut, iar cea mai mare parte este încărcarea.',
    'faq.time.speed.video': 'Videoul este categoria cea mai lentă fiindcă fiecare cadru trebuie recodat. Un clip scurt ia secunde, în timp ce un fişier lung la rezoluţie mare poate lua câteva minute.',
    'faq.time.speed.archive': 'Arhivele se convertesc în secunde, deşi una mare durează mai mult, fiindcă fiecare fişier dinăuntru trebuie dezarhivat şi rearhivat.',
    'faq.time.speed.ebook': 'Cărţile electronice merg repede — un roman întreg se converteşte în mod normal în câteva secunde.',
    'faq.time.speed.subtitle': 'Transcrierea avansează cu circa câteva secunde pe minut de sunet, aşa că un videoclip de zece minute este de obicei subtitrat în mult sub un minut.',
    'faq.time.suffix.standard': ' Se acceptă fişiere de până la 200 MB.',
    'faq.time.suffix.smart': ' Funcţiile inteligente acceptă fişiere de până la 25 MB; conversiile obişnuite până la 200 MB.',
    'faq.time.q.metadata': 'Cât durează citirea metadatelor unui fişier?',
    'faq.time.a.metadata': 'O secundă sau două, odată ce fişierul s-a încărcat. Nu se converteşte şi nu se recodează nimic — antetele sunt analizate, iar rezultatul este scris direct în pagină — aşa că aşteptarea este practic doar încărcarea.',
    'faq.time.q.soon': 'Va costa în plus?',
    'faq.time.a.soon': 'Va folosi aceleaşi credite ca tot restul site-ului. Nu există un plan sau un abonament separat la care să te înscrii, iar creditele pe care le ai deja în cont vor funcţiona cu ea din clipa în care porneşte.',

    'faq.safety.q.pair': 'Este sigur să încarc fişierul meu {{from}}?',
    'faq.safety.q.tool': 'Este fişierul meu în siguranţă?',
    'faq.safety.a.pair': 'Fişierele călătoresc printr-o conexiune TLS criptată şi nu sunt folosite pentru nimic altceva decât conversia pe care ai cerut-o. Atât fişierul tău {{from}} original, cât şi fişierul {{to}} pe care ţi-l înapoiem sunt şterse automat în 24 de ore — definitiv şi fără să se păstreze copii de rezervă — iar conţinutul nu este niciodată citit, analizat sau partajat. Serviciul este operat din Germania, sub GDPR.',
    'faq.safety.a.tool': 'Fişierele călătoresc printr-o conexiune TLS criptată şi nu sunt folosite pentru nimic altceva decât conversia pe care ai cerut-o. Atât fişierul tău original, cât şi rezultatul pe care ţi-l înapoiem sunt şterse automat în 24 de ore — definitiv şi fără să se păstreze copii de rezervă — iar conţinutul nu este niciodată citit, analizat sau partajat. Serviciul este operat din Germania, sub GDPR.',

    'quality.vectorRaster.q': 'Va rămâne {{fn}}-ul meu clar ca {{tn}}?',
    'quality.vectorRaster.a': 'Până la dimensiunea la care îl exporţi, da. {{fn}} reţine forme, nu pixeli, aşa că se scalează la nesfârşit, dar un {{tn}} este o grilă fixă de pixeli şi va deveni neclar dacă este mărit ulterior dincolo de acea grilă. Setează în setările avansate lăţimea şi înălţimea de care ai cu adevărat nevoie înainte de conversie — exportul la de două sau de trei ori dimensiunea de afişare este trucul obişnuit pentru ecranele cu densitate mare de pixeli. Păstrează fişierul {{fn}} original: rămâne copia-etalon din care poţi exporta din nou la orice rezoluţie.',
    'quality.docToTxt.q': 'Pierd formatarea când convertesc {{fn}} în {{tn}}?',
    'quality.docToTxt.a': 'Da, şi în mod intenţionat — un fişier {{tn}} conţine caractere şi nimic altceva. Fonturile, culorile, imaginile, tabelele, coloanele şi sfârşiturile de pagină dispar toate; înapoi primeşti textul lizibil al documentului în ordinea de citire. Exact asta vrei ca să cauţi, ca să scrii scripturi sau ca să dai textul altui program, şi exact asta nu vrei dacă sperai să păstrezi designul. Atenţie: un {{fn}} care este de fapt o imagine scanată nu conţine deloc text de extras — trece-l mai bine prin unealta OCR.',
    'quality.docToSheet.q': 'Cât de exact se extrag tabelele dintr-un {{fn}}?',
    'quality.docToSheet.a': 'Tabelele curate, cu linii şi coloane uniforme — extrase de cont, facturi, rapoarte exportate — trec fiabil, iar fiecare valoare ajunge în propria celulă, ca să o poţi însuma şi sorta. Tabelele fără chenare vizibile, celulele întinse pe mai multe rânduri sau cifrele tăiate de un sfârşit de pagină sunt cazurile pe care merită să le verifici cu ochiul după aceea. {{fn}} reţine poziţii, nu structură de tabel, aşa că mai departe conversia trebuie să deducă unde se termină o coloană şi începe următoarea.',
    'quality.docToReflow.q': 'Supravieţuieşte aşezarea în pagină conversiei din {{fn}} în {{tn}}?',
    'quality.docToReflow.a': 'Nu chiar, şi tocmai asta e ideea. {{fn}} ţintuieşte textul la coordonate fixe de pagină; {{tn}} îl lasă să curgă din nou după ecranul şi mărimea de font ale cititorului, aşa că numerele fixe de pagină, antetele, subsolurile şi aşezările pe mai multe coloane sunt reinterpretate, nu reproduse. Textul de bază, titlurile, ordinea paragrafelor şi imaginile trec bine. Documentele alcătuite mai ales din proză se convertesc splendid; paginile lucrate grafic, formularele şi tabelele complexe sunt cele la care merită să te uiţi după aceea.',
    'quality.docToFixed.q': 'Îmi va fi păstrată formatarea în {{tn}}?',
    'quality.docToFixed.a': 'Da — direcţia aceasta este cea sigură. {{tn}} înregistrează pagina aşa cum a fost în final randată, aşa că fonturile, spaţierile, tabelele, imaginile şi sfârşiturile de pagină sunt îngheţate exact aşa cum au fost aşezate şi vor arăta la fel pe orice dispozitiv şi la orice imprimantă. Acesta este şi compromisul: rezultatul nu mai poate fi editat liber, ceea ce este de obicei chiar motivul pentru care un document este trecut în {{tn}} înainte de a fi trimis.',
    'quality.docToEditable.q': 'Cât de exactă este conversia din {{fn}} în {{tn}}?',
    'quality.docToEditable.a': 'Textul, titlurile, listele, imaginile şi tabelele simple trec fiabil şi rămân pe deplin editabile. Fiindcă {{fn}} reţine poziţii, nu structură, conversia trebuie să reconstruiască acea structură, aşa că paginile lucrate grafic — mai multe coloane, text care înconjoară imagini, tabele imbricate complexe — pot avea nevoie de o mică ordonare după aceea. Dacă PDF-ul este o scanare complet fără strat de text, foloseşte mai bine unealta OCR: recunoaşte caracterele din imagine în loc să caute un text care nu există.',
    'quality.docGeneric.q': 'Pierd ceva când convertesc {{fn}} în {{tn}}?',
    'quality.docGeneric.a': 'Cuvintele, titlurile, listele şi imaginile trec neatinse. {{tn}} are un vocabular de formatare diferit de {{fn}}, aşa că un stil foarte specific poate fi simplificat pe drum, dar conţinutul în sine se păstrează.',
    'quality.archive.q': 'Vor fi modificate fişierele din arhiva mea {{fn}}?',
    'quality.archive.a': 'Nu. Formatele de arhivă sunt containere fără pierderi: {{fn}} este dezarhivat, iar aceleaşi fişiere sunt rearhivate ca {{tn}}, octet cu octet. Se schimbă doar metoda de compresie şi containerul. Ce se schimbă însă este dimensiunea arhivei în sine — {{clause}}.',
    'quality.archive.clause.to7z': '7Z produce în general o arhivă mai mică decât ZIP, graţie compresiei LZMA',
    'quality.archive.clause.toZip': 'ZIP iese de obicei puţin mai mare decât 7Z sau RAR, iar acesta este preţul pentru a putea fi deschis oriunde fără software suplimentar',
    'quality.archive.clause.other': 'noul format comprimă altfel, aşa că dimensiunea fişierului se poate deplasa în oricare dintre sensuri',
    'quality.imageToDoc.q': 'Îşi vor pierde pozele mele din calitate în interiorul {{tn}}?',
    'quality.imageToDoc.a': 'Nu. Fiecare imagine {{fn}} este aşezată în {{tn}} aşa cum este, câte una pe pagină, fără să fie recomprimată, aşa că ce vezi în document este ce a ieşit din aparat. {{tn}} va cântări aproximativ cât toate imaginile la un loc, ceea ce merită ştiut înainte să îl trimiţi pe e-mail — trece rezultatul prin Comprimare PDF dacă trebuie să fie mai mic.',
    'quality.toGif.q': 'De ce arată GIF-ul meu mai prost decât {{fn}}-ul original?',
    'quality.toGif.a': 'Fiindcă GIF este limitat la 256 de culori pe cadru. Un videoclip sau o fotografie conţin milioane, aşa că codorul trebuie să aleagă o paletă şi să aproximeze tot restul, ceea ce se vede ca benzi în degradeuri şi pe cer. GIF nu poartă, în plus, nicio pistă audio. Ambele ţin de format, nu de conversie — ţine clipul scurt, iar dacă pierderea de culoare atârnă mai greu decât redarea automată încorporată, un MP4 va arăta mult mai bine la o dimensiune mai mică.',
    'quality.lossyToLossless.q': 'Se îmbunătăţeşte calitatea prin conversia {{fn}} în {{tn}}?',
    'quality.lossyToLossless.a': 'Nu — şi aceasta este de departe cea mai răspândită neînţelegere despre conversia asta. {{fn}} este cu pierderi: detaliile pe care codorul lui le-a aruncat s-au dus definitiv şi nimic nu le poate reconstrui. Ce îţi dă {{tn}} este un container fără pierderi pentru ce a rămas, aşa că fişierul încetează să se degradeze la fiecare salvare sau editare ulterioară. Este cu adevărat util când urmează să {{clause}}, dar nu va recupera o calitate deja pierdută.',
    'quality.lossyToLossless.edit.audio': 'editezi, masterizezi sau prelucrezi sunetul',
    'quality.lossyToLossless.edit.image': 'editezi, retuşezi sau compui imaginea',
    'quality.losslessToLossy.q': 'Pierd calitate când convertesc {{fn}} în {{tn}}?',
    'quality.losslessToLossy.a.audio': 'Ceva, şi în mod deliberat — aşa se micşorează fişierul. {{tn}} este cu pierderi, aşa că codorul aruncă informaţia pe care o consideră cel mai puţin sesizabilă. La setări rezonabile diferenţa este foarte greu de prins cu urechea, iar în setările avansate poţi urca debitul dacă preferi să dai dimensiune pentru fidelitate. Păstrează fişierul {{fn}} original: rămâne copia-etalon, iar recodarea ulterioară a {{tn}} ar adânci pierderea.',
    'quality.losslessToLossy.a.visual': 'Ceva, şi în mod deliberat — aşa se micşorează fişierul. {{tn}} este cu pierderi, aşa că codorul aruncă informaţia pe care o consideră cel mai puţin sesizabilă. La setări rezonabile diferenţa este foarte greu de prins cu ochiul, iar în setările avansate poţi urca valoarea calităţii dacă preferi să dai dimensiune pentru fidelitate. Păstrează fişierul {{fn}} original: rămâne copia-etalon, iar recodarea ulterioară a {{tn}} ar adânci pierderea.',
    'quality.lossyToLossy.q': 'Pierd calitate când convertesc {{fn}} în {{tn}}?',
    'quality.lossyToLossy.a.audio': 'Puţin. Ambele formate sunt cu pierderi, aşa că {{fn}} este decodat şi apoi recodat ca {{tn}}, iar fiecare generaţie de codare cu pierderi lasă să cadă o cantitate mică de detaliu. La setări normale nu este ceva ce observă majoritatea la ascultare, iar în setările avansate poţi urca debitul. Ce ar trebui să eviţi este să converteşti acelaşi fişier înainte şi înapoi în mod repetat — asta face pierderea audibilă.',
    'quality.lossyToLossy.a.visual': 'Puţin. Ambele formate sunt cu pierderi, aşa că {{fn}} este decodat şi apoi recodat ca {{tn}}, iar fiecare generaţie de codare cu pierderi lasă să cadă o cantitate mică de detaliu. La setări normale nu este ceva ce observă majoritatea, iar în setările avansate poţi urca calitatea. Ce ar trebui să eviţi este să converteşti acelaşi fişier înainte şi înapoi în mod repetat — asta face pierderea vizibilă.',
    'quality.losslessToLossless.q': 'Pierd calitate când convertesc {{fn}} în {{tn}}?',
    'quality.losslessToLossless.a.plain': 'Nu. Şi {{fn}}, şi {{tn}} sunt fără pierderi, aşa că {{unit}} este păstrat exact, iar rezultatul este identic cu originalul. Se schimbă doar dimensiunea fişierului. Poţi converti înapoi mai târziu fără nicio degradare.',
    'quality.losslessToLossless.a.bulky': 'Nu. Şi {{fn}}, şi {{tn}} sunt fără pierderi, aşa că {{unit}} este păstrat exact, iar rezultatul este identic cu originalul. Se schimbă doar dimensiunea fişierului, de regulă dramatic în jos, fiindcă {{fn}} îşi reţine datele practic necomprimate. Poţi converti înapoi mai târziu fără nicio degradare.',
    'quality.fallback.q': 'Pierd calitate când convertesc {{fn}} în {{tn}}?',
    'quality.fallback.a': 'Pentru fişiere obişnuite, rezultatul este echivalent vizual şi funcţional cu originalul. Acolo unde cele două formate acceptă lucruri diferite, conversia păstrează tot ce {{tn}} este capabil să reprezinte. Setările avansate îţi permit să urci calitatea dacă compromisul implicit nu este cel pe care îl vrei.',

    'relation.uncompressed.q': 'De ce este fişierul {{tn}} atât de mult mai mare decât {{fn}}?',
    'relation.uncompressed.a': 'Fiindcă {{tn}} este necomprimat. {{fn}} micşorează sunetul aruncând date şi codând eficient ce rămâne; {{tn}} scrie fiecare eşantion la dimensiune completă, ceea ce iese la circa 10 MB pe minut de stereo la calitate CD. O creştere de zece ori este normală şi de aşteptat — este preţul unui fişier pe care programele de montaj îl pot prelucra fără să decodeze mai întâi nimic. Dacă vrei sunet fără pierderi la aproximativ jumătate din dimensiune, converteşte-l mai bine în FLAC.',
    'relation.extractAudio.q': 'Păstrează asta videoclipul sau doar sunetul?',
    'relation.extractAudio.a': 'Doar sunetul. Pista audio este extrasă din fişierul {{fn}} şi salvată ca {{tn}}; pista video este aruncată, şi de aceea rezultatul este o fracţiune din dimensiunea originală. Sunetul în sine nu este reînregistrat, aşa că îşi păstrează calitatea pe care o avea în interiorul {{fn}} — extragerea dintr-un videoclip cu debit mic nu poate produce sunet cu debit mare.',
    'relation.videoContainer.q': 'Va rula {{tn}}-ul meu pe telefoane, televizoare şi în reţelele sociale?',
    'relation.videoContainer.a.mp4': 'Exact pentru asta este conversia aceasta. MP4 cu video H.264 este cel mai aproape de un format video universal: iPhone, telefoanele Android, televizoarele inteligente, orice browser, Instagram, YouTube, TikTok şi orice program de montaj de larg consum îl acceptă fără codecuri suplimentare. {{fn}} era formatul care îţi dădea bătăi de cap; MP4 este cel care nu îţi dă.',
    'relation.videoContainer.a.other': '{{tn}} este mai specializat decât MP4. {{note}} Dacă scopul tău este pur şi simplu „să ruleze peste tot”, MP4 este alegerea mai sigură — ia {{tn}} atunci când un anumit program sau aparat l-a cerut.',
    'relation.alphaLost.q': 'Ce se întâmplă cu transparenţa la conversia din {{fn}} în {{tn}}?',
    'relation.alphaLost.a': '{{tn}} nu are canal alfa, aşa că zonele transparente nu pot fi duse mai departe — sunt umplute cu un fundal uniform (alb, implicit) în timpul conversiei. Dacă fundalul transparent chiar lucrează în designul tău, converteşte mai bine în PNG sau WebP, care îl păstrează amândouă. Dacă imaginea este o fotografie fără pic de transparenţă, asta nu schimbă absolut nimic.',
    'relation.alphaGained.q': 'Face conversia din {{fn}} în {{tn}} fundalul transparent?',
    'relation.alphaGained.a': 'Nu — şi mulţi se lasă păcăliţi aici. {{tn}} acceptă transparenţă, dar un fişier {{fn}} nu are nicio informaţie de transparenţă de dus mai departe, aşa că fundalul rămâne exact cum era. Ce îţi dă conversia este un fişier capabil să poarte transparenţă odată ce decupezi fundalul într-un editor de imagini, plus pixeli fără pierderi care nu se degradează în timp ce lucrezi.',
    'relation.reflow.q': 'Va funcţiona {{tn}} pe e-readerul meu?',
    'relation.reflow.a.epub': 'EPUB este citit de Apple Books, Kobo, Google Play Cărţi, Calibre şi practic de orice e-reader în afară de Kindle, care vrea MOBI sau AZW3 (Kindle acceptă acum şi EPUB prin e-mail). Fiindcă textul curge din nou, poţi schimba mărimea fontului pe dispozitiv fără să ajungi să derulezi lateral — şi tocmai acesta este întregul motiv pentru care converteşti un {{fn}} de la bun început.',
    'relation.reflow.a.kindle': '{{tn}} este citit de dispozitivele şi aplicaţiile Kindle pentru care a fost conceput. Fiindcă textul curge din nou, poţi schimba mărimea fontului pe dispozitiv fără să ajungi să derulezi lateral — şi tocmai acesta este întregul motiv pentru care converteşti un {{fn}} de la bun început.',

    'compatibility.q': 'Cu ce voi putea deschide fişierul {{tn}} după aceea?',
    'compatibility.a': '{{note}} Nu trebuie instalat nimic pentru conversia în sine — rulează pe serverele noastre, iar {{tn}}-ul finalizat se întoarce în browserul tău gata de deschis, editat sau trimis mai departe. Fişierul tău {{fn}} original nu este niciodată modificat; înapoiem întotdeauna doar un fişier nou.',
    'compatibility.noteFallback': '{{tn}} are sprijin larg.',

    'shapeFaq.pdf-merge.q1': 'Va scădea îmbinarea calitatea PDF-urilor mele?',
    'shapeFaq.pdf-merge.a1': 'Nu. Paginile sunt copiate în noul document exact aşa cum sunt, în loc să fie reprocesate, aşa că textul rămâne selectabil, iar imaginile îşi păstrează rezoluţia originală. Fişierul îmbinat cântăreşte aproximativ cât originalele la un loc — trece-l după aceea prin Comprimare PDF dacă asta contează.',
    'shapeFaq.pdf-merge.q2': 'Câte PDF-uri pot îmbina deodată şi contează ordinea?',
    'shapeFaq.pdf-merge.a2': 'Poţi adăuga deodată câte fişiere ai nevoie, iar ordinea contează cu siguranţă: documentul final urmează ordinea afişată în listă, pe care o poţi rearanja prin tragere înainte de îmbinare. Stabileşte întâi ordinea şi abia apoi îmbină — merge mai repede decât să corectezi după aceea.',
    'shapeFaq.pdf-split.q1': 'Cum aleg ce pagini să fie extrase?',
    'shapeFaq.pdf-split.a1': 'Scrie-le în câmpul pentru intervale de pagini folosind virgule şi cratime: „1-3, 5, 7-10” îţi dă paginile de la unu la trei, pagina cinci şi paginile de la şapte la zece într-un singur document de ieşire. Numerele se referă la paginile proprii ale PDF-ului, numărate de la unu, ceea ce nu este întotdeauna numărul tipărit pe pagină.',
    'shapeFaq.pdf-split.q2': 'Modifică împărţirea PDF-ul original?',
    'shapeFaq.pdf-split.a2': 'Nu. Fişierul pe care îl încarci nu este niciodată modificat — paginile extrase sunt scrise într-un document nou, iar originalul rămâne neatins, până când este şters de pe serverele noastre în 24 de ore, împreună cu rezultatul.',
    'shapeFaq.pdf-compress.q1': 'Cu cât se va micşora PDF-ul meu?',
    'shapeFaq.pdf-compress.a1': 'Depinde în întregime de ce se află înăuntru. PDF-urile dominate de scanări sau fotografii se micşorează adesea cu 50–90 %, fiindcă acolo stă aproape toată dimensiunea. Un PDF doar cu text este deja compact şi s-ar putea să nu se schimbe aproape deloc. Textul şi grafica vectorială rămân clare în ambele cazuri — economia vine din recodarea imaginilor şi din îndepărtarea datelor încorporate redundante.',
    'shapeFaq.pdf-compress.q2': 'Va rămâne textul selectabil şi căutabil?',
    'shapeFaq.pdf-compress.a2': 'Da. Compresia lucrează asupra imaginilor încorporate şi a datelor interne redundante; stratul de text, fonturile, legăturile şi marcajele rămân neatinse, aşa că vei putea căuta, selecta şi copia din fişierul comprimat exact ca înainte.',
    'shapeFaq.pdf-compress-ai.q1': 'Prin ce diferă asta de compresia obişnuită a PDF-urilor?',
    'shapeFaq.pdf-compress-ai.a1': 'Compresia obişnuită aplică o singură setare întregului fişier. Unealta aceasta se uită întâi la ce conţine cu adevărat fiecare pagină, aşa că imaginile fotografice, diagramele plate şi paginile doar cu text sunt tratate fiecare în felul care economiseşte cel mai mult spaţiu fără să le degradeze vizibil. La documentele mixte asta înseamnă de obicei un fişier mai mic la aceeaşi calitate percepută.',
    'shapeFaq.pdf-compress-ai.q2': 'Va rămâne textul selectabil şi căutabil?',
    'shapeFaq.pdf-compress-ai.a2': 'Da. Stratul de text, fonturile, legăturile şi marcajele se păstrează — se recodează doar imaginile încorporate şi datele interne redundante, aşa că PDF-ul comprimat rămâne pe deplin căutabil şi copiabil.',
    'shapeFaq.pdf-rotate.q1': 'Se pierde calitate când un PDF este rotit?',
    'shapeFaq.pdf-rotate.a1': 'Deloc. Rotirea schimbă geometria paginilor consemnată în fişier, în loc să reproceseze ceva, aşa că textul rămâne clar ca vectorul, imaginile rămân neatinse, iar dimensiunea fişierului aproape că nu se clinteşte. Poţi roti din nou mai târziu, fără nicio deteriorare cumulată.',
    'shapeFaq.pdf-rotate.q2': 'Pot roti doar o parte dintre pagini?',
    'shapeFaq.pdf-rotate.a2': 'Rotirea pe care o alegi — 90°, 180° sau 270° — se aplică documentului. Dacă pagini diferite stau greşit în direcţii diferite, abordarea obişnuită este să împarţi PDF-ul, să roteşti fiecare parte cu unghiul de care are nevoie şi să reuneşti rezultatele cu unealta Îmbinare PDF.',
    'shapeFaq.pdf-protect.q1': 'Ce se întâmplă dacă uit parola?',
    'shapeFaq.pdf-protect.a1': 'Fişierul nu va putea fi deschis. Criptarea se aplică PDF-ului în sine, aşa că nu există nicio legătură de resetare şi nicio uşă din dos — nici pentru tine, nici pentru noi. Păstrează parola într-un loc sigur înainte să trimiţi documentul mai departe şi trimite-o pe alt canal decât fişierul.',
    'shapeFaq.pdf-protect.q2': 'Cât de puternică este protecţia?',
    'shapeFaq.pdf-protect.a2': 'PDF-ul este criptat cu schema standard din industrie încorporată în format, aşa că niciun cititor conform nu îi poate citi conţinutul fără parolă. Punctul slab practic nu este niciodată algoritmul, ci parola însăşi — una scurtă sau evidentă se ghiceşte repede, aşa că foloseşte una lungă pentru orice este cu adevărat confidenţial.',
    'shapeFaq.pdf-unlock.q1': 'Poate asta înlătura o parolă pe care nu o ştiu?',
    'shapeFaq.pdf-unlock.a1': 'Nu. Trebuie să furnizezi parola curentă; unealta decriptează fişierul cu ea, nu sparge criptarea. Este menită documentelor care îţi aparţin sau pe care ai dreptul să le deschizi — un extras de la propria bancă, de exemplu — unde restricţia doar stă în cale.',
    'shapeFaq.pdf-unlock.q2': 'Ce pot face cu fişierul după aceea?',
    'shapeFaq.pdf-unlock.a2': 'Tot ce bloca protecţia: să îl deschizi fără să ţi se ceară nimic, să îl tipăreşti, să copiezi text din el şi să îl editezi în alte programe. Conţinutul paginilor în sine este neschimbat — se înlătură doar stratul de criptare şi restricţiile lui de utilizare.',
    'shapeFaq.metadata.q1': 'Îmi schimbă asta fişierul în vreun fel?',
    'shapeFaq.metadata.a1': 'Nu. Fişierul este citit, nu convertit — nu se scrie nimic înapoi şi nu se produce nimic nou în afară de informaţiile de pe ecran. Este cea mai sigură unealtă de aici pe care să o îndrepţi spre un fişier de care nu eşti sigur.',
    'shapeFaq.metadata.q2': 'Ce fel de informaţii voi vedea?',
    'shapeFaq.metadata.a2': 'Depinde de fişier. Imaginile arată dimensiuni, adâncime de culoare şi date EXIF precum modelul aparatului, obiectivul, expunerea şi, când aparatul le-a înregistrat, coordonatele GPS. Sunetul arată durata, debitul, frecvenţa de eşantionare şi numărul de canale. Videoul adaugă codecul, rezoluţia şi cadenţa. Documentele arată numărul de pagini, autorul, producătorul şi data creării.',
    'shapeFaq.ocr.q1': 'Cât de exactă este recunoaşterea textului?',
    'shapeFaq.ocr.a1': 'O scanare curată şi dreaptă a unui text tipărit, la o rezoluţie rezonabilă, este recunoscută foarte exact. Exactitatea scade la pagini strâmbe sau neclare, la fotografii cu contrast slab, la fonturi neobişnuite şi la scrisul de mână. Alegerea limbii potrivite contează, fiindcă recunoaşterea o foloseşte ca să lămurească literele ambigue.',
    'shapeFaq.ocr.q2': 'Care este diferenţa dintre PDF-ul căutabil şi ieşirea în text simplu?',
    'shapeFaq.ocr.a2': 'PDF-ul căutabil păstrează imaginea originală a paginii exact aşa cum arată şi adaugă dedesubt un strat de text invizibil, aşa că documentul pare neschimbat, dar acum se poate căuta şi copia din el — asta vrei pentru arhivare. Textul simplu aruncă aşezarea în pagină şi îţi dă doar cuvintele, ceea ce vrei pentru editare, scripturi sau pentru a-l da altui program.',
    'shapeFaq.tts.q1': 'Cât de natural sună vocile?',
    'shapeFaq.tts.a1': 'Sunt voci neurale, nu vechea sinteză prin lipire de fragmente, aşa că poartă intonaţie la nivel de frază şi pauze fireşti, în loc să citească cuvânt cu cuvânt. Sunt disponibile şase voci, de la neutră la caldă şi la autoritară, iar ritmul vorbirii poate fi reglat. Punctuaţia contează mai mult decât cred oamenii: virgulele şi punctele modelează frazarea, aşa că un text bine punctuat se citeşte vizibil mai bine.',
    'shapeFaq.tts.q2': 'Cât text pot converti deodată?',
    'shapeFaq.tts.a2': 'Până la 4096 de caractere pe conversie — aproximativ 600 până la 700 de cuvinte, adică vreo cinci minute de vorbire. Pentru texte mai lungi, taie-le într-un loc firesc, cum ar fi un titlu de capitol sau de secţiune, şi converteşte fiecare parte separat; setările de voce şi de viteză rămân aceleaşi între rulări, aşa că bucăţile se îmbină curat.',
    'shapeFaq.stt.q1': 'Cât de exactă este transcrierea?',
    'shapeFaq.stt.a1': 'Vorbirea clară într-un mediu rezonabil de liniştit se transcrie foarte exact, inclusiv pe o gamă largă de accente. Exactitatea scade la zgomot de fond puternic, când mai multe persoane vorbesc una peste alta, sau la jargon foarte specializat şi nume proprii. Indicarea limbii vorbite, în loc să fie lăsată detectarea automată, ajută vizibil.',
    'shapeFaq.stt.q2': 'Pot înregistra direct de la microfon?',
    'shapeFaq.stt.a2': 'Da — reportofonul din pagina aceasta captează sunetul direct în browser, ceea ce e adesea mai rapid decât să cauţi întâi o aplicaţie de înregistrare. Browserul îţi va cere permisiunea pentru microfon prima dată. Poţi de asemenea să încarci un fişier existent, iar transcrierea apare în pagină ca să o poţi citi înainte să o descarci ca TXT sau DOCX.',
    'shapeFaq.subtitle.q1': 'Cât de exacte sunt subtitrările generate?',
    'shapeFaq.subtitle.a1': 'Vorbirea clară se transcrie foarte exact, inclusiv cu accent. Muzica de fundal, vorbitul peste şi terminologia specializată sunt locurile unde se strecoară erorile, iar indicarea limbii vorbite în loc de detectare automată ajută. Ieşirea este un fişier de subtitrare în text simplu, aşa că îndreptarea câte unui cuvânt ia câteva secunde în orice editor de text.',
    'shapeFaq.subtitle.q2': 'Să aleg SRT sau VTT?',
    'shapeFaq.subtitle.a2': 'SRT este alegerea implicită mai sigură: YouTube, Vimeo, Premiere, Final Cut, VLC şi practic orice player îl acceptă. Alege VTT dacă subtitrările merg într-un player video HTML5 de pe un site, fiindcă WebVTT este formatul pe care îl aşteaptă pista nativă de subtitrare a browserului şi acceptă stilizare şi poziţionare pe care SRT nu le poate exprima.',
    'shapeFaq.soon.q1': 'Când va fi disponibil?',
    'shapeFaq.soon.a1': 'Se lucrează activ la el. Unealta va apărea aici şi va începe să primească fişiere de îndată ce va fi gata — la tine nu trebuie instalat sau activat nimic.',
    'shapeFaq.soon.q2': 'Ce pot folosi între timp?',
    'shapeFaq.soon.a2': 'Restul convertorului este pe deplin disponibil: documentele, imaginile, sunetul, videoul, arhivele, GIF-urile şi trusa de unelte PDF funcţionează toate astăzi, la fel şi funcţiile inteligente pentru OCR, transcriere şi subtitrări.',
    'shapeFaq.compress.q1': 'Va rămâne fişierul comprimat tot un {{fn}}?',
    'shapeFaq.compress.a1': 'Da — formatul nu se schimbă, doar dimensiunea. Ce descarci este un {{fn}} obişnuit, care se deschide oriunde se deschidea originalul.{{alpha}} Cât economiseşti depinde de materialul de pornire: {{source}}.',
    'shapeFaq.compress.alpha': ' Transparenţa şi animaţia sunt păstrate.',
    'shapeFaq.compress.source.png': 'capturile de ecran şi grafica plată de interfaţă se comprimă spectaculos, în vreme ce fotografiile salvate ca PNG dau mai puţin',
    'shapeFaq.compress.source.gif': 'animaţiile lungi şi materialul agitat se comprimă cel mai mult, fiindcă este mai multă redundanţă de înlăturat',
    'shapeFaq.compress.source.other': 'fotografiile se comprimă bine, în vreme ce imaginile deja puternic comprimate au mai puţin de dat',
    'shapeFaq.compress.q2': 'Cu cât se va micşora fişierul?',
    'shapeFaq.compress.a2': 'De regulă undeva între o treime şi o zecime din original, depinzând în întregime de ce conţine fişierul şi de cum a fost salvat iniţial. După ce conversia se încheie, pagina arată dimensiunea de dinainte şi de după una lângă alta, aşa că vezi economia reală în loc să o ghiceşti.',
    'shapeFaq.hub.q1': 'Între ce formate pot converti?',
    'shapeFaq.hub.a1': 'Intrare: {{inputs}}. Ieşire: {{outputs}}. Orice intrare poate merge spre orice ieşire, aşa că nu trebuie să găseşti o pagină separată pentru fiecare combinaţie — alege fişierul, alege formatul-ţintă, converteşte.',
    'shapeFaq.hub.q2': 'Pierd calitate?',
    'shapeFaq.hub.a2': 'Depinde de pereche. Trecerea într-un format fără pierderi păstrează totul, dar produce un fişier mai mare; trecerea într-un format comprimat aruncă intenţionat date în schimbul dimensiunii, iar setările avansate te lasă să hotărăşti unde anume vrei să stai pe acest compromis. Conversia între două formate comprimate lasă să cadă de fiecare dată puţin detaliu, aşa că merită să păstrezi originalul drept copie-etalon.',
    'shapeFaq.hub-extract.q1': 'Se păstrează şi videoul?',
    'shapeFaq.hub-extract.a1': 'Nu — doar sunetul. Pista audio este ridicată din videoclip şi salvată separat, şi de aceea rezultatul este o fracţiune din dimensiunea fişierului original. Sunetul nu este reînregistrat, aşa că îşi păstrează calitatea pe care o avea deja în interiorul videoclipului; extragerea dintr-un clip cu debit mic nu poate produce sunet cu debit mare.',
    'shapeFaq.hub-extract.q2': 'Ce format de ieşire ar trebui să aleg?',
    'shapeFaq.hub-extract.a2': 'MP3 pentru compatibilitate maximă — rulează pe orice telefon, sistem audio auto şi player. AAC sau M4A dacă destinaţia este un dispozitiv Apple sau o aplicaţie modernă, fiindcă sună puţin mai bine la acelaşi debit. WAV sau FLAC doar dacă ai de gând să editezi sunetul, fiindcă amândouă sunt fără pierderi şi pe măsură de voluminoase.',
    'shapeFaq.hub-gif.q1': 'De ce arată GIF-ul mai prost decât originalul?',
    'shapeFaq.hub-gif.a1': 'Fiindcă GIF permite doar 256 de culori pe cadru, în vreme ce videoul şi fotografiile conţin milioane. Codorul alege o paletă şi aproximează restul, ceea ce se vede ca benzi în degradeuri şi pe cer. GIF nu poartă, în plus, niciun sunet. Ambele limite ţin de format, nu de conversie.',
    'shapeFaq.hub-gif.q2': 'De ce este fişierul meu GIF atât de mare?',
    'shapeFaq.hub-gif.a2': 'GIF comprimă mult mai puţin eficient decât codecurile video moderne, aşa că dimensiunea fişierului creşte repede cu durata, rezoluţia şi cadenţa. Câteva secunde este intervalul ideal. Dacă rezultatul iese prea greu, scurtează clipul, iar dacă dimensiunea atârnă mai greu decât redarea automată încorporată, un MP4 va arăta aceeaşi animaţie la o fracţiune din dimensiune.',
  },
};
