// Swedish content pack. Mirrors packs/en.js key for key — see the header there.
export default {
  lang: 'sv',
  formats: {
    pdf: { about: 'PDF är ett format med fast layout: det lagrar den exakta positionen för varje tecken, varje linje och varje bild, och därför ser en PDF likadan ut på vilken skärm eller skrivare som helst men är omständlig att redigera.', note: 'PDF låser sidbrytning, teckensnitt och layout, så mottagaren ser exakt det du skickade.' },
    docx: { about: 'DOCX är Microsoft Words moderna format, där texten lever i redigerbara stycken och formatmallar i stället för att vara fastnålad vid fasta sidkoordinater.', note: 'DOCX ger dig riktiga redigerbara stycken, spårade ändringar och kommentarer i Word, Google Dokument eller LibreOffice.' },
    xlsx: { about: 'XLSX är Excels kalkylbladsformat, där varje värde sitter i en adresserbar cell som går att sortera, filtrera och använda i en formel.', note: 'När data väl ligger i XLSX kan du summera, sortera, pivotera och rita diagram i stället för att skriva av dem.' },
    pptx: { about: 'PPTX sparar en presentation som separata bilder med redigerbara textrutor, former, talaranteckningar och övergångar.', note: 'PPTX ger dig bilder som du faktiskt kan redigera om, ordna om och presentera på nytt.' },
    txt: { about: 'En TXT-fil är ingenting annat än tecken — inga teckensnitt, inga bilder, ingen sidstruktur — vilket gör den pytteliten, läsbar överallt och trivialt sökbar.', note: 'TXT skalar bort allt utom orden, vilket är precis vad skript, sökindex och textredigerare vill ha.' },
    html: { about: 'HTML är webbens märkspråk: text inlindad i taggar som en webbläsare gör om till rubriker, stycken, länkar och bilder.', note: 'HTML öppnas i vilken webbläsare som helst och kan klistras in direkt i en webbplats eller ett CMS.' },
    rtf: { about: 'RTF är ett öppet dokumentformat byggt på ren text som bär med sig grundläggande formatering — fet stil, kursiv, teckensnitt, tabeller — utan att låsa in dig i en enda ordbehandlare.', note: 'RTF öppnas i Word, Pages, LibreOffice, WordPad och nästan varje ordbehandlare som någonsin skrivits.' },
    odt: { about: 'ODT är OpenDocument-textformatet som LibreOffice och OpenOffice använder, och det är en ISO-standard snarare än ett leverantörsformat.', note: 'ODT är det inbyggda, fullt redigerbara formatet för LibreOffice och OpenOffice.' },
    epub: { about: 'EPUB är ett e-boksformat med flytande text: det har ingen fast sidstorlek, så texten bryts om efter den skärm och teckenstorlek läsaren använder.', note: 'EPUB låter läsaren ändra teckenstorlek och låta texten flöda om, och det är det som gör långa dokument bekväma på en telefon eller läsplatta.' },
    jpg: { about: 'JPG använder förstörande komprimering avstämd för fotografier: den kastar bort de detaljer ögat märker minst, vilket gör foton små men lägger till mjuka, blockiga artefakter kring skarpa kanter och text.', note: 'JPG ger små filer som öppnas bokstavligen överallt, till priset av permanent bortkastade detaljer och ingen genomskinlighet.' },
    jfif: { about: 'JFIF är en JPEG-bild sparad med en annan filändelse; pixlarna inuti är vanliga JPEG-data, men Windows vägrar ofta lämna över filen till den app du vill använda.', note: 'JFIF är egentligen bara JPEG under ett annat namn.' },
    png: { about: 'PNG är förlustfritt: det lagrar varje pixel exakt, stöder en fullständig alfakanal för genomskinlighet och försämras aldrig när du sparar om det, och därför är det förstahandsvalet för skärmbilder, logotyper och gränssnittsgrafik.', note: 'PNG bevarar varje pixel exakt som den är och stöder äkta genomskinlighet, så det klarar upprepad redigering utan att försämras.' },
    webp: { about: 'WebP är Googles moderna webbildformat; det komprimerar märkbart hårdare än JPG eller PNG vid liknande kvalitet och stöder genomskinlighet och animering, men gott om skrivbords- och tryckprogram kan fortfarande inte öppna det.', note: 'WebP ger de minsta filerna bland de vanliga webbformaten och stöder genomskinlighet.' },
    bmp: { about: 'BMP lagrar rå, i princip okomprimerad pixeldata, vilket gör det fullkomligt troget och enormt slösaktigt — ett foto kan lätt bli tio gånger större än samma bild som PNG.', note: 'BMP är rått och okomprimerat, vilket gammal Windows-programvara och vissa skannrar fortfarande förväntar sig.' },
    tiff: { about: 'TIFF är arkiv- och tryckformatet: förlustfritt, med hög färgdjup, kapabelt att rymma flera sidor eller lager — och följaktligen stort.', note: 'TIFF är formatet tryckerier och arkiv ber om, eftersom ingenting kastas bort.' },
    gif: { about: 'GIF är begränsat till en palett på 256 färger per bildruta, och det är därför fotografier ser bandade ut i det, men det animerar och spelas upp av sig självt inbäddat nästan överallt på internet.', note: 'GIF animerar och spelas upp av sig självt i chattappar, ärendesystem och forum, men är begränsat till 256 färger per bildruta.' },
    ico: { about: 'ICO är en Windows-ikonbehållare som rymmer samma grafik i flera storlekar samtidigt, så att systemet kan välja 16×16 för en flik och 256×256 för en skrivbordsgenväg.', note: 'ICO buntar flera upplösningar i en enda fil, vilket är precis vad favikoner och Windows-programikoner behöver.' },
    heic: { about: 'HEIC är formatet iPhone sparar foton i som standard; det ger ungefär samma kvalitet som JPG på ungefär halva utrymmet, men Windows, många webbformulär och en hel del äldre program vägrar helt enkelt att öppna det.', note: 'HEIC är kompakt men dåligt stött utanför Apples enheter.' },
    svg: { about: 'SVG består inte av pixlar alls — det är XML som beskriver former, banor och text, så det förblir knivskarpt i vilken storlek som helst och kan redigeras eller stilsättas om med kod.', note: 'SVG skalar till vilken storlek som helst utan att någonsin bli suddigt, eftersom det lagrar former i stället för pixlar.' },
    mp4: { about: 'MP4 är en behållare — vanligen H.264-video med AAC-ljud — och det är det enda videoformat som telefoner, webbläsare, tv-apparater, redigeringsprogram och sociala plattformar alla är överens om.', note: 'MP4 spelas upp på i stort sett varje telefon, webbläsare, tv och redigeringsprogram utan extra programvara.' },
    avi: { about: 'AVI är en Microsoft-behållare från 1990-talet; äldre spelare och redigeringssviter läser den fortfarande, men den har inga moderna strömningsfunktioner och dess filer brukar bli betydligt större än MP4.', note: 'AVI är vad äldre spelare, dvd-verktyg och gammal redigeringsprogramvara förväntar sig.' },
    mov: { about: 'MOV är Apples QuickTime-behållare, formatet iPhone och Mac spelar in i och det som Final Cut Pro och iMovie hanterar smidigast.', note: 'MOV är den behållare Apples redigeringsverktyg arbetar smidigast med.' },
    mkv: { about: 'MKV (Matroska) är en öppen behållare som kan rymma hur många video-, ljud- och undertextspår som helst i en fil — utmärkt för arkivering, men avvisad av de flesta telefoner, tv-apparater och webbläsare.', note: 'MKV kan bära flera ljud- och undertextspår i en enda fil.' },
    webm: { about: 'WebM är den royaltyfria behållaren byggd för HTML5-video, vanligen med VP9 eller AV1; webbläsare älskar den, men skrivbordsredigerare och Apple-program rör den ofta inte.', note: 'WebM är litet och strömmas inbyggt i webbläsare.' },
    wmv: { about: 'WMV är Microsofts Windows Media-videoformat, i praktiken enbart för Windows och till stor del övergivet utanför gamla företagsinspelningar och skärminspelningar.', note: 'WMV är ett Windows Media-format med mycket svagt stöd på andra håll.' },
    flv: { about: 'FLV var behållaren bakom Flash-video, och sedan Flash togs bort från alla webbläsare är det i praktiken ett ospelbart arkivformat.', note: 'FLV är en död behållare från Flash-eran.' },
    mp3: { about: 'MP3 är förstörande: kodaren raderar permanent de delar av signalen den förutspår att du inte hör, vilket krymper ett spår till ungefär en tiondel och är skälet till att det spelas på absolut allt.', note: 'MP3 är ungefär tio gånger mindre än okomprimerat ljud och spelas på varje telefon, bilstereo och spelare från de senaste tjugo åren.' },
    wav: { about: 'WAV lagrar ljud okomprimerat, sampling för sampling, precis som det spelades in — därför använder studior det, och därför tar en minut stereo i cd-kvalitet ungefär 10 MB.', note: 'WAV är okomprimerat och förlustfritt, så redigerings- och masteringprogram kan bearbeta det utan att först avkoda något.' },
    flac: { about: 'FLAC komprimerar ljud förlustfritt: det är ungefär hälften så stort som WAV och avkodas ändå tillbaka till en bit-för-bit identisk kopia av originalinspelningen.', note: 'FLAC är bit-för-bit identiskt men ungefär hälften så stort som WAV.' },
    aac: { about: 'AAC är den förstörande kodek som ligger bakom Apple Music, YouTube och de flesta strömningstjänster; vid samma bithastighet låter den i allmänhet bättre än MP3.', note: 'AAC låter bättre än MP3 vid samma bithastighet och är standard i Apple- och strömningsvärlden.' },
    ogg: { about: 'OGG Vorbis är en patentfri förstörande kodek som gynnas av spel, öppen källkod och Wikipedia, med kvalitet jämförbar med MP3 vid mindre storlek.', note: 'OGG är fritt från patentbegränsningar, och därför föredrar spelmotorer och öppen källkod det.' },
    m4a: { about: 'M4A är en MP4-behållare som bara innehåller ljud, normalt AAC — formatet iTunes, Apple Music och iPhones röstmemon skapar.', note: 'M4A är Apple-ekosystemets standardljudfil.' },
    wma: { about: 'WMA är Microsofts förstörande ljudkodek från Windows Media Player-eran, sällan stödd utanför Windows och i praktiken nedlagd.', note: 'WMA är en föråldrad ljudkodek som bara lever på Windows.' },
    zip: { about: 'ZIP är arkivformatet som är inbyggt i Windows, macOS och varje telefon — det räcker att dubbelklicka, utan att installera något extra.', note: 'ZIP öppnas med ett dubbelklick på Windows, macOS, Linux, iOS och Android utan att något installeras.' },
    rar: { about: 'RAR är ett proprietärt arkivformat med god komprimering och återställningsdata, men det behöver WinRAR eller ett kompatibelt verktyg för att öppnas.', note: 'RAR kräver programvara från tredje part för att packas upp.' },
    '7z': { about: '7Z använder LZMA-komprimering, som regelbundet ger märkbart mindre arkiv än ZIP — till priset av att kräva 7-Zip eller ett kompatibelt verktyg för att öppnas.', note: '7Z komprimerar betydligt hårdare än ZIP, vilket spelar roll för stora mappar och betald molnlagring.' },
    tar: { about: 'En TAR-fil buntar många filer till en utan att komprimera dem; den kommer från Unix-världen och bevarar rättigheter och katalogstruktur.', note: 'TAR bevarar Unix-rättigheter och katalogstruktur.' },
    gz: { about: 'GZ (gzip) komprimerar en enda dataström och är vad Linux-servrar och kommandoradsverktyg producerar; på Windows är det omständligt att öppna utan extra programvara.', note: 'GZ är standardformatet för komprimering på Linux och på webbservrar.' },
    srt: { about: 'SRT är undertextformatet i ren text som varje redigeringsprogram och varje spelare förstår: numrerade repliker, ett tidkodsintervall och dialograden.', note: 'SRT accepteras av YouTube, Vimeo, Premiere, Final Cut och varje vanlig spelare.' },
  },
  reasons: {
    'pdf-to-word': 'Den vanliga anledningen är en ändring du inte kan göra i själva PDF-filen — en avtalsklausul, en punkt i ett cv eller ett stycke i en rapport som måste ändras utan att hela dokumentet skrivs om.',
    'word-to-pdf': 'Word görs om till PDF allra sist i ett dokuments liv: när ett cv, en offert eller ett undertecknat formulär ska till någon vars teckensnitt, Word-version och marginaler du inte råder över.',
    'pdf-to-excel': 'Det typiska fallet är ett kontoutdrag, en faktura eller en rapport som bara finns som PDF men vars siffror du behöver summera, sortera eller rita diagram av.',
    'excel-to-pdf': 'Det här gör man innan en budget eller prislista skickas till någon som ska läsa den men inte ändra den, och före utskrift — en PDF spikar de sidbrytningar som Excel annars skulle räkna om på varje dator.',
    'pptx-to-pdf': 'De flesta gör om en presentation till PDF innan de mejlar eller delar ut den, så att bilderna inte hoppar och ingen behöver ha PowerPoint installerat för att öppna dem.',
    'pdf-to-pptx': 'Det här behöver du när den enda kvarvarande kopian av en presentation är den PDF som skickades runt efter mötet och du måste uppdatera eller återanvända bilderna.',
    'pdf-to-txt': 'Vanliga skäl: mata ett dokument till ett skript, ett sökindex eller ett AI-verktyg, eller koka ner en lång rapport till något du kan söka i, jämföra och klistra in var som helst.',
    'pdf-to-html': 'Det är det snabbaste sättet att publicera en befintlig rapport, manual eller broschyr på en webbplats utan att bygga om sidan för hand.',
    'html-to-pdf': 'Man gör det för att arkivera en webbsida exakt som den ser ut i dag, eller för att förvandla en HTML-mall för faktura eller rapport till något utskrivbart och skickbart.',
    'rtf-to-pdf': 'RTF kommer oftast ur äldre program eller juridiska dokumentmallar; att göra en PDF av det ger dig en fil som öppnas likadant överallt och inte kan ändras av misstag.',
    'pdf-to-rtf': 'Det här är valet när du behöver en redigerbar kopia av en PDF men inte kan förutsätta att mottagaren har Word — praktiskt taget varje ordbehandlare som någonsin skrivits öppnar RTF.',
    'odt-to-pdf': 'Det typiska fallet: du skrev dokumentet i LibreOffice eller OpenOffice och mottagaren använder Microsoft Office, eller ingenting alls.',
    'pdf-to-epub': 'Att läsa en PDF på en telefon innebär ständigt nyp och sidled-scrollande; den här konverteringen handlar framför allt om att göra ett långt dokument verkligt läsbart på en liten skärm eller läsplatta.',
    'epub-to-pdf': 'Man gör om EPUB till PDF när man vill skriva ut en bok, kommentera den mot fasta sidnummer eller skicka den till någon utan läsplatteapp.',
    'document-converter': 'Det är verktyget att öppna när du får ett dokument i det format avsändaren råkade ha och behöver det i det som din egen programvara faktiskt öppnar.',
    'ebook-converter': 'E-bokhandlar och läsplattor gynnar var och en sitt eget format, så det här använder du för att flytta en bok du äger från en läsare eller app till en annan.',
    'jpg-to-png': 'Den vanliga anledningen är redigering: du behöver frilägga en bakgrund, lägga en logotyp ovanpå en annan bild, eller hindra en skärmbild från att bli suddigare varje gång den sparas om.',
    'png-to-jpg': 'Det här är lösningen på en skärmbild eller export som är för stor för att bifogas i ett mejl eller för att ta sig förbi storleksgränsen i ett uppladdningsformulär.',
    'webp-to-png': 'Du behöver oftast det här efter att ha sparat en bild från en webbplats: WebP laddas ner utan problem, men äldre bildredigerare, kontorsprogram och vissa tryckerier vägrar fortfarande att öppna det.',
    'webp-to-jpg': 'De flesta gör det här för att få en webbplatsbild till något universellt accepterat — ett mejl, ett äldre CMS, en fotoframkallningstjänst eller en kollegas urgamla program.',
    'heic-to-jpg': 'Det här är det klassiska iPhone-problemet: foton ser fina ut på telefonen men landar på en Windows-dator eller i ett webbformulär som oöppningsbara .heic-filer.',
    'heic-to-png': 'Använd det här när du tänker redigera fotot och inte bara dela det — PNG lämnar över förlustfria pixlar till din bildredigerare i stället för en nyss omkomprimerad kopia.',
    'svg-to-png': 'Den vanliga anledningen är ett verktyg som vägrar vektorer: en presentation, en annons på en marknadsplats, en mejlsignatur eller en ikonproduktionskedja som bara tar emot pixlar.',
    'svg-to-jpg': 'Det här är för ställen som vill ha en enkel fotoliknande fil — ett dokument, ett inlägg i sociala medier eller ett uppladdningsformulär som avvisar både SVG-kod och genomskinlighet.',
    'bmp-to-png': 'BMP-filer kommer ur gammal Windows-programvara och skannrar i absurda storlekar; PNG lagrar exakt samma pixlar på en bråkdel av utrymmet.',
    'tiff-to-jpg': 'Skannrar och proffskameror ger TIFF-filer som är alldeles för stora för att mejla, så JPG är vad man skickar när arkivkopian väl ligger tryggt.',
    'gif-to-png': 'Det här gör man med en stillastående GIF — en logotyp, en ikon eller en exporterad bildruta — som visar färgband eller en fransig kant på grund av 256-färgsgränsen.',
    'png-to-ico': 'Nästan alla som gör om PNG till ICO bygger en favikon eller en Windows-programikon, och båda förväntar sig ICO-behållaren snarare än en vanlig bildfil.',
    'jfif-to-png': 'JFIF-filer dyker typiskt upp när ett foto sparas från Outlook eller en webbläsare och Windows sedan vägrar lämna över det till den app du faktiskt ville använda.',
    'heic-to-pdf': 'Praktiskt när du fotograferar dokument, kvitton eller en whiteboard med en iPhone och måste lämna in dem som en enda fil i stället för en mapp med bilder.',
    'image-compressor': 'Den vanliga anledningen är en hård gräns någonstans — ett uppladdningsformulär, ett tak för mejlbilagor, eller en webbsida som laddar för långsamt för att dess bilder är mycket större än de behöver vara.',
    'jpeg-compressor': 'Fotografer och webbplatsägare använder det här när JPEG-filer i full upplösning bromsar en sida eller inte får plats inom en uppladdningsgräns.',
    'png-compressor': 'Skärmbilder och exporterad gränssnittsgrafik väger ofta flera megabyte utan god anledning; det här krymper dem innan de hamnar i ett dokument, ett ärende eller på en webbsida.',
    'mp4-to-avi': 'Anledningen är nästan alltid en äldre apparat eller ett specifikt program — vissa gamla spelare, dvd-verktyg och kameraprogram läser AVI och ingenting annat.',
    'mp4-to-mov': 'Det här är normalt första steget före redigering på en Mac, eftersom Final Cut Pro och iMovie hanterar QuickTime-filer smidigast.',
    'mov-to-mp4': 'iPhone och Mac spelar in i MOV; allt annat förväntar sig MP4, så det här är konverteringen man kör innan man laddar upp, mejlar eller lägger ut ett klipp.',
    'mkv-to-mp4': 'MKV är utmärkt för lagring men telefoner, tv-apparater, webbläsare och de flesta redigeringsprogram spelar inte upp det — att göra om till MP4 är det som gör filen verkligt användbar.',
    'webm-to-mp4': 'WebM-filer som sparats från webben vägrar ofta öppnas i QuickTime, på iOS eller i Premiere; MP4 är formatet de alla accepterar.',
    'avi-to-mp4': 'Det här är standardräddningen för gammalt videokamera-material och arkiverade klipp som slukar gigabyte och inte spelas upp på någon telefon.',
    'flv-to-mp4': 'Flash är borta ur varje webbläsare, så varje FLV du fortfarande har är i praktiken ospelbar — att göra om den till MP4 håller det arkiverade materialet tittbart.',
    'wmv-to-mp4': 'WMV är en kvarleva som bara lever på Windows, så det här gör man innan en gammal inspelning eller skärminspelning skickas till en Mac, en iPhone eller en webbplattform.',
    'mp4-to-mp3': 'Poängen är oftast ljudet snarare än bilden — en föreläsning, en intervju, en podd eller en musikvideo du vill ha i telefonen utan att släpa med videon.',
    'video-to-mp3': 'Man tar till det här när ljudet är den del som är värd att behålla: ett inspelat föredrag, en intervju, en repetition eller ett soundtrack.',
    'mp4-converter': 'Det här är verktyget när ett klipp inte spelas upp eller inte går att ladda upp, eftersom MP4 är det enda videoformat som telefoner, webbläsare, tv-apparater och sociala plattformar alla accepterar.',
    'video-converter': 'Använd det när ett klipp behöver byta värld — ut ur ett redigeringsprogram, in i en telefon, in i en webbläsare, eller till en plattform som bara tar emot en viss behållare.',
    'mp3-to-wav': 'Den vanliga anledningen är redigering: musikprogram, masteringkedjor och många ljudflöden för radio eller spel vill ha okomprimerad WAV, så att de slipper avkoda en komprimerad fil vid varje enskild operation.',
    'wav-to-mp3': 'Inspelningar kommer ur en fältinspelare eller ett musikprogram som enorma WAV-filer; MP3 är det som gör dem små nog att mejla, ladda upp eller få plats i telefonen.',
    'flac-to-mp3': 'Ett FLAC-bibliotek låter utmärkt hemma, men bilstereor, äldre telefoner och billiga spelare vägrar ofta ta emot det — MP3 är kompatibilitetskopian du tar med dig.',
    'aac-to-mp3': 'Det här handlar mest om kompatibilitet: AAC kommer ur Apple- och strömningsvärlden, medan äldre spelare, bilstereor och dj-program förväntar sig MP3.',
    'ogg-to-mp3': 'OGG dyker upp i spel, på Wikipedia och i program med öppen källkod, och nästan ingen av de vanliga spelarna i en telefon eller bil öppnar det.',
    'wma-to-mp3': 'WMA är en kvarleva från Windows Media Player-eran, och så räddar man en gammal rippad musiksamling till en telefon eller ett strömningsbibliotek.',
    'm4a-to-mp3': 'Det här är det vanliga steget när musik eller iPhone-röstmemon ska flyttas från Apple-enheter till program, bilar eller spelare som bara förstår MP3.',
    'mp3-to-aac': 'Vissa enheter och appar — särskilt inom Apple och strömningsplattformarna — föredrar AAC, så det här är en kompatibilitetskonvertering och ingen kvalitetsförbättring.',
    'mp3-to-ogg': 'Man gör om till OGG för spelmotorer, projekt med öppen källkod och plattformar där en patentfri kodek krävs.',
    'audio-converter': 'Det här är verktyget för stunden då en fil inte spelas upp: ett enda ställe att flytta ljud till just det av de vanliga formaten som din enhet, ditt redigeringsprogram eller ditt uppladdningsformulär insisterar på.',
    'rar-to-zip': 'RAR behöver extra programvara för att öppnas, så det här gör man innan ett arkiv skickas till någon som inte tänker installera WinRAR.',
    '7z-to-zip': '7Z komprimerar bättre men kräver att 7-Zip är installerat; som ZIP kan mottagaren helt enkelt dubbelklicka på filen.',
    'tar-to-zip': 'TAR kommer från kommandoraden i Linux och macOS, medan ZIP är vad en kollega på Windows kan öppna utan att installera någonting alls.',
    'gz-to-zip': 'GZ-filer kommer oftast från en server eller ett Linux-verktyg och är omständliga på Windows, där en ZIP packas upp med ett dubbelklick.',
    'zip-to-7z': 'Här handlar det om storlek: 7Z komprimerar märkbart hårdare, vilket spelar roll när du arkiverar en stor mapp eller betalar för molnlagring per gigabyte.',
    'video-to-gif': 'Den typiska användningen är en kort loop till ett chattmeddelande, en README, en buggrapport eller ett inlägg — ställen där en GIF spelas upp av sig själv inbäddat medan en videofil inte gör det.',
    'mp4-to-gif': 'Den typiska användningen är en kort loop till en chatt, en README, en buggrapport eller ett inlägg, där en GIF spelas upp av sig själv inbäddat medan en video bara skulle ligga där som en bilaga.',
    'webm-to-gif': 'WebM-klipp som sparats från webben går ofta inte att bädda in där du vill ha dem, medan en GIF spelas upp inbäddat i chattappar, ärendesystem och forum.',
    'mov-to-gif': 'Det här gör man med en QuickTime-skärminspelning som ska synas inbäddad i en pull request, ett supportärende eller ett inlägg.',
    'avi-to-gif': 'Att göra några sekunder av ett gammalt AVI-klipp till en GIF är det enklaste sättet att få in dem i ett dokument, en chattråd eller en webbsida.',
    'gif-to-mp4': 'Långa GIF-filer är enorma och spelas hackigt; MP4 visar samma animering på en bråkdel av storleken, vilket är precis varför sociala plattformar gör om dem i bakgrunden.',
    'image-to-gif': 'Användbart när en plattform eller ett äldre system uttryckligen förväntar sig en GIF, eller när du behöver en stillbild i samma format som en befintlig serie animeringar.',
    'gif-compressor': 'Animerade GIF-filer sväller snabbt, och det här är lösningen när en är för tung för ett mejl, en uppladdningsgräns i en chatt eller en sida som måste ladda snabbt.',
    'merge-pdf': 'Det klassiska fallet är en ansökan eller en skadeanmälan: ett formulär, en skanning och ett kvitto som alla måste komma fram som ett enda dokument.',
    'split-pdf': 'Oftast behöver du exakt en sak ur en mycket längre fil — ett kapitel, en faktura, en undertecknad sida ur en femtiosidig skanning.',
    'compress-pdf': 'Nästan alltid en storleksgräns: ett tak för mejlbilagor, ett myndighetsformulär eller en portal som avvisar allt över några megabyte.',
    'rotate-pdf': 'Det här löser det vardagliga skannerproblemet — sidor som kom ut på sidan eller upp-och-ner på grund av hur arken matades in.',
    'protect-pdf': 'Man lösenordsskyddar PDF-filer innan man mejlar lönebesked, avtal eller läkarintyg, så att innehållet inte går att läsa för den som meddelandet sedan vidarebefordras till.',
    'unlock-pdf': 'Använd det på dokument du äger när lösenordet är känt men begränsningen står i vägen — ett kontoutdrag du inte kan skriva ut, till exempel.',
    'view-metadata': 'Det besvarar frågorna en fil inte berättar rakt ut: vilken kamera tog det här fotot, hur lång är den här inspelningen egentligen, vilken kodek sitter i den här videon, hur många sidor har den här PDF-filen.',
    'ocr': 'Situationen är alltid densamma: du har ett dokument som bild och behöver orden ur det — för att söka i dem, citera dem, redigera dem eller arkivera dem ordentligt.',
    'pdf-compress-ai': 'Ta till det när vanlig komprimering redan har prövats och filen fortfarande är för stor för den uppladdningsgräns du kämpar mot.',
    'text-to-speech': 'Man använder det för att lyssna på något i stället för att läsa det — en artikel på väg till jobbet, ett manus uppläst för att fånga knöliga formuleringar, eller en speakerröst till en video.',
    'speech-to-text': 'Det vanliga fallet är en inspelning du behöver i skrift: ett möte, en intervju, en föreläsning eller ett röstmemo som ska bli anteckningar, protokoll eller en citerbar utskrift.',
    'auto-subtitle': 'Undertexter är det som gör en video tittbar utan ljud och sökbar för sökmotorer, och att skriva dem för hand tar även för ett kort klipp långt mer tid än folk tror.',
    'document-translation': 'Målet är att kunna läsa eller skicka ett dokument på ett annat språk utan att förlora den layout som gör det läsbart.',
  },
  t: {
    'list.and': 'och',
    'family.document': 'dokument',
    'family.image': 'bild',
    'family.video': 'video',
    'family.audio': 'ljud',
    'family.ebook': 'e-boks',
    'family.archive': 'arkiv',
    'family.subtitle': 'undertext',
    'family.none': 'fil',
    'unit.sample': 'varje sampling',
    'unit.pixel': 'varje pixel',

    'intro.convert': '{{fromAbout}} {{toAbout}} {{reason}} {{toNote}}',
    'intro.convert.noSource': '{{fn}} är källformatet för den här konverteringen.',
    'intro.lead': '{{lead}} {{reason}}',
    'intro.hub': 'Det här är den allmänna {{category}}konverteraren: den tar emot {{inputs}} och skriver {{outputs}}, så du slipper leta efter det enda verktyg som passar just ditt formatpar. {{reason}} Välj utdataformat ovan — konverteringen sker på servern, ingenting behöver installeras.',
    'intro.hubExtract': 'Det här verktyget drar ut ljudspåret ur en videofil och sparar det för sig, så att en video blir en vanlig ljudfil som spelas upp överallt. Det tar emot {{inputs}} och skriver {{outputs}}. Videospåret kastas helt enkelt bort, och därför blir resultatet en bråkdel av originalstorleken. {{reason}}',
    'intro.hubGif': 'Det här verktyget gör om {{inputs}}-filer till animerade GIF-filer. {{gifAbout}} {{reason}}',
    'intro.hubGif.gifAbout': 'GIF är begränsat till en palett på 256 färger per bildruta, och det är därför fotografier ser bandade ut i det, men det animerar och spelas upp av sig självt inbäddat nästan överallt på internet.',
    'intro.compress': '{{about}} Det här verktyget kodar om din {{fn}} till en mindre filstorlek utan att byta format, så det du laddar ner är fortfarande en vanlig {{fn}} som öppnas precis där originalet gjorde det. {{reason}}{{extra}}',
    'intro.compress.lossless': ' Eftersom {{fn}} är förlustfritt kommer det mesta av besparingen från smartare kodning och minskad palett snarare än från att detaljer kastas bort.',
    'intro.soon': '{{reason}} Det här verktyget är inte igång ännu — det byggs just nu och dyker upp här så snart det är klart.',
    'intro.lead.pdf-merge': 'Sammanfogning slår ihop flera PDF-filer till en enda, i den ordning du väljer, utan att rita om sidorna — texten går fortfarande att markera och bilderna behåller sin ursprungliga kvalitet. PDF är ett format med fast layout: det lagrar den exakta positionen för varje tecken, varje linje och varje bild, och därför ser det likadant ut överallt men är omständligt att redigera.',
    'intro.lead.pdf-split': 'Delning plockar ut de sidor du anger ur en PDF och sparar dem som ett nytt dokument, medan originalet lämnas orört. PDF är ett format med fast layout: det lagrar den exakta positionen för varje tecken, varje linje och varje bild, och därför ser det likadant ut överallt men är omständligt att redigera.',
    'intro.lead.pdf-compress': 'Att komprimera en PDF kodar om bilderna inuti den och rensar bort överflödiga inbäddade data, och det är där nästan hela storleken i en stor PDF faktiskt sitter. Text och vektorgrafik lämnas knivskarpa.',
    'intro.lead.pdf-compress-ai': 'Det här verktyget analyserar vad som finns i PDF-filen innan det komprimerar, så att fotografiska bilder, platt grafik och rena textsidor var för sig hanteras på det sätt som sparar mest utrymme utan att synligt försämra dem.',
    'intro.lead.pdf-rotate': 'Rotation ändrar orienteringsmarkeringen och sidgeometrin i en PDF så att sidorna visas och skrivs ut rättvända. Ingenting ritas om, så ingen kvalitet går förlorad.',
    'intro.lead.pdf-protect': 'Att skydda en PDF krypterar dess innehåll så att den inte kan öppnas utan lösenordet du sätter. Krypteringen tillämpas på själva filen, inte på ett hölje runt den.',
    'intro.lead.pdf-unlock': 'Upplåsning tar bort lösenordet och användningsbegränsningarna ur en PDF vars lösenord du redan har, så att den åter kan öppnas, skrivas ut och kopieras normalt.',
    'intro.lead.metadata': 'Varje fil bär information om sig själv som inte syns när du öppnar den: bildens mått och kamerans inställningar, ljudets längd och bithastighet, videons kodek och bildfrekvens, dokumentets författare och sidantal. Det här verktyget läser den metadatan och visar den för dig.',
    'intro.lead.ocr': 'Optisk teckenigenkänning tittar på en bild av text — en skanning, ett foto, en PDF-sida utan textlager — och räknar ut vilka tecknen är, vilket förvandlar en bild av ord till ord som en dator kan söka i, kopiera och redigera.',
    'intro.lead.tts': 'Text till tal genererar talat ljud ur skriven text med neurala röster, så du får en naturligt klingande inspelning i stället för den platta robotröst äldre system gav.',
    'intro.lead.stt': 'Tal till text skriver ut talat ljud som ord. Det klarar naturligt tal, brytningar och bakgrundsljud långt bättre än gamla dikteringsprogram gjorde, och lämnar en utskrift du kan redigera.',
    'intro.lead.subtitle': 'Undertextgeneratorn skriver ut talet i en video och lägger till tidkoder, vilket ger en standardiserad undertextfil snarare än en ren utskrift.',

    'steps.convert.1.batch': 'Släpp din {{fn}}-fil på uppladdningsytan högst upp på den här sidan, eller klicka på den för att bläddra på din enhet. Du kan lägga till flera filer — eller en hel mapp — och konvertera dem allihop på en gång.',
    'steps.convert.1.single': 'Släpp din {{fn}}-fil på uppladdningsytan högst upp på den här sidan, eller klicka på den för att bläddra på din enhet.',
    'steps.convert.2.direct': 'Välj {{tn}} som utdataformat och klicka på Konvertera.',
    'steps.convert.2.dropdown': 'Välj {{tn}} som utdataformat i listan och klicka på Konvertera.',
    'steps.convert.2.directMedia': 'Välj {{tn}} som utdataformat, justera vid behov kvalitet eller storlek under avancerade inställningar och klicka på Konvertera.',
    'steps.convert.2.dropdownMedia': 'Välj {{tn}} som utdataformat i listan, justera vid behov kvalitet eller storlek under avancerade inställningar och klicka på Konvertera.',
    'steps.convert.3': 'Ladda ner din färdiga {{tn}}-fil. Nedladdningslänken är aktiv i 24 timmar, därefter raderas båda filerna automatiskt.',
    'steps.hub.1.batch': 'Släpp din {{category}}fil ({{inputs}} tas alla emot) på uppladdningsytan högst upp på den här sidan, eller klicka på den för att bläddra på din enhet. Du kan lägga till flera filer — eller en hel mapp — och konvertera dem allihop på en gång.',
    'steps.hub.1.single': 'Släpp din {{category}}fil ({{inputs}} tas alla emot) på uppladdningsytan högst upp på den här sidan, eller klicka på den för att bläddra på din enhet.',
    'steps.hub.2.direct': 'Välj det utdataformat du behöver och klicka på Konvertera.',
    'steps.hub.2.dropdown': 'Välj i listan det utdataformat du behöver och klicka på Konvertera.',
    'steps.hub.2.directMedia': 'Välj det utdataformat du behöver, justera vid behov kvalitet eller storlek under avancerade inställningar och klicka på Konvertera.',
    'steps.hub.2.dropdownMedia': 'Välj i listan det utdataformat du behöver, justera vid behov kvalitet eller storlek under avancerade inställningar och klicka på Konvertera.',
    'steps.hub.3': 'Ladda ner din färdiga fil. Nedladdningslänken är aktiv i 24 timmar, därefter raderas båda filerna automatiskt.',
    'steps.pdf-merge.1': 'Lägg till varje PDF du vill slå ihop — släpp dem tillsammans på uppladdningsytan, eller klicka för att välja dem en efter en.',
    'steps.pdf-merge.2': 'Dra filerna till den ordning du vill att de ska stå i det färdiga dokumentet.',
    'steps.pdf-merge.3': 'Klicka på Slå ihop och ladda ner den enda sammanfogade PDF-filen.',
    'steps.pdf-split.1': 'Ladda upp den PDF du vill plocka sidor ur.',
    'steps.pdf-split.2': 'Skriv de sidor eller intervall du behöver i fältet för sidintervall — till exempel 1-3, 5, 7-10.',
    'steps.pdf-split.3': 'Klicka på Konvertera och ladda ner de uttagna sidorna.',
    'steps.pdf-compress.1': 'Släpp din PDF på uppladdningsytan, eller klicka för att leta rätt på den.',
    'steps.pdf-compress.2': 'Klicka på Konvertera — filen analyseras och dess bilder och inbäddade data kodas om till mindre storlek.',
    'steps.pdf-compress.3': 'Ladda ner den komprimerade PDF-filen och se besparingen som visas bredvid.',
    'steps.pdf-rotate.1': 'Ladda upp den PDF vars sidor ligger åt fel håll.',
    'steps.pdf-rotate.2': 'Välj hur mycket de ska vridas — 90°, 180° eller 270°.',
    'steps.pdf-rotate.3': 'Klicka på Konvertera och ladda ner den rättade PDF-filen.',
    'steps.pdf-protect.1': 'Ladda upp den PDF du vill skydda.',
    'steps.pdf-protect.2': 'Ange det lösenord som ska krävas för att öppna den, och spara en kopia på ett säkert ställe.',
    'steps.pdf-protect.3': 'Klicka på Konvertera och ladda ner den krypterade PDF-filen.',
    'steps.pdf-unlock.1': 'Ladda upp den lösenordsskyddade PDF-filen.',
    'steps.pdf-unlock.2': 'Ange dess nuvarande lösenord så att filen kan dekrypteras.',
    'steps.pdf-unlock.3': 'Klicka på Konvertera och ladda ner den upplåsta PDF-filen.',
    'steps.metadata.1': 'Släpp vilken fil som helst på uppladdningsytan — en bild, en video, en ljudfil eller ett dokument.',
    'steps.metadata.2': 'Filen granskas i stället för att konverteras, så ingenting i den ändras.',
    'steps.metadata.3': 'Läs metadatan direkt på sidan: mått, längd, kodek, kamerauppgifter, sidantal och mer.',
    'steps.ocr.1': 'Ladda upp den skannade PDF-filen eller fotot av texten.',
    'steps.ocr.2': 'Välj dokumentets språk och om du vill ha en sökbar PDF eller ren text.',
    'steps.ocr.3': 'Klicka på Konvertera och ladda ner resultatet, där den igenkända texten nu går att markera och söka i.',
    'steps.tts.1': 'Skriv eller klistra in din text i rutan — upp till 4096 tecken per konvertering.',
    'steps.tts.2': 'Välj en röst, ett taltempo och ett utdataformat.',
    'steps.tts.3': 'Klicka på Konvertera och ladda ner den färdiga ljudfilen.',
    'steps.stt.1': 'Ladda upp din inspelning, eller spela in direkt från mikrofonen med knappen på sidan.',
    'steps.stt.2': 'Ange gärna det talade språket för bättre träffsäkerhet, och välj TXT- eller DOCX-utdata.',
    'steps.stt.3': 'Klicka på Konvertera, läs utskriften på sidan och ladda sedan ner den.',
    'steps.subtitle.1': 'Ladda upp den video du vill texta.',
    'steps.subtitle.2': 'Välj SRT eller VTT, och ange det talade språket om du känner till det.',
    'steps.subtitle.3': 'Klicka på Konvertera och ladda ner den tidkodade undertextfilen, redo att läggas in i din spelare eller ditt redigeringsprogram.',
    'steps.compress.1': 'Släpp dina {{fn}}-bilder på uppladdningsytan, eller klicka för att bläddra. Du kan lägga till en hel mapp på en gång.',
    'steps.compress.1.gif': 'Släpp din {{fn}}-animering på uppladdningsytan, eller klicka för att bläddra. Du kan lägga till en hel mapp på en gång.',
    'steps.compress.2': 'Klicka på Konvertera — filen kodas om till mindre storlek men stannar i samma format.',
    'steps.compress.3': 'Ladda ner resultatet och jämför det med originalstorleken som visas på sidan.',
    'steps.soon.1': 'Välj det verktyg du behöver på verktygssidan — allt utom det här fungerar redan i dag.',
    'steps.soon.2': 'Ladda upp din fil och välj ett utdataformat.',
    'steps.soon.3': 'Ladda ner resultatet, eller titta förbi här igen när dokumentöversättning går i gång.',

    'faq.cost.q.pair': 'Är det gratis att konvertera {{from}} till {{to}}?',
    'faq.cost.q.tool': 'Är {{label}} gratis att använda?',
    'faq.cost.a.pair': 'Nya konton får en gratis konverteringskredit, så din första konvertering från {{from}} till {{to}} kostar ingenting. Därefter drar varje konvertering en kredit ur ett litet förbetalt paket — det finns inget abonnemang, krediter går aldrig ut, och en misslyckad konvertering debiteras inte.',
    'faq.cost.a.tool': 'Nya konton får en gratis konverteringskredit, så din första fil kostar ingenting. Därefter drar varje konvertering en kredit ur ett litet förbetalt paket — det finns inget abonnemang, krediter går aldrig ut, och en misslyckad konvertering debiteras inte.',
    'faq.cost.a.smartTts': 'Nya konton får en gratis konverteringskredit att prova med, och de smarta funktionerna debiteras efter användning i stället för per fil — 1 kredit per 1000 tecken text, uppåt avrundat. Inget abonnemang: krediter köps i små förbetalda paket, går aldrig ut, och en misslyckad konvertering kostar aldrig något.',
    'faq.cost.a.smartAv': 'Nya konton får en gratis konverteringskredit att prova med, och de smarta funktionerna debiteras efter användning i stället för per fil — 1 kredit per 5 minuter ljud eller video, uppåt avrundat. Inget abonnemang: krediter köps i små förbetalda paket, går aldrig ut, och en misslyckad konvertering kostar aldrig något.',
    'faq.cost.q.metadata': 'Är verktyget Filinfo gratis?',
    'faq.cost.a.metadata': 'Ja. Att läsa en fils metadata är ingen konvertering och drar därför ingen kredit — du kan granska hur många filer du vill. Krediter går bara åt när ett verktyg faktiskt skapar en ny fil åt dig.',
    'faq.cost.q.soon': 'Är {{label}} tillgängligt än?',
    'faq.cost.a.soon': 'Inte än — den här sidan är en platshållare medan verktyget byggs, så det finns ingenting att ladda upp här i dag. Prissättningen följer samma förbetalda kreditmodell som resten av webbplatsen: inget abonnemang, krediter som aldrig går ut, och ingen avgift för en misslyckad konvertering.',

    'faq.time.q.pair': 'Hur lång tid tar konverteringen från {{from}} till {{to}}?',
    'faq.time.q.tool': 'Hur lång tid tar {{label}}?',
    'faq.time.a': '{{speed}} Uppladdningshastigheten är oftast den begränsande faktorn, så en stor fil på en långsam uppkoppling tar längre tid än själva konverteringen.{{suffix}}',
    'faq.time.speed.image': 'Bilder är det snabbaste vi konverterar — ett enstaka foto är normalt klart på under fem sekunder, och en hel mapp tar ungefär lika lång tid som uppladdningen.',
    'faq.time.speed.document': 'De flesta dokument är klara på några sekunder. Mycket långa filer — några hundra sidor, eller en skanning full av bilder — kan ta upp till en minut.',
    'faq.time.speed.audio': 'En vanlig låt konverteras på några sekunder. En inspelning i full längd, som en föreläsning eller ett poddavsnitt, tar normalt en bra bit under en minut, och det mesta av det är uppladdningen.',
    'faq.time.speed.video': 'Video är den långsammaste kategorin eftersom varje bildruta måste kodas om. Ett kort klipp tar sekunder, medan en lång fil i hög upplösning kan ta några minuter.',
    'faq.time.speed.archive': 'Arkiv konverteras på sekunder, även om ett stort tar längre tid eftersom varje fil inuti måste packas upp och packas om.',
    'faq.time.speed.ebook': 'E-böcker går snabbt — en hel roman konverteras normalt på några sekunder.',
    'faq.time.speed.subtitle': 'Utskrift går i ungefär några sekunder per minut ljud, så en tio minuter lång video textas oftast på en bra bit under en minut.',
    'faq.time.suffix.standard': ' Filer upp till 200 MB tas emot.',
    'faq.time.suffix.smart': ' Smarta funktioner tar emot filer upp till 25 MB; vanliga konverteringar upp till 200 MB.',
    'faq.time.q.metadata': 'Hur lång tid tar det att läsa en fils metadata?',
    'faq.time.a.metadata': 'En sekund eller två när filen väl laddats upp. Ingenting konverteras eller kodas om — huvudena läses och resultatet skrivs direkt till sidan — så väntan är i praktiken uppladdningen.',
    'faq.time.q.soon': 'Kommer det att kosta extra?',
    'faq.time.a.soon': 'Det kommer att använda samma krediter som allt annat på webbplatsen. Det finns ingen separat plan eller prenumeration att teckna, och krediter du redan har på kontot fungerar med det från den stund det går i gång.',

    'faq.safety.q.pair': 'Är det säkert att ladda upp min {{from}}-fil?',
    'faq.safety.q.tool': 'Är min fil säker?',
    'faq.safety.a.pair': 'Filer färdas över en krypterad TLS-anslutning och används inte till något annat än den konvertering du bad om. Både din ursprungliga {{from}}-fil och den {{to}}-fil vi lämnar tillbaka raderas automatiskt inom 24 timmar — permanent och utan att några säkerhetskopior sparas — och innehållet läses, analyseras eller delas aldrig. Tjänsten drivs från Tyskland under GDPR.',
    'faq.safety.a.tool': 'Filer färdas över en krypterad TLS-anslutning och används inte till något annat än den konvertering du bad om. Både din ursprungliga fil och det resultat vi lämnar tillbaka raderas automatiskt inom 24 timmar — permanent och utan att några säkerhetskopior sparas — och innehållet läses, analyseras eller delas aldrig. Tjänsten drivs från Tyskland under GDPR.',

    'quality.vectorRaster.q': 'Förblir min {{fn}} skarp som {{tn}}?',
    'quality.vectorRaster.a': 'Upp till den storlek du exporterar den i, ja. {{fn}} lagrar former snarare än pixlar och är därmed oändligt skalbar, men en {{tn}} är ett fast rutnät av pixlar och blir suddig om den senare förstoras bortom det rutnätet. Ställ in den bredd och höjd du faktiskt behöver under avancerade inställningar innan du konverterar — att exportera i två eller tre gånger visningsstorleken är det vanliga knepet för skärmar med hög pixeltäthet. Behåll originalfilen i {{fn}}: den förblir mallkopian du kan exportera om i vilken upplösning som helst.',
    'quality.docToTxt.q': 'Förlorar jag formatering när jag konverterar {{fn}} till {{tn}}?',
    'quality.docToTxt.a': 'Ja, och det är själva poängen — en {{tn}}-fil innehåller tecken och ingenting annat. Teckensnitt, färger, bilder, tabeller, spalter och sidbrytningar försvinner allihop; det du får tillbaka är dokumentets läsbara text i läsordning. Det är precis vad du vill ha för att söka, skripta eller mata texten till ett annat program, och precis vad du inte vill ha om du hoppades behålla formgivningen. Observera att en {{fn}} som i själva verket är en inskannad bild inte innehåller någon text alls att plocka ut — kör den genom OCR-verktyget i stället.',
    'quality.docToSheet.q': 'Hur träffsäker är tabelluttagningen ur en {{fn}}?',
    'quality.docToSheet.a': 'Rena tabeller med linjer och jämna spalter — kontoutdrag, fakturor, exporterade rapporter — kommer igenom pålitligt, och varje värde landar i sin egen cell så att du kan summera och sortera. Tabeller utan synliga ramar, celler som spänner över flera rader eller siffror som delas av en sidbrytning är de fall som är värda att kika igenom efteråt. {{fn}} lagrar positioner och inte tabellstruktur, så konverteringen måste sluta sig till var en spalt slutar och nästa börjar.',
    'quality.docToReflow.q': 'Överlever layouten konverteringen från {{fn}} till {{tn}}?',
    'quality.docToReflow.a': 'Inte exakt, och det är hela poängen. {{fn}} nålar fast texten vid fasta sidkoordinater; {{tn}} låter den flöda om efter läsarens skärm och teckenstorlek, så fasta sidnummer, sidhuvuden, sidfötter och flerspaltiga layouter tolkas om snarare än återges. Brödtext, rubriker, styckeordning och bilder kommer igenom bra. Dokument som mest består av löpande text konverteras utmärkt; det är tungt formgivna sidor, formulär och komplexa tabeller som är värda en titt efteråt.',
    'quality.docToFixed.q': 'Bevaras min formatering i {{tn}}?',
    'quality.docToFixed.a': 'Ja — den här riktningen är den säkra. {{tn}} lagrar den färdigt renderade sidan, så teckensnitt, avstånd, tabeller, bilder och sidbrytningar fryses exakt som de satts och kommer att se likadana ut på varje enhet och skrivare. Det är också avvägningen: resultatet går inte längre fritt att redigera, vilket brukar vara precis skälet till att man gör om till {{tn}} innan ett dokument skickas i väg.',
    'quality.docToEditable.q': 'Hur träffsäker är konverteringen från {{fn}} till {{tn}}?',
    'quality.docToEditable.a': 'Text, rubriker, listor, bilder och enkla tabeller kommer igenom pålitligt och förblir fullt redigerbara. Eftersom {{fn}} lagrar positioner snarare än struktur måste konverteringen bygga upp den strukturen igen, så tungt formgivna sidor — flera spalter, text som löper runt bilder, komplexa nästlade tabeller — kan behöva en lätt uppsnyggning efteråt. Är PDF-filen en skanning helt utan textlager ska du använda OCR-verktyget i stället: det känner igen tecknen i bilden i stället för att leta efter text som inte finns.',
    'quality.docGeneric.q': 'Förlorar jag något när jag konverterar {{fn}} till {{tn}}?',
    'quality.docGeneric.a': 'Orden, rubrikerna, listorna och bilderna följer med orörda. {{tn}} har ett annat formateringsordförråd än {{fn}}, så mycket specifik formgivning kan förenklas på vägen, men själva innehållet bevaras.',
    'quality.archive.q': 'Ändras filerna inuti mitt {{fn}}-arkiv?',
    'quality.archive.a': 'Nej. Arkivformat är förlustfria behållare: {{fn}} packas upp och exakt samma filer packas om som {{tn}}, byte för byte. Bara komprimeringsmetoden och behållaren ändras. Det som däremot ändras är arkivets egen storlek — {{clause}}.',
    'quality.archive.clause.to7z': '7Z ger i allmänhet ett mindre arkiv än ZIP tack vare LZMA-komprimering',
    'quality.archive.clause.toZip': 'ZIP blir oftast något större än 7Z eller RAR, vilket är priset för att kunna öppnas överallt utan extra programvara',
    'quality.archive.clause.other': 'det nya formatet komprimerar annorlunda, så filstorleken kan röra sig åt båda håll',
    'quality.imageToDoc.q': 'Förlorar mina foton kvalitet inuti {{tn}}-filen?',
    'quality.imageToDoc.a': 'Nej. Varje {{fn}}-bild placeras i {{tn}}-filen som den är, en per sida, i stället för att komprimeras om, så det du ser i dokumentet är det som kom ur kameran. {{tn}}-filen blir ungefär lika stor som bilderna tillsammans, vilket är värt att veta innan du mejlar den — kör resultatet genom Komprimera PDF om den behöver bli mindre.',
    'quality.toGif.q': 'Varför ser min GIF sämre ut än originalet i {{fn}}?',
    'quality.toGif.a': 'För att GIF är begränsat till 256 färger per bildruta. En video eller ett foto innehåller miljoner, så kodaren måste välja en palett och approximera allt annat, vilket syns som band i övergångar och himlar. GIF bär dessutom inget ljudspår alls. Bådadera hör till formatet och inte till konverteringen — håll klippet kort, och om färgförlusten väger tyngre än inbäddad automatisk uppspelning kommer en MP4 att se långt bättre ut vid mindre storlek.',
    'quality.lossyToLossless.q': 'Blir kvaliteten bättre av att konvertera {{fn}} till {{tn}}?',
    'quality.lossyToLossless.a': 'Nej — och det här är med god marginal det vanligaste missförståndet kring den här konverteringen. {{fn}} är förstörande: de detaljer dess kodare kastade bort är borta för gott, och ingenting kan återskapa dem. Det {{tn}} ger dig är en förlustfri behållare för det som återstår, så att filen slutar försämras vid varje efterföljande sparning eller redigering. Det är verkligen användbart när du står i begrepp att {{clause}}, men det återställer inte kvalitet som redan gått förlorad.',
    'quality.lossyToLossless.edit.audio': 'redigera, mastra eller bearbeta ljudet',
    'quality.lossyToLossless.edit.image': 'redigera, retuschera eller montera bilden',
    'quality.losslessToLossy.q': 'Förlorar jag kvalitet när jag konverterar {{fn}} till {{tn}}?',
    'quality.losslessToLossy.a.audio': 'En del, och avsiktligt — det är så filen blir mindre. {{tn}} är förstörande, så kodaren kastar den information den bedömer som minst märkbar. Med vettiga inställningar är skillnaden mycket svår att höra, och du kan höja bithastigheten under avancerade inställningar om du hellre byter storlek mot trohet. Behåll din ursprungliga {{fn}}-fil: den förblir mallkopian, och att koda om {{tn}} igen senare skulle förvärra förlusten.',
    'quality.losslessToLossy.a.visual': 'En del, och avsiktligt — det är så filen blir mindre. {{tn}} är förstörande, så kodaren kastar den information den bedömer som minst märkbar. Med vettiga inställningar är skillnaden mycket svår att se, och du kan höja kvalitetsvärdet under avancerade inställningar om du hellre byter storlek mot trohet. Behåll din ursprungliga {{fn}}-fil: den förblir mallkopian, och att koda om {{tn}} igen senare skulle förvärra förlusten.',
    'quality.lossyToLossy.q': 'Förlorar jag kvalitet när jag konverterar {{fn}} till {{tn}}?',
    'quality.lossyToLossy.a.audio': 'En aning. Båda formaten är förstörande, så {{fn}} avkodas och kodas sedan om som {{tn}}, och varje generation av förstörande kodning tappar en liten mängd detaljer. Vid normala inställningar är det inget de flesta märker när de lyssnar, och du kan höja bithastigheten under avancerade inställningar. Det du bör undvika är att konvertera samma fil fram och tillbaka gång på gång — det är det som gör förlusten hörbar.',
    'quality.lossyToLossy.a.visual': 'En aning. Båda formaten är förstörande, så {{fn}} avkodas och kodas sedan om som {{tn}}, och varje generation av förstörande kodning tappar en liten mängd detaljer. Vid normala inställningar är det inget de flesta märker, och du kan höja kvaliteten under avancerade inställningar. Det du bör undvika är att konvertera samma fil fram och tillbaka gång på gång — det är det som gör förlusten synlig.',
    'quality.losslessToLossless.q': 'Förlorar jag kvalitet när jag konverterar {{fn}} till {{tn}}?',
    'quality.losslessToLossless.a.plain': 'Nej. Både {{fn}} och {{tn}} är förlustfria, så {{unit}} bevaras exakt och resultatet är identiskt med originalet. Bara filstorleken ändras. Du kan konvertera tillbaka senare utan någon som helst försämring.',
    'quality.losslessToLossless.a.bulky': 'Nej. Både {{fn}} och {{tn}} är förlustfria, så {{unit}} bevaras exakt och resultatet är identiskt med originalet. Bara filstorleken ändras, vanligtvis dramatiskt nedåt, eftersom {{fn}} lagrar sina data i praktiken okomprimerade. Du kan konvertera tillbaka senare utan någon som helst försämring.',
    'quality.fallback.q': 'Förlorar jag kvalitet när jag konverterar {{fn}} till {{tn}}?',
    'quality.fallback.a': 'För vanliga filer är resultatet visuellt och funktionellt likvärdigt med originalet. Där de två formaten stöder olika saker behåller konverteringen allt som {{tn}} klarar av att representera. Med avancerade inställningar kan du höja kvaliteten om standardavvägningen inte är den du vill ha.',

    'relation.uncompressed.q': 'Varför är {{tn}}-filen så mycket större än {{fn}}-filen?',
    'relation.uncompressed.a': 'För att {{tn}} är okomprimerat. {{fn}} krymper ljud genom att kasta data och koda resten effektivt; {{tn}} skriver ut varje sampling i full storlek, vilket blir ungefär 10 MB per minut stereo i cd-kvalitet. En tiodubbling är normal och väntad — det är priset för en fil som redigeringsprogram kan bearbeta utan att först avkoda något. Vill du ha förlustfritt ljud på ungefär halva storleken ska du konvertera till FLAC i stället.',
    'relation.extractAudio.q': 'Behåller det här videon, eller bara ljudet?',
    'relation.extractAudio.a': 'Bara ljudet. Ljudspåret plockas ur {{fn}}-filen och sparas som {{tn}}; videospåret kastas, och därför blir resultatet en bråkdel av originalstorleken. Själva ljudet spelas inte in på nytt, så det behåller den kvalitet det hade inuti {{fn}}-filen — att plocka ur en video med låg bithastighet kan inte ge ljud med hög bithastighet.',
    'relation.videoContainer.q': 'Kommer min {{tn}} att spelas upp på telefoner, tv-apparater och i sociala medier?',
    'relation.videoContainer.a.mp4': 'Det är precis vad den här konverteringen är till för. MP4 med H.264-video är det närmaste ett universellt videoformat man kommer: iPhone, Android-telefoner, smarta tv-apparater, varje webbläsare, Instagram, YouTube, TikTok och varje gängse redigeringsprogram tar emot det utan extra kodekar. {{fn}} var formatet som krånglade; MP4 är det som inte gör det.',
    'relation.videoContainer.a.other': '{{tn}} är mer specialiserat än MP4. {{note}} Om ditt mål helt enkelt är att det ska ”spelas överallt” är MP4 det säkrare valet — ta {{tn}} när ett bestämt program eller en bestämd apparat har bett om det.',
    'relation.alphaLost.q': 'Vad händer med genomskinligheten när {{fn}} görs om till {{tn}}?',
    'relation.alphaLost.a': '{{tn}} har ingen alfakanal, så genomskinliga ytor kan inte följa med — de fylls med en enfärgad bakgrund (vit som standard) under konverteringen. Om den genomskinliga bakgrunden gör verklig nytta i din formgivning ska du konvertera till PNG eller WebP i stället, som båda bevarar den. Är bilden ett fotografi utan någon genomskinlighet alls gör det här ingen skillnad.',
    'relation.alphaGained.q': 'Blir bakgrunden genomskinlig av att göra om {{fn}} till {{tn}}?',
    'relation.alphaGained.a': 'Nej — och det här går många på. {{tn}} stöder genomskinlighet, men en {{fn}}-fil har ingen genomskinlighetsinformation att föra över, så bakgrunden förblir precis som den var. Det konverteringen ger dig är en fil som kan bära genomskinlighet när du väl friläggt bakgrunden i en bildredigerare, plus förlustfria pixlar som inte försämras medan du arbetar.',
    'relation.reflow.q': 'Fungerar {{tn}} på min läsplatta?',
    'relation.reflow.a.epub': 'EPUB läses av Apple Books, Kobo, Google Play Böcker, Calibre och i stort sett varje läsplatta utom Kindle, som vill ha MOBI eller AZW3 (Kindle tar numera även emot EPUB via e-post). Eftersom texten flödar om kan du ändra teckenstorlek på enheten utan att sluta med att scrolla i sidled — vilket är hela poängen med att konvertera en {{fn}} från början.',
    'relation.reflow.a.kindle': '{{tn}} läses av de Kindle-enheter och -appar som det utformades för. Eftersom texten flödar om kan du ändra teckenstorlek på enheten utan att sluta med att scrolla i sidled — vilket är hela poängen med att konvertera en {{fn}} från början.',

    'compatibility.q': 'Vad kan öppna {{tn}}-filen efteråt?',
    'compatibility.a': '{{note}} Ingenting behöver installeras för att göra konverteringen — den körs på våra servrar, och den färdiga {{tn}}-filen kommer tillbaka i din webbläsare redo att öppna, redigera eller skicka vidare. Din ursprungliga {{fn}}-fil ändras aldrig; vi lämnar alltid bara tillbaka en ny fil.',
    'compatibility.noteFallback': '{{tn}} har brett stöd.',

    'shapeFaq.pdf-merge.q1': 'Försämrar sammanfogningen kvaliteten på mina PDF-filer?',
    'shapeFaq.pdf-merge.a1': 'Nej. Sidorna kopieras in i det nya dokumentet precis som de är i stället för att ritas om, så texten går fortfarande att markera och bilderna behåller sin ursprungliga upplösning. Den sammanfogade filen blir ungefär lika stor som originalen tillsammans — kör den genom Komprimera PDF efteråt om det spelar roll.',
    'shapeFaq.pdf-merge.q2': 'Hur många PDF-filer kan jag slå ihop på en gång, och spelar ordningen roll?',
    'shapeFaq.pdf-merge.a2': 'Du kan lägga till hur många filer du behöver på en gång, och ordningen spelar absolut roll: det färdiga dokumentet följer ordningen i listan, som du kan dra om innan du slår ihop. Ställ ordningen först och slå ihop sedan — det går fortare än att rätta till det efteråt.',
    'shapeFaq.pdf-split.q1': 'Hur väljer jag vilka sidor som ska plockas ut?',
    'shapeFaq.pdf-split.a1': 'Skriv in dem i fältet för sidintervall med kommatecken och bindestreck: ”1-3, 5, 7-10” ger dig sidorna ett till tre, sidan fem och sidorna sju till tio i ett enda utdatadokument. Numren avser PDF-filens egna sidor, räknat från ett, vilket inte alltid är det nummer som står tryckt på sidan.',
    'shapeFaq.pdf-split.q2': 'Ändrar delningen den ursprungliga PDF-filen?',
    'shapeFaq.pdf-split.a2': 'Nej. Filen du laddar upp ändras aldrig — de uttagna sidorna skrivs till ett nytt dokument och originalet lämnas orört, innan det raderas från våra servrar inom 24 timmar tillsammans med resultatet.',
    'shapeFaq.pdf-compress.q1': 'Hur mycket mindre blir min PDF?',
    'shapeFaq.pdf-compress.a1': 'Det beror helt på vad som finns i den. PDF-filer som domineras av skanningar eller fotografier krymper ofta med 50–90 %, för det är där nästan hela storleken sitter. En PDF med bara text är redan kompakt och kanske knappt ändras alls. Text och vektorgrafik förblir knivskarpa i båda fallen — besparingen kommer av att bilder kodas om och att överflödiga inbäddade data plockas bort.',
    'shapeFaq.pdf-compress.q2': 'Går texten fortfarande att markera och söka i?',
    'shapeFaq.pdf-compress.a2': 'Ja. Komprimeringen arbetar på de inbäddade bilderna och på överflödiga interna data; textlagret, teckensnitten, länkarna och bokmärkena lämnas orörda, så du kan fortfarande söka, markera och kopiera ur den komprimerade filen precis som förut.',
    'shapeFaq.pdf-compress-ai.q1': 'Hur skiljer sig det här från vanlig PDF-komprimering?',
    'shapeFaq.pdf-compress-ai.a1': 'Vanlig komprimering lägger en och samma inställning över hela filen. Det här verktyget tittar först på vad varje sida faktiskt innehåller, så att fotografiska bilder, platta diagram och rena textsidor var för sig hanteras på det sätt som sparar mest utrymme utan att synligt försämra dem. I blandade dokument betyder det oftast en mindre fil vid samma upplevda kvalitet.',
    'shapeFaq.pdf-compress-ai.q2': 'Går texten fortfarande att markera och söka i?',
    'shapeFaq.pdf-compress-ai.a2': 'Ja. Textlagret, teckensnitten, länkarna och bokmärkena bevaras — bara de inbäddade bilderna och överflödiga interna data kodas om, så den komprimerade PDF-filen förblir fullt sökbar och kopierbar.',
    'shapeFaq.pdf-rotate.q1': 'Går någon kvalitet förlorad när en PDF roteras?',
    'shapeFaq.pdf-rotate.a1': 'Inte alls. Rotationen ändrar den sidgeometri som står i filen i stället för att rita om något, så texten förblir vektorskarp, bilderna är orörda och filstorleken knappt rör sig. Du kan rotera igen senare utan någon ackumulerad skada.',
    'shapeFaq.pdf-rotate.q2': 'Kan jag rotera bara vissa sidor?',
    'shapeFaq.pdf-rotate.a2': 'Den rotation du väljer — 90°, 180° eller 270° — tillämpas på dokumentet. Om olika sidor är fel åt olika håll är det vanliga tillvägagångssättet att dela PDF-filen, rotera varje del den vinkel den behöver och sedan slå ihop resultaten igen med verktyget Slå ihop PDF.',
    'shapeFaq.pdf-protect.q1': 'Vad händer om jag glömmer lösenordet?',
    'shapeFaq.pdf-protect.a1': 'Filen går inte att öppna. Krypteringen tillämpas på själva PDF-filen, så det finns ingen återställningslänk och ingen bakdörr — varken för dig eller för oss. Förvara lösenordet på ett säkert ställe innan du skickar dokumentet vidare, och skicka det via en annan kanal än filen.',
    'shapeFaq.pdf-protect.q2': 'Hur starkt är skyddet?',
    'shapeFaq.pdf-protect.a2': 'PDF-filen krypteras med den branschstandard som är inbyggd i formatet, så dess innehåll kan inte läsas utan lösenordet av någon läsare som följer standarden. Den praktiska svaga punkten är aldrig algoritmen utan själva lösenordet — ett kort eller självklart lösenord gissas snabbt, så använd ett långt till allt som verkligen är känsligt.',
    'shapeFaq.pdf-unlock.q1': 'Kan det här ta bort ett lösenord som jag inte känner till?',
    'shapeFaq.pdf-unlock.a1': 'Nej. Du måste ange det nuvarande lösenordet; verktyget dekrypterar filen med det snarare än att knäcka krypteringen. Det är avsett för dokument du äger eller har rätt att öppna — ett kontoutdrag från din egen bank, till exempel — där begränsningen bara står i vägen.',
    'shapeFaq.pdf-unlock.q2': 'Vad kan jag göra med filen efteråt?',
    'shapeFaq.pdf-unlock.a2': 'Allt som skyddet blockerade: öppna den utan fråga, skriva ut den, kopiera text ur den och redigera den i andra program. Själva sidinnehållet är oförändrat — bara krypteringslagret och dess användningsbegränsningar tas bort.',
    'shapeFaq.metadata.q1': 'Ändrar det här min fil på något sätt?',
    'shapeFaq.metadata.a1': 'Nej. Filen läses, inte konverteras — ingenting skrivs tillbaka och ingenting nytt skapas utöver informationen på skärmen. Det är det säkraste verktyget här att rikta mot en fil du är osäker på.',
    'shapeFaq.metadata.q2': 'Vilken sorts information får jag se?',
    'shapeFaq.metadata.a2': 'Det beror på filen. Bilder visar mått, färgdjup och EXIF-data som kameramodell, objektiv, exponering och, när kameran registrerade dem, GPS-koordinater. Ljud visar längd, bithastighet, samplingsfrekvens och antal kanaler. Video lägger till kodek, upplösning och bildfrekvens. Dokument visar sidantal, författare, producent och skapandedatum.',
    'shapeFaq.ocr.q1': 'Hur träffsäker är textigenkänningen?',
    'shapeFaq.ocr.a1': 'En ren, rak skanning av tryckt text i rimlig upplösning känns igen mycket träffsäkert. Träffsäkerheten sjunker med sneda eller suddiga sidor, kontrastsvaga fotografier, ovanliga teckensnitt och handskrift. Att välja rätt språk spelar roll, eftersom igenkänningen använder det för att avgöra tvetydiga tecken.',
    'shapeFaq.ocr.q2': 'Vad är skillnaden mellan den sökbara PDF-filen och utdata i ren text?',
    'shapeFaq.ocr.a2': 'Den sökbara PDF-filen behåller den ursprungliga sidbilden exakt som den ser ut och lägger ett osynligt textlager under den, så dokumentet ser oförändrat ut men går nu att söka i och kopiera ur — det är vad du vill ha för arkivering. Ren text kastar layouten och ger dig bara orden, vilket är vad du vill ha för redigering, skript eller för att mata in i ett annat program.',
    'shapeFaq.tts.q1': 'Hur naturliga låter rösterna?',
    'shapeFaq.tts.a1': 'Det här är neurala röster och inte den äldre ihopklippta talsyntesen, så de bär satsmelodi och naturliga pauser i stället för att läsa ord för ord. Sex röster finns att välja på, från neutral till varm till auktoritativ, och taltempot går att ställa in. Skiljetecken betyder mer än man tror: kommatecken och punkter formar frasering, så välinterpungerad text läses upp märkbart bättre.',
    'shapeFaq.tts.q2': 'Hur mycket text kan jag konvertera på en gång?',
    'shapeFaq.tts.a2': 'Upp till 4096 tecken per konvertering — grovt räknat 600 till 700 ord, eller ungefär fem minuters tal. För längre texter delar du vid ett naturligt ställe som en kapitel- eller avsnittsrubrik och konverterar varje del för sig; röst- och tempoinställningarna är desamma mellan körningarna, så bitarna fogas ihop rent.',
    'shapeFaq.stt.q1': 'Hur träffsäker är utskriften?',
    'shapeFaq.stt.a1': 'Tydligt tal i en någorlunda tyst miljö skrivs ut mycket träffsäkert, även vid ett brett spektrum av brytningar. Träffsäkerheten faller vid kraftigt bakgrundsljud, när flera personer pratar i mun på varandra, eller vid mycket specialiserad jargong och egennamn. Att ange det talade språket i stället för att låta det upptäckas automatiskt hjälper märkbart.',
    'shapeFaq.stt.q2': 'Kan jag spela in direkt från mikrofonen?',
    'shapeFaq.stt.a2': 'Ja — inspelaren på den här sidan fångar ljud direkt i webbläsaren, vilket ofta går snabbare än att först leta upp en inspelningsapp. Din webbläsare frågar efter mikrofonbehörighet första gången. Du kan också ladda upp en befintlig fil, och utskriften visas på sidan så att du kan läsa den innan du laddar ner den som TXT eller DOCX.',
    'shapeFaq.subtitle.q1': 'Hur träffsäkra är de genererade undertexterna?',
    'shapeFaq.subtitle.a1': 'Tydligt tal skrivs ut mycket träffsäkert, även med brytning. Bakgrundsmusik, överlappande prat och specialiserad terminologi är där felen smyger sig in, och att ange det talade språket i stället för att upptäcka det automatiskt hjälper. Utdata är en undertextfil i ren text, så att rätta ett och annat ord tar sekunder i vilken textredigerare som helst.',
    'shapeFaq.subtitle.q2': 'Ska jag välja SRT eller VTT?',
    'shapeFaq.subtitle.a2': 'SRT är det säkrare standardvalet: YouTube, Vimeo, Premiere, Final Cut, VLC och praktiskt taget varje spelare tar emot det. Välj VTT om undertexterna ska till en HTML5-videospelare på en webbplats, eftersom WebVTT är det format webbläsarens inbyggda undertextspår förväntar sig och det stöder stilsättning och positionering som SRT inte kan uttrycka.',
    'shapeFaq.soon.q1': 'När kommer det här att finnas?',
    'shapeFaq.soon.a1': 'Det byggs aktivt just nu. Verktyget dyker upp här och börjar ta emot filer så snart det är klart — ingenting behöver installeras eller aktiveras hos dig.',
    'shapeFaq.soon.q2': 'Vad kan jag använda under tiden?',
    'shapeFaq.soon.a2': 'Resten av konverteraren är fullt tillgänglig: dokument, bilder, ljud, video, arkiv, GIF-filer och PDF-verktygslådan fungerar allihop i dag, liksom de smarta funktionerna för OCR, utskrift och undertexter.',
    'shapeFaq.compress.q1': 'Är den komprimerade filen fortfarande en {{fn}}?',
    'shapeFaq.compress.a1': 'Ja — formatet ändras inte, bara storleken. Det du laddar ner är en vanlig {{fn}} som öppnas överallt där originalet gjorde det.{{alpha}} Hur mycket du sparar beror på källmaterialet: {{source}}.',
    'shapeFaq.compress.alpha': ' Genomskinlighet och animering bevaras.',
    'shapeFaq.compress.source.png': 'skärmbilder och platt gränssnittsgrafik komprimeras dramatiskt, medan fotografier sparade som PNG ger mindre',
    'shapeFaq.compress.source.gif': 'långa animeringar och stökigt material komprimeras mest, eftersom det finns mer upprepning att plocka bort',
    'shapeFaq.compress.source.other': 'fotografier komprimeras bra, medan bilder som redan var hårt komprimerade har mindre kvar att ge',
    'shapeFaq.compress.q2': 'Hur mycket mindre blir filen?',
    'shapeFaq.compress.a2': 'Vanligtvis någonstans mellan en tredjedel och en tiondel av originalet, helt beroende på vad filen innehåller och hur den sparades från början. När konverteringen är klar visar sidan storleken före och efter bredvid varandra, så du ser den faktiska besparingen i stället för att gissa.',
    'shapeFaq.hub.q1': 'Mellan vilka format kan jag konvertera?',
    'shapeFaq.hub.a1': 'Indata: {{inputs}}. Utdata: {{outputs}}. Vilken indata som helst kan gå till vilken utdata som helst, så du behöver inte leta upp en egen sida för varje kombination — välj filen, välj målformatet, konvertera.',
    'shapeFaq.hub.q2': 'Förlorar jag kvalitet?',
    'shapeFaq.hub.a2': 'Det beror på paret. Att gå till ett förlustfritt format behåller allt men ger en större fil; att gå till ett komprimerat format kastar avsiktligt data i utbyte mot storlek, och med avancerade inställningar bestämmer du var på den avvägningen du vill ligga. Att konvertera mellan två komprimerade format tappar lite detaljer varje gång, så det lönar sig att behålla originalet som mallkopia.',
    'shapeFaq.hub-extract.q1': 'Behålls videon också?',
    'shapeFaq.hub-extract.a1': 'Nej — bara ljudet. Ljudspåret lyfts ur videon och sparas för sig, och därför blir resultatet en bråkdel av den ursprungliga filstorleken. Ljudet spelas inte in på nytt, så det behåller den kvalitet det redan hade inuti videon; att plocka ur ett klipp med låg bithastighet kan inte ge ljud med hög bithastighet.',
    'shapeFaq.hub-extract.q2': 'Vilket utdataformat bör jag välja?',
    'shapeFaq.hub-extract.a2': 'MP3 för maximal kompatibilitet — det spelas på varje telefon, bilstereo och spelare. AAC eller M4A om målet är en Apple-enhet eller en modern app, eftersom de låter något bättre vid samma bithastighet. WAV eller FLAC bara om du tänker redigera ljudet, eftersom båda är förlustfria och därmed stora.',
    'shapeFaq.hub-gif.q1': 'Varför ser GIF-filen sämre ut än originalet?',
    'shapeFaq.hub-gif.a1': 'För att GIF bara tillåter 256 färger per bildruta, medan video och fotografier innehåller miljoner. Kodaren väljer en palett och approximerar resten, vilket syns som band i övergångar och himlar. GIF bär dessutom inget ljud alls. Båda gränserna hör till formatet och inte till konverteringen.',
    'shapeFaq.hub-gif.q2': 'Varför är min GIF-fil så stor?',
    'shapeFaq.hub-gif.a2': 'GIF komprimerar långt sämre än moderna videokodekar, så filstorleken växer snabbt med längd, upplösning och bildfrekvens. Några sekunder är den söta punkten. Blir resultatet för tungt kortar du klippet, och väger storleken tyngre än inbäddad automatisk uppspelning kommer en MP4 att visa samma animering på en bråkdel av storleken.',
  },
};
