// Turkish content pack. Mirrors packs/en.js key for key — see the header there.
// Turkish suffixes harmonise with the preceding vowel, which a placeholder
// cannot know, so format names are followed by a separate word ("{{fn}} dosyası",
// "{{tn}} biçimine") rather than by a directly attached case ending.
export default {
  lang: 'tr',
  formats: {
    pdf: { about: 'PDF sabit yerleşimli bir biçimdir: her karakterin, her çizginin ve her görüntünün tam konumunu saklar, bu yüzden her ekranda ve her yazıcıda birebir aynı görünür ama düzenlemesi zahmetlidir.', note: 'PDF sayfalamayı, yazı tiplerini ve yerleşimi kilitler, böylece alıcı tam olarak gönderdiğin şeyi görür.' },
    docx: { about: 'DOCX, Microsoft Word’ün çağdaş biçimidir; metin sabit sayfa koordinatlarına çakılmak yerine düzenlenebilir paragraflarda ve stillerde yaşar.', note: 'DOCX sana Word, Google Dokümanlar veya LibreOffice içinde gerçekten düzenlenebilir paragraflar, değişiklik izleme ve yorumlar verir.' },
    xlsx: { about: 'XLSX, Excel’in hesap tablosu biçimidir; her değer, sıralanabilen, süzülebilen ve bir formülde kullanılabilen adreslenebilir bir hücrede oturur.', note: 'Veriler bir kez XLSX’e girdiğinde onları yeniden yazmak yerine toplayabilir, sıralayabilir, özet tabloya dökebilir ve grafiğe çevirebilirsin.' },
    pptx: { about: 'PPTX bir sunuyu ayrı slaytlar olarak saklar; düzenlenebilir metin kutuları, şekiller, konuşmacı notları ve geçişlerle birlikte.', note: 'PPTX sana gerçekten yeniden düzenleyebileceğin, sıralayabileceğin ve yeniden sunabileceğin slaytlar verir.' },
    txt: { about: 'Bir TXT dosyası karakterlerden başka bir şey değildir — yazı tipi yok, görüntü yok, sayfa yapısı yok — bu da onu minicik, her yerde okunabilir ve arama açısından son derece kolay kılar.', note: 'TXT sözcükler dışında her şeyi söker atar ve betiklerin, arama dizinlerinin ve metin düzenleyicilerin istediği tam da budur.' },
    html: { about: 'HTML, web’in işaretleme dilidir: bir tarayıcının başlıklara, paragraflara, bağlantılara ve görüntülere dönüştürdüğü, etiketlerle sarılmış metin.', note: 'HTML her tarayıcıda açılır ve doğrudan bir siteye ya da içerik yönetim sistemine yapıştırılabilir.' },
    rtf: { about: 'RTF, düz metin üzerine kurulu açık bir belge biçimidir; temel biçimlendirmeyi — kalın, eğik, yazı tipleri, tablolar — yanında taşır ama seni tek bir kelime işlemciye kilitlemez.', note: 'RTF, Word’de, Pages’te, LibreOffice’te, WordPad’de ve şimdiye kadar yazılmış hemen her kelime işlemcide açılır.' },
    odt: { about: 'ODT, LibreOffice ve OpenOffice’in kullandığı OpenDocument metin biçimidir ve tek bir üreticinin biçimi değil, bir ISO standardıdır.', note: 'ODT, LibreOffice ve OpenOffice’in kendi, tümüyle düzenlenebilir biçimidir.' },
    epub: { about: 'EPUB akıcı metinli bir e-kitap biçimidir: sabit sayfa boyutu yoktur, bu yüzden metin okuyucunun kullandığı ekrana ve yazı boyutuna göre yeniden sarılır.', note: 'EPUB okuyucunun yazı boyutunu değiştirmesine ve metnin yeniden akmasına izin verir; uzun belgeleri telefonda ya da okuyucuda rahat kılan da tam olarak budur.' },
    jpg: { about: 'JPG, fotoğraflar için ayarlanmış kayıplı sıkıştırma kullanır: gözün en az fark ettiği ayrıntıları atar, bu da fotoğrafları küçültür ama keskin kenarların ve metnin çevresine yumuşak, blok blok bozulmalar ekler.', note: 'JPG kelimenin tam anlamıyla her yerde açılan küçük dosyalar üretir; bedeli, kalıcı olarak atılan bir miktar ayrıntı ve saydamlığın bulunmayışıdır.' },
    jfif: { about: 'JFIF, farklı bir uzantıyla kaydedilmiş bir JPEG görüntüsüdür; içindeki pikseller sıradan JPEG verisidir, ama Windows dosyayı istediğin uygulamaya teslim etmeyi çoğu zaman reddeder.', note: 'JFIF aslında başka bir adla JPEG’den ibarettir.' },
    png: { about: 'PNG kayıpsızdır: her pikseli tam olarak saklar, saydamlık için tam bir alfa kanalını destekler ve yeniden kaydettiğinde asla bozulmaz; ekran görüntüleri, logolar ve arayüz grafikleri için ilk tercih olmasının nedeni de budur.', note: 'PNG her pikseli olduğu gibi korur ve gerçek saydamlığı destekler, bu yüzden tekrar tekrar düzenlemeye bozulmadan dayanır.' },
    webp: { about: 'WebP, Google’ın çağdaş web görüntü biçimidir; benzer kalitede JPG’den ya da PNG’den gözle görülür ölçüde daha çok sıkıştırır, saydamlığı ve canlandırmayı destekler, ama pek çok masaüstü ve matbaa yazılımı onu hâlâ açamaz.', note: 'WebP, yaygın web biçimleri arasında en küçük dosyaları üretir ve saydamlığı destekler.' },
    bmp: { about: 'BMP ham, neredeyse hiç sıkıştırılmamış piksel verisi saklar; bu onu kusursuz sadık ve muazzam savurgan kılar — bir fotoğraf, aynı görüntünün PNG hâlinden rahatlıkla on kat büyük olabilir.', note: 'BMP ham ve sıkıştırılmamıştır; eski Windows yazılımının ve bazı tarayıcıların hâlâ beklediği tam olarak budur.' },
    tiff: { about: 'TIFF, arşivleme ve baskı öncesi hazırlığın biçimidir: kayıpsız, yüksek renk derinlikli, birden çok sayfa ya da katman taşıyabilen — ve buna uygun biçimde hacimli.', note: 'TIFF, matbaaların ve arşivlerin istediği biçimdir, çünkü hiçbir şey atılmaz.' },
    gif: { about: 'GIF kare başına 256 renkle sınırlıdır, fotoğrafların içinde bantlı görünmesinin nedeni budur; buna karşılık canlanır ve internette hemen her yerde gömülü olarak kendiliğinden oynar.', note: 'GIF sohbet uygulamalarında, talep sistemlerinde ve forumlarda gömülü olarak kendiliğinden oynar, ama kare başına 256 renkle sınırlıdır.' },
    ico: { about: 'ICO, aynı görseli birden çok boyutta bir arada tutan bir Windows simge kabıdır; böylece sistem bir sekme için 16×16, bir masaüstü kısayolu için 256×256 seçebilir.', note: 'ICO birden çok çözünürlüğü tek dosyada toplar; site simgelerinin ve Windows uygulama simgelerinin ihtiyacı tam olarak budur.' },
    heic: { about: 'HEIC, iPhone’ların fotoğrafları öntanımlı olarak kaydettiği biçimdir; JPG ile aşağı yukarı aynı kaliteyi yaklaşık yarı yerde verir, ama Windows, pek çok web formu ve bir yığın eski yazılım onu açmayı düpedüz reddeder.', note: 'HEIC derli topludur ama Apple aygıtlarının dışında zayıf desteklenir.' },
    svg: { about: 'SVG piksellerden hiç oluşmaz — şekilleri, yolları ve metni betimleyen bir XML’dir, bu yüzden her boyutta kusursuz keskin kalır ve kodla düzenlenebilir ya da yeniden biçemlendirilebilir.', note: 'SVG, piksel yerine şekil sakladığı için hiç bulanıklaşmadan her boyuta ölçeklenir.' },
    mp4: { about: 'MP4 bir kaptır — genellikle AAC sesli H.264 videosu — ve telefonların, tarayıcıların, televizyonların, kurgu programlarının ve sosyal platformların hepsinin üzerinde anlaştığı tek video biçimidir.', note: 'MP4 fiilen her telefonda, tarayıcıda, televizyonda ve kurgu programında ek yazılım olmadan oynar.' },
    avi: { about: 'AVI, Microsoft’un doksanlardan kalma bir kabıdır; eski oynatıcılar ve kurgu paketleri hâlâ okur, ama çağdaş akış özellikleri yoktur ve dosyaları genellikle MP4’ten çok daha büyük olur.', note: 'AVI, eski oynatıcıların, DVD hazırlama araçlarının ve köhne kurgu yazılımının beklediği biçimdir.' },
    mov: { about: 'MOV, Apple’ın QuickTime kabıdır; iPhone ve Mac’in kayıt yaptığı, Final Cut Pro ile iMovie’nin en rahat başa çıktığı biçimdir.', note: 'MOV, Apple’ın kurgu araçlarının en pürüzsüz çalıştığı kaptır.' },
    mkv: { about: 'MKV (Matroska), tek dosyada istediğin kadar video, ses ve altyazı izini barındırabilen açık bir kaptır — arşivleme için mükemmel, ama telefonların, televizyonların ve tarayıcıların çoğu tarafından reddedilir.', note: 'MKV tek bir dosyada birden çok ses ve altyazı izi taşıyabilir.' },
    webm: { about: 'WebM, HTML5 videosu için yapılmış telifsiz kaptır, genellikle VP9 ya da AV1 ile; tarayıcılar ona bayılır, ama masaüstü kurgu programları ve Apple yazılımı çoğu zaman ona el bile sürmez.', note: 'WebM küçüktür ve tarayıcılarda kendiliğinden akar.' },
    wmv: { about: 'WMV, Microsoft’un Windows Media video biçimidir; fiilen yalnızca Windows’a özgüdür ve eski kurumsal kayıtlar ile ekran kayıtları dışında büyük ölçüde terk edilmiştir.', note: 'WMV, başka yerlerde desteği çok zayıf bir Windows Media biçimidir.' },
    flv: { about: 'FLV, Flash videosunun arkasındaki kaptı; Flash her tarayıcıdan kaldırıldığından beri fiilen oynatılamayan bir arşiv biçimidir.', note: 'FLV, Flash döneminden kalma ölü bir kaptır.' },
    mp3: { about: 'MP3 kayıplıdır: kodlayıcı, duymayacağını öngördüğü sinyal parçalarını kalıcı olarak siler; bu da bir parçayı kabaca onda birine indirir ve gerçekten her şeyde oynamasının nedenidir.', note: 'MP3, sıkıştırılmamış sesten yaklaşık on kat küçüktür ve son yirmi yılın her telefonunda, araç teybinde ve oynatıcısında çalar.' },
    wav: { about: 'WAV sesi sıkıştırmadan, örnek örnek, tam kaydedildiği gibi saklar — stüdyoların kullanma nedeni budur ve CD kalitesinde bir dakikalık stereo sesin yaklaşık 10 MB yer kaplamasının nedeni de budur.', note: 'WAV sıkıştırılmamış ve kayıpsızdır, böylece kurgu ve mastering programları önce hiçbir şeyi çözmeden onu işleyebilir.' },
    flac: { about: 'FLAC sesi kayıpsız sıkıştırır: WAV’ın kabaca yarısı kadar yer kaplar ama yine de özgün kaydın bit bit aynısı olan bir kopyaya geri çözülür.', note: 'FLAC bit bit aynıdır ama WAV’ın kabaca yarısı kadar yer kaplar.' },
    aac: { about: 'AAC, Apple Music’in, YouTube’un ve çoğu akış hizmetinin arkasındaki kayıplı kodektir; aynı bit hızında genellikle MP3’ten daha iyi duyulur.', note: 'AAC aynı bit hızında MP3’ten daha iyi duyulur ve Apple ile akış dünyasında standarttır.' },
    ogg: { about: 'OGG Vorbis, oyunların, açık kaynak yazılımların ve Vikipedi’nin gözdesi olan patentsiz bir kayıplı kodektir; daha küçük boyutta MP3 ile kıyaslanabilir kalite sunar.', note: 'OGG patent kısıtlarından muaftır; oyun motorlarının ve açık kaynak projelerinin onu yeğlemesinin nedeni budur.' },
    m4a: { about: 'M4A, yalnızca ses barındıran bir MP4 kabıdır, normalde AAC ile — iTunes’un, Apple Music’in ve iPhone ses notlarının ürettiği biçim.', note: 'M4A, Apple ekosisteminin standart ses dosyasıdır.' },
    wma: { about: 'WMA, Microsoft’un Windows Media Player döneminden kalma kayıplı ses kodeğidir; Windows dışında ender desteklenir ve fiilen sonlandırılmıştır.', note: 'WMA, yalnızca Windows’ta yaşayan eskimiş bir ses kodeğidir.' },
    zip: { about: 'ZIP, Windows’a, macOS’e ve her telefona gömülü arşiv biçimidir — çift tıklamak yeter, fazladan hiçbir şey kurmadan.', note: 'ZIP, Windows’ta, macOS’te, Linux’ta, iOS’te ve Android’de hiçbir şey kurmadan çift tıklamayla açılır.' },
    rar: { about: 'RAR, iyi sıkıştırma ve kurtarma kayıtları olan kapalı bir arşiv biçimidir, ama açmak için WinRAR ya da uyumlu bir araç gerekir.', note: 'RAR’ın açılması için üçüncü taraf yazılım gerekir.' },
    '7z': { about: '7Z, ZIP’ten düzenli olarak gözle görülür ölçüde küçük arşivler üreten LZMA sıkıştırmasını kullanır — bedeli, açmak için 7-Zip ya da uyumlu bir araç gerektirmesidir.', note: '7Z, ZIP’ten belirgin biçimde daha sıkı sıkıştırır; büyük klasörlerde ve ücretli bulut depolamada bunun önemi vardır.' },
    tar: { about: 'Bir TAR dosyası çok sayıda dosyayı sıkıştırmadan tek bir dosyada toplar; Unix dünyasından gelir ve izinleri ile dizin yapısını korur.', note: 'TAR, Unix izinlerini ve dizin yapısını korur.' },
    gz: { about: 'GZ (gzip) tek bir veri akışını sıkıştırır; Linux sunucularının ve komut satırı araçlarının ürettiği şeydir. Windows’ta ek yazılım olmadan açması zahmetlidir.', note: 'GZ, Linux’ta ve web sunucularında standart sıkıştırma biçimidir.' },
    srt: { about: 'SRT, her kurgu programının ve her oynatıcının anladığı düz metin altyazı biçimidir: numaralı replikler, bir zaman kodu aralığı ve diyalog satırı.', note: 'SRT’yi YouTube, Vimeo, Premiere, Final Cut ve her yaygın oynatıcı kabul eder.' },
    avif: {
      about: "AVIF, AV1 video kodeğine dayanan modern bir görsel biçimidir; belirli bir kalitede elde edilebilecek en küçük dosyalardan bazılarını üretir ve saydamlığı destekler, ancak eski yazılımlar onu çoğu zaman açamaz.",
      note: "AVIF sana modern tarayıcılar ve uygulamalar için iyi kalitede çok küçük dosyalar verir.",
    },
    md: {
      about: "Markdown, hafif biçimlendirme işaretleri taşıyan düz metindir — başlıklar için #, vurgu için *, listeler için - — ham metin olarak okunabilir kalır ve biçimlendirilmiş bir belgeye dönüştürülebilir.",
      note: "Markdown içeriğini, düzenlemesi ve sürüm denetiminde izlemesi kolay, yalın metin olarak tutar.",
    },
    aif: {
      about: "AIF, Apple’ın sıkıştırılmamış ses biçimi AIFF’in kısa uzantısıdır: her örnek tam kaydedildiği gibi saklanır, bu da stüdyo kalitesi ve çok büyük dosyalar demektir.",
      note: "AIF sesi sıkıştırılmamış ve bir Mac’te düzenlemeye hazır tutar.",
    },
  },
  reasons: {
    'pdf-to-word': 'Alışılmış tetikleyici, PDF’in kendi içinde yapamadığın bir değişikliktir — bir sözleşme maddesi, bir özgeçmiş satırı ya da tüm belgeyi yeniden yazmadan değişmesi gereken bir rapor paragrafı.',
    'word-to-pdf': 'Word, bir belgenin ömrünün tam sonunda PDF’e çevrilir: yazı tiplerini, Word sürümünü ve kenar boşluklarını denetleyemediğin birine özgeçmiş, teklif ya da imzalı form giderken.',
    'pdf-to-excel': 'Tipik durum, yalnızca PDF olarak var olan ama sayılarını toplaman, sıralaman ya da grafiğe dökmen gereken bir banka ekstresi, fatura ya da rapordur.',
    'excel-to-pdf': 'Bunu, bir bütçeyi ya da fiyat listesini okuması gereken ama değiştirmemesi gereken birine göndermeden önce ve baskıdan önce yaparsın — PDF, Excel’in aksi hâlde her makinede yeniden hesaplayacağı sayfa sonlarını çakar.',
    'pptx-to-pdf': 'Çoğu kişi bir sunuyu göndermeden ya da dağıtmadan önce PDF’e çevirir; böylece slaytlar kaymaz ve açmak için kimsenin kurulu PowerPoint’e ihtiyacı olmaz.',
    'pdf-to-pptx': 'Bu, bir sunudan geriye kalan tek kopyanın toplantıdan sonra dolaşıma giren PDF olduğu ve slaytları güncellemen ya da yeniden kullanman gerektiği durumda gerekir.',
    'pdf-to-txt': 'Yaygın nedenler: bir belgeyi bir betiğe, bir arama dizinine ya da bir yapay zekâ aracına vermek, ya da uzun bir raporu arayabileceğin, karşılaştırabileceğin ve her yere yapıştırabileceğin bir şeye indirgemek.',
    'pdf-to-html': 'Var olan bir raporu, kılavuzu ya da broşürü sayfayı elle yeniden kurmadan bir sitede yayımlamanın en hızlı yolu budur.',
    'html-to-pdf': 'Bir web sayfasını bugün göründüğü gibi arşivlemek için ya da HTML bir fatura veya rapor şablonunu basılabilir ve gönderilebilir bir şeye dönüştürmek için yapılır.',
    'rtf-to-pdf': 'RTF genellikle eski yazılımlardan ya da hukuki belge şablonlarından çıkar; PDF’e çevirmek sana her yerde aynı açılan ve yanlışlıkla değiştirilemeyen tek bir dosya verir.',
    'pdf-to-rtf': 'Bir PDF’in düzenlenebilir bir kopyasına ihtiyacın olduğu ama alıcıda Word bulunduğunu varsayamadığın durumda başvurulacak seçenek budur — şimdiye kadar yazılmış hemen her kelime işlemci RTF’i açar.',
    'odt-to-pdf': 'Tipik durum: belgeyi LibreOffice ya da OpenOffice’te yazdın, alan kişi ise Microsoft Office kullanıyor — ya da hiçbir şey kullanmıyor.',
    'pdf-to-epub': 'Telefonda PDF okumak sürekli yakınlaştırma ve yatay kaydırma demektir; bu dönüştürme her şeyden önce uzun bir belgeyi küçük ekranda ya da okuyucuda gerçekten okunabilir kılmakla ilgilidir.',
    'epub-to-pdf': 'EPUB, bir kitabı yazdırmak, sabit sayfa numaralarına göre not düşmek ya da hiç okuma uygulaması olmayan birine göndermek istendiğinde PDF’e çevrilir.',
    'document-converter': 'Bu, sana gönderenin elinde ne varsa o biçimde bir belge verildiğinde ve senin kendi yazılımının gerçekten açtığı biçimde ihtiyacın olduğunda açacağın araçtır.',
    'ebook-converter': 'E-kitap mağazaları ve okuyucular her biri kendi biçimini yeğler, bu yüzden sahip olduğun bir kitabı bir okuyucudan ya da uygulamadan diğerine taşımak için bunu kullanırsın.',
    'jpg-to-png': 'Alışılmış tetikleyici düzenlemedir: bir arka planı kesip çıkarman, bir logoyu başka bir görüntünün üzerine koyman ya da bir ekran görüntüsünün her yeniden kaydedişte daha bulanık hâle gelmesini engellemen gerekir.',
    'png-to-jpg': 'Bu, bir e-postaya eklenemeyecek ya da bir yükleme formunun boyut sınırını geçemeyecek kadar büyük bir ekran görüntüsü ya da dışa aktarım için çözümdür.',
    'webp-to-png': 'Buna genellikle bir siteden görüntü kaydettikten sonra ihtiyaç duyarsın: WebP sorunsuz iner, ama eski düzenleyiciler, ofis yazılımları ve bazı baskı hizmetleri onu açmayı hâlâ reddeder.',
    'webp-to-jpg': 'Çoğu kişi bunu bir site görüntüsünü evrensel kabul gören bir şeye taşımak için yapar — bir e-postaya, eski bir içerik yönetim sistemine, bir fotoğraf baskı hizmetine ya da bir meslektaşın tarih öncesi yazılımına.',
    'heic-to-jpg': 'Bu klasik iPhone sorunudur: fotoğraflar telefonda gayet iyi görünür ama bir Windows bilgisayarına ya da bir web formuna açılamayan .heic dosyaları olarak düşer.',
    'heic-to-png': 'Fotoğrafı yalnızca paylaşmak değil düzenlemek niyetindeysen bunu kullan — PNG, düzenleyicine yeni baştan sıkıştırılmış bir kopya yerine kayıpsız pikseller verir.',
    'svg-to-png': 'Alışılmış neden, vektörleri reddeden bir araçtır: bir sunu, bir pazar yeri ilanı, bir e-posta imzası ya da yalnızca piksel kabul eden bir uygulama simgesi üretim hattı.',
    'svg-to-jpg': 'Bu, sade fotoğraf türü bir dosya isteyen yerler içindir — bir belge, bir sosyal medya gönderisi ya da hem SVG işaretlemesini hem saydamlığı reddeden bir yükleme formu.',
    'bmp-to-png': 'BMP dosyaları eski Windows yazılımından ve tarayıcılardan akıl almaz boyutlarda çıkar; PNG tam olarak aynı pikselleri yerin küçük bir kesrinde saklar.',
    'tiff-to-jpg': 'Tarayıcılar ve profesyonel fotoğraf makineleri e-postayla gönderilemeyecek kadar büyük TIFF dosyaları üretir, bu yüzden arşiv kopyası güvenle durduğunda gönderdiğin şey JPG olur.',
    'gif-to-png': 'Bunu, 256 renk sınırı yüzünden renk bantları ya da saçaklı kenar gösteren duran bir GIF ile yaparsın — bir logo, bir simge ya da dışa aktarılmış tek bir kare.',
    'png-to-ico': 'PNG’yi ICO’ya çevirenlerin neredeyse hepsi bir site simgesi ya da bir Windows uygulama simgesi hazırlıyordur ve ikisi de sade bir görüntü dosyası yerine ICO kabını bekler.',
    'jfif-to-png': 'JFIF dosyaları tipik olarak bir fotoğraf Outlook’tan ya da bir tarayıcıdan kaydedildiğinde ortaya çıkar ve Windows sonrasında onu gerçekten kullanmak istediğin uygulamaya vermeyi reddeder.',
    'heic-to-pdf': 'iPhone’la belge, fiş ya da bir beyaz tahta fotoğrafladığında ve bunları görüntü klasörü yerine tek dosya olarak teslim etmen gerektiğinde işe yarar.',
    'image-compressor': 'Alışılmış neden bir yerdeki katı bir sınırdır — bir yükleme formu, bir e-posta eki tavanı ya da görüntüleri gerekenden çok daha büyük olduğu için fazla yavaş açılan bir web sayfası.',
    'jpeg-compressor': 'Fotoğrafçılar ve site sahipleri bunu tam çözünürlüklü JPEG’ler bir sayfayı yavaşlattığında ya da bir yükleme sınırından geçemediğinde kullanır.',
    'png-compressor': 'Ekran görüntüleri ve dışa aktarılmış arayüz grafikleri çoğu kez hiç gereği yokken birkaç megabayt tutar; bu, onlar bir belgeye, bir talebe ya da bir web sayfasına gitmeden önce küçültür.',
    'mp4-to-avi': 'Neden neredeyse her zaman eski bir aygıt ya da belirli bir programdır — bazı köhne oynatıcılar, DVD hazırlama araçları ve fotoğraf makinesi yardımcı programları AVI okur, başka bir şey okumaz.',
    'mp4-to-mov': 'Bu normalde Mac’te kurguya başlamadan önceki ilk adımdır, çünkü Final Cut Pro ve iMovie QuickTime dosyalarıyla en pürüzsüz başa çıkar.',
    'mov-to-mp4': 'iPhone ve Mac MOV’a kaydeder; geri kalan her şey MP4 bekler, bu yüzden bir klibi yüklemeden, göndermeden ya da paylaşmadan önce çalıştırılan dönüştürme budur.',
    'mkv-to-mp4': 'MKV saklamak için mükemmeldir ama telefonlar, televizyonlar, tarayıcılar ve kurgu programlarının çoğu onu oynatmaz — dosyayı gerçekten kullanılabilir kılan şey MP4’e çevirmektir.',
    'webm-to-mp4': 'Web’den kaydedilen WebM dosyaları çoğu zaman QuickTime’da, iOS’te ya da Premiere’de açılmayı reddeder; MP4, hepsinin kabul ettiği biçimdir.',
    'avi-to-mp4': 'Bu, gigabaytları yutan ve hiçbir telefonda oynamayan eski kamera görüntüleri ile arşivlenmiş klipler için standart kurtarma yoludur.',
    'flv-to-mp4': 'Flash her tarayıcıdan gitti, dolayısıyla elinde kalan her FLV fiilen oynatılamaz — MP4’e çevirmek o arşiv malzemesini izlenebilir tutar.',
    'wmv-to-mp4': 'WMV yalnızca Windows’ta yaşayan bir kalıntıdır, bu yüzden eski bir kaydı ya da ekran kaydını bir Mac’e, bir iPhone’a ya da bir web platformuna göndermeden önce bunu yaparsın.',
    'mp4-to-mp3': 'Mesele genellikle görüntü değil sestir — bir ders, bir söyleşi, bir podcast ya da videoyu yanında taşımadan telefonunda istediğin bir müzik klibi.',
    'video-to-mp3': 'Saklamaya değer kısım ses olduğunda buna başvurulur: kaydedilmiş bir konuşma, bir söyleşi, bir prova ya da bir müzik parçası.',
    'mp4-converter': 'Bu, bir klip oynamadığında ya da yüklenemediğinde kullanılacak araçtır, çünkü MP4 telefonların, tarayıcıların, televizyonların ve sosyal platformların hepsinin kabul ettiği tek video biçimidir.',
    'video-converter': 'Bir klibin dünya değiştirmesi gerektiğinde kullan — bir kurgu programından çıkması, bir telefona geçmesi, bir tarayıcıya girmesi ya da yalnızca belirli bir kabı alan bir platforma ulaşması gerektiğinde.',
    'mp3-to-wav': 'Alışılmış neden kurgudur: dijital ses istasyonları, mastering zincirleri ve yayıncılık ya da oyun için pek çok ses iş akışı sıkıştırılmamış WAV ister, böylece her tek işlemde sıkıştırılmış bir dosyayı çözmek zorunda kalmazlar.',
    'wav-to-mp3': 'Kayıtlar bir saha kaydedicisinden ya da bir ses istasyonundan devasa WAV dosyaları olarak çıkar; MP3 onları gönderilebilecek, yüklenebilecek ya da telefona sığacak kadar küçültür.',
    'flac-to-mp3': 'Bir FLAC kitaplığı evde harika duyulur, ama araç ses sistemleri, eski telefonlar ve ucuz oynatıcılar onu çoğu zaman reddeder — MP3, yanında götürdüğün uyumluluk kopyasıdır.',
    'aac-to-mp3': 'Burada mesele çoğunlukla uyumluluktur: AAC Apple ve akış dünyasından gelir, eski oynatıcılar, araç radyoları ve DJ yazılımları ise MP3 bekler.',
    'ogg-to-mp3': 'OGG oyunlarda, Vikipedi’de ve açık kaynak yazılımlarda karşımıza çıkar ve bir telefondaki ya da arabadaki yaygın oynatıcıların neredeyse hiçbiri onu açmaz.',
    'wma-to-mp3': 'WMA, Windows Media Player döneminin kalıntısıdır; eski bir müzik derlemesini telefona ya da bir akış kitaplığına böyle kurtarırsın.',
    'm4a-to-mp3': 'Bu, müzikleri ya da iPhone ses notlarını Apple aygıtlarından yalnızca MP3 anlayan programlara, arabalara ya da oynatıcılara taşırken atılan alışılmış adımdır.',
    'mp3-to-aac': 'Bazı aygıtlar ve uygulamalar — özellikle Apple ve akış platformları çevresinde — AAC’yi yeğler, dolayısıyla bu bir kalite yükseltmesi değil, uyumluluk dönüştürmesidir.',
    'mp3-to-ogg': 'OGG’ye, patentsiz bir kodeğin şart koşulduğu oyun motorları, açık kaynak projeler ve platformlar için çevrilir.',
    'audio-converter': 'Bu, bir dosyanın oynamadığı an için araçtır: sesi, aygıtının, düzenleyicinin ya da yükleme formunun ısrar ettiği yaygın biçimlerden tam olarak hangisiyse ona taşıyacağın tek yer.',
    'rar-to-zip': 'RAR açmak için ek yazılım ister, bu yüzden bir arşivi WinRAR kurmayacak birine göndermeden önce bunu yaparsın.',
    '7z-to-zip': '7Z daha iyi sıkıştırır ama kurulu 7-Zip gerektirir; ZIP olarak alıcı dosyaya sadece çift tıklayabilir.',
    'tar-to-zip': 'TAR, Linux ile macOS komut satırından gelir; ZIP ise Windows’taki bir meslektaşın hiçbir şey kurmadan açabildiği biçimdir.',
    'gz-to-zip': 'GZ dosyaları genellikle bir sunucudan ya da bir Linux aracından gelir ve ZIP’in çift tıklamayla açıldığı Windows’ta zahmetlidir.',
    'zip-to-7z': 'Burada mesele boyuttur: 7Z’nin sıkıştırması gözle görülür ölçüde güçlüdür; büyük bir klasörü arşivlerken ya da bulut depolamayı gigabayt başına öderken bunun önemi vardır.',
    'video-to-gif': 'Tipik kullanım bir sohbet iletisi, bir README, bir hata bildirimi ya da bir gönderi için kısa bir döngüdür — GIF’in gömülü olarak kendiliğinden oynadığı, bir video dosyasının ise oynamadığı yerler.',
    'mp4-to-gif': 'Tipik kullanım bir sohbet, bir README, bir hata bildirimi ya da bir gönderi için kısa bir döngüdür; orada GIF gömülü olarak kendiliğinden oynar, bir video ise yalnızca ek olarak öylece durur.',
    'webm-to-gif': 'Web’den kaydedilen WebM klipleri çoğu zaman istediğin yere gömülemez, oysa GIF sohbet uygulamalarında, talep sistemlerinde ve forumlarda gömülü olarak oynar.',
    'mov-to-gif': 'Bunu, bir pull request’te, bir destek talebinde ya da bir gönderide gömülü görünmesi gereken bir QuickTime ekran kaydıyla yaparsın.',
    'avi-to-gif': 'Eski bir AVI klibinin birkaç saniyesini GIF’e çevirmek, onları bir belgeye, bir sohbet başlığına ya da bir web sayfasına sokmanın en basit yoludur.',
    'gif-to-mp4': 'Uzun GIF’ler devasadır ve takılarak oynar; MP4 aynı canlandırmayı boyutun küçük bir kesrinde gösterir, sosyal platformların onları perde arkasında dönüştürmesinin nedeni de tam olarak budur.',
    'image-to-gif': 'Bir platform ya da eski bir sistem açıkça GIF beklediğinde, ya da var olan bir canlandırma dizisiyle aynı biçimde duran bir kareye ihtiyacın olduğunda işe yarar.',
    'gif-compressor': 'Hareketli GIF’ler hızla şişer ve biri bir e-posta, bir sohbet yükleme sınırı ya da hızlı açılması gereken bir sayfa için fazla ağır olduğunda çözüm budur.',
    'merge-pdf': 'Klasik durum bir başvuru ya da bir hasar bildirimidir: bir form, bir tarama ve bir fişin hepsinin tek belge olarak ulaşması gerekir.',
    'split-pdf': 'Genellikle çok daha uzun bir dosyadan tam olarak tek bir şeye ihtiyacın olur — bir bölüm, bir fatura, elli sayfalık bir taramadan imzalı tek bir sayfa.',
    'compress-pdf': 'Neredeyse her zaman bir boyut sınırı: bir e-posta eki tavanı, bir resmî form ya da birkaç megabaytı aşan her şeyi reddeden bir portal.',
    'rotate-pdf': 'Bu, gündelik tarayıcı derdini çözer — kâğıtların besleniş biçimi yüzünden yan ya da ters çıkan sayfaları.',
    'protect-pdf': 'PDF’ler maaş bordroları, sözleşmeler ya da sağlık raporları gönderilmeden önce parolayla korunur; böylece iletinin ardından yönlendirileceği kişi içeriği okuyamaz.',
    'unlock-pdf': 'Parola biliniyor ama kısıtlama yolunu tıkıyorsa, sana ait belgelerde kullan — örneğin yazdıramadığın bir banka ekstresinde.',
    'view-metadata': 'Bir dosyanın sana doğrudan söylemediği soruları yanıtlar: bu fotoğrafı hangi makine çekti, bu kayıt gerçekte ne kadar sürüyor, bu videonun içinde hangi kodek var, bu PDF kaç sayfa.',
    'ocr': 'Durum her zaman aynıdır: elinde görüntü hâlinde bir belge vardır ve içindeki sözcüklere ihtiyacın vardır — aramak, alıntılamak, düzenlemek ya da düzgün arşivlemek için.',
    'pdf-compress-ai': 'Sıradan sıkıştırma zaten denendiğinde ve dosya hâlâ boğuştuğun yükleme sınırı için fazla büyük olduğunda buna başvur.',
    'text-to-speech': 'Bir şeyi okumak yerine dinlemek için kullanılır — işe giderken bir makale, tuhaf kaçan cümleleri yakalamak için sesli okunan bir senaryo ya da bir videoya dış ses.',
    'speech-to-text': 'Alışılmış durum, yazılı olarak ihtiyaç duyduğun bir kayıttır: not, tutanak ya da alıntılanabilir bir döküm olması gereken bir toplantı, söyleşi, ders ya da ses notu.',
    'auto-subtitle': 'Altyazılar bir videoyu sessizken izlenebilir ve arama motorlarınca bulunabilir kılan şeydir; elle yazmak ise kısa bir klipte bile insanların sandığından çok daha uzun sürer.',
    'document-translation': 'Amaç, bir belgeyi okunur kılan yerleşimi yitirmeden başka bir dilde okumak ya da göndermektir.',
    "jpeg-to-jpg": "Genellikle tetikleyici, .jpg uzantısında ısrar eden ve .jpeg olarak kaydedilmiş aynı resmi reddeden bir form, bir site oluşturucu ya da eski bir programdır.",
    "jpg-to-jpeg": "Bazı yükleme formları, fotoğraf laboratuvarları ve eski sistemler kabul edilen tek uzantı olarak .jpeg’i listeler ve içerik aynı olsa da .jpg dosyasını reddeder.",
    "jpg-to-webp": "Çoğu kişi bunu bir web sitesini hızlandırmak için ister: WebP fotoğraflar benzer görsel kalitede aynı JPG’den genellikle dörtte bir ile üçte bir oranında daha küçüktür; bu da daha hızlı sayfalar ve daha iyi sayfa hızı puanları demektir.",
    "png-to-webp": "Yaygın durum, yavaş yüklenen PNG ekran görüntüleri, logolar ve grafiklerle dolu bir web sitesidir — WebP saydamlığı korur ama dosya boyutunu genellikle epey azaltır.",
    "avif-to-jpg": "Modern sitelerden veya yeni telefonlardan kaydedilen AVIF görselleri eski fotoğraf düzenleyicilerinde, ofis yazılımlarında ya da yükleme formlarında çoğu zaman açılmaz; JPG ise kesinlikle her yerde çalışır.",
    "avif-to-png": "Buna genellikle bir AVIF grafiğini henüz AVIF okuyamayan bir programda düzenlemen, katmanlara ayırman ya da başka bir arka plana yerleştirmen gerektiğinde ihtiyaç duyarsın.",
    "bmp-to-jpg": "Eski tarayıcılardan, Windows Paint’ten ya da endüstriyel yazılımlardan gelen BMP dosyaları sıkıştırılmamış oldukları için devasadır; JPG’ye çevirmek onları e-postayla gönderecek ya da yükleyecek kadar küçültür.",
    "tiff-to-png": "Taramalar ve baskıya hazır TIFF’ler web için fazla ağır ve fazla zayıf desteklenir; PNG her pikseli net tutar ve her tarayıcıda açılır.",
    "ico-to-png": "Tipik neden, bir favicon’un ya da Windows simgesinin içindeki çizime ulaşıp onu bir tasarımda, belgede veya sunumda yeniden kullanmaktır.",
    "gif-to-jpg": "Genellikle bir GIF’ten yalnızca tek bir durağan kareye ihtiyacın olur — bir küçük resim, bir belge ya da hareketli görselleri kabul etmeyen bir site için.",
    "jpg-to-pdf": "Klasik durum, elinde yalnızca bir fişin, kimlik kartının ya da imzalı bir sayfanın telefonla çekilmiş fotoğrafı varken PDF isteyen bir başvuru ya da taleptir.",
    "png-to-pdf": "Ekran görüntülerini, diyagramları veya taranmış sayfaları düzgün bir belge olarak teslim etmek için kullanılır — pek çok portal ve e-posta alıcısı görsel değil PDF bekler.",
    "txt-to-pdf": "Düz metin her düzenleyicide farklı görünür; notları, günlükleri ya da bir taslağı PDF’ye çevirmek yazı tipini ve düzeni sabitler, böylece herkes için aynı okunur ve aynı yazdırılır.",
    "markdown-to-pdf": "Yazarlar ve geliştiriciler taslaklarını Markdown’da yazar, ama iş arkadaşları ve müşteriler bitmiş bir belge bekler — hiçbir araç gerektirmeden açabilecekleri bir README, rapor ya da not derlemesi.",
    "csv-to-excel": "Bankalardan, mağazalardan ve veritabanlarından alınan CSV dışa aktarımları çoğu zaman bozuk sütunlar, kaybolan baştaki sıfırlar ya da karışmış tarihlerle açılır; bir Excel çalışma kitabı verileri toplamlara ve grafiklere hazır, düzgün hücrelerde tutar.",
    "excel-to-csv": "Çoğu içe aktarma aracı — CRM’ler, bülten hizmetleri, online mağazalar ve veritabanları — yalnızca CSV kabul eder; bu yüzden bir tablo, yüklenebilmesi için önce düzleştirilmelidir.",
    "word-to-txt": "Olağan neden, metni Word dosyalarını anlamayan bir yerde yeniden kullanmaktır: bir kod düzenleyici, bir site CMS’i, bir altyazı aracı ya da bir yapay zekâ istemi.",
    "mp4-to-webm": "Web geliştiricileri, tarayıcılarda doğrudan oynayan ve benzer kalitede çoğu zaman MP4’ten daha küçük olan açık, telifsiz video için WebM’e dönüştürür.",
    "mp4-to-mkv": "MKV, arşivlerin ve Plex ya da Jellyfin gibi medya sunucularının tercih ettiği kapsayıcıdır; çünkü tek bir dosya birden çok ses parçası, altyazı ve bölüm barındırabilir.",
    "m4v-to-mp4": "iTunes’tan ya da Apple cihazlarından gelen M4V dosyaları Android’de, Windows’ta veya video düzenleyicilerde çoğu zaman açılmaz; MP4 ise her yerde oynar.",
    "3gp-to-mp4": "Eski telefon videoları çoğunlukla 3GP olarak saklanır; modern bilgisayarlar, telefonlar ve sosyal platformlar bu biçimi sık sık oynatamaz ya da yükleyemez.",
    "mpeg-to-mp4": "DVD kopyalarından, eski kameralardan ve TV kayıtlarından gelen MPEG dosyaları büyüktür ve telefonlarda zayıf desteklenir; MP4 onları küçültür ve her yerde oynar.",
    "m4a-to-wav": "Ses düzenleyicileri, sampler’lar ve bazı yayın araçları sıkıştırılmamış WAV ister; oysa iPhone sesli notları ve iTunes indirmeleri M4A olarak gelir.",
    "flac-to-wav": "Ses iş istasyonları, CD yazma yazılımları ve bazı donanım oynatıcılar WAV’ı işler ama FLAC’ı işlemez; ikisi de kayıpsız olduğundan yolda hiçbir şey kaybolmaz.",
    "wav-to-flac": "Müzisyenler ve arşivciler büyük WAV kayıtlarını her örneği bit bit aynı tutarak kabaca yarıya küçültmek için kullanır.",
    "aiff-to-mp3": "Logic, GarageBand ya da Mac örnek kütüphanelerinden gelen AIFF kayıtları büyüktür; MP3 onları paylaşacak, yayınlayacak ya da her cihazda çalacak kadar küçültür.",
    "opus-to-mp3": "WhatsApp ve Telegram sesli mesajları ile pek çok web kaydı OPUS olarak saklanır; araç ses sistemleri, eski oynatıcılar ve düzenleyiciler bunları çoğu zaman çalmaz.",
    "mp3-to-m4a": "Genellikle Apple cihazları için istenir — M4A, Apple Music’te ve iTunes’ta sorunsuz çalışır ve bir iPhone zil sesinin başlangıç noktasıdır.",
    "zip-to-tar": "Geliştiriciler ve sunucu yöneticileri Linux sistemlerine dağıtım yaparken, kapsayıcı imajları oluştururken ya da ZIP yerine tarball bekleyen araçları kullanırken TAR’a ihtiyaç duyar.",
    "rar-to-7z": "RAR arşivleri, 7-Zip’in doğrudan oluşturup açtığı ücretsiz ve açık bir biçimi kullanmak için 7Z olarak yeniden paketlenir; sıkıştırma da çoğu zaman daha iyidir.",
    "pdf-to-images": "Sosyal medya için yapılmıştır: Instagram kaydırmalı gönderileri, LinkedIn paylaşımları ve hikâyeler PDF değil görsel ister; bu yüzden bir sunum, menü ya da el ilanı sayfa başına bir görsele dönüşmelidir.",
    "photo-collage": "Olağan neden birkaç fotoğrafı tek bir görsel olarak paylaşmaktır — tek tek kaydırılmak yerine bir bakışta görülmesi gereken bir önce-sonra karşılaştırması, bir tatil özeti ya da bir ürün yelpazesi.",
    "resize-for-social-media": "Her platform kendi biçimine göre kırpar: Story olarak paylaşılan yatay bir fotoğraf siyah şeritler alır ya da kenarlarını kaybeder, uzun bir telefon çekimi ise akışta kesilir — fotoğrafı kendin yeniden çerçevelersen resimde neyin kalacağına sen karar verirsin.",
    "profile-picture-maker": "Profil fotoğrafları çok küçük gösterilir ve genellikle daire biçiminde kesilir; bu yüzden gelişigüzel çekilmiş bir fotoğrafta yüz çoğu zaman ortalanmamış ya da kesilmiş olur. Doğru çerçevelenmiş kare bir görsel bunu yüklemeden önce düzeltir.",
    "social-media-image-compressor": "Telefon fotoğrafları çoğu zaman 4000 piksel genişliğinde ve birkaç megabayt boyutundadır; bir platform onları gösterim boyutuna kendisi küçülttüğünde aynı zamanda sert biçimde sıkıştırır ve bulanıklık ile kare kare gökyüzü buradan gelir.",
  },
  t: {
    'list.and': 've',
    'family.document': 'belge',
    'family.image': 'görüntü',
    'family.video': 'video',
    'family.audio': 'ses',
    'family.ebook': 'e-kitap',
    'family.archive': 'arşiv',
    'family.subtitle': 'altyazı',
    'family.none': 'dosya',
    'unit.sample': 'her örnek',
    'unit.pixel': 'her piksel',

    'intro.convert': '{{fromAbout}} {{toAbout}} {{reason}} {{toNote}}',
    'intro.convert.noSource': '{{fn}}, bu dönüştürmenin kaynak biçimidir.',
    'intro.lead': '{{lead}} {{reason}}',
    'intro.hub': 'Bu, genel amaçlı {{category}} dönüştürücüsüdür: şunları kabul eder — {{inputs}} — ve şunları yazar: {{outputs}}. Böylece tam senin biçim çiftine uyan o tek aracı aramak zorunda kalmazsın. {{reason}} Çıkış biçimini yukarıdan seç — dönüştürme sunucuda yapılır, kuracak bir şey yok.',
    'intro.hubExtract': 'Bu araç, bir video dosyasından ses izini çekip ayrı kaydeder; böylece videodan her yerde oynayan sade bir ses dosyası olur. Şunları kabul eder — {{inputs}} — ve şunları yazar: {{outputs}}. Görüntü izi basitçe atılır, sonucun özgün boyutun küçük bir kesri olmasının nedeni de budur. {{reason}}',
    'intro.hubGif': 'Bu araç {{inputs}} dosyalarını hareketli GIF’lere çevirir. {{gifAbout}} {{reason}}',
    'intro.hubGif.gifAbout': 'GIF kare başına 256 renkle sınırlıdır, fotoğrafların içinde bantlı görünmesinin nedeni budur; buna karşılık canlanır ve internette hemen her yerde gömülü olarak kendiliğinden oynar.',
    'intro.compress': '{{about}} Bu araç {{fn}} dosyanı biçim değiştirmeden daha küçük boyutta yeniden kodlar; yani indirdiğin şey hâlâ sıradan bir {{fn}} dosyasıdır ve özgün dosyanın açıldığı her yerde açılır. {{reason}}{{extra}}',
    'intro.compress.lossless': ' {{fn}} kayıpsız olduğu için kazancın büyük kısmı ayrıntı atmaktan değil, daha akıllı kodlamadan ve daraltılmış renk paletinden gelir.',
    'intro.soon': '{{reason}} Bu araç henüz yayında değil — şu anda geliştiriliyor ve hazır olur olmaz burada görünecek.',
    'intro.lead.pdf-merge': 'Birleştirme, birden çok PDF’i seçtiğin sırayla tek dosyada toplar ve sayfaları yeniden çizmez — metin seçilebilir kalır, görüntüler özgün kalitesini korur. PDF sabit yerleşimli bir biçimdir: her karakterin, her çizginin ve her görüntünün tam konumunu saklar, bu yüzden her yerde aynı görünür ama düzenlemesi zahmetlidir.',
    'intro.lead.pdf-split': 'Bölme, bir PDF’ten belirttiğin sayfaları çıkarır ve yeni bir belge olarak kaydeder; özgün dosyaya dokunmaz. PDF sabit yerleşimli bir biçimdir: her karakterin, her çizginin ve her görüntünün tam konumunu saklar, bu yüzden her yerde aynı görünür ama düzenlemesi zahmetlidir.',
    'intro.lead.pdf-compress': 'Bir PDF’i sıkıştırmak, içindeki görüntüleri yeniden kodlar ve gereksiz gömülü verileri temizler; büyük bir PDF’in boyutunun neredeyse tamamı da orada durur. Metin ve vektör grafikleri keskin kalır.',
    'intro.lead.pdf-compress-ai': 'Bu araç sıkıştırmadan önce PDF’in içinde ne olduğunu çözümler; böylece fotoğrafik görüntüler, düz grafikler ve yalnızca metin içeren sayfaların her biri, gözle görülür bozulma olmadan en çok yer kazandıran biçimde ele alınır.',
    'intro.lead.pdf-rotate': 'Döndürme, bir PDF’in yön işaretini ve sayfa geometrisini değiştirir; böylece sayfalar doğru yönde görünür ve yazdırılır. Hiçbir şey yeniden çizilmez, dolayısıyla kalite yitmez.',
    'intro.lead.pdf-protect': 'Bir PDF’i korumak, içeriğini şifreler; böylece belirlediğin parola olmadan açılamaz. Şifreleme, çevresindeki bir kılıfa değil dosyanın kendisine uygulanır.',
    'intro.lead.pdf-unlock': 'Kilit açma, parolasını zaten bildiğin bir PDF’ten parolayı ve kullanım kısıtlarını kaldırır; böylece yeniden normal biçimde açılabilir, yazdırılabilir ve içinden kopyalanabilir.',
    'intro.lead.metadata': 'Her dosya kendisi hakkında, açtığında görünmeyen bilgiler taşır: görüntü ölçüleri ve makine ayarları, ses süresi ve bit hızı, video kodeği ve kare hızı, belge yazarı ve sayfa sayısı. Bu araç o üstverileri okur ve sana gösterir.',
    'intro.lead.ocr': 'Optik karakter tanıma, metnin bir görüntüsüne bakar — bir tarama, bir fotoğraf, metin katmanı olmayan bir PDF sayfası — ve karakterlerin ne olduğunu çıkarır; böylece sözcüklerin resmi, bilgisayarın arayabileceği, kopyalayabileceği ve düzenleyebileceği sözcüklere dönüşür.',
    'intro.lead.tts': 'Metin okuma, yazılı metinden sinirsel seslerle konuşma üretir; böylece eski sistemlerin düz, robotik çıktısı yerine doğal tınlayan bir kayıt elde edersin.',
    'intro.lead.stt': 'Konuşma yazıya çevirme, konuşulan sesi yazılı sözcüklere döker. Doğal konuşmayla, aksanlarla ve arka plan gürültüsüyle eski dikte yazılımlarından çok daha iyi başa çıkar ve düzenleyebileceğin bir döküm verir.',
    'intro.lead.subtitle': 'Altyazı üreteci, bir videodaki konuşmayı döker ve zaman koduyla birlikte yazar; böylece salt bir döküm değil, standart bir altyazı dosyası ortaya çıkar.',

    'steps.convert.1.batch': '{{fn}} dosyanı bu sayfanın üstündeki yükleme alanına sürükle ya da aygıtında gezinmek için üzerine tıkla. Birden çok dosya — hatta bütün bir klasör — ekleyip hepsini bir kerede dönüştürebilirsin.',
    'steps.convert.1.single': '{{fn}} dosyanı bu sayfanın üstündeki yükleme alanına sürükle ya da aygıtında gezinmek için üzerine tıkla.',
    'steps.convert.2.direct': 'Çıkış biçimi olarak {{tn}} seç ve Dönüştür’e tıkla.',
    'steps.convert.2.dropdown': 'Açılır listeden çıkış biçimi olarak {{tn}} seç ve Dönüştür’e tıkla.',
    'steps.convert.2.directMedia': 'Çıkış biçimi olarak {{tn}} seç, gerekirse gelişmiş ayarlardan kaliteyi ya da boyutu ayarla ve Dönüştür’e tıkla.',
    'steps.convert.2.dropdownMedia': 'Açılır listeden çıkış biçimi olarak {{tn}} seç, gerekirse gelişmiş ayarlardan kaliteyi ya da boyutu ayarla ve Dönüştür’e tıkla.',
    'steps.convert.3': 'Tamamlanan {{tn}} dosyanı indir. İndirme bağlantısı 24 saat açık kalır, ardından iki dosya da kendiliğinden silinir.',
    'steps.hub.1.batch': 'Dosyanı bu sayfanın üstündeki yükleme alanına sürükle ya da aygıtında gezinmek için üzerine tıkla — {{category}} dönüştürücüsü şunları kabul eder: {{inputs}}. Birden çok dosya — hatta bütün bir klasör — ekleyip hepsini bir kerede dönüştürebilirsin.',
    'steps.hub.1.single': 'Dosyanı bu sayfanın üstündeki yükleme alanına sürükle ya da aygıtında gezinmek için üzerine tıkla — {{category}} dönüştürücüsü şunları kabul eder: {{inputs}}.',
    'steps.hub.2.direct': 'İhtiyacın olan çıkış biçimini seç ve Dönüştür’e tıkla.',
    'steps.hub.2.dropdown': 'Açılır listeden ihtiyacın olan çıkış biçimini seç ve Dönüştür’e tıkla.',
    'steps.hub.2.directMedia': 'İhtiyacın olan çıkış biçimini seç, gerekirse gelişmiş ayarlardan kaliteyi ya da boyutu ayarla ve Dönüştür’e tıkla.',
    'steps.hub.2.dropdownMedia': 'Açılır listeden ihtiyacın olan çıkış biçimini seç, gerekirse gelişmiş ayarlardan kaliteyi ya da boyutu ayarla ve Dönüştür’e tıkla.',
    'steps.hub.3': 'Tamamlanan dosyanı indir. İndirme bağlantısı 24 saat açık kalır, ardından iki dosya da kendiliğinden silinir.',
    'steps.pdf-merge.1': 'Birleştirmek istediğin her PDF’i ekle — hepsini birden yükleme alanına sürükle ya da tıklayıp tek tek seç.',
    'steps.pdf-merge.2': 'Dosyaları, tamamlanan belgede görünmelerini istediğin sıraya sürükle.',
    'steps.pdf-merge.3': 'Birleştir’e tıkla ve tek parça hâlindeki birleşik PDF’i indir.',
    'steps.pdf-split.1': 'Sayfa çıkarmak istediğin PDF’i yükle.',
    'steps.pdf-split.2': 'İhtiyacın olan sayfaları ya da aralıkları sayfa aralığı kutusuna yaz — örneğin 1-3, 5, 7-10.',
    'steps.pdf-split.3': 'Dönüştür’e tıkla ve çıkarılan sayfaları indir.',
    'steps.pdf-compress.1': 'PDF’ini yükleme alanına sürükle ya da bulmak için tıkla.',
    'steps.pdf-compress.2': 'Dönüştür’e tıkla — dosya çözümlenir, görüntüleri ve gömülü verileri daha küçük boyutta yeniden kodlanır.',
    'steps.pdf-compress.3': 'Sıkıştırılmış PDF’i indir ve yanında gösterilen boyut kazancını gör.',
    'steps.pdf-rotate.1': 'Sayfaları ters duran PDF’i yükle.',
    'steps.pdf-rotate.2': 'Ne kadar döndürüleceğini seç — 90°, 180° ya da 270°.',
    'steps.pdf-rotate.3': 'Dönüştür’e tıkla ve düzeltilmiş PDF’i indir.',
    'steps.pdf-protect.1': 'Güvence altına almak istediğin PDF’i yükle.',
    'steps.pdf-protect.2': 'Açmak için gerekecek parolayı gir ve bir kopyasını güvenli bir yerde sakla.',
    'steps.pdf-protect.3': 'Dönüştür’e tıkla ve şifrelenmiş PDF’i indir.',
    'steps.pdf-unlock.1': 'Parolayla korunan PDF’i yükle.',
    'steps.pdf-unlock.2': 'Dosyanın çözülebilmesi için geçerli parolasını gir.',
    'steps.pdf-unlock.3': 'Dönüştür’e tıkla ve kilidi açılmış PDF’i indir.',
    'steps.metadata.1': 'Herhangi bir dosyayı yükleme alanına sürükle — bir görüntü, bir video, bir ses dosyası ya da bir belge.',
    'steps.metadata.2': 'Dosya dönüştürülmez, incelenir; dolayısıyla üzerinde hiçbir şey değişmez.',
    'steps.metadata.3': 'Üstverileri doğrudan sayfada oku: ölçüler, süre, kodek, makine ayrıntıları, sayfa sayısı ve dahası.',
    'steps.ocr.1': 'Taranmış PDF’i ya da metnin fotoğrafını yükle.',
    'steps.ocr.2': 'Belgenin dilini ve aranabilir PDF mi yoksa düz metin mi istediğini seç.',
    'steps.ocr.3': 'Dönüştür’e tıkla ve sonucu indir; tanınan metin artık seçilebilir ve aranabilir olur.',
    'steps.tts.1': 'Metnini kutuya yaz ya da yapıştır — dönüştürme başına en çok 4096 karakter.',
    'steps.tts.2': 'Bir ses, bir konuşma hızı ve bir çıkış biçimi seç.',
    'steps.tts.3': 'Dönüştür’e tıkla ve tamamlanan ses dosyasını indir.',
    'steps.stt.1': 'Kaydını yükle ya da sayfadaki düğmeyle doğrudan mikrofonundan kayıt yap.',
    'steps.stt.2': 'İstersen doğruluğu artırmak için konuşulan dili belirle ve TXT ya da DOCX çıkışı seç.',
    'steps.stt.3': 'Dönüştür’e tıkla, dökümü sayfada oku, sonra indir.',
    'steps.subtitle.1': 'Altyazı istediğin videoyu yükle.',
    'steps.subtitle.2': 'SRT ya da VTT seç ve biliyorsan konuşulan dili belirt.',
    'steps.subtitle.3': 'Dönüştür’e tıkla ve zaman kodlu altyazı dosyasını indir; oynatıcına ya da kurgu programına koymaya hazırdır.',
    'steps.compress.1': '{{fn}} görüntülerini yükleme alanına sürükle ya da gezinmek için tıkla. Bir kerede bütün bir klasör ekleyebilirsin.',
    'steps.compress.1.gif': '{{fn}} canlandırmanı yükleme alanına sürükle ya da gezinmek için tıkla. Bir kerede bütün bir klasör ekleyebilirsin.',
    'steps.compress.2': 'Dönüştür’e tıkla — dosya aynı biçimde kalarak daha küçük boyutta yeniden kodlanır.',
    'steps.compress.3': 'Sonucu indir ve sayfada gösterilen özgün boyutla karşılaştır.',
    'steps.soon.1': 'İhtiyacın olan aracı Araçlar sayfasından seç — bu araç dışında her şey bugün zaten çalışıyor.',
    'steps.soon.2': 'Dosyanı yükle ve bir çıkış biçimi seç.',
    'steps.soon.3': 'Sonucu indir ya da belge çevirisi devreye girdiğinde buraya yeniden uğra.',

    'faq.cost.q.pair': '{{from}} biçimini {{to}} biçimine dönüştürmek ücretsiz mi?',
    'faq.cost.q.tool': '{{label}} ücretsiz mi?',
    'faq.cost.a.pair': "Her {{from}} – {{to}} dönüştürmesi, küçük bir ön ödemeli paketten bir kredi harcar — abonelik yok, krediler asla sona ermez ve başarısız bir dönüştürme için ücret alınmaz.",
    'faq.cost.a.tool': "Her dönüştürme, küçük bir ön ödemeli paketten bir kredi harcar — abonelik yok, krediler asla sona ermez ve başarısız bir dönüştürme için ücret alınmaz.",
    'faq.cost.a.smartTts': "Akıllı işlevler dosya başına değil kullanıma göre ücretlendirilir — her 1000 metin karakteri için 1 kredi, yukarı yuvarlanarak. Abonelik yok: krediler küçük ön ödemeli paketlerle alınır, asla sona ermez ve başarısız bir dönüştürme hiçbir zaman hiçbir şeye mal olmaz.",
    'faq.cost.a.smartAv': "Akıllı işlevler dosya başına değil kullanıma göre ücretlendirilir — her 5 dakikalık ses ya da video için 1 kredi, yukarı yuvarlanarak. Abonelik yok: krediler küçük ön ödemeli paketlerle alınır, asla sona ermez ve başarısız bir dönüştürme hiçbir zaman hiçbir şeye mal olmaz.",
    'faq.cost.q.metadata': 'Dosya Bilgisi aracı ücretsiz mi?',
    'faq.cost.a.metadata': 'Evet. Bir dosyanın üstverisini okumak dönüştürme değildir, dolayısıyla kredi harcamaz — istediğin kadar dosyayı inceleyebilirsin. Krediler yalnızca bir araç senin için gerçekten yeni bir dosya ürettiğinde harcanır.',
    'faq.cost.q.soon': '{{label}} şimdiden kullanılabiliyor mu?',
    'faq.cost.a.soon': 'Henüz değil — bu sayfa, araç yapılırken yer tutuyor; dolayısıyla bugün burada yüklenecek bir şey yok. Fiyatlandırma, sitenin geri kalanıyla aynı ön ödemeli kredi düzenini izleyecek: abonelik yok, krediler asla sona ermiyor ve başarısız bir dönüştürme için ücret alınmıyor.',

    'faq.time.q.pair': '{{from}} – {{to}} dönüştürmesi ne kadar sürer?',
    'faq.time.q.tool': '{{label}} ne kadar sürer?',
    'faq.time.a': '{{speed}} Sınırlayıcı etken genellikle yükleme hızıdır, dolayısıyla yavaş bir bağlantıdaki büyük bir dosya, dönüştürmenin kendisinden daha uzun sürer.{{suffix}}',
    'faq.time.speed.image': 'Görüntüler en hızlı dönüştürdüğümüz şeydir — tek bir fotoğraf normalde beş saniyenin altında biter, bütün bir klasör ise aşağı yukarı yüklemenin kendisi kadar sürer.',
    'faq.time.speed.document': 'Belgelerin çoğu birkaç saniyede biter. Çok uzun dosyalar — birkaç yüz sayfa ya da görüntü dolu bir tarama — bir dakikayı bulabilir.',
    'faq.time.speed.audio': 'Sıradan bir parça birkaç saniyede dönüşür. Bir ders ya da bir podcast bölümü gibi tam uzunlukta bir kayıt genellikle bir dakikanın hayli altında sürer ve bunun büyük kısmı yüklemedir.',
    'faq.time.speed.video': 'Video en yavaş kategoridir, çünkü her karenin yeniden kodlanması gerekir. Kısa bir klip saniyeler alır, uzun ve yüksek çözünürlüklü bir dosya ise birkaç dakika sürebilir.',
    'faq.time.speed.archive': 'Arşivler saniyeler içinde dönüşür, gerçi büyük olan daha uzun sürer, çünkü içindeki her dosyanın açılıp yeniden paketlenmesi gerekir.',
    'faq.time.speed.ebook': 'E-kitaplar hızlı gider — bütün bir roman normalde birkaç saniyede dönüşür.',
    'faq.time.speed.subtitle': 'Döküm, dakikada birkaç saniyelik bir hızla ilerler; dolayısıyla on dakikalık bir video genellikle bir dakikanın hayli altında altyazılanır.',
    'faq.time.suffix.standard': ' 200 MB’a kadar dosyalar kabul edilir.',
    'faq.time.suffix.smart': ' Akıllı işlevler 25 MB’a kadar dosya kabul eder; sıradan dönüştürmeler 200 MB’a kadar.',
    'faq.time.q.metadata': 'Bir dosyanın üstverisini okumak ne kadar sürer?',
    'faq.time.a.metadata': 'Dosya yüklendikten sonra bir ya da iki saniye. Hiçbir şey dönüştürülmez ya da yeniden kodlanmaz — başlıklar ayrıştırılır ve sonuç doğrudan sayfaya yazılır — dolayısıyla bekleme aslında yüklemenin kendisidir.',
    'faq.time.q.soon': 'Ek ücrete mi mal olacak?',
    'faq.time.a.soon': 'Sitedeki her şeyle aynı kredileri kullanacak. Ayrıca kaydolunacak ayrı bir paket ya da abonelik yok ve hesabında hâlihazırda bulunan krediler, devreye girdiği andan itibaren onunla çalışacak.',

    'faq.safety.q.pair': '{{from}} dosyamı yüklemek güvenli mi?',
    'faq.safety.q.tool': 'Dosyam güvende mi?',
    'faq.safety.a.pair': 'Dosyalar şifreli bir TLS bağlantısı üzerinden gider ve istediğin dönüştürme dışında hiçbir şey için kullanılmaz. Hem özgün {{from}} dosyan hem de geri verdiğimiz {{to}} dosyası 24 saat içinde kendiliğinden silinir — kalıcı olarak, hiçbir yedek tutulmadan — ve içerik asla okunmaz, çözümlenmez ya da paylaşılmaz. Hizmet, GDPR kapsamında Almanya’dan işletilmektedir.',
    'faq.safety.a.tool': 'Dosyalar şifreli bir TLS bağlantısı üzerinden gider ve istediğin dönüştürme dışında hiçbir şey için kullanılmaz. Hem özgün dosyan hem de geri verdiğimiz sonuç 24 saat içinde kendiliğinden silinir — kalıcı olarak, hiçbir yedek tutulmadan — ve içerik asla okunmaz, çözümlenmez ya da paylaşılmaz. Hizmet, GDPR kapsamında Almanya’dan işletilmektedir.',

    'quality.vectorRaster.q': '{{fn}} dosyam {{tn}} olarak keskin kalır mı?',
    'quality.vectorRaster.a': 'Dışa aktardığın boyuta kadar evet. {{fn}} piksel yerine şekil sakladığı için sonsuz ölçeklenir, ama {{tn}} sabit bir piksel ızgarasıdır ve sonradan o ızgaranın ötesinde büyütülürse bulanıklaşır. Dönüştürmeden önce gelişmiş ayarlardan gerçekten ihtiyacın olan genişliği ve yüksekliği belirle — görüntüleme boyutunun iki ya da üç katında dışa aktarmak, yüksek piksel yoğunluklu ekranlar için alışılmış yöntemdir. Özgün {{fn}} dosyasını sakla: her çözünürlükte yeniden dışa aktarabileceğin ana kopya odur.',
    'quality.docToTxt.q': '{{fn}} biçimini {{tn}} biçimine dönüştürürken biçimlendirmeyi yitirir miyim?',
    'quality.docToTxt.a': 'Evet ve bilerek — bir {{tn}} dosyası karakterler barındırır, başka bir şey değil. Yazı tipleri, renkler, görüntüler, tablolar, sütunlar ve sayfa sonları hepsi düşer; geri aldığın şey belgenin okunur metnidir, okuma sırasıyla. Arama yapmak, betik yazmak ya da metni başka bir programa vermek için tam olarak istediğin şey budur; tasarımı korumayı umuyorsan da tam olarak istemediğin şeydir. Şunu unutma: aslında taranmış bir görüntü olan bir {{fn}} dosyasında çıkarılacak hiç metin yoktur — onu bunun yerine OCR aracından geçir.',
    'quality.docToSheet.q': '{{fn}} dosyasından tablo çıkarımı ne kadar isabetli?',
    'quality.docToSheet.a': 'Çizgili ve düzenli sütunlu temiz tablolar — ekstreler, faturalar, dışa aktarılmış raporlar — güvenilir biçimde geçer ve her değer kendi hücresine düşer, böylece toplayıp sıralayabilirsin. Görünür çerçevesi olmayan tablolar, birden çok satıra yayılan hücreler ya da bir sayfa sonuyla bölünen sayılar, sonradan gözle kontrol etmeye değer durumlardır. {{fn}} tablo yapısını değil konumları sakladığı için, dönüştürmenin bir sütunun nerede bitip diğerinin nerede başladığını çıkarsaması gerekir.',
    'quality.docToReflow.q': 'Yerleşim, {{fn}} – {{tn}} dönüştürmesinden sağ çıkar mı?',
    'quality.docToReflow.a': 'Tam olarak değil ve asıl mesele de bu. {{fn}} metni sabit sayfa koordinatlarına çakar; {{tn}} ise okuyucunun ekranına ve yazı boyutuna uyacak biçimde yeniden akıtır, dolayısıyla sabit sayfa numaraları, üstbilgiler, altbilgiler ve çok sütunlu yerleşimler yeniden üretilmek yerine yeniden yorumlanır. Ana metin, başlıklar, paragraf sırası ve görüntüler iyi geçer. Çoğunlukla düzyazıdan oluşan belgeler harika dönüşür; sonradan bakmaya değer olanlar ağır tasarımlı sayfalar, formlar ve karmaşık tablolardır.',
    'quality.docToFixed.q': 'Biçimlendirmem {{tn}} içinde korunur mu?',
    'quality.docToFixed.a': 'Evet — bu yön güvenli olanıdır. {{tn}} sonunda işlenmiş sayfayı kaydeder, dolayısıyla yazı tipleri, boşluklar, tablolar, görüntüler ve sayfa sonları dizildikleri hâliyle donar ve her aygıtta ve yazıcıda aynı görünür. Bu aynı zamanda ödünün kendisidir: sonuç artık serbestçe düzenlenemez ve bir belgeyi göndermeden önce {{tn}} biçimine çevirmenin nedeni de genellikle tam olarak budur.',
    'quality.docToEditable.q': '{{fn}} – {{tn}} dönüştürmesi ne kadar isabetli?',
    'quality.docToEditable.a': 'Metin, başlıklar, listeler, görüntüler ve basit tablolar güvenilir biçimde geçer ve tümüyle düzenlenebilir kalır. {{fn}} yapı değil konum sakladığı için dönüştürmenin o yapıyı yeniden kurması gerekir; dolayısıyla ağır tasarımlı sayfalar — birden çok sütun, görüntülerin çevresinden akan metin, karmaşık iç içe tablolar — sonradan hafif bir toparlama isteyebilir. PDF hiç metin katmanı olmayan bir taramaysa bunun yerine OCR aracını kullan: orada olmayan metni aramak yerine görüntüdeki karakterleri tanır.',
    'quality.docGeneric.q': '{{fn}} biçimini {{tn}} biçimine dönüştürürken bir şey yitirir miyim?',
    'quality.docGeneric.a': 'Sözcükler, başlıklar, listeler ve görüntüler eksiksiz geçer. {{tn}}, {{fn}} biçiminden farklı bir biçimlendirme dağarcığına sahiptir, dolayısıyla çok özel bir tasarım yol boyunca yalınlaşabilir, ama içeriğin kendisi korunur.',
    'quality.archive.q': '{{fn}} arşivimin içindeki dosyalar değişir mi?',
    'quality.archive.a': 'Hayır. Arşiv biçimleri kayıpsız kaplardır: {{fn}} açılır ve aynı dosyalar bayt bayt {{tn}} olarak yeniden paketlenir. Yalnızca sıkıştırma yöntemi ve kap değişir. Değişen şey, arşivin kendi boyutudur — {{clause}}.',
    'quality.archive.clause.to7z': '7Z, LZMA sıkıştırması sayesinde genellikle ZIP’ten küçük bir arşiv verir',
    'quality.archive.clause.toZip': 'ZIP genellikle 7Z ya da RAR’dan biraz daha büyük çıkar; bu da ek yazılım olmadan her yerde açılabilmenin bedelidir',
    'quality.archive.clause.other': 'yeni biçim farklı sıkıştırır, dolayısıyla dosya boyutu iki yönden birine kayabilir',
    'quality.imageToDoc.q': 'Fotoğraflarım {{tn}} içinde kalite yitirir mi?',
    'quality.imageToDoc.a': 'Hayır. Her {{fn}} görüntüsü {{tn}} içine yeniden sıkıştırılmadan, olduğu gibi, sayfa başına bir tane yerleştirilir; dolayısıyla belgede gördüğün şey makineden çıkan şeydir. {{tn}} kabaca görüntülerin toplamı kadar olacaktır; e-postayla göndermeden önce bunu bilmekte yarar var — daha küçük olması gerekiyorsa sonucu PDF Sıkıştır aracından geçir.',
    'quality.toGif.q': 'GIF’im neden özgün {{fn}} dosyasından daha kötü görünüyor?',
    'quality.toGif.a': 'Çünkü GIF kare başına 256 renkle sınırlıdır. Bir video ya da fotoğraf milyonlarca renk içerir, dolayısıyla kodlayıcının bir palet seçip geri kalan her şeyi yaklaştırması gerekir; bu da geçişlerde ve gökyüzünde bantlanma olarak görünür. GIF ayrıca hiç ses izi taşımaz. İkisi de dönüştürmenin değil biçimin doğasıdır — klibi kısa tut, renk kaybı gömülü kendiliğinden oynamaktan daha ağır basıyorsa bir MP4 daha küçük boyutta çok daha iyi görünecektir.',
    'quality.lossyToLossless.q': '{{fn}} biçimini {{tn}} biçimine dönüştürmek kaliteyi artırır mı?',
    'quality.lossyToLossless.a': 'Hayır — ve bu, bu dönüştürme hakkındaki açık ara en yaygın yanlış anlamadır. {{fn}} kayıplıdır: kodlayıcısının attığı ayrıntılar kalıcı olarak gitmiştir ve hiçbir şey onları geri kuramaz. {{tn}} sana geriye kalan için kayıpsız bir kap verir; böylece dosya her sonraki kaydetme ya da düzenlemede bozulmayı bırakır. Bu, {{clause}} üzereyken gerçekten yararlıdır, ama çoktan yitmiş kaliteyi geri getirmez.',
    'quality.lossyToLossless.edit.audio': 'sesi düzenlemek, masterlamak ya da işlemek',
    'quality.lossyToLossless.edit.image': 'görüntüyü düzenlemek, rötuşlamak ya da birleştirmek',
    'quality.losslessToLossy.q': '{{fn}} biçimini {{tn}} biçimine dönüştürürken kalite yitirir miyim?',
    'quality.losslessToLossy.a.audio': 'Bir miktar ve bilerek — dosya böyle küçülür. {{tn}} kayıplıdır, dolayısıyla kodlayıcı en az fark edilir bulduğu bilgiyi atar. Makul ayarlarda farkı kulakla yakalamak çok güçtür ve boyutu sadakate değişmeyi yeğlersen gelişmiş ayarlardan bit hızını yükseltebilirsin. Özgün {{fn}} dosyanı sakla: ana kopya odur ve {{tn}} dosyasını sonradan yeniden kodlamak kaybı derinleştirir.',
    'quality.losslessToLossy.a.visual': 'Bir miktar ve bilerek — dosya böyle küçülür. {{tn}} kayıplıdır, dolayısıyla kodlayıcı en az fark edilir bulduğu bilgiyi atar. Makul ayarlarda farkı gözle yakalamak çok güçtür ve boyutu sadakate değişmeyi yeğlersen gelişmiş ayarlardan kalite değerini yükseltebilirsin. Özgün {{fn}} dosyanı sakla: ana kopya odur ve {{tn}} dosyasını sonradan yeniden kodlamak kaybı derinleştirir.',
    'quality.lossyToLossy.q': '{{fn}} biçimini {{tn}} biçimine dönüştürürken kalite yitirir miyim?',
    'quality.lossyToLossy.a.audio': 'Azıcık. İki biçim de kayıplıdır, dolayısıyla {{fn}} çözülüp sonra {{tn}} olarak yeniden kodlanır ve kayıplı kodlamanın her kuşağı biraz ayrıntı düşürür. Normal ayarlarda çoğu kişinin dinlerken fark ettiği bir şey değildir ve gelişmiş ayarlardan bit hızını yükseltebilirsin. Kaçınman gereken şey, aynı dosyayı defalarca ileri geri dönüştürmektir — kaybı duyulur kılan tam olarak budur.',
    'quality.lossyToLossy.a.visual': 'Azıcık. İki biçim de kayıplıdır, dolayısıyla {{fn}} çözülüp sonra {{tn}} olarak yeniden kodlanır ve kayıplı kodlamanın her kuşağı biraz ayrıntı düşürür. Normal ayarlarda çoğu kişinin fark ettiği bir şey değildir ve gelişmiş ayarlardan kaliteyi yükseltebilirsin. Kaçınman gereken şey, aynı dosyayı defalarca ileri geri dönüştürmektir — kaybı görünür kılan tam olarak budur.',
    'quality.losslessToLossless.q': '{{fn}} biçimini {{tn}} biçimine dönüştürürken kalite yitirir miyim?',
    'quality.losslessToLossless.a.plain': 'Hayır. Hem {{fn}} hem {{tn}} kayıpsızdır, dolayısıyla {{unit}} tam olarak korunur ve sonuç özgün dosyayla birebir aynıdır. Yalnızca dosya boyutu değişir. Daha sonra hiçbir bozulma olmadan geri dönüştürebilirsin.',
    'quality.losslessToLossless.a.bulky': 'Hayır. Hem {{fn}} hem {{tn}} kayıpsızdır, dolayısıyla {{unit}} tam olarak korunur ve sonuç özgün dosyayla birebir aynıdır. Yalnızca dosya boyutu değişir, genellikle çarpıcı biçimde aşağı doğru, çünkü {{fn}} verisini fiilen sıkıştırmadan saklar. Daha sonra hiçbir bozulma olmadan geri dönüştürebilirsin.',
    'quality.fallback.q': '{{fn}} biçimini {{tn}} biçimine dönüştürürken kalite yitirir miyim?',
    'quality.fallback.a': 'Sıradan dosyalarda sonuç, görsel ve işlevsel olarak özgün dosyaya denktir. İki biçimin farklı şeyleri desteklediği yerlerde dönüştürme, {{tn}} biçiminin temsil edebildiği her şeyi korur. Öntanımlı ödün istediğin ödün değilse gelişmiş ayarlardan kaliteyi yükseltebilirsin.',

    'relation.uncompressed.q': '{{tn}} dosyası neden {{fn}} dosyasından bu kadar büyük?',
    'relation.uncompressed.a': 'Çünkü {{tn}} sıkıştırılmamıştır. {{fn}} sesi veri atarak ve kalanı verimli kodlayarak küçültür; {{tn}} ise her örneği tam boyutta yazar ve bu da CD kalitesinde dakika başına kabaca 10 MB eder. Ona bir artış normaldir ve beklenir — kurgu yazılımının önce hiçbir şeyi çözmeden işleyebildiği bir dosyanın bedeli budur. Kayıpsız sesi yaklaşık yarı boyutta istiyorsan bunun yerine FLAC’e dönüştür.',
    'relation.extractAudio.q': 'Bu, videoyu da korur mu yoksa yalnızca sesi mi?',
    'relation.extractAudio.a': 'Yalnızca sesi. Ses izi {{fn}} dosyasından çıkarılır ve {{tn}} olarak kaydedilir; görüntü izi atılır, sonucun özgün boyutun küçük bir kesri olmasının nedeni de budur. Sesin kendisi yeniden kaydedilmez, dolayısıyla {{fn}} içinde sahip olduğu kaliteyi korur — düşük bit hızlı bir videodan yüksek bit hızlı ses çıkarılamaz.',
    'relation.videoContainer.q': '{{tn}} dosyam telefonlarda, televizyonlarda ve sosyal medyada oynar mı?',
    'relation.videoContainer.a.mp4': 'Bu dönüştürme tam olarak bunun içindir. H.264 videolu MP4, evrensel bir video biçimine en yakın şeydir: iPhone’lar, Android telefonlar, akıllı televizyonlar, her tarayıcı, Instagram, YouTube, TikTok ve her yaygın kurgu programı onu ek kodek olmadan kabul eder. {{fn}} sana sorun çıkaran biçimdi; MP4 çıkarmayan biçimdir.',
    'relation.videoContainer.a.other': '{{tn}}, MP4’ten daha uzmanlaşmıştır. {{note}} Amacın yalnızca “her yerde oynasın” ise MP4 daha güvenli seçimdir — belirli bir yazılım ya da donanım istediğinde {{tn}} biçimini seç.',
    'relation.alphaLost.q': '{{fn}} biçimi {{tn}} biçimine dönüşürken saydamlığa ne olur?',
    'relation.alphaLost.a': '{{tn}} biçiminin alfa kanalı yoktur, dolayısıyla saydam alanlar taşınamaz — dönüştürme sırasında düz bir arka planla (öntanımlı olarak beyazla) doldurulur. Saydam arka plan tasarımında gerçekten iş görüyorsa bunun yerine PNG ya da WebP biçimine dönüştür; ikisi de onu korur. Görüntü hiç saydamlığı olmayan bir fotoğrafsa bunun hiçbir önemi yoktur.',
    'relation.alphaGained.q': '{{fn}} biçimini {{tn}} biçimine dönüştürmek arka planı saydam yapar mı?',
    'relation.alphaGained.a': 'Hayır — ve pek çok kişi buna takılır. {{tn}} saydamlığı destekler, ama bir {{fn}} dosyasında taşınacak hiçbir saydamlık bilgisi yoktur, dolayısıyla arka plan tam olduğu gibi kalır. Dönüştürmenin sana verdiği şey, bir görüntü düzenleyicide arka planı kesip çıkardığında saydamlık taşıyabilecek bir dosya ve üstelik çalışırken bozulmayacak kayıpsız piksellerdir.',
    'relation.reflow.q': '{{tn}} benim okuyucumda çalışır mı?',
    'relation.reflow.a.epub': 'EPUB’u Apple Books, Kobo, Google Play Kitaplar, Calibre ve MOBI ya da AZW3 isteyen Kindle dışında fiilen her okuyucu okur (Kindle bugünlerde e-postayla EPUB da kabul ediyor). Metin yeniden aktığı için aygıtta yazı boyutunu, yana kaydırmak zorunda kalmadan değiştirebilirsin — bir {{fn}} dosyasını en baştan dönüştürmenin tüm nedeni de budur.',
    'relation.reflow.a.kindle': '{{tn}} biçimini, tasarlandığı Kindle aygıtları ve uygulamaları okur. Metin yeniden aktığı için aygıtta yazı boyutunu, yana kaydırmak zorunda kalmadan değiştirebilirsin — bir {{fn}} dosyasını en baştan dönüştürmenin tüm nedeni de budur.',

    'compatibility.q': '{{tn}} dosyasını sonrasında neyle açabilirim?',
    'compatibility.a': '{{note}} Dönüştürmenin kendisi için hiçbir şey kurmak gerekmez — sunucularımızda çalışır ve tamamlanan {{tn}} dosyası açmaya, düzenlemeye ya da iletmeye hazır olarak tarayıcına döner. Özgün {{fn}} dosyan asla değiştirilmez; her zaman yalnızca yeni bir dosya veririz.',
    'compatibility.noteFallback': '{{tn}} geniş biçimde desteklenir.',

    'shapeFaq.pdf-merge.q1': 'Birleştirme PDF’lerimin kalitesini düşürür mü?',
    'shapeFaq.pdf-merge.a1': 'Hayır. Sayfalar yeniden çizilmek yerine yeni belgeye oldukları gibi kopyalanır, dolayısıyla metin seçilebilir kalır ve görüntüler özgün çözünürlüğünü korur. Birleşik dosya kabaca özgün dosyaların toplamı kadardır — bunun önemi varsa sonradan PDF Sıkıştır aracından geçir.',
    'shapeFaq.pdf-merge.q2': 'Bir kerede kaç PDF birleştirebilirim ve sıra önemli mi?',
    'shapeFaq.pdf-merge.a2': 'Bir kerede ihtiyacın olduğu kadar dosya ekleyebilirsin ve sıra kesinlikle önemlidir: tamamlanan belge listede görünen sırayı izler ve birleştirmeden önce sürükleyerek yeniden düzenleyebilirsin. Önce sırayı belirle, sonra birleştir — bu, sonradan düzeltmekten hızlıdır.',
    'shapeFaq.pdf-split.q1': 'Hangi sayfaların çıkarılacağını nasıl seçerim?',
    'shapeFaq.pdf-split.a1': 'Onları sayfa aralığı kutusuna virgül ve tire kullanarak yaz: “1-3, 5, 7-10” sana birden üçe sayfaları, beşinci sayfayı ve yediden ona sayfaları tek bir çıktı belgesinde verir. Numaralar birden sayılarak PDF’in kendi sayfalarına gönderme yapar; bu her zaman sayfanın üzerinde basılı numara değildir.',
    'shapeFaq.pdf-split.q2': 'Bölme özgün PDF’i değiştirir mi?',
    'shapeFaq.pdf-split.a2': 'Hayır. Yüklediğin dosya asla değiştirilmez — çıkarılan sayfalar yeni bir belgeye yazılır ve özgün dosya dokunulmadan kalır, ardından sonuçla birlikte 24 saat içinde sunucularımızdan silinir.',
    'shapeFaq.pdf-compress.q1': 'PDF’im ne kadar küçülür?',
    'shapeFaq.pdf-compress.a1': 'Bu tümüyle içinde ne olduğuna bağlıdır. Taramaların ya da fotoğrafların ağır bastığı PDF’ler çoğu kez %50-90 küçülür, çünkü boyutun neredeyse tamamı oradadır. Yalnızca metin içeren bir PDF zaten derli topludur ve belki de neredeyse hiç değişmez. Metin ve vektör grafikleri iki durumda da keskin kalır — kazanç, görüntülerin yeniden kodlanmasından ve gereksiz gömülü verilerin atılmasından gelir.',
    'shapeFaq.pdf-compress.q2': 'Metin yine seçilebilir ve aranabilir kalır mı?',
    'shapeFaq.pdf-compress.a2': 'Evet. Sıkıştırma, gömülü görüntüler ve gereksiz iç veriler üzerinde çalışır; metin katmanı, yazı tipleri, bağlantılar ve yer imleri el değmeden kalır, dolayısıyla sıkıştırılmış dosyada tam eskisi gibi arayabilir, seçebilir ve kopyalayabilirsin.',
    'shapeFaq.pdf-compress-ai.q1': 'Bunun sıradan PDF sıkıştırmasından farkı ne?',
    'shapeFaq.pdf-compress-ai.a1': 'Sıradan sıkıştırma tüm dosyaya tek bir ayar uygular. Bu araç önce her sayfanın gerçekte ne içerdiğine bakar; böylece fotoğrafik görüntüler, düz şemalar ve yalnızca metin içeren sayfaların her biri, gözle görülür bozulma olmadan en çok yer kazandıran biçimde ele alınır. Karışık belgelerde bu genellikle aynı algılanan kalitede daha küçük bir dosya demektir.',
    'shapeFaq.pdf-compress-ai.q2': 'Metin yine seçilebilir ve aranabilir kalır mı?',
    'shapeFaq.pdf-compress-ai.a2': 'Evet. Metin katmanı, yazı tipleri, bağlantılar ve yer imleri korunur — yalnızca gömülü görüntüler ve gereksiz iç veriler yeniden kodlanır, dolayısıyla sıkıştırılmış PDF tümüyle aranabilir ve kopyalanabilir kalır.',
    'shapeFaq.pdf-rotate.q1': 'Bir PDF döndürülürken kalite yitirilir mi?',
    'shapeFaq.pdf-rotate.a1': 'Hiç. Döndürme, herhangi bir şeyi yeniden çizmek yerine dosyada kayıtlı sayfa geometrisini değiştirir; dolayısıyla metin vektör keskinliğinde kalır, görüntülere dokunulmaz ve dosya boyutu neredeyse kıpırdamaz. Daha sonra hiçbir birikimli hasar olmadan yeniden döndürebilirsin.',
    'shapeFaq.pdf-rotate.q2': 'Yalnızca bazı sayfaları döndürebilir miyim?',
    'shapeFaq.pdf-rotate.a2': 'Seçtiğin döndürme — 90°, 180° ya da 270° — belgeye uygulanır. Farklı sayfalar farklı yönlerde ters duruyorsa alışılmış yol, PDF’i bölmek, her parçayı gereken açıyla döndürmek ve sonuçları PDF Birleştir aracıyla yeniden bir araya getirmektir.',
    'shapeFaq.pdf-protect.q1': 'Parolayı unutursam ne olur?',
    'shapeFaq.pdf-protect.a1': 'Dosya açılamaz. Şifreleme PDF’in kendisine uygulanır, dolayısıyla ne sıfırlama bağlantısı ne de bir arka kapı vardır — ne senin için ne bizim için. Belgeyi iletmeden önce parolayı güvenli bir yerde sakla ve dosyadan farklı bir kanaldan gönder.',
    'shapeFaq.pdf-protect.q2': 'Koruma ne kadar güçlü?',
    'shapeFaq.pdf-protect.a2': 'PDF, biçime gömülü sektör standardıyla şifrelenir; dolayısıyla içeriği, standarda uyan hiçbir okuyucu tarafından parolasız okunamaz. Uygulamadaki zayıf nokta hiçbir zaman algoritma değil, parolanın kendisidir — kısa ya da bariz bir parola çabuk tahmin edilir, bu yüzden gerçekten gizli olan her şey için uzun bir parola kullan.',
    'shapeFaq.pdf-unlock.q1': 'Bu, bilmediğim bir parolayı kaldırabilir mi?',
    'shapeFaq.pdf-unlock.a1': 'Hayır. Geçerli parolayı vermen gerekir; araç şifrelemeyi kırmak yerine dosyayı onunla çözer. Sana ait olan ya da açmaya yetkin olduğun belgeler içindir — örneğin kendi bankandan bir ekstre — kısıtlamanın yalnızca yolunu tıkadığı durumlar için.',
    'shapeFaq.pdf-unlock.q2': 'Sonrasında dosyayla ne yapabilirim?',
    'shapeFaq.pdf-unlock.a2': 'Korumanın engellediği her şeyi: sormadan açmak, yazdırmak, içinden metin kopyalamak ve başka yazılımlarda düzenlemek. Sayfa içeriğinin kendisi değişmez — yalnızca şifreleme katmanı ve onun kullanım kısıtları kaldırılır.',
    'shapeFaq.metadata.q1': 'Bu, dosyamı herhangi bir biçimde değiştirir mi?',
    'shapeFaq.metadata.a1': 'Hayır. Dosya dönüştürülmez, okunur — hiçbir şey geri yazılmaz ve ekranda görünen bilgi dışında yeni bir şey üretilmez. Emin olmadığın bir dosyaya doğrultabileceğin, buradaki en güvenli araçtır.',
    'shapeFaq.metadata.q2': 'Ne tür bilgiler göreceğim?',
    'shapeFaq.metadata.a2': 'Dosyaya bağlı. Görüntüler ölçüleri, renk derinliğini ve makine modeli, objektif, pozlama gibi EXIF verilerini, makine kaydettiyse GPS koordinatlarını gösterir. Ses süreyi, bit hızını, örnekleme hızını ve kanal sayısını gösterir. Video bunlara kodek, çözünürlük ve kare hızını ekler. Belgeler sayfa sayısını, yazarı, üreticiyi ve oluşturma tarihini gösterir.',
    'shapeFaq.ocr.q1': 'Metin tanıma ne kadar isabetli?',
    'shapeFaq.ocr.a1': 'Basılı metnin makul çözünürlükte temiz ve düz bir taraması çok isabetli tanınır. İsabet; eğri ya da bulanık sayfalarda, düşük karşıtlıklı fotoğraflarda, alışılmadık yazı tiplerinde ve el yazısında düşer. Doğru dili seçmenin önemi vardır, çünkü tanıma belirsiz karakterleri çözmek için onu kullanır.',
    'shapeFaq.ocr.q2': 'Aranabilir PDF ile düz metin çıktısı arasındaki fark ne?',
    'shapeFaq.ocr.a2': 'Aranabilir PDF, özgün sayfa görüntüsünü tam göründüğü gibi korur ve altına görünmez bir metin katmanı ekler; böylece belge değişmemiş görünür ama artık aranabilir ve içinden kopyalanabilir — arşivleme için istediğin budur. Düz metin yerleşimi atar ve sana yalnızca sözcükleri verir; düzenleme, betik yazma ya da başka bir programa aktarma için istediğin de budur.',
    'shapeFaq.tts.q1': 'Sesler ne kadar doğal duyuluyor?',
    'shapeFaq.tts.a1': 'Bunlar eski, parçaları birbirine eklenmiş konuşma sentezi değil sinirsel seslerdir; dolayısıyla sözcük sözcük okumak yerine cümle düzeyinde tonlama ve doğal duraklar taşırlar. Nötrden sıcağa ve buyurgana altı ses vardır ve konuşma hızı ayarlanabilir. Noktalama sanılandan çok daha önemlidir: virgüller ve noktalar tonlamayı biçimlendirir, dolayısıyla iyi noktalanmış metin gözle görülür ölçüde daha iyi okunur.',
    'shapeFaq.tts.q2': 'Bir kerede ne kadar metin dönüştürebilirim?',
    'shapeFaq.tts.a2': 'Dönüştürme başına en çok 4096 karakter — kabaca 600 ila 700 sözcük, yani yaklaşık beş dakikalık konuşma. Daha uzun metinlerde, bölüm ya da kesim başlığı gibi doğal bir yerden ayır ve her parçayı ayrı ayrı dönüştür; ses ve hız ayarları çalıştırmalar arasında aynı kalır, dolayısıyla parçalar temiz birleşir.',
    'shapeFaq.stt.q1': 'Döküm ne kadar isabetli?',
    'shapeFaq.stt.a1': 'Makul ölçüde sessiz bir ortamda net konuşma, geniş bir aksan yelpazesinde de olmak üzere çok isabetli dökülür. Yoğun arka plan gürültüsünde, birkaç kişi üst üste konuştuğunda ya da çok uzmanlaşmış jargon ve özel adlarda isabet düşer. Konuşulan dili kendiliğinden algılamaya bırakmak yerine belirlemek gözle görülür ölçüde yardımcı olur.',
    'shapeFaq.stt.q2': 'Doğrudan mikrofonumdan kayıt yapabilir miyim?',
    'shapeFaq.stt.a2': 'Evet — bu sayfadaki kaydedici sesi doğrudan tarayıcıda yakalar; bu da çoğu zaman önce bir kayıt uygulaması aramaktan hızlıdır. Tarayıcın ilk seferinde mikrofon izni isteyecektir. Var olan bir dosyayı da yükleyebilirsin ve döküm sayfada görünür, böylece TXT ya da DOCX olarak indirmeden önce okuyabilirsin.',
    'shapeFaq.subtitle.q1': 'Üretilen altyazılar ne kadar isabetli?',
    'shapeFaq.subtitle.a1': 'Net konuşma, aksanla bile olsa çok isabetli dökülür. Fon müziği, üst üste konuşmalar ve uzmanlık terimleri hataların sızdığı yerlerdir; konuşulan dili kendiliğinden algılatmak yerine belirlemek yardımcı olur. Çıktı düz metin bir altyazı dosyasıdır, dolayısıyla arada bir sözcüğü düzeltmek herhangi bir metin düzenleyicide saniyeler alır.',
    'shapeFaq.subtitle.q2': 'SRT mi VTT mi seçmeliyim?',
    'shapeFaq.subtitle.a2': 'SRT daha güvenli öntanımlı seçimdir: YouTube, Vimeo, Premiere, Final Cut, VLC ve fiilen her oynatıcı onu kabul eder. Altyazılar bir sitedeki HTML5 video oynatıcısına gidecekse VTT’yi seç, çünkü WebVTT tarayıcının kendi altyazı izinin beklediği biçimdir ve SRT’nin ifade edemediği biçemlendirme ile konumlandırmayı destekler.',
    'shapeFaq.soon.q1': 'Bu ne zaman kullanılabilir olacak?',
    'shapeFaq.soon.a1': 'Üzerinde etkin biçimde çalışılıyor. Araç burada görünecek ve hazır olur olmaz dosya kabul etmeye başlayacak — senin tarafında kurulacak ya da açılacak bir şey yok.',
    'shapeFaq.soon.q2': 'Bu arada neyi kullanabilirim?',
    'shapeFaq.soon.a2': 'Dönüştürücünün geri kalanı tümüyle kullanılabilir: belgeler, görüntüler, ses, video, arşivler, GIF’ler ve PDF araç takımının hepsi bugün çalışıyor; OCR, döküm ve altyazı için akıllı işlevler de öyle.',
    'shapeFaq.compress.q1': 'Sıkıştırılmış dosya yine {{fn}} olacak mı?',
    'shapeFaq.compress.a1': 'Evet — biçim değişmez, yalnızca boyut değişir. İndirdiğin şey, özgün dosyanın açıldığı her yerde açılan sıradan bir {{fn}} dosyasıdır.{{alpha}} Ne kadar kazanacağın kaynak malzemeye bağlıdır: {{source}}.',
    'shapeFaq.compress.alpha': ' Saydamlık ve canlandırma korunur.',
    'shapeFaq.compress.source.png': 'ekran görüntüleri ve düz arayüz grafikleri çarpıcı biçimde sıkışır, PNG olarak kaydedilmiş fotoğraflar ise daha azını verir',
    'shapeFaq.compress.source.gif': 'uzun canlandırmalar ve hareketli görüntüler en çok sıkışır, çünkü atılacak daha çok yineleme vardır',
    'shapeFaq.compress.source.other': 'fotoğraflar iyi sıkışır, zaten ağır sıkıştırılmış görüntülerin ise verecek daha azı kalmıştır',
    'shapeFaq.compress.q2': 'Dosya ne kadar küçülür?',
    'shapeFaq.compress.a2': 'Genellikle özgün boyutun üçte biri ile onda biri arasında bir yerde; bu tümüyle dosyanın ne içerdiğine ve başlangıçta nasıl kaydedildiğine bağlıdır. Dönüştürme bittiğinde sayfa önceki ve sonraki boyutu yan yana gösterir, böylece tahmin etmek yerine gerçek kazancı görürsün.',
    'shapeFaq.hub.q1': 'Hangi biçimler arasında dönüştürebilirim?',
    'shapeFaq.hub.a1': 'Girdi: {{inputs}}. Çıktı: {{outputs}}. Herhangi bir girdi herhangi bir çıktıya gidebilir, dolayısıyla her birleşim için ayrı bir sayfa bulman gerekmez — dosyayı seç, hedef biçimi seç, dönüştür.',
    'shapeFaq.hub.q2': 'Kalite yitirir miyim?',
    'shapeFaq.hub.a2': 'Bu çifte bağlı. Kayıpsız bir biçime geçmek her şeyi korur ama daha büyük bir dosya üretir; sıkıştırılmış bir biçime geçmek boyut karşılığında bilerek veri atar ve gelişmiş ayarlar bu ödünde nerede duracağına karar vermeni sağlar. İki sıkıştırılmış biçim arasında dönüştürmek her seferinde biraz ayrıntı düşürür, dolayısıyla özgün dosyayı ana kopya olarak saklamakta yarar var.',
    'shapeFaq.hub-extract.q1': 'Video da korunur mu?',
    'shapeFaq.hub-extract.a1': 'Hayır — yalnızca ses. Ses izi videodan çıkarılıp ayrı kaydedilir, sonucun özgün dosya boyutunun küçük bir kesri olmasının nedeni de budur. Ses yeniden kaydedilmez, dolayısıyla videonun içinde zaten sahip olduğu kaliteyi korur; düşük bit hızlı bir klipten yüksek bit hızlı ses çıkarılamaz.',
    'shapeFaq.hub-extract.q2': 'Hangi çıkış biçimini seçmeliyim?',
    'shapeFaq.hub-extract.a2': 'En geniş uyumluluk için MP3 — her telefonda, araç ses sisteminde ve oynatıcıda çalar. Hedef bir Apple aygıtı ya da çağdaş bir uygulamaysa AAC ya da M4A, çünkü aynı bit hızında biraz daha iyi duyulurlar. WAV ya da FLAC yalnızca sesi düzenleyecekseniz, çünkü ikisi de kayıpsız ve buna uygun biçimde hacimlidir.',
    'shapeFaq.hub-gif.q1': 'GIF neden özgün dosyadan daha kötü görünüyor?',
    'shapeFaq.hub-gif.a1': 'Çünkü GIF kare başına yalnızca 256 renge izin verir, oysa video ve fotoğraflar milyonlarca renk içerir. Kodlayıcı bir palet seçer ve geri kalanı yaklaştırır; bu da geçişlerde ve gökyüzünde bantlanma olarak görünür. GIF ayrıca hiç ses taşımaz. İki sınır da dönüştürmenin değil biçimin doğasıdır.',
    'shapeFaq.hub-gif.q2': 'GIF dosyam neden bu kadar büyük?',
    'shapeFaq.hub-gif.a2': 'GIF, çağdaş video kodeklerinden çok daha verimsiz sıkıştırır; dolayısıyla dosya boyutu süre, çözünürlük ve kare hızıyla birlikte hızla büyür. Birkaç saniye en ideal aralıktır. Sonuç fazla ağırsa klibi kısalt; boyut gömülü kendiliğinden oynamaktan daha ağır basıyorsa bir MP4 aynı canlandırmayı boyutun küçük bir kesrinde gösterecektir.',
    "shapeFaq.rename.q1": "{{fn}} dosyasını {{tn}} biçimine dönüştürmek fotoğrafımın kalitesini düşürür mü?",
    "shapeFaq.rename.a1": "Hayır. {{fn}} ve {{tn}}, aynı görsel biçiminin uzantısının iki farklı yazılışıdır; bu yüzden hiçbir şey çözülmez ya da yeniden sıkıştırılmaz. Dosyan bayt bayt kopyalanır ve yalnızca yeni uzantıyı alır; yani sonuç, EXIF verileri dahil, özgün dosyayla birebir aynıdır.",
    "shapeFaq.rename.q2": "{{fn}} ve {{tn}} aynı biçimse neden dönüştürmeliyim?",
    "shapeFaq.rename.a2": "Çünkü bazı yazılımlar içeriğe değil uzantıya bakar. Yükleme formları, eski programlar ve bazı fotoğraf hizmetleri iki yazılıştan yalnızca birini kabul edip diğerini reddeder, oysa içerideki görsel aynıdır. Dosyanın kabul edilmesi için uzantıyı değiştirmek yeterlidir.",
    "intro.lead.pdf-images": "PDF’den görsellere aracı, bir PDF’nin her sayfasını sayfa sırasına göre numaralanmış ayrı bir JPG veya PNG görsele dönüştürür; böylece her sayfa ayrı ayrı paylaşılabilir, gönderilebilir ya da düzenlenebilir. PDF sayfalarını sabit düzenli tek bir dosyada birbirine kilitler; işte bu yüzden yalnızca görsellere izin verilen yerlerde paylaşılamaz.",
    "steps.pdf-images.1": "PDF’ini bu sayfanın üstündeki yükleme alanına bırak ya da aygıtından dosyayı seçmek için üzerine tıkla.",
    "steps.pdf-images.2": "Fotoğraflara ve sosyal medyaya uygun daha küçük dosyalar için JPG’yi, keskin metin ve grafikler için PNG’yi seç, ardından Dönüştür’e tıkla.",
    "steps.pdf-images.3": "Her sayfayı tek tek indir ya da tüm sayfaları bir kerede ZIP olarak al. Bağlantılar 24 saat açık kalır, ardından her şey silinir.",
    "shapeFaq.pdf-images.q1": "PDF’imin her sayfası ayrı bir görsel olur mu?",
    "shapeFaq.pdf-images.a1": "Evet. Her sayfa kendi görseli olarak işlenir ve sırayla numaralanır — page-01, page-02 ve böyle devam eder — yani on sayfalık bir PDF sana on görsel verir. Onları tek tek ya da tek bir ZIP dosyasında birlikte indirebilirsin; PDF’nin tamamı, kaç sayfa olursa olsun, yalnızca tek bir krediye mal olur.",
    "shapeFaq.pdf-images.q2": "Görseller Instagram ve diğer sosyal medya için uygun mu?",
    "shapeFaq.pdf-images.a2": "Evet. Sayfalar yüksek çözünürlükte işlenir, bu yüzden Instagram, LinkedIn ya da Facebook onları küçülttükten sonra da net kalır. Dikey sayfalar Instagram kaydırmalı gönderileri için iyi çalışır; en iyi uyum için slaytları PDF’yi dışa aktarmadan önce 4:5 ya da kare biçimde tasarla ve yüklemeler küçük kalsın diye JPG’yi seç.",
    "intro.lead.collage": "Fotoğraf kolajı birkaç fotoğrafı tek bir görselde birleştirir: her resim yeniden boyutlandırılıp eşit aralıklarla düzenli bir ızgaraya yerleştirilir; böylece her şey tek tek kaydırılmak yerine bir bakışta görülür. Otomatik bir düzen ya da sabit 2×2 veya 3×3 ızgara seç ve tek bir JPG veya PNG al.",
    "steps.collage.1": "Yükleme alanına bırakarak ya da tıklayıp seçerek 2 ile 16 arasında fotoğraf ekle, ardından sıralarını belirlemek için onları listede sürükle.",
    "steps.collage.2": "Bir düzen seç — Otomatik, 2×2 ya da 3×3 —, fotoğrafların karelerini doldurmasını mı yoksa tamamen görünmesini mi istediğine karar ver ve JPG veya PNG’yi seç.",
    "steps.collage.3": "Kolaj oluştur’a tıkla, önizlemeyi kontrol et ve tamamlanan görseli indir. Görsel 24 saat boyunca erişilebilir kalır.",
    "shapeFaq.collage.q1": "Fotoğraflarım kolajda kırpılacak mı?",
    "shapeFaq.collage.a1": "Bu sana kalmış. “Her kareyi doldur” seçeneğinde her fotoğraf, resmin en ilgi çekici kısmı ortalanarak kare biçiminde kırpılır ve en düzenli ızgara elde edilir. “Fotoğrafın tamamını göster” seçeneğinde hiçbir şey kesilmez: fotoğraf sığacak şekilde küçültülür ve kalan boşluk beyazla doldurulur.",
    "shapeFaq.collage.q2": "Bir kolaja kaç fotoğraf koyabilirim?",
    "shapeFaq.collage.a2": "Otomatik düzenle en az 2, en fazla 16 fotoğraf; bu düzen eklediğin fotoğraf sayısı için kareye en yakın ızgarayı seçer. 2×2 ızgara en fazla 4, 3×3 ızgara en fazla 9 fotoğraf alır. Her kolaj, içinde kaç fotoğraf olursa olsun, bir krediye mal olur.",
    "intro.rename": "{{fn}} ve {{tn}}, iki farklı dosya uzantısı altındaki aynı görsel biçimidir; bu yüzden bu dönüştürme yalnızca adı değiştirir: resim bayt bayt kopyalanır, yeniden sıkıştırma ve kalite kaybı olmaz. {{reason}}",
    "intro.lead.social-resize": "Sosyal medya için yeniden boyutlandırma aracı, bir fotoğrafı veya videoyu platformun beklediği biçime tam olarak yeniden çerçeveler: TikTok, Reels, Stories ve Shorts için 9:16, kare akış gönderileri için 1:1, dikey Instagram gönderileri için 4:5 ve YouTube için 16:9. Fotoğraflar en ilgi çekici kısımlarının çevresinde kırpılabilir ya da bulanık veya düz bir arka plan üzerinde tamamen gösterilebilir; videolar ise ortadan kırpılır ya da siyah şeritlerle sığdırılır ve MP4 olarak kaydedilir.",
    "steps.social-resize.1": "Fotoğrafını veya videonu bu sayfanın üstündeki yükleme alanına bırak ya da aygıtından bir dosya seçmek için üzerine tıkla.",
    "steps.social-resize.2": "Platform biçimini seç, ardından çerçeveyi dolduracak şekilde mi kırpacağına yoksa resmin tamamını mı sığdıracağına karar ver.",
    "steps.social-resize.3": "Dönüştür’e tıkla ve yeniden çerçevelenen fotoğrafı veya videoyu indir. İndirme bağlantısı 24 saat açık kalır.",
    "shapeFaq.social-resize.q1": "Fotoğrafımı kırpmalı mıyım, yoksa tamamını mı sığdırmalıyım?",
    "shapeFaq.social-resize.a1": "Konu yeni biçimin içine rahatça sığıyorsa kırp: görsel tüm ekranı doldurur ve platforma özgü görünür; kırpma da resmin en ilgi çekici kısmına ortalanır. Hiçbir şeyin kesilmemesi gerektiğinde, örneğin bir grup fotoğrafında ya da kenarlarına yakın metin bulunan bir afişte, görselin tamamını sığdır; resmin tamamı kendi bulanık kopyası ya da beyaz veya siyah bir arka plan üzerinde görünür kalır.",
    "shapeFaq.social-resize.q2": "Videoları da yeniden boyutlandırabilir miyim, ücreti ne kadar?",
    "shapeFaq.social-resize.a2": "Evet. 3 dakikaya ve 500 MB'a kadar olan MP4, MOV, M4V, 3GP ve WebM klipleri 1080 × 1920, 1080 × 1080, 1080 × 1350 veya 1920 × 1080 piksel boyutunda H.264 MP4'e dönüştürülür. Kırpma karenin ortasına göre yapılır, sığdırma ise siyah şeritler ekler. Video işlemek bir fotoğrafa göre çok daha fazla işlem süresi gerektirdiği için bir video 1 yerine 2 kredi kullanır; dönüştürme başarısız olursa krediler iade edilir.",
    "intro.lead.profile-picture": "Profil fotoğrafı oluşturucu, bir fotoğrafı yüze ya da ana konuya ortalanmış bir kareye kırpar ve 400, 800 veya 1080 piksellik standart bir avatar boyutuna ölçekler. Bunun yerine yuvarlak sürümü seçersen köşeler şeffaf olur, böylece avatar her arka planda doğru görünür.",
    "steps.profile-picture.1": "Kendi fotoğrafını, logonu ya da markanı yükleme alanına bırak veya bir tane seçmek ya da fotoğraf çekmek için üzerine tıkla.",
    "steps.profile-picture.2": "Kare ya da daire ile bir boyut seç — 800 × 800 piksel tüm büyük platformlara uyar.",
    "steps.profile-picture.3": "Dönüştür’e tıkla, kare ve yuvarlak önizlemeyi kontrol et, ardından yeni profil fotoğrafını indir.",
    "shapeFaq.profile-picture.q1": "Kare mi yoksa yuvarlak bir profil fotoğrafı mı yüklemeliyim?",
    "shapeFaq.profile-picture.a1": "Genellikle kare olanı. Instagram, Facebook, LinkedIn, X ve YouTube’un hepsi kare bir görsel ister ve onu kendisi daire biçiminde keser; yuvarlak önizleme bunun nasıl görüneceğini sana gösterir. Şeffaf köşeli yuvarlak PNG ise dosyayı tam olduğu gibi gösteren yerler içindir: web siteleri, e-posta imzaları, sunumlar ya da sohbet uygulamaları gibi.",
    "shapeFaq.profile-picture.q2": "Hangi boyutu seçmeliyim?",
    "shapeFaq.profile-picture.a2": "800 × 800 piksel güvenli seçimdir: herhangi bir platformun profil fotoğrafını gösterdiğinden daha net, ama yine de küçük bir dosya. 400 × 400 LinkedIn, X ve Facebook için yeterlidir; 1080 × 1080 ise yüksek çözünürlüklü ekranlar ya da baskıda yeniden kullanım için ekstra ayrıntı sağlar.",
    "intro.lead.social-compress": "Sosyal medya için görsel sıkıştırıcı, bir fotoğrafı platformun gerçekte gösterdiği en büyük boyuta küçültür — Instagram için 1080 piksel, Facebook için 2048, X için 4096 —, her uygulamanın beklediği sRGB renklere dönüştürür ve yüksek kaliteli bir JPG olarak kaydeder. Zaten daha küçük olan resimler asla büyütülmez.",
    "steps.social-compress.1": "Fotoğrafını bu sayfanın üstündeki yükleme alanına bırak ya da bir tane seçmek için üzerine tıkla. Aynı anda birden fazla fotoğraf ekleyebilirsin.",
    "steps.social-compress.2": "Paylaşım yapacağın platformu seç ve Dönüştür’e tıkla.",
    "steps.social-compress.3": "Optimize edilmiş JPG’yi indir ve platforma yükle. Bağlantı 24 saat açık kalır.",
    "shapeFaq.social-compress.q1": "Daha küçük bir dosya yüklendikten sonra neden daha iyi görünür?",
    "shapeFaq.social-compress.a1": "Çünkü platformun onu artık işlemesi gerekmez. Bir fotoğraf platformun gösterdiğinden büyük olduğunda otomatik olarak küçültülür ve çoğu zaman düşük kalitede yeniden sıkıştırılır; silik ayrıntılar ve kare kare gökyüzü buradan gelir. Zaten doğru boyutta ve sRGB renklerle gelen bir fotoğraf ise neredeyse tam gönderdiğin gibi saklanır.",
    "shapeFaq.social-compress.q2": "Bunun normal Görsel sıkıştırıcıdan farkı ne?",
    "shapeFaq.social-compress.a2": "Normal Görsel sıkıştırıcı dosyanın boyutlarını ve biçimini korur, yalnızca verileri sıkıştırır. Bu araç ise fotoğrafı ayrıca platformun gösterim boyutuna yeniden boyutlandırır ve sRGB bir JPG’ye dönüştürür; sosyal medyada farkı yaratan da budur. PNG’nin şeffaf alanları beyaz olur, çünkü JPG’de şeffaflık yoktur.",
  },
};
